import React,{useMemo,useState}from'react';
import{Binary,Copy,FileCode,Globe,Upload}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{base64ToBytes,base64ToUtf8,base64UrlToUtf8,buildQueryString,makeDataUrl,parseDataUrl,parseQueryString,parseUrlDetailed,urlDecodeComponent,urlDecodeFull,urlEncodeComponent,urlEncodeFull,urlEncodeRfc3986Component,utf8ToBase64,utf8ToBase64Url,type QueryParamItem}from'../../utilities/encoding-tools';
interface Props{initialText?:string}
export const EncodingTools:React.FC<Props>=({initialText=''})=>{
 const[tab,setTab]=useState<'url'|'params'|'base64'|'binary'>('url');const[urlInput,setUrlInput]=useState(initialText||'https://example.com/search?q=hello world#results');const[urlMode,setUrlMode]=useState<'component'|'rfc3986'|'full'>('component');const[queryInput,setQueryInput]=useState('https://example.com/api?flag&tag=one&tag=two#section');const[parsed,setParsed]=useState(()=>parseQueryString('https://example.com/api?flag&tag=one&tag=two#section'));const[b64Input,setB64Input]=useState('Tiny Tools 🚀');const[b64Mode,setB64Mode]=useState<'standard'|'url'>('standard');const[b64Output,setB64Output]=useState('');const[binaryBytes,setBinaryBytes]=useState<Uint8Array|null>(null);const[binaryName,setBinaryName]=useState('');const[binaryMime,setBinaryMime]=useState('application/octet-stream');const[binaryB64,setBinaryB64]=useState('');const[error,setError]=useState('');
 const urlOutput=useMemo(()=>urlMode==='component'?urlEncodeComponent(urlInput):urlMode==='rfc3986'?urlEncodeRfc3986Component(urlInput):urlEncodeFull(urlInput),[urlInput,urlMode]),inspector=useMemo(()=>parseUrlDetailed(urlInput),[urlInput]);
 const rebuild=(next:QueryParamItem[])=>{const p={...parsed,params:next};setParsed(p);setQueryInput(buildQueryString(p.baseUrl,p.params));};
 const encodeB64=()=>{const r=b64Mode==='url'?utf8ToBase64Url(b64Input):utf8ToBase64(b64Input);setError(r.error||'');setB64Output(r.result||'');};const decodeB64=()=>{const r=b64Mode==='url'?base64UrlToUtf8(b64Input):base64ToUtf8(b64Input);setError(r.error||'');setB64Output(r.result||'');};
 const loadBinary=async(file:File)=>{const bytes=new Uint8Array(await file.arrayBuffer());setBinaryBytes(bytes);setBinaryName(file.name);setBinaryMime(file.type||'application/octet-stream');const r=makeDataUrl(bytes,file.type||'application/octet-stream');setBinaryB64(r.slice(r.indexOf(',')+1));};
 const restoreBinary=()=>{const result=base64ToBytes(binaryB64);if(!result.result){setError(result.error||'Invalid Base64');return;}setBinaryBytes(result.result);setError('');const blob=new Blob([result.result],{type:binaryMime}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=binaryName||'decoded.bin';a.click();URL.revokeObjectURL(u);};
 const output=tab==='url'?urlOutput:tab==='params'?queryInput:tab==='base64'?b64Output:binaryB64;
 return <ToolShell toolId="encoding-tools" title="URL & Base64 Tools" description="Standards-aware URL, query, Base64/Base64URL, data-URL and binary-file encoding utilities." category="developer" relatedToolIds={['json-formatter','regex-tester','text-cleaner']} outputToTransfer={output}><div className="space-y-5"><div className="flex flex-wrap border-b">{([['url','URL'],['params','Query params'],['base64','Base64 / Base64URL'],['binary','Binary file']] as const).map(([id,label])=><button key={id} onClick={()=>setTab(id)} className={`px-3 py-2 text-xs border-b-2 ${tab===id?'border-blue-600 text-blue-600':'border-transparent'}`}>{label}</button>)}</div>
 {error&&<div className="p-2 text-xs border border-red-300 bg-red-50 dark:bg-red-950/30 rounded">{error}</div>}
 {tab==='url'&&<div className="space-y-3"><div className="flex gap-2"><select value={urlMode} onChange={e=>setUrlMode(e.target.value as typeof urlMode)} className="p-2 text-xs border rounded bg-white dark:bg-neutral-900"><option value="component">Component</option><option value="rfc3986">RFC 3986 strict</option><option value="full">Full URI</option></select><button onClick={()=>{const r=urlMode==='full'?urlDecodeFull(urlInput):urlDecodeComponent(urlInput);if(r.result!==undefined)setUrlInput(r.result);else setError(r.error||'Decode failed');}} className="px-3 py-2 text-xs border rounded">Decode in place</button></div><div className="grid lg:grid-cols-2 gap-3"><textarea value={urlInput} onChange={e=>setUrlInput(e.target.value)} rows={8} className="p-3 border rounded font-mono text-sm bg-white dark:bg-neutral-900"/><textarea readOnly value={urlOutput} rows={8} className="p-3 border rounded font-mono text-sm bg-neutral-50 dark:bg-neutral-950"/></div><div className="p-3 border rounded-xl"><h3 className="text-sm font-semibold flex gap-1"><Globe className="w-4 h-4"/>URL inspector</h3>{inspector.valid?<div className="grid sm:grid-cols-3 gap-2 mt-2 text-xs font-mono"><span>scheme {inspector.protocol}</span><span>host {inspector.hostname}</span><span>port {inspector.port||'default'}</span><span className="sm:col-span-2 break-all">path {inspector.pathname}</span><span>credentials {inspector.passwordPresent?'present':'none'}</span><span className="sm:col-span-3 break-all">origin {inspector.origin}</span></div>:<p className="text-xs text-neutral-500 mt-1">Input is not an absolute URL; encoding still works as text.</p>}</div></div>}
 {tab==='params'&&<div className="space-y-3"><input value={queryInput} onChange={e=>{setQueryInput(e.target.value);setParsed(parseQueryString(e.target.value));}} className="w-full p-2 border rounded font-mono text-xs bg-white dark:bg-neutral-900"/><div className="space-y-2">{parsed.params.map(p=><div key={p.id} className="grid grid-cols-[1fr_1fr_auto] gap-2"><input value={p.key} onChange={e=>rebuild(parsed.params.map(x=>x.id===p.id?{...x,key:e.target.value}:x))} className="p-2 border rounded text-xs bg-white dark:bg-neutral-900"/><input value={p.value} disabled={p.hasEquals===false} onChange={e=>rebuild(parsed.params.map(x=>x.id===p.id?{...x,value:e.target.value}:x))} className="p-2 border rounded text-xs bg-white dark:bg-neutral-900"/><label className="text-[11px] flex items-center gap-1"><input type="checkbox" checked={p.hasEquals!==false} onChange={e=>rebuild(parsed.params.map(x=>x.id===p.id?{...x,hasEquals:e.target.checked}:x))}/>=</label></div>)}</div><button onClick={()=>rebuild([...parsed.params,{id:`param-${Date.now()}`,key:'key',value:'value',hasEquals:true}])} className="px-3 py-1.5 text-xs border rounded">Add parameter</button></div>}
 {tab==='base64'&&<div className="space-y-3"><div className="flex gap-2"><select value={b64Mode} onChange={e=>setB64Mode(e.target.value as typeof b64Mode)} className="p-2 text-xs border rounded bg-white dark:bg-neutral-900"><option value="standard">Standard Base64</option><option value="url">Base64URL (unpadded)</option></select><button onClick={encodeB64} className="px-3 py-2 text-xs bg-blue-600 text-white rounded">Encode</button><button onClick={decodeB64} className="px-3 py-2 text-xs border rounded">Decode</button></div><div className="grid lg:grid-cols-2 gap-3"><textarea value={b64Input} onChange={e=>setB64Input(e.target.value)} rows={10} className="p-3 border rounded font-mono text-sm bg-white dark:bg-neutral-900"/><textarea value={b64Output} onChange={e=>setB64Output(e.target.value)} rows={10} className="p-3 border rounded font-mono text-sm bg-neutral-50 dark:bg-neutral-950"/></div></div>}
 {tab==='binary'&&<div className="space-y-3"><label className="inline-flex px-3 py-2 text-xs bg-blue-600 text-white rounded cursor-pointer gap-1"><Upload className="w-3 h-3"/>Binary file<input hidden type="file" onChange={e=>e.target.files?.[0]&&void loadBinary(e.target.files[0])}/></label>{binaryBytes&&<div className="text-xs">{binaryName} · {binaryBytes.length.toLocaleString()} bytes · {binaryMime}</div>}<textarea value={binaryB64} onChange={e=>setBinaryB64(e.target.value)} rows={12} placeholder="File Base64 payload" className="w-full p-3 border rounded font-mono text-xs bg-white dark:bg-neutral-900"/><div className="flex gap-2"><button onClick={restoreBinary} disabled={!binaryB64} className="px-3 py-2 text-xs border rounded disabled:opacity-40">Decode & download</button><button onClick={()=>{if(binaryBytes){const data=makeDataUrl(binaryBytes,binaryMime);void copyToClipboard(data);}}} className="px-3 py-2 text-xs border rounded">Copy data URL</button></div>{binaryB64&&<div className="text-[11px] text-neutral-500">Data URL parser check: {parseDataUrl(`data:${binaryMime};base64,${binaryB64}`)?.bytes.length??'invalid'} decoded bytes</div>}</div>}
 {output&&<button onClick={()=>void copyToClipboard(output)} className="px-3 py-2 text-xs border rounded inline-flex gap-1"><Copy className="w-3 h-3"/>Copy current output</button>}</div></ToolShell>;
};
export default EncodingTools;
