export interface PublicImageTask{id:string;name:string;shortName:string;description:string;keywords:string[];featured?:boolean}
type Raw=[string,string,string,string,string?,boolean?];
const RAW:Raw[]=[
['crop-image','Crop Image','Crop an image to a user-defined rectangle or a common centered aspect ratio entirely in your browser.','crop image|photo cropper|trim image|aspect crop','',true],
['rotate-flip-image','Rotate & Flip Image','Rotate photos by 90° steps or flip them horizontally or vertically without uploading them.','rotate image|flip image|mirror photo|orientation','Rotate / Flip',true],
['image-converter','Image Converter','Convert mainstream browser-decodable images to JPG, PNG, WebP, AVIF, GIF, BMP, ICO, or TIFF locally, including batch output.','image converter|jpg jpeg jfif png apng webp avif gif bmp ico tiff tif heic heif svg|heic converter|heif converter|svg to png|tiff to png|png to tiff|png to ico|jpg to gif|bmp to png|batch image converter|photo format converter','Image Converter',true],
['compress-image-to-size','Compress Image to Target Size','Aim for a target KB file size with bounded JPEG/WebP quality search at your chosen output dimensions.','compress image to 200kb|image target size|reduce photo size|compress jpg kb','Target Size Compress',true],
['profile-picture-maker','Profile Picture Maker','Create a circular profile-picture PNG from a centered square crop with transparent corners.','profile picture|circle crop|avatar maker|pfp crop','Profile Picture',true],
['blur-pixelate-image','Blur & Pixelate Image','Choose blur or pixelation for an entire image with adjustable strength for quick visual obfuscation.','blur image|pixelate photo|mosaic image|blur photo','Blur / Pixelate'],
['privacy-blur-image','Privacy Blur / Redactor','Manually blur or pixelate a selected rectangle such as a face, name, screen, address, or license plate.','face blur|privacy blur|redact image|blur license plate|hide personal info','Privacy Blur',true],
['image-metadata-cleaner','Image Metadata Viewer & Cleaner','Inspect common JPEG EXIF privacy fields and export a clean re-encoded copy that strips embedded metadata.','exif viewer|remove photo metadata|gps metadata|privacy metadata|clean exif','Metadata Cleaner',true],
['social-media-image-resizer','Social Media Image Resizer','Resize and crop images to common post, story, thumbnail, banner, and profile dimensions.','instagram size|youtube thumbnail|social media image size|story resize|banner resize','Social Resizer'],
['favicon-maker','Favicon & ICO Maker','Create a multi-size favicon PNG pack plus a standards-compatible PNG-backed ICO file from one image.','favicon maker|png to ico|jpg to ico|website icon|favicon generator','Favicon Maker'],
['image-grid-splitter','Image Grid Splitter','Split one image into equal rows and columns for tiles, carousels, print layouts, or social grids.','split image grid|instagram grid|image tiles|cut photo grid','Grid Splitter'],
['image-border-frame','Add Border / Frame to Image','Add a solid outside border around an image with configurable width and color.','add border to image|photo frame|image outline|white border','Image Border'],
['photo-filters','Photo Filters & Adjustments','Adjust brightness, contrast, saturation, grayscale, sepia, and hue with local canvas filters.','photo filter|brightness contrast|saturation|grayscale|sepia','Photo Filters'],
['image-compare','Image Compare Slider','Compare two images with an interactive before/after reveal slider.','before after image|compare photos|image slider|visual diff','Image Compare'],
['background-changer','Image Background Changer','Remove a foreground background locally, then place the subject on a chosen solid-color background.','change photo background|replace background|white background|background color','Background Changer'],
['transparent-image-maker','Make Image Background Transparent','Create a transparent PNG using the existing local background-removal engine.','transparent background|remove background png|make png transparent','Transparent Background',true],
['contact-sheet-maker','Contact Sheet Maker','Lay multiple images out on a clean thumbnail grid and export one combined PNG sheet.','contact sheet|photo sheet|thumbnail sheet|image grid collage','Contact Sheet'],
['image-upscaler','Image Upscaler','Upscale an image with high-quality browser resampling up to 4× without claiming AI-generated detail.','upscale image|enlarge photo|resize bigger|high quality upscale','Upscale Image'],
['headshot-cropper','Headshot & Portrait Cropper','Create consistent portrait and headshot crops with guided framing and common square/portrait ratios.','headshot crop|portrait crop|linkedin photo|professional profile crop','Headshot Cropper'],
];
export const PUBLIC_IMAGE_TASKS:PublicImageTask[]=RAW.map(([id,name,description,keys,shortName,featured])=>({id,name,shortName:shortName||name,description,keywords:keys.split('|'),featured}));
export function getPublicImageTask(id:string|null|undefined){return id?PUBLIC_IMAGE_TASKS.find(task=>task.id===id):undefined}
