import React,{useMemo,useState}from'react';
import{Check,Copy}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{slugQuality,uniqueSlugs,type SlugOptions,type SlugSeparator}from'../../utilities/s-tier-slug';
const inputClass='mt-1 w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 dark:border-neutral-700 dark:bg-neutral-950';
export default function SlugStudio({initialText=''}:{initialText?:string}){
 const[input,setInput]=useState(initialText||'How to Build a Better Tiny Tools App\nHow to Build a Better Tiny Tools App\nCafé & Crème — Déjà Vu'),[separator,setSeparator]=useState<SlugSeparator>('-'),[lowercase,setLowercase]=useState(true),[unicode,setUnicode]=useState(false),[stop,setStop]=useState(false),[maxLength,setMaxLength]=useState(80),[copied,setCopied]=useState(false);
 const options:SlugOptions={separator,lowercase,unicode,removeStopWords:stop,maxLength,trimBoundary:true};const rows=useMemo(()=>uniqueSlugs(input.split(/\r?\n/).map(line=>line.trim()).filter(Boolean),options),[input,separator,lowercase,unicode,stop,maxLength]);const output=rows.map(row=>row.slug).join('\n');const firstQuality=slugQuality(rows[0]?.slug??'');
 const copy=async()=>{if(await copyToClipboard(output)){setCopied(true);setTimeout(()=>setCopied(false),1200)}};
 return<ToolShell toolId="slug-generator" title="URL Slug Generator" description="Generate production-ready URL slugs in batches with ASCII folding or Unicode preservation, separator choice, stop-word removal, length limits, and automatic duplicate suffixes." category="developer" relatedToolIds={['url-parser','meta-tags-generator','sitemap-xml-builder']} outputToTransfer={output}><div className="space-y-5">
  <div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs leading-5 text-blue-900 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-200">One source title per line. Duplicate generated slugs are made unique with stable suffixes such as <code>-2</code>. ASCII mode folds common Latin diacritics; Unicode mode keeps letters from other scripts.</div>
  <div className="grid gap-4 lg:grid-cols-[1fr_18rem]"><label className="text-xs font-semibold">Titles / phrases<textarea aria-label="Titles to slugify" rows={10} value={input} onChange={e=>setInput(e.target.value)} className={`${inputClass} resize-y`}/></label><div className="space-y-3"><label className="text-xs font-semibold">Separator<select aria-label="Slug separator" className={inputClass} value={separator} onChange={e=>setSeparator(e.target.value as SlugSeparator)}><option value="-">Hyphen -</option><option value="_">Underscore _</option><option value=".">Dot .</option></select></label><label className="text-xs font-semibold">Maximum length<input aria-label="Maximum slug length" className={inputClass} type="number" min="10" max="300" step="1" value={maxLength} onChange={e=>setMaxLength(Number(e.target.value))}/></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={lowercase} onChange={e=>setLowercase(e.target.checked)}/> Lowercase output</label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={unicode} onChange={e=>setUnicode(e.target.checked)}/> Preserve Unicode letters</label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={stop} onChange={e=>setStop(e.target.checked)}/> Remove common English stop words</label><div className="grid grid-cols-2 gap-2"><Metric label="First length" value={firstQuality.length}/><Metric label="First words" value={firstQuality.words}/></div></div></div>
  <section className="rounded-xl border border-neutral-200 dark:border-neutral-800"><div className="flex items-center justify-between border-b border-neutral-200 p-3 dark:border-neutral-800"><h2 className="text-sm font-bold">Generated slugs</h2><button type="button" onClick={()=>void copy()} disabled={!output} className="inline-flex items-center gap-1.5 rounded-lg border border-neutral-300 px-2.5 py-1.5 text-xs font-semibold disabled:opacity-40 dark:border-neutral-700">{copied?<Check className="h-3.5 w-3.5"/>:<Copy className="h-3.5 w-3.5"/>}{copied?'Copied':'Copy all'}</button></div><div className="divide-y divide-neutral-200 dark:divide-neutral-800">{rows.map((row,index)=><div key={`${row.source}-${index}`} className="grid gap-2 p-3 md:grid-cols-[1fr_1fr_auto]"><div className="text-sm text-neutral-600 dark:text-neutral-300">{row.source}</div><code className="break-all rounded bg-neutral-50 px-2 py-1 text-xs dark:bg-neutral-950">{row.slug}</code><span className="text-[10px] font-semibold uppercase text-neutral-500">{row.duplicateIndex>1?`duplicate ${row.duplicateIndex}`:'unique'}</span></div>)}</div></section>
  <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-200">Changing a published URL slug can break inbound links unless the old URL redirects. Treat generated slugs as candidates and keep your site’s routing/redirect policy in mind.</div>
 </div></ToolShell>
}
function Metric({label,value}:{label:string;value:number}){return<div className="rounded-lg border border-neutral-200 p-2 dark:border-neutral-800"><div className="text-[9px] font-semibold uppercase text-neutral-500">{label}</div><div className="text-base font-bold">{value}</div></div>}
