import React from'react';
import{ArrowRight,Download,FileUp,RefreshCw,ShieldCheck}from'lucide-react';
import{humanBytes}from'../../utilities/unified-converters';
export function ConverterNotice({children}:{children?:React.ReactNode}){return<div className="flex items-start gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-300"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0"/><span>{children??'Upload, choose an output format, convert, download. Files stay on this device. Optional format runtimes are downloaded only when needed; your file content is not sent to them.'}</span></div>}
export function ConverterPicker({file,onFile,accept,multiple=false}:{file?:File|null;onFile:(file:File|null,files?:File[])=>void;accept?:string;multiple?:boolean}){return<label className="flex min-h-36 cursor-pointer flex-col items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-neutral-300 bg-neutral-50 px-5 py-7 text-center dark:border-neutral-700 dark:bg-neutral-950"><FileUp className="h-7 w-7 text-neutral-500"/><span className="text-sm font-bold">{file?file.name:'Drop or choose a file'}</span>{file&&<span className="text-xs text-neutral-500">{humanBytes(file.size)}</span>}<span className="text-xs text-neutral-500">Your file never leaves this device.</span><input className="sr-only" type="file" accept={accept} multiple={multiple} onChange={e=>{const files=[...e.target.files??[]];onFile(files[0]??null,files)}}/></label>}
export function ConverterFlow({source,target,setTarget,targets}:{source:string;target:string;setTarget:(v:string)=>void;targets:{value:string;label:string}[]}){return<div className="grid items-end gap-3 sm:grid-cols-[1fr_auto_1fr]"><label className="text-xs font-semibold">Detected / source format<input value={source.toUpperCase()} readOnly className="mt-1 w-full rounded-xl border bg-neutral-100 px-3 py-3 font-bold dark:bg-neutral-900"/></label><ArrowRight className="mb-3 hidden h-5 w-5 text-neutral-400 sm:block"/><label className="text-xs font-semibold">Convert to<select value={target} onChange={e=>setTarget(e.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-3 font-bold dark:bg-neutral-950">{targets.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label></div>}
export function ConverterAction({busy,disabled,onClick,label='Convert & download'}:{busy:boolean;disabled?:boolean;onClick:()=>void;label?:string}){return<button type="button" disabled={busy||disabled} onClick={onClick} className="inline-flex items-center gap-2 rounded-xl bg-neutral-900 px-5 py-3 text-sm font-bold text-white disabled:opacity-40 dark:bg-neutral-100 dark:text-neutral-900">{busy?<RefreshCw className="h-4 w-4 animate-spin"/>:<Download className="h-4 w-4"/>}{busy?'Converting…':label}</button>}
export function ConverterError({text}:{text:string}){return text?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{text}</div>:null}
export function saveConverterBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200)}
export const converterTextBlob=(text:string,type='text/plain;charset=utf-8')=>new Blob([text],{type});
export const converterBaseName=(name:string)=>(name.replace(/\.(?:tar\.gz|[^.]+)$/i,'').trim().replace(/[\\/:*?"<>|]+/g,'-')||'converted').slice(0,90);
export const converterError=(e:unknown)=>e instanceof Error?e.message:String(e);
