import React,{useEffect,useMemo,useState}from'react';
import JSZip from'jszip';
import{ArrowRight,Download,FileUp,RefreshCw,ShieldCheck}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{getToolById}from'../../registry/tools';
import{normalizeToolShellId}from'../../registry/tool-shell-mode';
import{audioBufferToWavBlob}from'../../utilities/audio-recorder';
import{csvTextToJson,jsonTextToCsv,jsonTextToXlsx,jsonTextToXml,xlsxToJson,xmlTextToJson}from'../../utilities/file-format-conversion';
import{htmlToMarkdown,jsonToToml,jsonToYaml,markdownToHtml,parseTomlSubset,parseYamlSubset}from'../../utilities/p11-developer';
import{createDocx,createEpub,extractDocx,extractEpub,extractPptx,type BookMetadata}from'../../utilities/p13-office';
import{formatSubtitles,parseSubtitles,subtitleToPlainText,transcriptToSubtitleCues,type SubtitleFormat}from'../../utilities/p16-subtitles';
import{audioTargets,DATA_FORMATS,detectDataFormat,detectDocumentFormat,detectSubtitleFormat,documentTextViews,DOCUMENT_INPUT_FORMATS,DOCUMENT_OUTPUT_FORMATS,extractBasicPdfText,humanBytes,plainTextToHtml,SUBTITLE_CONVERTER_FORMATS,type AudioTarget,type DataFormat,type DocumentFormat,type SubtitleConverterFormat}from'../../utilities/unified-converters';

function routeId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0],raw=clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0];return normalizeToolShellId(raw)}
function save(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200)}
function textBlob(text:string,type='text/plain;charset=utf-8'){return new Blob([text],{type})}
function baseName(name:string){return(name.replace(/\.[^.]+$/,'').trim().replace(/[\\/:*?"<>|]+/g,'-')||'converted').slice(0,90)}
function errorMessage(e:unknown){return e instanceof Error?e.message:String(e)}
function mimeForText(ext:string){return ext==='html'?'text/html;charset=utf-8':ext==='json'?'application/json':ext==='xml'?'application/xml':ext==='csv'?'text/csv;charset=utf-8':'text/plain;charset=utf-8'}

const UnifiedConverters:React.FC<{initialText?:string}>=({initialText})=>{const id=routeId(),tool=getToolById(id);if(!tool)return null;let body:React.ReactNode;switch(id){case'document-converter':body=<DocumentConverter initialText={initialText}/>;break;case'data-converter':body=<DataConverter initialText={initialText}/>;break;case'image-converter':body=<ImageConverter/>;break;case'audio-converter':body=<AudioConverter/>;break;case'subtitle-converter':body=<SubtitleConverter initialText={initialText}/>;break;default:return null}return<ToolShell toolId={tool.id} title={tool.name} description={tool.description} category={tool.category} relatedToolIds={id==='document-converter'?['docx-metadata-inspector','epub-metadata-editor','file-type-inspector']:id==='data-converter'?['csv-splitter','csv-merger','file-type-inspector']:id==='image-converter'?['image-optimizer','image-metadata-cleaner','favicon-maker']:id==='audio-converter'?['audio-joiner','audio-normalizer','video-to-audio']:['subtitle-editor','subtitle-cleaner-validator','subtitle-burner']}><div className="space-y-5"><Notice/>{body}</div></ToolShell>}
function Notice(){return<div className="flex items-start gap-2 rounded-xl border border-emerald-200 bg-emerald-50 p-3 text-xs text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-300"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0"/><span>Upload, choose an output format, convert, download. Processing stays in your browser. Available outputs reflect formats Tiny Tools can produce locally rather than advertising server-only conversions.</span></div>}
function Picker({file,onFile,accept,multiple=false}:{file?:File|null;onFile:(file:File|null,files?:File[])=>void;accept?:string;multiple?:boolean}){return<label className="flex min-h-36 cursor-pointer flex-col items-center justify-center gap-2 rounded-2xl border-2 border-dashed border-neutral-300 bg-neutral-50 px-5 py-7 text-center dark:border-neutral-700 dark:bg-neutral-950"><FileUp className="h-7 w-7 text-neutral-500"/><span className="text-sm font-bold">{file?file.name:'Drop or choose a file'}</span>{file&&<span className="text-xs text-neutral-500">{humanBytes(file.size)}</span>}<span className="text-xs text-neutral-500">Your file never leaves this device.</span><input className="sr-only" type="file" accept={accept} multiple={multiple} onChange={e=>{const files=[...e.target.files??[]];onFile(files[0]??null,files)}}/></label>}
function Flow({source,target,setTarget,targets}:{source:string;target:string;setTarget:(v:string)=>void;targets:{value:string;label:string}[]}){return<div className="grid items-end gap-3 sm:grid-cols-[1fr_auto_1fr]"><label className="text-xs font-semibold">Detected / source format<input value={source.toUpperCase()} readOnly className="mt-1 w-full rounded-xl border bg-neutral-100 px-3 py-3 font-bold dark:bg-neutral-900"/></label><ArrowRight className="mb-3 hidden h-5 w-5 text-neutral-400 sm:block"/><label className="text-xs font-semibold">Convert to<select value={target} onChange={e=>setTarget(e.target.value)} className="mt-1 w-full rounded-xl border bg-white px-3 py-3 font-bold dark:bg-neutral-950">{targets.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select></label></div>}
function Action({busy,disabled,onClick,label='Convert & download'}:{busy:boolean;disabled?:boolean;onClick:()=>void;label?:string}){return<button type="button" disabled={busy||disabled} onClick={onClick} className="inline-flex items-center gap-2 rounded-xl bg-neutral-900 px-5 py-3 text-sm font-bold text-white disabled:opacity-40 dark:bg-neutral-100 dark:text-neutral-900">{busy?<RefreshCw className="h-4 w-4 animate-spin"/>:<Download className="h-4 w-4"/>}{busy?'Converting…':label}</button>}
function ErrorBox({text}:{text:string}){return text?<div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{text}</div>:null}

async function docViews(file:File|null,format:DocumentFormat,textInput:string){if(format==='txt'||format==='md'||format==='html')return documentTextViews(file?await file.text():textInput,format);if(!file)throw new Error(`Choose a ${format.toUpperCase()} file first.`);const bytes=await file.arrayBuffer();if(format==='docx')return{text:await extractDocx(bytes,'text'),markdown:await extractDocx(bytes,'markdown'),html:await extractDocx(bytes,'html')};if(format==='epub')return{text:await extractEpub(bytes,'text'),markdown:await extractEpub(bytes,'markdown'),html:await extractEpub(bytes,'html')};if(format==='pptx'){const markdown=await extractPptx(bytes,'markdown'),text=await extractPptx(bytes,'text');return{text,markdown,html:markdownToHtml(markdown)}}const text=await extractBasicPdfText(bytes);return{text,markdown:text,html:plainTextToHtml(text)}}
function wrapCanvasText(ctx:CanvasRenderingContext2D,text:string,maxWidth:number){const words=text.split(/\s+/),out:string[]=[];let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){out.push(line);line=word}else line=test}if(line)out.push(line);return out}
function bytesFromBase64(data:string){const raw=atob(data),out=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
function ascii(text:string){return new TextEncoder().encode(text)}
function joinBytes(parts:Uint8Array[]){const size=parts.reduce((n,p)=>n+p.length,0),out=new Uint8Array(size);let at=0;for(const p of parts){out.set(p,at);at+=p.length}return out}
async function rasterTextPdf(text:string){const W=1240,H=1754,margin=105,lineH=42,font='28px system-ui, sans-serif',canvas=document.createElement('canvas');canvas.width=W;canvas.height=H;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas is unavailable.');ctx.font=font;const sourceLines=text.replace(/\r/g,'').split('\n'),lines:string[]=[];for(const raw of sourceLines){if(!raw.trim()){lines.push('');continue}lines.push(...wrapCanvasText(ctx,raw,W-margin*2))}const perPage=Math.floor((H-margin*2)/lineH),images:Uint8Array[]=[];for(let p=0;p<Math.max(1,Math.ceil(lines.length/perPage));p++){ctx.fillStyle='#fff';ctx.fillRect(0,0,W,H);ctx.fillStyle='#111';ctx.font=font;ctx.textBaseline='top';const page=lines.slice(p*perPage,(p+1)*perPage);page.forEach((line,i)=>ctx.fillText(line,margin,margin+i*lineH,W-margin*2));const url=canvas.toDataURL('image/jpeg',.9),b64=url.split(',')[1];images.push(bytesFromBase64(b64))}const count=images.length,objects:(Uint8Array|null)[]=new Array(3+count*3).fill(null);objects[1]=ascii('<< /Type /Catalog /Pages 2 0 R >>');const kids=images.map((_,i)=>`${3+i*3} 0 R`).join(' ');objects[2]=ascii(`<< /Type /Pages /Count ${count} /Kids [${kids}] >>`);for(let i=0;i<count;i++){const page=3+i*3,img=page+1,content=page+2,jpeg=images[i],cmd=ascii('q\n595 0 0 842 0 0 cm\n/Im0 Do\nQ\n');objects[page]=ascii(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /XObject << /Im0 ${img} 0 R >> >> /Contents ${content} 0 R >>`);objects[img]=joinBytes([ascii(`<< /Type /XObject /Subtype /Image /Width ${W} /Height ${H} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${jpeg.length} >>\nstream\n`),jpeg,ascii('\nendstream')]);objects[content]=joinBytes([ascii(`<< /Length ${cmd.length} >>\nstream\n`),cmd,ascii('endstream')])}const parts=[ascii('%PDF-1.4\n%TinyTools\n')],offsets=[0];let offset=parts[0].length;for(let i=1;i<objects.length;i++){offsets[i]=offset;const body=joinBytes([ascii(`${i} 0 obj\n`),objects[i]!,ascii('\nendobj\n')]);parts.push(body);offset+=body.length}const xref=offset,rows=['0000000000 65535 f '];for(let i=1;i<objects.length;i++)rows.push(`${String(offsets[i]).padStart(10,'0')} 00000 n `);parts.push(ascii(`xref\n0 ${objects.length}\n${rows.join('\n')}\ntrailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`));return new Blob([joinBytes(parts)],{type:'application/pdf'})}
function DocumentConverter({initialText}:{initialText?:string}){const[file,setFile]=useState<File|null>(null),[source,setSource]=useState<DocumentFormat>('txt'),[target,setTarget]=useState<DocumentFormat>('docx'),[text,setText]=useState(initialText??'Tiny Tools document\n\nUpload a file or paste text, then choose one output format.'),[busy,setBusy]=useState(false),[error,setError]=useState('');const targets=DOCUMENT_OUTPUT_FORMATS.filter(x=>x!==source).map(x=>({value:x,label:x==='md'?'Markdown':x==='txt'?'Plain text':x.toUpperCase()}));useEffect(()=>{if(!targets.some(x=>x.value===target))setTarget(targets[0]?.value as DocumentFormat)},[source]);const choose=async(f:File|null)=>{setFile(f);setError('');if(!f)return;const detected=detectDocumentFormat(f.name);if(!detected){setError('Supported inputs: TXT, Markdown, HTML, DOCX, EPUB, PPTX, and PDF.');return}setSource(detected);if(['txt','md','html'].includes(detected))setText(await f.text())};const run=async()=>{setBusy(true);setError('');try{const views=await docViews(file,source,text),name=baseName(file?.name||'document');if(target==='txt')save(textBlob(views.text),`${name}.txt`);else if(target==='md')save(textBlob(views.markdown),`${name}.md`);else if(target==='html')save(textBlob(views.html,'text/html;charset=utf-8'),`${name}.html`);else if(target==='docx')save(new Blob([await createDocx(views.markdown,{title:name})],{type:'application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),`${name}.docx`);else if(target==='epub'){const meta:BookMetadata={title:name,creator:'',language:'en',identifier:'',publisher:'',description:''};save(new Blob([await createEpub(views.markdown,meta)],{type:'application/epub+zip'}),`${name}.epub`)}else save(await rasterTextPdf(views.text),`${name}.pdf`)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};return<div className="space-y-4"><Picker file={file} onFile={f=>void choose(f)} accept=".txt,.md,.markdown,.html,.htm,.docx,.epub,.pptx,.pdf,text/plain,text/markdown,text/html,application/pdf"/><Flow source={source} target={target} setTarget={v=>setTarget(v as DocumentFormat)} targets={targets}/>{['txt','md','html'].includes(source)&&<label className="block text-xs font-semibold">Source content<textarea rows={10} value={text} onChange={e=>setText(e.target.value)} className="mt-1 w-full rounded-xl border bg-white p-3 font-mono text-sm dark:bg-neutral-950"/></label>}<ErrorBox text={error}/><Action busy={busy} disabled={!file&&!text.trim()} onClick={()=>void run()}/><p className="text-xs text-neutral-500">DOCX/EPUB/PPTX conversions are content-oriented rather than layout-perfect. PDF import is best-effort text extraction; scanned/complex PDFs may need the dedicated PDF OCR workspace. PDF export is a local browser-rendered document designed for portable reading rather than editable PDF text.</p></div>}

async function dataJson(source:DataFormat,file:File|null,text:string){if(source==='xlsx'){if(!file)throw new Error('Choose an XLSX file first.');return await xlsxToJson(file)}const input=file?await file.text():text;if(source==='json')return JSON.stringify(JSON.parse(input),null,2);if(source==='csv')return csvTextToJson(input);if(source==='xml')return xmlTextToJson(input);if(source==='yaml')return JSON.stringify(parseYamlSubset(input),null,2);return JSON.stringify(parseTomlSubset(input),null,2)}
function DataConverter({initialText}:{initialText?:string}){const[file,setFile]=useState<File|null>(null),[source,setSource]=useState<DataFormat>('csv'),[target,setTarget]=useState<DataFormat>('json'),[text,setText]=useState(initialText??'name,score\nAda,98\nLin,91'),[busy,setBusy]=useState(false),[error,setError]=useState('');const targets=DATA_FORMATS.filter(x=>x!==source).map(x=>({value:x,label:x.toUpperCase()}));useEffect(()=>{if(!targets.some(x=>x.value===target))setTarget(targets[0]?.value as DataFormat)},[source]);const choose=async(f:File|null)=>{setFile(f);setError('');if(!f)return;const detected=detectDataFormat(f.name);if(!detected){setError('Supported inputs: CSV, JSON, XML, XLSX, YAML/YML, and TOML.');return}setSource(detected);if(detected!=='xlsx')setText(await f.text())};const run=async()=>{setBusy(true);setError('');try{const json=await dataJson(source,file,text),value=JSON.parse(json),name=baseName(file?.name||'data');if(target==='json')save(textBlob(JSON.stringify(value,null,2),'application/json'),`${name}.json`);else if(target==='csv')save(textBlob(jsonTextToCsv(JSON.stringify(value)),'text/csv;charset=utf-8'),`${name}.csv`);else if(target==='xml')save(textBlob(jsonTextToXml(JSON.stringify(value)),'application/xml'),`${name}.xml`);else if(target==='yaml')save(textBlob(jsonToYaml(value)),`${name}.yaml`);else if(target==='toml')save(textBlob(jsonToToml(Array.isArray(value)?{records:value}:value)),`${name}.toml`);else save(await jsonTextToXlsx(JSON.stringify(value)),`${name}.xlsx`)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};return<div className="space-y-4"><Picker file={file} onFile={f=>void choose(f)} accept=".csv,.json,.xml,.xlsx,.yaml,.yml,.toml,text/csv,application/json,application/xml"/><Flow source={source} target={target} setTarget={v=>setTarget(v as DataFormat)} targets={targets}/>{source!=='xlsx'&&<label className="block text-xs font-semibold">Source data<textarea rows={11} value={text} onChange={e=>setText(e.target.value)} className="mt-1 w-full rounded-xl border bg-white p-3 font-mono text-sm dark:bg-neutral-950"/></label>}<ErrorBox text={error}/><Action busy={busy} disabled={source==='xlsx'?!file:!text.trim()} onClick={()=>void run()}/><p className="text-xs text-neutral-500">Structured conversions normalize through JSON. Spreadsheet conversion uses the first XLSX worksheet and is value-oriented. CSV/XLSX outputs require record-like data; TOML array roots are wrapped under a records key.</p></div>}

function imageLoad(file:File){return new Promise<HTMLImageElement>((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error(`This browser could not decode ${file.name}. HEIC/HEIF and AVIF support depends on the browser and operating system.`))};img.src=url})}
function canvasBlob(canvas:HTMLCanvasElement,type:string,quality:number){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error(`This browser cannot encode ${type}.`)),type,quality))}
const imageTargets=[{value:'image/jpeg',label:'JPG',ext:'jpg'},{value:'image/png',label:'PNG',ext:'png'},{value:'image/webp',label:'WebP',ext:'webp'},{value:'image/avif',label:'AVIF',ext:'avif'}];
function ImageConverter(){const[files,setFiles]=useState<File[]>([]),[target,setTarget]=useState('image/jpeg'),[quality,setQuality]=useState(.9),[busy,setBusy]=useState(false),[error,setError]=useState('');const run=async()=>{setBusy(true);setError('');try{if(!files.length)throw new Error('Choose one or more images first.');const chosen=imageTargets.find(x=>x.value===target)!,outputs:{name:string;blob:Blob}[]=[];for(const file of files){const img=await imageLoad(file),canvas=document.createElement('canvas');canvas.width=img.naturalWidth||1024;canvas.height=img.naturalHeight||1024;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas is unavailable.');if(target==='image/jpeg'){ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height)}ctx.drawImage(img,0,0,canvas.width,canvas.height);outputs.push({name:`${baseName(file.name)}.${chosen.ext}`,blob:await canvasBlob(canvas,target,quality)})}if(outputs.length===1)save(outputs[0].blob,outputs[0].name);else{const zip=new JSZip();for(const o of outputs)zip.file(o.name,await o.blob.arrayBuffer());save(await zip.generateAsync({type:'blob',compression:'DEFLATE'}),`converted-${chosen.ext}.zip`)}}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};return<div className="space-y-4"><Picker file={files[0]??null} multiple onFile={(_,all)=>setFiles(all??[])} accept="image/*,.svg,.heic,.heif,.avif"/>{files.length>1&&<div className="rounded-xl border p-3 text-sm">{files.length} images selected · batch export will download as ZIP.</div>}<Flow source={files[0]?detectImageLabel(files[0].name):'image'} target={target} setTarget={setTarget} targets={imageTargets.map(x=>({value:x.value,label:x.label}))}/>{target!=='image/png'&&<label className="block text-xs font-semibold">Quality: {Math.round(quality*100)}%<input type="range" min="0.2" max="1" step="0.02" value={quality} onChange={e=>setQuality(Number(e.target.value))} className="mt-2 w-full"/></label>}<ErrorBox text={error}/><Action busy={busy} disabled={!files.length} onClick={()=>void run()}/><p className="text-xs text-neutral-500">Inputs include common browser-decodable images such as JPG, PNG, WebP, GIF/BMP first-frame rasterization, SVG, AVIF, and HEIC/HEIF when the browser can decode them. Outputs are JPG, PNG, WebP, and AVIF when the browser encoder supports the selected format.</p></div>}
function detectImageLabel(name:string){const ext=name.split('.').pop()?.toUpperCase();return ext||'IMAGE'}

async function encodeAudioMedia(buffer:AudioBuffer,target:AudioTarget){const ctx=new AudioContext(),dest=ctx.createMediaStreamDestination(),source=ctx.createBufferSource();source.buffer=buffer;source.connect(dest);const chunks:Blob[]=[],rec=new MediaRecorder(dest.stream,{mimeType:target.mime});rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const stopped=new Promise<Blob>((resolve,reject)=>{rec.onerror=()=>reject(new Error('The browser audio encoder failed.'));rec.onstop=()=>resolve(new Blob(chunks,{type:target.mime}))});await ctx.resume();rec.start(250);source.start();await new Promise<void>(resolve=>{source.onended=()=>resolve()});rec.stop();const blob=await stopped;dest.stream.getTracks().forEach(t=>t.stop());await ctx.close();return blob}
function AudioConverter(){const[file,setFile]=useState<File|null>(null),[targetMime,setTargetMime]=useState('audio/wav'),[busy,setBusy]=useState(false),[error,setError]=useState('');const targets=useMemo(()=>audioTargets(m=>typeof MediaRecorder!=='undefined'&&MediaRecorder.isTypeSupported(m)),[]);useEffect(()=>{if(!targets.some(x=>x.mime===targetMime))setTargetMime(targets[0].mime)},[targets,targetMime]);const run=async()=>{if(!file)return;setBusy(true);setError('');let decode:AudioContext|null=null;try{decode=new AudioContext();const buffer=await decode.decodeAudioData((await file.arrayBuffer()).slice(0)),target=targets.find(x=>x.mime===targetMime)!;if(target.mime==='audio/wav')save(audioBufferToWavBlob(buffer),`${baseName(file.name)}.wav`);else save(await encodeAudioMedia(buffer,target),`${baseName(file.name)}.${target.extension}`)}catch(e){setError(errorMessage(e))}finally{await decode?.close().catch(()=>{});setBusy(false)}};return<div className="space-y-4"><Picker file={file} onFile={setFile} accept="audio/*,.mp3,.wav,.m4a,.aac,.ogg,.opus,.flac,.webm"/><Flow source={file?(file.name.split('.').pop()||'audio'):'audio'} target={targetMime} setTarget={setTargetMime} targets={targets.map(x=>({value:x.mime,label:x.label}))}/>{targets.find(x=>x.mime===targetMime)?.realtime&&<div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-300">This browser encodes the selected compressed format through MediaRecorder, so conversion runs approximately in real time.</div>}<ErrorBox text={error}/><Action busy={busy} disabled={!file} onClick={()=>void run()}/><p className="text-xs text-neutral-500">MP3, WAV, M4A/AAC, OGG/Opus, FLAC, and other sources work when the browser can decode them. WAV output is always available. MP3, AAC/M4A, OGG, and WebM outputs appear only when the current browser exposes a matching local encoder.</p></div>}

function SubtitleConverter({initialText}:{initialText?:string}){const[file,setFile]=useState<File|null>(null),[source,setSource]=useState<SubtitleConverterFormat>('srt'),[target,setTarget]=useState<SubtitleConverterFormat>('vtt'),[text,setText]=useState(initialText??'1\n00:00:01,000 --> 00:00:03,000\nWelcome to Tiny Tools.\n'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[preview,setPreview]=useState('');const targets=SUBTITLE_CONVERTER_FORMATS.filter(x=>x!==source).map(x=>({value:x,label:x==='vtt'?'WebVTT':x==='srt'?'SRT':'Plain text'}));useEffect(()=>{if(!targets.some(x=>x.value===target))setTarget(targets[0]?.value as SubtitleConverterFormat)},[source]);const choose=async(f:File|null)=>{setFile(f);if(!f)return;const detected=detectSubtitleFormat(f.name);if(detected)setSource(detected);setText(await f.text())};const run=()=>{setBusy(true);setError('');try{let out='';if(source==='txt'){if(target==='txt')out=text;else out=formatSubtitles(transcriptToSubtitleCues(text,{cueDurationMs:3000,gapMs:150,maxChars:84}),target as SubtitleFormat)}else{const cues=parseSubtitles(text,source as SubtitleFormat).cues;if(target==='txt')out=subtitleToPlainText(cues,'lines',true);else out=formatSubtitles(cues,target as SubtitleFormat)}setPreview(out);save(textBlob(out),`${baseName(file?.name||'subtitles')}.${target}`)}catch(e){setError(errorMessage(e))}finally{setBusy(false)}};return<div className="space-y-4"><Picker file={file} onFile={f=>void choose(f)} accept=".srt,.vtt,.webvtt,.txt,text/plain,text/vtt"/><Flow source={source} target={target} setTarget={v=>setTarget(v as SubtitleConverterFormat)} targets={targets}/><label className="block text-xs font-semibold">Subtitle / transcript text<textarea rows={11} value={text} onChange={e=>setText(e.target.value)} className="mt-1 w-full rounded-xl border bg-white p-3 font-mono text-sm dark:bg-neutral-950"/></label><ErrorBox text={error}/><Action busy={busy} disabled={!text.trim()} onClick={run}/>{preview&&<pre className="max-h-64 overflow-auto whitespace-pre-wrap rounded-xl border bg-neutral-50 p-3 text-xs dark:bg-neutral-950">{preview}</pre>}<p className="text-xs text-neutral-500">SRT and WebVTT preserve cue timing and text. Plain-text export removes timestamps. Plain text → SRT/WebVTT creates deterministic evenly timed cues; it does not infer timing from audio.</p></div>}
export default UnifiedConverters;
