import React,{useMemo,useRef,useState}from'react';
import{Copy,Palette,Upload}from'lucide-react';
import{copyToClipboard}from'../../utilities/clipboard';
import{extractColorsFromCanvas,formatAsCssVariables,generateHarmonies,sortExtractedPalette,suggestAccessibleColorRoles,type ExtractedColor,type PaletteSortOption}from'../../utilities/palette-extractor';
export const PaletteExtractorTool:React.FC=()=>{
 const[url,setUrl]=useState<string|null>(null);const[colors,setColors]=useState<ExtractedColor[]>([]);const[size,setSize]=useState(6);const[sort,setSort]=useState<PaletteSortOption>('dominance');const[selected,setSelected]=useState<string|null>(null);const urlRef=useRef<string|null>(null);
 const process=(file:File)=>{if(!file.type.startsWith('image/'))return;if(urlRef.current)URL.revokeObjectURL(urlRef.current);const next=URL.createObjectURL(file);urlRef.current=next;setUrl(next);const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d')?.drawImage(img,0,0);const result=extractColorsFromCanvas(c,size);setColors(result);setSelected(result[0]?.hex||null);};img.src=next;};
 const display=useMemo(()=>sortExtractedPalette(colors,sort),[colors,sort]),roles=useMemo(()=>suggestAccessibleColorRoles(display),[display]),harmonies=selected?generateHarmonies(selected):[];
 const reprocess=()=>{if(!url)return;const img=new Image();img.onload=()=>{const c=document.createElement('canvas');c.width=img.naturalWidth;c.height=img.naturalHeight;c.getContext('2d')?.drawImage(img,0,0);const result=extractColorsFromCanvas(c,size);setColors(result);setSelected(result[0]?.hex||null);};img.src=url;};
 return <div className="space-y-5" onPaste={e=>{const item=[...e.clipboardData.items].find(i=>i.type.startsWith('image/'));const file=item?.getAsFile();if(file)process(file);}}>
  <div className="flex flex-wrap gap-2 items-center"><label className="px-3 py-2 rounded-lg bg-indigo-600 text-white text-xs font-semibold cursor-pointer inline-flex gap-1 items-center"><Upload className="w-4 h-4"/>Choose image<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&process(e.target.files[0])}/></label><label className="text-xs">Perceptual palette size <select value={size} onChange={e=>{setSize(Number(e.target.value));queueMicrotask(reprocess);}} className="ml-1 border rounded bg-white dark:bg-neutral-900 p-1"><option>3</option><option>5</option><option>6</option><option>8</option><option>10</option><option>12</option></select></label><label className="text-xs">Sort <select value={sort} onChange={e=>setSort(e.target.value as PaletteSortOption)} className="ml-1 border rounded bg-white dark:bg-neutral-900 p-1"><option value="dominance">dominance</option><option value="brightness">brightness</option><option value="hue">hue</option></select></label></div>
  {!url?<div className="p-12 text-center border-2 border-dashed rounded-xl"><Palette className="mx-auto w-8 h-8 text-indigo-500"/><p className="mt-2 text-sm font-semibold">CIELAB perceptual color extraction</p><p className="text-xs text-neutral-500">Drop/paste an image or choose a file. Transparent pixels are ignored.</p></div>:<div className="grid lg:grid-cols-[320px_1fr] gap-5"><img src={url} alt="Palette source" className="w-full max-h-80 object-contain rounded-xl border bg-neutral-100 dark:bg-neutral-900"/><div className="space-y-3"><div className="h-16 flex rounded-xl overflow-hidden border">{display.map(c=><button key={c.hex} type="button" title={`${c.hex} · ${c.dominancePercent}%`} onClick={()=>setSelected(c.hex)} style={{backgroundColor:c.hex,flexGrow:Math.max(1,c.dominancePercent)}} className="min-w-5"/>)}</div><div className="grid sm:grid-cols-3 xl:grid-cols-5 gap-2">{display.map(c=><button key={c.hex} type="button" onClick={()=>setSelected(c.hex)} className={`p-2 rounded-lg border text-left ${selected===c.hex?'ring-2 ring-indigo-500':''}`}><span className="block h-10 rounded mb-1" style={{backgroundColor:c.hex}}/><span className="font-mono text-xs">{c.hex}</span><span className="block text-[10px] text-neutral-500">{c.dominancePercent}% · L {c.l}</span></button>)}</div></div></div>}
  {roles&&<div className="p-4 border rounded-xl space-y-3"><div><h3 className="text-sm font-semibold">Accessible roles</h3><p className="text-xs text-neutral-500">Automatically selects high-contrast roles from the Perceptual palette plus black/white when required.</p></div><div className="grid sm:grid-cols-4 gap-2">{([['Background',roles.background],['Text',roles.text],['Accent',roles.accent],['Muted',roles.muted]] as const).map(([label,hex])=><button key={label} onClick={()=>void copyToClipboard(hex)} className="border rounded-lg p-2 text-xs"><span className="block h-8 rounded mb-1" style={{backgroundColor:hex}}/>{label}: <span className="font-mono">{hex}</span></button>)}</div><div className="text-xs">Background/text contrast: <strong>{roles.backgroundTextContrast}:1</strong> · Accent/background: <strong>{roles.accentContrast}:1</strong></div></div>}
  {selected&&<div className="grid md:grid-cols-2 gap-4"><div className="p-4 border rounded-xl"><h3 className="font-semibold text-sm mb-2">Harmonies for {selected}</h3>{harmonies.map(h=><div key={h.type} className="mb-2"><div className="text-xs text-neutral-500">{h.name}</div><div className="flex">{h.colors.map(c=><button key={c} onClick={()=>void copyToClipboard(c)} title={c} className="h-8 flex-1" style={{backgroundColor:c}}/>)}</div></div>)}</div><div className="p-4 border rounded-xl"><div className="flex justify-between"><h3 className="font-semibold text-sm">CSS variables</h3><button onClick={()=>void copyToClipboard(formatAsCssVariables(display))} className="text-xs inline-flex gap-1"><Copy className="w-3 h-3"/>Copy</button></div><pre className="mt-2 text-xs overflow-auto bg-neutral-50 dark:bg-neutral-950 p-3 rounded">{formatAsCssVariables(display)}</pre></div></div>}
 </div>;
};
export default PaletteExtractorTool;
