import React,{useMemo,useState}from'react';
import{Clipboard,Code2}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{buildQueryStringFromLines,compareSemver,dotenvObject,formatDotenv,formatXml,jsonToTypeScript,lookupMime,minifyHtml,normalizeUnicode,parseChmod,parseHttpHeaders,parseQueryString,parseSemver,parseUrl}from'../../utilities/p12-developer';
import{getPublicP12Task,PUBLIC_P12_TASKS}from'../../expansion/publicP12Tasks';
function currentId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
function safe<T>(fn:()=>T){try{return{value:fn(),error:''}}catch(e){return{value:null,error:e instanceof globalThis.Error?e.message:String(e)}}}
const SAMPLE:Record<string,string>={
'xml-formatter':'<catalog><book id="1"><title>Tiny Tools</title><local>true</local></book></catalog>',
'url-parser':'https://example.com:8443/docs/page?q=tiny&q=tools#start',
'query-string-tool':'?q=tiny+tools&category=developer&category=web',
'chmod-calculator':'755',
'json-to-typescript':'{"id":1,"name":"Tiny Tools","active":true,"tags":["local","fast"],"owner":{"name":"Ada"}}',
'http-header-parser':'HTTP/1.1 200 OK\nContent-Type: application/json\nCache-Control: no-store\nX-Request-Id: abc123',
'mime-type-lookup':'.svg',
'unicode-normalizer':'Café — Ångström',
'dotenv-formatter':'# local config\nAPP_NAME = "Tiny Tools"\nDEBUG=true\nPORT = 3000',
'html-minifier':'<!doctype html>\n<html>\n  <body>\n    <!-- remove me -->\n    <h1>Tiny Tools</h1>\n    <p>Local utilities.</p>\n  </body>\n</html>'};
const DeveloperAuthoringTools:React.FC<{initialText?:string}>=({initialText})=>{const task=useMemo(()=>getPublicP12Task(currentId())??PUBLIC_P12_TASKS.find(t=>t.engine==='developer')!,[]),[text,setText]=useState(initialText??SAMPLE[task.id]??''),[secondary,setSecondary]=useState('2.0.0-beta.1'),[mode,setMode]=useState('parse'),[rootName,setRootName]=useState('Root'),[copied,setCopied]=useState(false);const copy=async(v:string)=>{if(await copyToClipboard(v)){setCopied(true);setTimeout(()=>setCopied(false),1000)}};
 const result=useMemo(()=>{switch(task.id){case'xml-formatter':return safe(()=>formatXml(text));case'url-parser':return safe(()=>parseUrl(text));case'query-string-tool':return mode==='build'?safe(()=>buildQueryStringFromLines(text)):safe(()=>parseQueryString(text));case'semver-comparator':return safe(()=>{const cmp=compareSemver(text,secondary);return{left:parseSemver(text),right:parseSemver(secondary),comparison:cmp,relation:cmp<0?'left < right':cmp>0?'left > right':'equal precedence'}});case'chmod-calculator':return safe(()=>parseChmod(text));case'json-to-typescript':return safe(()=>jsonToTypeScript(JSON.parse(text),rootName));case'http-header-parser':return safe(()=>parseHttpHeaders(text));case'mime-type-lookup':return safe(()=>lookupMime(text));case'unicode-normalizer':return safe(()=>normalizeUnicode(text));case'dotenv-formatter':return mode==='object'?safe(()=>dotenvObject(text)):safe(()=>formatDotenv(text));case'html-minifier':return safe(()=>minifyHtml(text));default:return{value:null,error:''}}},[task.id,text,secondary,mode,rootName]);
 return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={['json-formatter','regex-tester','encoding-tools']}><div className="space-y-5"><div className="flex items-center gap-2 rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-2 text-xs text-indigo-700 dark:border-indigo-900 dark:bg-indigo-950/20 dark:text-indigo-300"><Code2 className="h-4 w-4"/>All parsing and generation stays in this browser. Lightweight formatters document their scope instead of claiming full compiler-level semantics.</div>
 {task.id==='query-string-tool'&&<Mode value={mode} set={setMode} options={[['parse','Parse'],['build','Build from key=value lines']]}/>} 
 {task.id==='dotenv-formatter'&&<Mode value={mode} set={setMode} options={[['format','Format'],['object','Parse to JSON object']]}/>} 
 {task.id==='semver-comparator'?<div className="grid gap-3 sm:grid-cols-2"><Input label="Left version" value={text} set={setText}/><Input label="Right version" value={secondary} set={setSecondary}/></div>:task.id==='json-to-typescript'?<><Input label="Root type name" value={rootName} set={setRootName}/><Area label="JSON" value={text} set={setText}/></>:['url-parser','chmod-calculator','mime-type-lookup'].includes(task.id)?<Input label={inputLabel(task.id)} value={text} set={setText}/>:<Area label={inputLabel(task.id)} value={text} set={setText}/>} 
 <Result result={result} copied={copied} copy={copy}/><Limit id={task.id}/></div></ToolShell>};
function inputLabel(id:string){const m:Record<string,string>={'xml-formatter':'XML','url-parser':'Absolute URL','query-string-tool':'Query string or key=value lines','chmod-calculator':'Octal or symbolic permissions','json-to-typescript':'JSON','http-header-parser':'HTTP start line and headers','mime-type-lookup':'Extension or MIME type','unicode-normalizer':'Unicode text','dotenv-formatter':'.env text','html-minifier':'HTML'};return m[id]??'Input'}
function Mode({value,set,options}:{value:string;set:React.Dispatch<React.SetStateAction<string>>;options:string[][]}){return<div className="flex flex-wrap gap-2">{options.map(([v,l])=><button key={v} onClick={()=>set(v)} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${value===v?'bg-neutral-900 text-white dark:bg-neutral-100 dark:text-neutral-900':''}`}>{l}</button>)}</div>}
function Input({label,value,set}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>}){return<label className="block text-xs font-semibold">{label}<input value={value} onChange={e=>set(e.target.value)} spellCheck={false} className="mt-1 w-full rounded border bg-transparent px-3 py-2 font-mono"/></label>}
function Area({label,value,set}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>}){return<label className="block text-xs font-semibold">{label}<textarea rows={10} value={value} onChange={e=>set(e.target.value)} spellCheck={false} className="mt-1 w-full resize-y rounded-xl border bg-transparent p-3 font-mono text-sm"/></label>}
function Result({result,copied,copy}:{result:{value:unknown;error:string};copied:boolean;copy:(v:string)=>Promise<void>}){if(result.error)return<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{result.error}</div>;if(result.value==null)return null;const value=typeof result.value==='string'?result.value:JSON.stringify(result.value,null,2);return<section className="rounded-xl border bg-neutral-50 p-3 dark:bg-neutral-950"><div className="mb-2 flex justify-end"><button onClick={()=>void copy(value)} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Clipboard className="h-3.5 w-3.5"/>{copied?'Copied':'Copy'}</button></div><pre className="max-h-[30rem] overflow-auto whitespace-pre-wrap break-words text-xs">{value}</pre></section>}
function Limit({id}:{id:string}){const notes:Record<string,string>={
'xml-formatter':'Checks balanced start/end tags and formats XML tokens. It does not resolve schemas, namespaces, entities, DTD semantics, or XSD validation.',
'url-parser':'Uses the browser URL parser and requires an absolute URL with a scheme.',
'query-string-tool':'Uses URLSearchParams semantics. Duplicate keys are preserved and exposed as arrays in the parsed object.',
'semver-comparator':'Compares SemVer 2.0-style major/minor/patch and pre-release precedence. Build metadata does not affect precedence.',
'chmod-calculator':'Supports three/four-digit octal modes and nine-character symbolic rwx forms, including setuid/setgid/sticky display bits.',
'json-to-typescript':'Infers structural TypeScript interfaces from one JSON sample. Generated types describe that sample; they do not prove an external API contract.',
'http-header-parser':'Parses header syntax and repeated fields; it does not validate protocol-specific header semantics.',
'mime-type-lookup':'Uses a curated list of common web and document types. Unknown extensions fall back to application/octet-stream.',
'unicode-normalizer':'Uses JavaScript Unicode normalization forms NFC, NFD, NFKC, and NFKD. Compatibility normalization can intentionally change presentation distinctions.',
'dotenv-formatter':'Supports common KEY=value syntax, comments, export prefixes, and basic quoted escapes. Shell expansion and every dotenv-library dialect are outside scope.',
'html-minifier':'Removes ordinary comments and collapses redundant whitespace while protecting pre, textarea, script, and style blocks. It is not an AST-level optimizer.'};return notes[id]?<p className="text-xs text-neutral-500">{notes[id]}</p>:null}
export default DeveloperAuthoringTools;
