import React,{useMemo,useState}from'react';
import{Clipboard,Palette}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{buildBoxShadow,buildCssGradient,buildHtmlTable,buildMetaTags,buildSocialMeta,contrastRatio,cssClamp}from'../../utilities/p12-web';
import{getPublicP12Task,PUBLIC_P12_TASKS}from'../../expansion/publicP12Tasks';
function currentId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
function safe<T>(fn:()=>T){try{return{value:fn(),error:''}}catch(e){return{value:null,error:e instanceof globalThis.Error?e.message:String(e)}}}
const WebAuthoringTools:React.FC=()=>{const task=useMemo(()=>getPublicP12Task(currentId())??PUBLIC_P12_TASKS.find(t=>t.engine==='web')!,[]),[meta,setMeta]=useState({title:'Tiny Tools',description:'Fast privacy-first browser utilities.',canonical:'https://example.com/tools',robots:'index, follow',author:'',themeColor:'#ffffff',viewport:'width=device-width, initial-scale=1'}),[social,setSocial]=useState({title:'Tiny Tools',description:'Fast privacy-first browser utilities.',url:'https://example.com/tools',image:'https://example.com/preview.png',siteName:'Tiny Tools',type:'website',twitterSite:''}),[fg,setFg]=useState('#1F2937'),[bg,setBg]=useState('#FFFFFF'),[gradientType,setGradientType]=useState<'linear'|'radial'>('linear'),[color1,setColor1]=useState('#2563EB'),[color2,setColor2]=useState('#7C3AED'),[angle,setAngle]=useState(135),[shadow,setShadow]=useState({x:0,y:10,blur:30,spread:0,color:'#000000',opacity:.2,inset:false}),[clamp,setClamp]=useState({minSize:16,maxSize:32,minViewport:320,maxViewport:1280}),[table,setTable]=useState('Name,Category,Local\nYAML Formatter,Developer,Yes\nColor Contrast,Design,Yes'),[caption,setCaption]=useState('Tiny Tools'),[className,setClassName]=useState('utility-table'),[header,setHeader]=useState(true),[copied,setCopied]=useState(false);const copy=async(v:string)=>{if(await copyToClipboard(v)){setCopied(true);setTimeout(()=>setCopied(false),1000)}};
 const result=useMemo(()=>{switch(task.id){case'meta-tags-generator':return safe(()=>buildMetaTags(meta));case'open-graph-generator':return safe(()=>buildSocialMeta({...social,twitterCard:'summary_large_image'}));case'color-contrast-checker':return safe(()=>contrastRatio(fg,bg));case'css-gradient-generator':return safe(()=>buildCssGradient(gradientType,[{color:color1,position:0},{color:color2,position:100}],angle));case'box-shadow-generator':return safe(()=>buildBoxShadow(shadow));case'css-clamp-calculator':return safe(()=>cssClamp(clamp.minSize,clamp.maxSize,clamp.minViewport,clamp.maxViewport));case'html-table-generator':return safe(()=>buildHtmlTable(table,{header,caption,className}));default:return{value:null,error:''}},[task.id,meta,social,fg,bg,gradientType,color1,color2,angle,shadow,clamp,table,header,caption,className]);
 return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={['color-converter','aspect-ratio-calculator','qr-studio']}><div className="space-y-5"><div className="flex items-center gap-2 rounded-lg border border-violet-200 bg-violet-50 px-3 py-2 text-xs text-violet-700 dark:border-violet-900 dark:bg-violet-950/20 dark:text-violet-300"><Palette className="h-4 w-4"/>Local generators produce copyable standards-oriented snippets. Preview helpers do not send URLs, colors, or metadata to a server.</div>
 {task.id==='meta-tags-generator'&&<FieldGrid value={meta} set={setMeta}/>} 
 {task.id==='open-graph-generator'&&<FieldGrid value={social} set={setSocial}/>} 
 {task.id==='color-contrast-checker'&&<><div className="grid gap-3 sm:grid-cols-2"><Color label="Foreground" value={fg} set={setFg}/><Color label="Background" value={bg} set={setBg}/></div><div className="rounded-xl border p-6 text-center text-lg font-bold" style={{color:fg,backgroundColor:bg}}>Readable sample text</div>{result.value&&<Contrast value={result.value as ReturnType<typeof contrastRatio>}/>}</>}
 {task.id==='css-gradient-generator'&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-semibold">Type<select value={gradientType} onChange={e=>setGradientType(e.target.value as'linear'|'radial')} className="mt-1 w-full rounded border bg-transparent px-3 py-2"><option value="linear">Linear</option><option value="radial">Radial</option></select></label><Color label="Start" value={color1} set={setColor1}/><Color label="End" value={color2} set={setColor2}/><Num label="Angle (deg)" value={angle} set={setAngle}/></div>{typeof result.value==='string'&&<div className="h-40 rounded-xl border" style={{backgroundImage:result.value}}/>}</>}
 {task.id==='box-shadow-generator'&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Num label="X (px)" value={shadow.x} set={v=>setShadow(s=>({...s,x:v}))}/><Num label="Y (px)" value={shadow.y} set={v=>setShadow(s=>({...s,y:v}))}/><Num label="Blur (px)" value={shadow.blur} set={v=>setShadow(s=>({...s,blur:v}))}/><Num label="Spread (px)" value={shadow.spread} set={v=>setShadow(s=>({...s,spread:v}))}/><Color label="Color" value={shadow.color} set={v=>setShadow(s=>({...s,color:v}))}/><Num label="Opacity" value={shadow.opacity} set={v=>setShadow(s=>({...s,opacity:v}))} step={.05}/><label className="flex items-center gap-2 self-end rounded border px-3 py-2 text-xs font-semibold"><input type="checkbox" checked={shadow.inset} onChange={e=>setShadow(s=>({...s,inset:e.target.checked}))}/>Inset</label></div>{typeof result.value==='string'&&<div className="flex min-h-44 items-center justify-center rounded-xl bg-neutral-100 dark:bg-neutral-900"><div className="h-24 w-40 rounded-xl bg-white dark:bg-neutral-800" style={{boxShadow:result.value}}/></div>}</>}
 {task.id==='css-clamp-calculator'&&<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Num label="Min size (px)" value={clamp.minSize} set={v=>setClamp(s=>({...s,minSize:v}))}/><Num label="Max size (px)" value={clamp.maxSize} set={v=>setClamp(s=>({...s,maxSize:v}))}/><Num label="Min viewport (px)" value={clamp.minViewport} set={v=>setClamp(s=>({...s,minViewport:v}))}/><Num label="Max viewport (px)" value={clamp.maxViewport} set={v=>setClamp(s=>({...s,maxViewport:v}))}/></div>}
 {task.id==='html-table-generator'&&<><Area label="CSV, TSV, or semicolon-delimited data" value={table} set={setTable}/><div className="grid gap-3 sm:grid-cols-2"><Input label="Caption" value={caption} set={setCaption}/><Input label="CSS class" value={className} set={setClassName}/></div><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={header} onChange={e=>setHeader(e.target.checked)}/>Use first row as column headers</label></>}
 {task.id!=='color-contrast-checker'&&<Result result={result} copied={copied} copy={copy}/>}<Limit id={task.id}/></div></ToolShell>};
function FieldGrid({value,set}:{value:Record<string,string>;set:React.Dispatch<React.SetStateAction<any>>}){return<div className="grid gap-3 sm:grid-cols-2">{Object.entries(value).map(([k,v])=><label key={k} className="text-xs font-semibold capitalize">{k.replace(/([A-Z])/g,' $1')}<input value={v} onChange={e=>set((x:any)=>({...x,[k]:e.target.value}))} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>)}</div>}
function Color({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return<label className="text-xs font-semibold">{label}<div className="mt-1 flex gap-2"><input type="color" value={value} onChange={e=>set(e.target.value)} className="h-10 w-14 rounded border bg-transparent p-1"/><input value={value} onChange={e=>set(e.target.value)} className="min-w-0 flex-1 rounded border bg-transparent px-3 py-2 font-mono"/></div></label>}
function Num({label,value,set,step='any'}:{label:string;value:number;set:(v:number)=>void;step?:number|'any'}){return<label className="text-xs font-semibold">{label}<input type="number" step={step} value={value} onChange={e=>set(Number(e.target.value))} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>}
function Input({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return<label className="text-xs font-semibold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>}
function Area({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return<label className="text-xs font-semibold">{label}<textarea rows={9} value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent p-3 font-mono text-sm"/></label>}
function Contrast({value}:{value:ReturnType<typeof contrastRatio>}){const Row=({label,pass}:{label:string;pass:boolean})=><div className="rounded-lg border p-3"><div className="text-[10px] uppercase text-neutral-500">{label}</div><div className="mt-1 text-sm font-bold">{pass?'Pass':'Fail'}</div></div>;return<section className="space-y-3"><div className="text-3xl font-bold">{value.ratio.toFixed(2)}:1</div><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Row label="AA normal" pass={value.aaNormal}/><Row label="AA large" pass={value.aaLarge}/><Row label="AAA normal" pass={value.aaaNormal}/><Row label="AAA large" pass={value.aaaLarge}/></div></section>}
function Result({result,copied,copy}:{result:{value:unknown;error:string};copied:boolean;copy:(v:string)=>Promise<void>}){if(result.error)return<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{result.error}</div>;if(result.value==null)return null;const value=typeof result.value==='string'?result.value:JSON.stringify(result.value,null,2);return<section className="rounded-xl border bg-neutral-50 p-3 dark:bg-neutral-950"><div className="mb-2 flex justify-end"><button onClick={()=>void copy(value)} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Clipboard className="h-3.5 w-3.5"/>{copied?'Copied':'Copy'}</button></div><pre className="max-h-[28rem] overflow-auto whitespace-pre-wrap break-words text-xs">{value}</pre></section>}
function Limit({id}:{id:string}){const notes:Record<string,string>={
'meta-tags-generator':'Generates common HTML metadata. Search engines decide how or whether to use individual tags; this tool does not promise ranking changes.',
'open-graph-generator':'Generates common Open Graph and Twitter/X card metadata. Social platforms may cache previews and apply platform-specific rules.',
'color-contrast-checker':'Uses the WCAG 2.x relative-luminance contrast formula and AA/AAA thresholds. It does not evaluate font size, weight, surrounding UI, or newer perceptual contrast models.',
'css-gradient-generator':'Produces standard linear-gradient() or radial-gradient() CSS from two HEX colors.',
'box-shadow-generator':'Produces one CSS box-shadow layer. Rendering can vary subtly across browsers and compositing contexts.',
'css-clamp-calculator':'Builds a linear viewport-based clamp() expression between two viewport widths. It does not account for container queries or user-defined root scaling.',
'html-table-generator':'Parses ordinary CSV/TSV/semicolon data with quoted CSV fields and HTML-escapes all cell content. Complex spreadsheet formatting is intentionally excluded.'};return notes[id]?<p className="text-xs text-neutral-500">{notes[id]}</p>:null}
export default WebAuthoringTools;
