export interface PublicPdfTask{id:string;pdfTaskId:string;name:string;shortName:string;description:string;keywords:string[];pdfHash:string;featured:boolean}
type Raw=[string,string,string,string,string,string,string,boolean?];
const RAW:Raw[]=[
['merge-pdf','merge-pdfs','Merge PDFs','Merge PDF','Combine multiple PDF files into one document in the order you choose.','merge pdf|combine pdf|join pdf|append pdf|multiple pdf files','#/merge',true],
['scan-to-pdf','scan-to-pdf','Scan to PDF','Scan to PDF','Turn camera captures, JPGs, PNGs, and other images into a PDF, with optional OCR.','scan to pdf|images to pdf|jpg to pdf|png to pdf|photo to pdf|camera scan','#/scan',true],
['edit-pdf','edit-pdf','Edit PDF','Edit PDF','Edit supported PDF text, images, vectors, tables, and added objects locally in the browser.','edit pdf|change pdf|edit pdf text|replace pdf text|pdf editor','#/tools/edit-pdf',true],
['annotate-pdf','annotate-pdf','Annotate PDF','Annotate PDF','Highlight, draw, add notes, shapes, stamps, and review markup to a PDF.','annotate pdf|highlight pdf|comment pdf|draw on pdf|markup pdf|notes','#/tools/annotate-pdf'],
['sign-pdf','visual-signature','Sign PDF','Sign PDF','Place an appearance-only handwritten or image signature on a PDF locally.','sign pdf|signature pdf|add signature|autograph pdf|visual signature','#/tools/visual-signature',true],
['redact-pdf','mark-redaction','Redact PDF','Redact PDF','Mark sensitive areas and then permanently remove the covered PDF content from a derived copy.','redact pdf|blackout pdf|remove sensitive information|privacy pdf|permanent redaction','#/tools/mark-redaction',true],
['organize-pdf-pages','organize-pages','Organize PDF Pages','Organize PDF','Reorder, rotate, duplicate, delete, reverse, or extract pages from a PDF.','organize pdf|reorder pdf pages|rotate pdf|delete pdf pages|extract pdf pages|reverse pdf pages','#/tools/organize-pages',true],
['split-pdf','split-pdf','Split PDF','Split PDF','Divide one multi-page PDF into separate PDF files or page ranges.','split pdf|divide pdf|separate pdf pages|pdf page ranges|extract pages','#/tools/split-pdf',true],
['crop-pdf','crop-pages','Crop PDF Pages','Crop PDF','Trim visible PDF page margins by changing the page CropBox while preserving the original file.','crop pdf|trim pdf margins|pdf cropbox|remove margins|resize pdf page','#/tools/crop-pages'],
['watermark-pdf','watermark-numbering','Watermark & Number PDF','Watermark PDF','Add watermarks, headers, footers, and page numbers to PDF pages.','watermark pdf|page numbers pdf|add page numbers|header pdf|footer pdf|confidential stamp','#/tools/watermark-numbering'],
['fill-pdf-forms','fill-forms','Fill PDF Forms','Fill PDF Forms','Fill supported writable PDF form fields and export the completed document locally.','fill pdf|pdf form|acroform|checkbox pdf|fillable pdf|form fields','#/tools/fill-forms'],
['protect-pdf','password-protect','Password-Protect PDF','Protect PDF','Create a password-protected PDF copy with supported encryption settings.','protect pdf|password pdf|encrypt pdf|lock pdf|secure pdf','#/tools/password-protect',true],
['clean-pdf','sanitize-pdf','Clean Up PDF','Clean PDF','Remove selected metadata, scripts, automatic actions, attachments, links, comments, or form values.','clean pdf|sanitize pdf|remove javascript pdf|remove attachments|pdf privacy|remove metadata','#/tools/sanitize-pdf'],
['ocr-pdf','ocr-pdf','OCR PDF','OCR PDF','Recognize printed text in scanned PDF pages and create a searchable PDF reconstruction locally.','ocr pdf|searchable pdf|scan text pdf|recognize text|tesseract pdf','#/tools/ocr-pdf',true],
['compress-pdf','compress-pdf','Compress PDF','Compress PDF','Reduce PDF file size with preservation-oriented or stronger image-based compression options.','compress pdf|reduce pdf size|make pdf smaller|optimize pdf|shrink pdf','#/tools/compress-pdf',true],
['pdf-metadata','metadata','PDF Metadata Editor','PDF Metadata','View, edit, or remove PDF title, author, subject, keywords, and other document metadata.','pdf metadata|remove pdf metadata|pdf author|pdf title|document properties|privacy','#/tools/metadata'],
['compare-pdf','compare-pdfs','Compare PDFs','Compare PDFs','Compare two PDF versions visually or by extracted text to find changes.','compare pdf|pdf diff|changes between pdfs|original revised pdf|document comparison','#/compare'],
['pdf-page-tools','organize-pages','PDF Page Tools','PDF Page Tools','Use one page workspace for rotate, delete, duplicate, reverse, reorder, and extract operations.','rotate pdf|delete pdf page|duplicate pdf page|reverse pdf|extract page|reorder pages','#/tools/organize-pages'],
];
export const PUBLIC_PDF_TASKS:PublicPdfTask[]=RAW.map(([id,pdfTaskId,name,shortName,description,keys,pdfHash,featured])=>({id,pdfTaskId,name,shortName,description,keywords:keys.split('|'),pdfHash,featured:Boolean(featured)}));
export function getPublicPdfTask(id:string|null|undefined):PublicPdfTask|undefined{return id?PUBLIC_PDF_TASKS.find(task=>task.id===id):undefined}
export function readTinyToolsPdfTaskId(hash:string):string|null{const clean=hash.replace(/^#\/?/,'').split('?')[0];if(!clean)return null;if(clean.startsWith('tool/'))return clean.slice('tool/'.length).split('/')[0]||null;return clean.split('/')[0]||null}
export function buildPdfWorkspaceUrl(task:PublicPdfTask,locationLike?:Pick<Location,'hostname'|'origin'>):string{const hostname=locationLike?.hostname??(typeof window!=='undefined'?window.location.hostname:''),origin=locationLike?.origin??(typeof window!=='undefined'?window.location.origin:'https://thiepn.github.io'),local=hostname==='localhost'||hostname==='127.0.0.1'||hostname==='0.0.0.0',base=local?'https://thiepn.github.io/pdf/':`${origin.replace(/\/$/,'')}/pdf/`;return`${base}${task.pdfHash}`}
export function shouldEmbedPdfWorkspace(hostname:string):boolean{return hostname!=='localhost'&&hostname!=='127.0.0.1'&&hostname!=='0.0.0.0'}
