import React,{useCallback,useEffect,useMemo,useRef,useState}from'react';
import{Maximize,Minimize,Pause,Play,RotateCcw}from'lucide-react';
import{DEFAULT_TELEPROMPTER_CONFIG,calculatePrompterProgress,calculateScrollSpeedForWpm,calculateSpeakingStats,estimateRemainingSeconds,parseTeleprompterCues,stripTeleprompterCueParagraphs,type TeleprompterConfig}from'../../utilities/teleprompter';
const SAMPLE=`Welcome to the presentation.\n\n[[Cue: Demo]]\n\nThis teleprompter can now follow a calibrated speaking pace instead of an arbitrary animation speed.\n\n[[Cue: Close]]\n\nThank you for listening.`;
type FullscreenMode='none'|'native'|'fallback';
export const TeleprompterTool:React.FC=()=>{
 const[script,setScript]=useState(SAMPLE);const[config,setConfig]=useState<TeleprompterConfig>(DEFAULT_TELEPROMPTER_CONFIG);const[wpm,setWpm]=useState(140);const[playing,setPlaying]=useState(false);const[countdownSeconds,setCountdownSeconds]=useState(3);const[countdown,setCountdown]=useState<number|null>(null);const[progress,setProgress]=useState(0);const[fullscreenMode,setFullscreenMode]=useState<FullscreenMode>('none');const[isFullscreen,setIsFullscreen]=useState(false);
 const stageRef=useRef<HTMLDivElement>(null),scrollRef=useRef<HTMLDivElement>(null),frameRef=useRef<number|null>(null),lastRef=useRef<number|null>(null),publishRef=useRef(0);
 const stats=useMemo(()=>calculateSpeakingStats(script,wpm),[script,wpm]),cues=useMemo(()=>parseTeleprompterCues(script),[script]),paragraphs=useMemo(()=>stripTeleprompterCueParagraphs(script),[script]);const remaining=estimateRemainingSeconds(stats.estimatedSeconds,progress);const supportsNative=typeof document!=='undefined'&&typeof Element!=='undefined'&&typeof Element.prototype.requestFullscreen==='function'&&typeof document.exitFullscreen==='function';
 const loop=useCallback((timestamp:number)=>{const el=scrollRef.current;if(!el)return;const previous=lastRef.current??timestamp,last=timestamp-previous;lastRef.current=timestamp;const pxPerSecond=calculateScrollSpeedForWpm(wpm,config.fontSize,config.lineHeight);el.scrollTop+=pxPerSecond*Math.max(0,Math.min(250,last))/1000;if(timestamp-publishRef.current>200){publishRef.current=timestamp;setProgress(calculatePrompterProgress(el.scrollTop,el.clientHeight,el.scrollHeight));}if(el.scrollTop+el.clientHeight>=el.scrollHeight-4){setPlaying(false);setProgress(1);return;}frameRef.current=requestAnimationFrame(loop);},[wpm,config.fontSize,config.lineHeight]);
 useEffect(()=>{if(playing){lastRef.current=null;frameRef.current=requestAnimationFrame(loop);}return()=>{if(frameRef.current!==null)cancelAnimationFrame(frameRef.current);frameRef.current=null;};},[playing,loop]);
 useEffect(()=>{if(countdown===null)return;if(countdown<=0){setCountdown(null);setPlaying(true);return;}const id=window.setTimeout(()=>setCountdown(v=>v===null?null:v-1),1000);return()=>clearTimeout(id);},[countdown]);
 useEffect(()=>{if(!supportsNative)return;const sync=()=>{const active=document.fullscreenElement===stageRef.current;setIsFullscreen(active);setFullscreenMode(active?'native':'none');};document.addEventListener('fullscreenchange',sync);return()=>document.removeEventListener('fullscreenchange',sync);},[supportsNative]);
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.target instanceof HTMLInputElement||event.target instanceof HTMLTextAreaElement)return;if(event.code==='Space'){event.preventDefault();if(playing)setPlaying(false);else if(countdownSeconds)setCountdown(countdownSeconds);else setPlaying(true);}if(event.code==='ArrowUp'&&scrollRef.current)scrollRef.current.scrollTop-=60;if(event.code==='ArrowDown'&&scrollRef.current)scrollRef.current.scrollTop+=60;if(event.key==='Escape'&&fullscreenMode==='fallback'){setFullscreenMode('none');setIsFullscreen(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[playing,countdownSeconds,fullscreenMode]);
 const restart=()=>{if(scrollRef.current)scrollRef.current.scrollTop=0;setProgress(0);setPlaying(false);setCountdown(null);};
 const toggleFullscreen=async()=>{const stage=stageRef.current;if(!stage)return;if(fullscreenMode==='fallback'){setFullscreenMode('none');setIsFullscreen(false);return;}if(supportsNative){if(document.fullscreenElement){try{await document.exitFullscreen();}catch{}return;}try{await stage.requestFullscreen();setFullscreenMode('native');setIsFullscreen(true);return;}catch{}}setFullscreenMode('fallback');setIsFullscreen(true);};
 const jumpCue=(paragraphIndex:number)=>{const el=scrollRef.current;if(!el)return;const total=Math.max(1,script.split(/\n\s*\n/).length-1),ratio=Math.max(0,Math.min(1,paragraphIndex/total));el.scrollTop=(el.scrollHeight-el.clientHeight)*ratio;setProgress(calculatePrompterProgress(el.scrollTop,el.clientHeight,el.scrollHeight));};
 return <div className="space-y-5"><div className="grid lg:grid-cols-2 gap-4"><div><div className="flex justify-between text-xs mb-1"><strong>Prompter script</strong><span>{stats.wordCount} words · ~{stats.formattedDuration}</span></div><textarea rows={10} value={script} onChange={e=>setScript(e.target.value)} className="w-full p-3 border rounded-xl bg-white dark:bg-neutral-900"/><p className="text-[11px] text-neutral-500 mt-1">Add a standalone <code>[[Cue: Demo]]</code> paragraph to create a Cue jump point.</p></div><div className="p-4 border rounded-xl space-y-3"><label className="text-xs">Speaking pace: <strong>{wpm} WPM</strong><input className="w-full" type="range" min={70} max={240} value={wpm} onChange={e=>setWpm(Number(e.target.value))}/></label><label className="text-xs">Text size: <strong>{config.fontSize}px</strong><input className="w-full" type="range" min={24} max={72} value={config.fontSize} onChange={e=>setConfig(c=>({...c,fontSize:Number(e.target.value)}))}/></label><label className="text-xs">Countdown <select value={countdownSeconds} onChange={e=>setCountdownSeconds(Number(e.target.value))} className="ml-1 p-1 border rounded bg-white dark:bg-neutral-900"><option value={0}>Off</option><option value={3}>3 sec</option><option value={5}>5 sec</option><option value={10}>10 sec</option></select></label><div className="flex flex-wrap gap-1">{cues.map(c=><button key={`${c.label}-${c.paragraphIndex}`} onClick={()=>jumpCue(c.paragraphIndex)} className="px-2 py-1 text-xs border rounded">Cue: {c.label}</button>)}</div><div className="text-xs">Progress {Math.round(progress*100)}% · about {Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')} remaining</div><div className="h-1.5 rounded bg-neutral-200"><div className="h-full bg-indigo-600 rounded" style={{width:`${progress*100}%`}}/></div></div></div>
  <div ref={stageRef} data-teleprompter-stage data-fullscreen-mode={fullscreenMode} className={`overflow-hidden shadow-lg border border-slate-800 bg-black flex flex-col ${fullscreenMode==='fallback'?'fixed inset-0 z-50 h-[100dvh] rounded-none':'relative h-[500px] rounded-2xl'}`}><div className="absolute top-4 inset-x-4 z-20 flex justify-between items-center bg-slate-900/85 px-4 py-2 rounded-xl"><div className="flex gap-2">{playing?<button onClick={()=>setPlaying(false)} className="px-4 py-1.5 bg-amber-600 text-white rounded text-xs inline-flex gap-1"><Pause className="w-3 h-3"/>Pause</button>:<button onClick={()=>countdownSeconds?setCountdown(countdownSeconds):setPlaying(true)} className="px-4 py-1.5 bg-indigo-600 text-white rounded text-xs inline-flex gap-1"><Play className="w-3 h-3"/>Start</button>}<button onClick={restart} title="Restart from top" className="p-1.5 text-white"><RotateCcw className="w-4 h-4"/></button></div><button type="button" onClick={()=>void toggleFullscreen()} title="Toggle Fullscreen" aria-label={isFullscreen?'Exit fullscreen':'Enter fullscreen'} className="p-1.5 text-white">{isFullscreen?<Minimize className="w-4 h-4"/>:<Maximize className="w-4 h-4"/>}</button></div>{countdown!==null&&countdown>0&&<div className="absolute inset-0 z-30 grid place-items-center bg-black/70 text-white text-8xl font-bold">{countdown}</div>}<div ref={scrollRef} onScroll={e=>setProgress(calculatePrompterProgress(e.currentTarget.scrollTop,e.currentTarget.clientHeight,e.currentTarget.scrollHeight))} className="flex-1 overflow-y-auto px-8 py-44" style={{transform:config.isMirrored?'scaleX(-1)':'none'}}><div className="mx-auto text-white font-semibold" style={{maxWidth:`${config.marginWidthPercent}%`,fontSize:config.fontSize,lineHeight:config.lineHeight,textAlign:config.textAlign}}>{paragraphs.map((p,i)=><p className="mb-8" key={i}>{p}</p>)}</div></div></div>
 </div>;
};
export default TeleprompterTool;
