import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import { Play, Pause, RotateCcw, Flag, Copy, Check, Timer as TimerIcon, Clock, Flame } from 'lucide-react';
import { ToolShell } from '../../components/tool-shell/ToolShell';
import { copyToClipboard } from '../../utilities/clipboard';
import { playChimeSound, primeTimerAudio } from '../../utilities/timer-audio';

interface LapRecord { lapNumber: number; lapTimeMs: number; totalTimeMs: number; }

export const TimerStopwatchTool: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'timer' | 'stopwatch' | 'pomodoro'>('timer');
  const [timerHours, setTimerHours] = useState(0); const [timerMins, setTimerMins] = useState(5); const [timerSecs, setTimerSecs] = useState(0);
  const [totalTimerDurationMs, setTotalTimerDurationMs] = useState(300000); const [timerRemainingMs, setTimerRemainingMs] = useState(300000); const [isTimerRunning, setIsTimerRunning] = useState(false);
  const timerEndTimestampRef = useRef<number | null>(null); const timerTimeoutRef = useRef<number | null>(null); const timerCompletedRef = useRef(false);

  const [isStopwatchRunning, setIsStopwatchRunning] = useState(false); const [stopwatchElapsedMs, setStopwatchElapsedMs] = useState(0); const [laps, setLaps] = useState<LapRecord[]>([]);
  const stopwatchStartRef = useRef<number | null>(null); const stopwatchAccumulatedRef = useRef(0);

  const [pomoMode, setPomoMode] = useState<'work' | 'shortBreak' | 'longBreak'>('work'); const [pomoWorkMins, setPomoWorkMins] = useState(25); const [pomoShortMins, setPomoShortMins] = useState(5); const [pomoLongMins, setPomoLongMins] = useState(15); const [pomoCycleCount, setPomoCycleCount] = useState(1); const [pomoRemainingMs, setPomoRemainingMs] = useState(25 * 60 * 1000); const [isPomoRunning, setIsPomoRunning] = useState(false);
  const pomoEndTimestampRef = useRef<number | null>(null); const pomoTimeoutRef = useRef<number | null>(null); const pomoCompletedRef = useRef(false);
  const [copiedLaps, setCopiedLaps] = useState(false);

  const formatTime = (totalMs: number, showMs = false) => { const safe=Math.max(0,Number.isFinite(totalMs)?totalMs:0);const seconds=Math.floor(safe/1000),hours=Math.floor(seconds/3600),mins=Math.floor((seconds%3600)/60),secs=seconds%60,centis=Math.floor((safe%1000)/10),pad=(n:number)=>String(n).padStart(2,'0');let base=hours>0?`${pad(hours)}:${pad(mins)}:${pad(secs)}`:`${pad(mins)}:${pad(secs)}`;if(showMs)base+=`.${pad(centis)}`;return base; };
  const clearTimerTimeout=()=>{if(timerTimeoutRef.current!==null){clearTimeout(timerTimeoutRef.current);timerTimeoutRef.current=null;}};
  const clearPomoTimeout=()=>{if(pomoTimeoutRef.current!==null){clearTimeout(pomoTimeoutRef.current);pomoTimeoutRef.current=null;}};

  const completeTimer=useCallback(()=>{if(timerCompletedRef.current)return;timerCompletedRef.current=true;clearTimerTimeout();setTimerRemainingMs(0);setIsTimerRunning(false);timerEndTimestampRef.current=null;playChimeSound();},[]);
  const completePomo=useCallback(()=>{if(pomoCompletedRef.current)return;pomoCompletedRef.current=true;clearPomoTimeout();setIsPomoRunning(false);pomoEndTimestampRef.current=null;playChimeSound();if(pomoMode==='work'){if(pomoCycleCount%4===0){setPomoMode('longBreak');setPomoRemainingMs(pomoLongMins*60000);}else{setPomoMode('shortBreak');setPomoRemainingMs(pomoShortMins*60000);}setPomoCycleCount(value=>value+1);}else{setPomoMode('work');setPomoRemainingMs(pomoWorkMins*60000);}},[pomoMode,pomoCycleCount,pomoLongMins,pomoShortMins,pomoWorkMins]);
  const scheduleTimer=(remaining:number)=>{clearTimerTimeout();timerTimeoutRef.current=window.setTimeout(completeTimer,Math.max(0,remaining)+5);};
  const schedulePomo=(remaining:number)=>{clearPomoTimeout();pomoTimeoutRef.current=window.setTimeout(completePomo,Math.max(0,remaining)+5);};

  useEffect(()=>{let frame:number|undefined;if(isTimerRunning&&timerEndTimestampRef.current!==null){const tick=()=>{const remaining=Math.max(0,timerEndTimestampRef.current!-Date.now());setTimerRemainingMs(remaining);if(remaining<=0){completeTimer();return;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);}return()=>{if(frame!==undefined)cancelAnimationFrame(frame);};},[isTimerRunning,completeTimer]);
  useEffect(()=>{let frame:number|undefined;if(isStopwatchRunning){const tick=()=>{setStopwatchElapsedMs(stopwatchAccumulatedRef.current+(Date.now()-(stopwatchStartRef.current||Date.now())));frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);}return()=>{if(frame!==undefined)cancelAnimationFrame(frame);};},[isStopwatchRunning]);
  useEffect(()=>{let frame:number|undefined;if(isPomoRunning&&pomoEndTimestampRef.current!==null){const tick=()=>{const remaining=Math.max(0,pomoEndTimestampRef.current!-Date.now());setPomoRemainingMs(remaining);if(remaining<=0){completePomo();return;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);}return()=>{if(frame!==undefined)cancelAnimationFrame(frame);};},[isPomoRunning,completePomo]);

  // Browser animation callbacks may pause in a background tab. Absolute end
  // timestamps remain authoritative and are reconciled as soon as visibility returns.
  useEffect(()=>{const sync=()=>{if(document.visibilityState!=='visible')return;if(isTimerRunning&&timerEndTimestampRef.current!==null){const remaining=Math.max(0,timerEndTimestampRef.current-Date.now());setTimerRemainingMs(remaining);if(remaining<=0)completeTimer();}if(isPomoRunning&&pomoEndTimestampRef.current!==null){const remaining=Math.max(0,pomoEndTimestampRef.current-Date.now());setPomoRemainingMs(remaining);if(remaining<=0)completePomo();}};document.addEventListener('visibilitychange',sync);return()=>document.removeEventListener('visibilitychange',sync);},[isTimerRunning,isPomoRunning,completeTimer,completePomo]);
  useEffect(()=>()=>{clearTimerTimeout();clearPomoTimeout();},[]);

  const handleStartTimer=()=>{const duration=(timerHours*3600+timerMins*60+timerSecs)*1000;if(duration<=0)return;primeTimerAudio();timerCompletedRef.current=false;setTotalTimerDurationMs(duration);setTimerRemainingMs(duration);timerEndTimestampRef.current=Date.now()+duration;scheduleTimer(duration);setIsTimerRunning(true);};
  const handlePauseTimer=()=>{if(timerEndTimestampRef.current!==null)setTimerRemainingMs(Math.max(0,timerEndTimestampRef.current-Date.now()));clearTimerTimeout();setIsTimerRunning(false);timerEndTimestampRef.current=null;};
  const handleResumeTimer=()=>{if(timerRemainingMs<=0)return;primeTimerAudio();timerCompletedRef.current=false;timerEndTimestampRef.current=Date.now()+timerRemainingMs;scheduleTimer(timerRemainingMs);setIsTimerRunning(true);};
  const handleResetTimer=()=>{clearTimerTimeout();timerCompletedRef.current=false;setIsTimerRunning(false);timerEndTimestampRef.current=null;const duration=(timerHours*3600+timerMins*60+timerSecs)*1000;setTotalTimerDurationMs(duration);setTimerRemainingMs(duration);};
  const applyTimerPreset=(minutes:number)=>{if(isTimerRunning)return;const total=Math.max(0,Math.round(minutes*60));const hours=Math.floor(total/3600),remaining=total-hours*3600;setTimerHours(hours);setTimerMins(Math.floor(remaining/60));setTimerSecs(remaining%60);const duration=total*1000;setTotalTimerDurationMs(duration);setTimerRemainingMs(duration);timerCompletedRef.current=false;};

  const handleStartStopwatch=()=>{if(isStopwatchRunning)return;stopwatchStartRef.current=Date.now();setIsStopwatchRunning(true);};
  const handlePauseStopwatch=()=>{if(stopwatchStartRef.current!==null){stopwatchAccumulatedRef.current+=Date.now()-stopwatchStartRef.current;stopwatchStartRef.current=null;setStopwatchElapsedMs(stopwatchAccumulatedRef.current);}setIsStopwatchRunning(false);};
  const handleResetStopwatch=()=>{setIsStopwatchRunning(false);stopwatchStartRef.current=null;stopwatchAccumulatedRef.current=0;setStopwatchElapsedMs(0);setLaps([]);};
  const handleRecordLap=()=>{const previous=laps.length?laps[0].totalTimeMs:0;const lap={lapNumber:laps.length+1,lapTimeMs:stopwatchElapsedMs-previous,totalTimeMs:stopwatchElapsedMs};setLaps(current=>[lap,...current]);};
  const handleCopyLaps=async()=>{const formatted=laps.map(lap=>`Lap ${lap.lapNumber}: +${formatTime(lap.lapTimeMs,true)} (Total: ${formatTime(lap.totalTimeMs,true)})`).join('\n');if(await copyToClipboard(formatted)){setCopiedLaps(true);window.setTimeout(()=>setCopiedLaps(false),2000);}};

  const handleStartPomo=()=>{if(pomoRemainingMs<=0)return;primeTimerAudio();pomoCompletedRef.current=false;pomoEndTimestampRef.current=Date.now()+pomoRemainingMs;schedulePomo(pomoRemainingMs);setIsPomoRunning(true);};
  const handlePausePomo=()=>{if(pomoEndTimestampRef.current!==null)setPomoRemainingMs(Math.max(0,pomoEndTimestampRef.current-Date.now()));clearPomoTimeout();setIsPomoRunning(false);pomoEndTimestampRef.current=null;};
  const handleResetPomo=()=>{clearPomoTimeout();pomoCompletedRef.current=false;setIsPomoRunning(false);pomoEndTimestampRef.current=null;const minutes=pomoMode==='work'?pomoWorkMins:pomoMode==='shortBreak'?pomoShortMins:pomoLongMins;setPomoRemainingMs(minutes*60000);};
  const {minLapMs,maxLapMs}=useMemo(()=>{if(laps.length<=1)return{minLapMs:null,maxLapMs:null};const times=laps.map(l=>l.lapTimeMs);return{minLapMs:Math.min(...times),maxLapMs:Math.max(...times)};},[laps]);
  const transferOutput=activeTab==='stopwatch'&&laps.length?laps.map(l=>`Lap ${l.lapNumber}: ${formatTime(l.lapTimeMs,true)} (${formatTime(l.totalTimeMs,true)})`).join('\n'):activeTab==='pomodoro'?`${pomoMode}: ${formatTime(pomoRemainingMs)}`:formatTime(timerRemainingMs);

  return <ToolShell toolId="timer-stopwatch" title="Timer, Stopwatch & Pomodoro" description="Background-resilient countdown timer with primed synth chimes, millisecond split-lap stopwatch, and Pomodoro focus intervals." category="time" relatedToolIds={['time-zone-converter','date-calculator']} outputToTransfer={transferOutput}>
   <div className="space-y-6">
    <div className="flex flex-wrap items-center gap-2 border-b border-neutral-200 dark:border-neutral-800 pb-3">
     <button type="button" onClick={()=>setActiveTab('timer')} className={`px-4 py-2 text-xs font-bold rounded-lg inline-flex items-center gap-1.5 ${activeTab==='timer'?'bg-neutral-900 text-white dark:bg-neutral-100 dark:text-neutral-900':'bg-neutral-100 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-400'}`}><TimerIcon className="w-4 h-4"/>Countdown Timer</button>
     <button type="button" onClick={()=>setActiveTab('stopwatch')} className={`px-4 py-2 text-xs font-bold rounded-lg inline-flex items-center gap-1.5 ${activeTab==='stopwatch'?'bg-neutral-900 text-white dark:bg-neutral-100 dark:text-neutral-900':'bg-neutral-100 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-400'}`}><Clock className="w-4 h-4"/>Precision Stopwatch</button>
     <button type="button" onClick={()=>setActiveTab('pomodoro')} className={`px-4 py-2 text-xs font-bold rounded-lg inline-flex items-center gap-1.5 ${activeTab==='pomodoro'?'bg-neutral-900 text-white dark:bg-neutral-100 dark:text-neutral-900':'bg-neutral-100 dark:bg-neutral-800 text-neutral-600 dark:text-neutral-400'}`}><Flame className="w-4 h-4 text-rose-500"/>Pomodoro Focus</button>
    </div>

    {activeTab==='timer'&&<div className="space-y-6">
     <div className="p-8 bg-neutral-900 text-white rounded-2xl border border-neutral-800 flex flex-col items-center justify-center space-y-6"><div className="font-mono text-5xl sm:text-7xl font-bold tracking-tight text-neutral-100 select-none">{formatTime(timerRemainingMs)}</div><div className="flex items-center gap-3">{!isTimerRunning?<button type="button" onClick={timerRemainingMs<totalTimerDurationMs&&timerRemainingMs>0?handleResumeTimer:handleStartTimer} className="px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white rounded-xl text-sm font-bold inline-flex items-center gap-2"><Play className="w-4 h-4 fill-white"/>{timerRemainingMs<totalTimerDurationMs&&timerRemainingMs>0?'Resume':'Start Timer'}</button>:<button type="button" onClick={handlePauseTimer} className="px-6 py-3 bg-amber-600 text-white rounded-xl text-sm font-bold inline-flex items-center gap-2"><Pause className="w-4 h-4"/>Pause</button>}<button type="button" onClick={handleResetTimer} className="px-4 py-3 bg-neutral-800 text-neutral-300 rounded-xl text-sm font-semibold inline-flex items-center gap-1.5"><RotateCcw className="w-4 h-4"/>Reset</button></div></div>
     <div className="p-4 bg-neutral-50 dark:bg-neutral-950 border border-neutral-200 dark:border-neutral-800 rounded-lg space-y-4"><h4 className="text-xs font-bold uppercase tracking-wider text-neutral-700 dark:text-neutral-300">Set Timer Duration</h4><div className="grid grid-cols-3 gap-3 max-w-sm">{[
      ['Hours',timerHours,(v:number)=>setTimerHours(Math.max(0,Math.min(99,v)))],['Minutes',timerMins,(v:number)=>setTimerMins(Math.max(0,Math.min(59,v)))],['Seconds',timerSecs,(v:number)=>setTimerSecs(Math.max(0,Math.min(59,v)))]
     ].map(([label,value,setter])=><label key={String(label)} className="block text-[11px] font-medium text-neutral-500 text-center">{String(label)}<input type="number" min={0} value={Number(value)} onChange={e=>(setter as (v:number)=>void)(Number(e.target.value))} disabled={isTimerRunning} className="mt-1 w-full text-center py-1.5 text-xs font-mono font-bold bg-white dark:bg-neutral-900 border border-neutral-300 dark:border-neutral-700 rounded disabled:opacity-50"/></label>)}</div><div className="flex flex-wrap items-center gap-2"><span className="text-[11px] text-neutral-400">Presets:</span>{[1,5,10,15,25,30,45,60,90].map(minutes=><button key={minutes} type="button" disabled={isTimerRunning} onClick={()=>applyTimerPreset(minutes)} className="px-2.5 py-1 text-xs font-semibold bg-white dark:bg-neutral-900 border border-neutral-300 dark:border-neutral-700 rounded disabled:opacity-40">{minutes>=60?`${minutes/60}h`:`${minutes}m`}</button>)}</div></div>
    </div>}

    {activeTab==='stopwatch'&&<div className="space-y-6"><div className="p-8 bg-neutral-900 text-white rounded-2xl border border-neutral-800 flex flex-col items-center justify-center space-y-6"><div className="font-mono text-5xl sm:text-7xl font-bold tracking-tight text-neutral-100 select-none">{formatTime(stopwatchElapsedMs,true)}</div><div className="flex items-center gap-3">{!isStopwatchRunning?<button type="button" onClick={handleStartStopwatch} className="px-6 py-3 bg-blue-600 text-white rounded-xl text-sm font-bold inline-flex items-center gap-2"><Play className="w-4 h-4 fill-white"/>Start</button>:<button type="button" onClick={handlePauseStopwatch} className="px-6 py-3 bg-amber-600 text-white rounded-xl text-sm font-bold inline-flex items-center gap-2"><Pause className="w-4 h-4"/>Pause</button>}<button type="button" onClick={handleRecordLap} disabled={!isStopwatchRunning} className="px-4 py-3 bg-neutral-800 text-neutral-300 rounded-xl text-sm font-semibold inline-flex items-center gap-1.5 disabled:opacity-40"><Flag className="w-4 h-4"/>Lap</button><button type="button" onClick={handleResetStopwatch} className="px-4 py-3 bg-neutral-800 text-neutral-300 rounded-xl text-sm font-semibold inline-flex items-center gap-1.5"><RotateCcw className="w-4 h-4"/>Reset</button></div></div>{laps.length>0&&<div className="p-4 bg-neutral-50 dark:bg-neutral-950 border border-neutral-200 dark:border-neutral-800 rounded-lg space-y-3"><div className="flex items-center justify-between"><h4 className="text-xs font-bold uppercase tracking-wider">Recorded Laps ({laps.length})</h4><button type="button" onClick={()=>void handleCopyLaps()} className="px-2.5 py-1 text-xs font-semibold rounded bg-white dark:bg-neutral-900 border border-neutral-300 dark:border-neutral-700 inline-flex items-center gap-1">{copiedLaps?<Check className="w-3.5 h-3.5 text-emerald-600"/>:<Copy className="w-3.5 h-3.5"/>}{copiedLaps?'Copied Laps':'Copy All'}</button></div><div className="space-y-1.5 max-h-64 overflow-y-auto">{laps.map(lap=>{const fastest=minLapMs!==null&&lap.lapTimeMs===minLapMs,slowest=maxLapMs!==null&&lap.lapTimeMs===maxLapMs;return <div key={lap.lapNumber} className={`flex items-center justify-between p-2.5 rounded text-xs font-mono border ${fastest?'bg-emerald-50 dark:bg-emerald-950/40 border-emerald-300':slowest?'bg-rose-50 dark:bg-rose-950/40 border-rose-300':'bg-white dark:bg-neutral-900 border-neutral-200 dark:border-neutral-800'}`}><span>#{lap.lapNumber}{fastest?' · fastest':slowest?' · slowest':''}</span><span><strong>+{formatTime(lap.lapTimeMs,true)}</strong> · {formatTime(lap.totalTimeMs,true)}</span></div>;})}</div></div>}</div>}

    {activeTab==='pomodoro'&&<div className="space-y-6"><div className="p-8 bg-neutral-900 text-white rounded-2xl border border-neutral-800 flex flex-col items-center justify-center space-y-5"><div className="flex items-center gap-2 px-3 py-1 bg-neutral-800 rounded-full text-xs font-bold uppercase tracking-wider text-rose-400"><Flame className="w-3.5 h-3.5 fill-rose-400"/>{pomoMode==='work'?'Focus Work':pomoMode==='shortBreak'?'Short Break':'Long Break'} • Cycle {pomoCycleCount}</div><div className="font-mono text-5xl sm:text-7xl font-bold tracking-tight">{formatTime(pomoRemainingMs)}</div><div className="flex items-center gap-3">{!isPomoRunning?<button type="button" onClick={handleStartPomo} className="px-6 py-3 bg-rose-600 text-white rounded-xl text-sm font-bold inline-flex items-center gap-2"><Play className="w-4 h-4 fill-white"/>Start Interval</button>:<button type="button" onClick={handlePausePomo} className="px-6 py-3 bg-amber-600 text-white rounded-xl text-sm font-bold inline-flex items-center gap-2"><Pause className="w-4 h-4"/>Pause</button>}<button type="button" onClick={handleResetPomo} className="px-4 py-3 bg-neutral-800 text-neutral-300 rounded-xl text-sm font-semibold inline-flex items-center gap-1.5"><RotateCcw className="w-4 h-4"/>Reset</button></div></div><div className="p-4 bg-neutral-50 dark:bg-neutral-950 border border-neutral-200 dark:border-neutral-800 rounded-lg space-y-3"><h4 className="text-xs font-bold uppercase tracking-wider">Interval Durations (Minutes)</h4><div className="grid grid-cols-3 gap-3">{[['Focus Work',pomoWorkMins,setPomoWorkMins,90],['Short Break',pomoShortMins,setPomoShortMins,30],['Long Break',pomoLongMins,setPomoLongMins,60]].map(([label,value,setter,max])=><label key={String(label)} className="block text-[11px] font-medium text-neutral-500">{String(label)}<input type="number" min={1} max={Number(max)} value={Number(value)} disabled={isPomoRunning} onChange={e=>(setter as React.Dispatch<React.SetStateAction<number>>)(Math.max(1,Math.min(Number(max),Number(e.target.value))))} className="mt-1 w-full px-2.5 py-1.5 text-xs font-mono font-bold bg-white dark:bg-neutral-900 border border-neutral-300 dark:border-neutral-700 rounded disabled:opacity-50"/></label>)}</div></div></div>}
   </div>
  </ToolShell>;
};
export default TimerStopwatchTool;
