import React, { useEffect, useMemo, useRef, useState } from 'react';
import JSZip from 'jszip';
import { Download, Image as ImageIcon, Loader2, ShieldCheck, Upload } from 'lucide-react';
import { ToolShell } from '../../components/tool-shell/ToolShell';
import { getPublicImageTask, PUBLIC_IMAGE_TASKS } from '../../image/publicImageTasks';
import { processImageCanvas, type OutputFormat, type CropRect } from '../../utilities/image-optimizer';
import { removeBackgroundLocal } from '../../utilities/background-remover';
import {
  SOCIAL_IMAGE_PRESETS,
  buildIcoFromPng,
  centerCropForAspect,
  contactSheetLayout,
  coverCrop,
  gridRegions,
  metadataPrivacySummary,
  outputExtension,
  parseJpegExif,
  safeImageBaseName,
} from '../../utilities/image-micro-tools';

function readTaskId(hash:string){const clean=hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0];}
function downloadBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function loadImage(blob:Blob):Promise<HTMLImageElement>{return new Promise((resolve,reject)=>{const url=URL.createObjectURL(blob),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img);};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('This browser could not decode the selected image format.'));};img.src=url;});}
function canvasBlob(canvas:HTMLCanvasElement,type:string,quality=.9){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(new Error('Image export failed.')),type,quality));}
function formatName(file:File|undefined,format:OutputFormat){return`${safeImageBaseName(file?.name||'image')}-converted.${outputExtension(format)}`;}

type NumericSetter=React.Dispatch<React.SetStateAction<number>>;

export const ImageMicroTools:React.FC=()=>{
  const task=useMemo(()=>getPublicImageTask(typeof window!=='undefined'?readTaskId(window.location.hash):'')??PUBLIC_IMAGE_TASKS[0],[]);
  const [file,setFile]=useState<File|null>(null),[files,setFiles]=useState<File[]>([]),[image,setImage]=useState<HTMLImageElement|null>(null),[secondFile,setSecondFile]=useState<File|null>(null),[secondUrl,setSecondUrl]=useState(''),[sourceUrl,setSourceUrl]=useState('');
  const [format,setFormat]=useState<OutputFormat>('image/png'),[quality,setQuality]=useState(.9),[width,setWidth]=useState(1080),[height,setHeight]=useState(1080),[rotation,setRotation]=useState(90),[flipH,setFlipH]=useState(false),[flipV,setFlipV]=useState(false),[ratio,setRatio]=useState('1:1'),[targetKb,setTargetKb]=useState(300),[strength,setStrength]=useState(12),[rows,setRows]=useState(3),[columns,setColumns]=useState(3),[border,setBorder]=useState(24),[color,setColor]=useState('#ffffff'),[slider,setSlider]=useState(50),[preset,setPreset]=useState('instagram-square'),[scale,setScale]=useState(2),[focusX,setFocusX]=useState(.5),[focusY,setFocusY]=useState(.35),[region,setRegion]=useState({x:25,y:25,width:50,height:30});
  const [brightness,setBrightness]=useState(100),[contrast,setContrast]=useState(100),[saturation,setSaturation]=useState(100),[grayscale,setGrayscale]=useState(0),[sepia,setSepia]=useState(0),[hue,setHue]=useState(0);
  const [busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[metadata,setMetadata]=useState<string[]>([]);
  const inputRef=useRef<HTMLInputElement>(null),secondRef=useRef<HTMLInputElement>(null);

  useEffect(()=>()=>{if(sourceUrl)URL.revokeObjectURL(sourceUrl);if(secondUrl)URL.revokeObjectURL(secondUrl);},[sourceUrl,secondUrl]);
  useEffect(()=>{if(!file||task.id!=='image-metadata-cleaner'){setMetadata([]);return;}void file.arrayBuffer().then(b=>setMetadata(metadataPrivacySummary(parseJpegExif(new Uint8Array(b)))));},[file,task.id]);

  const multi=['batch-image-converter','contact-sheet-maker'].includes(task.id);
  const accept=task.id==='svg-to-image'?'.svg,image/svg+xml':task.id==='heic-image-converter'?'.heic,.heif,image/heic,image/heif':'image/*,.heic,.heif,.svg';
  const pick=async(list:FileList|null)=>{if(!list?.length)return;setError('');const selected=[...list];setFiles(multi?selected:[selected[0]]);setFile(selected[0]);try{const img=await loadImage(selected[0]);setImage(img);setWidth(img.naturalWidth);setHeight(img.naturalHeight);if(sourceUrl)URL.revokeObjectURL(sourceUrl);setSourceUrl(URL.createObjectURL(selected[0]));}catch(e){setImage(null);setError(e instanceof Error?e.message:'Unable to decode image.');}};
  const pickSecond=async(list:FileList|null)=>{if(!list?.[0])return;setSecondFile(list[0]);try{await loadImage(list[0]);if(secondUrl)URL.revokeObjectURL(secondUrl);setSecondUrl(URL.createObjectURL(list[0]));}catch(e){setError(e instanceof Error?e.message:'Unable to decode second image.');}};

  const exportStandard=async(crop:CropRect|null=null,targetW=width,targetH=height,opts:{rotation?:number;flipH?:boolean;flipV?:boolean;format?:OutputFormat;quality?:number}={})=>{if(!image)throw new Error('Choose an image first.');return processImageCanvas(image,{targetWidth:Math.max(1,targetW),targetHeight:Math.max(1,targetH),rotationDeg:opts.rotation??0,flipH:opts.flipH??false,flipV:opts.flipV??false,crop,format:opts.format??format,quality:opts.quality??quality});};
  const renderFilteredCanvas=()=>{if(!image)throw new Error('Choose an image first.');const c=document.createElement('canvas');c.width=image.naturalWidth;c.height=image.naturalHeight;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas is unavailable.');ctx.filter=`brightness(${brightness}%) contrast(${contrast}%) saturate(${saturation}%) grayscale(${grayscale}%) sepia(${sepia}%) hue-rotate(${hue}deg)`;ctx.drawImage(image,0,0);return c;};

  const process=async()=>{setBusy(true);setError('');setStatus('Processing locally…');try{
    if(task.id==='image-compare'){if(!file||!secondFile)throw new Error('Choose two images to compare.');setStatus('Comparison ready.');return;}
    if(task.id==='batch-image-converter'){if(!files.length)throw new Error('Choose images first.');const zip=new JSZip();for(let i=0;i<files.length;i++){setStatus(`Converting ${i+1}/${files.length}…`);const img=await loadImage(files[i]),r=await processImageCanvas(img,{targetWidth:img.naturalWidth,targetHeight:img.naturalHeight,rotationDeg:0,flipH:false,flipV:false,format,quality});zip.file(`${safeImageBaseName(files[i].name)}.${outputExtension(format)}`,await r.blob.arrayBuffer());URL.revokeObjectURL(r.url);}downloadBlob(await zip.generateAsync({type:'blob',compression:'DEFLATE'}),'converted-images.zip');setStatus('Batch ready.');return;}
    if(task.id==='contact-sheet-maker'){if(!files.length)throw new Error('Choose images first.');const loaded=await Promise.all(files.map(loadImage)),thumbW=240,thumbH=180,layout=contactSheetLayout(loaded.length,thumbW,thumbH,columns,12,16),c=document.createElement('canvas');c.width=layout.width;c.height=layout.height;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable.');ctx.fillStyle=color;ctx.fillRect(0,0,c.width,c.height);loaded.forEach((img,i)=>{const col=i%layout.columns,row=Math.floor(i/layout.columns),x=16+col*(thumbW+12),y=16+row*(thumbH+12),crop=coverCrop(img.naturalWidth,img.naturalHeight,thumbW,thumbH);ctx.drawImage(img,crop.x,crop.y,crop.width,crop.height,x,y,thumbW,thumbH);});downloadBlob(await canvasBlob(c,'image/png'),'contact-sheet.png');setStatus('Contact sheet ready.');return;}
    if(!image||!file)throw new Error('Choose an image first.');
    if(task.id==='crop-image'){const a=ratio==='free'?image.naturalWidth/image.naturalHeight:ratio==='4:5'?4/5:ratio==='16:9'?16/9:1,crop=centerCropForAspect(image.naturalWidth,image.naturalHeight,a),r=await exportStandard(crop,Math.round(crop.width),Math.round(crop.height));downloadBlob(r.blob,formatName(file,format));URL.revokeObjectURL(r.url);}
    else if(task.id==='rotate-flip-image'){const rotated=Math.abs(rotation%180)===90,r=await exportStandard(null,rotated?image.naturalHeight:image.naturalWidth,rotated?image.naturalWidth:image.naturalHeight,{rotation,flipH,flipV});downloadBlob(r.blob,formatName(file,format));URL.revokeObjectURL(r.url);}
    else if(['heic-image-converter','avif-image-converter','svg-to-image','image-format-converter','image-metadata-cleaner'].includes(task.id)){const r=await exportStandard(null,width,height);downloadBlob(r.blob,formatName(file,format));URL.revokeObjectURL(r.url);}
    else if(task.id==='compress-image-to-size'){if(format==='image/png')throw new Error('Target-size compression needs JPEG or WebP because PNG quality is lossless.');let low=.1,high=.98,best:Blob|null=null,bestDiff=Infinity;for(let i=0;i<8;i++){const q=(low+high)/2,r=await exportStandard(null,width,height,{quality:q}),diff=Math.abs(r.blob.size-targetKb*1024);if(diff<bestDiff){best=r.blob;bestDiff=diff;}if(r.blob.size>targetKb*1024)high=q;else low=q;URL.revokeObjectURL(r.url);}if(!best)throw new Error('Unable to produce compressed image.');downloadBlob(best,`${safeImageBaseName(file.name)}-${targetKb}kb.${outputExtension(format)}`);}
    else if(task.id==='profile-picture-maker'){const crop=centerCropForAspect(image.naturalWidth,image.naturalHeight,1),size=Math.min(1080,Math.round(crop.width)),base=await exportStandard(crop,size,size,{format:'image/png'}),img=await loadImage(base.blob),c=document.createElement('canvas');c.width=c.height=size;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable.');ctx.save();ctx.beginPath();ctx.arc(size/2,size/2,size/2,0,Math.PI*2);ctx.clip();ctx.drawImage(img,0,0,size,size);ctx.restore();downloadBlob(await canvasBlob(c,'image/png'),`${safeImageBaseName(file.name)}-profile.png`);URL.revokeObjectURL(base.url);}
    else if(task.id==='blur-pixelate-image'){const c=document.createElement('canvas');c.width=image.naturalWidth;c.height=image.naturalHeight;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable.');if(strength<=25){ctx.filter=`blur(${Math.max(1,strength)}px)`;ctx.drawImage(image,0,0);}else{const factor=Math.max(2,Math.round(strength/3)),sw=Math.max(1,Math.round(c.width/factor)),sh=Math.max(1,Math.round(c.height/factor)),tmp=document.createElement('canvas');tmp.width=sw;tmp.height=sh;const t=tmp.getContext('2d');if(!t)throw new Error('Canvas unavailable.');t.imageSmoothingEnabled=false;t.drawImage(image,0,0,sw,sh);ctx.imageSmoothingEnabled=false;ctx.drawImage(tmp,0,0,c.width,c.height);}downloadBlob(await canvasBlob(c,format,quality),formatName(file,format));}
    else if(task.id==='privacy-blur-image'){const c=document.createElement('canvas');c.width=image.naturalWidth;c.height=image.naturalHeight;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable.');ctx.drawImage(image,0,0);const rx=c.width*region.x/100,ry=c.height*region.y/100,rw=c.width*region.width/100,rh=c.height*region.height/100,tmp=document.createElement('canvas');tmp.width=Math.max(1,Math.round(rw/16));tmp.height=Math.max(1,Math.round(rh/16));tmp.getContext('2d')?.drawImage(c,rx,ry,rw,rh,0,0,tmp.width,tmp.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(tmp,0,0,tmp.width,tmp.height,rx,ry,rw,rh);downloadBlob(await canvasBlob(c,format,quality),`${safeImageBaseName(file.name)}-redacted.${outputExtension(format)}`);}
    else if(task.id==='social-media-image-resizer'){const p=SOCIAL_IMAGE_PRESETS.find(x=>x.id===preset)??SOCIAL_IMAGE_PRESETS[0],crop=coverCrop(image.naturalWidth,image.naturalHeight,p.width,p.height),r=await exportStandard(crop,p.width,p.height);downloadBlob(r.blob,`${safeImageBaseName(file.name)}-${p.id}.${outputExtension(format)}`);URL.revokeObjectURL(r.url);}
    else if(task.id==='favicon-maker'){const crop=centerCropForAspect(image.naturalWidth,image.naturalHeight,1),r=await exportStandard(crop,256,256,{format:'image/png'}),png=new Uint8Array(await r.blob.arrayBuffer()),ico=buildIcoFromPng(png,256,256);downloadBlob(new Blob([ico],{type:'image/x-icon'}),'favicon.ico');downloadBlob(r.blob,'favicon-256.png');URL.revokeObjectURL(r.url);}
    else if(task.id==='image-grid-splitter'){const zip=new JSZip();for(const [i,g] of gridRegions(image.naturalWidth,image.naturalHeight,rows,columns).entries()){const r=await exportStandard(g,g.width,g.height);zip.file(`tile-${String(i+1).padStart(2,'0')}.${outputExtension(format)}`,await r.blob.arrayBuffer());URL.revokeObjectURL(r.url);}downloadBlob(await zip.generateAsync({type:'blob'}),'image-tiles.zip');}
    else if(task.id==='image-border-frame'){const c=document.createElement('canvas'),b=Math.max(0,Math.round(border));c.width=image.naturalWidth+b*2;c.height=image.naturalHeight+b*2;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable.');ctx.fillStyle=color;ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(image,b,b);downloadBlob(await canvasBlob(c,format,quality),`${safeImageBaseName(file.name)}-framed.${outputExtension(format)}`);}
    else if(task.id==='photo-filters'){downloadBlob(await canvasBlob(renderFilteredCanvas(),format,quality),`${safeImageBaseName(file.name)}-filtered.${outputExtension(format)}`);}
    else if(task.id==='transparent-image-maker'||task.id==='background-changer'){setStatus('Running local background removal…');const fgBlob=await removeBackgroundLocal(file,s=>setStatus(s));if(task.id==='transparent-image-maker')downloadBlob(fgBlob,`${safeImageBaseName(file.name)}-transparent.png`);else{const fg=await loadImage(fgBlob),c=document.createElement('canvas');c.width=fg.naturalWidth;c.height=fg.naturalHeight;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable.');ctx.fillStyle=color;ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(fg,0,0);downloadBlob(await canvasBlob(c,format,quality),`${safeImageBaseName(file.name)}-background.${outputExtension(format)}`);}}
    else if(task.id==='image-upscaler'){const factor=Math.max(1,Math.min(4,scale)),r=await exportStandard(null,Math.round(image.naturalWidth*factor),Math.round(image.naturalHeight*factor));downloadBlob(r.blob,`${safeImageBaseName(file.name)}-${factor}x.${outputExtension(format)}`);URL.revokeObjectURL(r.url);}
    else if(task.id==='headshot-cropper'){const aspect=ratio==='4:5'?4/5:ratio==='1:1'?1:3/4,crop=coverCrop(image.naturalWidth,image.naturalHeight,aspect*1000,1000,focusX,focusY),targetH=1200,targetW=Math.round(targetH*aspect),r=await exportStandard(crop,targetW,targetH);downloadBlob(r.blob,`${safeImageBaseName(file.name)}-headshot.${outputExtension(format)}`);URL.revokeObjectURL(r.url);}
    setStatus('Done.');
  }catch(e){setError(e instanceof Error?e.message:'Image processing failed.');setStatus('');}finally{setBusy(false);}};

  const ratioControls=['crop-image','headshot-cropper'].includes(task.id),formatControls=!['favicon-maker','transparent-image-maker','contact-sheet-maker','image-compare'].includes(task.id),dimensionControls=['heic-image-converter','avif-image-converter','svg-to-image','image-format-converter','image-metadata-cleaner','compress-image-to-size'].includes(task.id);
  const filterControls:Array<[string,number,NumericSetter,number,number]>=[['Brightness',brightness,setBrightness,0,200],['Contrast',contrast,setContrast,0,200],['Saturation',saturation,setSaturation,0,200],['Grayscale',grayscale,setGrayscale,0,100],['Sepia',sepia,setSepia,0,100],['Hue',hue,setHue,-180,180]];

  return <ToolShell toolId={task.id} title={task.name} description={task.description} category="image" relatedToolIds={['image-optimizer','background-remover','image-annotator','image-collage']}>
    <div className="space-y-5">
      <div className="flex items-start gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs leading-5 text-emerald-900 dark:border-emerald-900/70 dark:bg-emerald-950/20 dark:text-emerald-200"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0"/><span>Image pixels are processed locally in your browser. HEIC/HEIF and AVIF depend on the browser's installed decoder support.</span></div>
      <input ref={inputRef} type="file" accept={accept} multiple={multi} className="hidden" onChange={e=>void pick(e.target.files)}/><input ref={secondRef} type="file" accept="image/*" className="hidden" onChange={e=>void pickSecond(e.target.files)}/>
      <button type="button" onClick={()=>inputRef.current?.click()} className="w-full rounded-xl border-2 border-dashed border-neutral-300 p-8 text-center dark:border-neutral-700"><Upload className="mx-auto mb-2 h-6 w-6"/><span className="font-semibold">{multi?'Choose images':'Choose an image'}</span>{file&&<span className="mt-1 block text-xs text-neutral-500">{multi?`${files.length} image(s) selected`:file.name}</span>}</button>
      {task.id==='image-compare'&&<button type="button" onClick={()=>secondRef.current?.click()} className="w-full rounded-lg border border-neutral-300 px-3 py-2 text-sm dark:border-neutral-700">Choose second image{secondFile?` — ${secondFile.name}`:''}</button>}
      {sourceUrl&&task.id==='image-compare'&&secondUrl?<div className="relative overflow-hidden rounded-xl border border-neutral-200 bg-neutral-100 dark:border-neutral-800"><img src={secondUrl} className="block w-full" alt="Second comparison"/><div className="absolute inset-y-0 left-0 overflow-hidden" style={{width:`${slider}%`}}><img src={sourceUrl} className="h-full max-w-none object-cover" style={{width:'100vw'}} alt="First comparison"/></div><input aria-label="Comparison reveal" type="range" min="0" max="100" value={slider} onChange={e=>setSlider(Number(e.target.value))} className="absolute bottom-3 left-4 right-4 w-[calc(100%-2rem)]"/></div>:sourceUrl&&<img src={sourceUrl} className="mx-auto max-h-[420px] max-w-full rounded-xl border border-neutral-200 object-contain dark:border-neutral-800" alt="Selected preview"/>}
      <section className="grid gap-3 rounded-xl border border-neutral-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-3 dark:border-neutral-800 dark:bg-neutral-950">
        {formatControls&&<label className="text-xs font-semibold">Output format<select value={format} onChange={e=>setFormat(e.target.value as OutputFormat)} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700"><option value="image/png">PNG</option><option value="image/jpeg">JPEG</option><option value="image/webp">WebP</option></select></label>}
        {formatControls&&format!=='image/png'&&<label className="text-xs font-semibold">Quality {Math.round(quality*100)}%<input type="range" min="0.2" max="1" step="0.01" value={quality} onChange={e=>setQuality(Number(e.target.value))} className="mt-2 w-full"/></label>}
        {dimensionControls&&<><label className="text-xs font-semibold">Width<input type="number" min="1" value={width} onChange={e=>setWidth(Math.max(1,Number(e.target.value)))} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700"/></label><label className="text-xs font-semibold">Height<input type="number" min="1" value={height} onChange={e=>setHeight(Math.max(1,Number(e.target.value)))} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700"/></label></>}
        {ratioControls&&<label className="text-xs font-semibold">Crop ratio<select value={ratio} onChange={e=>setRatio(e.target.value)} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700"><option value="1:1">1:1</option><option value="4:5">4:5</option><option value="3:4">3:4</option>{task.id==='crop-image'&&<><option value="16:9">16:9</option><option value="free">Original</option></>}</select></label>}
        {task.id==='rotate-flip-image'&&<><label className="text-xs font-semibold">Rotation<select value={rotation} onChange={e=>setRotation(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700"><option value={90}>90°</option><option value={180}>180°</option><option value={270}>270°</option></select></label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={flipH} onChange={e=>setFlipH(e.target.checked)}/>Flip horizontal</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={flipV} onChange={e=>setFlipV(e.target.checked)}/>Flip vertical</label></>}
        {task.id==='compress-image-to-size'&&<label className="text-xs font-semibold">Target size (KB)<input type="number" min="10" value={targetKb} onChange={e=>setTargetKb(Math.max(10,Number(e.target.value)))} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700"/></label>}
        {task.id==='social-media-image-resizer'&&<label className="text-xs font-semibold">Preset<select value={preset} onChange={e=>setPreset(e.target.value)} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700">{SOCIAL_IMAGE_PRESETS.map(p=><option key={p.id} value={p.id}>{p.label} — {p.width}×{p.height}</option>)}</select></label>}
        {task.id==='blur-pixelate-image'&&<label className="text-xs font-semibold">Strength {strength}<input type="range" min="1" max="60" value={strength} onChange={e=>setStrength(Number(e.target.value))} className="mt-2 w-full"/></label>}
        {task.id==='privacy-blur-image'&&Object.entries(region).map(([k,v])=><label key={k} className="text-xs font-semibold">{k} %<input type="number" min="0" max="100" value={v} onChange={e=>setRegion(r=>({...r,[k]:Number(e.target.value)}))} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700"/></label>)}
        {task.id==='image-grid-splitter'&&<><label className="text-xs font-semibold">Rows<input type="number" min="1" max="20" value={rows} onChange={e=>setRows(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700"/></label><label className="text-xs font-semibold">Columns<input type="number" min="1" max="20" value={columns} onChange={e=>setColumns(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700"/></label></>}
        {task.id==='contact-sheet-maker'&&<label className="text-xs font-semibold">Columns<input type="number" min="1" max="12" value={columns} onChange={e=>setColumns(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700"/></label>}
        {task.id==='image-border-frame'&&<label className="text-xs font-semibold">Border width (px)<input type="number" min="0" max="1000" value={border} onChange={e=>setBorder(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700"/></label>}
        {['image-border-frame','background-changer','contact-sheet-maker'].includes(task.id)&&<label className="text-xs font-semibold">Color<input type="color" value={color} onChange={e=>setColor(e.target.value)} className="mt-1 h-10 w-full rounded-lg border border-neutral-300 bg-transparent p-1 dark:border-neutral-700"/></label>}
        {task.id==='photo-filters'&&filterControls.map(([label,val,setter,min,max])=><label key={label} className="text-xs font-semibold">{label} {val}<input type="range" min={min} max={max} value={val} onChange={e=>setter(Number(e.target.value))} className="mt-2 w-full"/></label>)}
        {task.id==='image-upscaler'&&<label className="text-xs font-semibold">Scale<select value={scale} onChange={e=>setScale(Number(e.target.value))} className="mt-1 w-full rounded-lg border border-neutral-300 bg-transparent px-3 py-2 dark:border-neutral-700"><option value={1.5}>1.5×</option><option value={2}>2×</option><option value={3}>3×</option><option value={4}>4×</option></select></label>}
        {task.id==='headshot-cropper'&&<><label className="text-xs font-semibold">Horizontal focus<input type="range" min="0" max="1" step="0.01" value={focusX} onChange={e=>setFocusX(Number(e.target.value))} className="mt-2 w-full"/></label><label className="text-xs font-semibold">Vertical focus<input type="range" min="0" max="1" step="0.01" value={focusY} onChange={e=>setFocusY(Number(e.target.value))} className="mt-2 w-full"/></label></>}
      </section>
      {metadata.length>0&&<div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-200"><strong>Detected metadata:</strong><ul className="mt-1 list-disc pl-5">{metadata.map(x=><li key={x}>{x}</li>)}</ul><p className="mt-2">Exporting creates a freshly encoded image and strips source metadata chunks.</p></div>}
      {error&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{error}</div>}
      <button type="button" disabled={busy} onClick={()=>void process()} className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50 dark:bg-neutral-100 dark:text-neutral-900">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Download className="h-4 w-4"/>}{task.id==='image-compare'?'Prepare comparison':'Process & download'}</button>{status&&<span className="ml-3 text-xs text-neutral-500">{status}</span>}
      {task.id==='image-upscaler'&&<div className="flex items-start gap-2 rounded-lg border border-blue-200 bg-blue-50 p-3 text-xs text-blue-900 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-200"><ImageIcon className="mt-0.5 h-4 w-4 shrink-0"/><span>This is high-quality resampling. It can enlarge pixels smoothly but does not invent real detail the source image did not contain.</span></div>}
    </div>
  </ToolShell>;
};

export default ImageMicroTools;
