import React,{useEffect,useMemo,useState}from'react';
import{Clock,ShieldCheck}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{calendarAge,countdownParts,durationBetween,isoWeekInfo,minutesLabel,parseTimesheet}from'../../utilities/everyday-docs';
import{getPublicEverydayTask,PUBLIC_EVERYDAY_TASKS}from'../../everyday/publicEverydayTasks';
function currentId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
function localDate(d=new Date()){const y=d.getFullYear(),m=String(d.getMonth()+1).padStart(2,'0'),day=String(d.getDate()).padStart(2,'0');return`${y}-${m}-${day}`}
function localDateTime(d=new Date()){const y=localDate(d),h=String(d.getHours()).padStart(2,'0'),m=String(d.getMinutes()).padStart(2,'0');return`${y}T${h}:${m}`}
const PlanningTools:React.FC=()=>{const task=useMemo(()=>getPublicEverydayTask(currentId())??PUBLIC_EVERYDAY_TASKS.find(t=>t.group==='planning')!,[]);return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={['date-calculator','timer-stopwatch','calendar-event-maker']}><div className="space-y-5"><div className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-300"><ShieldCheck className="h-4 w-4"/>Calculations run locally and use your browser’s date/time interpretation where a clock time is involved.</div>{task.id==='countdown-to-date'?<Countdown/>:task.id==='work-hours-timesheet'?<Timesheet/>:task.id==='week-number-weekday'?<WeekInfo/>:task.id==='time-duration-calculator'?<Duration/>:<Age/>}</div></ToolShell>}
function Countdown(){const tomorrow=new Date(Date.now()+DAY),[target,setTarget]=useState(localDateTime(tomorrow)),[now,setNow]=useState(new Date());useEffect(()=>{const id=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(id)},[]);const result=useMemo(()=>safe(()=>countdownParts(target,now)),[target,now]);return<><Input label="Target date & time" type="datetime-local" value={target} set={setTarget}/>{result.value?<><div className="grid gap-3 sm:grid-cols-4"><Stat label="Days" value={String(result.value.days)}/><Stat label="Hours" value={String(result.value.hours)}/><Stat label="Minutes" value={String(result.value.minutes)}/><Stat label="Seconds" value={String(result.value.seconds)}/></div><p className="text-xs text-neutral-500">{result.value.sign>=0?'Time remaining':'Target passed'} · {Math.abs(result.value.totalSeconds).toLocaleString()} total seconds</p></>:<ErrorBox text={result.error}/>}</>}
const DAY=86400000;
function Timesheet(){const[text,setText]=useState(`${localDate()} | 09:00 | 17:00 | 30\n${localDate(new Date(Date.now()-DAY))} | 09:15 | 17:30 | 45`),result=useMemo(()=>parseTimesheet(text),[text]);return<><Area label="Shifts — Date | Start | End | Unpaid break minutes" value={text} set={setText} rows={9}/>{result.errors.length>0&&<ErrorBox text={result.errors.join(' ')}/>}<div className="grid gap-3 sm:grid-cols-2"><Stat label="Total worked" value={minutesLabel(result.totalMinutes)}/><Stat label="Decimal hours" value={(result.totalMinutes/60).toFixed(2)}/></div><div className="overflow-auto rounded-xl border"><table className="w-full text-xs"><thead><tr><th className="p-2 text-left">Date</th><th>Start</th><th>End</th><th>Break</th><th>Worked</th></tr></thead><tbody>{result.items.map((r,i)=><tr key={i} className="border-t"><td className="p-2">{r.date}</td><td className="text-center">{r.start}</td><td className="text-center">{r.end}</td><td className="text-center">{r.breakMinutes}m</td><td className="text-center font-semibold">{minutesLabel(r.workedMinutes)}</td></tr>)}</tbody></table></div><p className="text-xs text-neutral-500">If an end time is earlier than its start time, the shift is treated as crossing midnight. This calculator does not apply overtime, wage, labor-law, or payroll rules.</p></>}
function WeekInfo(){const[date,setDate]=useState(localDate()),result=useMemo(()=>safe(()=>isoWeekInfo(date)),[date]);return<><Input label="Date" type="date" value={date} set={setDate}/>{result.value?<div className="grid gap-3 sm:grid-cols-4"><Stat label="Weekday" value={result.value.weekday}/><Stat label="ISO week" value={`${result.value.isoYear}-W${String(result.value.week).padStart(2,'0')}`}/><Stat label="ISO weekday" value={String(result.value.isoWeekday)}/><Stat label="Day of year" value={String(result.value.dayOfYear)}/></div>:<ErrorBox text={result.error}/>}<p className="text-xs text-neutral-500">ISO weeks start Monday; week 1 is the week containing the year’s first Thursday.</p></>}
function Duration(){const startDefault=new Date(),endDefault=new Date(Date.now()+90*60000),[start,setStart]=useState(localDateTime(startDefault)),[end,setEnd]=useState(localDateTime(endDefault)),result=useMemo(()=>safe(()=>durationBetween(start,end)),[start,end]);return<><div className="grid gap-3 sm:grid-cols-2"><Input label="Start" type="datetime-local" value={start} set={setStart}/><Input label="End" type="datetime-local" value={end} set={setEnd}/></div>{result.value?<><div className="grid gap-3 sm:grid-cols-4"><Stat label="Days" value={String(result.value.days)}/><Stat label="Hours" value={String(result.value.hours)}/><Stat label="Minutes" value={String(result.value.minutes)}/><Stat label="Seconds" value={String(result.value.seconds)}/></div><p className="text-xs text-neutral-500">Direction: {result.value.sign>=0?'end is after start':'end is before start'} · {(Math.abs(result.value.milliseconds)/3600000).toFixed(4)} total hours</p></>:<ErrorBox text={result.error}/>}</>}
function Age(){const[birth,setBirth]=useState('2000-01-01'),[asOf,setAsOf]=useState(localDate()),result=useMemo(()=>safe(()=>calendarAge(birth,asOf)),[birth,asOf]);return<><div className="grid gap-3 sm:grid-cols-2"><Input label="Date of birth" type="date" value={birth} set={setBirth}/><Input label="Age on" type="date" value={asOf} set={setAsOf}/></div>{result.value?<><div className="grid gap-3 sm:grid-cols-4"><Stat label="Years" value={String(result.value.years)}/><Stat label="Months" value={String(result.value.months)}/><Stat label="Days" value={String(result.value.days)}/><Stat label="Total elapsed days" value={result.value.totalDays.toLocaleString()}/></div><p className="text-xs text-neutral-500">Calendar age uses clamped month/year anniversaries; for a February 29 birth date, a non-leap-year anniversary is treated as February 28. Legal age rules can vary by jurisdiction.</p></>:<ErrorBox text={result.error}/>}</>}
function safe<T>(fn:()=>T){try{return{value:fn(),error:''}}catch(e){return{value:null,error:e instanceof Error?e.message:'Unable to calculate.'}}}
function Input({label,value,set,type='text'}:{label:string;value:string;set:(v:string)=>void;type?:string}){return<label className="block text-xs font-semibold">{label}<input type={type} value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-lg border bg-transparent p-3"/></label>}
function Area({label,value,set,rows=6}:{label:string;value:string;set:(v:string)=>void;rows?:number}){return<label className="block text-xs font-semibold">{label}<textarea rows={rows} value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full resize-y rounded-xl border bg-transparent p-3 font-mono text-sm"/></label>}
function Stat({label,value}:{label:string;value:string}){return<div className="rounded-xl border p-3"><div className="flex items-center gap-1 text-[11px] uppercase tracking-wide text-neutral-500"><Clock className="h-3 w-3"/>{label}</div><div className="mt-1 break-words text-lg font-bold">{value}</div></div>}
function ErrorBox({text}:{text:string}){return<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{text}</div>}
export default PlanningTools;
