import React,{useMemo,useState}from'react';
import{Check,Copy,RefreshCw}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{generateLorem,isGraphemePalindrome,repeatText,reverseText,textMetrics,wrapText,type LoremUnit,type ReverseMode,type WrapMode}from'../../utilities/s-tier-text';
import{getPublicTextStudyTask,PUBLIC_TEXT_STUDY_TASKS}from'../../text-study/publicTextStudyTasks';

const IDS=new Set(['text-reverser','text-repeater','text-wrapper','lorem-ipsum-generator']);
const inputClass='mt-1 w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 dark:border-neutral-700 dark:bg-neutral-950';
function currentId(){const clean=location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
function safe<T>(fn:()=>T){try{return{value:fn(),error:''}}catch(error){return{value:null,error:error instanceof Error?error.message:String(error)}}}

export default function TextPowerTools({initialText=''}:{initialText?:string}){
 const task=useMemo(()=>getPublicTextStudyTask(IDS.has(currentId())?currentId():'')??PUBLIC_TEXT_STUDY_TASKS.find(t=>t.id==='text-reverser')!,[]);
 return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={['text-cleaner','word-counter','case-converter']}>
  {task.id==='text-reverser'?<Reverser initialText={initialText}/>:task.id==='text-repeater'?<Repeater initialText={initialText}/>:task.id==='text-wrapper'?<Wrapper initialText={initialText}/>:<Lorem/>}
 </ToolShell>
}

function Reverser({initialText}:{initialText:string}){
 const[input,setInput]=useState(initialText||'Never odd or even 👨‍👩‍👧‍👦'),[mode,setMode]=useState<ReverseMode>('graphemes'),[ignoreCase,setIgnoreCase]=useState(true),[ignorePunctuation,setIgnorePunctuation]=useState(true);
 const output=useMemo(()=>reverseText(input,mode),[input,mode]);const metrics=textMetrics(output);const palindrome=isGraphemePalindrome(input,ignoreCase,ignorePunctuation);
 return<div className="space-y-4"><Notice>Unicode-aware reversal uses grapheme segmentation when available, so emoji sequences and combining characters are handled more safely than reversing UTF-16 code units.</Notice><div className="grid gap-3 md:grid-cols-[1fr_15rem]"><Area label="Input" value={input} set={setInput}/><div className="space-y-3"><Select label="Reverse" value={mode} set={v=>setMode(v as ReverseMode)} options={[['graphemes','Characters / graphemes'],['words','Word order'],['words-per-line','Words within each line'],['lines','Line order']]}/><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={ignoreCase} onChange={e=>setIgnoreCase(e.target.checked)}/> Ignore case for palindrome check</label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={ignorePunctuation} onChange={e=>setIgnorePunctuation(e.target.checked)}/> Ignore punctuation/spaces</label><Metric label="Palindrome" value={palindrome?'Yes':'No'}/></div></div><Output value={output}/><Metrics value={metrics}/></div>
}

function Repeater({initialText}:{initialText:string}){
 const[input,setInput]=useState(initialText||'Tiny Tools'),[count,setCount]=useState(5),[separator,setSeparator]=useState('\n'),[custom,setCustom]=useState(''),[prefix,setPrefix]=useState(''),[suffix,setSuffix]=useState(''),[number,setNumber]=useState(false),[start,setStart]=useState(1);
 const sep=separator==='custom'?custom:separator==='space'?' ':separator==='blank'?'\n\n':separator==='comma'?', ':separator==='none'?'':'\n';
 const result=useMemo(()=>safe(()=>repeatText(input,{count,separator:sep,prefix,suffix,numberLines:number,startNumber:start})),[input,count,sep,prefix,suffix,number,start]);
 return<div className="space-y-4"><Notice>Repeat up to 10,000 times with a 2-million-character output guard, configurable separators, prefixes/suffixes, and optional numbering.</Notice><Area label="Text to repeat" value={input} set={setInput}/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Num label="Repeats" value={count} set={setCount} min={0} max={10000}/><Select label="Separator" value={separator} set={setSeparator} options={[['newline','New line'],['blank','Blank line'],['space','Space'],['comma','Comma + space'],['none','None'],['custom','Custom']]}/>{separator==='custom'&&<Input label="Custom separator" value={custom} set={setCustom}/>}<Input label="Prefix each copy" value={prefix} set={setPrefix}/><Input label="Suffix each copy" value={suffix} set={setSuffix}/></div><div className="flex flex-wrap items-end gap-4"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={number} onChange={e=>setNumber(e.target.checked)}/> Number copies</label>{number&&<div className="w-32"><Num label="Start number" value={start} set={setStart}/></div>}</div>{result.error?<ErrorBox text={result.error}/>:<><Output value={result.value??''}/><Metrics value={textMetrics(result.value??'')}/></>}</div>
}

function Wrapper({initialText}:{initialText:string}){
 const[input,setInput]=useState(initialText||'Tiny Tools wraps text at a chosen visual character width while preserving paragraphs and supporting soft word wrapping or hard grapheme-safe wrapping.'),[width,setWidth]=useState(72),[mode,setMode]=useState<WrapMode>('soft'),[first,setFirst]=useState(''),[rest,setRest]=useState(''),[paragraphs,setParagraphs]=useState(true),[trim,setTrim]=useState(true);
 const result=useMemo(()=>safe(()=>wrapText(input,{width,mode,firstIndent:first,restIndent:rest,preserveParagraphs:paragraphs,trimLines:trim})),[input,width,mode,first,rest,paragraphs,trim]);
 return<div className="space-y-4"><Notice>Soft wrapping prefers word boundaries; hard wrapping uses grapheme units when available. Width is capped at 500 characters to keep output predictable.</Notice><Area label="Text to wrap" value={input} set={setInput}/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Num label="Line width" value={width} set={setWidth} min={1} max={500}/><Select label="Wrap mode" value={mode} set={v=>setMode(v as WrapMode)} options={[['soft','Soft · word boundaries'],['hard','Hard · exact width']]}/><Input label="First-line indent" value={first} set={setFirst}/><Input label="Following-line indent" value={rest} set={setRest}/></div><div className="flex flex-wrap gap-5"><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={paragraphs} onChange={e=>setParagraphs(e.target.checked)}/> Preserve paragraphs</label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={trim} onChange={e=>setTrim(e.target.checked)}/> Normalize line whitespace</label></div>{result.error?<ErrorBox text={result.error}/>:<><Output value={result.value??''}/><Metrics value={textMetrics(result.value??'')}/></>}</div>
}

function Lorem(){
 const[unit,setUnit]=useState<LoremUnit>('paragraphs'),[count,setCount]=useState(3),[seed,setSeed]=useState('tiny-tools'),[min,setMin]=useState(8),[max,setMax]=useState(18),[sentences,setSentences]=useState(4),[classic,setClassic]=useState(true);
 const result=useMemo(()=>safe(()=>generateLorem({unit,count,seed,minSentenceWords:min,maxSentenceWords:max,sentencesPerParagraph:sentences,startClassic:classic})),[unit,count,seed,min,max,sentences,classic]);
 const randomSeed=()=>{const bytes=new Uint32Array(2);crypto.getRandomValues(bytes);setSeed(`${bytes[0].toString(36)}-${bytes[1].toString(36)}`)};
 return<div className="space-y-4"><Notice>Seeded generation is reproducible: the same settings and seed produce the same filler text. Use a new seed when you want another variation.</Notice><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Select label="Generate" value={unit} set={v=>setUnit(v as LoremUnit)} options={[['paragraphs','Paragraphs'],['sentences','Sentences'],['words','Words']]}/><Num label={unit==='paragraphs'?'Paragraph count':unit==='sentences'?'Sentence count':'Word count'} value={count} set={setCount} min={1} max={500}/><Input label="Seed" value={seed} set={setSeed}/><div className="flex items-end"><button type="button" onClick={randomSeed} className="inline-flex w-full items-center justify-center gap-2 rounded-lg border border-neutral-300 px-3 py-2 text-sm font-semibold dark:border-neutral-700"><RefreshCw className="h-4 w-4"/>New seed</button></div></div>{unit!=='words'&&<div className="grid gap-3 sm:grid-cols-3"><Num label="Min words / sentence" value={min} set={setMin} min={3} max={30}/><Num label="Max words / sentence" value={max} set={setMax} min={3} max={60}/>{unit==='paragraphs'&&<Num label="Sentences / paragraph" value={sentences} set={setSentences} min={1} max={20}/>}</div>}<label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={classic} onChange={e=>setClassic(e.target.checked)}/> Begin with the classic “Lorem ipsum…” sentence</label>{result.error?<ErrorBox text={result.error}/>:<><Output value={result.value??''}/><Metrics value={textMetrics(result.value??'')}/></>}</div>
}

function Output({value}:{value:string}){const[copied,setCopied]=useState(false);const copy=async()=>{if(await copyToClipboard(value)){setCopied(true);setTimeout(()=>setCopied(false),1200)}};return<section className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800"><div className="mb-2 flex items-center justify-between"><div className="text-xs font-semibold uppercase tracking-wide text-neutral-500">Output</div><button type="button" disabled={!value} onClick={()=>void copy()} className="inline-flex items-center gap-1.5 rounded-lg border border-neutral-300 px-2.5 py-1.5 text-xs font-semibold disabled:opacity-40 dark:border-neutral-700">{copied?<Check className="h-3.5 w-3.5"/>:<Copy className="h-3.5 w-3.5"/>}{copied?'Copied':'Copy'}</button></div><textarea aria-label="Generated output" readOnly rows={10} value={value} className="w-full resize-y rounded-lg border border-neutral-200 bg-neutral-50 p-3 font-mono text-sm dark:border-neutral-800 dark:bg-neutral-950"/></section>}
function Metrics({value}:{value:ReturnType<typeof textMetrics>}){return<div className="grid gap-2 grid-cols-2 sm:grid-cols-4"><Metric label="Characters" value={value.characters.toLocaleString()}/><Metric label="Graphemes" value={value.graphemes.toLocaleString()}/><Metric label="Words" value={value.words.toLocaleString()}/><Metric label="Lines" value={value.lines.toLocaleString()}/></div>}
function Metric({label,value}:{label:string;value:string}){return<div className="rounded-lg border border-neutral-200 p-3 dark:border-neutral-800"><div className="text-[10px] font-semibold uppercase tracking-wide text-neutral-500">{label}</div><div className="mt-1 text-lg font-bold">{value}</div></div>}
function Notice({children}:{children:React.ReactNode}){return<div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs leading-5 text-blue-900 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-200">{children}</div>}
function ErrorBox({text}:{text:string}){return<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{text}</div>}
function Area({label,value,set}:{label:string;value:string;set:(value:string)=>void}){return<label className="block text-xs font-semibold">{label}<textarea aria-label={label} rows={7} value={value} onChange={e=>set(e.target.value)} className={`${inputClass} resize-y font-mono`}/></label>}
function Input({label,value,set}:{label:string;value:string;set:(value:string)=>void}){return<label className="block text-xs font-semibold">{label}<input aria-label={label} value={value} onChange={e=>set(e.target.value)} className={inputClass}/></label>}
function Num({label,value,set,min,max}:{label:string;value:number;set:(value:number)=>void;min?:number;max?:number}){return<label className="block text-xs font-semibold">{label}<input aria-label={label} type="number" min={min} max={max} step="1" value={value} onChange={e=>set(Number(e.target.value))} className={inputClass}/></label>}
function Select({label,value,set,options}:{label:string;value:string;set:(value:string)=>void;options:string[][]}){return<label className="block text-xs font-semibold">{label}<select aria-label={label} value={value} onChange={e=>set(e.target.value)} className={inputClass}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
