import React,{useMemo,useState}from'react';
import{Check,Copy,Plus,Trash2}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{analyzeDecisionSensitivity,decisionContributionShare,decisionWinnerMargin,normalizedDecisionWeights,rankDecisionOptionsStable,type StableDecisionCriterion,type StableDecisionOption}from'../../utilities/s-tier-decision';
const inputClass='w-full rounded-md border border-neutral-300 bg-white px-2 py-1.5 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 dark:border-neutral-700 dark:bg-neutral-950';
export default function DecisionMatrixStudio(){
 const[criteria,setCriteria]=useState<StableDecisionCriterion[]>([{name:'Impact',weight:40},{name:'Cost / value',weight:30},{name:'Ease',weight:30}]);const[options,setOptions]=useState<StableDecisionOption[]>([{name:'Option A',scores:[8,6,7]},{name:'Option B',scores:[6,9,8]},{name:'Option C',scores:[7,7,6]}]);const[copied,setCopied]=useState(false);
 const weights=useMemo(()=>normalizedDecisionWeights(criteria),[criteria]);const ranked=useMemo(()=>rankDecisionOptionsStable(criteria,options),[criteria,options]);const sensitivity=useMemo(()=>analyzeDecisionSensitivity(criteria,options),[criteria,options]);const margin=decisionWinnerMargin(ranked);const totalWeight=criteria.reduce((sum,c)=>sum+Math.max(0,Number(c.weight)||0),0);
 const updateCriterion=(index:number,patch:Partial<StableDecisionCriterion>)=>setCriteria(current=>current.map((item,i)=>i===index?{...item,...patch}:item));const removeCriterion=(index:number)=>{if(criteria.length<=1)return;setCriteria(current=>current.filter((_,i)=>i!==index));setOptions(current=>current.map(option=>({...option,scores:option.scores.filter((_,i)=>i!==index)})))};const addCriterion=()=>{setCriteria(current=>[...current,{name:`Criterion ${current.length+1}`,weight:10}]);setOptions(current=>current.map(option=>({...option,scores:[...option.scores,5]})))};
 const updateOption=(index:number,patch:Partial<StableDecisionOption>)=>setOptions(current=>current.map((item,i)=>i===index?{...item,...patch}:item));const setScore=(oi:number,ci:number,value:number)=>setOptions(current=>current.map((item,i)=>{if(i!==oi)return item;const scores=[...item.scores];scores[ci]=Math.min(10,Math.max(0,Number.isFinite(value)?value:0));return{...item,scores}}));const addOption=()=>setOptions(current=>[...current,{name:`Option ${String.fromCharCode(65+current.length)}`,scores:criteria.map(()=>5)}]);const removeOption=(index:number)=>options.length>1&&setOptions(current=>current.filter((_,i)=>i!==index));
 const exportText=['Weighted Decision Matrix',...ranked.map((row,index)=>`${index+1}. ${row.name} [row ${row.sourceIndex+1}] — ${row.score.toFixed(2)}/10`),'',`Winner margin: ${margin==null?'n/a':margin.toFixed(2)}`,...criteria.map((c,i)=>`${c.name}: ${((weights[i]??0)*100).toFixed(1)}% normalized weight`)].join('\n');const copy=async()=>{if(await copyToClipboard(exportText)){setCopied(true);setTimeout(()=>setCopied(false),1200)}};
 return<ToolShell toolId="decision-matrix" title="Weighted Decision Matrix" description="Compare alternatives with weighted criteria, stable row identity, normalized weights, contribution breakdowns, winner margin, and leave-one-criterion-out sensitivity analysis." category="productivity" relatedToolIds={['weighted-average-calculator','eisenhower-matrix','random-picker']}><div className="space-y-5">
  <div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs leading-5 text-blue-900 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-200">Score each option from 0–10 where 10 is best. Weights are relative and normalized automatically, so they do not need to total 100. Duplicate option names are supported because ranking uses stable source-row identity rather than the editable label.</div>
  {totalWeight<=0&&<div role="alert" className="rounded-lg border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-200">At least one criterion needs a positive weight before a ranking is meaningful.</div>}
  <div className="overflow-x-auto rounded-xl border border-neutral-200 dark:border-neutral-800"><table className="min-w-[800px] w-full text-sm"><thead className="bg-neutral-50 dark:bg-neutral-950"><tr><th className="p-3 text-left">Option</th>{criteria.map((c,ci)=><th key={ci} className="p-3 text-left align-top"><input aria-label={`Criterion ${ci+1} name`} value={c.name} onChange={e=>updateCriterion(ci,{name:e.target.value})} className={inputClass}/><div className="mt-1 grid grid-cols-[1fr_auto] gap-1"><input aria-label={`${c.name||`Criterion ${ci+1}`} weight`} type="number" min="0" step="1" value={c.weight} onChange={e=>updateCriterion(ci,{weight:Number(e.target.value)})} className={inputClass}/><button type="button" aria-label={`Remove ${c.name||`criterion ${ci+1}`}`} disabled={criteria.length<=1} onClick={()=>removeCriterion(ci)} className="rounded p-1.5 text-neutral-400 hover:text-red-600 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></div><div className="mt-1 text-[10px] font-normal text-neutral-500">{((weights[ci]??0)*100).toFixed(1)}% normalized</div></th>)}<th className="p-3 text-left">Score</th><th className="w-10 p-3"/></tr></thead><tbody>{options.map((option,oi)=>{const result=ranked.find(row=>row.sourceIndex===oi);return<tr key={oi} className="border-t border-neutral-200 dark:border-neutral-800"><td className="p-3"><input aria-label={`Option ${oi+1} name`} value={option.name} onChange={e=>updateOption(oi,{name:e.target.value})} className={inputClass}/></td>{criteria.map((c,ci)=><td key={ci} className="p-3"><input aria-label={`${option.name||`Option ${oi+1}`} score for ${c.name||`criterion ${ci+1}`}`} type="number" min="0" max="10" step="0.5" value={option.scores[ci]??0} onChange={e=>setScore(oi,ci,Number(e.target.value))} className={inputClass}/></td>)}<td className="p-3 font-bold tabular-nums">{totalWeight>0?`${result?.score.toFixed(2)??'0.00'} / 10`:'—'}</td><td className="p-3"><button type="button" aria-label={`Remove ${option.name||`option ${oi+1}`}`} disabled={options.length<=1} onClick={()=>removeOption(oi)} className="rounded p-1.5 text-neutral-400 hover:text-red-600 disabled:opacity-30"><Trash2 className="h-4 w-4"/></button></td></tr>})}</tbody></table></div>
  <div className="flex flex-wrap gap-2"><button type="button" onClick={addOption} className="inline-flex items-center gap-2 rounded-lg border border-neutral-300 px-3 py-2 text-sm font-semibold dark:border-neutral-700"><Plus className="h-4 w-4"/>Add option</button><button type="button" onClick={addCriterion} className="inline-flex items-center gap-2 rounded-lg border border-neutral-300 px-3 py-2 text-sm font-semibold dark:border-neutral-700"><Plus className="h-4 w-4"/>Add criterion</button><button type="button" onClick={()=>void copy()} className="inline-flex items-center gap-2 rounded-lg border border-neutral-300 px-3 py-2 text-sm font-semibold dark:border-neutral-700">{copied?<Check className="h-4 w-4"/>:<Copy className="h-4 w-4"/>}{copied?'Copied':'Copy analysis'}</button></div>
  <section><div className="mb-2 flex flex-wrap items-end justify-between gap-2"><div><h2 className="font-bold">Ranking</h2><p className="text-xs text-neutral-500">{ranked.length>1&&margin!=null?`Leader margin: ${margin.toFixed(2)} points.`:'Add at least two alternatives to compare a leader margin.'}</p></div></div><div className="grid gap-3 lg:grid-cols-2">{ranked.map((row,index)=>{const shares=decisionContributionShare(row);return<article key={row.sourceIndex} className={`rounded-xl border p-4 ${index===0&&totalWeight>0?'border-emerald-300 bg-emerald-50/60 dark:border-emerald-900 dark:bg-emerald-950/10':'border-neutral-200 dark:border-neutral-800'}`}><div className="flex items-center justify-between gap-2"><div><div className="text-[10px] font-semibold uppercase text-neutral-500">#{index+1} · source row {row.sourceIndex+1}</div><div className="font-bold">{row.name}</div></div><div className="text-2xl font-bold tabular-nums">{totalWeight>0?row.score.toFixed(2):'—'}</div></div><div className="mt-3 space-y-2">{criteria.map((c,ci)=><div key={ci}><div className="flex justify-between gap-2 text-[11px]"><span>{c.name||`Criterion ${ci+1}`}</span><span className="tabular-nums text-neutral-500">+{(row.contributions[ci]??0).toFixed(2)} · {shares[ci]??0}% of row score</span></div><div className="mt-1 h-1.5 overflow-hidden rounded bg-neutral-100 dark:bg-neutral-800"><div className="h-full rounded bg-neutral-500" style={{width:`${Math.min(100,shares[ci]??0)}%`}}/></div></div>)}</div></article>})}</div></section>
  <section className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><h2 className="font-bold">Sensitivity check</h2><p className="mt-1 text-xs text-neutral-500">Each row temporarily removes one criterion’s weight. If the winner changes, your result is sensitive to that criterion.</p><div className="mt-3 overflow-auto"><table className="w-full min-w-[38rem] text-xs"><thead><tr className="text-left text-neutral-500"><th className="p-2">Criterion removed</th><th className="p-2">Winner</th><th className="p-2">Score</th><th className="p-2">Result</th></tr></thead><tbody>{sensitivity.map(s=><tr key={s.criterionIndex} className="border-t border-neutral-200 dark:border-neutral-800"><td className="p-2">{s.criterionName}</td><td className="p-2">{s.winnerName??'—'}{s.winnerSourceIndex!=null?` · row ${s.winnerSourceIndex+1}`:''}</td><td className="p-2 tabular-nums">{s.winnerScore?.toFixed(2)??'—'}</td><td className={`p-2 font-semibold ${s.changedWinner?'text-amber-700 dark:text-amber-300':'text-emerald-700 dark:text-emerald-300'}`}>{s.changedWinner?'Winner changes':'Winner stable'}</td></tr>)}</tbody></table></div></section>
  <div className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs leading-5 text-amber-900 dark:border-amber-900 dark:bg-amber-950/20 dark:text-amber-200">A weighted matrix makes assumptions explicit; it does not make subjective scores objective. Use sensitivity results to identify where uncertain weights or scores deserve another look.</div>
 </div></ToolShell>
}
