import React,{useMemo,useState}from'react';
import{Check,Copy,Search}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{acceptFragment,batchMimeLookup,MIME_CATALOG,type MimeRecord}from'../../utilities/s-tier-mime';
const inputClass='w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 dark:border-neutral-700 dark:bg-neutral-950';
export default function MimeTypeExplorer(){
 const[query,setQuery]=useState('json'),[batch,setBatch]=useState('report.pdf\nphoto.webp\naudio.mp3\napplication/json'),[group,setGroup]=useState('All');
 const groups=useMemo(()=>['All',...new Set(MIME_CATALOG.map(record=>record.group))].sort((a,b)=>a==='All'?-1:b==='All'?1:a.localeCompare(b)),[]);
 const results=useMemo(()=>{const q=query.trim().toLowerCase();return MIME_CATALOG.filter(record=>(group==='All'||record.group===group)&&(!q||record.mime.toLowerCase().includes(q)||record.label.toLowerCase().includes(q)||record.extensions.some(ext=>ext.includes(q.replace(/^\./,'')))||record.aliases?.some(alias=>alias.toLowerCase().includes(q))));},[query,group]);
 const batchRows=useMemo(()=>batchMimeLookup(batch),[batch]);
 return<ToolShell toolId="mime-type-lookup" title="MIME Type Lookup" description="Search a broad local MIME catalog by file extension, filename, MIME string, or format name; inspect aliases and extensions; and run batch lookups with ready-to-copy HTTP and input-accept examples." category="developer" relatedToolIds={['file-type-inspector','http-header-parser','file-base64-converter']}><div className="space-y-5">
  <div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs leading-5 text-blue-900 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-200">The catalog covers common web, document, spreadsheet, presentation, archive, image, audio, video, font, code, package, and certificate formats. MIME detection from a filename is advisory: trustworthy file identification should inspect content/signatures too.</div>
  <div className="grid gap-3 sm:grid-cols-[1fr_14rem]"><label className="text-xs font-semibold">Search extension, filename, MIME, or format<div className="relative mt-1"><Search className="pointer-events-none absolute left-3 top-2.5 h-4 w-4 text-neutral-400"/><input aria-label="Search MIME catalog" value={query} onChange={e=>setQuery(e.target.value)} className={`${inputClass} pl-9`} placeholder=".webp, report.pdf, application/json…"/></div></label><label className="text-xs font-semibold">Group<select aria-label="MIME group" value={group} onChange={e=>setGroup(e.target.value)} className={`${inputClass} mt-1`}>{groups.map(item=><option key={item}>{item}</option>)}</select></label></div>
  <div className="flex flex-wrap gap-2 text-xs text-neutral-500"><span>{MIME_CATALOG.length} catalog records</span><span>•</span><span>{results.length} current matches</span><span>•</span><span>{new Set(MIME_CATALOG.flatMap(record=>record.extensions)).size} extension aliases</span></div>
  <div className="grid gap-3 lg:grid-cols-2">{results.slice(0,40).map(record=><MimeCard key={`${record.mime}-${record.extensions.join('.')}`} record={record}/>)}</div>{results.length>40&&<p className="text-xs text-neutral-500">Showing the first 40 matches. Narrow the search or group filter for more specific results.</p>}
  <section className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><h2 className="text-sm font-bold">Batch lookup</h2><p className="mt-1 text-xs text-neutral-500">One filename, extension, or MIME type per line.</p><textarea aria-label="Batch MIME queries" rows={6} value={batch} onChange={e=>setBatch(e.target.value)} className={`${inputClass} mt-3 resize-y font-mono`}/><div className="mt-3 overflow-auto"><table className="w-full min-w-[44rem] text-xs"><thead><tr className="text-left text-neutral-500"><th className="p-2">Query</th><th className="p-2">Best match</th><th className="p-2">Extensions</th><th className="p-2">Notes</th></tr></thead><tbody>{batchRows.map((row,index)=>{const match=row.matches[0];return<tr key={`${row.query}-${index}`} className="border-t border-neutral-200 dark:border-neutral-800"><td className="p-2 font-mono">{row.query}</td><td className="p-2 font-mono">{match?.mime??'No catalog match'}</td><td className="p-2">{match?.extensions.map(ext=>`.${ext}`).join(', ')??'—'}</td><td className="p-2 text-neutral-500">{match?`${match.label} · ${match.group}`:'Try a MIME string or common extension.'}</td></tr>})}</tbody></table></div></section>
 </div></ToolShell>
}
function MimeCard({record}:{record:MimeRecord}){const[copied,setCopied]=useState('');const copy=async(value:string,key:string)=>{if(await copyToClipboard(value)){setCopied(key);setTimeout(()=>setCopied(''),1200)}};const accept=acceptFragment(record);return<article className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><div className="flex flex-wrap items-start justify-between gap-2"><div><div className="text-xs font-semibold uppercase tracking-wide text-neutral-500">{record.group}</div><h3 className="mt-1 font-bold">{record.label}</h3></div><div className="flex gap-1"><Badge>{record.text?'text':'binary'}</Badge>{record.compressible&&<Badge>compressible</Badge>}</div></div><CopyLine label="MIME" value={record.mime} copied={copied==='mime'} onCopy={()=>void copy(record.mime,'mime')}/><CopyLine label="Extensions" value={record.extensions.map(ext=>`.${ext}`).join(', ')} copied={copied==='ext'} onCopy={()=>void copy(record.extensions.map(ext=>`.${ext}`).join(', '),'ext')}/>{record.aliases?.length?<div className="mt-2 text-xs"><span className="font-semibold">Aliases:</span> <span className="font-mono text-neutral-600 dark:text-neutral-300">{record.aliases.join(', ')}</span></div>:null}<CopyLine label="Accept attribute" value={accept} copied={copied==='accept'} onCopy={()=>void copy(accept,'accept')}/><CopyLine label="Content-Type" value={`Content-Type: ${record.mime}`} copied={copied==='header'} onCopy={()=>void copy(`Content-Type: ${record.mime}`,'header')}/></article>}
function CopyLine({label,value,copied,onCopy}:{label:string;value:string;copied:boolean;onCopy:()=>void}){return<div className="mt-2 grid grid-cols-[6rem_1fr_auto] items-start gap-2 text-xs"><div className="font-semibold text-neutral-500">{label}</div><code className="break-all rounded bg-neutral-50 px-2 py-1 dark:bg-neutral-950">{value}</code><button type="button" aria-label={`Copy ${label}`} onClick={onCopy} className="rounded border border-neutral-300 p-1.5 dark:border-neutral-700">{copied?<Check className="h-3.5 w-3.5"/>:<Copy className="h-3.5 w-3.5"/>}</button></div>}
function Badge({children}:{children:React.ReactNode}){return<span className="rounded-full border border-neutral-200 px-2 py-0.5 text-[10px] text-neutral-500 dark:border-neutral-800">{children}</span>}
