import React,{useMemo,useState}from'react';
import{Clipboard,Download,FileCode2,Upload}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{buildUtmUrl,calculateSubnet,decodeBaseText,encodeBaseText,evaluateJsonPath,formatSql,formatToml,formatYaml,htmlToMarkdown,jsonToToml,jsonToYaml,markdownToHtml,minifySql,parseTomlSubset,parseUserAgent,parseYamlSubset,validateJsonSchema,type BaseEncoding}from'../../utilities/p11-developer';
import{getPublicP11Task,PUBLIC_P11_TASKS}from'../../expansion/publicP11Tasks';
function currentId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
function safe<T>(fn:()=>T){try{return{value:fn(),error:''}}catch(e){return{value:null,error:e instanceof Error?e.message:'Unable to process input.'}}}
const samples={yaml:'name: Tiny Tools\nprivacy: true\ntags:\n  - local\n  - fast',toml:'title = "Tiny Tools"\nactive = true\n\n[owner]\nname = "Jonathan"',sql:'select id, name from users where active = true and score > 10 order by name;',json:'{"name":"Tiny Tools","active":true,"scores":[9,12]}',schema:'{"type":"object","required":["name"],"properties":{"name":{"type":"string","minLength":2},"active":{"type":"boolean"}}}',html:'<h1>Tiny Tools</h1><p><strong>Local</strong> utilities.</p>',md:'# Tiny Tools\n\n**Local** utilities.'};
const DeveloperExpansionTools:React.FC<{initialText?:string}>=({initialText})=>{const task=useMemo(()=>getPublicP11Task(currentId())??PUBLIC_P11_TASKS.find(t=>t.engine==='developer')!,[]),[text,setText]=useState(initialText||samples.yaml),[secondary,setSecondary]=useState(samples.schema),[mode,setMode]=useState('format'),[encoding,setEncoding]=useState<BaseEncoding>('base32'),[path,setPath]=useState('$.scores[*]'),[cidr,setCidr]=useState('192.168.1.42/24'),[ua,setUa]=useState(typeof navigator!=='undefined'?navigator.userAgent:'Mozilla/5.0'),[baseUrl,setBaseUrl]=useState('https://example.com/page'),[utm,setUtm]=useState({source:'newsletter',medium:'email',campaign:'launch',term:'',content:''}),[fileName,setFileName]=useState('decoded.bin'),[copied,setCopied]=useState(false),[fileBase64,setFileBase64]=useState('');
 const copy=async(v:string)=>{if(await copyToClipboard(v)){setCopied(true);setTimeout(()=>setCopied(false),1000)}};
 const result=useMemo(()=>{switch(task.id){case'yaml-formatter':return safe(()=>formatYaml(text));case'yaml-json-converter':return mode==='json-yaml'?safe(()=>jsonToYaml(JSON.parse(text))):safe(()=>JSON.stringify(parseYamlSubset(text),null,2));case'toml-formatter':return safe(()=>formatToml(text));case'toml-json-converter':return mode==='json-toml'?safe(()=>jsonToToml(JSON.parse(text))):safe(()=>JSON.stringify(parseTomlSubset(text),null,2));case'sql-formatter':return safe(()=>mode==='minify'?minifySql(text):formatSql(text));case'json-schema-validator':return safe(()=>validateJsonSchema(JSON.parse(text),JSON.parse(secondary)));case'jsonpath-tester':return safe(()=>evaluateJsonPath(JSON.parse(text),path));case'base-encoding-converter':return safe(()=>mode==='decode'?decodeBaseText(text,encoding):encodeBaseText(text,encoding));case'cidr-subnet-calculator':return safe(()=>calculateSubnet(cidr));case'user-agent-parser':return safe(()=>parseUserAgent(ua));case'utm-link-builder':return safe(()=>buildUtmUrl(baseUrl,utm));case'markdown-html-converter':return safe(()=>mode==='html-md'?htmlToMarkdown(text):markdownToHtml(text));default:return{value:null,error:''}}},[task.id,text,secondary,mode,encoding,path,cidr,ua,baseUrl,utm]);
 const loadSample=()=>{if(task.id.startsWith('yaml'))setText(samples.yaml);else if(task.id.startsWith('toml'))setText(samples.toml);else if(task.id==='sql-formatter')setText(samples.sql);else if(task.id==='json-schema-validator'||task.id==='jsonpath-tester')setText(samples.json);else if(task.id==='markdown-html-converter')setText(mode==='html-md'?samples.html:samples.md)};
 const handleFile=async(file:File)=>{const bytes=new Uint8Array(await file.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));setFileBase64(btoa(binary));setFileName(file.name+'.decoded')};
 const downloadDecoded=()=>{try{const clean=fileBase64.trim().replace(/^data:[^,]*,/,'').replace(/\s/g,''),binary=atob(clean),bytes=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)bytes[i]=binary.charCodeAt(i);const url=URL.createObjectURL(new Blob([bytes]));const a=document.createElement('a');a.href=url;a.download=fileName||'decoded.bin';a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}catch{alert('Base64 input is not valid.')}};
 return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={['json-formatter','encoding-tools','text-diff']}><div className="space-y-5"><Notice/>
 {task.id==='file-base64-converter'?<><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed p-5 text-sm font-semibold"><Upload className="h-4 w-4"/>Choose a local file<input type="file" className="sr-only" onChange={e=>{const f=e.target.files?.[0];if(f)void handleFile(f)}}/></label><TextArea label="Base64" value={fileBase64} set={setFileBase64} rows={10}/><div className="grid gap-3 sm:grid-cols-[1fr_auto]"><label className="text-xs font-semibold">Decoded filename<input value={fileName} onChange={e=>setFileName(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label><button onClick={downloadDecoded} className="self-end inline-flex items-center justify-center gap-2 rounded-lg bg-neutral-900 px-4 py-2 text-xs font-bold text-white dark:bg-neutral-100 dark:text-neutral-900"><Download className="h-4 w-4"/>Decode & download</button></div><p className="text-xs text-neutral-500">Files stay in browser memory. Very large files can consume substantial memory because Base64 expands data by roughly one third.</p></>:
 task.id==='cidr-subnet-calculator'?<><Input label="IPv4 CIDR" value={cidr} set={setCidr}/>{result.value&&<Stats value={result.value as Record<string,unknown>}/>}<Error text={result.error}/></>:
 task.id==='user-agent-parser'?<><TextArea label="User-Agent" value={ua} set={setUa} rows={5}/>{result.value&&<Stats value={result.value as Record<string,unknown>}/>}<Error text={result.error}/><p className="text-xs text-neutral-500">User-agent parsing is heuristic. Modern browsers may intentionally reduce or freeze identifying details.</p></>:
 task.id==='utm-link-builder'?<><Input label="Destination URL" value={baseUrl} set={setBaseUrl}/><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{(['source','medium','campaign','term','content']as const).map(k=><label key={k} className="text-xs font-semibold">utm_{k}<input value={utm[k]} onChange={e=>setUtm(v=>({...v,[k]:e.target.value}))} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>)}</div>{typeof result.value==='string'&&<Output value={result.value} copy={copy} copied={copied}/>}<Error text={result.error}/></>:
 <><ToolControls taskId={task.id} mode={mode} setMode={setMode} encoding={encoding} setEncoding={setEncoding} loadSample={loadSample}/>{task.id==='json-schema-validator'?<div className="grid gap-4 lg:grid-cols-2"><TextArea label="JSON instance" value={text} set={setText}/><TextArea label="JSON Schema" value={secondary} set={setSecondary}/></div>:task.id==='jsonpath-tester'?<><TextArea label="JSON" value={text} set={setText}/><Input label="JSONPath" value={path} set={setPath}/></>:<TextArea label={inputLabel(task.id,mode)} value={text} set={setText}/>}<Result taskId={task.id} result={result} copied={copied} copy={copy}/><Limit taskId={task.id}/></>}
 </div></ToolShell>};
function Notice(){return<div className="flex items-center gap-2 rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-2 text-xs text-indigo-700 dark:border-indigo-900 dark:bg-indigo-950/20 dark:text-indigo-300"><FileCode2 className="h-4 w-4"/>Local processing. Parsers deliberately state when they support a practical subset instead of pretending to implement every edge case of a full language specification.</div>}
function ToolControls({taskId,mode,setMode,encoding,setEncoding,loadSample}:{taskId:string;mode:string;setMode:React.Dispatch<React.SetStateAction<string>>;encoding:BaseEncoding;setEncoding:React.Dispatch<React.SetStateAction<BaseEncoding>>;loadSample:()=>void}){const modes=taskId==='yaml-json-converter'?[['yaml-json','YAML → JSON'],['json-yaml','JSON → YAML']]:taskId==='toml-json-converter'?[['toml-json','TOML → JSON'],['json-toml','JSON → TOML']]:taskId==='sql-formatter'?[['format','Format'],['minify','Minify']]:taskId==='base-encoding-converter'?[['encode','Encode'],['decode','Decode']]:taskId==='markdown-html-converter'?[['md-html','Markdown → HTML'],['html-md','HTML → Markdown']]:[];return<div className="flex flex-wrap items-end gap-2">{modes.map(([id,label])=><button key={id} onClick={()=>setMode(id)} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${mode===id?'bg-neutral-900 text-white dark:bg-neutral-100 dark:text-neutral-900':''}`}>{label}</button>)}{taskId==='base-encoding-converter'&&<label className="text-xs font-semibold">Encoding<select value={encoding} onChange={e=>setEncoding(e.target.value as BaseEncoding)} className="ml-2 rounded border bg-transparent px-3 py-2"><option value="base32">Base32</option><option value="base58">Base58</option><option value="base85">Ascii85</option></select></label>}{['yaml-formatter','yaml-json-converter','toml-formatter','toml-json-converter','sql-formatter','json-schema-validator','jsonpath-tester','markdown-html-converter'].includes(taskId)&&<button onClick={loadSample} className="rounded-lg border px-3 py-2 text-xs font-semibold">Load sample</button>}</div>}
function inputLabel(id:string,mode:string){if(id.startsWith('yaml'))return mode==='json-yaml'?'JSON':'YAML';if(id.startsWith('toml'))return mode==='json-toml'?'JSON':'TOML';if(id==='sql-formatter')return'SQL';if(id==='base-encoding-converter')return mode==='decode'?'Encoded text':'UTF-8 text';if(id==='markdown-html-converter')return mode==='html-md'?'HTML':'Markdown';return'Input'}
function Result({taskId,result,copied,copy}:{taskId:string;result:{value:unknown;error:string};copied:boolean;copy:(v:string)=>Promise<void>}){if(result.error)return<Error text={result.error}/>;if(result.value==null)return null;if(taskId==='json-schema-validator'){const issues=result.value as{path:string;message:string}[];return<section className={`rounded-xl border p-4 ${issues.length?'border-amber-300 bg-amber-50 dark:border-amber-900 dark:bg-amber-950/20':'border-emerald-300 bg-emerald-50 dark:border-emerald-900 dark:bg-emerald-950/20'}`}><div className="text-sm font-bold">{issues.length?`${issues.length} validation issue${issues.length===1?'':'s'}`:'Valid against the supported schema subset'}</div>{issues.length>0&&<ul className="mt-3 space-y-1 text-xs">{issues.map((x,i)=><li key={i}><code>{x.path}</code> — {x.message}</li>)}</ul>}</section>}const value=typeof result.value==='string'?result.value:JSON.stringify(result.value,null,2);return<Output value={value} copy={copy} copied={copied}/>}function Output({value,copy,copied}:{value:string;copy:(v:string)=>Promise<void>;copied:boolean}){return<section className="rounded-xl border bg-neutral-50 p-3 dark:bg-neutral-950"><div className="mb-2 flex justify-end"><button onClick={()=>void copy(value)} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Clipboard className="h-3.5 w-3.5"/>{copied?'Copied':'Copy'}</button></div><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-words text-xs">{value}</pre></section>}
function Stats({value}:{value:Record<string,unknown>}){return<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(value).map(([k,v])=><div key={k} className="rounded-xl border p-3"><div className="text-[10px] uppercase tracking-wide text-neutral-500">{k.replace(/([A-Z])/g,' $1')}</div><div className="mt-1 break-words text-sm font-semibold">{String(v)}</div></div>)}</div>}
function Input({label,value,set}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>}){return<label className="block text-xs font-semibold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2 font-mono"/></label>}
function TextArea({label,value,set,rows=9}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>;rows?:number}){return<label className="block text-xs font-semibold">{label}<textarea rows={rows} value={value} onChange={e=>set(e.target.value)} spellCheck={false} className="mt-1 w-full resize-y rounded-xl border bg-white p-3 font-mono text-sm dark:bg-neutral-950"/></label>}
function Error({text}:{text:string}){return text?<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{text}</div>:null}
function Limit({taskId}:{taskId:string}){const notes:Record<string,string>={
'yaml-formatter':'YAML support covers common indentation-based mappings, sequences, scalars, and JSON-style inline values. Anchors, aliases, tags, block scalars, merge keys, and multi-document semantics are intentionally not claimed.',
'yaml-json-converter':'YAML support covers common mappings, sequences, scalars, and JSON-style inline values; advanced YAML features are outside this lightweight local parser.',
'toml-formatter':'TOML support covers common key/value data, arrays, dotted keys, and table sections. Multiline strings, arrays of tables, dates, and every TOML lexical edge case are not claimed.',
'toml-json-converter':'Conversion targets a common TOML subset and deterministic JSON objects, not lossless round-tripping of comments or specialized TOML scalar types.',
'sql-formatter':'Formatting is lexical and quote-aware for common SQL. It is not a dialect parser and does not validate query semantics.',
'json-schema-validator':'Validation supports a useful subset: type, properties, required, additionalProperties=false, items, enum, string lengths/patterns, numeric bounds, and array bounds. It does not claim full JSON Schema draft compliance.',
'jsonpath-tester':'Supports $, dot properties, quoted bracket properties, numeric indexes, and wildcards. Filters, recursive descent, slices, unions, and script expressions are intentionally excluded.',
'base-encoding-converter':'Base58 uses the Bitcoin alphabet; Base32 uses RFC 4648 alphabet; Base85 uses Ascii85-style encoding.',
'markdown-html-converter':'Markdown conversion covers common headings, paragraphs, unordered lists, blockquotes, fenced code, emphasis, inline code, and HTTP(S) links. It is not a full CommonMark engine.'};return notes[taskId]?<p className="text-xs text-neutral-500">{notes[taskId]}</p>:null}
export default DeveloperExpansionTools;
