import React,{useMemo,useState}from'react';
import{Calculator,Clipboard}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{complexArgument,complexMagnitude,complexOp,factorialBig,formatComplex,formatMatrix,gcdBig,lcmBig,linearRegression,matrixAdd,matrixDeterminant,matrixInverse,matrixMultiply,matrixTranspose,nCr,nPr,normalInterval,normalStats,parseBigIntStrict,parseComplex,parseMatrix,parseNumberList,parseVector,primeFactors,solveQuadratic,vectorAdd,vectorAngle,vectorCross,vectorDot,vectorMagnitude}from'../../utilities/p11-math';
import{getPublicP11Task,PUBLIC_P11_TASKS}from'../../expansion/publicP11Tasks';
function currentId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
function safe<T>(fn:()=>T){try{return{value:fn(),error:''}}catch(e){return{value:null,error:e instanceof Error?e.message:'Unable to calculate.'}}}
const MathExpansionTools:React.FC=()=>{const task=useMemo(()=>getPublicP11Task(currentId())??PUBLIC_P11_TASKS.find(t=>t.engine==='math')!,[]),[a,setA]=useState(task.id==='matrix-calculator'?'1 2\n3 4':task.id==='complex-number-calculator'?'3+4i':task.id==='vector-calculator'?'1, 2, 3':'12'),[b,setB]=useState(task.id==='matrix-calculator'?'5 6\n7 8':task.id==='complex-number-calculator'?'1-2i':task.id==='vector-calculator'?'4, 5, 6':'18'),[op,setOp]=useState('add'),[n,setN]=useState(10),[r,setR]=useState(3),[mean,setMean]=useState(0),[sd,setSd]=useState(1),[x,setX]=useState(1.96),[lower,setLower]=useState(-1.96),[upper,setUpper]=useState(1.96),[xs,setXs]=useState('1,2,3,4,5'),[ys,setYs]=useState('2,4,5,8,10'),[predictX,setPredictX]=useState(6),[qa,setQa]=useState(1),[qb,setQb]=useState(-3),[qc,setQc]=useState(2),[scalar,setScalar]=useState(2),[copied,setCopied]=useState(false);const copy=async(v:string)=>{if(await copyToClipboard(v)){setCopied(true);setTimeout(()=>setCopied(false),1000)}};
 const result=useMemo(()=>{switch(task.id){case'matrix-calculator':return safe(()=>{const A=parseMatrix(a),B=parseMatrix(b);if(op==='add')return formatMatrix(matrixAdd(A,B));if(op==='subtract')return formatMatrix(matrixAdd(A,B,-1));if(op==='multiply')return formatMatrix(matrixMultiply(A,B));if(op==='transpose-a')return formatMatrix(matrixTranspose(A));if(op==='det-a')return String(matrixDeterminant(A));if(op==='inverse-a')return formatMatrix(matrixInverse(A));throw new Error('Choose a matrix operation.')});case'combinations-permutations-calculator':return safe(()=>({nCr:nCr(n,r).toString(),nPr:nPr(n,r).toString(),factorialN:n<=5000?factorialBig(n).toString():'Omitted above n=5000 for display size'}));case'normal-distribution-calculator':return safe(()=>({...normalStats(x,mean,sd),interval:normalInterval(lower,upper,mean,sd)}));case'linear-regression-calculator':return safe(()=>{const reg=linearRegression(parseNumberList(xs),parseNumberList(ys));return{n:reg.n,slope:reg.slope,intercept:reg.intercept,r:reg.r,r2:reg.r2,rmse:reg.rmse,predictionX:predictX,predictionY:reg.predict(predictX)}});case'gcd-lcm-prime-factorization':return safe(()=>{const A=parseBigIntStrict(a),B=parseBigIntStrict(b),f=primeFactors(A);return{gcd:gcdBig(A,B).toString(),lcm:lcmBig(A,B).toString(),factorsA:f.length?f.map(([p,e])=>e===1?String(p):`${p}^${e}`).join(' × '):'No prime factors'}});case'complex-number-calculator':return safe(()=>{const A=parseComplex(a),B=parseComplex(b),z=complexOp(A,B,op as'add'|'subtract'|'multiply'|'divide');return{result:formatComplex(z),magnitude:complexMagnitude(z),argumentRadians:complexArgument(z),argumentDegrees:complexArgument(z)*180/Math.PI}});case'quadratic-solver':return safe(()=>solveQuadratic(qa,qb,qc));case'vector-calculator':return safe(()=>{const A=parseVector(a),B=parseVector(b);if(op==='add')return{result:vectorAdd(A,B),magnitudeA:vectorMagnitude(A)};if(op==='subtract')return{result:vectorAdd(A,B,-1),magnitudeA:vectorMagnitude(A)};if(op==='dot')return{dot:vectorDot(A,B),magnitudeA:vectorMagnitude(A),magnitudeB:vectorMagnitude(B)};if(op==='cross')return{cross:vectorCross(A,B)};if(op==='angle')return{radians:vectorAngle(A,B),degrees:vectorAngle(A,B)*180/Math.PI};if(op==='scale')return{result:A.map(v=>v*scalar)};return{magnitudeA:vectorMagnitude(A)}});default:return{value:null,error:''}}},[task.id,a,b,op,n,r,mean,sd,x,lower,upper,xs,ys,predictX,qa,qb,qc,scalar]);
 return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={['scientific-calculator','statistics-calculator','probability-calculator']}><div className="space-y-5"><div className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-300"><Calculator className="h-4 w-4"/>Deterministic local calculations. Numeric tools report formulas and limitations instead of implying statistical inference beyond the supplied data.</div>
 {task.id==='matrix-calculator'&&<><div className="grid gap-4 lg:grid-cols-2"><Area label="Matrix A" value={a} set={setA}/><Area label="Matrix B" value={b} set={setB}/></div><Select label="Operation" value={op} set={setOp} options={[['add','A + B'],['subtract','A − B'],['multiply','A × B'],['transpose-a','Transpose A'],['det-a','det(A)'],['inverse-a','A⁻¹']]}/></>}
 {task.id==='combinations-permutations-calculator'&&<div className="grid gap-3 sm:grid-cols-2"><Num label="n" value={n} set={setN} step={1}/><Num label="r" value={r} set={setR} step={1}/></div>}
 {task.id==='normal-distribution-calculator'&&<><div className="grid gap-3 sm:grid-cols-3"><Num label="Mean μ" value={mean} set={setMean}/><Num label="Std. deviation σ" value={sd} set={setSd}/><Num label="Value x" value={x} set={setX}/></div><div className="grid gap-3 sm:grid-cols-2"><Num label="Interval lower" value={lower} set={setLower}/><Num label="Interval upper" value={upper} set={setUpper}/></div></>}
 {task.id==='linear-regression-calculator'&&<><div className="grid gap-4 lg:grid-cols-2"><Area label="X values" value={xs} set={setXs}/><Area label="Y values" value={ys} set={setYs}/></div><Num label="Predict at X" value={predictX} set={setPredictX}/></>}
 {task.id==='gcd-lcm-prime-factorization'&&<div className="grid gap-3 sm:grid-cols-2"><Input label="Integer A" value={a} set={setA}/><Input label="Integer B" value={b} set={setB}/></div>}
 {task.id==='complex-number-calculator'&&<><div className="grid gap-3 sm:grid-cols-2"><Input label="Complex A" value={a} set={setA}/><Input label="Complex B" value={b} set={setB}/></div><Select label="Operation" value={op} set={setOp} options={[['add','A + B'],['subtract','A − B'],['multiply','A × B'],['divide','A ÷ B']]}/></>}
 {task.id==='quadratic-solver'&&<div className="grid gap-3 sm:grid-cols-3"><Num label="a" value={qa} set={setQa}/><Num label="b" value={qb} set={setQb}/><Num label="c" value={qc} set={setQc}/></div>}
 {task.id==='vector-calculator'&&<><div className="grid gap-3 sm:grid-cols-2"><Input label="Vector A" value={a} set={setA}/><Input label="Vector B" value={b} set={setB}/></div><div className="grid gap-3 sm:grid-cols-2"><Select label="Operation" value={op} set={setOp} options={[['add','A + B'],['subtract','A − B'],['dot','Dot product'],['cross','Cross product (3D)'],['angle','Angle'],['scale','Scale A']]}/>{op==='scale'&&<Num label="Scalar" value={scalar} set={setScalar}/>}</div></>}
 <Result result={result} copied={copied} copy={copy}/><Limit id={task.id}/></div></ToolShell>};
function Result({result,copied,copy}:{result:{value:unknown;error:string};copied:boolean;copy:(v:string)=>Promise<void>}){if(result.error)return<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{result.error}</div>;if(result.value==null)return null;const v=typeof result.value==='string'?result.value:JSON.stringify(result.value,(_,x)=>typeof x==='number'?Number(x.toPrecision(10)):x,2);return<section className="rounded-xl border bg-neutral-50 p-3 dark:bg-neutral-950"><div className="mb-2 flex justify-end"><button onClick={()=>void copy(v)} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Clipboard className="h-3.5 w-3.5"/>{copied?'Copied':'Copy'}</button></div><pre className="overflow-auto whitespace-pre-wrap text-xs">{v}</pre></section>}
function Area({label,value,set}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>}){return<label className="text-xs font-semibold">{label}<textarea rows={6} value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent p-3 font-mono"/></label>}
function Input({label,value,set}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>}){return<label className="text-xs font-semibold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2 font-mono"/></label>}
function Num({label,value,set,step='any'}:{label:string;value:number;set:React.Dispatch<React.SetStateAction<number>>;step?:number|'any'}){return<label className="text-xs font-semibold">{label}<input type="number" step={step} value={value} onChange={e=>set(Number(e.target.value))} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>}
function Select({label,value,set,options}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>;options:string[][]}){return<label className="text-xs font-semibold">{label}<select value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Limit({id}:{id:string}){const notes:Record<string,string>={
'matrix-calculator':'Matrix inversion and determinants use floating-point Gaussian elimination with pivoting. Results near singularity can be numerically sensitive.',
'combinations-permutations-calculator':'nCr and nPr use exact BigInt arithmetic. Factorial display is intentionally omitted above n=5000 because the output becomes extremely large.',
'normal-distribution-calculator':'Normal probabilities use a standard numerical error-function approximation. This is a calculator, not a statistical test or modeling recommendation.',
'linear-regression-calculator':'Regression is ordinary least squares for one predictor and reports descriptive fit metrics only. It does not establish causation or validate model assumptions.',
'gcd-lcm-prime-factorization':'Prime factorization uses trial division and is intended for ordinary integers, not cryptographic-size factorization.',
'quadratic-solver':'Roots use the standard quadratic formula with JavaScript floating-point arithmetic.',
'vector-calculator':'Dot products work in matching dimensions; cross products require exactly 3D vectors.'};return notes[id]?<p className="text-xs text-neutral-500">{notes[id]}</p>:null}
export default MathExpansionTools;
