import React,{useEffect,useMemo,useState}from'react';
import{Clipboard,Download,Globe2,RefreshCw}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{buildRobotsTxt,buildSitemapXml,buildVCard,generateTotp,minifyCss,optimizeSvg,pixelsFromPrint,printSizeFromPixels,simulateColorVision,type VisionMode}from'../../utilities/p11-web';
import{getPublicP11Task,PUBLIC_P11_TASKS}from'../../expansion/publicP11Tasks';
function currentId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
function safe<T>(fn:()=>T){try{return{value:fn(),error:''}}catch(e){return{value:null,error:e instanceof Error?e.message:'Unable to process input.'}}}
const WebExpansionTools:React.FC=()=>{const task=useMemo(()=>getPublicP11Task(currentId())??PUBLIC_P11_TASKS.find(t=>t.engine==='web')!,[]),[text,setText]=useState(task.id==='svg-optimizer'?'<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><!-- comment --><circle cx="50" cy="50" r="40" fill="#2563eb" /></svg>':'body { color: #222; /* comment */ margin: 0 10px; }'),[widthPx,setWidthPx]=useState(3000),[heightPx,setHeightPx]=useState(2000),[dpi,setDpi]=useState(300),[printW,setPrintW]=useState(10),[printH,setPrintH]=useState(8),[unit,setUnit]=useState<'in'|'cm'>('in'),[hex,setHex]=useState('#2563EB'),[vision,setVision]=useState<VisionMode>('deuteranopia'),[agent,setAgent]=useState('*'),[allow,setAllow]=useState(''),[disallow,setDisallow]=useState('/admin\n/private'),[sitemap,setSitemap]=useState('https://example.com/sitemap.xml'),[urls,setUrls]=useState('https://example.com/\nhttps://example.com/about\nhttps://example.com/contact'),[vc,setVc]=useState({first:'Ada',last:'Lovelace',organization:'Analytical Engines',title:'Mathematician',phone:'+44 123 456 789',email:'ada@example.com',website:'https://example.com',street:'',city:'London',region:'',postal:'',country:'United Kingdom'}),[secret,setSecret]=useState('JBSWY3DPEHPK3PXP'),[digits,setDigits]=useState<6|8>(6),[period,setPeriod]=useState(30),[totp,setTotp]=useState<{code:string;remaining:number;counter:string}|null>(null),[totpError,setTotpError]=useState(''),[copied,setCopied]=useState(false);const copy=async(v:string)=>{if(await copyToClipboard(v)){setCopied(true);setTimeout(()=>setCopied(false),1000)}};
 useEffect(()=>{if(task.id!=='totp-generator')return;let active=true;const refresh=()=>void generateTotp(secret,{digits,period}).then(v=>{if(active){setTotp(v);setTotpError('')}}).catch(e=>{if(active){setTotp(null);setTotpError(e instanceof Error?e.message:'Unable to generate TOTP.')}});refresh();const id=setInterval(refresh,1000);return()=>{active=false;clearInterval(id)}},[task.id,secret,digits,period]);
 const result=useMemo(()=>{switch(task.id){case'svg-optimizer':return safe(()=>optimizeSvg(text));case'dpi-print-size-calculator':return safe(()=>({fromPixels:printSizeFromPixels(widthPx,heightPx,dpi),toPixels:pixelsFromPrint(printW,printH,unit,dpi)}));case'color-blindness-simulator':return safe(()=>simulateColorVision(hex,vision));case'robots-txt-builder':return safe(()=>buildRobotsTxt([{agent,allow:allow.split(/\r?\n/).map(s=>s.trim()).filter(Boolean),disallow:disallow.split(/\r?\n/).map(s=>s.trim()).filter(Boolean)}],sitemap.trim()?[sitemap.trim()]:[]));case'sitemap-xml-builder':return safe(()=>buildSitemapXml(urls.split(/\r?\n/).map(s=>s.trim()).filter(Boolean).map(loc=>({loc}))));case'vcard-generator':return safe(()=>buildVCard(vc));case'css-minifier':return safe(()=>minifyCss(text));default:return{value:null,error:''}},[task.id,text,widthPx,heightPx,dpi,printW,printH,unit,hex,vision,agent,allow,disallow,sitemap,urls,vc]);
 const downloadText=(content:string,name:string,type:string)=>{const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)};
 return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={['color-converter','qr-studio','encoding-tools']}><div className="space-y-5"><div className="flex items-center gap-2 rounded-lg border border-sky-200 bg-sky-50 px-3 py-2 text-xs text-sky-700 dark:border-sky-900 dark:bg-sky-950/20 dark:text-sky-300"><Globe2 className="h-4 w-4"/>These utilities run locally. Generated SEO/contact outputs are standards-oriented helpers, not a claim that every crawler, client, or platform handles every optional field identically.</div>
 {task.id==='dpi-print-size-calculator'&&<><div className="grid gap-3 sm:grid-cols-3"><Num label="Width (px)" value={widthPx} set={setWidthPx}/><Num label="Height (px)" value={heightPx} set={setHeightPx}/><Num label="DPI / PPI" value={dpi} set={setDpi}/></div><div className="grid gap-3 sm:grid-cols-3"><Num label={`Print width (${unit})`} value={printW} set={setPrintW}/><Num label={`Print height (${unit})`} value={printH} set={setPrintH}/><label className="text-xs font-semibold">Unit<select value={unit} onChange={e=>setUnit(e.target.value as'in'|'cm')} className="mt-1 w-full rounded border bg-transparent px-3 py-2"><option value="in">Inches</option><option value="cm">Centimeters</option></select></label></div></>}
 {task.id==='color-blindness-simulator'&&<><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Color<input type="color" value={hex} onChange={e=>setHex(e.target.value)} className="mt-1 h-11 w-full rounded border bg-transparent p-1"/><input value={hex} onChange={e=>setHex(e.target.value)} className="mt-2 w-full rounded border bg-transparent px-3 py-2 font-mono"/></label><label className="text-xs font-semibold">Simulation<select value={vision} onChange={e=>setVision(e.target.value as VisionMode)} className="mt-1 w-full rounded border bg-transparent px-3 py-2"><option value="protanopia">Protanopia approximation</option><option value="deuteranopia">Deuteranopia approximation</option><option value="tritanopia">Tritanopia approximation</option><option value="grayscale">Grayscale</option></select></label></div>{result.value&&<div className="grid grid-cols-2 overflow-hidden rounded-xl border"><Swatch label="Original" hex={(result.value as any).input}/><Swatch label="Simulated" hex={(result.value as any).output}/></div>}<p className="text-xs text-neutral-500">This is a simple matrix approximation for color comparison, not a medical vision simulation or replacement for WCAG contrast testing.</p></>}
 {task.id==='robots-txt-builder'&&<><div className="grid gap-3 sm:grid-cols-2"><Input label="User-agent" value={agent} set={setAgent}/><Input label="Sitemap URL" value={sitemap} set={setSitemap}/></div><div className="grid gap-4 sm:grid-cols-2"><Area label="Allow paths · one per line" value={allow} set={setAllow}/><Area label="Disallow paths · one per line" value={disallow} set={setDisallow}/></div></>}
 {task.id==='sitemap-xml-builder'&&<Area label="URLs · one per line" value={urls} set={setUrls}/>} 
 {task.id==='vcard-generator'&&<div className="grid gap-3 sm:grid-cols-2">{Object.entries(vc).map(([k,v])=><label key={k} className="text-xs font-semibold capitalize">{k}<input value={v} onChange={e=>setVc(x=>({...x,[k]:e.target.value}))} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>)}</div>}
 {task.id==='totp-generator'&&<><div className="grid gap-3 sm:grid-cols-3"><Input label="Base32 secret" value={secret} set={setSecret}/><label className="text-xs font-semibold">Digits<select value={digits} onChange={e=>setDigits(Number(e.target.value)as 6|8)} className="mt-1 w-full rounded border bg-transparent px-3 py-2"><option value={6}>6</option><option value={8}>8</option></select></label><Num label="Period (seconds)" value={period} set={setPeriod}/></div>{totp&&<section className="rounded-xl border bg-neutral-50 p-5 text-center dark:bg-neutral-950"><div className="font-mono text-4xl font-bold tracking-[.2em]">{totp.code}</div><div className="mt-2 text-xs text-neutral-500">Refreshes in {totp.remaining}s · counter {totp.counter}</div><button onClick={()=>void copy(totp.code)} className="mt-3 inline-flex items-center gap-1 rounded border px-3 py-1.5 text-xs"><Clipboard className="h-3.5 w-3.5"/>{copied?'Copied':'Copy code'}</button></section>}<Error text={totpError}/><p className="text-xs text-neutral-500">Your secret never leaves the browser. Codes use HMAC-SHA-1, a 30-second default period, and dynamic truncation compatible with common authenticator setups. Keep 2FA secrets private.</p></>}
 {['svg-optimizer','css-minifier'].includes(task.id)&&<Area label={task.id==='svg-optimizer'?'SVG source':'CSS'} value={text} set={setText}/>} 
 {task.id!=='totp-generator'&&<Result result={result} copied={copied} copy={copy} download={task.id==='vcard-generator'?v=>downloadText(v,'contact.vcf','text/vcard;charset=utf-8'):task.id==='sitemap-xml-builder'?v=>downloadText(v,'sitemap.xml','application/xml;charset=utf-8'):task.id==='robots-txt-builder'?v=>downloadText(v,'robots.txt','text/plain;charset=utf-8'):task.id==='svg-optimizer'?v=>downloadText(v,'optimized.svg','image/svg+xml;charset=utf-8'):undefined}/>}</div></ToolShell>};
function Result({result,copied,copy,download}:{result:{value:unknown;error:string};copied:boolean;copy:(v:string)=>Promise<void>;download?:((v:string)=>void)}){if(result.error)return<Error text={result.error}/>;if(result.value==null)return null;const v=typeof result.value==='string'?result.value:JSON.stringify(result.value,(_,x)=>typeof x==='number'?Number(x.toPrecision(10)):x,2);return<section className="rounded-xl border bg-neutral-50 p-3 dark:bg-neutral-950"><div className="mb-2 flex justify-end gap-2"><button onClick={()=>void copy(v)} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Clipboard className="h-3.5 w-3.5"/>{copied?'Copied':'Copy'}</button>{download&&<button onClick={()=>download(v)} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Download className="h-3.5 w-3.5"/>Download</button>}</div><pre className="max-h-96 overflow-auto whitespace-pre-wrap break-words text-xs">{v}</pre></section>}
function Swatch({label,hex}:{label:string;hex:string}){return<div className="min-h-32 p-4 flex flex-col justify-end" style={{backgroundColor:hex}}><span className="w-fit rounded bg-white/90 px-2 py-1 text-xs font-bold text-black">{label} · {hex}</span></div>}
function Area({label,value,set}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>}){return<label className="block text-xs font-semibold">{label}<textarea rows={8} value={value} onChange={e=>set(e.target.value)} spellCheck={false} className="mt-1 w-full rounded-xl border bg-transparent p-3 font-mono"/></label>}
function Input({label,value,set}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>}){return<label className="text-xs font-semibold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2 font-mono"/></label>}
function Num({label,value,set}:{label:string;value:number;set:React.Dispatch<React.SetStateAction<number>>}){return<label className="text-xs font-semibold">{label}<input type="number" value={value} onChange={e=>set(Number(e.target.value))} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>}
function Error({text}:{text:string}){return text?<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{text}</div>:null}
export default WebExpansionTools;
