import React,{useMemo,useState}from'react';
import{BookOpen,Download,FileText,Upload}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{getPublicP13Task,PUBLIC_P13_TASKS}from'../../expansion/publicP13Tasks';
import{createDocx,createEpub,editEpubMetadata,extractDocx,extractEpub,extractPptx,inspectDocxMetadata,inspectEpubMetadata,safeFilename,type BookMetadata}from'../../utilities/p13-office';

function currentId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
function download(data:BlobPart,name:string,type:string){const url=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const DEFAULT_MD='# Tiny Tools Document\n\nA **local-first** document generated entirely in your browser.\n\n- No upload\n- Simple headings\n- Portable content';
const EMPTY_META:BookMetadata={title:'Tiny Tools Book',creator:'',language:'en',identifier:'',publisher:'',description:''};

const OfficeEbookInterchangeTools:React.FC<{initialText?:string}>=({initialText})=>{const task=useMemo(()=>getPublicP13Task(currentId())??PUBLIC_P13_TASKS[0],[]),[file,setFile]=useState<File|null>(null),[input,setInput]=useState(initialText??DEFAULT_MD),[output,setOutput]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[title,setTitle]=useState('Tiny Tools Document'),[creator,setCreator]=useState(''),[meta,setMeta]=useState<BookMetadata>(EMPTY_META),[loadedMeta,setLoadedMeta]=useState(false);
 const accept=task.format==='docx'?'.docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document':task.format==='epub'?'.epub,application/epub+zip':'.pptx,application/vnd.openxmlformats-officedocument.presentationml.presentation';
 const reset=()=>{setOutput('');setError('');setLoadedMeta(false)};
 const onFile=(f:File|null)=>{setFile(f);reset()};
 const run=async()=>{setBusy(true);setError('');try{
  if(task.mode==='export'){if(task.format==='docx'){const bytes=await createDocx(input,{title,creator,plain:task.id==='text-to-docx'});download(bytes,safeFilename(title,'docx'),'application/vnd.openxmlformats-officedocument.wordprocessingml.document')}else{const bytes=await createEpub(input,{...meta,title:meta.title||title,creator:meta.creator||creator,plain:task.id==='text-to-epub'});download(bytes,safeFilename(meta.title||title,'epub'),'application/epub+zip')}return}
  if(!file)throw new Error(`Choose a ${task.format.toUpperCase()} file first.`);const bytes=await file.arrayBuffer();
  if(task.id==='docx-metadata-inspector'){setOutput(JSON.stringify(await inspectDocxMetadata(bytes),null,2));return}
  if(task.id==='epub-metadata-editor'){const m=await inspectEpubMetadata(bytes);setMeta(m);setLoadedMeta(true);setOutput(JSON.stringify(m,null,2));return}
  if(task.format==='docx')setOutput(await extractDocx(bytes,task.id.endsWith('markdown')?'markdown':task.id.endsWith('html')?'html':'text'));
  else if(task.format==='epub')setOutput(await extractEpub(bytes,task.id.endsWith('markdown')?'markdown':task.id.endsWith('html')?'html':'text'));
  else setOutput(await extractPptx(bytes,task.id.endsWith('markdown')?'markdown':'text'));
 }catch(e){setError(e instanceof globalThis.Error?e.message:String(e))}finally{setBusy(false)}};
 const saveEpubMeta=async()=>{if(!file)return;setBusy(true);setError('');try{const bytes=await editEpubMetadata(await file.arrayBuffer(),meta);download(bytes,safeFilename(meta.title||file.name.replace(/\.epub$/i,''),'epub'),'application/epub+zip')}catch(e){setError(e instanceof globalThis.Error?e.message:String(e))}finally{setBusy(false)}};
 const outExt=task.id.endsWith('markdown')?'md':task.id.endsWith('html')?'html':'txt';
 return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={['file-type-inspector','zip-manager','markdown-html-converter']}><div className="space-y-5"><div className="flex items-start gap-2 rounded-lg border border-sky-200 bg-sky-50 px-3 py-2 text-xs text-sky-800 dark:border-sky-900 dark:bg-sky-950/20 dark:text-sky-300"><BookOpen className="mt-0.5 h-4 w-4 shrink-0"/><span>Local content interchange. DOCX/PPTX extraction reads the packaged XML structure; EPUB processing reads or writes standard ZIP/XML eBook files. Layout-perfect Office rendering is intentionally not claimed.</span></div>
 {task.mode==='export'?<ExportForm taskId={task.id} format={task.format} input={input} setInput={setInput} title={title} setTitle={setTitle} creator={creator} setCreator={setCreator} meta={meta} setMeta={setMeta} busy={busy} run={run}/>:<><FilePicker accept={accept} file={file} onFile={onFile}/><button type="button" disabled={busy||!file} onClick={()=>void run()} className="rounded-lg bg-neutral-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50 dark:bg-neutral-100 dark:text-neutral-900">{busy?'Processing…':task.id==='epub-metadata-editor'?'Read metadata':'Process file'}</button>{task.id==='epub-metadata-editor'&&loadedMeta&&<MetadataFields value={meta} set={setMeta}/>} {task.id==='epub-metadata-editor'&&loadedMeta&&<button type="button" disabled={busy} onClick={()=>void saveEpubMeta()} className="inline-flex items-center gap-2 rounded-lg border px-4 py-2 text-sm font-semibold"><Download className="h-4 w-4"/>Save edited EPUB</button>}</>}
 {error&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{error}</div>}
 {output&&<Output value={output} filename={`converted.${outExt}`} type={outExt==='html'?'text/html;charset=utf-8':'text/plain;charset=utf-8'} downloadable={task.mode==='import'}/>}<Limit id={task.id}/></div></ToolShell>};

function FilePicker({accept,file,onFile}:{accept:string;file:File|null;onFile:(f:File|null)=>void}){return<label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed p-6 text-sm font-semibold"><Upload className="h-4 w-4"/>{file?file.name:'Choose local file'}<input type="file" accept={accept} className="sr-only" onChange={e=>onFile(e.target.files?.[0]??null)}/></label>}
function ExportForm({taskId,format,input,setInput,title,setTitle,creator,setCreator,meta,setMeta,busy,run}:{taskId:string;format:string;input:string;setInput:(v:string)=>void;title:string;setTitle:(v:string)=>void;creator:string;setCreator:(v:string)=>void;meta:BookMetadata;setMeta:React.Dispatch<React.SetStateAction<BookMetadata>>;busy:boolean;run:()=>Promise<void>}){const plain=taskId==='text-to-docx'||taskId==='text-to-epub';return<div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Input label="Title" value={format==='epub'?meta.title:title} set={v=>format==='epub'?setMeta(m=>({...m,title:v})):setTitle(v)}/><Input label="Creator / author" value={format==='epub'?meta.creator:creator} set={v=>format==='epub'?setMeta(m=>({...m,creator:v})):setCreator(v)}/></div>{format==='epub'&&<div className="grid gap-3 sm:grid-cols-2"><Input label="Language" value={meta.language} set={v=>setMeta(m=>({...m,language:v}))}/><Input label="Publisher (optional)" value={meta.publisher} set={v=>setMeta(m=>({...m,publisher:v}))}/></div>}<label className="block text-xs font-semibold">{plain?'Plain text':'Markdown'}<textarea rows={16} value={input} onChange={e=>setInput(e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent p-3 font-mono text-sm"/></label><button type="button" disabled={busy||!input.trim()} onClick={()=>void run()} className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50 dark:bg-neutral-100 dark:text-neutral-900"><FileText className="h-4 w-4"/>{busy?'Generating…':`Generate ${format.toUpperCase()}`}</button></div>}
function MetadataFields({value,set}:{value:BookMetadata;set:React.Dispatch<React.SetStateAction<BookMetadata>>}){return<div className="grid gap-3 sm:grid-cols-2">{(Object.keys(value)as(keyof BookMetadata)[]).map(k=><Input key={k} label={k[0].toUpperCase()+k.slice(1)} value={value[k]} set={v=>set(m=>({...m,[k]:v}))}/>)}</div>}
function Input({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return<label className="text-xs font-semibold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>}
function Output({value,filename,type,downloadable}:{value:string;filename:string;type:string;downloadable:boolean}){return<section className="rounded-xl border bg-neutral-50 p-3 dark:bg-neutral-950"><div className="mb-2 flex items-center justify-between gap-3"><div className="text-xs font-bold">Output</div>{downloadable&&<button type="button" onClick={()=>download(value,filename,type)} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Download className="h-3.5 w-3.5"/>Download</button>}</div><pre className="max-h-[32rem] overflow-auto whitespace-pre-wrap break-words text-xs">{value}</pre></section>}
function Limit({id}:{id:string}){const notes:Record<string,string>={
'docx-to-markdown':'Preserves paragraph order and recognizes common Word heading styles. Complex tables, floating objects, tracked changes, footnotes, equations, embedded media, and exact layout are outside this content extractor.',
'docx-to-html':'Produces semantic paragraph/heading HTML from Word paragraph content, not a pixel-perfect reproduction of Word layout.',
'docx-to-text':'Extracts readable paragraph text. Headers, footers, comments, drawings, and other non-body package parts are not merged into the result.',
'markdown-to-docx':'Creates a valid lightweight DOCX with paragraphs, headings, simple bullets, and quotes. It is designed for portable editable content rather than advanced Word styling.',
'text-to-docx':'Creates a simple editable DOCX from plain text without attempting page-layout design.',
'docx-metadata-inspector':'Reads common core and extended package properties when present; custom properties and document contents are not treated as metadata.',
'epub-to-markdown':'Reads the EPUB package spine in reading order and converts common XHTML structure to Markdown. CSS styling, media, scripts, and fixed-layout positioning are not reproduced.',
'epub-to-html':'Combines readable EPUB spine bodies into HTML sections; external CSS and fixed-layout rendering are intentionally not reproduced.',
'epub-to-text':'Extracts readable spine text in package reading order.',
'markdown-to-epub':'Creates a standards-oriented EPUB 3 package with one content document, navigation, basic CSS, and metadata. It is intentionally simple rather than a full publishing suite.',
'text-to-epub':'Creates a simple EPUB from paragraphs of plain text.',
'epub-metadata-editor':'Updates common Dublin Core package metadata while preserving the rest of the EPUB ZIP contents. DRM-protected books cannot be processed meaningfully.',
'pptx-to-text':'Extracts text from slide XML in slide-number order. Speaker notes, charts, SmartArt semantics, images, animations, and visual placement are not reproduced.',
'pptx-to-markdown':'Creates a slide-by-slide Markdown outline from visible slide text, not a visual PowerPoint conversion.'};return<p className="text-xs text-neutral-500">{notes[id]}</p>}
export default OfficeEbookInterchangeTools;
