export interface RatioPreset{name:string;w:number;h:number;}
export const RATIO_PRESETS:RatioPreset[]=[{name:'1:1 Square',w:1,h:1},{name:'4:3 Standard Display',w:4,h:3},{name:'3:2 Classic Photo / 35mm',w:3,h:2},{name:'5:4 Large Format',w:5,h:4},{name:'16:9 Widescreen / HD',w:16,h:9},{name:'16:10 Modern Laptop',w:16,h:10},{name:'18:9 Mobile Display',w:18,h:9},{name:'21:9 Ultrawide Cinematic',w:21,h:9},{name:'9:16 Vertical / Stories',w:9,h:16},{name:'4:5 Social Portrait',w:4,h:5},{name:'1.91:1 Social Landscape',w:1.91,h:1}];
export function calculateGcd(a:number,b:number):number{let x=Math.abs(Math.trunc(a)),y=Math.abs(Math.trunc(b));while(y){const t=y;y=x%y;x=t;}return x||1;}
function decimalPlaces(value:number):number{if(!Number.isFinite(value))return 0;const text=value.toString().toLowerCase();if(text.includes('e-'))return Math.min(8,Number(text.split('e-')[1])||0);return Math.min(8,(text.split('.')[1]||'').length);}
export function simplifyRatio(width:number,height:number):{ratioW:number;ratioH:number;ratioString:string;decimal:number;orientation:'Landscape'|'Portrait'|'Square';gcd:number}{if(!Number.isFinite(width)||!Number.isFinite(height)||width<=0||height<=0)return{ratioW:0,ratioH:0,ratioString:'Invalid dimensions',decimal:0,orientation:'Square',gcd:1};const places=Math.max(decimalPlaces(width),decimalPlaces(height)),factor=10**places,iw=Math.round(width*factor),ih=Math.round(height*factor),gcd=calculateGcd(iw,ih),ratioW=iw/gcd,ratioH=ih/gcd,orientation=width>height?'Landscape':height>width?'Portrait':'Square';return{ratioW,ratioH,ratioString:`${ratioW}:${ratioH}`,decimal:Number((width/height).toFixed(6)),orientation,gcd};}
export function calculateMissingDimension(ratioW:number,ratioH:number,knownValue:number,knownDimension:'width'|'height',roundToInteger=true):number|null{if(![ratioW,ratioH,knownValue].every(Number.isFinite)||ratioW<=0||ratioH<=0||knownValue<=0)return null;const v=knownDimension==='width'?knownValue*ratioH/ratioW:knownValue*ratioW/ratioH;return roundToInteger?Math.round(v):Number(v.toFixed(6));}
export function scaleResolution(origW:number,origH:number,newW?:number,newH?:number,roundToInteger=true):{targetW:number;targetH:number;scaleFactor:number}|null{if(![origW,origH].every(Number.isFinite)||origW<=0||origH<=0)return null;if(newW&&Number.isFinite(newW)&&newW>0){const s=newW/origW,h=origH*s;return{targetW:newW,targetH:roundToInteger?Math.round(h):Number(h.toFixed(4)),scaleFactor:Number(s.toFixed(6))};}if(newH&&Number.isFinite(newH)&&newH>0){const s=newH/origH,w=origW*s;return{targetW:roundToInteger?Math.round(w):Number(w.toFixed(4)),targetH:newH,scaleFactor:Number(s.toFixed(6))};}return null;}
export interface FitCalculation{mode:'contain'|'cover';outputWidth:number;outputHeight:number;scale:number;overflowWidth:number;overflowHeight:number;cropPercentX:number;cropPercentY:number;}
export function calculateFit(sourceW:number,sourceH:number,boxW:number,boxH:number,mode:'contain'|'cover'):FitCalculation|null{if(![sourceW,sourceH,boxW,boxH].every(Number.isFinite)||sourceW<=0||sourceH<=0||boxW<=0||boxH<=0)return null;const scale=mode==='cover'?Math.max(boxW/sourceW,boxH/sourceH):Math.min(boxW/sourceW,boxH/sourceH),outputWidth=sourceW*scale,outputHeight=sourceH*scale,overflowWidth=Math.max(0,outputWidth-boxW),overflowHeight=Math.max(0,outputHeight-boxH);return{mode,outputWidth:Number(outputWidth.toFixed(4)),outputHeight:Number(outputHeight.toFixed(4)),scale:Number(scale.toFixed(6)),overflowWidth:Number(overflowWidth.toFixed(4)),overflowHeight:Number(overflowHeight.toFixed(4)),cropPercentX:outputWidth?Number((overflowWidth/outputWidth*100).toFixed(2)):0,cropPercentY:outputHeight?Number((overflowHeight/outputHeight*100).toFixed(2)):0};}
export interface CropCalculation{sx:number;sy:number;sw:number;sh:number;removedPercent:number;ratio:string;}
export function calculateCropToRatio(sourceW:number,sourceH:number,ratioW:number,ratioH:number,anchorX=.5,anchorY=.5):CropCalculation|null{if(![sourceW,sourceH,ratioW,ratioH].every(Number.isFinite)||sourceW<=0||sourceH<=0||ratioW<=0||ratioH<=0)return null;const target=ratioW/ratioH,current=sourceW/sourceH;let sw=sourceW,sh=sourceH;if(current>target)sw=sourceH*target;else if(current<target)sh=sourceW/target;const ax=Math.max(0,Math.min(1,anchorX)),ay=Math.max(0,Math.min(1,anchorY)),sx=(sourceW-sw)*ax,sy=(sourceH-sh)*ay,removed=1-sw*sh/(sourceW*sourceH);return{sx:Number(sx.toFixed(4)),sy:Number(sy.toFixed(4)),sw:Number(sw.toFixed(4)),sh:Number(sh.toFixed(4)),removedPercent:Number((removed*100).toFixed(2)),ratio:`${ratioW}:${ratioH}`};}
export function findNearestRatioPreset(width:number,height:number):{preset:RatioPreset;errorPercent:number}|null{if(width<=0||height<=0)return null;const ratio=width/height;let best=RATIO_PRESETS[0],error=Infinity;for(const preset of RATIO_PRESETS){const candidate=preset.w/preset.h,diff=Math.abs(candidate-ratio)/ratio*100;if(diff<error){error=diff;best=preset;}}return{preset:best,errorPercent:Number(error.toFixed(2))};}
export function calculateConstrainedResolution(origW:number,origH:number,knownDimension:'width'|'height',knownValue:number,multipleOf=1):{width:number;height:number;scale:number}|null{if(![origW,origH,knownValue,multipleOf].every(Number.isFinite)||origW<=0||origH<=0||knownValue<=0||multipleOf<=0)return null;const raw=knownDimension==='width'?{width:knownValue,height:knownValue*origH/origW}:{width:knownValue*origW/origH,height:knownValue},snap=(v:number)=>Math.max(multipleOf,Math.round(v/multipleOf)*multipleOf),width=snap(raw.width),height=snap(raw.height);return{width,height,scale:Number(((width/origW+height/origH)/2).toFixed(6))};}
