/** Audio Recorder & Trimmer Utility */
export interface TrimRange{startSeconds:number;endSeconds:number;}
export interface AudioEditOptions{fadeInSeconds:number;fadeOutSeconds:number;gain:number;}
export async function decodeAudioBlob(blob:Blob,audioCtx:AudioContext):Promise<AudioBuffer>{return audioCtx.decodeAudioData(await blob.arrayBuffer());}

/** Returns peak buckets across all channels, including very short recordings. */
export function extractWaveformPeaks(buffer:AudioBuffer,numBuckets=200):number[]{const buckets=Math.max(1,Math.floor(numBuckets));const total=buffer.length;if(total<=0)return Array(buckets).fill(0);const channels=Array.from({length:Math.max(1,buffer.numberOfChannels)},(_,index)=>buffer.getChannelData(index));const peaks:number[]=[];for(let bucket=0;bucket<buckets;bucket++){const start=Math.min(total-1,Math.floor(bucket*total/buckets));const end=Math.max(start+1,Math.min(total,Math.ceil((bucket+1)*total/buckets)));let peak=0;for(const channel of channels){for(let sample=start;sample<end;sample++)peak=Math.max(peak,Math.abs(channel[sample]||0));}peaks.push(peak);}return peaks;}

export function trimAudioBuffer(sourceBuffer:AudioBuffer,audioCtx:AudioContext,range:TrimRange,options:AudioEditOptions={fadeInSeconds:0,fadeOutSeconds:0,gain:1}):AudioBuffer{
 const rate=sourceBuffer.sampleRate,channels=sourceBuffer.numberOfChannels,duration=sourceBuffer.duration;const rawStart=Number.isFinite(range.startSeconds)?range.startSeconds:0,rawEnd=Number.isFinite(range.endSeconds)?range.endSeconds:duration;const startSeconds=Math.max(0,Math.min(duration,Math.min(rawStart,rawEnd)));const endSeconds=Math.max(startSeconds,Math.min(duration,Math.max(rawStart,rawEnd)));const startSample=Math.min(sourceBuffer.length,Math.floor(startSeconds*rate));const endSample=Math.min(sourceBuffer.length,Math.max(startSample+1,Math.ceil(endSeconds*rate)));const length=Math.max(1,endSample-startSample);const output=audioCtx.createBuffer(channels,length,rate);const fadeIn=Math.min(length,Math.max(0,Math.round(Math.max(0,options.fadeInSeconds)*rate)));const fadeOut=Math.min(length,Math.max(0,Math.round(Math.max(0,options.fadeOutSeconds)*rate)));const gain=Number.isFinite(options.gain)?Math.max(0,options.gain):1;
 for(let ch=0;ch<channels;ch++){const source=sourceBuffer.getChannelData(ch),dest=output.getChannelData(ch);for(let i=0;i<length;i++){let sample=(source[startSample+i]||0)*gain;if(fadeIn>0&&i<fadeIn)sample*=fadeIn===1?1:i/(fadeIn-1);if(fadeOut>0&&i>=length-fadeOut)sample*=fadeOut===1?0:(length-1-i)/(fadeOut-1);dest[i]=Math.max(-1,Math.min(1,sample));}}
 return output;
}

export function audioBufferToWavBlob(buffer:AudioBuffer):Blob{const channels=buffer.numberOfChannels,rate=buffer.sampleRate,bitDepth=16,bytesPerSample=2,blockAlign=channels*bytesPerSample,byteRate=rate*blockAlign,dataSize=buffer.length*channels*bytesPerSample,totalSize=44+dataSize,arrayBuffer=new ArrayBuffer(totalSize),view=new DataView(arrayBuffer);writeString(view,0,'RIFF');view.setUint32(4,totalSize-8,true);writeString(view,8,'WAVE');writeString(view,12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,rate,true);view.setUint32(28,byteRate,true);view.setUint16(32,blockAlign,true);view.setUint16(34,bitDepth,true);writeString(view,36,'data');view.setUint32(40,dataSize,true);let offset=44;for(let i=0;i<buffer.length;i++){for(let ch=0;ch<channels;ch++){const sample=Math.max(-1,Math.min(1,buffer.getChannelData(ch)[i]||0));view.setInt16(offset,Math.round(sample<0?sample*0x8000:sample*0x7fff),true);offset+=2;}}return new Blob([arrayBuffer],{type:'audio/wav'});}
function writeString(view:DataView,offset:number,value:string):void{for(let i=0;i<value.length;i++)view.setUint8(offset+i,value.charCodeAt(i));}
