/** Client-side background removal and mask-refinement utilities. */
export interface SegmentationResult{segmentedBlob:Blob;segmentedDataUrl:string;width:number;height:number;maskCanvas:HTMLCanvasElement;}
export type BackgroundStyle='transparent'|'white'|'black'|'custom-color'|'custom-image';
export interface BgRemoverOptions{backgroundStyle:BackgroundStyle;customColor:string;customImage?:HTMLImageElement|null;smoothing:number;feather:number;quality:number;format:'image/png'|'image/jpeg'|'image/webp';}
export interface RgbColor{r:number;g:number;b:number;}
export type MaskBrushMode='restore'|'erase';
const colorDistance=(r:number,g:number,b:number,target:RgbColor)=>Math.hypot(r-target.r,g-target.g,b-target.b);
export function estimateCornerBackgroundColor(rgba:Uint8ClampedArray,width:number,height:number,radius=2):RgbColor{if(width<=0||height<=0||rgba.length<width*height*4)return{r:255,g:255,b:255};const anchors=[[0,0],[width-1,0],[0,height-1],[width-1,height-1]];let r=0,g=0,b=0,count=0;for(const[aX,aY]of anchors){for(let dy=-radius;dy<=radius;dy++){for(let dx=-radius;dx<=radius;dx++){const x=Math.max(0,Math.min(width-1,aX+dx)),y=Math.max(0,Math.min(height-1,aY+dy)),i=(y*width+x)*4;r+=rgba[i];g+=rgba[i+1];b+=rgba[i+2];count++;}}}return{r:r/Math.max(1,count),g:g/Math.max(1,count),b:b/Math.max(1,count)};}
/** Adapts tolerance to noisy JPEG/photo corners without letting it grow unbounded. */
export function estimateBackgroundTolerance(rgba:Uint8ClampedArray,width:number,height:number,background=estimateCornerBackgroundColor(rgba,width,height)):number{if(width<=0||height<=0)return 45;const samples:number[]=[];const radius=Math.max(1,Math.min(5,Math.floor(Math.min(width,height)/40)));const anchors=[[0,0],[width-1,0],[0,height-1],[width-1,height-1]];for(const[aX,aY]of anchors)for(let dy=-radius;dy<=radius;dy++)for(let dx=-radius;dx<=radius;dx++){const x=Math.max(0,Math.min(width-1,aX+dx)),y=Math.max(0,Math.min(height-1,aY+dy)),i=(y*width+x)*4;samples.push(colorDistance(rgba[i],rgba[i+1],rgba[i+2],background));}const mean=samples.reduce((s,v)=>s+v,0)/Math.max(1,samples.length);const variance=samples.reduce((s,v)=>s+(v-mean)**2,0)/Math.max(1,samples.length);return Math.round(Math.max(28,Math.min(85,34+mean+Math.sqrt(variance)*2.2)));}
export function buildConnectedBackgroundMask(rgba:Uint8ClampedArray,width:number,height:number,tolerance=45,background=estimateCornerBackgroundColor(rgba,width,height)):Uint8Array{const pixelCount=Math.max(0,width*height),mask=new Uint8Array(pixelCount);if(!pixelCount||rgba.length<pixelCount*4)return mask;const visited=new Uint8Array(pixelCount),queue=new Int32Array(pixelCount);let head=0,tail=0;const matches=(p:number)=>{const i=p*4;return rgba[i+3]<16||colorDistance(rgba[i],rgba[i+1],rgba[i+2],background)<=tolerance;};const seed=(p:number)=>{if(visited[p])return;visited[p]=1;if(!matches(p))return;mask[p]=1;queue[tail++]=p;};for(let x=0;x<width;x++){seed(x);if(height>1)seed((height-1)*width+x);}for(let y=1;y<height-1;y++){seed(y*width);if(width>1)seed(y*width+width-1);}while(head<tail){const p=queue[head++],x=p%width,y=Math.floor(p/width);const neighbors=[x>0?p-1:-1,x+1<width?p+1:-1,y>0?p-width:-1,y+1<height?p+width:-1];for(const n of neighbors){if(n<0||visited[n])continue;visited[n]=1;if(!matches(n))continue;mask[n]=1;queue[tail++]=n;}}return mask;}
function blurAlpha(alpha:Uint8Array,width:number,height:number,radius:number):Uint8Array{if(radius<=0)return new Uint8Array(alpha);const r=Math.min(12,Math.max(1,Math.round(radius))),temp=new Float32Array(alpha.length),out=new Uint8Array(alpha.length);for(let y=0;y<height;y++){let sum=0;for(let x=-r;x<=r;x++)sum+=alpha[y*width+Math.max(0,Math.min(width-1,x))];for(let x=0;x<width;x++){temp[y*width+x]=sum/(r*2+1);sum-=alpha[y*width+Math.max(0,x-r)];sum+=alpha[y*width+Math.min(width-1,x+r+1)];}}for(let x=0;x<width;x++){let sum=0;for(let y=-r;y<=r;y++)sum+=temp[Math.max(0,Math.min(height-1,y))*width+x];for(let y=0;y<height;y++){out[y*width+x]=Math.round(sum/(r*2+1));sum-=temp[Math.max(0,y-r)*width+x];sum+=temp[Math.min(height-1,y+r+1)*width+x];}}return out;}
/** Applies small morphological cleanup plus feathering to an RGBA alpha channel. */
export function refineAlphaMaskRgba(source:Uint8ClampedArray,width:number,height:number,smoothing=0,feather=0):Uint8ClampedArray{if(source.length!==width*height*4||width<=0||height<=0)return new Uint8ClampedArray(source);const out=new Uint8ClampedArray(source),alpha=new Uint8Array(width*height);for(let p=0;p<alpha.length;p++)alpha[p]=source[p*4+3];const passes=Math.max(0,Math.min(3,Math.round(smoothing/3)));let current=alpha;for(let pass=0;pass<passes;pass++){const next=new Uint8Array(current.length);for(let y=0;y<height;y++)for(let x=0;x<width;x++){let sum=0,count=0;for(let dy=-1;dy<=1;dy++)for(let dx=-1;dx<=1;dx++){const nx=x+dx,ny=y+dy;if(nx<0||nx>=width||ny<0||ny>=height)continue;sum+=current[ny*width+nx];count++;}const avg=sum/Math.max(1,count),a=current[y*width+x];next[y*width+x]=avg>170?Math.max(a,Math.round(avg)):avg<85?Math.min(a,Math.round(avg)):a;}current=next;}current=blurAlpha(current,width,height,Math.max(0,Math.min(10,feather)));for(let p=0;p<current.length;p++)out[p*4+3]=current[p];return out;}
/** Pure brush operation used by the refine UI; restore copies original RGBA while erase changes alpha only. */
export function applyCircularMaskBrush(target:Uint8ClampedArray,original:Uint8ClampedArray,width:number,height:number,points:{x:number;y:number}[],radius:number,mode:MaskBrushMode):Uint8ClampedArray{const out=new Uint8ClampedArray(target);if(out.length!==width*height*4||original.length!==out.length)return out;const r=Math.max(1,Math.min(Math.max(width,height),radius));for(const point of points){const minX=Math.max(0,Math.floor(point.x-r)),maxX=Math.min(width-1,Math.ceil(point.x+r)),minY=Math.max(0,Math.floor(point.y-r)),maxY=Math.min(height-1,Math.ceil(point.y+r));for(let y=minY;y<=maxY;y++)for(let x=minX;x<=maxX;x++){const d=Math.hypot(x-point.x,y-point.y);if(d>r)continue;const strength=Math.min(1,Math.max(0,(r-d)/Math.max(1,r*0.35))),i=(y*width+x)*4;if(mode==='erase'){out[i+3]=Math.round(out[i+3]*(1-strength));}else{out[i]=original[i];out[i+1]=original[i+1];out[i+2]=original[i+2];out[i+3]=Math.max(out[i+3],Math.round(original[i+3]*strength));}}}return out;}
export async function removeBackgroundLocal(imageBlob:Blob,onProgress?:(stage:string,percent:number)=>void):Promise<Blob>{onProgress?.('Loading local ML model...',20);try{const{removeBackground}=await import('@imgly/background-removal');onProgress?.('Segmenting foreground with local neural network...',50);const result=await removeBackground(imageBlob,{progress:(_key:string,current:number,total:number)=>{if(total>0)onProgress?.(`Processing image (${Math.min(95,Math.round(50+current/total*45))}%)...`,Math.min(95,Math.round(50+current/total*45)));},output:{format:'image/png',quality:0.95}});onProgress?.('Refining edges...',98);return result;}catch(error){console.warn('ML background removal failed; using connected local fallback:',error);onProgress?.('Applying connected local background segmenter...',60);return removeBackgroundCanvasFallback(imageBlob,onProgress);}}
export async function removeBackgroundCanvasFallback(imageBlob:Blob,onProgress?:(stage:string,percent:number)=>void):Promise<Blob>{return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(imageBlob);img.onload=()=>{URL.revokeObjectURL(url);const canvas=document.createElement('canvas');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx||!canvas.width||!canvas.height){reject(new Error('Canvas 2D context unavailable'));return;}ctx.drawImage(img,0,0);const image=ctx.getImageData(0,0,canvas.width,canvas.height),data=image.data,background=estimateCornerBackgroundColor(data,canvas.width,canvas.height),tolerance=estimateBackgroundTolerance(data,canvas.width,canvas.height,background),mask=buildConnectedBackgroundMask(data,canvas.width,canvas.height,tolerance,background);onProgress?.('Generating connected transparency mask...',82);for(let p=0;p<mask.length;p++)if(mask[p])data[p*4+3]=0;const refined=refineAlphaMaskRgba(data,canvas.width,canvas.height,2,2);image.data.set(refined);ctx.putImageData(image,0,0);onProgress?.('Done!',100);canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Blob generation failed')),'image/png');};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('Failed to load image for fallback segmentation'));};img.src=url;});}
function drawCover(ctx:CanvasRenderingContext2D,img:HTMLImageElement,w:number,h:number){const sw=img.naturalWidth||img.width,sh=img.naturalHeight||img.height,scale=Math.max(w/sw,h/sh),dw=sw*scale,dh=sh*scale;ctx.drawImage(img,(w-dw)/2,(h-dh)/2,dw,dh);}
export function compositeSegmentedImage(foregroundImg:HTMLImageElement,options:BgRemoverOptions,destCanvas:HTMLCanvasElement):void{destCanvas.width=foregroundImg.naturalWidth;destCanvas.height=foregroundImg.naturalHeight;const ctx=destCanvas.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,destCanvas.width,destCanvas.height);if(options.backgroundStyle==='white'){ctx.fillStyle='#fff';ctx.fillRect(0,0,destCanvas.width,destCanvas.height);}else if(options.backgroundStyle==='black'){ctx.fillStyle='#000';ctx.fillRect(0,0,destCanvas.width,destCanvas.height);}else if(options.backgroundStyle==='custom-color'){ctx.fillStyle=options.customColor||'#3B82F6';ctx.fillRect(0,0,destCanvas.width,destCanvas.height);}else if(options.backgroundStyle==='custom-image'&&options.customImage)drawCover(ctx,options.customImage,destCanvas.width,destCanvas.height);ctx.drawImage(foregroundImg,0,0);}
