import { resolveDateInZone } from './time-zone-converter';
export type EventRecurrence='NONE'|'DAILY'|'WEEKLY'|'MONTHLY'|'YEARLY';export type EventReminder=0|5|10|15|30|60|1440;
export interface CalendarEventData{title:string;description:string;location:string;url:string;startDate:string;startTime:string;endDate:string;endTime:string;isAllDay:boolean;timezone:string;reminderMinutes:EventReminder;recurrence:EventRecurrence;repeatCount?:number;repeatUntil?:string;organizerName?:string;organizerEmail?:string;attendees?:string[];recurrenceInterval?:number;recurrenceByWeekday?:string[];status?:'TENTATIVE'|'CONFIRMED'|'CANCELLED';transparency?:'OPAQUE'|'TRANSPARENT';additionalReminders?:number[];}
const FALLBACK_ZONES=['UTC','America/New_York','America/Chicago','America/Denver','America/Los_Angeles','America/Toronto','America/Sao_Paulo','Europe/London','Europe/Paris','Europe/Berlin','Asia/Dubai','Asia/Kolkata','Asia/Singapore','Asia/Seoul','Asia/Tokyo','Australia/Sydney','Pacific/Auckland'];
export function getSupportedCalendarTimeZones():string[]{try{const supported=(Intl as typeof Intl&{supportedValuesOf?:(key:string)=>string[]}).supportedValuesOf?.('timeZone')||[];return ['UTC',...supported.filter(z=>z!=='UTC')];}catch{return FALLBACK_ZONES;}}
export const COMMON_TIMEZONES=getSupportedCalendarTimeZones();
let fallbackUidCounter=0;
export function escapeIcsText(s:string):string{return(s||'').replace(/\\/g,'\\\\').replace(/;/g,'\\;').replace(/,/g,'\\,').replace(/\r?\n/g,'\\n');}
export function escapeIcsParameter(s:string):string{const value=s.replace(/[\r\n]/g,' ').trim();if(!value)return'';const escaped=value.replace(/\\/g,'\\\\').replace(/"/g,'\\"');return/[,:;\s]/.test(escaped)?`"${escaped}"`:escaped;}
export function foldIcsLine(line:string,maxOctets=75):string[]{const enc=new TextEncoder(),limit=Math.max(16,maxOctets);if(enc.encode(line).length<=limit)return[line];const out:string[]=[];let cur='',bytes=0;for(const ch of line){const n=enc.encode(ch).length,effective=out.length?limit-1:limit;if(cur&&bytes+n>effective){out.push(out.length?` ${cur}`:cur);cur=ch;bytes=n;}else{cur+=ch;bytes+=n;}}if(cur)out.push(out.length?` ${cur}`:cur);return out;}
export function formatIcsUtcTimestamp(date:Date):string{const p=(n:number)=>String(n).padStart(2,'0');return`${date.getUTCFullYear()}${p(date.getUTCMonth()+1)}${p(date.getUTCDate())}T${p(date.getUTCHours())}${p(date.getUTCMinutes())}${p(date.getUTCSeconds())}Z`;}
function addDays(dateStr:string,days:number){const[y,m,d]=dateStr.split('-').map(Number),date=new Date(0);date.setUTCFullYear(y,m-1,d+days);date.setUTCHours(0,0,0,0);return`${date.getUTCFullYear()}-${String(date.getUTCMonth()+1).padStart(2,'0')}-${String(date.getUTCDate()).padStart(2,'0')}`;}
export function formatIcsDateTime(dateStr:string,timeStr:string,isAllDay:boolean,timezone:string):{icsKey:string;icsValue:string}{const date=dateStr.replace(/-/g,'');if(isAllDay)return{icsKey:';VALUE=DATE',icsValue:date};const time=(timeStr||'09:00').replace(/:/g,'')+'00';return timezone==='UTC'?{icsKey:'',icsValue:`${date}T${time}Z`}:{icsKey:`;TZID=${timezone}`,icsValue:`${date}T${time}`};}
function zoneValid(zone:string){try{new Intl.DateTimeFormat('en',{timeZone:zone}).format(0);return true;}catch{return false;}}
function wallInstant(date:string,time:string,zone:string):Date{const[y,m,d]=date.split('-').map(Number),[h,min]=time.split(':').map(Number);return zone==='UTC'?new Date(Date.UTC(y,m-1,d,h||0,min||0)):resolveDateInZone(y,m,d,h||0,min||0,zone).date;}
export function validateCalendarEvent(event:CalendarEventData):{isValid:boolean;errors:string[]}{const errors:string[]=[];if(!event.title.trim())errors.push('Event title is required.');if(!/^\d{4}-\d{2}-\d{2}$/.test(event.startDate))errors.push('Start date is required.');if(!event.isAllDay&&!/^\d{2}:\d{2}$/.test(event.startTime))errors.push('Start time is required for timed events.');if(!zoneValid(event.timezone||'UTC'))errors.push('Time zone is not supported by this browser.');if(event.startDate&&event.endDate){const start=event.isAllDay?Date.parse(`${event.startDate}T00:00:00Z`):wallInstant(event.startDate,event.startTime,event.timezone||'UTC').getTime(),end=event.isAllDay?Date.parse(`${event.endDate}T23:59:59Z`):wallInstant(event.endDate,event.endTime||event.startTime,event.timezone||'UTC').getTime();if(end<start)errors.push('End date/time cannot be earlier than start date/time.');}const emails=[event.organizerEmail,...(event.attendees||[])].filter(Boolean) as string[];for(const email of emails)if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email.trim()))errors.push(`Invalid email address: ${email}`);if(event.repeatCount!==undefined&&(!Number.isInteger(event.repeatCount)||event.repeatCount<1))errors.push('Repeat count must be a positive whole number.');if(event.recurrenceInterval!==undefined&&(!Number.isInteger(event.recurrenceInterval)||event.recurrenceInterval<1))errors.push('Recurrence interval must be a positive whole number.');return{isValid:!errors.length,errors};}
export function createCalendarUid():string{return globalThis.crypto?.randomUUID?.()?`${globalThis.crypto.randomUUID()}@tinytools.local`:`event-${Date.now()}-${(++fallbackUidCounter).toString(36)}@tinytools.local`;}
function trigger(minutes:number){if(minutes===1440)return'-P1D';if(minutes>=60&&minutes%60===0)return`-PT${minutes/60}H`;return`-PT${minutes}M`;}
function recurrenceUntil(event:CalendarEventData):string|undefined{if(!event.repeatUntil)return;const clean=event.repeatUntil.replace(/-/g,'');if(event.isAllDay)return clean;return formatIcsUtcTimestamp(wallInstant(event.repeatUntil,event.startTime,event.timezone||'UTC'));}
function safeUri(value:string){return value.replace(/[\r\n]/g,'').trim();}
export function generateIcsFile(event:CalendarEventData):string{const validity=validateCalendarEvent(event);if(!validity.isValid)throw new Error(validity.errors.join(' '));const start=formatIcsDateTime(event.startDate,event.startTime,event.isAllDay,event.timezone||'UTC'),selectedEnd=event.endDate||event.startDate,effectiveEnd=event.isAllDay?addDays(selectedEnd,1):selectedEnd,end=formatIcsDateTime(effectiveEnd,event.endTime||event.startTime,event.isAllDay,event.timezone||'UTC');const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Tiny Tools//Calendar Event Maker//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH',`X-WR-TIMEZONE:${safeUri(event.timezone||'UTC')}`,'BEGIN:VEVENT',`UID:${createCalendarUid()}`,`DTSTAMP:${formatIcsUtcTimestamp(new Date())}`,`DTSTART${start.icsKey}:${start.icsValue}`,`DTEND${end.icsKey}:${end.icsValue}`,`SUMMARY:${escapeIcsText(event.title)}`];if(event.description.trim())lines.push(`DESCRIPTION:${escapeIcsText(event.description)}`);if(event.location.trim())lines.push(`LOCATION:${escapeIcsText(event.location)}`);if(event.url.trim())lines.push(`URL:${safeUri(event.url)}`);if(event.organizerEmail?.trim())lines.push(`ORGANIZER${event.organizerName?.trim()?`;CN=${escapeIcsParameter(event.organizerName)}`:''}:mailto:${event.organizerEmail.trim()}`);for(const attendee of new Set((event.attendees||[]).map(v=>v.trim()).filter(Boolean)))lines.push(`ATTENDEE;ROLE=REQ-PARTICIPANT;RSVP=TRUE:mailto:${attendee}`);if(event.status)lines.push(`STATUS:${event.status}`);if(event.transparency)lines.push(`TRANSP:${event.transparency}`);if(event.recurrence!=='NONE'){let rule=`RRULE:FREQ=${event.recurrence}`;if((event.recurrenceInterval||1)>1)rule+=`;INTERVAL=${event.recurrenceInterval}`;if(event.recurrenceByWeekday?.length)rule+=`;BYDAY=${event.recurrenceByWeekday.join(',')}`;if(event.repeatCount)rule+=`;COUNT=${event.repeatCount}`;else{const until=recurrenceUntil(event);if(until)rule+=`;UNTIL=${until}`;}lines.push(rule);}const reminders=[event.reminderMinutes,...(event.additionalReminders||[])].filter((v,i,a)=>v>0&&a.indexOf(v)===i);for(const mins of reminders)lines.push('BEGIN:VALARM','ACTION:DISPLAY',`DESCRIPTION:${escapeIcsText(event.title)}`,`TRIGGER:${trigger(mins)}`,'END:VALARM');lines.push('END:VEVENT','END:VCALENDAR');return lines.flatMap(line=>foldIcsLine(line)).join('\r\n');}
function compactUtc(date:string,time:string,zone:string){return formatIcsUtcTimestamp(wallInstant(date,time,zone)).replace(/[:-]/g,'');}
export function generateGoogleCalendarUrl(event:CalendarEventData):string{const p=new URLSearchParams({action:'TEMPLATE',text:event.title,details:event.description||'',location:event.location||''});if(event.isAllDay)p.set('dates',`${event.startDate.replace(/-/g,'')}/${addDays(event.endDate||event.startDate,1).replace(/-/g,'')}`);else p.set('dates',`${compactUtc(event.startDate,event.startTime,event.timezone)}/${compactUtc(event.endDate||event.startDate,event.endTime||event.startTime,event.timezone)}`);return`https://calendar.google.com/calendar/render?${p.toString()}`;}
export function generateOutlookCalendarUrl(event:CalendarEventData):string{const p=new URLSearchParams({path:'/calendar/action/compose',rru:'addevent',subject:event.title,body:event.description||'',location:event.location||'',startdt:wallInstant(event.startDate,event.startTime||'00:00',event.timezone).toISOString(),enddt:wallInstant(event.endDate||event.startDate,event.endTime||event.startTime||'00:00',event.timezone).toISOString()});return`https://outlook.live.com/calendar/0/deeplink/compose?${p.toString()}`;}
