export type CaseType='lowercase'|'UPPERCASE'|'Sentence case'|'Title Case'|'camelCase'|'PascalCase'|'snake_case'|'kebab-case'|'CONSTANT_CASE'|'dot.case'|'path/case'|'Train-Case'|'COBOL-CASE'|'Header Case';export interface CaseConversionResult{type:CaseType;label:string;example:string;result:string;}export interface CaseConversionOptions{locale?:string;splitLetterDigit?:boolean;preserveAcronyms?:string[];}
export function splitIntoWords(text:string):string[]{if(!text.trim())return[];return text.normalize('NFC').replace(/([\p{Ll}\p{N}])([\p{Lu}])/gu,'$1 $2').replace(/([\p{Lu}]+)([\p{Lu}][\p{Ll}])/gu,'$1 $2').replace(/[_\-./\\~|:,;!?"'()[\]{}<>@#$%^&*+=]+/g,' ').trim().split(/\s+/u).filter(Boolean);}
export function splitIntoWordsAdvanced(text:string,options:CaseConversionOptions={}):string[]{let value=text;if(options.splitLetterDigit)value=value.replace(/([\p{L}])(\p{N})/gu,'$1 $2').replace(/(\p{N})([\p{L}])/gu,'$1 $2');return splitIntoWords(value);}
const lower=(w:string,locale?:string)=>w.toLocaleLowerCase(locale),upper=(w:string,locale?:string)=>w.toLocaleUpperCase(locale);const initial=(w:string,locale?:string)=>{const l=lower(w,locale),chars=Array.from(l);return chars.length?upper(chars[0],locale)+chars.slice(1).join(''):'';};
export const toLowercase=(t:string,locale?:string)=>lower(t,locale);export const toUppercase=(t:string,locale?:string)=>upper(t,locale);
export function toSentenceCase(text:string,locale?:string):string{if(!text)return'';return lower(text,locale).replace(/(^\s*|[.!?。！？\n]\s*)([\p{L}])/gu,(_,p,l)=>p+upper(l,locale));}
const MINOR=new Set(['a','an','and','as','at','but','by','en','for','if','in','nor','of','on','or','per','the','to','via','vs','with']);
function capToken(token:string,locale?:string){return lower(token,locale).replace(/^([^\p{L}]*)(\p{L})/u,(_,p,l)=>p+upper(l,locale));}
export function toTitleCase(text:string,locale?:string):string{if(!text)return'';return text.split('\n').map(line=>{const tokens=line.match(/\S+|\s+/gu)||[],indices=tokens.map((v,i)=>/\p{L}/u.test(v)?i:-1).filter(i=>i>=0),first=indices[0],last=indices.at(-1);return tokens.map((token,i)=>{if(/^\s+$/u.test(token)||!/\p{L}/u.test(token))return token;const parts=token.split(/(-)/),lex=parts.filter(x=>x!=='-');return parts.map((part,j)=>{if(part==='-')return part;const bare=part.replace(/^[^\p{L}]*/u,'').replace(/[^\p{L}]*$/u,'').toLocaleLowerCase(locale),li=parts.slice(0,j).filter(x=>x!=='-').length,boundary=i===first||i===last||(parts.length>1&&(li===0||li===lex.length-1));return MINOR.has(bare)&&!boundary?lower(part,locale):capToken(part,locale);}).join('');}).join('');}).join('\n');}
function words(text:string,o:CaseConversionOptions={}){return splitIntoWordsAdvanced(text,o);}function normalizedWord(word:string,index:number,o:CaseConversionOptions,capitalize=false){const acronyms=new Set((o.preserveAcronyms||[]).map(a=>a.toLocaleLowerCase(o.locale)));if(acronyms.has(word.toLocaleLowerCase(o.locale)))return word.toLocaleUpperCase(o.locale);return capitalize||index>0?initial(word,o.locale):lower(word,o.locale);}
export function toCamelCase(t:string,o:CaseConversionOptions={}):string{return words(t,o).map((w,i)=>normalizedWord(w,i,o,false)).join('');}export function toPascalCase(t:string,o:CaseConversionOptions={}):string{return words(t,o).map((w,i)=>normalizedWord(w,i,o,true)).join('');}export function toSnakeCase(t:string,o:CaseConversionOptions={}):string{return words(t,o).map(w=>lower(w,o.locale)).join('_');}export function toKebabCase(t:string,o:CaseConversionOptions={}):string{return words(t,o).map(w=>lower(w,o.locale)).join('-');}export function toConstantCase(t:string,o:CaseConversionOptions={}):string{return words(t,o).map(w=>upper(w,o.locale)).join('_');}export function toDotCase(t:string,o:CaseConversionOptions={}):string{return words(t,o).map(w=>lower(w,o.locale)).join('.');}
export function convertCase(text:string,type:CaseType):string{return convertCaseAdvanced(text,type);}
export function convertCaseAdvanced(text:string,type:CaseType,o:CaseConversionOptions={}):string{switch(type){case'lowercase':return toLowercase(text,o.locale);case'UPPERCASE':return toUppercase(text,o.locale);case'Sentence case':return toSentenceCase(text,o.locale);case'Title Case':return toTitleCase(text,o.locale);case'camelCase':return toCamelCase(text,o);case'PascalCase':return toPascalCase(text,o);case'snake_case':return toSnakeCase(text,o);case'kebab-case':return toKebabCase(text,o);case'CONSTANT_CASE':return toConstantCase(text,o);case'dot.case':return toDotCase(text,o);case'path/case':return words(text,o).map(w=>lower(w,o.locale)).join('/');case'Train-Case':return words(text,o).map(w=>initial(w,o.locale)).join('-');case'COBOL-CASE':return words(text,o).map(w=>upper(w,o.locale)).join('-');case'Header Case':return words(text,o).map(w=>initial(w,o.locale)).join(' ');default:return text;}}
export function convertAllCases(input:string):CaseConversionResult[]{const defs:Array<[CaseType,string,string]>=[['lowercase','lower case','hello world'],['UPPERCASE','UPPER CASE','HELLO WORLD'],['Sentence case','Sentence case','Hello world.'],['Title Case','Title Case','Hello World'],['camelCase','camelCase','helloWorld'],['PascalCase','PascalCase','HelloWorld'],['snake_case','snake_case','hello_world'],['kebab-case','kebab-case','hello-world'],['CONSTANT_CASE','CONSTANT_CASE','HELLO_WORLD'],['dot.case','dot.case','hello.world'],['path/case','path/case','hello/world'],['Train-Case','Train-Case','Hello-World'],['COBOL-CASE','COBOL-CASE','HELLO-WORLD'],['Header Case','Header Case','Hello World']];return defs.map(([type,label,example])=>({type,label,example,result:convertCase(input,type)}));}
export function detectCaseStyle(text:string):CaseType|'mixed'{if(text&&text===text.toUpperCase()&&/_/.test(text))return'CONSTANT_CASE';if(/^[a-z][\p{L}\p{N}]*([A-Z][\p{L}\p{N}]*)+$/u.test(text))return'camelCase';if(/^[A-Z][\p{L}\p{N}]*([A-Z][\p{L}\p{N}]*)*$/u.test(text)&&!/[ _.-]/.test(text))return'PascalCase';if(/^[\p{Ll}\p{N}]+(?:_[\p{Ll}\p{N}]+)+$/u.test(text))return'snake_case';if(/^[\p{Ll}\p{N}]+(?:-[\p{Ll}\p{N}]+)+$/u.test(text))return'kebab-case';if(/^[\p{Ll}\p{N}]+(?:\.[\p{Ll}\p{N}]+)+$/u.test(text))return'dot.case';return'mixed';}
export function slugify(text:string,locale?:string):string{return text.normalize('NFKD').replace(/\p{M}+/gu,'').toLocaleLowerCase(locale).replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-+|-+$/g,'').replace(/-{2,}/g,'-');}
export function convertLines(text:string,type:CaseType,o:CaseConversionOptions={}):string{return text.split(/\r?\n/).map(line=>convertCaseAdvanced(line,type,o)).join('\n');}
