/** Checklist persistence, import/export and deterministic list transformations. */
export type ChecklistPriority='low'|'medium'|'high';
export interface ChecklistItem{id:string;text:string;completed:boolean;priority?:ChecklistPriority;note?:string;}
export interface ChecklistDoc{id:string;title:string;updatedAt:number;items:ChecklistItem[];}
export interface ChecklistStore{version:number;activeListId:string;lists:ChecklistDoc[];}
export const CHECKLIST_STORAGE_KEY='tiny_tools_checklist_store_v1';
export const CHECKLIST_TEMPLATES:{id:string;name:string;items:string[]}[]=[
{id:'travel',name:'Travel & Vacation Packing',items:['Passport / ID & Boarding Pass','Phone, Laptop & Multi-port Charger','Power Bank / Portable Battery','Universal Plug Adapter','Travel Insurance documents','Prescription Medications & First Aid','Toothbrush, Toothpaste & Floss','Shampoo, Body Wash & Deodorant','Weather-appropriate Clothing & Jacket','Underwear & Socks (1 pair/day + extra)','Comfortable Walking Shoes','Sunglasses & Sunscreen','Earplugs & Sleep Mask','Headphones / Earbuds']},
{id:'weekend',name:'Weekend Trip',items:['Change of clothes (2-3 days)','Toiletries kit','Phone charger','Water bottle','Snacks for journey','House keys & Wallet','Weather layer / Light jacket']},
{id:'camping',name:'Camping Essentials',items:['Tent, Stakes & Rainfly','Sleeping Bag & Ground Pad','Flashlight / Headlamp + Extra Batteries','Camp Stove, Fuel & Lighter/Matches','Cookware, Utensils & Mug','Water Filter or Purification Tablets','Insect Repellent & Sunscreen','Trash Bags (Leave No Trace)','Multi-tool / Pocket Knife','Warm Fleece & Thermal Base Layers']},
{id:'moving',name:'Moving Checklist',items:['Cardboard boxes & Heavy-duty packing tape','Bubble wrap & packing paper','Permanent markers for labeling rooms','Essentials box for first night','Notify utility companies','Change address with Post Office & Bank','Take photos of meter readings','Deep clean old residence']},
{id:'school',name:'University / School Supplies',items:['Laptop & Charger','Notebooks / Binder & Loose leaf paper','Pens, Pencils & Highlighters','Backpack / Bag','Student ID card','Scientific / Graphing Calculator','Planner / Calendar app synced','Reusable Water Bottle']},
{id:'gym',name:'Gym Bag',items:['Workout shirt & shorts/leggings','Athletic sneakers & clean socks','Water bottle / shaker cup','Gym towel','Combination padlock for locker','Wireless earbuds','Post-workout snack / Protein bar']},
{id:'grocery',name:'Grocery Essentials',items:['Fresh Fruit & Vegetables','Milk / Oat Milk','Eggs','Bread / Tortillas','Pasta / Rice / Grains','Olive oil & Cooking spices','Coffee / Tea','Dish soap & Paper towels']},
{id:'daytrip',name:'Day Trip',items:['Small backpack','Water bottle (filled)','Snacks & Lunch','Portable phone charger','Sunscreen & Hat','Small hand sanitizer','Rain poncho / Compact umbrella']},];
function createDefault():ChecklistStore{const now=Date.now();return{version:1,activeListId:'default-travel',lists:[{id:'default-travel',title:'Travel & Packing List',updatedAt:now,items:CHECKLIST_TEMPLATES[0].items.map((text,index)=>({id:`item-${index+1}`,text,completed:index<3}))}]};}
export const defaultChecklistStore=createDefault();
const cloneDefault=()=>({version:1,activeListId:defaultChecklistStore.activeListId,lists:defaultChecklistStore.lists.map(l=>({...l,items:l.items.map(i=>({...i}))}))});
const MAX_LISTS=200,MAX_ITEMS=5000,MAX_TEXT=10_000;
function uniqueId(preferred:string,used:Set<string>,fallback:string){let id=preferred.trim()||fallback;if(!used.has(id)){used.add(id);return id;}let n=2;while(used.has(`${id}-${n}`))n++;id=`${id}-${n}`;used.add(id);return id;}
export function sanitizeChecklistStore(raw:unknown):ChecklistStore{if(!raw||typeof raw!=='object')return cloneDefault();try{const c=raw as Partial<ChecklistStore>;if(!Array.isArray(c.lists)||!c.lists.length)return cloneDefault();const usedLists=new Set<string>(),lists:ChecklistDoc[]=[];for(const value of c.lists.slice(0,MAX_LISTS)){if(!value||typeof value!=='object')continue;const source=value as Partial<ChecklistDoc>,id=uniqueId(typeof source.id==='string'?source.id:'',usedLists,`list-${lists.length+1}`),usedItems=new Set<string>(),items:ChecklistItem[]=[];for(const rawItem of(Array.isArray(source.items)?source.items:[]).slice(0,MAX_ITEMS)){if(!rawItem||typeof rawItem!=='object')continue;const item=rawItem as Partial<ChecklistItem>,priority=item.priority==='low'||item.priority==='medium'||item.priority==='high'?item.priority:undefined;items.push({id:uniqueId(typeof item.id==='string'?item.id:'',usedItems,`item-${items.length+1}`),text:typeof item.text==='string'?item.text.slice(0,MAX_TEXT):'',completed:Boolean(item.completed),priority,note:typeof item.note==='string'?item.note.slice(0,MAX_TEXT):undefined});}lists.push({id,title:typeof source.title==='string'&&source.title.trim()?source.title.trim().slice(0,500):'Untitled List',updatedAt:typeof source.updatedAt==='number'&&Number.isFinite(source.updatedAt)?source.updatedAt:Date.now(),items});}if(!lists.length)return cloneDefault();const requested=typeof c.activeListId==='string'?c.activeListId:'';return{version:1,activeListId:lists.find(l=>l.id===requested)?.id||lists[0].id,lists};}catch{return cloneDefault();}}
export function getStoredChecklists():ChecklistStore{if(typeof window==='undefined'||!window.localStorage)return cloneDefault();try{const raw=window.localStorage.getItem(CHECKLIST_STORAGE_KEY);return raw?sanitizeChecklistStore(JSON.parse(raw)):cloneDefault();}catch{return cloneDefault();}}
export function saveChecklists(store:ChecklistStore):void{if(typeof window==='undefined'||!window.localStorage)return;try{window.localStorage.setItem(CHECKLIST_STORAGE_KEY,JSON.stringify(sanitizeChecklistStore(store)));}catch{}}
export function calculateChecklistStats(items:ChecklistItem[]){const total=items.length;if(!total)return{total:0,completed:0,remaining:0,percent:0};const completed=items.reduce((n,i)=>n+(i.completed?1:0),0);return{total,completed,remaining:total-completed,percent:Math.round(completed/total*100)};}
export function formatChecklistToText(list:ChecklistDoc):string{return[`# ${list.title}`,'',...list.items.map(item=>`${item.completed?'[x]':'[ ]'}${item.priority?` [${item.priority.toUpperCase()}]`:''} ${item.text}${item.note?` — ${item.note}`:''}`)].join('\n');}
export function parseChecklistText(text:string,title='Imported Checklist'):ChecklistDoc{const items:ChecklistItem[]=[];for(const raw of text.split(/\r?\n/)){const line=raw.trim();if(!line||/^#\s+/.test(line))continue;const match=line.match(/^(?:[-*•]\s*)?\[([xX ])\]\s*(?:\[(HIGH|MEDIUM|LOW)\]\s*)?(.*)$/);const plain=match?match[3].trim():line.replace(/^[-*•]\s*/, '').trim();if(!plain)continue;items.push({id:`import-${items.length+1}`,text:plain,completed:Boolean(match&&match[1].toLowerCase()==='x'),priority:match?.[2]?.toLowerCase() as ChecklistPriority|undefined});}return{id:`list-${Date.now()}`,title,updatedAt:Date.now(),items};}
export function serializeChecklistBackup(store:ChecklistStore):string{return JSON.stringify(sanitizeChecklistStore(store),null,2);}
export function parseChecklistBackup(raw:string):ChecklistStore|null{try{const parsed=JSON.parse(raw);if(!parsed||typeof parsed!=='object'||!Array.isArray((parsed as ChecklistStore).lists))return null;return sanitizeChecklistStore(parsed);}catch{return null;}}
export function mergeChecklistItems(existing:ChecklistItem[],incoming:ChecklistItem[],deduplicate=true):ChecklistItem[]{const output=existing.map(i=>({...i})),seen=new Set(existing.map(i=>i.text.trim().toLocaleLowerCase()));for(const item of incoming){const key=item.text.trim().toLocaleLowerCase();if(!key||(deduplicate&&seen.has(key)))continue;seen.add(key);output.push({...item,id:`item-${Date.now()}-${output.length}`});}return output;}
export function reorderChecklistItems(items:ChecklistItem[],fromIndex:number,toIndex:number):ChecklistItem[]{if(fromIndex<0||fromIndex>=items.length||toIndex<0||toIndex>=items.length)return items.map(i=>({...i}));const out=[...items],moved=out.splice(fromIndex,1)[0];out.splice(toIndex,0,moved);return out;}
export function filterChecklistItems(items:ChecklistItem[],query:string):ChecklistItem[]{const needle=query.trim().toLocaleLowerCase();return needle?items.filter(item=>`${item.text}\n${item.note||''}`.toLocaleLowerCase().includes(needle)):items;}
