function finiteNonNegative(v:number){return Number.isFinite(v)?Math.max(0,v):0;}function finitePercent(v:number,max=Infinity){return Number.isFinite(v)?Math.max(0,Math.min(max,v)):0;}
export function roundFinancial(value:number,decimals=10):number{if(!Number.isFinite(value))return 0;return Number(value.toFixed(Math.max(0,Math.min(12,Math.floor(decimals)))));}
export function roundCurrency(value:number,minorUnitDigits=2):number{return roundFinancial(value,Math.max(0,Math.min(6,Math.trunc(minorUnitDigits))));}
export interface DiscountResult{originalPrice:number;primaryDiscountAmount:number;secondaryDiscountAmount:number;totalSaved:number;finalPrice:number;effectiveDiscountPercent:number;}
export function calculateDiscount(originalPrice:number,primaryPercent:number,secondaryPercent=0,fixedDiscountAmount=0):DiscountResult{const price=finiteNonNegative(originalPrice),fixed=Math.min(price,finiteNonNegative(fixedDiscountAmount)),afterFixed=price-fixed,primary=afterFixed*finitePercent(primaryPercent,100)/100,afterPrimary=afterFixed-primary,secondary=afterPrimary*finitePercent(secondaryPercent,100)/100,final=Math.max(0,afterPrimary-secondary),saved=price-final;return{originalPrice:roundFinancial(price),primaryDiscountAmount:roundFinancial(primary+fixed),secondaryDiscountAmount:roundFinancial(secondary),totalSaved:roundFinancial(saved),finalPrice:roundFinancial(final),effectiveDiscountPercent:price?roundFinancial(saved/price*100):0};}
export function calculateOriginalPriceFromDiscount(finalPrice:number,primaryPercent:number,secondaryPercent=0,fixedDiscountAmount=0):{originalPrice:number|null;error?:string}{const factor=(1-finitePercent(primaryPercent,100)/100)*(1-finitePercent(secondaryPercent,100)/100);if(factor<=0)return{originalPrice:null,error:'A 100% discount cannot be reversed.'};return{originalPrice:roundFinancial(finiteNonNegative(finalPrice)/factor+finiteNonNegative(fixedDiscountAmount))};}
export interface VatResult{netAmount:number;taxAmount:number;grossAmount:number;taxRate:number;}
export function calculateVatAdd(netAmount:number,taxRate:number):VatResult{const net=finiteNonNegative(netAmount),rate=finitePercent(taxRate),tax=net*rate/100;return{netAmount:roundFinancial(net),taxAmount:roundFinancial(tax),grossAmount:roundFinancial(net+tax),taxRate:roundFinancial(rate)};}
export function calculateVatExtract(grossAmount:number,taxRate:number):VatResult{const gross=finiteNonNegative(grossAmount),rate=finitePercent(taxRate),net=gross/(1+rate/100);return{netAmount:roundFinancial(net),taxAmount:roundFinancial(gross-net),grossAmount:roundFinancial(gross),taxRate:roundFinancial(rate)};}
export interface MarginMarkupResult{cost:number;revenue:number;profit:number;marginPercent:number;markupPercent:number;}
export function calculateFromCostAndRevenue(cost:number,revenue:number):MarginMarkupResult{const c=finiteNonNegative(cost),r=finiteNonNegative(revenue),p=r-c;return{cost:roundFinancial(c),revenue:roundFinancial(r),profit:roundFinancial(p),marginPercent:r?roundFinancial(p/r*100):0,markupPercent:c?roundFinancial(p/c*100):0};}
export function calculateFromCostAndMargin(cost:number,marginPercent:number):MarginMarkupResult{const c=finiteNonNegative(cost),m=finitePercent(marginPercent,99.999999),r=c/(1-m/100);return calculateFromCostAndRevenue(c,r);}
export function calculateFromCostAndMarkup(cost:number,markupPercent:number):MarginMarkupResult{const c=finiteNonNegative(cost),m=finitePercent(markupPercent);return calculateFromCostAndRevenue(c,c*(1+m/100));}
export type PricingAdjustment={type:'fixed-discount'|'percent-discount'|'fixed-fee'|'percent-fee'|'tax';value:number;label?:string};
export interface PricingStep{label:string;before:number;change:number;after:number;type:PricingAdjustment['type'];}
export function calculatePricingScenario(basePrice:number,adjustments:PricingAdjustment[],minorUnitDigits=2):{basePrice:number;finalPrice:number;steps:PricingStep[];effectiveChangePercent:number}{let current=finiteNonNegative(basePrice);const base=current,steps:PricingStep[]=[];for(const adjustment of adjustments){const before=current,value=finiteNonNegative(adjustment.value);let change=0;if(adjustment.type==='fixed-discount')change=-Math.min(current,value);else if(adjustment.type==='percent-discount')change=-current*finitePercent(value,100)/100;else if(adjustment.type==='fixed-fee')change=value;else change=current*value/100;current=Math.max(0,current+change);steps.push({label:adjustment.label||adjustment.type,before:roundCurrency(before,minorUnitDigits),change:roundCurrency(change,minorUnitDigits),after:roundCurrency(current,minorUnitDigits),type:adjustment.type});}const final=roundCurrency(current,minorUnitDigits);return{basePrice:roundCurrency(base,minorUnitDigits),finalPrice:final,steps,effectiveChangePercent:base?roundFinancial((final-base)/base*100):0};}
export function allocateProportionalDiscount(amounts:number[],discount:number,minorUnitDigits=2):number[]{const safe=amounts.map(finiteNonNegative),total=safe.reduce((a,b)=>a+b,0),target=Math.min(total,finiteNonNegative(discount));if(!total||!target)return safe.map(()=>0);const factor=10**minorUnitDigits,targetUnits=Math.round(target*factor),raw=safe.map(v=>v/total*targetUnits),floors=raw.map(Math.floor);let remainder=targetUnits-floors.reduce((a,b)=>a+b,0);const order=raw.map((v,i)=>({i,f:v-floors[i]})).sort((a,b)=>b.f-a.f||a.i-b.i);for(let k=0;k<remainder;k++)floors[order[k%order.length].i]++;return floors.map(v=>v/factor);}
export interface VatLine{net:number;rate:number;quantity?:number;}
export function calculateMixedVatCart(lines:VatLine[],minorUnitDigits=2):{net:number;tax:number;gross:number;byRate:Record<string,{net:number;tax:number;gross:number}>}{const byRate:Record<string,{net:number;tax:number;gross:number}>={};let net=0,tax=0;for(const line of lines){const n=finiteNonNegative(line.net)*Math.max(0,line.quantity??1),r=finitePercent(line.rate),t=n*r/100,key=String(r);net+=n;tax+=t;const bucket=byRate[key]||{net:0,tax:0,gross:0};bucket.net+=n;bucket.tax+=t;bucket.gross+=n+t;byRate[key]=bucket;}for(const value of Object.values(byRate)){value.net=roundCurrency(value.net,minorUnitDigits);value.tax=roundCurrency(value.tax,minorUnitDigits);value.gross=roundCurrency(value.gross,minorUnitDigits);}return{net:roundCurrency(net,minorUnitDigits),tax:roundCurrency(tax,minorUnitDigits),gross:roundCurrency(net+tax,minorUnitDigits),byRate};}
export function calculateBreakEven(fixedCosts:number,pricePerUnit:number,variableCostPerUnit:number):{units:number|null;contributionMargin:number;error?:string}{const contribution=finiteNonNegative(pricePerUnit)-finiteNonNegative(variableCostPerUnit);if(contribution<=0)return{units:null,contributionMargin:roundFinancial(contribution),error:'Price per unit must exceed variable cost per unit.'};return{units:Math.ceil(finiteNonNegative(fixedCosts)/contribution),contributionMargin:roundFinancial(contribution)};}
