export interface LineItem{description:string;quantity:number;unitPrice:number}
export interface ParseResult<T>{items:T[];errors:string[]}
const DAY_MS=86400000;
export function roundMoney(value:number){return Math.round((value+Number.EPSILON)*100)/100}
export function parseLineItems(text:string):ParseResult<LineItem>{const items:LineItem[]=[],errors:string[]=[];for(const [index,raw]of text.split(/\r?\n/).entries()){const line=raw.trim();if(!line)continue;const parts=(line.includes('|')?line.split('|'):line.split('\t')).map(v=>v.trim());if(parts.length<3){errors.push(`Line ${index+1}: use Description | Quantity | Unit price.`);continue}const description=parts[0],quantity=Number(parts[1]),unitPrice=Number(parts[2].replace(',','.'));if(!description||!Number.isFinite(quantity)||quantity<=0||!Number.isFinite(unitPrice)||unitPrice<0){errors.push(`Line ${index+1}: quantity must be positive and unit price must be zero or more.`);continue}items.push({description,quantity,unitPrice})}return{items,errors}}
export function calculateDocumentTotals(items:LineItem[],taxRate=0,discountRate=0){const subtotal=roundMoney(items.reduce((sum,item)=>sum+item.quantity*item.unitPrice,0)),discount=roundMoney(subtotal*Math.max(0,discountRate)/100),taxable=roundMoney(Math.max(0,subtotal-discount)),tax=roundMoney(taxable*Math.max(0,taxRate)/100),total=roundMoney(taxable+tax);return{subtotal,discount,taxable,tax,total}}
export function formatMoney(value:number,currency='EUR'){try{return new Intl.NumberFormat(undefined,{style:'currency',currency:currency.trim().toUpperCase()||'EUR'}).format(value)}catch{return`${roundMoney(value).toFixed(2)} ${currency.trim().toUpperCase()||'EUR'}`}}
export function escapeHtml(value:string){return value.replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]!))}
export function safeHttpUrl(value:string){const raw=value.trim();if(!raw)return'';try{const url=new URL(/^[a-z][a-z0-9+.-]*:/i.test(raw)?raw:`https://${raw}`);return url.protocol==='http:'||url.protocol==='https:'?url.href:''}catch{return''}}
export function printableHtml(title:string,body:string){return`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>html{font-family:Arial,sans-serif;color:#171717}body{max-width:900px;margin:32px auto;padding:0 24px;line-height:1.45}h1,h2,h3{margin:.2em 0 .5em}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left;vertical-align:top}.right{text-align:right}.muted{color:#666}.grid{display:grid;gap:12px}.card{border:1px solid #bbb;border-radius:6px;padding:12px;break-inside:avoid}.labels{display:grid;grid-template-columns:repeat(var(--cols),1fr);gap:8px}.label{border:1px dashed #aaa;min-height:70px;padding:10px;white-space:pre-wrap;break-inside:avoid}.calendar{table-layout:fixed}.calendar td{height:88px;border:1px solid #ccc}.day{font-weight:700}.schedule td,.schedule th{border:1px solid #ccc}.resume-section{margin-top:22px}.resume-section h2{font-size:15px;text-transform:uppercase;letter-spacing:.08em;border-bottom:1px solid #999;padding-bottom:4px;white-space:pre-wrap}@page{margin:14mm}@media print{body{margin:0;max-width:none}.no-print{display:none}}</style></head><body>${body}</body></html>`}
function dateParts(value:string){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);if(!m)throw new Error('Use a valid YYYY-MM-DD date.');const y=Number(m[1]),mo=Number(m[2]),d=Number(m[3]),date=new Date(Date.UTC(y,mo-1,d));if(date.getUTCFullYear()!==y||date.getUTCMonth()!==mo-1||date.getUTCDate()!==d)throw new Error('Date is not valid.');return{y,mo,d,date}}
export interface CalendarCell{day:number|null;iso:string|null}
export function buildMonthCalendar(year:number,month:number,weekStartsOn:0|1=1){if(!Number.isInteger(year)||year<1||year>9999||!Number.isInteger(month)||month<1||month>12)throw new Error('Choose a valid month and year.');const days=new Date(Date.UTC(year,month,0)).getUTCDate(),firstDow=new Date(Date.UTC(year,month-1,1)).getUTCDay(),offset=(firstDow-weekStartsOn+7)%7,cells:CalendarCell[]=[];for(let i=0;i<offset;i++)cells.push({day:null,iso:null});for(let d=1;d<=days;d++)cells.push({day:d,iso:`${String(year).padStart(4,'0')}-${String(month).padStart(2,'0')}-${String(d).padStart(2,'0')}`});while(cells.length%7)cells.push({day:null,iso:null});const weeks:CalendarCell[][]=[];for(let i=0;i<cells.length;i+=7)weeks.push(cells.slice(i,i+7));return weeks}
export function monthLabel(year:number,month:number){return new Intl.DateTimeFormat(undefined,{month:'long',year:'numeric',timeZone:'UTC'}).format(new Date(Date.UTC(year,month-1,1)))}
const WEEKDAYS=['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'];
export interface ScheduleEntry{weekday:number;day:string;start:string;end:string;title:string}
function validTime(value:string){const m=/^(\d{1,2}):(\d{2})$/.exec(value);return Boolean(m&&Number(m[1])<=23&&Number(m[2])<=59)}
export function parseScheduleEntries(text:string):ParseResult<ScheduleEntry>{const items:ScheduleEntry[]=[],errors:string[]=[];for(const[index,raw]of text.split(/\r?\n/).entries()){if(!raw.trim())continue;const parts=raw.split('|').map(v=>v.trim());if(parts.length<4){errors.push(`Line ${index+1}: use Day | Start | End | Title.`);continue}const weekday=WEEKDAYS.findIndex(d=>d.toLowerCase().startsWith(parts[0].toLowerCase().slice(0,3)));if(weekday<0||!validTime(parts[1])||!validTime(parts[2])||!parts[3]){errors.push(`Line ${index+1}: invalid weekday, time, or title.`);continue}items.push({weekday,day:WEEKDAYS[weekday],start:parts[1].padStart(5,'0'),end:parts[2].padStart(5,'0'),title:parts.slice(3).join(' | ')})}items.sort((a,b)=>a.weekday-b.weekday||a.start.localeCompare(b.start));return{items,errors}}
export function splitDuration(ms:number){const sign=ms<0?-1:1,totalSeconds=Math.floor(Math.abs(ms)/1000),days=Math.floor(totalSeconds/86400),hours=Math.floor(totalSeconds%86400/3600),minutes=Math.floor(totalSeconds%3600/60),seconds=totalSeconds%60;return{sign,days,hours,minutes,seconds,totalSeconds}}
export function countdownParts(target:string|Date,now:string|Date=new Date()){const targetMs=new Date(target).getTime(),nowMs=new Date(now).getTime();if(!Number.isFinite(targetMs)||!Number.isFinite(nowMs))throw new Error('Choose a valid date and time.');return{...splitDuration(targetMs-nowMs),targetMs,nowMs}}
function minutesFromTime(value:string){if(!validTime(value))throw new Error('Invalid time.');const[h,m]=value.split(':').map(Number);return h*60+m}
export interface TimesheetEntry{date:string;start:string;end:string;breakMinutes:number;workedMinutes:number}
export function parseTimesheet(text:string):ParseResult<TimesheetEntry>&{totalMinutes:number}{const items:TimesheetEntry[]=[],errors:string[]=[];let totalMinutes=0;for(const[index,raw]of text.split(/\r?\n/).entries()){if(!raw.trim())continue;const p=raw.split('|').map(v=>v.trim());if(p.length<3){errors.push(`Line ${index+1}: use Date | Start | End | Break minutes.`);continue}try{dateParts(p[0]);let start=minutesFromTime(p[1]),end=minutesFromTime(p[2]);if(end<start)end+=1440;const breakMinutes=p[3]?Number(p[3]):0,duration=end-start;if(!Number.isFinite(breakMinutes)||breakMinutes<0||breakMinutes>duration)throw new Error();const workedMinutes=duration-breakMinutes;items.push({date:p[0],start:p[1],end:p[2],breakMinutes,workedMinutes});totalMinutes+=workedMinutes}catch{errors.push(`Line ${index+1}: invalid date, time, or break.`)}}return{items,errors,totalMinutes}}
export function isoWeekInfo(value:string){const{date}=dateParts(value),weekday=date.getUTCDay(),isoWeekday=weekday===0?7:weekday,thursday=new Date(date);thursday.setUTCDate(date.getUTCDate()+4-isoWeekday);const isoYear=thursday.getUTCFullYear(),yearStart=new Date(Date.UTC(isoYear,0,1)),week=Math.ceil((((thursday.getTime()-yearStart.getTime())/DAY_MS)+1)/7),dayOfYear=Math.floor((date.getTime()-Date.UTC(date.getUTCFullYear(),0,1))/DAY_MS)+1;return{isoYear,week,weekday:WEEKDAYS[weekday],isoWeekday,dayOfYear}}
export function durationBetween(start:string,end:string){const a=new Date(start).getTime(),b=new Date(end).getTime();if(!Number.isFinite(a)||!Number.isFinite(b))throw new Error('Choose valid start and end date-times.');return{...splitDuration(b-a),milliseconds:b-a}}
function daysInMonth(y:number,m:number){return new Date(Date.UTC(y,m,0)).getUTCDate()}
function addMonthsClamped(date:Date,months:number){const baseMonth=date.getUTCMonth()+months,y=date.getUTCFullYear()+Math.floor(baseMonth/12),m=((baseMonth%12)+12)%12,d=Math.min(date.getUTCDate(),daysInMonth(y,m+1));return new Date(Date.UTC(y,m,d))}
function addYearsClamped(date:Date,years:number){const y=date.getUTCFullYear()+years,m=date.getUTCMonth(),d=Math.min(date.getUTCDate(),daysInMonth(y,m+1));return new Date(Date.UTC(y,m,d))}
export function calendarAge(birth:string,asOf:string){const start=dateParts(birth).date,end=dateParts(asOf).date;if(end<start)throw new Error('As-of date must not be before the birth date.');let years=end.getUTCFullYear()-start.getUTCFullYear(),cursor=addYearsClamped(start,years);if(cursor>end){years--;cursor=addYearsClamped(start,years)}let months=0;while(months<11){const next=addMonthsClamped(cursor,1);if(next>end)break;cursor=next;months++}const days=Math.floor((end.getTime()-cursor.getTime())/DAY_MS),totalDays=Math.floor((end.getTime()-start.getTime())/DAY_MS);return{years,months,days,totalDays}}
export function minutesLabel(minutes:number){const sign=minutes<0?'-':'',abs=Math.abs(Math.round(minutes)),h=Math.floor(abs/60),m=abs%60;return`${sign}${h}h ${String(m).padStart(2,'0')}m`}
