export type CollageLayoutType='auto'|'2-horizontal'|'2-vertical'|'before-after'|'2x2'|'3x3'|'h-strip'|'v-strip'|'custom';
export type AspectRatioPreset='auto'|'1:1'|'4:3'|'3:2'|'16:9'|'9:16'|'custom';
export type FitMode='cover'|'contain';
export type ImageRotation=0|90|180|270;
export interface CollageItem{id:string;blob:Blob;dataUrl:string;imgElement?:HTMLImageElement;filename:string;naturalWidth:number;naturalHeight:number;fitMode:FitMode;offsetX:number;offsetY:number;zoom:number;rotation?:ImageRotation;caption?:string;}
export interface CollageConfig{layout:CollageLayoutType;customRows:number;customCols:number;aspectPreset:AspectRatioPreset;targetWidth:number;targetHeight:number;gap:number;padding:number;borderRadius:number;backgroundColor:string;format:'image/png'|'image/jpeg'|'image/webp';quality:number;}
export interface GridDimensions{rows:number;cols:number;totalCells:number;}
export interface CellRect{x:number;y:number;width:number;height:number;row:number;col:number;}
export function calculateGridDimensions(layout:CollageLayoutType,itemCount:number,customRows=2,customCols=2):GridDimensions{const count=Math.max(1,itemCount);switch(layout){case'2-horizontal':case'before-after':return{rows:1,cols:2,totalCells:2};case'2-vertical':return{rows:2,cols:1,totalCells:2};case'2x2':return{rows:2,cols:2,totalCells:4};case'3x3':return{rows:3,cols:3,totalCells:9};case'h-strip':return{rows:1,cols:count,totalCells:count};case'v-strip':return{rows:count,cols:1,totalCells:count};case'custom':{const rows=Math.max(1,Math.floor(customRows)),cols=Math.max(1,Math.floor(customCols));return{rows,cols,totalCells:rows*cols};}default:{if(count<=1)return{rows:1,cols:1,totalCells:1};if(count===2)return{rows:1,cols:2,totalCells:2};if(count===3)return{rows:1,cols:3,totalCells:3};if(count===4)return{rows:2,cols:2,totalCells:4};if(count<=6)return{rows:2,cols:3,totalCells:6};if(count<=8)return{rows:2,cols:4,totalCells:8};if(count<=9)return{rows:3,cols:3,totalCells:9};if(count<=12)return{rows:3,cols:4,totalCells:12};if(count<=16)return{rows:4,cols:4,totalCells:16};const cols=Math.ceil(Math.sqrt(count)),rows=Math.ceil(count/cols);return{rows,cols,totalCells:rows*cols};}}}
export function calculateCanvasSize(preset:AspectRatioPreset,baseWidth:number,baseHeight:number,grid:GridDimensions):{width:number;height:number}{const width=Math.min(Math.max(400,Number.isFinite(baseWidth)?baseWidth:1200),8192);let height:number;switch(preset){case'1:1':height=width;break;case'4:3':height=Math.round(width*3/4);break;case'3:2':height=Math.round(width*2/3);break;case'16:9':height=Math.round(width*9/16);break;case'9:16':height=Math.round(width*16/9);break;case'custom':height=Math.min(Math.max(300,Number.isFinite(baseHeight)?baseHeight:800),8192);break;default:height=Math.min(Math.max(300,Math.round(width*grid.rows/Math.max(1,grid.cols))),8192);}const maxPixels=32_000_000,scale=Math.min(1,Math.sqrt(maxPixels/(width*height)));return{width:Math.max(1,Math.round(width*scale)),height:Math.max(1,Math.round(height*scale))};}
export function calculateCellRects(grid:GridDimensions,itemCount:number,canvasWidth:number,canvasHeight:number,gap=0,padding=0):CellRect[]{const count=Math.max(0,Math.min(itemCount,grid.totalCells)),safeGap=Math.max(0,gap),pad=Math.max(0,padding),availableW=Math.max(1,canvasWidth-pad*2-safeGap*(grid.cols-1)),availableH=Math.max(1,canvasHeight-pad*2-safeGap*(grid.rows-1)),cellW=availableW/grid.cols,cellH=availableH/grid.rows,rects:CellRect[]=[];for(let row=0;row<grid.rows;row++){const rowStart=row*grid.cols,itemsInRow=Math.max(0,Math.min(grid.cols,count-rowStart));if(!itemsInRow)break;const usedW=itemsInRow*cellW+Math.max(0,itemsInRow-1)*safeGap,startX=pad+(availableW+safeGap*(grid.cols-1)-usedW)/2;for(let col=0;col<itemsInRow;col++)rects.push({x:startX+col*(cellW+safeGap),y:pad+row*(cellH+safeGap),width:cellW,height:cellH,row,col});}return rects;}
export interface ImagePlacement{sx:number;sy:number;sw:number;sh:number;dx:number;dy:number;dw:number;dh:number;}
const clamp01=(v:number)=>Math.max(0,Math.min(1,Number.isFinite(v)?v:.5));
export function calculateImagePlacement(imageW:number,imageH:number,cellX:number,cellY:number,cellW:number,cellH:number,fitMode:FitMode,offsetX=.5,offsetY=.5,zoom=1):ImagePlacement|null{if([imageW,imageH,cellW,cellH].some(v=>!Number.isFinite(v)||v<=0))return null;const z=Math.max(1,Math.min(4,Number.isFinite(zoom)?zoom:1));if(fitMode==='contain'){const scale=Math.min(cellW/imageW,cellH/imageH)*z,dw=imageW*scale,dh=imageH*scale;return{sx:0,sy:0,sw:imageW,sh:imageH,dx:cellX+(cellW-dw)*clamp01(offsetX),dy:cellY+(cellH-dh)*clamp01(offsetY),dw,dh};}const scale=Math.max(cellW/imageW,cellH/imageH)*z,sw=Math.min(imageW,cellW/scale),sh=Math.min(imageH,cellH/scale),maxX=Math.max(0,imageW-sw),maxY=Math.max(0,imageH-sh);return{sx:maxX*clamp01(offsetX),sy:maxY*clamp01(offsetY),sw,sh,dx:cellX,dy:cellY,dw:cellW,dh:cellH};}
function drawRotatedPlacement(ctx:CanvasRenderingContext2D,img:HTMLImageElement,placement:ImagePlacement,rotation:ImageRotation,fitMode:FitMode,offsetX:number,offsetY:number,zoom:number){if(rotation===0){ctx.drawImage(img,placement.sx,placement.sy,placement.sw,placement.sh,placement.dx,placement.dy,placement.dw,placement.dh);return;}const temp=document.createElement('canvas'),rotated=rotation===90||rotation===270;temp.width=rotated?img.naturalHeight:img.naturalWidth;temp.height=rotated?img.naturalWidth:img.naturalHeight;const t=temp.getContext('2d');if(!t)return;t.translate(temp.width/2,temp.height/2);t.rotate(rotation*Math.PI/180);t.drawImage(img,-img.naturalWidth/2,-img.naturalHeight/2);const p=calculateImagePlacement(temp.width,temp.height,placement.dx,placement.dy,placement.dw,placement.dh,fitMode,offsetX,offsetY,zoom);if(p)ctx.drawImage(temp,p.sx,p.sy,p.sw,p.sh,p.dx,p.dy,p.dw,p.dh);}
export function renderCollageToCanvas(canvas:HTMLCanvasElement,items:CollageItem[],config:CollageConfig):void{const grid=calculateGridDimensions(config.layout,items.length,config.customRows,config.customCols),size=calculateCanvasSize(config.aspectPreset,config.targetWidth,config.targetHeight,grid);canvas.width=size.width;canvas.height=size.height;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.fillStyle=config.backgroundColor;ctx.fillRect(0,0,size.width,size.height);const rects=calculateCellRects(grid,items.length,size.width,size.height,config.gap,config.padding);for(let index=0;index<rects.length;index++){const item=items[index],img=item.imgElement,rect=rects[index];if(!img||!img.complete||img.naturalWidth<=0||img.naturalHeight<=0)continue;ctx.save();ctx.beginPath();const radius=Math.max(0,Math.min(config.borderRadius,rect.width/2,rect.height/2));if(radius>0)ctx.roundRect(rect.x,rect.y,rect.width,rect.height,radius);else ctx.rect(rect.x,rect.y,rect.width,rect.height);ctx.clip();const rotation=item.rotation??0,rotated=rotation===90||rotation===270,imageW=rotated?img.naturalHeight:img.naturalWidth,imageH=rotated?img.naturalWidth:img.naturalHeight,placement=calculateImagePlacement(imageW,imageH,rect.x,rect.y,rect.width,rect.height,item.fitMode,item.offsetX,item.offsetY,item.zoom);if(placement)drawRotatedPlacement(ctx,img,placement,rotation,item.fitMode,item.offsetX,item.offsetY,item.zoom);if(config.layout==='before-after'&&(index===0||index===1)){const label=index===0?'BEFORE':'AFTER';ctx.font='bold 13px sans-serif';const badgeW=ctx.measureText(label).width+20,bx=rect.x+12,by=rect.y+12;ctx.fillStyle='rgba(15,23,42,.78)';ctx.beginPath();ctx.roundRect(bx,by,badgeW,24,4);ctx.fill();ctx.fillStyle='#fff';ctx.fillText(label,bx+10,by+16);}if(item.caption?.trim()){const text=item.caption.trim();ctx.font=`600 ${Math.max(12,Math.min(28,rect.width/20))}px sans-serif`;ctx.textAlign='center';ctx.textBaseline='bottom';const y=rect.y+rect.height-10;ctx.lineWidth=4;ctx.strokeStyle='rgba(0,0,0,.7)';ctx.strokeText(text,rect.x+rect.width/2,y,rect.width-20);ctx.fillStyle='#fff';ctx.fillText(text,rect.x+rect.width/2,y,rect.width-20);}ctx.restore();}}
