import JSZip from'jszip';
import{createTar,type TarEntry}from'./file-format-conversion';

export const SHEETJS_ESM_URL='https://cdn.sheetjs.com/xlsx-0.20.3/package/xlsx.mjs';
export const LIBARCHIVE_ESM_URL='https://esm.sh/libarchive-wasm@1.2.0?bundle';
export const LIBARCHIVE_WASM_URL='https://cdn.jsdelivr.net/npm/libarchive-wasm@1.2.0/dist/libarchive.wasm';
export const LAMEJS_URL='https://cdn.jsdelivr.net/npm/lamejs@1.2.1/lame.min.js';
export const HEIC2ANY_URL='https://cdn.jsdelivr.net/npm/heic2any@0.0.4/dist/heic2any.min.js';
export const UTIF_URL='https://cdn.jsdelivr.net/npm/utif@3.1.0/UTIF.js';

type SheetModule={read:(data:ArrayBuffer|Uint8Array,opts?:Record<string,unknown>)=>{SheetNames:string[];Sheets:Record<string,unknown>};utils:{sheet_to_json:(sheet:unknown,opts?:Record<string,unknown>)=>unknown[];json_to_sheet:(rows:unknown[])=>unknown;book_new:()=>unknown;book_append_sheet:(book:unknown,sheet:unknown,name:string)=>void};write:(book:unknown,opts:Record<string,unknown>)=>ArrayBuffer|Uint8Array};
let sheetPromise:Promise<SheetModule>|null=null;
async function sheetJs(){if(!sheetPromise)sheetPromise=import(/* @vite-ignore */ SHEETJS_ESM_URL) as Promise<SheetModule>;return sheetPromise}
export async function xlsToJson(data:ArrayBuffer|Uint8Array){const XLSX=await sheetJs(),book=XLSX.read(data,{type:'array'}),name=book.SheetNames[0];if(!name)throw new Error('The XLS workbook has no worksheets.');return JSON.stringify(XLSX.utils.sheet_to_json(book.Sheets[name],{defval:''}),null,2)}
export async function jsonToXls(json:string){const XLSX=await sheetJs(),value=JSON.parse(json),rows=Array.isArray(value)?value:[value],sheet=XLSX.utils.json_to_sheet(rows),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,sheet,'Sheet1');const bytes=XLSX.write(book,{bookType:'xls',type:'array'});return new Blob([bytes as BlobPart],{type:'application/vnd.ms-excel'})}

type LibarchiveReader={nextEntryPointer:()=>number;getEntryFiletype:(ptr:number)=>string;getEntryPathname:(ptr:number)=>string;getEntrySize:(ptr:number)=>number;isEntryEncrypted:(ptr:number)=>boolean;readData:(size:number)=>Int8Array;skipData:()=>void;free:()=>void};
type LibarchiveModule={ArchiveReader:new(mod:unknown,data:Int8Array,passphrase?:string)=>LibarchiveReader;libarchiveWasm:(options?:Record<string,unknown>)=>Promise<unknown>};
let libarchivePromise:Promise<LibarchiveModule>|null=null;
async function libarchiveModule(){if(!libarchivePromise)libarchivePromise=import(/* @vite-ignore */ LIBARCHIVE_ESM_URL) as Promise<LibarchiveModule>;return libarchivePromise}
function safeArchivePath(path:string){const normalized=path.replace(/\\/g,'/').split('/').filter(part=>part&&part!=='.'&&part!=='..').join('/');return normalized||'file'}
export async function extractRar7z(data:ArrayBuffer|Uint8Array,passphrase?:string):Promise<TarEntry[]>{const api=await libarchiveModule(),mod=await api.libarchiveWasm({locateFile:(name:string)=>name.endsWith('.wasm')?LIBARCHIVE_WASM_URL:name}),bytes=data instanceof Uint8Array?data:new Uint8Array(data),reader=new api.ArchiveReader(mod,new Int8Array(bytes.buffer,bytes.byteOffset,bytes.byteLength),passphrase),entries:TarEntry[]=[];let total=0;try{for(;;){const ptr=reader.nextEntryPointer();if(!ptr)break;const kind=reader.getEntryFiletype(ptr),size=reader.getEntrySize(ptr);if(kind!=='File'){reader.skipData();continue}if(reader.isEntryEncrypted(ptr)&&!passphrase)throw new Error('This archive contains encrypted entries. Entering archive passwords is not supported in this lightweight converter.');if(size<0||size>512*1024*1024)throw new Error('An archive entry is too large for the browser safety limit.');total+=size;if(total>1024*1024*1024)throw new Error('The extracted archive would exceed the 1 GB browser safety limit.');const raw=reader.readData(size),copy=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)copy[i]=raw[i]&255;entries.push({path:safeArchivePath(reader.getEntryPathname(ptr)),bytes:copy})}if(!entries.length)throw new Error('No regular files were found in this archive.');return entries}finally{reader.free()}}
export async function rar7zToZip(data:ArrayBuffer|Uint8Array){const entries=await extractRar7z(data),zip=new JSZip();for(const entry of entries)zip.file(entry.path,entry.bytes);return zip.generateAsync({type:'blob',compression:'DEFLATE'})}
export async function rar7zToTar(data:ArrayBuffer|Uint8Array){return createTar(await extractRar7z(data))}

type LameGlobal={Mp3Encoder:new(channels:number,sampleRate:number,kbps:number)=>{encodeBuffer:(left:Int16Array,right?:Int16Array)=>Int8Array;flush:()=>Int8Array}};
type HeicFn=(options:{blob:Blob;toType:string;quality?:number})=>Promise<Blob|Blob[]>;
type UtifGlobal={decode:(buffer:ArrayBuffer)=>Record<string,unknown>[];decodeImage:(buffer:ArrayBuffer,ifd:Record<string,unknown>)=>void;toRGBA8:(ifd:Record<string,unknown>)=>Uint8Array};
declare global{interface Window{lamejs?:LameGlobal;heic2any?:HeicFn;UTIF?:UtifGlobal}}
const scriptLoads=new Map<string,Promise<void>>();
function loadScript(url:string){const existing=scriptLoads.get(url);if(existing)return existing;const promise=new Promise<void>((resolve,reject)=>{const script=document.createElement('script');script.src=url;script.async=true;script.crossOrigin='anonymous';script.onload=()=>resolve();script.onerror=()=>reject(new Error(`Could not load the optional conversion runtime from ${new URL(url).hostname}.`));document.head.appendChild(script)});scriptLoads.set(url,promise);return promise}
function int16(samples:Float32Array,start:number,end:number){const out=new Int16Array(end-start);for(let i=start,j=0;i<end;i++,j++){const s=Math.max(-1,Math.min(1,samples[i]||0));out[j]=s<0?Math.round(s*32768):Math.round(s*32767)}return out}
export async function audioBufferToMp3Blob(buffer:AudioBuffer,kbps=192){await loadScript(LAMEJS_URL);const lame=window.lamejs;if(!lame)throw new Error('The MP3 encoder runtime did not initialize.');const channels=Math.min(2,Math.max(1,buffer.numberOfChannels)),encoder=new lame.Mp3Encoder(channels,buffer.sampleRate,kbps),left=buffer.getChannelData(0),right=channels>1?buffer.getChannelData(1):undefined,chunks:Uint8Array[]=[];for(let i=0;i<buffer.length;i+=1152){const l=int16(left,i,Math.min(buffer.length,i+1152)),r=right?int16(right,i,Math.min(buffer.length,i+1152)):undefined,encoded=encoder.encodeBuffer(l,r);if(encoded.length){const copy=new Uint8Array(encoded.length);for(let j=0;j<encoded.length;j++)copy[j]=encoded[j]&255;chunks.push(copy)}}const tail=encoder.flush();if(tail.length){const copy=new Uint8Array(tail.length);for(let j=0;j<tail.length;j++)copy[j]=tail[j]&255;chunks.push(copy)}return new Blob(chunks as BlobPart[],{type:'audio/mpeg'})}
export async function heicToPngBlob(file:Blob){await loadScript(HEIC2ANY_URL);if(!window.heic2any)throw new Error('The HEIC decoder runtime did not initialize.');const result=await window.heic2any({blob:file,toType:'image/png',quality:1});return Array.isArray(result)?result[0]:result}
export async function tiffToPngBlob(file:Blob){await loadScript(UTIF_URL);const UTIF=window.UTIF;if(!UTIF)throw new Error('The TIFF decoder runtime did not initialize.');const buffer=await file.arrayBuffer(),ifds=UTIF.decode(buffer),ifd=ifds[0];if(!ifd)throw new Error('No TIFF image page was found.');UTIF.decodeImage(buffer,ifd);const rgba=UTIF.toRGBA8(ifd),width=Number((ifd as Record<string,unknown>).width??(ifd as Record<string,unknown>).t256??0),height=Number((ifd as Record<string,unknown>).height??(ifd as Record<string,unknown>).t257??0);if(!width||!height)throw new Error('The TIFF dimensions could not be read.');const canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas is unavailable.');const pixels=new Uint8ClampedArray(rgba.length);pixels.set(rgba);ctx.putImageData(new ImageData(pixels,width,height),0,0);return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('TIFF conversion failed.')),'image/png'))}
