import type{SubtitleCue}from'./p16-subtitles';
export function encodeBmp(data:ImageData){const{width:w,height:h}=data,row=w*4,size=54+row*h,out=new Uint8Array(size),v=new DataView(out.buffer);out.set([0x42,0x4d]);v.setUint32(2,size,true);v.setUint32(10,54,true);v.setUint32(14,40,true);v.setInt32(18,w,true);v.setInt32(22,h,true);v.setUint16(26,1,true);v.setUint16(28,32,true);v.setUint32(34,row*h,true);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const s=(y*w+x)*4,d=54+((h-1-y)*w+x)*4;out[d]=data.data[s+2];out[d+1]=data.data[s+1];out[d+2]=data.data[s];out[d+3]=data.data[s+3]}return new Blob([out],{type:'image/bmp'})}
export function encodeTiff(data:ImageData){const{width:w,height:h}=data,pixels=w*h*3,ifd=8,entries=10,bitsOffset=ifd+2+entries*12+4,pixelOffset=bitsOffset+6,size=pixelOffset+pixels,out=new Uint8Array(size),v=new DataView(out.buffer);out.set([0x49,0x49,0x2a,0x00]);v.setUint32(4,ifd,true);v.setUint16(ifd,entries,true);let at=ifd+2;const entry=(tag:number,type:number,count:number,value:number)=>{v.setUint16(at,tag,true);v.setUint16(at+2,type,true);v.setUint32(at+4,count,true);if(type===3&&count===1)v.setUint16(at+8,value,true);else v.setUint32(at+8,value,true);at+=12};entry(256,4,1,w);entry(257,4,1,h);entry(258,3,3,bitsOffset);entry(259,3,1,1);entry(262,3,1,2);entry(273,4,1,pixelOffset);entry(277,3,1,3);entry(278,4,1,h);entry(279,4,1,pixels);entry(284,3,1,1);v.setUint32(at,0,true);v.setUint16(bitsOffset,8,true);v.setUint16(bitsOffset+2,8,true);v.setUint16(bitsOffset+4,8,true);for(let i=0,j=pixelOffset;i<data.data.length;i+=4){out[j++]=data.data[i];out[j++]=data.data[i+1];out[j++]=data.data[i+2]}return new Blob([out],{type:'image/tiff'})}
function extended80(v:DataView,offset:number,value:number){if(value<=0){for(let i=0;i<10;i++)v.setUint8(offset+i,0);return}const e=Math.floor(Math.log2(value)),exp=e+16383,m=value/2**e,mant=BigInt(Math.floor(m*2**63));v.setUint16(offset,exp,false);for(let i=0;i<8;i++)v.setUint8(offset+2+i,Number((mant>>BigInt((7-i)*8))&255n))}
export function audioBufferToAiffBlob(buffer:AudioBuffer){const channels=Math.min(2,Math.max(1,buffer.numberOfChannels)),frames=buffer.length,dataBytes=frames*channels*2,out=new ArrayBuffer(54+dataBytes),v=new DataView(out),u=new Uint8Array(out),str=(o:number,s:string)=>{for(let i=0;i<s.length;i++)u[o+i]=s.charCodeAt(i)};str(0,'FORM');v.setUint32(4,46+dataBytes,false);str(8,'AIFF');str(12,'COMM');v.setUint32(16,18,false);v.setUint16(20,channels,false);v.setUint32(22,frames,false);v.setUint16(26,16,false);extended80(v,28,buffer.sampleRate);str(38,'SSND');v.setUint32(42,8+dataBytes,false);v.setUint32(46,0,false);v.setUint32(50,0,false);let p=54;for(let i=0;i<frames;i++)for(let c=0;c<channels;c++){const sample=Math.max(-1,Math.min(1,buffer.getChannelData(Math.min(c,buffer.numberOfChannels-1))[i]||0));v.setInt16(p,sample<0?Math.round(sample*32768):Math.round(sample*32767),false);p+=2}return new Blob([out],{type:'audio/aiff'})}
const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const strip=(s:string)=>s.replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,'').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').trim();
const mk=(i:number,startMs:number,endMs:number,text:string):SubtitleCue=>({index:i,startMs,endMs,text:text.trim()});
function clock(s:string){const p=s.trim().replace(',','.').split(':').map(Number);if(p.length===3)return Math.round((p[0]*3600+p[1]*60+p[2])*1000);if(p.length===2)return Math.round((p[0]*60+p[1])*1000);return Math.round((p[0]||0)*1000)}
function assClock(ms:number){const cs=Math.round(Math.max(0,ms)/10),h=Math.floor(cs/360000),m=Math.floor(cs/6000)%60,s=Math.floor(cs/100)%60,c=cs%100;return`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}.${String(c).padStart(2,'0')}`}
export function parseAssSsa(text:string){const out:SubtitleCue[]=[];for(const line of text.replace(/\r/g,'').split('\n'))if(/^Dialogue:/i.test(line)){const parts=line.replace(/^Dialogue:\s*/i,'').split(',');if(parts.length<10)continue;out.push(mk(out.length+1,clock(parts[1]),clock(parts[2]),parts.slice(9).join(',').replace(/\\N/g,'\n').replace(/\{\\[^}]+\}/g,'')))}if(!out.length)throw new Error('No ASS/SSA Dialogue cues were found.');return out}
export function formatAssSsa(cues:SubtitleCue[],ssa=false){const header=ssa?'[Script Info]\nScriptType: v4.00\n\n[Events]\nFormat: Marked, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n':'[Script Info]\nScriptType: v4.00+\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n';return header+cues.map(c=>`Dialogue: 0,${assClock(c.startMs)},${assClock(c.endMs)},Default,,0,0,0,,${c.text.replace(/\n/g,'\\N')}`).join('\n')+'\n'}
export function parseSbv(text:string){const out:SubtitleCue[]=[];for(const b of text.replace(/\r/g,'').trim().split(/\n{2,}/)){const lines=b.split('\n'),timing=lines.shift()?.split(',');if(timing?.length!==2)continue;out.push(mk(out.length+1,clock(timing[0]),clock(timing[1]),lines.join('\n')))}if(!out.length)throw new Error('No SBV cues were found.');return out}
export function formatSbv(cues:SubtitleCue[]){const f=(ms:number)=>{const s=Math.max(0,ms)/1000,h=Math.floor(s/3600),m=Math.floor(s/60)%60,sec=(s%60).toFixed(3).padStart(6,'0');return`${h}:${String(m).padStart(2,'0')}:${sec}`};return cues.map(c=>`${f(c.startMs)},${f(c.endMs)}\n${c.text}`).join('\n\n')+'\n'}
export function parseTtml(text:string){const out:SubtitleCue[]=[];for(const m of text.matchAll(/<p\b([^>]*)>([\s\S]*?)<\/p>/gi)){const attrs=m[1],begin=attrs.match(/\bbegin=["']([^"']+)/i)?.[1],end=attrs.match(/\bend=["']([^"']+)/i)?.[1],dur=attrs.match(/\bdur=["']([^"']+)/i)?.[1];if(!begin)continue;const start=clock(begin),finish=end?clock(end):dur?start+clock(dur):start+3000;out.push(mk(out.length+1,start,finish,strip(m[2])))}if(!out.length)throw new Error('No timed TTML/DFXP cues were found.');return out}
export function formatTtml(cues:SubtitleCue[]){const f=(ms:number)=>{const s=Math.max(0,ms)/1000,h=Math.floor(s/3600),m=Math.floor(s/60)%60,sec=(s%60).toFixed(3).padStart(6,'0');return`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${sec}`};return`<?xml version="1.0" encoding="UTF-8"?>\n<tt xmlns="http://www.w3.org/ns/ttml"><body><div>\n${cues.map(c=>`  <p begin="${f(c.startMs)}" end="${f(c.endMs)}">${esc(c.text).replace(/\n/g,'<br/>')}</p>`).join('\n')}\n</div></body></tt>\n`}
