import JSZip from'jszip';
const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const dec=(s:string)=>s.replace(/&#x([0-9a-f]+);/gi,(_,x)=>String.fromCodePoint(parseInt(x,16))).replace(/&#(\d+);/g,(_,x)=>String.fromCodePoint(Number(x))).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"');
const strip=(s:string)=>dec(s.replace(/<br\s*\/?\s*>/gi,'\n').replace(/<[^>]+>/g,' ')).replace(/[ \t]+/g,' ').trim();
function parseDelimited(text:string,sep:string){const rows:string[][]=[];let row:string[]=[],field='',quoted=false;for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++}else if(c==='"')quoted=false;else field+=c}else if(c==='"')quoted=true;else if(c===sep){row.push(field);field=''}else if(c==='\n'){row.push(field.replace(/\r$/,''));rows.push(row);row=[];field=''}else field+=c}row.push(field.replace(/\r$/,''));if(row.some(Boolean)||!rows.length)rows.push(row);return rows}
function records(rows:string[][]){if(!rows.length)return[];const headers=rows[0].map((x,i)=>x.trim()||`column${i+1}`);return rows.slice(1).filter(r=>r.some(Boolean)).map(r=>Object.fromEntries(headers.map((h,i)=>[h,r[i]??''])))}
export const tsvTextToJson=(text:string)=>JSON.stringify(records(parseDelimited(text,'\t')),null,2);
export function jsonTextToTsv(json:string){const value=JSON.parse(json),rows=Array.isArray(value)?value:[value],objects=rows.map(v=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{value:v});if(!objects.length)return'';const headers=[...new Set(objects.flatMap(o=>Object.keys(o)))],cell=(v:unknown)=>{const s=v==null?'':typeof v==='object'?JSON.stringify(v):String(v);return/[\t\n"]/g.test(s)?`"${s.replace(/"/g,'""')}"`:s};return[headers.join('\t'),...objects.map(o=>headers.map(h=>cell(o[h])).join('\t'))].join('\n')}
export function htmlTableToJson(html:string){const table=html.match(/<table[\s\S]*?<\/table>/i)?.[0]??html,rows=[...table.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].map(r=>[...r[1].matchAll(/<(?:th|td)[^>]*>([\s\S]*?)<\/(?:th|td)>/gi)].map(c=>strip(c[1])));if(!rows.length)throw new Error('No HTML table rows were found.');return JSON.stringify(records(rows),null,2)}
export function jsonToHtmlTable(json:string){const value=JSON.parse(json),rows=Array.isArray(value)?value:[value],objects=rows.map(v=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{value:v}),headers=[...new Set(objects.flatMap(o=>Object.keys(o)))];return`<table>\n  <thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead>\n  <tbody>\n${objects.map(o=>`    <tr>${headers.map(h=>`<td>${esc(o[h]==null?'':typeof o[h]==='object'?JSON.stringify(o[h]):String(o[h]))}</td>`).join('')}</tr>`).join('\n')}\n  </tbody>\n</table>`}
export async function odsToJson(data:ArrayBuffer|Uint8Array){const zip=await JSZip.loadAsync(data),xml=await zip.file('content.xml')?.async('string');if(!xml)throw new Error('This file does not contain content.xml and does not appear to be a readable ODS spreadsheet.');const rows:string[][]=[];for(const r of xml.matchAll(/<table:table-row[^>]*>([\s\S]*?)<\/table:table-row>/gi)){const row:string[]=[];for(const c of r[1].matchAll(/<table:table-cell([^>]*)>([\s\S]*?)<\/table:table-cell>|<table:table-cell([^>]*)\/>/gi)){const attrs=c[1]??c[3]??'',body=c[2]??'',repeat=Math.max(1,Math.min(1000,Number(attrs.match(/table:number-columns-repeated=["'](\d+)/i)?.[1]??1))),value=attrs.match(/office:(?:string-value|value)=["']([^"']*)/i)?.[1]??strip(body);for(let i=0;i<repeat;i++)row.push(dec(value))}rows.push(row)}return JSON.stringify(records(rows),null,2)}
export async function jsonToOds(json:string){const value=JSON.parse(json),rows=Array.isArray(value)?value:[value],objects=rows.map(v=>v&&typeof v==='object'&&!Array.isArray(v)?v as Record<string,unknown>:{value:v}),headers=[...new Set(objects.flatMap(o=>Object.keys(o)))],cell=(v:unknown)=>`<table:table-cell office:value-type="string"><text:p>${esc(v==null?'':typeof v==='object'?JSON.stringify(v):String(v))}</text:p></table:table-cell>`,xmlRows=[headers,...objects.map(o=>headers.map(h=>o[h]))].map(r=>`<table:table-row>${r.map(cell).join('')}</table:table-row>`).join(''),zip=new JSZip();zip.file('mimetype','application/vnd.oasis.opendocument.spreadsheet',{compression:'STORE'});zip.file('content.xml',`<?xml version="1.0" encoding="UTF-8"?><office:document-content xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0" xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0" xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0" office:version="1.3"><office:body><office:spreadsheet><table:table table:name="Sheet1">${xmlRows}</table:table></office:spreadsheet></office:body></office:document-content>`);zip.folder('META-INF')!.file('manifest.xml','<?xml version="1.0" encoding="UTF-8"?><manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0" manifest:version="1.3"><manifest:file-entry manifest:full-path="/" manifest:media-type="application/vnd.oasis.opendocument.spreadsheet"/><manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/></manifest:manifest>');return zip.generateAsync({type:'uint8array',compression:'DEFLATE'})}
