export interface SubtitleCue{start:number;end:number;text:string;}
export function parseSubtitleTimestamp(raw:string):number{const value=raw.trim().replace(',', '.');const parts=value.split(':').map(Number);if(parts.some(n=>!Number.isFinite(n)))return NaN;if(parts.length===3)return parts[0]*3600+parts[1]*60+parts[2];if(parts.length===2)return parts[0]*60+parts[1];return parts[0]||0;}
export function parseSubtitleCues(text:string):SubtitleCue[]{const normalized=text.replace(/^WEBVTT[^\n]*\n+/i,'').replace(/\r/g,'');const blocks=normalized.split(/\n{2,}/),out:SubtitleCue[]=[];for(const block of blocks){const lines=block.split('\n').map(x=>x.trim()).filter(Boolean);if(!lines.length)continue;const timingIndex=lines.findIndex(line=>line.includes('-->'));if(timingIndex<0)continue;const [a,b]=lines[timingIndex].split('-->').map(x=>x.trim().split(/\s+/)[0]);const start=parseSubtitleTimestamp(a),end=parseSubtitleTimestamp(b);if(!Number.isFinite(start)||!Number.isFinite(end)||end<=start)continue;const cueText=lines.slice(timingIndex+1).join(' ').replace(/<[^>]+>/g,'').trim();if(cueText)out.push({start,end,text:cueText});}return out.sort((x,y)=>x.start-y.start);}
export function subtitleAtTime(cues:SubtitleCue[],time:number):string{return cues.find(c=>time>=c.start&&time<c.end)?.text||'';}
export function planVideoFrameTimes(duration:number,count:number,start=0,end=duration):number[]{const safeDuration=Math.max(0,Number.isFinite(duration)?duration:0),s=Math.max(0,Math.min(safeDuration,start)),e=Math.max(s,Math.min(safeDuration,end)),n=Math.max(1,Math.min(240,Math.floor(count)));if(n===1)return[(s+e)/2];const span=e-s;return Array.from({length:n},(_,i)=>s+span*i/(n-1));}
export function playbackRateForSemitones(semitones:number):number{return 2**(Math.max(-24,Math.min(24,semitones))/12);}
export function joinedAudioDuration(durations:number[]):number{return durations.reduce((sum,v)=>sum+(Number.isFinite(v)&&v>0?v:0),0);}
export function estimateLoopedDuration(duration:number,loops:number,speed=1):number{return Math.max(0,duration)*Math.max(1,Math.min(20,Math.floor(loops)))/Math.max(.1,speed);}
export function dbToGain(db:number):number{return 10**(Math.max(-96,Math.min(24,db))/20);}
export function softNoiseGateSample(sample:number,thresholdDb=-45):number{const threshold=dbToGain(thresholdDb),a=Math.abs(sample);if(a>=threshold)return sample;if(threshold<=0)return sample;const ratio=a/threshold;return sample*ratio*ratio;}
export function downmixChannels(channels:Float32Array[]):Float32Array{if(!channels.length)return new Float32Array();const length=Math.min(...channels.map(c=>c.length)),out=new Float32Array(length);for(let i=0;i<length;i++){let sum=0;for(const channel of channels)sum+=channel[i]||0;out[i]=sum/channels.length;}return out;}
export function reverseSamples(samples:Float32Array):Float32Array{const out=new Float32Array(samples.length);for(let i=0;i<samples.length;i++)out[i]=samples[samples.length-1-i]||0;return out;}
export function sanitizeMediaBaseName(name:string):string{const stem=name.replace(/\.[^/.]+$/,'').replace(/[<>:"/\\|?*\u0000-\u001f]/g,'-').trim().replace(/^\.+|\.+$/g,'');return stem||'media';}
export function mediaExtensionFromMime(mime:string):string{const m=mime.toLowerCase();if(m.includes('mp4'))return'mp4';if(m.includes('ogg'))return'ogg';if(m.includes('wav'))return'wav';if(m.includes('gif'))return'gif';return'webm';}
export function supportedVideoRecorderMimes():string[]{if(typeof MediaRecorder==='undefined')return[];return['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm','video/mp4;codecs=avc1','video/mp4'].filter(type=>MediaRecorder.isTypeSupported(type));}
export function supportedAudioRecorderMimes():string[]{if(typeof MediaRecorder==='undefined')return[];return['audio/webm;codecs=opus','audio/ogg;codecs=opus','audio/webm','audio/mp4'].filter(type=>MediaRecorder.isTypeSupported(type));}
