export type Matrix=number[][];
export function parseMatrix(input:string):Matrix{const rows=input.trim().split(/\r?\n/).filter(Boolean).map(line=>line.trim().split(/[\s,;]+/).filter(Boolean).map(Number));if(!rows.length||rows.some(r=>!r.length||r.some(n=>!Number.isFinite(n))))throw new Error('Enter a numeric matrix with one row per line.');const cols=rows[0].length;if(rows.some(r=>r.length!==cols))throw new Error('Every matrix row must have the same number of columns.');return rows}
export const formatMatrix=(m:Matrix)=>m.map(r=>r.map(n=>Number.isInteger(n)?String(n):Number(n.toPrecision(10)).toString()).join('\t')).join('\n');
const sameShape=(a:Matrix,b:Matrix)=>a.length===b.length&&a[0]?.length===b[0]?.length;
export function matrixAdd(a:Matrix,b:Matrix,sign=1){if(!sameShape(a,b))throw new Error('Matrices must have identical dimensions.');return a.map((r,i)=>r.map((v,j)=>v+sign*b[i][j]))}
export function matrixMultiply(a:Matrix,b:Matrix){if(a[0].length!==b.length)throw new Error('A columns must equal B rows.');return a.map(r=>Array.from({length:b[0].length},(_,j)=>r.reduce((sum,v,k)=>sum+v*b[k][j],0)))}
export const matrixTranspose=(a:Matrix)=>Array.from({length:a[0].length},(_,j)=>a.map(r=>r[j]));
export function matrixDeterminant(a:Matrix){if(a.length!==a[0].length)throw new Error('Determinant requires a square matrix.');const m=a.map(r=>r.slice());let det=1;for(let i=0;i<m.length;i++){let p=i;for(let r=i+1;r<m.length;r++)if(Math.abs(m[r][i])>Math.abs(m[p][i]))p=r;if(Math.abs(m[p][i])<1e-12)return 0;if(p!==i){[m[p],m[i]]=[m[i],m[p]];det*=-1}const pivot=m[i][i];det*=pivot;for(let r=i+1;r<m.length;r++){const f=m[r][i]/pivot;for(let c=i+1;c<m.length;c++)m[r][c]-=f*m[i][c]}}return det}
export function matrixInverse(a:Matrix){if(a.length!==a[0].length)throw new Error('Inverse requires a square matrix.');const n=a.length,m=a.map((r,i)=>[...r,...Array.from({length:n},(_,j)=>i===j?1:0)]);for(let i=0;i<n;i++){let p=i;for(let r=i+1;r<n;r++)if(Math.abs(m[r][i])>Math.abs(m[p][i]))p=r;if(Math.abs(m[p][i])<1e-12)throw new Error('Matrix is singular and has no inverse.');[m[p],m[i]]=[m[i],m[p]];const pivot=m[i][i];for(let c=0;c<2*n;c++)m[i][c]/=pivot;for(let r=0;r<n;r++)if(r!==i){const f=m[r][i];for(let c=0;c<2*n;c++)m[r][c]-=f*m[i][c]}}return m.map(r=>r.slice(n))}
export function factorialBig(n:number){if(!Number.isInteger(n)||n<0||n>100000)throw new Error('n must be an integer from 0 to 100000.');let x=1n;for(let i=2n;i<=BigInt(n);i++)x*=i;return x}
export function nPr(n:number,r:number){if(!Number.isInteger(n)||!Number.isInteger(r)||n<0||r<0||r>n)throw new Error('Require integers with 0 ≤ r ≤ n.');let x=1n;for(let i=0;i<r;i++)x*=BigInt(n-i);return x}
export function nCr(n:number,r:number){if(!Number.isInteger(n)||!Number.isInteger(r)||n<0||r<0||r>n)throw new Error('Require integers with 0 ≤ r ≤ n.');r=Math.min(r,n-r);let x=1n;for(let i=1;i<=r;i++)x=x*BigInt(n-r+i)/BigInt(i);return x}
function erf(x:number){const sign=x<0?-1:1,a=Math.abs(x),t=1/(1+0.3275911*a),y=1-(((((1.061405429*t-1.453152027)*t+1.421413741)*t-0.284496736)*t+0.254829592)*t)*Math.exp(-a*a);return sign*y}
export const normalCdf=(x:number,mean=0,sd=1)=>{if(!(sd>0))throw new Error('Standard deviation must be greater than zero.');return.5*(1+erf((x-mean)/(sd*Math.SQRT2)))};
export function normalStats(x:number,mean:number,sd:number){const z=(x-mean)/sd,cdf=normalCdf(x,mean,sd);return{z,cdf,upper:1-cdf}}
export function normalInterval(lower:number,upper:number,mean:number,sd:number){if(lower>upper)[lower,upper]=[upper,lower];return normalCdf(upper,mean,sd)-normalCdf(lower,mean,sd)}
export function parseNumberList(input:string){const values=input.trim().split(/[\s,;]+/).filter(Boolean).map(Number);if(!values.length||values.some(n=>!Number.isFinite(n)))throw new Error('Enter a list of finite numbers separated by spaces, commas, or semicolons.');return values}
export function linearRegression(xs:number[],ys:number[]){if(xs.length!==ys.length||xs.length<2)throw new Error('X and Y must contain the same number of values, with at least two pairs.');const n=xs.length,mx=xs.reduce((a,b)=>a+b,0)/n,my=ys.reduce((a,b)=>a+b,0)/n;let sxx=0,syy=0,sxy=0;for(let i=0;i<n;i++){const dx=xs[i]-mx,dy=ys[i]-my;sxx+=dx*dx;syy+=dy*dy;sxy+=dx*dy}if(sxx===0)throw new Error('Regression is undefined when all X values are identical.');const slope=sxy/sxx,intercept=my-slope*mx,r=syy===0?0:sxy/Math.sqrt(sxx*syy),r2=r*r,residuals=xs.map((x,i)=>ys[i]-(intercept+slope*x)),sse=residuals.reduce((s,e)=>s+e*e,0),rmse=Math.sqrt(sse/n);return{n,meanX:mx,meanY:my,slope,intercept,r,r2,sse,rmse,predict:(x:number)=>intercept+slope*x,residuals}}
const absBig=(n:bigint)=>n<0n?-n:n;
export function gcdBig(a:bigint,b:bigint){a=absBig(a);b=absBig(b);while(b)[a,b]=[b,a%b];return a}
export function lcmBig(a:bigint,b:bigint){return a===0n||b===0n?0n:absBig(a/gcdBig(a,b)*b)}
export function primeFactors(n:bigint){n=absBig(n);if(n<2n)return[]as [bigint,number][];const out:[bigint,number][]=[];let p=2n;while(p*p<=n){let c=0;while(n%p===0n){n/=p;c++}if(c)out.push([p,c]);p=p===2n?3n:p+2n}if(n>1n)out.push([n,1]);return out}
export function parseBigIntStrict(input:string){if(!/^[+-]?\d+$/.test(input.trim()))throw new Error('Enter an integer.');return BigInt(input.trim())}
export type Complex={re:number;im:number};
export function parseComplex(input:string):Complex{const s=input.replace(/\s+/g,'').replace(/j/g,'i');if(!s.includes('i')){const re=Number(s);if(!Number.isFinite(re))throw new Error('Use a form such as 3+4i.');return{re,im:0}}const t=s.replace(/i$/,'');let split=-1;for(let i=1;i<t.length;i++)if((t[i]==='+'||t[i]==='-')&&!/[eE]/.test(t[i-1]))split=i;let re=0,im=0;if(split>=0){re=Number(t.slice(0,split));const part=t.slice(split);im=part==='+'?1:part==='-'?-1:Number(part)}else{im=t===''||t==='+'?1:t==='-'?-1:Number(t)}if(!Number.isFinite(re)||!Number.isFinite(im))throw new Error('Use a form such as 3+4i.');return{re,im}}
export const formatComplex=(z:Complex)=>`${Number(z.re.toPrecision(10))}${z.im<0?' - ':' + '}${Number(Math.abs(z.im).toPrecision(10))}i`;
export function complexOp(a:Complex,b:Complex,op:'add'|'subtract'|'multiply'|'divide'){if(op==='add')return{re:a.re+b.re,im:a.im+b.im};if(op==='subtract')return{re:a.re-b.re,im:a.im-b.im};if(op==='multiply')return{re:a.re*b.re-a.im*b.im,im:a.re*b.im+a.im*b.re};const d=b.re*b.re+b.im*b.im;if(d===0)throw new Error('Cannot divide by zero.');return{re:(a.re*b.re+a.im*b.im)/d,im:(a.im*b.re-a.re*b.im)/d}}
export const complexMagnitude=(z:Complex)=>Math.hypot(z.re,z.im);export const complexArgument=(z:Complex)=>Math.atan2(z.im,z.re);
export function solveQuadratic(a:number,b:number,c:number){if(![a,b,c].every(Number.isFinite))throw new Error('Coefficients must be finite numbers.');if(a===0){if(b===0)throw new Error('At least a or b must be non-zero.');return{kind:'linear' as const,roots:[-c/b],discriminant:null,vertex:null,axis:null}}const d=b*b-4*a*c,axis=-b/(2*a),vertex={x:axis,y:a*axis*axis+b*axis+c};if(d>=0){const s=Math.sqrt(d);return{kind:'real' as const,roots:[(-b+s)/(2*a),(-b-s)/(2*a)],discriminant:d,vertex,axis}}const s=Math.sqrt(-d);return{kind:'complex' as const,roots:[{re:-b/(2*a),im:s/(2*a)},{re:-b/(2*a),im:-s/(2*a)}],discriminant:d,vertex,axis}}
export type Vector=number[];export function parseVector(input:string){return parseNumberList(input)}
const requireSame=(a:Vector,b:Vector)=>{if(a.length!==b.length)throw new Error('Vectors must have the same dimension.')};
export const vectorAdd=(a:Vector,b:Vector,sign=1)=>{requireSame(a,b);return a.map((v,i)=>v+sign*b[i])};export const vectorMagnitude=(a:Vector)=>Math.hypot(...a);export const vectorDot=(a:Vector,b:Vector)=>{requireSame(a,b);return a.reduce((s,v,i)=>s+v*b[i],0)};
export function vectorCross(a:Vector,b:Vector){if(a.length!==3||b.length!==3)throw new Error('Cross product requires two 3D vectors.');return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
export function vectorAngle(a:Vector,b:Vector){const ma=vectorMagnitude(a),mb=vectorMagnitude(b);if(ma===0||mb===0)throw new Error('Angle is undefined for a zero vector.');const c=Math.max(-1,Math.min(1,vectorDot(a,b)/(ma*mb)));return Math.acos(c)}
