const splitOutside=(input:string,separator:string)=>{const out:string[]=[];let quote='',depth=0,start=0;for(let i=0;i<input.length;i++){const c=input[i];if(quote){if(c==='\\')i++;else if(c===quote)quote='';continue}if(c==='"'||c==="'"){quote=c;continue}if('([{'.includes(c))depth++;else if(')]}'.includes(c))depth--;else if(c===separator&&depth===0){out.push(input.slice(start,i));start=i+1}}out.push(input.slice(start));return out};
const splitKeyValue=(line:string)=>{let quote='';for(let i=0;i<line.length;i++){const c=line[i];if(quote){if(c==='\\')i++;else if(c===quote)quote='';continue}if(c==='"'||c==="'")quote=c;else if(c===':')return[line.slice(0,i).trim(),line.slice(i+1).trim()]as const}throw new Error(`Expected key: value near “${line}”.`)};
const stripYamlComment=(line:string)=>{let quote='';for(let i=0;i<line.length;i++){const c=line[i];if(quote){if(c==='\\')i++;else if(c===quote)quote='';continue}if(c==='"'||c==="'")quote=c;else if(c==='#'&&(i===0||/\s/.test(line[i-1])))return line.slice(0,i)}return line};
function parseScalar(raw:string):unknown{const s=raw.trim();if(!s)return'';if(s==='null'||s==='~')return null;if(s==='true')return true;if(s==='false')return false;if(/^[-+]?\d+(?:\.\d+)?(?:e[-+]?\d+)?$/i.test(s))return Number(s);if((s.startsWith('"')&&s.endsWith('"'))||(s.startsWith("'")&&s.endsWith("'"))){if(s[0]==='"')return JSON.parse(s);return s.slice(1,-1).replace(/''/g,"'")}if((s.startsWith('[')&&s.endsWith(']'))||(s.startsWith('{')&&s.endsWith('}'))){try{return JSON.parse(s)}catch{/* keep plain string */}}return s}
type YLine={indent:number;text:string};
export function parseYamlSubset(input:string):unknown{const lines:YLine[]=input.replace(/\t/g,'  ').split(/\r?\n/).map(stripYamlComment).map(raw=>({indent:raw.match(/^ */)?.[0].length??0,text:raw.trim()})).filter(l=>l.text&&l.text!=='---'&&l.text!=='...');if(!lines.length)return{};const parse=(start:number,indent:number):[unknown,number]=>{const sequence=lines[start]?.indent===indent&&lines[start].text.startsWith('-');if(sequence){const arr:unknown[]=[];let i=start;while(i<lines.length&&lines[i].indent===indent&&lines[i].text.startsWith('-')){const rest=lines[i].text.slice(1).trim();if(!rest){if(lines[i+1]&&lines[i+1].indent>indent){const[v,n]=parse(i+1,lines[i+1].indent);arr.push(v);i=n}else{arr.push(null);i++}continue}if(/^[^:]+:\s*/.test(rest)){const[k,vraw]=splitKeyValue(rest),obj:Record<string,unknown>={[k]:vraw?parseScalar(vraw):null};i++;while(i<lines.length&&lines[i].indent>indent){const childIndent=lines[i].indent;if(lines[i].text.startsWith('-')){if(obj[k]===null){const[v,n]=parse(i,childIndent);obj[k]=v;i=n;continue}break}const[ck,cv]=splitKeyValue(lines[i].text);if(cv){obj[ck]=parseScalar(cv);i++}else if(lines[i+1]&&lines[i+1].indent>childIndent){const[v,n]=parse(i+1,lines[i+1].indent);obj[ck]=v;i=n}else{obj[ck]=null;i++}}arr.push(obj)}else{arr.push(parseScalar(rest));i++}}return[arr,i]}
 const obj:Record<string,unknown>={};let i=start;while(i<lines.length&&lines[i].indent===indent&&!lines[i].text.startsWith('-')){const[k,vraw]=splitKeyValue(lines[i].text);if(vraw){obj[k]=parseScalar(vraw);i++}else if(lines[i+1]&&lines[i+1].indent>indent){const[v,n]=parse(i+1,lines[i+1].indent);obj[k]=v;i=n}else{obj[k]=null;i++}}return[obj,i]};return parse(0,lines[0].indent)[0]}
const needsYamlQuotes=(s:string)=>!s||/^(?:null|true|false|~|[-+]?\d+(?:\.\d+)?|[-?:,\[\]{}#&*!|>'"%@`]|.*:\s|.*\s#)/i.test(s);
const yamlScalar=(v:unknown)=>v===null?'null':typeof v==='string'?(needsYamlQuotes(v)?JSON.stringify(v):v):typeof v==='number'||typeof v==='boolean'?String(v):JSON.stringify(v);
export function jsonToYaml(value:unknown,indent=0):string{const pad=' '.repeat(indent);if(Array.isArray(value))return value.map(v=>v!==null&&typeof v==='object'?`${pad}-\n${jsonToYaml(v,indent+2)}`:`${pad}- ${yamlScalar(v)}`).join('\n');if(value&&typeof value==='object')return Object.entries(value as Record<string,unknown>).map(([k,v])=>v!==null&&typeof v==='object'?`${pad}${k}:\n${jsonToYaml(v,indent+2)}`:`${pad}${k}: ${yamlScalar(v)}`).join('\n');return`${pad}${yamlScalar(value)}`}
export const formatYaml=(input:string)=>jsonToYaml(parseYamlSubset(input));
function tomlValue(raw:string):unknown{const s=raw.trim();if((s.startsWith('"')&&s.endsWith('"'))||(s.startsWith("'")&&s.endsWith("'")))return s.slice(1,-1).replace(/\\"/g,'"').replace(/\\n/g,'\n');if(s==='true'||s==='false')return s==='true';if(/^[-+]?\d+(?:\.\d+)?$/.test(s))return Number(s);if(s.startsWith('[')&&s.endsWith(']'))return splitOutside(s.slice(1,-1),',').filter(Boolean).map(tomlValue);return s}
const setPath=(root:Record<string,unknown>,path:string[],value:unknown)=>{let node=root;for(const part of path.slice(0,-1)){const next=node[part];node=next&&typeof next==='object'&&!Array.isArray(next)?next as Record<string,unknown>:(node[part]={}) as Record<string,unknown>}node[path.at(-1)!]=value};
export function parseTomlSubset(input:string):Record<string,unknown>{const root:Record<string,unknown>={};let section:string[]=[];for(const raw of input.split(/\r?\n/)){const line=raw.replace(/\s+#.*$/,'').trim();if(!line)continue;if(/^\[.+\]$/.test(line)){section=line.slice(1,-1).split('.').map(s=>s.trim().replace(/^['"]|['"]$/g,''));continue}const eq=line.indexOf('=');if(eq<1)throw new Error(`Expected key = value near “${line}”.`);const key=line.slice(0,eq).trim().replace(/^['"]|['"]$/g,'');setPath(root,[...section,...key.split('.')],tomlValue(line.slice(eq+1)))}return root}
const tomlScalar=(v:unknown)=>typeof v==='string'?JSON.stringify(v):typeof v==='number'||typeof v==='boolean'?String(v):v===null?'""':Array.isArray(v)?`[${v.map(tomlScalar).join(', ')}]`:JSON.stringify(v);
export function jsonToToml(value:unknown):string{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('TOML root must be a JSON object.');const root=value as Record<string,unknown>,lines:string[]=[],tables:[string,Record<string,unknown>][]=[];const walk=(obj:Record<string,unknown>,path:string[])=>{const scalars=Object.entries(obj).filter(([,v])=>v===null||typeof v!=='object'||Array.isArray(v));const nested=Object.entries(obj).filter(([,v])=>v&&typeof v==='object'&&!Array.isArray(v));if(path.length){lines.push(`[${path.join('.')}]`)}for(const[k,v]of scalars)lines.push(`${k} = ${tomlScalar(v)}`);if(path.length&&nested.length)lines.push('');for(const[k,v]of nested)tables.push([path.concat(k).join('.'),v as Record<string,unknown>])};walk(root,[]);while(tables.length){const[path,obj]=tables.shift()!;if(lines.length&&lines.at(-1)!=='')lines.push('');const parts=path.split('.');lines.push(`[${path}]`);for(const[k,v]of Object.entries(obj)){if(v&&typeof v==='object'&&!Array.isArray(v))tables.push([parts.concat(k).join('.'),v as Record<string,unknown>]);else lines.push(`${k} = ${tomlScalar(v)}`)}}return lines.join('\n').replace(/\n{3,}/g,'\n\n')}
export const formatToml=(input:string)=>jsonToToml(parseTomlSubset(input));
const SQL_KEYWORDS=['SELECT','FROM','WHERE','GROUP BY','ORDER BY','HAVING','LIMIT','OFFSET','VALUES','SET','RETURNING','UNION','UNION ALL','LEFT JOIN','RIGHT JOIN','INNER JOIN','OUTER JOIN','FULL JOIN','CROSS JOIN','JOIN','ON','INSERT INTO','UPDATE','DELETE FROM','CREATE TABLE','ALTER TABLE','DROP TABLE'];
const protectStrings=(input:string)=>{const strings:string[]=[];let out='',quote='';for(let i=0;i<input.length;i++){const c=input[i];if(!quote&&(c==='"'||c==="'"||c==='`')){quote=c;let buf=c;for(i++;i<input.length;i++){buf+=input[i];if(input[i]===quote&&input[i-1]!=='\\')break}strings.push(buf);out+=`§${strings.length-1}§`;quote=''}else out+=c}return{out,strings}};
const restoreStrings=(input:string,strings:string[])=>input.replace(/§(\d+)§/g,(_,n)=>strings[Number(n)]??'');
export function minifySql(input:string){const{out,strings}=protectStrings(input);return restoreStrings(out.replace(/--[^\n]*|\/\*[\s\S]*?\*\//g,' ').replace(/\s+/g,' ').replace(/\s*([(),;=<>+*/-])\s*/g,'$1').trim(),strings)}
export function formatSql(input:string){const{out,strings}=protectStrings(minifySql(input));let s=out;for(const kw of [...SQL_KEYWORDS].sort((a,b)=>b.length-a.length)){const re=new RegExp(`\\b${kw.replace(/ /g,'\\s+')}\\b`,'gi');s=s.replace(re,`\n${kw}`)}s=s.replace(/^\n/,'').replace(/,\s*/g,',\n  ').replace(/\b(AND|OR)\b/gi,'\n  $1').replace(/;/g,';\n\n').replace(/\n{3,}/g,'\n\n');return restoreStrings(s.trim(),strings)}
export type SchemaIssue={path:string;message:string};
export function validateJsonSchema(value:unknown,schema:unknown):SchemaIssue[]{const issues:SchemaIssue[]=[];const visit=(v:unknown,s:any,path:string)=>{if(!s||typeof s!=='object')return;const type=s.type as string|undefined;if(type){const ok=type==='array'?Array.isArray(v):type==='null'?v===null:type==='integer'?Number.isInteger(v):type==='number'?typeof v==='number'&&Number.isFinite(v):type==='object'?!!v&&typeof v==='object'&&!Array.isArray(v):typeof v===type;if(!ok){issues.push({path,message:`Expected ${type}.`});return}}if(Array.isArray(s.enum)&&!s.enum.some((x:unknown)=>JSON.stringify(x)===JSON.stringify(v)))issues.push({path,message:'Value is not in enum.'});if(typeof v==='string'){if(typeof s.minLength==='number'&&v.length<s.minLength)issues.push({path,message:`Minimum length is ${s.minLength}.`});if(typeof s.maxLength==='number'&&v.length>s.maxLength)issues.push({path,message:`Maximum length is ${s.maxLength}.`});if(typeof s.pattern==='string'){try{if(!new RegExp(s.pattern).test(v))issues.push({path,message:`Does not match /${s.pattern}/.`})catch{issues.push({path,message:'Schema pattern is not a valid regular expression.'})}}if(typeof v==='number'){if(typeof s.minimum==='number'&&v<s.minimum)issues.push({path,message:`Must be ≥ ${s.minimum}.`});if(typeof s.maximum==='number'&&v>s.maximum)issues.push({path,message:`Must be ≤ ${s.maximum}.`})}if(Array.isArray(v)){if(typeof s.minItems==='number'&&v.length<s.minItems)issues.push({path,message:`Requires at least ${s.minItems} items.`});if(typeof s.maxItems==='number'&&v.length>s.maxItems)issues.push({path,message:`Allows at most ${s.maxItems} items.`});if(s.items)v.forEach((x,i)=>visit(x,s.items,`${path}[${i}]`))}if(v&&typeof v==='object'&&!Array.isArray(v)){const o=v as Record<string,unknown>;if(Array.isArray(s.required))for(const key of s.required)if(!(key in o))issues.push({path:`${path}.${key}`,message:'Required property is missing.'});if(s.properties&&typeof s.properties==='object')for(const[key,sub]of Object.entries(s.properties))if(key in o)visit(o[key],sub,`${path}.${key}`);if(s.additionalProperties===false&&s.properties)for(const key of Object.keys(o))if(!(key in s.properties))issues.push({path:`${path}.${key}`,message:'Additional property is not allowed.'})}};visit(value,schema,'$');return issues}
export function evaluateJsonPath(root:unknown,path:string):unknown[]{let i=0;if(path[i]!=='$')throw new Error('JSONPath must start with $.');i++;let nodes:unknown[]=[root];const applyKey=(key:string)=>{nodes=nodes.flatMap(n=>n&&typeof n==='object'&&!Array.isArray(n)&&key in(n as any)?[(n as any)[key]]:[])};const applyIndex=(idx:number)=>{nodes=nodes.flatMap(n=>Array.isArray(n)&&idx>=0&&idx<n.length?[n[idx]]:[])};const wildcard=()=>{nodes=nodes.flatMap(n=>Array.isArray(n)?n:n&&typeof n==='object'?Object.values(n as Record<string,unknown>):[])};while(i<path.length){if(path[i]==='.') {i++;if(path[i]==='*'){wildcard();i++;continue}const m=path.slice(i).match(/^[A-Za-z_$][\w$-]*/);if(!m)throw new Error(`Invalid property selector near ${path.slice(i)}.`);applyKey(m[0]);i+=m[0].length;continue}if(path[i]==='['){const end=path.indexOf(']',i);if(end<0)throw new Error('Missing closing ].');const body=path.slice(i+1,end).trim();if(body==='*')wildcard();else if(/^\d+$/.test(body))applyIndex(Number(body));else if(/^(['"]).*\1$/.test(body))applyKey(body.slice(1,-1));else throw new Error(`Unsupported bracket selector [${body}].`);i=end+1;continue}throw new Error(`Unexpected JSONPath token “${path[i]}”.`)}return nodes}
const textEncoder=new TextEncoder(),textDecoder=new TextDecoder();
export function encodeBase32Bytes(bytes:Uint8Array){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';let bits=0,value=0,out='';for(const b of bytes){value=(value<<8)|b;bits+=8;while(bits>=5){out+=alphabet[(value>>>(bits-5))&31];bits-=5}}if(bits)out+=alphabet[(value<<(5-bits))&31];while(out.length%8)out+='=';return out}
export function decodeBase32Bytes(input:string){const alphabet='ABCDEFGHIJKLMNOPQRSTUVWXYZ234567',clean=input.toUpperCase().replace(/[\s=-]/g,'');let bits=0,value=0;const out:number[]=[];for(const c of clean){const n=alphabet.indexOf(c);if(n<0)throw new Error(`Invalid Base32 character: ${c}`);value=(value<<5)|n;bits+=5;if(bits>=8){out.push((value>>>(bits-8))&255);bits-=8}}return new Uint8Array(out)}
const B58='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
export function encodeBase58Bytes(bytes:Uint8Array){let n=0n;for(const b of bytes)n=(n<<8n)|BigInt(b);let out='';while(n){out=B58[Number(n%58n)]+out;n/=58n}for(const b of bytes){if(b===0)out='1'+out;else break}return out||'1'}
export function decodeBase58Bytes(input:string){let n=0n;for(const c of input.trim()){const x=B58.indexOf(c);if(x<0)throw new Error(`Invalid Base58 character: ${c}`);n=n*58n+BigInt(x)}const out:number[]=[];while(n){out.unshift(Number(n&255n));n>>=8n}for(const c of input){if(c==='1')out.unshift(0);else break}return new Uint8Array(out)}
export function encodeAscii85Bytes(bytes:Uint8Array){let out='<~';for(let i=0;i<bytes.length;i+=4){const chunk=bytes.slice(i,i+4);let n=0;for(let j=0;j<4;j++)n=n*256+(chunk[j]??0);if(chunk.length===4&&n===0){out+='z';continue}const chars=Array(5).fill('');for(let j=4;j>=0;j--){chars[j]=String.fromCharCode(n%85+33);n=Math.floor(n/85)}out+=chars.slice(0,chunk.length+1).join('')}return out+'~>'}
export function decodeAscii85Bytes(input:string){const s=input.trim().replace(/^<~/,'').replace(/~>$/,'').replace(/\s/g,'');const out:number[]=[];let group='';const flush=()=>{if(!group)return;const len=group.length;while(group.length<5)group+='u';let n=0;for(const c of group)n=n*85+(c.charCodeAt(0)-33);const bytes=[n>>>24,(n>>>16)&255,(n>>>8)&255,n&255];out.push(...bytes.slice(0,len-1));group=''};for(const c of s){if(c==='z'){if(group)throw new Error('Ascii85 z shorthand must align to a 4-byte group.');out.push(0,0,0,0);continue}const code=c.charCodeAt(0);if(code<33||code>117)throw new Error(`Invalid Ascii85 character: ${c}`);group+=c;if(group.length===5){let n=0;for(const x of group)n=n*85+(x.charCodeAt(0)-33);out.push(n>>>24,(n>>>16)&255,(n>>>8)&255,n&255);group=''}}flush();return new Uint8Array(out)}
export type BaseEncoding='base32'|'base58'|'base85';
export function encodeBaseText(text:string,encoding:BaseEncoding){const b=textEncoder.encode(text);return encoding==='base32'?encodeBase32Bytes(b):encoding==='base58'?encodeBase58Bytes(b):encodeAscii85Bytes(b)}
export function decodeBaseText(text:string,encoding:BaseEncoding){const b=encoding==='base32'?decodeBase32Bytes(text):encoding==='base58'?decodeBase58Bytes(text):decodeAscii85Bytes(text);return textDecoder.decode(b)}
const ipToInt=(ip:string)=>{const p=ip.split('.').map(Number);if(p.length!==4||p.some(n=>!Number.isInteger(n)||n<0||n>255))throw new Error('Enter a valid IPv4 address.');return(((p[0]<<24)>>>0)+(p[1]<<16)+(p[2]<<8)+p[3])>>>0};const intToIp=(n:number)=>[n>>>24,(n>>>16)&255,(n>>>8)&255,n&255].join('.');
export function calculateSubnet(input:string){const[ip,prefixRaw]=input.trim().split('/'),prefix=Number(prefixRaw);if(!Number.isInteger(prefix)||prefix<0||prefix>32)throw new Error('CIDR prefix must be between /0 and /32.');const addr=ipToInt(ip),mask=prefix===0?0:(0xffffffff<<(32-prefix))>>>0,network=(addr&mask)>>>0,broadcast=(network|(~mask>>>0))>>>0,total=2**(32-prefix),usable=prefix>=31?total:Math.max(0,total-2);return{address:ip,prefix,mask:intToIp(mask),wildcard:intToIp((~mask)>>>0),network:intToIp(network),broadcast:intToIp(broadcast),firstHost:intToIp(prefix>=31?network:(network+1)>>>0),lastHost:intToIp(prefix>=31?broadcast:(broadcast-1)>>>0),totalAddresses:total,usableHosts:usable}}
export function parseUserAgent(ua:string){const browser=/Edg\/(\S+)/.exec(ua)?['Edge',RegExp.$1]:/OPR\/(\S+)/.exec(ua)?['Opera',RegExp.$1]:/Firefox\/(\S+)/.exec(ua)?['Firefox',RegExp.$1]:/Chrome\/(\S+)/.exec(ua)?['Chrome',RegExp.$1]:/Version\/(\S+).*Safari/.exec(ua)?['Safari',RegExp.$1]:['Unknown',''];const os=/Windows NT 10/.test(ua)?'Windows':/Android ([^;]+)/.exec(ua)?.[1]?`Android ${RegExp.$1}`:/iPhone OS ([\d_]+)/.exec(ua)?.[1]?`iOS ${RegExp.$1.replace(/_/g,'.')}`:/iPad.*OS ([\d_]+)/.exec(ua)?.[1]?`iPadOS ${RegExp.$1.replace(/_/g,'.')}`:/Mac OS X ([\d_]+)/.exec(ua)?.[1]?`macOS ${RegExp.$1.replace(/_/g,'.')}`:/Linux/.test(ua)?'Linux':'Unknown';const engine=/AppleWebKit\/([\d.]+)/.exec(ua)?.[1]?`WebKit ${RegExp.$1}`:/Gecko\/\d+/.test(ua)?'Gecko':'Unknown';const device=/Mobile|Android|iPhone|iPad/.test(ua)?(/iPad|Tablet/.test(ua)?'Tablet':'Mobile'):'Desktop';return{browser:browser[0],version:browser[1],engine,os,device}}
export function buildUtmUrl(base:string,params:{source?:string;medium?:string;campaign?:string;term?:string;content?:string}){const url=new URL(base);const map:[keyof typeof params,string][]=[['source','utm_source'],['medium','utm_medium'],['campaign','utm_campaign'],['term','utm_term'],['content','utm_content']];for(const[k,q]of map){const v=params[k]?.trim();if(v)url.searchParams.set(q,v);else url.searchParams.delete(q)}return url.toString()}
const escapeHtml=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const inlineMarkdown=(s:string)=>escapeHtml(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a href="$2" rel="noopener noreferrer">$1</a>');
export function markdownToHtml(input:string){const lines=input.split(/\r?\n/),out:string[]=[];let inCode=false,code:string[]=[];const closeList=()=>{if(out.at(-1)==='__LI__')out[out.length-1]='</ul>'};let list=false;for(const line of lines){if(/^```/.test(line)){if(inCode){out.push(`<pre><code>${escapeHtml(code.join('\n'))}</code></pre>`);code=[];inCode=false}else{if(list){out.push('</ul>');list=false}inCode=true}continue}if(inCode){code.push(line);continue}const h=/^(#{1,6})\s+(.*)$/.exec(line);if(h){if(list){out.push('</ul>');list=false}out.push(`<h${h[1].length}>${inlineMarkdown(h[2])}</h${h[1].length}>`);continue}const li=/^[-*+]\s+(.*)$/.exec(line);if(li){if(!list){out.push('<ul>');list=true}out.push(`<li>${inlineMarkdown(li[1])}</li>`);continue}if(list){out.push('</ul>');list=false}if(/^>\s?/.test(line)){out.push(`<blockquote>${inlineMarkdown(line.replace(/^>\s?/,''))}</blockquote>`);continue}if(!line.trim()){out.push('');continue}out.push(`<p>${inlineMarkdown(line)}</p>`)}if(inCode)out.push(`<pre><code>${escapeHtml(code.join('\n'))}</code></pre>`);if(list)out.push('</ul>');return out.join('\n').replace(/\n{3,}/g,'\n\n')}
export function htmlToMarkdown(input:string){return input.replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi,'').replace(/<pre><code[^>]*>([\s\S]*?)<\/code><\/pre>/gi,(_,x)=>`\n\`\`\`\n${x.replace(/<[^>]+>/g,'')}\n\`\`\`\n`).replace(/<h([1-6])[^>]*>([\s\S]*?)<\/h\1>/gi,(_,n,x)=>`\n${'#'.repeat(Number(n))} ${x.replace(/<[^>]+>/g,'')}\n`).replace(/<li[^>]*>([\s\S]*?)<\/li>/gi,(_,x)=>`\n- ${x.replace(/<[^>]+>/g,'')}`).replace(/<blockquote[^>]*>([\s\S]*?)<\/blockquote>/gi,(_,x)=>`\n> ${x.replace(/<[^>]+>/g,'')}\n`).replace(/<(strong|b)[^>]*>([\s\S]*?)<\/\1>/gi,'**$2**').replace(/<(em|i)[^>]*>([\s\S]*?)<\/\1>/gi,'*$2*').replace(/<code[^>]*>([\s\S]*?)<\/code>/gi,'`$1`').replace(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi,'[$2]($1)').replace(/<br\s*\/?>/gi,'\n').replace(/<\/(p|div|ul|ol|section)>/gi,'\n').replace(/<[^>]+>/g,'').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&amp;/g,'&').replace(/\n{3,}/g,'\n\n').trim()}
