import{decodeBase32Bytes}from'./p11-developer';
export function optimizeSvg(input:string){const src=input.trim();if(!/<svg\b/i.test(src))throw new Error('Input does not contain an <svg> root element.');return src.replace(/<!--([\s\S]*?)-->/g,'').replace(/<metadata\b[\s\S]*?<\/metadata>/gi,'').replace(/\s+(?:inkscape|sodipodi|sketch|xmlns:(?:inkscape|sodipodi)):[\w:-]+=("[^"]*"|'[^']*')/gi,'').replace(/\s+xmlns:(?:inkscape|sodipodi)=("[^"]*"|'[^']*')/gi,'').replace(/>\s+</g,'><').replace(/\s{2,}/g,' ').replace(/\s+\/>/g,'/>').trim()}
export function printSizeFromPixels(widthPx:number,heightPx:number,dpi:number){if(![widthPx,heightPx,dpi].every(n=>Number.isFinite(n)&&n>0))throw new Error('Pixel dimensions and DPI must be greater than zero.');const widthIn=widthPx/dpi,heightIn=heightPx/dpi;return{widthIn,heightIn,widthCm:widthIn*2.54,heightCm:heightIn*2.54,megapixels:widthPx*heightPx/1e6}}
export function pixelsFromPrint(width:number,height:number,unit:'in'|'cm',dpi:number){if(![width,height,dpi].every(n=>Number.isFinite(n)&&n>0))throw new Error('Print dimensions and DPI must be greater than zero.');const f=unit==='cm'?1/2.54:1;return{widthPx:Math.round(width*f*dpi),heightPx:Math.round(height*f*dpi)}}
const clamp=(n:number)=>Math.max(0,Math.min(255,Math.round(n)));
export function parseHexColor(input:string){const s=input.trim().replace(/^#/,'');if(!/^[0-9a-f]{3}([0-9a-f]{3})?$/i.test(s))throw new Error('Enter a 3- or 6-digit HEX color.');const h=s.length===3?s.split('').map(c=>c+c).join(''):s;return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]as[number,number,number]}
const toHex=(rgb:number[])=>'#'+rgb.map(v=>clamp(v).toString(16).padStart(2,'0')).join('').toUpperCase();
const MATRICES={protanopia:[[.567,.433,0],[.558,.442,0],[0,.242,.758]],deuteranopia:[[.625,.375,0],[.7,.3,0],[0,.3,.7]],tritanopia:[[.95,.05,0],[0,.433,.567],[0,.475,.525]],grayscale:[[.299,.587,.114],[.299,.587,.114],[.299,.587,.114]]}as const;
export type VisionMode=keyof typeof MATRICES;
export function simulateColorVision(hex:string,mode:VisionMode){const rgb=parseHexColor(hex),m=MATRICES[mode],out=m.map(row=>row[0]*rgb[0]+row[1]*rgb[1]+row[2]*rgb[2]);return{input:toHex(rgb),output:toHex(out)}}
export type RobotsGroup={agent:string;allow:string[];disallow:string[];crawlDelay?:number|null};
export function buildRobotsTxt(groups:RobotsGroup[],sitemaps:string[]=[]){if(!groups.length)throw new Error('Add at least one user-agent group.');const lines:string[]=[];for(const group of groups){const agent=group.agent.trim()||'*';lines.push(`User-agent: ${agent}`);for(const path of group.allow.filter(Boolean))lines.push(`Allow: ${path.startsWith('/')?path:'/'+path}`);for(const path of group.disallow.filter(Boolean))lines.push(`Disallow: ${path.startsWith('/')?path:'/'+path}`);if(group.crawlDelay!=null&&Number.isFinite(group.crawlDelay)&&group.crawlDelay>=0)lines.push(`# Crawl-delay is not supported by every crawler.`, `Crawl-delay: ${group.crawlDelay}`);lines.push('')}for(const sitemap of sitemaps.filter(Boolean)){const url=new URL(sitemap);lines.push(`Sitemap: ${url.toString()}`)}return lines.join('\n').trim()+'\n'}
const xmlEscape=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');
export type SitemapEntry={loc:string;lastmod?:string;changefreq?:string;priority?:number|null};
export function buildSitemapXml(entries:SitemapEntry[]){if(!entries.length)throw new Error('Add at least one URL.');const body=entries.map(entry=>{const url=new URL(entry.loc).toString(),parts=[`    <loc>${xmlEscape(url)}</loc>`];if(entry.lastmod){if(!/^\d{4}-\d{2}-\d{2}(?:T.*)?$/.test(entry.lastmod))throw new Error(`Invalid last-modified date for ${entry.loc}.`);parts.push(`    <lastmod>${xmlEscape(entry.lastmod)}</lastmod>`)}if(entry.changefreq)parts.push(`    <changefreq>${xmlEscape(entry.changefreq)}</changefreq>`);if(entry.priority!=null){if(entry.priority<0||entry.priority>1)throw new Error('Sitemap priority must be between 0 and 1.');parts.push(`    <priority>${entry.priority.toFixed(1)}</priority>`)}return`  <url>\n${parts.join('\n')}\n  </url>`}).join('\n');return`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${body}\n</urlset>\n`}
const vEscape=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/,/g,'\\,').replace(/;/g,'\\;');
export type VCardData={first:string;last:string;organization?:string;title?:string;phone?:string;email?:string;website?:string;street?:string;city?:string;region?:string;postal?:string;country?:string};
export function buildVCard(data:VCardData){if(!(data.first.trim()||data.last.trim()))throw new Error('Enter at least a first or last name.');const lines=['BEGIN:VCARD','VERSION:3.0',`N:${vEscape(data.last)};${vEscape(data.first)};;;`,`FN:${vEscape([data.first,data.last].filter(Boolean).join(' '))}`];if(data.organization)lines.push(`ORG:${vEscape(data.organization)}`);if(data.title)lines.push(`TITLE:${vEscape(data.title)}`);if(data.phone)lines.push(`TEL;TYPE=CELL:${vEscape(data.phone)}`);if(data.email)lines.push(`EMAIL;TYPE=INTERNET:${vEscape(data.email)}`);if(data.website){const url=new URL(data.website);lines.push(`URL:${url.toString()}`)}if(data.street||data.city||data.region||data.postal||data.country)lines.push(`ADR;TYPE=HOME:;;${vEscape(data.street||'')};${vEscape(data.city||'')};${vEscape(data.region||'')};${vEscape(data.postal||'')};${vEscape(data.country||'')}`);lines.push('END:VCARD');return lines.join('\r\n')+'\r\n'}
export async function generateTotp(secret:string,options?:{digits?:6|8;period?:number;timestamp?:number;algorithm?:'SHA-1'|'SHA-256'|'SHA-512'}){const keyBytes=decodeBase32Bytes(secret),digits=options?.digits??6,period=options?.period??30,timestamp=options?.timestamp??Date.now(),algorithm=options?.algorithm??'SHA-1';if(!keyBytes.length)throw new Error('Enter a non-empty Base32 secret.');if(!(period>0&&Number.isFinite(period)))throw new Error('Period must be greater than zero.');const counter=BigInt(Math.floor(timestamp/1000/period)),msg=new Uint8Array(8);let x=counter;for(let i=7;i>=0;i--){msg[i]=Number(x&255n);x>>=8n}const key=await crypto.subtle.importKey('raw',keyBytes,{name:'HMAC',hash:algorithm},false,['sign']),sig=new Uint8Array(await crypto.subtle.sign('HMAC',key,msg)),offset=sig[sig.length-1]&15,binary=((sig[offset]&127)<<24)|((sig[offset+1]&255)<<16)|((sig[offset+2]&255)<<8)|(sig[offset+3]&255),mod=10**digits,code=String(binary%mod).padStart(digits,'0'),elapsed=Math.floor(timestamp/1000)%period;return{code,remaining:period-elapsed,counter:counter.toString(),period,digits,algorithm}}
export function minifyCss(input:string){let out='',quote='',comment=false;for(let i=0;i<input.length;i++){const c=input[i],n=input[i+1];if(comment){if(c==='*'&&n==='/'){comment=false;i++}continue}if(quote){out+=c;if(c==='\\'&&i+1<input.length){out+=input[++i];continue}if(c===quote)quote='';continue}if(c==='/'&&n==='*'){comment=true;i++;continue}if(c==='"'||c==="'"){quote=c;out+=c;continue}out+=c}return out.replace(/\s+/g,' ').replace(/\s*([{}:;,>+~])\s*/g,'$1').replace(/;}/g,'}').trim()}
