const collapseText=(s:string)=>s.replace(/\s+/g,' ').trim();
function xmlTokens(input:string){const out:string[]=[];let i=0,start=0;const pushText=(end:number)=>{const t=collapseText(input.slice(start,end));if(t)out.push(t)};while(i<input.length){if(input[i]!=='<'){i++;continue}pushText(i);let end=-1;if(input.startsWith('<!--',i)){end=input.indexOf('-->',i+4);if(end<0)throw new Error('Unclosed XML comment.');end+=3}else if(input.startsWith('<![CDATA[',i)){end=input.indexOf(']]>',i+9);if(end<0)throw new Error('Unclosed CDATA section.');end+=3}else{let quote='';for(let j=i+1;j<input.length;j++){const c=input[j];if(quote){if(c===quote)quote=''}else if(c==='"'||c==="'")quote=c;else if(c==='>'){end=j+1;break}}if(end<0)throw new Error('Unclosed XML tag.')}out.push(input.slice(i,end).trim());i=end;start=end}pushText(input.length);return out}
const xmlName=(token:string)=>token.match(/^<\/?\s*([^\s/>]+)/)?.[1]??'';
export function formatXml(input:string){const tokens=xmlTokens(input.trim());if(!tokens.length)throw new Error('Enter XML to format.');const out:string[]=[],stack:string[]=[];let depth=0;for(const token of tokens){if(token.startsWith('</')){const name=xmlName(token),expected=stack.pop();if(!name||expected!==name)throw new Error(`Mismatched closing tag: expected </${expected??'?'}> but found </${name||'?'}>.`);depth--;out.push(`${'  '.repeat(Math.max(0,depth))}${token}`);continue}if(token.startsWith('<')){const special=/^<\?|^<!/.test(token),selfClosing=/\/\s*>$/.test(token),name=xmlName(token);out.push(`${'  '.repeat(depth)}${token}`);if(!special&&!selfClosing){if(!name)throw new Error('Invalid XML start tag.');stack.push(name);depth++}continue}out.push(`${'  '.repeat(depth)}${token}`)}if(stack.length)throw new Error(`Unclosed XML tag: <${stack.at(-1)}>.`);return out.join('\n')}
export function parseUrl(input:string){const u=new URL(input.trim());const params:[string,string][]=[...u.searchParams.entries()];return{href:u.href,protocol:u.protocol,origin:u.origin,hostname:u.hostname,port:u.port||'(default)',pathname:u.pathname,search:u.search,hash:u.hash,username:u.username,hasPassword:Boolean(u.password),queryEntries:params}}
export function parseQueryString(input:string){let raw=input.trim();if(raw.includes('?'))raw=raw.slice(raw.indexOf('?')+1);if(raw.includes('#'))raw=raw.slice(0,raw.indexOf('#'));raw=raw.replace(/^\?/,'');const params=new URLSearchParams(raw),entries=[...params.entries()],object:Record<string,string|string[]>={};for(const[k,v]of entries){const prev=object[k];object[k]=prev===undefined?v:Array.isArray(prev)?[...prev,v]:[prev,v]}return{entries,object,count:entries.length}}
export function buildQueryStringFromLines(input:string){const params=new URLSearchParams();for(const raw of input.split(/\r?\n/)){const line=raw.trim();if(!line)continue;const eq=line.indexOf('='),key=(eq<0?line:line.slice(0,eq)).trim(),value=eq<0?'':line.slice(eq+1).trim();if(!key)throw new Error('Query parameter keys cannot be empty.');params.append(key,value)}const s=params.toString();return s?`?${s}`:''}
type SemVer={major:number;minor:number;patch:number;pre:(string|number)[];build:string[];raw:string};
export function parseSemver(input:string):SemVer{const raw=input.trim(),m=/^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z.-]+))?(?:\+([0-9A-Za-z.-]+))?$/.exec(raw);if(!m)throw new Error('Use Semantic Versioning form such as 1.2.3, 1.2.3-beta.1, or 1.2.3+build.');const pre=(m[4]?.split('.')??[]).map(x=>/^0$|^[1-9]\d*$/.test(x)?Number(x):x);return{major:Number(m[1]),minor:Number(m[2]),patch:Number(m[3]),pre,build:m[5]?.split('.')??[],raw}}
export function compareSemver(a:string,b:string){const A=parseSemver(a),B=parseSemver(b);for(const k of ['major','minor','patch']as const)if(A[k]!==B[k])return A[k]<B[k]?-1:1;if(!A.pre.length&&!B.pre.length)return 0;if(!A.pre.length)return 1;if(!B.pre.length)return-1;const n=Math.max(A.pre.length,B.pre.length);for(let i=0;i<n;i++){const x=A.pre[i],y=B.pre[i];if(x===undefined)return-1;if(y===undefined)return 1;if(x===y)continue;if(typeof x==='number'&&typeof y==='number')return x<y?-1:1;if(typeof x==='number')return-1;if(typeof y==='number')return 1;return x<y?-1:1}return 0}
const rwx=(n:number)=>`${n&4?'r':'-'}${n&2?'w':'-'}${n&1?'x':'-'}`;
function symbolicFromMode(mode:number){const special=(mode>>9)&7,a=[(mode>>6)&7,(mode>>3)&7,mode&7],parts=a.map(rwx);if(special&4)parts[0]=parts[0].slice(0,2)+(parts[0][2]==='x'?'s':'S');if(special&2)parts[1]=parts[1].slice(0,2)+(parts[1][2]==='x'?'s':'S');if(special&1)parts[2]=parts[2].slice(0,2)+(parts[2][2]==='x'?'t':'T');return parts.join('')}
function modeFromSymbolic(s:string){if(!/^[r-][w-][xSs-][r-][w-][xSs-][r-][w-][xTt-]$/.test(s))throw new Error('Symbolic mode must look like rwxr-xr--.');let mode=0,special=0;for(let group=0;group<3;group++){const p=s.slice(group*3,group*3+3);let n=(p[0]==='r'?4:0)+(p[1]==='w'?2:0)+(/[xst]/i.test(p[2])?1:0);mode|=n<<((2-group)*3)}if(/[sS]/.test(s[2]))special|=4;if(/[sS]/.test(s[5]))special|=2;if(/[tT]/.test(s[8]))special|=1;return mode|(special<<9)}
export function parseChmod(input:string){const s=input.trim();let mode:number;if(/^[0-7]{3,4}$/.test(s)){const digits=s.length===3?'0'+s:s,vals=digits.split('').map(Number);mode=((vals[0]&7)<<9)|((vals[1]&7)<<6)|((vals[2]&7)<<3)|(vals[3]&7)}else mode=modeFromSymbolic(s);const special=(mode>>9)&7,owner=(mode>>6)&7,group=(mode>>3)&7,other=mode&7;return{octal:`${special?special:''}${owner}${group}${other}`,symbolic:symbolicFromMode(mode),owner:{read:Boolean(owner&4),write:Boolean(owner&2),execute:Boolean(owner&1)},group:{read:Boolean(group&4),write:Boolean(group&2),execute:Boolean(group&1)},other:{read:Boolean(other&4),write:Boolean(other&2),execute:Boolean(other&1)},special:{setuid:Boolean(special&4),setgid:Boolean(special&2),sticky:Boolean(special&1)}}}
const pascal=(s:string)=>{const v=s.replace(/[^A-Za-z0-9]+/g,' ').trim().split(/\s+/).filter(Boolean).map(x=>x[0].toUpperCase()+x.slice(1)).join('');return/^\d/.test(v)?`T${v}`:v||'Value'};
const tsKey=(k:string)=>/^[A-Za-z_$][\w$]*$/.test(k)?k:JSON.stringify(k);
export function jsonToTypeScript(value:unknown,rootName='Root'){const blocks:string[]=[],seen=new Set<string>();const infer=(v:unknown,name:string):string=>{if(v===null)return'null';if(Array.isArray(v)){if(!v.length)return'unknown[]';const types=[...new Set(v.map((x,i)=>infer(x,`${name}Item${i?i+1:''}`)))];return`(${types.join(' | ')})[]`}switch(typeof v){case'string':return'string';case'number':return'number';case'boolean':return'boolean';case'object':{const interfaceName=pascal(name);if(!seen.has(interfaceName)){seen.add(interfaceName);const rows=Object.entries(v as Record<string,unknown>).map(([k,x])=>`  ${tsKey(k)}: ${infer(x,interfaceName+pascal(k))};`);blocks.push(`export interface ${interfaceName} {\n${rows.join('\n')}\n}`)}return interfaceName}default:return'unknown'}};const name=pascal(rootName),type=infer(value,name);if(type!==name)blocks.push(`export type ${name} = ${type};`);return blocks.reverse().join('\n\n')}
export function parseHttpHeaders(input:string){const lines=input.replace(/\r\n/g,'\n').split('\n'),headers:Record<string,string[]>={},entries:{name:string;value:string}[]=[];let startLine='';for(const raw of lines){const line=raw.trim();if(!line)continue;const colon=line.indexOf(':');if(colon<1){if(!startLine)startLine=line;else throw new Error(`Expected “Header-Name: value” near: ${line}`);continue}const name=line.slice(0,colon).trim(),value=line.slice(colon+1).trim();if(!/^[!#$%&'*+.^_`|~0-9A-Za-z-]+$/.test(name))throw new Error(`Invalid HTTP header name: ${name}`);entries.push({name,value});const key=name.toLowerCase();(headers[key]??=[]).push(value)}return{startLine,entries,headers,count:entries.length}}
const MIME:Record<string,string>={html:'text/html',htm:'text/html',css:'text/css',js:'text/javascript',mjs:'text/javascript',json:'application/json',xml:'application/xml',txt:'text/plain',csv:'text/csv',md:'text/markdown',pdf:'application/pdf',zip:'application/zip',gz:'application/gzip',tar:'application/x-tar',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',svg:'image/svg+xml',ico:'image/x-icon',avif:'image/avif',mp3:'audio/mpeg',wav:'audio/wav',ogg:'audio/ogg',m4a:'audio/mp4',mp4:'video/mp4',webm:'video/webm',mov:'video/quicktime',woff:'font/woff',woff2:'font/woff2',ttf:'font/ttf',otf:'font/otf',wasm:'application/wasm',ics:'text/calendar',vcf:'text/vcard',yaml:'application/yaml',yml:'application/yaml'};
export function lookupMime(input:string){const q=input.trim().toLowerCase().replace(/^\./,'');if(!q)throw new Error('Enter a file extension or MIME type.');if(q.includes('/')){const extensions=Object.entries(MIME).filter(([,mime])=>mime===q).map(([ext])=>'.'+ext);return{mime:q,extensions,known:extensions.length>0}}const mime=MIME[q];return{extension:'.'+q,mime:mime??'application/octet-stream',known:Boolean(mime)}}
export function normalizeUnicode(input:string){const forms={NFC:input.normalize('NFC'),NFD:input.normalize('NFD'),NFKC:input.normalize('NFKC'),NFKD:input.normalize('NFKD')};return{...forms,codePoints:[...input].map(c=>`U+${c.codePointAt(0)!.toString(16).toUpperCase().padStart(4,'0')}`)}}
export type DotenvEntry={key:string;value:string};
export function parseDotenv(input:string){const entries:DotenvEntry[]=[];for(const raw of input.split(/\r?\n/)){const line=raw.trim();if(!line||line.startsWith('#'))continue;const body=line.replace(/^export\s+/,'');const eq=body.indexOf('=');if(eq<1)throw new Error(`Expected KEY=value near: ${line}`);const key=body.slice(0,eq).trim();if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key))throw new Error(`Invalid environment variable name: ${key}`);let value=body.slice(eq+1).trim();if((value.startsWith('"')&&value.endsWith('"'))||(value.startsWith("'")&&value.endsWith("'"))){const quote=value[0];value=value.slice(1,-1);if(quote==='"')value=value.replace(/\\n/g,'\n').replace(/\\r/g,'\r').replace(/\\t/g,'\t').replace(/\\"/g,'"').replace(/\\\\/g,'\\')}else value=value.replace(/\s+#.*$/,'');entries.push({key,value})}return entries}
const envValue=(v:string)=>!v||/[\s#'"\\]/.test(v)?JSON.stringify(v):v;
export function formatDotenv(input:string){return parseDotenv(input).map(({key,value})=>`${key}=${envValue(value)}`).join('\n')+'\n'}
export function dotenvObject(input:string){const out:Record<string,string>={};for(const e of parseDotenv(input))out[e.key]=e.value;return out}
export function minifyHtml(input:string){const protectedBlocks:string[]=[];let s=input.replace(/<(pre|textarea|script|style)\b[^>]*>[\s\S]*?<\/\1>/gi,m=>{const key=`___TT_BLOCK_${protectedBlocks.length}___`;protectedBlocks.push(m);return key});s=s.replace(/<!--(?!\[if)[\s\S]*?-->/gi,'').replace(/>\s+</g,'><').replace(/[\t\r\n]+/g,' ').replace(/ {2,}/g,' ').trim();protectedBlocks.forEach((block,i)=>{s=s.replace(`___TT_BLOCK_${i}___`,block)});return s}
