const esc=(s:string)=>s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const meta=(name:string,content:string,property=false)=>content.trim()?`<meta ${property?'property':'name'}="${esc(name)}" content="${esc(content.trim())}">`:'';
export type MetaTagInput={title?:string;description?:string;canonical?:string;robots?:string;author?:string;themeColor?:string;viewport?:string};
export function buildMetaTags(data:MetaTagInput){const lines:string[]=[];if(data.title?.trim())lines.push(`<title>${esc(data.title.trim())}</title>`);if(data.description)lines.push(meta('description',data.description));if(data.author)lines.push(meta('author',data.author));if(data.robots)lines.push(meta('robots',data.robots));if(data.viewport)lines.push(meta('viewport',data.viewport));if(data.themeColor)lines.push(meta('theme-color',data.themeColor));if(data.canonical?.trim()){const u=new URL(data.canonical.trim());lines.push(`<link rel="canonical" href="${esc(u.toString())}">`)}return lines.filter(Boolean).join('\n')}
export type SocialMetaInput={title:string;description?:string;url?:string;image?:string;siteName?:string;type?:string;twitterCard?:'summary'|'summary_large_image';twitterSite?:string};
export function buildSocialMeta(data:SocialMetaInput){if(!data.title.trim())throw new Error('Title is required.');const lines=[meta('og:title',data.title,true),meta('og:type',data.type||'website',true)];if(data.description)lines.push(meta('og:description',data.description,true));if(data.siteName)lines.push(meta('og:site_name',data.siteName,true));if(data.url){const u=new URL(data.url);lines.push(meta('og:url',u.toString(),true))}if(data.image){const u=new URL(data.image);lines.push(meta('og:image',u.toString(),true))}lines.push(meta('twitter:card',data.twitterCard||'summary_large_image'),meta('twitter:title',data.title));if(data.description)lines.push(meta('twitter:description',data.description));if(data.image)lines.push(meta('twitter:image',new URL(data.image).toString()));if(data.twitterSite)lines.push(meta('twitter:site',data.twitterSite));return lines.filter(Boolean).join('\n')}
export function parseHexColor(input:string){const raw=input.trim().replace(/^#/,'');if(!/^[0-9a-f]{3}$|^[0-9a-f]{6}$/i.test(raw))throw new Error('Enter a 3- or 6-digit HEX color.');const h=raw.length===3?raw.split('').map(c=>c+c).join(''):raw;return[parseInt(h.slice(0,2),16),parseInt(h.slice(2,4),16),parseInt(h.slice(4,6),16)]as[number,number,number]}
const channel=(v:number)=>{const x=v/255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4};
export function relativeLuminance(hex:string){const[r,g,b]=parseHexColor(hex);return .2126*channel(r)+.7152*channel(g)+.0722*channel(b)}
export function contrastRatio(a:string,b:string){const l1=relativeLuminance(a),l2=relativeLuminance(b),ratio=(Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05);return{ratio,aaNormal:ratio>=4.5,aaLarge:ratio>=3,aaaNormal:ratio>=7,aaaLarge:ratio>=4.5}}
export type GradientStop={color:string;position:number};
export function buildCssGradient(type:'linear'|'radial',stops:GradientStop[],angle=135){if(stops.length<2)throw new Error('Add at least two gradient colors.');for(const s of stops){parseHexColor(s.color);if(!Number.isFinite(s.position)||s.position<0||s.position>100)throw new Error('Gradient stop positions must be between 0 and 100%.')}const body=stops.map(s=>`${s.color} ${s.position}%`).join(', ');return type==='linear'?`linear-gradient(${Number(angle.toFixed(2))}deg, ${body})`:`radial-gradient(circle, ${body})`}
export type ShadowInput={x:number;y:number;blur:number;spread:number;color:string;opacity:number;inset?:boolean};
export function buildBoxShadow(s:ShadowInput){parseHexColor(s.color);if(![s.x,s.y,s.blur,s.spread,s.opacity].every(Number.isFinite))throw new Error('Shadow values must be finite numbers.');if(s.blur<0)throw new Error('Blur cannot be negative.');if(s.opacity<0||s.opacity>1)throw new Error('Opacity must be between 0 and 1.');const[r,g,b]=parseHexColor(s.color);return`${s.inset?'inset ':''}${s.x}px ${s.y}px ${s.blur}px ${s.spread}px rgba(${r}, ${g}, ${b}, ${Number(s.opacity.toFixed(3))})`}
export function cssClamp(minSize:number,maxSize:number,minViewport:number,maxViewport:number,unit='px'){if(![minSize,maxSize,minViewport,maxViewport].every(Number.isFinite))throw new Error('All clamp values must be finite numbers.');if(maxViewport<=minViewport)throw new Error('Maximum viewport must be greater than minimum viewport.');if(maxSize<minSize)throw new Error('Maximum size must be at least the minimum size.');const slope=(maxSize-minSize)/(maxViewport-minViewport),vw=slope*100,intercept=minSize-slope*minViewport;const n=(v:number)=>Number(v.toFixed(4));return{css:`clamp(${n(minSize)}${unit}, calc(${n(intercept)}${unit} + ${n(vw)}vw), ${n(maxSize)}${unit})`,slope:n(slope),intercept:n(intercept),vwCoefficient:n(vw)}}
export function parseDelimitedText(input:string,delimiter?:string){const first=input.split(/\r?\n/,1)[0]??'',sep=delimiter??(first.includes('\t')?'\t':first.includes(',')?',':';'),rows:string[][]=[];let row:string[]=[],cell='',quote=false;for(let i=0;i<input.length;i++){const c=input[i];if(quote){if(c==='"'&&input[i+1]==='"'){cell+='"';i++}else if(c==='"')quote=false;else cell+=c;continue}if(c==='"'){quote=true;continue}if(c===sep){row.push(cell);cell='';continue}if(c==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';continue}cell+=c}if(quote)throw new Error('Unclosed quoted field.');if(cell||row.length){row.push(cell.replace(/\r$/,''));rows.push(row)}return rows.filter(r=>r.some(c=>c.length>0))}
export function buildHtmlTable(input:string,options?:{header?:boolean;delimiter?:string;caption?:string;className?:string}){const rows=parseDelimitedText(input,options?.delimiter);if(!rows.length)throw new Error('Enter at least one row of table data.');const width=Math.max(...rows.map(r=>r.length)),norm=rows.map(r=>Array.from({length:width},(_,i)=>r[i]??'')),header=options?.header??true,attrs=options?.className?.trim()?` class="${esc(options.className.trim())}"`:'';const lines=[`<table${attrs}>`];if(options?.caption?.trim())lines.push(`  <caption>${esc(options.caption.trim())}</caption>`);if(header){lines.push('  <thead>','    <tr>',...norm[0].map(c=>`      <th scope="col">${esc(c)}</th>`),'    </tr>','  </thead>')}const body=header?norm.slice(1):norm;if(body.length){lines.push('  <tbody>');for(const row of body)lines.push('    <tr>',...row.map(c=>`      <td>${esc(c)}</td>`),'    </tr>');lines.push('  </tbody>')}lines.push('</table>');return lines.join('\n')}
