export type JsonDiffKind='added'|'removed'|'changed';
export interface JsonDiffEntry{path:string;kind:JsonDiffKind;left?:unknown;right?:unknown}

function isRecord(v:unknown):v is Record<string,unknown>{return typeof v==='object'&&v!==null&&!Array.isArray(v)}
export function sortJsonValue(value:unknown):unknown{if(Array.isArray(value))return value.map(sortJsonValue);if(isRecord(value)){const out:Record<string,unknown>={};for(const key of Object.keys(value).sort())out[key]=sortJsonValue(value[key]);return out}return value}
export function canonicalizeJson(input:string,compact=false):string{return JSON.stringify(sortJsonValue(JSON.parse(input)),null,compact?0:2)}
function samePrimitive(a:unknown,b:unknown){return Object.is(a,b)}
export function diffJsonValues(left:unknown,right:unknown,path='$',out:JsonDiffEntry[]=[]):JsonDiffEntry[]{if(Array.isArray(left)&&Array.isArray(right)){const n=Math.max(left.length,right.length);for(let i=0;i<n;i++){const p=`${path}[${i}]`;if(i>=left.length)out.push({path:p,kind:'added',right:right[i]});else if(i>=right.length)out.push({path:p,kind:'removed',left:left[i]});else diffJsonValues(left[i],right[i],p,out); }return out}if(isRecord(left)&&isRecord(right)){const keys=[...new Set([...Object.keys(left),...Object.keys(right)])].sort();for(const key of keys){const p=/^[A-Za-z_$][\w$]*$/.test(key)?`${path}.${key}`:`${path}[${JSON.stringify(key)}]`;if(!(key in left))out.push({path:p,kind:'added',right:right[key]});else if(!(key in right))out.push({path:p,kind:'removed',left:left[key]});else diffJsonValues(left[key],right[key],p,out)}return out}if(!samePrimitive(left,right))out.push({path,kind:'changed',left,right});return out}
export function compareJson(leftText:string,rightText:string){const left=JSON.parse(leftText),right=JSON.parse(rightText),changes=diffJsonValues(left,right);return{equal:changes.length===0,changes,counts:{added:changes.filter(x=>x.kind==='added').length,removed:changes.filter(x=>x.kind==='removed').length,changed:changes.filter(x=>x.kind==='changed').length}}}

function b64urlBytes(value:string):Uint8Array{const s=value.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(value.length/4)*4,'='),bin=atob(s),out=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)out[i]=bin.charCodeAt(i);return out}
function b64urlJson(value:string):unknown{return JSON.parse(new TextDecoder().decode(b64urlBytes(value)))}
function pemBlock(pem:string){const m=pem.trim().match(/-----BEGIN ([A-Z0-9 ]+)-----([\s\S]*?)-----END \1-----/);if(!m)throw new Error('Expected a PEM block.');const bin=atob(m[2].replace(/\s+/g,'')),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);return{label:m[1],bytes}}
export function inspectPemEnvelope(pem:string){const x=pemBlock(pem);return{label:x.label,byteLength:x.bytes.length}}

interface DerNode{tag:number;start:number;contentStart:number;end:number;children:DerNode[]}
function readDer(bytes:Uint8Array,offset=0):DerNode{if(offset>=bytes.length)throw new Error('Unexpected end of DER data.');const start=offset,tag=bytes[offset++];if(offset>=bytes.length)throw new Error('Invalid DER length.');let len=bytes[offset++];if(len&0x80){const count=len&0x7f;if(count===0||count>4||offset+count>bytes.length)throw new Error('Unsupported DER length.');len=0;for(let i=0;i<count;i++)len=(len<<8)|bytes[offset++]}const contentStart=offset,end=contentStart+len;if(end>bytes.length)throw new Error('DER element exceeds input.');const children:DerNode[]=[];if((tag&0x20)!==0){let p=contentStart;while(p<end){const child=readDer(bytes,p);children.push(child);p=child.end}if(p!==end)throw new Error('Invalid constructed DER element.')}return{tag,start,contentStart,end,children}}
function raw(bytes:Uint8Array,node:DerNode){return bytes.slice(node.contentStart,node.end)}
function full(bytes:Uint8Array,node:DerNode){return bytes.slice(node.start,node.end)}
export function decodeDerOid(bytes:Uint8Array):string{if(!bytes.length)return'';const first=Math.min(2,Math.floor(bytes[0]/40)),parts=[first,bytes[0]-first*40];let n=0;for(let i=1;i<bytes.length;i++){n=n*128+(bytes[i]&0x7f);if(!(bytes[i]&0x80)){parts.push(n);n=0}}if(n)parts.push(n);return parts.join('.')}
const OID_NAMES:Record<string,string>={'2.5.4.3':'CN','2.5.4.6':'C','2.5.4.7':'L','2.5.4.8':'ST','2.5.4.10':'O','2.5.4.11':'OU','1.2.840.113549.1.9.1':'emailAddress','1.2.840.113549.1.1.1':'RSA','1.2.840.113549.1.1.5':'sha1WithRSAEncryption','1.2.840.113549.1.1.11':'sha256WithRSAEncryption','1.2.840.113549.1.1.12':'sha384WithRSAEncryption','1.2.840.113549.1.1.13':'sha512WithRSAEncryption','1.2.840.10045.2.1':'EC','1.2.840.10045.4.3.2':'ecdsa-with-SHA256','1.2.840.10045.4.3.3':'ecdsa-with-SHA384'};
function oid(bytes:Uint8Array,node:DerNode){const value=decodeDerOid(raw(bytes,node));return OID_NAMES[value]??value}
function derText(bytes:Uint8Array,node:DerNode){const data=raw(bytes,node);if(node.tag===0x1e){let s='';for(let i=0;i+1<data.length;i+=2)s+=String.fromCharCode((data[i]<<8)|data[i+1]);return s}return new TextDecoder().decode(data)}
function parseName(bytes:Uint8Array,node:DerNode){const parts:string[]=[];for(const set of node.children)for(const seq of set.children){const [o,v]=seq.children;if(o&&v)parts.push(`${OID_NAMES[decodeDerOid(raw(bytes,o))]??decodeDerOid(raw(bytes,o))}=${derText(bytes,v)}`)}return parts.join(', ')}
function parseAlgorithm(bytes:Uint8Array,node:DerNode){const o=node.children[0];return o?oid(bytes,o):'unknown'}
function parseIntegerHex(bytes:Uint8Array,node:DerNode){return [...raw(bytes,node)].map(x=>x.toString(16).padStart(2,'0')).join('').replace(/^00/,'').toUpperCase()||'0'}
function parseTime(bytes:Uint8Array,node:DerNode){const s=derText(bytes,node);let iso='';if(node.tag===0x17){const y=Number(s.slice(0,2));iso=`${y>=50?1900+y:2000+y}-${s.slice(2,4)}-${s.slice(4,6)}T${s.slice(6,8)}:${s.slice(8,10)}:${s.slice(10,12)}Z`}else if(node.tag===0x18)iso=`${s.slice(0,4)}-${s.slice(4,6)}-${s.slice(6,8)}T${s.slice(8,10)}:${s.slice(10,12)}:${s.slice(12,14)}Z`;return iso||s}
function hex(bytes:Uint8Array){return[...bytes].map(x=>x.toString(16).padStart(2,'0')).join('').toUpperCase()}
async function sha256Fingerprint(bytes:Uint8Array){return hex(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))).match(/.{1,2}/g)?.join(':')??''}
function certificateParts(bytes:Uint8Array){const root=readDer(bytes);if(root.tag!==0x30||root.children.length<3)throw new Error('Not a recognizable X.509 certificate.');const tbs=root.children[0];let i=tbs.children[0]?.tag===0xa0?1:0;const serial=tbs.children[i++],sig=tbs.children[i++],issuer=tbs.children[i++],validity=tbs.children[i++],subject=tbs.children[i++],spki=tbs.children[i++];if(!serial||!sig||!issuer||!validity||!subject||!spki)throw new Error('Certificate fields are incomplete.');return{root,tbs,serial,sig,issuer,validity,subject,spki}}
export async function inspectCertificatePem(pem:string){const block=pemBlock(pem);if(block.label!=='CERTIFICATE')throw new Error('Expected a CERTIFICATE PEM block.');const p=certificateParts(block.bytes),from=p.validity.children[0]?parseTime(block.bytes,p.validity.children[0]):'',to=p.validity.children[1]?parseTime(block.bytes,p.validity.children[1]):'',now=Date.now();return{type:'X.509 certificate',subject:parseName(block.bytes,p.subject),issuer:parseName(block.bytes,p.issuer),serialNumber:parseIntegerHex(block.bytes,p.serial),validFrom:from,validTo:to,signatureAlgorithm:parseAlgorithm(block.bytes,p.sig),publicKeyAlgorithm:parseAlgorithm(block.bytes,p.spki.children[0]),sha256Fingerprint:await sha256Fingerprint(block.bytes),expired:to?now>Date.parse(to):false,notYetValid:from?now<Date.parse(from):false,byteLength:block.bytes.length}}
export function inspectCsrPem(pem:string){const block=pemBlock(pem);if(!/CERTIFICATE REQUEST/.test(block.label))throw new Error('Expected a CERTIFICATE REQUEST PEM block.');const root=readDer(block.bytes),info=root.children[0],sig=root.children[1];if(root.tag!==0x30||!info||!sig||info.children.length<3)throw new Error('Not a recognizable PKCS#10 CSR.');const subject=info.children[1],spki=info.children[2];return{type:'PKCS#10 certificate signing request',subject:parseName(block.bytes,subject),publicKeyAlgorithm:parseAlgorithm(block.bytes,spki.children[0]),signatureAlgorithm:parseAlgorithm(block.bytes,sig),byteLength:block.bytes.length}}
function spkiFromCertificate(bytes:Uint8Array){return full(bytes,certificateParts(bytes).spki)}
function rsaSpkiFromPem(key:string){const block=pemBlock(key);if(block.label==='PUBLIC KEY')return block.bytes;if(block.label==='CERTIFICATE')return spkiFromCertificate(block.bytes);throw new Error('RSA verification expects a PUBLIC KEY or CERTIFICATE PEM block.')}
export async function verifyJwtSignature(token:string,keyMaterial:string){const parts=token.trim().split('.');if(parts.length!==3)throw new Error('JWT must contain header, payload, and signature segments.');const header=b64urlJson(parts[0]) as Record<string,unknown>,payload=b64urlJson(parts[1]),alg=String(header.alg??'');const data=new TextEncoder().encode(`${parts[0]}.${parts[1]}`),signature=b64urlBytes(parts[2]);let valid=false,keyType='';const hmac:Record<string,string>={HS256:'SHA-256',HS384:'SHA-384',HS512:'SHA-512'},rsa:Record<string,string>={RS256:'SHA-256',RS384:'SHA-384',RS512:'SHA-512'};if(hmac[alg]){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(keyMaterial),{name:'HMAC',hash:hmac[alg]},false,['verify']);valid=await crypto.subtle.verify('HMAC',key,signature,data);keyType='HMAC secret'}else if(rsa[alg]){const key=await crypto.subtle.importKey('spki',rsaSpkiFromPem(keyMaterial),{name:'RSASSA-PKCS1-v1_5',hash:rsa[alg]},false,['verify']);valid=await crypto.subtle.verify('RSASSA-PKCS1-v1_5',key,signature,data);keyType='RSA public key'}else throw new Error(`Unsupported JWT alg ${alg||'(missing)'}. Supported: HS256/384/512 and RS256/384/512.`);return{valid,algorithm:alg,keyType,header,payload}}

export type SriAlgorithm='SHA-256'|'SHA-384'|'SHA-512';
export async function generateSri(data:BufferSource,algorithm:SriAlgorithm='SHA-384'){const digest=new Uint8Array(await crypto.subtle.digest(algorithm,data)),binary=String.fromCharCode(...digest),label=algorithm.toLowerCase().replace('-','');return`${label}-${btoa(binary)}`}
