function escHtml(s:string){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!))}
export interface CspOptions{defaultSrc?:string;scriptSrc?:string;styleSrc?:string;imgSrc?:string;fontSrc?:string;connectSrc?:string;frameSrc?:string;objectSrc?:string;baseUri?:string;formAction?:string;frameAncestors?:string;upgradeInsecureRequests?:boolean}
export function buildCsp(o:CspOptions){const dirs:[string,string|undefined][]=[['default-src',o.defaultSrc],['script-src',o.scriptSrc],['style-src',o.styleSrc],['img-src',o.imgSrc],['font-src',o.fontSrc],['connect-src',o.connectSrc],['frame-src',o.frameSrc],['object-src',o.objectSrc],['base-uri',o.baseUri],['form-action',o.formAction],['frame-ancestors',o.frameAncestors]],parts=dirs.filter(([,v])=>v?.trim()).map(([k,v])=>`${k} ${v!.trim()}`);if(o.upgradeInsecureRequests)parts.push('upgrade-insecure-requests');return parts.join('; ')+';'}
export interface PwaManifestInput{name:string;shortName?:string;description?:string;startUrl?:string;scope?:string;display?:'standalone'|'fullscreen'|'minimal-ui'|'browser';themeColor?:string;backgroundColor?:string;orientation?:string;icons?:{src:string;sizes:string;type?:string;purpose?:string}[]}
export function buildPwaManifest(o:PwaManifestInput){if(!o.name.trim())throw new Error('App name is required.');const out:Record<string,unknown>={name:o.name.trim(),short_name:(o.shortName||o.name).trim(),start_url:o.startUrl||'/',scope:o.scope||'/',display:o.display||'standalone'};if(o.description?.trim())out.description=o.description.trim();if(o.themeColor)out.theme_color=o.themeColor;if(o.backgroundColor)out.background_color=o.backgroundColor;if(o.orientation)out.orientation=o.orientation;if(o.icons?.length)out.icons=o.icons.filter(x=>x.src.trim()).map(x=>({src:x.src.trim(),sizes:x.sizes.trim()||'any',...(x.type?{type:x.type}:{}),...(x.purpose?{purpose:x.purpose}:{})}));return JSON.stringify(out,null,2)}
export function buildJsonLd(type:string,fields:Record<string,unknown>){const cleanType=type.trim()||'Thing',value:Record<string,unknown>={'@context':'https://schema.org','@type':cleanType};for(const [k,v] of Object.entries(fields))if(v!==''&&v!=null)value[k]=v;const json=JSON.stringify(value,null,2).replace(/<\//g,'<\\/');return`<script type="application/ld+json">\n${json}\n</script>`}
export function serpPreview(title:string,url:string,description:string){return{title:title.trim(),url:url.trim(),description:description.trim(),titleLength:[...title.trim()].length,descriptionLength:[...description.trim()].length,titleGuidance:[...title.trim()].length<=60?'within common display range':'may truncate in many results',descriptionGuidance:[...description.trim()].length<=160?'within common display range':'may truncate in many results'}}
export function slugify(input:string,separator='-',asciiOnly=true){let s=input.normalize('NFKD').replace(/[\u0300-\u036f]/g,'');if(asciiOnly)s=s.replace(/[^\x00-\x7F]/g,'');s=s.toLowerCase().replace(/['’]/g,'').replace(/[^a-z0-9]+/g,separator).replace(new RegExp(`^${escapeRegExp(separator)}+|${escapeRegExp(separator)}+$`,'g'),'').replace(new RegExp(`${escapeRegExp(separator)}{2,}`,'g'),separator);return s}
function escapeRegExp(s:string){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
export function buildHreflang(rows:{lang:string;url:string}[],xDefault=''){const lines=rows.filter(r=>r.lang.trim()&&r.url.trim()).map(r=>`<link rel="alternate" hreflang="${escHtml(r.lang.trim())}" href="${escHtml(r.url.trim())}">`);if(xDefault.trim())lines.push(`<link rel="alternate" hreflang="x-default" href="${escHtml(xDefault.trim())}">`);return lines.join('\n')}
export interface HarEntrySummary{method:string;url:string;status:number;mimeType:string;time:number;transferSize:number;domain:string}
export function parseHar(text:string){const data=JSON.parse(text),entries=data?.log?.entries;if(!Array.isArray(entries))throw new Error('HAR must contain log.entries.');const summaries:HarEntrySummary[]=entries.map((e:any)=>{let domain='';try{domain=new URL(String(e?.request?.url??'')).hostname}catch{}const headersSize=Number(e?.response?.headersSize)||0,bodySize=Number(e?.response?.bodySize)||0,encoded=Number(e?.response?.content?._transferSize)||0;return{method:String(e?.request?.method??''),url:String(e?.request?.url??''),status:Number(e?.response?.status)||0,mimeType:String(e?.response?.content?.mimeType??''),time:Number(e?.time)||0,transferSize:encoded>0?encoded:Math.max(0,headersSize)+Math.max(0,bodySize),domain}});const statusClasses:Record<string,number>={};for(const e of summaries){const k=e.status?`${Math.floor(e.status/100)}xx`:'unknown';statusClasses[k]=(statusClasses[k]??0)+1}const domains=[...new Set(summaries.map(e=>e.domain).filter(Boolean))].sort();return{entryCount:summaries.length,totalTimeMs:summaries.reduce((a,e)=>a+e.time,0),totalTransferBytes:summaries.reduce((a,e)=>a+e.transferSize,0),domains,statusClasses,entries:summaries.slice(0,500)}}
