export type PlotPoint={x:number;y:number|null};
type ExprNode={kind:'number';value:number}|{kind:'var'}|{kind:'unary';op:'+'|'-';value:ExprNode}|{kind:'binary';op:'+'|'-'|'*'|'/'|'^';left:ExprNode;right:ExprNode}|{kind:'fn';name:string;value:ExprNode};
const FUNCTIONS:Record<string,(x:number)=>number>={sin:Math.sin,cos:Math.cos,tan:Math.tan,asin:Math.asin,acos:Math.acos,atan:Math.atan,sqrt:Math.sqrt,abs:Math.abs,exp:Math.exp,ln:Math.log,log:Math.log10,floor:Math.floor,ceil:Math.ceil,round:Math.round};
class ExprParser{private i=0;constructor(private readonly s:string){}private ws(){while(/\s/.test(this.s[this.i]??''))this.i++}private eat(c:string){this.ws();if(this.s.startsWith(c,this.i)){this.i+=c.length;return true}return false}private number(){this.ws();const m=this.s.slice(this.i).match(/^(?:(?:\d+(?:\.\d*)?|\.\d+)(?:[eE][+-]?\d+)?)/);if(!m)return null;this.i+=m[0].length;return Number(m[0])}private ident(){this.ws();const m=this.s.slice(this.i).match(/^[A-Za-z_][A-Za-z0-9_]*/);if(!m)return'';this.i+=m[0].length;return m[0].toLowerCase()}parse(){if(!this.s.trim())throw new Error('Enter a function expression.');const n=this.add();this.ws();if(this.i!==this.s.length)throw new Error(`Unexpected token near “${this.s.slice(this.i,this.i+12)}”.`);return n}private add():ExprNode{let n=this.mul();for(;;){if(this.eat('+'))n={kind:'binary',op:'+',left:n,right:this.mul()};else if(this.eat('-'))n={kind:'binary',op:'-',left:n,right:this.mul()};else return n}}private mul():ExprNode{let n=this.unary();for(;;){if(this.eat('*'))n={kind:'binary',op:'*',left:n,right:this.unary()};else if(this.eat('/'))n={kind:'binary',op:'/',left:n,right:this.unary()};else return n}}private unary():ExprNode{if(this.eat('+'))return{kind:'unary',op:'+',value:this.unary()};if(this.eat('-'))return{kind:'unary',op:'-',value:this.unary()};return this.power()}private power():ExprNode{const n=this.primary();return this.eat('^')?{kind:'binary',op:'^',left:n,right:this.unary()}:n}private primary():ExprNode{this.ws();if(this.eat('(')){const n=this.add();if(!this.eat(')'))throw new Error('Missing closing parenthesis.');return n}const num=this.number();if(num!==null)return{kind:'number',value:num};const id=this.ident();if(!id)throw new Error(`Expected a number, x, or function near “${this.s.slice(this.i,this.i+12)}”.`);if(id==='x')return{kind:'var'};if(id==='pi')return{kind:'number',value:Math.PI};if(id==='e')return{kind:'number',value:Math.E};if(!FUNCTIONS[id])throw new Error(`Unsupported function “${id}”.`);if(!this.eat('('))throw new Error(`Function ${id} requires parentheses.`);const value=this.add();if(!this.eat(')'))throw new Error('Missing closing parenthesis.');return{kind:'fn',name:id,value}}}
function evalNode(n:ExprNode,x:number):number{switch(n.kind){case'number':return n.value;case'var':return x;case'unary':return n.op==='-'?-evalNode(n.value,x):evalNode(n.value,x);case'fn':return FUNCTIONS[n.name](evalNode(n.value,x));case'binary':{const a=evalNode(n.left,x),b=evalNode(n.right,x);if(n.op==='+')return a+b;if(n.op==='-')return a-b;if(n.op==='*')return a*b;if(n.op==='/')return a/b;return a**b}}}
export function compileExpression(expression:string){const ast=new ExprParser(expression).parse();return(x:number)=>evalNode(ast,x)}
export function sampleFunction(expression:string,xMin=-10,xMax=10,samples=401):PlotPoint[]{if(!Number.isFinite(xMin)||!Number.isFinite(xMax)||xMin>=xMax)throw new Error('x minimum must be smaller than x maximum.');samples=Math.max(25,Math.min(2001,Math.round(samples)));const fn=compileExpression(expression),out:PlotPoint[]=[];for(let i=0;i<samples;i++){const x=xMin+(xMax-xMin)*i/(samples-1),raw=fn(x),y=Number.isFinite(raw)&&Math.abs(raw)<=1e12?raw:null;out.push({x,y})}return out}
export function parseCoefficients(input:string){const c=input.trim().split(/[\s,;]+/).filter(Boolean).map(Number);if(c.length<2||c.some(x=>!Number.isFinite(x)))throw new Error('Enter at least two finite coefficients, highest degree first.');while(c.length>1&&c[0]===0)c.shift();return c}
export function polynomialValue(coeffs:number[],x:number){return coeffs.reduce((y,c)=>y*x+c,0)}
export function samplePolynomial(coeffs:number[],xMin=-10,xMax=10,samples=401):PlotPoint[]{if(xMin>=xMax)throw new Error('x minimum must be smaller than x maximum.');return Array.from({length:samples},(_,i)=>{const x=xMin+(xMax-xMin)*i/(samples-1),y=polynomialValue(coeffs,x);return{x,y:Number.isFinite(y)&&Math.abs(y)<=1e12?y:null}})}
export function findPolynomialRealRoots(coeffs:number[],xMin=-10,xMax=10,steps=4000){if(xMin>=xMax)throw new Error('x minimum must be smaller than x maximum.');const roots:number[]=[],eps=1e-8,add=(x:number)=>{if(!roots.some(r=>Math.abs(r-x)<1e-5))roots.push(x)};let px=xMin,py=polynomialValue(coeffs,px);for(let i=1;i<=steps;i++){const x=xMin+(xMax-xMin)*i/steps,y=polynomialValue(coeffs,x);if(Math.abs(y)<eps)add(x);if(Number.isFinite(py)&&Number.isFinite(y)&&py*y<0){let a=px,b=x,fa=py;for(let j=0;j<60;j++){const m=(a+b)/2,fm=polynomialValue(coeffs,m);if(Math.abs(fm)<1e-12){a=b=m;break}if(fa*fm<=0)b=m;else{a=m;fa=fm}}add((a+b)/2)}px=x;py=y}return roots.sort((a,b)=>a-b)}
export function parseNumericMatrix(input:string){const rows=input.trim().split(/\r?\n/).filter(Boolean).map(line=>line.trim().split(/[\s,;]+/).filter(Boolean).map(Number));if(!rows.length||rows.some(r=>!r.length||r.some(v=>!Number.isFinite(v))))throw new Error('Enter a finite numeric matrix with one row per line.');const n=rows[0].length;if(rows.some(r=>r.length!==n))throw new Error('Every matrix row must have the same number of columns.');return rows}
export function solveLinearSystem(augmented:number[][]){if(!augmented.length||augmented[0].length<2)throw new Error('Enter an augmented matrix with at least one variable and a constants column.');const rows=augmented.length,cols=augmented[0].length,vars=cols-1;if(augmented.some(r=>r.length!==cols))throw new Error('Rows must have equal length.');const m=augmented.map(r=>r.slice()),eps=1e-10,pivots:number[]=[];let rr=0;for(let c=0;c<vars&&rr<rows;c++){let p=rr;for(let r=rr+1;r<rows;r++)if(Math.abs(m[r][c])>Math.abs(m[p][c]))p=r;if(Math.abs(m[p][c])<eps)continue;[m[p],m[rr]]=[m[rr],m[p]];const q=m[rr][c];for(let j=c;j<cols;j++)m[rr][j]/=q;for(let r=0;r<rows;r++)if(r!==rr){const f=m[r][c];if(Math.abs(f)>eps)for(let j=c;j<cols;j++)m[r][j]-=f*m[rr][j]}pivots.push(c);rr++}for(const row of m)for(let c=0;c<cols;c++)if(Math.abs(row[c])<eps)row[c]=0;const inconsistent=m.some(row=>row.slice(0,vars).every(v=>v===0)&&Math.abs(row[vars])>eps);if(inconsistent)return{kind:'inconsistent' as const,rref:m,rank:pivots.length,variables:vars,solution:null};if(pivots.length<vars)return{kind:'infinite' as const,rref:m,rank:pivots.length,variables:vars,solution:null};const solution=Array(vars).fill(0);for(let r=0;r<pivots.length;r++)solution[pivots[r]]=m[r][vars];return{kind:'unique' as const,rref:m,rank:pivots.length,variables:vars,solution}}
function logGamma(z:number){const p=[0.99999999999980993,676.5203681218851,-1259.1392167224028,771.32342877765313,-176.61502916214059,12.507343278686905,-0.13857109526572012,9.984369578019571e-6,1.5056327351493116e-7];if(z<.5)return Math.log(Math.PI)-Math.log(Math.sin(Math.PI*z))-logGamma(1-z);z-=1;let x=p[0];for(let i=1;i<p.length;i++)x+=p[i]/(z+i);const t=z+7.5;return.5*Math.log(2*Math.PI)+(z+.5)*Math.log(t)-t+Math.log(x)}
function betaCf(a:number,b:number,x:number){const MAX=200,EPS=3e-14,FPMIN=1e-300;let qab=a+b,qap=a+1,qam=a-1,c=1,d=1-qab*x/qap;if(Math.abs(d)<FPMIN)d=FPMIN;d=1/d;let h=d;for(let m=1;m<=MAX;m++){const m2=2*m;let aa=m*(b-m)*x/((qam+m2)*(a+m2));d=1+aa*d;if(Math.abs(d)<FPMIN)d=FPMIN;c=1+aa/c;if(Math.abs(c)<FPMIN)c=FPMIN;d=1/d;h*=d*c;aa=-(a+m)*(qab+m)*x/((a+m2)*(qap+m2));d=1+aa*d;if(Math.abs(d)<FPMIN)d=FPMIN;c=1+aa/c;if(Math.abs(c)<FPMIN)c=FPMIN;d=1/d;const del=d*c;h*=del;if(Math.abs(del-1)<EPS)break}return h}
function regularizedBeta(x:number,a:number,b:number){if(x<=0)return 0;if(x>=1)return 1;const bt=Math.exp(logGamma(a+b)-logGamma(a)-logGamma(b)+a*Math.log(x)+b*Math.log1p(-x));return x<(a+1)/(a+b+2)?bt*betaCf(a,b,x)/a:1-bt*betaCf(b,a,1-x)/b}
function gammaP(a:number,x:number){if(x<=0)return 0;const EPS=1e-14,MAX=300;if(x<a+1){let ap=a,sum=1/a,del=sum;for(let n=1;n<=MAX;n++){ap++;del*=x/ap;sum+=del;if(Math.abs(del)<Math.abs(sum)*EPS)break}return sum*Math.exp(-x+a*Math.log(x)-logGamma(a))}let b=x+1-a,c=1/1e-300,d=1/b,h=d;for(let i=1;i<=MAX;i++){const an=-i*(i-a);b+=2;d=an*d+b;if(Math.abs(d)<1e-300)d=1e-300;c=b+an/c;if(Math.abs(c)<1e-300)c=1e-300;d=1/d;const del=d*c;h*=del;if(Math.abs(del-1)<EPS)break}return 1-Math.exp(-x+a*Math.log(x)-logGamma(a))*h}
export function studentTCdf(t:number,df:number){if(!(df>0)||!Number.isFinite(t))throw new Error('t must be finite and degrees of freedom positive.');const x=df/(df+t*t),ib=regularizedBeta(x,df/2,.5);return t>=0?1-.5*ib:.5*ib}
export function chiSquareCdf(x:number,df:number){if(!(df>0))throw new Error('Degrees of freedom must be positive.');return x<=0?0:gammaP(df/2,x/2)}
export function inverseNormalCdf(p:number){if(!(p>0&&p<1))throw new Error('Probability must be between 0 and 1.');const a=[-39.69683028665376,220.9460984245205,-275.9285104469687,138.357751867269,-30.66479806614716,2.506628277459239],b=[-54.47609879822406,161.5858368580409,-155.6989798598866,66.80131188771972,-13.28068155288572],c=[-0.007784894002430293,-0.3223964580411365,-2.400758277161838,-2.549732539343734,4.374664141464968,2.938163982698783],d=[0.007784695709041462,0.3224671290700398,2.445134137142996,3.754408661907416],pl=.02425,ph=1-pl;let q,r;if(p<pl){q=Math.sqrt(-2*Math.log(p));return(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)}if(p>ph){q=Math.sqrt(-2*Math.log(1-p));return-(((((c[0]*q+c[1])*q+c[2])*q+c[3])*q+c[4])*q+c[5])/((((d[0]*q+d[1])*q+d[2])*q+d[3])*q+1)}q=p-.5;r=q*q;return(((((a[0]*r+a[1])*r+a[2])*r+a[3])*r+a[4])*r+a[5])*q/(((((b[0]*r+b[1])*r+b[2])*r+b[3])*r+b[4])*r+1)}
export function tCritical(confidence:number,df:number){if(!(confidence>0&&confidence<1))throw new Error('Confidence level must be between 0 and 1.');const target=(1+confidence)/2;let lo=0,hi=50;for(let i=0;i<100;i++){const mid=(lo+hi)/2;if(studentTCdf(mid,df)<target)lo=mid;else hi=mid}return(lo+hi)/2}
function validateProb(p:number){if(!(p>=0&&p<=1))throw new Error('Probability must be between 0 and 1.')}
export function binomialPmf(n:number,k:number,p:number){if(!Number.isInteger(n)||n<0||n>10000||!Number.isInteger(k)||k<0||k>n)throw new Error('Require 0 ≤ k ≤ n ≤ 10000 with integer n and k.');validateProb(p);if(p===0)return k===0?1:0;if(p===1)return k===n?1:0;return Math.exp(logGamma(n+1)-logGamma(k+1)-logGamma(n-k+1)+k*Math.log(p)+(n-k)*Math.log1p(-p))}
export function binomialRange(n:number,p:number,lower=0,upper=n){validateProb(p);lower=Math.max(0,Math.ceil(lower));upper=Math.min(n,Math.floor(upper));if(lower>upper)return 0;let sum=0;for(let k=lower;k<=upper;k++)sum+=binomialPmf(n,k,p);return Math.min(1,sum)}
export function poissonPmf(lambda:number,k:number){if(!(lambda>=0&&Number.isFinite(lambda))||!Number.isInteger(k)||k<0||k>100000)throw new Error('λ must be non-negative and k a non-negative integer.');if(lambda===0)return k===0?1:0;return Math.exp(k*Math.log(lambda)-lambda-logGamma(k+1))}
export function poissonRange(lambda:number,lower=0,upper=Math.max(0,Math.ceil(lambda+8*Math.sqrt(lambda+1)))){lower=Math.max(0,Math.ceil(lower));upper=Math.floor(upper);if(upper-lower>20000)throw new Error('Requested Poisson interval is too large for this browser calculator.');let sum=0;for(let k=lower;k<=upper;k++)sum+=poissonPmf(lambda,k);return Math.min(1,sum)}
export function parseNumberList(input:string){const a=input.trim().split(/[\s,;]+/).filter(Boolean).map(Number);if(!a.length||a.some(v=>!Number.isFinite(v)))throw new Error('Enter finite numbers separated by spaces, commas, or semicolons.');return a}
function quantileSorted(s:number[],q:number){const pos=(s.length-1)*q,lo=Math.floor(pos),hi=Math.ceil(pos),f=pos-lo;return s[lo]*(1-f)+s[hi]*f}
export function descriptiveStats(values:number[]){if(!values.length||values.some(v=>!Number.isFinite(v)))throw new Error('Provide finite numeric values.');const s=[...values].sort((a,b)=>a-b),n=s.length,mean=s.reduce((a,b)=>a+b,0)/n,ss=s.reduce((a,b)=>a+(b-mean)**2,0),variance=n>1?ss/(n-1):0,sd=Math.sqrt(variance),median=quantileSorted(s,.5),q1=quantileSorted(s,.25),q3=quantileSorted(s,.75);return{n,mean,median,min:s[0],max:s[n-1],q1,q3,iqr:q3-q1,variance,sd}}
export function meanConfidenceInterval(values:number[],confidence=.95){const d=descriptiveStats(values);if(d.n<2)throw new Error('Mean confidence intervals require at least two observations.');const critical=tCritical(confidence,d.n-1),se=d.sd/Math.sqrt(d.n),margin=critical*se;return{...d,confidence,critical,se,margin,lower:d.mean-margin,upper:d.mean+margin}}
export function proportionConfidenceInterval(successes:number,total:number,confidence=.95){if(!Number.isInteger(successes)||!Number.isInteger(total)||total<=0||successes<0||successes>total)throw new Error('Require integer successes with 0 ≤ successes ≤ total.');const z=inverseNormalCdf((1+confidence)/2),p=successes/total,z2=z*z,den=1+z2/total,center=(p+z2/(2*total))/den,margin=z*Math.sqrt(p*(1-p)/total+z2/(4*total*total))/den;return{successes,total,estimate:p,confidence,z,lower:Math.max(0,center-margin),upper:Math.min(1,center+margin),method:'Wilson score'}}
export function sampleSizeForProportion(confidence=.95,margin=.05,p=.5,population?:number){validateProb(p);if(!(margin>0&&margin<1))throw new Error('Margin of error must be between 0 and 1.');const z=inverseNormalCdf((1+confidence)/2),raw=z*z*p*(1-p)/(margin*margin);const adjusted=population&&population>0?raw/(1+(raw-1)/population):raw;return{z,raw,required:Math.ceil(adjusted)}}
export function sampleSizeForMean(confidence=.95,margin=1,sd=1){if(!(margin>0)||!(sd>0))throw new Error('Margin of error and standard deviation must be positive.');const z=inverseNormalCdf((1+confidence)/2),raw=(z*sd/margin)**2;return{z,raw,required:Math.ceil(raw)}}
export function oneSampleTTest(values:number[],mu0=0){const d=descriptiveStats(values);if(d.n<2||d.sd===0)throw new Error('t-test requires at least two observations with non-zero sample variation.');const se=d.sd/Math.sqrt(d.n),t=(d.mean-mu0)/se,df=d.n-1,p=Math.min(1,2*(1-studentTCdf(Math.abs(t),df)));return{kind:'one-sample' as const,n:d.n,mean:d.mean,sd:d.sd,mu0,t,df,pValue:p}}
export function welchTTest(a:number[],b:number[]){const A=descriptiveStats(a),B=descriptiveStats(b);if(A.n<2||B.n<2)throw new Error('Welch t-test requires at least two observations per group.');const va=A.variance/A.n,vb=B.variance/B.n,se2=va+vb;if(se2===0)throw new Error('Welch t-test is undefined when both groups have zero variance.');const t=(A.mean-B.mean)/Math.sqrt(se2),df=se2*se2/(va*va/(A.n-1)+vb*vb/(B.n-1)),p=Math.min(1,2*(1-studentTCdf(Math.abs(t),df)));return{kind:'welch' as const,nA:A.n,nB:B.n,meanA:A.mean,meanB:B.mean,t,df,pValue:p}}
export function chiSquareGoodness(observed:number[],expected:number[]){if(observed.length<2||observed.length!==expected.length||observed.some(v=>v<0||!Number.isFinite(v))||expected.some(v=>v<=0||!Number.isFinite(v)))throw new Error('Observed and expected frequency lists must have equal length, with non-negative observed and positive expected values.');const statistic=observed.reduce((s,o,i)=>s+(o-expected[i])**2/expected[i],0),df=observed.length-1,pValue=1-chiSquareCdf(statistic,df);return{statistic,df,pValue}}
export function chiSquareIndependence(matrix:number[][]){if(matrix.length<2||matrix[0]?.length<2||matrix.some(r=>r.length!==matrix[0].length||r.some(v=>v<0||!Number.isFinite(v))))throw new Error('Enter a rectangular contingency table with at least 2 rows and 2 columns of non-negative counts.');const rows=matrix.length,cols=matrix[0].length,rowTotals=matrix.map(r=>r.reduce((a,b)=>a+b,0)),colTotals=Array.from({length:cols},(_,c)=>matrix.reduce((s,r)=>s+r[c],0)),total=rowTotals.reduce((a,b)=>a+b,0);if(total<=0||rowTotals.some(v=>v===0)||colTotals.some(v=>v===0))throw new Error('Every row and column must have a positive total.');let statistic=0;const expected=matrix.map((r,i)=>r.map((_,j)=>rowTotals[i]*colTotals[j]/total));for(let i=0;i<rows;i++)for(let j=0;j<cols;j++)statistic+=(matrix[i][j]-expected[i][j])**2/expected[i][j];const df=(rows-1)*(cols-1),pValue=1-chiSquareCdf(statistic,df);return{statistic,df,pValue,expected,rowTotals,colTotals,total}}
export function histogram(values:number[],bins?:number){const d=descriptiveStats(values),count=Math.max(1,Math.min(100,Math.round(bins??Math.ceil(Math.log2(d.n)+1))));if(d.min===d.max)return{bins:[{lower:d.min-.5,upper:d.max+.5,count:d.n}],min:d.min,max:d.max};const width=(d.max-d.min)/count,out=Array.from({length:count},(_,i)=>({lower:d.min+i*width,upper:i===count-1?d.max:d.min+(i+1)*width,count:0}));for(const v of values){let i=Math.floor((v-d.min)/width);if(i>=count)i=count-1;out[i].count++}return{bins:out,min:d.min,max:d.max}}
export function scatterStats(xs:number[],ys:number[]){if(xs.length!==ys.length||xs.length<2||xs.some(v=>!Number.isFinite(v))||ys.some(v=>!Number.isFinite(v)))throw new Error('X and Y must contain the same number of finite values, with at least two pairs.');const n=xs.length,mx=xs.reduce((a,b)=>a+b,0)/n,my=ys.reduce((a,b)=>a+b,0)/n;let sxx=0,syy=0,sxy=0;for(let i=0;i<n;i++){const dx=xs[i]-mx,dy=ys[i]-my;sxx+=dx*dx;syy+=dy*dy;sxy+=dx*dy}if(sxx===0)throw new Error('Scatter regression requires variation in X.');const slope=sxy/sxx,intercept=my-slope*mx,r=syy===0?0:sxy/Math.sqrt(sxx*syy);return{n,slope,intercept,r,r2:r*r,points:xs.map((x,i)=>({x,y:ys[i]}))}}
export function parseCsv(text:string){const rows:string[][]=[];let row:string[]=[],cell='',quoted=false;for(let i=0;i<text.length;i++){const ch=text[i];if(quoted){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++}else if(ch==='"')quoted=false;else cell+=ch}else if(ch==='"')quoted=true;else if(ch===','){row.push(cell);cell=''}else if(ch==='\n'){row.push(cell);rows.push(row);row=[];cell=''}else if(ch!=='\r')cell+=ch}row.push(cell);if(row.some(x=>x.length)||!rows.length)rows.push(row);if(quoted)throw new Error('CSV contains an unterminated quoted field.');return rows.filter(r=>r.some(x=>x.trim().length))}
export function csvNumericSeries(text:string,xColumn:string,yColumn:string){const rows=parseCsv(text);if(rows.length<2)throw new Error('CSV needs a header row and at least one data row.');const headers=rows[0].map(h=>h.trim()),xi=headers.indexOf(xColumn),yi=headers.indexOf(yColumn);if(xi<0||yi<0)throw new Error('Select existing X and Y columns.');const points:PlotPoint[]=[];for(const r of rows.slice(1)){const x=Number(r[xi]),y=Number(r[yi]);if(Number.isFinite(x)&&Number.isFinite(y))points.push({x,y})}if(points.length<2)throw new Error('Selected columns need at least two numeric row pairs.');return{headers,points}}
