export type SubtitleFormat='srt'|'vtt';
export interface SubtitleCue{index:number;id?:string;startMs:number;endMs:number;text:string;settings?:string}
export interface ParsedSubtitles{format:SubtitleFormat;cues:SubtitleCue[];warnings:string[]}
export interface SubtitleIssue{severity:'error'|'warning';cue:number;code:string;message:string}
const nl=(s:string)=>s.replace(/^\uFEFF/,'').replace(/\r\n?/g,'\n');
const pad=(n:number,w=2)=>String(n).padStart(w,'0');
export function parseTimecode(value:string):number{const s=value.trim().replace(',','.');const parts=s.split(':');if(parts.length<2||parts.length>3)throw new Error(`Invalid timecode: ${value}`);let h=0,m=0,sec=0;if(parts.length===3){h=Number(parts[0]);m=Number(parts[1]);sec=Number(parts[2]);if(!Number.isInteger(h)||h<0||!Number.isInteger(m)||m<0||m>=60)throw new Error(`Invalid timecode: ${value}`)}else{m=Number(parts[0]);sec=Number(parts[1]);if(!Number.isInteger(m)||m<0)throw new Error(`Invalid timecode: ${value}`)}if(!Number.isFinite(sec)||sec<0||sec>=60)throw new Error(`Invalid timecode: ${value}`);return Math.round((h*3600+m*60+sec)*1000)}
export function formatTimecode(ms:number,format:SubtitleFormat='srt'){ms=Math.max(0,Math.round(ms));const h=Math.floor(ms/3600000);ms-=h*3600000;const m=Math.floor(ms/60000);ms-=m*60000;const s=Math.floor(ms/1000),millis=ms-s*1000;return`${pad(h)}:${pad(m)}:${pad(s)}${format==='srt'?',':'.'}${pad(millis,3)}`}
function timingParts(line:string){const m=line.match(/^(.+?)\s+-->\s+(\S+)(?:\s+(.*))?$/);if(!m)throw new Error('Missing subtitle timing arrow.');return{start:parseTimecode(m[1]),end:parseTimecode(m[2]),settings:m[3]?.trim()||undefined}}
export function parseSubtitles(input:string,forced?:SubtitleFormat):ParsedSubtitles{const text=nl(input).trim();if(!text)throw new Error('Paste SRT or WebVTT subtitle text.');const detected:SubtitleFormat=forced??(/^WEBVTT(?:\s|$)/i.test(text)?'vtt':'srt'),lines=text.split('\n'),warnings:string[]=[],cues:SubtitleCue[]=[];let i=0;if(detected==='vtt'&&/^WEBVTT(?:\s|$)/i.test(lines[0]??'')){i++;while(i<lines.length&&lines[i].trim()!=='')i++}while(i<lines.length){while(i<lines.length&&lines[i].trim()==='')i++;if(i>=lines.length)break;const first=lines[i].trim();if(detected==='vtt'&&/^(NOTE|STYLE|REGION)(?:\s|$)/.test(first)){while(i<lines.length&&lines[i].trim()!=='')i++;continue}let id:string|undefined,timingLine=first;if(!first.includes('-->')){id=first;i++;if(i>=lines.length){warnings.push(`Ignored trailing cue identifier ${id}.`);break}timingLine=lines[i].trim()}if(!timingLine.includes('-->')){warnings.push(`Ignored malformed cue near line ${i+1}.`);while(i<lines.length&&lines[i].trim()!=='')i++;continue}let timing:{start:number;end:number;settings?:string};try{timing=timingParts(timingLine)}catch(e){warnings.push(e instanceof Error?e.message:'Invalid cue timing.');while(i<lines.length&&lines[i].trim()!=='')i++;continue}i++;const body:string[]=[];while(i<lines.length&&lines[i].trim()!==''){body.push(lines[i]);i++}const cueText=body.join('\n').trim();if(timing.end<=timing.start)warnings.push(`Cue ${cues.length+1} ends at or before its start.`);cues.push({index:cues.length+1,id,startMs:timing.start,endMs:timing.end,text:cueText,settings:timing.settings})}if(!cues.length)throw new Error('No subtitle cues could be parsed.');return{format:detected,cues,warnings}}
export function formatSrt(cues:SubtitleCue[]){return cues.map((c,i)=>`${i+1}\n${formatTimecode(c.startMs,'srt')} --> ${formatTimecode(c.endMs,'srt')}\n${c.text.trim()}`).join('\n\n')+'\n'}
export function formatVtt(cues:SubtitleCue[]){return'WEBVTT\n\n'+cues.map(c=>`${c.id&&!/^\d+$/.test(c.id)?`${c.id}\n`:''}${formatTimecode(c.startMs,'vtt')} --> ${formatTimecode(c.endMs,'vtt')}${c.settings?` ${c.settings}`:''}\n${c.text.trim()}`).join('\n\n')+'\n'}
export const formatSubtitles=(cues:SubtitleCue[],format:SubtitleFormat)=>format==='srt'?formatSrt(cues):formatVtt(cues);
export function stripCueMarkup(text:string){return text.replace(/<[^>]*>/g,'').replace(/\{\\[^}]+\}/g,'').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'")}
export function cleanCueText(text:string,stripMarkup=false){let v=text.replace(/[\u200B-\u200D\uFEFF]/g,'').split('\n').map(line=>line.trim().replace(/[ \t]+/g,' ')).filter(Boolean).join('\n');if(stripMarkup)v=stripCueMarkup(v);return v.trim()}
export function cleanSubtitleCues(cues:SubtitleCue[],opts:{stripMarkup?:boolean;sort?:boolean;fixInvalidDurations?:boolean}={}){const strip=opts.stripMarkup??false,sort=opts.sort??true,fix=opts.fixInvalidDurations??true;let removedEmpty=0,removedDuplicates=0,fixedDurations=0;let out=cues.map(c=>({...c,text:cleanCueText(c.text,strip)})).filter(c=>{if(!c.text){removedEmpty++;return false}return true});if(sort)out.sort((a,b)=>a.startMs-b.startMs||a.endMs-b.endMs);out=out.filter((c,i,a)=>{const p=a[i-1];if(p&&p.startMs===c.startMs&&p.endMs===c.endMs&&p.text===c.text){removedDuplicates++;return false}return true}).map(c=>{if(fix&&c.endMs<=c.startMs){fixedDurations++;return{...c,endMs:c.startMs+1000}}return c});out=out.map((c,i)=>({...c,index:i+1}));return{cues:out,removedEmpty,removedDuplicates,fixedDurations}}
export function validateSubtitleCues(cues:SubtitleCue[],opts:{maxCps?:number;maxLines?:number;maxCharsPerLine?:number;minDurationMs?:number}={}){const maxCps=opts.maxCps??20,maxLines=opts.maxLines??2,maxChars=opts.maxCharsPerLine??42,minDuration=opts.minDurationMs??500,issues:SubtitleIssue[]=[];cues.forEach((c,i)=>{const n=i+1,duration=c.endMs-c.startMs,plain=stripCueMarkup(c.text),chars=plain.replace(/\s/g,'').length,lines=plain.split('\n');if(c.startMs<0)issues.push({severity:'error',cue:n,code:'negative-start',message:'Cue starts before 00:00:00.'});if(duration<=0)issues.push({severity:'error',cue:n,code:'invalid-duration',message:'Cue end must be after cue start.'});else{if(duration<minDuration)issues.push({severity:'warning',cue:n,code:'short-duration',message:`Cue is shorter than ${(minDuration/1000).toFixed(1)} s.`});const cps=chars/(duration/1000);if(cps>maxCps)issues.push({severity:'warning',cue:n,code:'reading-speed',message:`Reading speed is ${cps.toFixed(1)} characters/s (limit ${maxCps}).`})}if(lines.length>maxLines)issues.push({severity:'warning',cue:n,code:'too-many-lines',message:`Cue has ${lines.length} lines (limit ${maxLines}).`});if(lines.some(x=>x.length>maxChars))issues.push({severity:'warning',cue:n,code:'long-line',message:`At least one line exceeds ${maxChars} characters.`});const p=cues[i-1];if(p&&c.startMs<p.endMs)issues.push({severity:'warning',cue:n,code:'overlap',message:`Cue overlaps the previous cue by ${p.endMs-c.startMs} ms.`})});return{issues,errorCount:issues.filter(x=>x.severity==='error').length,warningCount:issues.filter(x=>x.severity==='warning').length,cueCount:cues.length}}
export function shiftSubtitleCues(cues:SubtitleCue[],offsetMs:number,clampAtZero=true){if(!Number.isFinite(offsetMs))throw new Error('Offset must be finite.');return cues.map((c,i)=>({...c,index:i+1,startMs:clampAtZero?Math.max(0,c.startMs+offsetMs):c.startMs+offsetMs,endMs:clampAtZero?Math.max(0,c.endMs+offsetMs):c.endMs+offsetMs}))}
export function resyncSubtitleCues(cues:SubtitleCue[],targetFirstStartMs:number,targetLastStartMs:number){if(cues.length<2)throw new Error('At least two cues are required for drift resynchronization.');const first=cues[0].startMs,last=cues[cues.length-1].startMs;if(last===first)throw new Error('First and last cue anchors must be different.');const scale=(targetLastStartMs-targetFirstStartMs)/(last-first);if(!Number.isFinite(scale)||scale<=0)throw new Error('Target anchors must preserve increasing subtitle time.');const map=(t:number)=>targetFirstStartMs+(t-first)*scale;return{scale,cues:cues.map((c,i)=>({...c,index:i+1,startMs:Math.max(0,map(c.startMs)),endMs:Math.max(0,map(c.endMs))}))}}
export function convertSubtitleFrameRate(cues:SubtitleCue[],sourceFps:number,targetFps:number){if(!(sourceFps>0)||!(targetFps>0)||![sourceFps,targetFps].every(Number.isFinite))throw new Error('Frame rates must be positive finite numbers.');const scale=sourceFps/targetFps;return{scale,cues:cues.map((c,i)=>({...c,index:i+1,startMs:c.startMs*scale,endMs:c.endMs*scale}))}}
function reindex(cues:SubtitleCue[]){return cues.map((c,i)=>({...c,index:i+1}))}
export function mergeSubtitleCues(a:SubtitleCue[],b:SubtitleCue[],mode:'timeline'|'append'|'bilingual'='timeline',gapMs=500){if(!a.length||!b.length)throw new Error('Both subtitle tracks need at least one cue.');if(mode==='timeline')return reindex([...a.map(c=>({...c})),...b.map(c=>({...c}))].sort((x,y)=>x.startMs-y.startMs||x.endMs-y.endMs));if(mode==='append'){const aEnd=Math.max(...a.map(c=>c.endMs)),bStart=Math.min(...b.map(c=>c.startMs)),shift=aEnd+Math.max(0,gapMs)-bStart;return reindex([...a.map(c=>({...c})),...b.map(c=>({...c,startMs:c.startMs+shift,endMs:c.endMs+shift}))])}const n=Math.max(a.length,b.length),out:SubtitleCue[]=[];for(let i=0;i<n;i++){const x=a[i],y=b[i];if(x&&y)out.push({index:i+1,startMs:Math.min(x.startMs,y.startMs),endMs:Math.max(x.endMs,y.endMs),text:`${x.text}\n${y.text}`});else out.push({...((x??y)!),index:i+1})}return reindex(out)}
export function splitSubtitleCues(cues:SubtitleCue[],atMs:number,rebaseSecond=true){if(!(atMs>=0)||!Number.isFinite(atMs))throw new Error('Split time must be a non-negative finite value.');const first:SubtitleCue[]=[],second:SubtitleCue[]=[];for(const c of cues){if(c.endMs<=atMs)first.push({...c});else if(c.startMs>=atMs)second.push({...c});else{first.push({...c,endMs:atMs});second.push({...c,startMs:atMs})}}const rebased=second.map(c=>rebaseSecond?{...c,startMs:Math.max(0,c.startMs-atMs),endMs:Math.max(0,c.endMs-atMs)}:c);return{first:reindex(first),second:reindex(rebased)}}
export function subtitleToPlainText(cues:SubtitleCue[],mode:'lines'|'paragraph'='lines',stripMarkup=true){const parts=cues.map(c=>cleanCueText(c.text,stripMarkup)).filter(Boolean);return mode==='paragraph'?parts.join(' ').replace(/\s+/g,' ').trim():parts.join('\n')}
function wrapTranscriptLine(line:string,maxChars:number){const words=line.trim().split(/\s+/).filter(Boolean);if(!words.length)return[];const chunks:string[]=[];let cur='';for(const w of words){if(cur&&`${cur} ${w}`.length>maxChars){chunks.push(cur);cur=w}else cur=cur?`${cur} ${w}`:w}if(cur)chunks.push(cur);return chunks}
export function transcriptToSubtitleCues(text:string,opts:{startMs?:number;cueDurationMs?:number;gapMs?:number;maxChars?:number}={}){const start=opts.startMs??0,duration=opts.cueDurationMs??3000,gap=opts.gapMs??150,maxChars=opts.maxChars??84;if(start<0||duration<=0||gap<0||maxChars<10)throw new Error('Use a non-negative start/gap, positive duration, and max characters of at least 10.');const lines=nl(text).split('\n').map(x=>x.trim()).filter(Boolean),chunks=lines.flatMap(line=>wrapTranscriptLine(line,maxChars));if(!chunks.length)throw new Error('Paste transcript text with at least one non-empty line.');let t=start;return chunks.map((text,i)=>{const cue={index:i+1,startMs:t,endMs:t+duration,text};t+=duration+gap;return cue})}
export function analyzeSubtitleReadingSpeed(cues:SubtitleCue[],maxCps=20){const rows=cues.map((c,i)=>{const plain=stripCueMarkup(c.text),durationSec=Math.max(0,(c.endMs-c.startMs)/1000),chars=plain.replace(/\s/g,'').length,words=(plain.match(/\S+/g)??[]).length,cps=durationSec>0?chars/durationSec:Infinity,wpm=durationSec>0?words/durationSec*60:Infinity,overlapMs=i>0?Math.max(0,cues[i-1].endMs-c.startMs):0;return{cue:i+1,start:formatTimecode(c.startMs,'srt'),end:formatTimecode(c.endMs,'srt'),durationSec:Number(durationSec.toFixed(3)),characters:chars,words,cps:Number(cps.toFixed(2)),wpm:Number(wpm.toFixed(1)),overlapMs,flag:cps>maxCps||overlapMs>0||durationSec<=0}});return{cueCount:rows.length,flagged:rows.filter(r=>r.flag).length,averageCps:Number((rows.reduce((s,r)=>s+(Number.isFinite(r.cps)?r.cps:0),0)/Math.max(1,rows.filter(r=>Number.isFinite(r.cps)).length)).toFixed(2)),maxCps,rows}}
