import JSZip from'jszip';
import{extractDocx,inspectDocxMetadata,type DocxMetadata}from'./p13-office';
import{extractOdt,rtfToText}from'./mainstream-document';
import{extractOdp}from'./mainstream-odp';
import{parseTableInput,type TableData}from'./table-studio';
import{xlsxToTable,xmlTextToTable,parseTar,gunzipBytes}from'./file-format-conversion';
import{odsToJson}from'./mainstream-data';
import{parseYamlSubset,parseTomlSubset}from'./p11-developer';
import{xlsToJson,extractRar7z}from'./mainstream-lazy-runtimes';

export interface ViewerFileLike{name:string;size:number;type?:string;lastModified?:number;text():Promise<string>;arrayBuffer():Promise<ArrayBuffer>}
export interface OutlineItem{level:number;title:string;index:number}
export interface DocumentView{format:string;text:string;markdown:string;outline:OutlineItem[];metadata:Record<string,string>;wordCount:number;characterCount:number}
export interface SheetView{name:string;headers:string[];rows:string[][];truncated:boolean}
export interface SpreadsheetView{format:string;sheets:SheetView[];note?:string}
export interface SlideView{index:number;title:string;lines:string[]}
export interface PresentationView{format:string;slides:SlideView[]}
export interface ChapterView{index:number;title:string;text:string}
export interface EbookView{format:'EPUB';chapters:ChapterView[];metadata:Record<string,string>}
export interface StructuredView{format:string;value:unknown;raw:string;nodeCount:number;maxDepth:number}
export interface ArchiveEntryView{path:string;size:number|null;isFolder:boolean;modified?:string}
export interface ArchiveView{format:string;entries:ArchiveEntryView[];fileCount:number;folderCount:number;totalBytes:number|null;note?:string}
export interface SvgInspection{width:string;height:string;viewBox:string;elementCount:number;tagCounts:Record<string,number>;warnings:string[];sanitizedSvg:string}
export interface FontInspection{format:string;signature:string;tableCount:number|null;size:number;extension:string}

const MAX_SHEETS=30,MAX_ROWS=10000,MAX_COLUMNS=500,MAX_CHAPTERS=250;
const decoder=new TextDecoder();
const extension=(name:string)=>{const clean=name.toLowerCase().replace(/\?.*$/,'');if(clean.endsWith('.tar.gz'))return'tgz';const i=clean.lastIndexOf('.');return i>=0?clean.slice(i+1):''};
const decodeXml=(s:string)=>s.replace(/&#x([0-9a-f]+);/gi,(_,x)=>String.fromCodePoint(parseInt(x,16))).replace(/&#(\d+);/g,(_,x)=>String.fromCodePoint(Number(x))).replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/&apos;/gi,"'");
const stripHtml=(s:string)=>decodeXml(s.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/(?:p|div|h[1-6]|li|blockquote|tr|section)>/gi,'\n').replace(/<li[^>]*>/gi,'• ').replace(/<[^>]+>/g,' ')).replace(/[ \t]+\n/g,'\n').replace(/\n[ \t]+/g,'\n').replace(/[ \t]{2,}/g,' ').replace(/\n{3,}/g,'\n\n').trim();
const outlineFromMarkdown=(md:string)=>[...md.matchAll(/^(#{1,6})\s+(.+)$/gm)].map((m,index)=>({level:m[1].length,title:m[2].trim(),index}));
const words=(s:string)=>s.trim()?s.trim().split(/\s+/).length:0;
const asRecord=(value:unknown)=>Object.fromEntries(Object.entries(value as Record<string,unknown>).map(([k,v])=>[k,v==null?'':String(v)]));

export async function readDocument(file:ViewerFileLike):Promise<DocumentView>{const ext=extension(file.name);let text='',markdown='',metadata:Record<string,string>={};if(ext==='docx'){const bytes=await file.arrayBuffer();text=await extractDocx(bytes,'text');markdown=await extractDocx(bytes,'markdown');metadata=asRecord(await inspectDocxMetadata(bytes)as DocxMetadata)}else if(ext==='odt'){const view=await extractOdt(await file.arrayBuffer());text=view.text;markdown=view.markdown}else if(ext==='rtf'){text=rtfToText(await file.text());markdown=text}else if(ext==='html'||ext==='htm'){const raw=await file.text();text=stripHtml(raw);markdown=text}else if(ext==='md'||ext==='markdown'){markdown=await file.text();text=stripHtml(markdown.replace(/^#{1,6}\s+/gm,'').replace(/^[-*+]\s+/gm,'').replace(/^>\s?/gm,''))}else if(ext==='txt'||ext==='text'||!ext){text=await file.text();markdown=text}else throw new Error('Document Viewer supports DOCX, ODT, RTF, TXT, Markdown, and HTML files.');return{format:ext.toUpperCase()||'TEXT',text,markdown,outline:outlineFromMarkdown(markdown),metadata,wordCount:words(text),characterCount:text.length}}

function sharedStrings(xml:string){return[...xml.matchAll(/<si(?:\s[^>]*)?>([\s\S]*?)<\/si>/g)].map(m=>[...m[1].matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)].map(x=>decodeXml(x[1])).join(''))}
function columnIndex(ref:string){const letters=ref.match(/[A-Z]+/i)?.[0]?.toUpperCase()??'A';let n=0;for(const c of letters)n=n*26+c.charCodeAt(0)-64;return Math.max(0,n-1)}
function sheetFromXml(xml:string,shared:string[],name:string):SheetView{const rows:string[][]=[];let truncated=false;for(const rowMatch of xml.matchAll(/<row(?:\s[^>]*)?>([\s\S]*?)<\/row>/g)){if(rows.length>=MAX_ROWS){truncated=true;break}const row:string[]=[];for(const cellMatch of rowMatch[1].matchAll(/<c\b([^>]*)>([\s\S]*?)<\/c>/g)){const attrs=cellMatch[1],body=cellMatch[2],idx=columnIndex(attrs.match(/\br=["']([^"']+)["']/)?.[1]??`A${rows.length+1}`);if(idx>=MAX_COLUMNS){truncated=true;continue}while(row.length<idx)row.push('');const type=attrs.match(/\bt=["']([^"']+)["']/)?.[1]??'';let value='';if(type==='inlineStr')value=[...body.matchAll(/<t(?:\s[^>]*)?>([\s\S]*?)<\/t>/g)].map(x=>decodeXml(x[1])).join('');else{const raw=body.match(/<v(?:\s[^>]*)?>([\s\S]*?)<\/v>/)?.[1]??'';value=type==='s'?(shared[Number(raw)]??''):type==='b'?(raw==='1'?'TRUE':'FALSE'):decodeXml(raw)}row[idx]=value}rows.push(row)}if(!rows.length)return{name,headers:[],rows:[],truncated};const width=Math.min(MAX_COLUMNS,Math.max(...rows.map(r=>r.length))),normalized=rows.map(r=>Array.from({length:width},(_,i)=>r[i]??'')),headers=normalized[0].map((v,i)=>v||`Column ${i+1}`);return{name,headers,rows:normalized.slice(1),truncated}}
function resolveWorkbookTarget(target:string){const clean=target.replace(/^\//,'');if(clean.startsWith('xl/'))return clean;const parts=['xl',...clean.split('/')],out:string[]=[];for(const part of parts){if(!part||part==='.')continue;if(part==='..')out.pop();else out.push(part)}return out.join('/')}
async function xlsxSheets(data:ArrayBuffer):Promise<SheetView[]>{const zip=await JSZip.loadAsync(data),sharedFile=zip.file('xl/sharedStrings.xml'),shared=sharedFile?sharedStrings(await sharedFile.async('string')):[],workbook=await zip.file('xl/workbook.xml')?.async('string')??'',rels=await zip.file('xl/_rels/workbook.xml.rels')?.async('string')??'',relMap=new Map<string,string>();for(const r of rels.matchAll(/<Relationship\b[^>]*>/gi)){const id=r[0].match(/\bId=["']([^"']+)/i)?.[1],target=r[0].match(/\bTarget=["']([^"']+)/i)?.[1];if(id&&target)relMap.set(id,resolveWorkbookTarget(target))}const defs=[...workbook.matchAll(/<sheet\b[^>]*>/gi)].slice(0,MAX_SHEETS).map((m,i)=>({name:decodeXml(m[0].match(/\bname=["']([^"']*)/i)?.[1]??`Sheet ${i+1}`),rid:m[0].match(/\br:id=["']([^"']+)/i)?.[1]??''})),files=Object.keys(zip.files).filter(n=>/^xl\/worksheets\/sheet\d+\.xml$/i.test(n)).sort((a,b)=>Number(a.match(/sheet(\d+)/i)?.[1])-Number(b.match(/sheet(\d+)/i)?.[1]));const sheets:SheetView[]=[];if(defs.length){for(let i=0;i<defs.length;i++){const path=relMap.get(defs[i].rid)??files[i],entry=path?zip.file(path):null;if(entry)sheets.push(sheetFromXml(await entry.async('string'),shared,defs[i].name))}}else for(let i=0;i<Math.min(files.length,MAX_SHEETS);i++)sheets.push(sheetFromXml(await zip.file(files[i])!.async('string'),shared,`Sheet ${i+1}`));if(!sheets.length)sheets.push(sheetFromTable(await xlsxToTable(data),'Sheet1'));return sheets}
function sheetFromTable(table:TableData,name:string):SheetView{return{name,headers:table.headers.slice(0,MAX_COLUMNS),rows:table.rows.slice(0,MAX_ROWS).map(r=>r.slice(0,MAX_COLUMNS)),truncated:table.rows.length>MAX_ROWS||table.headers.length>MAX_COLUMNS}}
function odsCellText(body:string,attrs:string){const raw=attrs.match(/office:(?:string-value|value)=["']([^"']*)/i)?.[1];return decodeXml(raw??stripHtml(body))}
async function odsSheets(data:ArrayBuffer):Promise<SheetView[]>{const zip=await JSZip.loadAsync(data),xml=await zip.file('content.xml')?.async('string');if(!xml)throw new Error('No ODS content.xml was found.');const sheets:SheetView[]=[];for(const table of [...xml.matchAll(/<table:table\b([^>]*)>([\s\S]*?)<\/table:table>/gi)].slice(0,MAX_SHEETS)){const name=decodeXml(table[1].match(/table:name=["']([^"']*)/i)?.[1]??`Sheet ${sheets.length+1}`),rows:string[][]=[];let truncated=false;for(const r of table[2].matchAll(/<table:table-row\b[^>]*>([\s\S]*?)<\/table:table-row>/gi)){if(rows.length>=MAX_ROWS){truncated=true;break}const row:string[]=[];for(const c of r[1].matchAll(/<table:table-cell([^>]*)>([\s\S]*?)<\/table:table-cell>|<table:table-cell([^>]*)\/>/gi)){const attrs=c[1]??c[3]??'',repeat=Math.max(1,Math.min(MAX_COLUMNS-row.length,Number(attrs.match(/table:number-columns-repeated=["'](\d+)/i)?.[1]??1))),value=odsCellText(c[2]??'',attrs);for(let i=0;i<repeat&&row.length<MAX_COLUMNS;i++)row.push(value)}rows.push(row)}if(!rows.length){sheets.push({name,headers:[],rows:[],truncated});continue}const width=Math.min(MAX_COLUMNS,Math.max(...rows.map(r=>r.length))),normalized=rows.map(r=>Array.from({length:width},(_,i)=>r[i]??'')),headers=normalized[0].map((v,i)=>v||`Column ${i+1}`);sheets.push({name,headers,rows:normalized.slice(1),truncated})}if(!sheets.length){const fallback=JSON.parse(await odsToJson(data));const table=parseTableInput(JSON.stringify(fallback),{format:'json'}).data;sheets.push(sheetFromTable(table,'Sheet1'))}return sheets}
export async function readSpreadsheet(file:ViewerFileLike):Promise<SpreadsheetView>{const ext=extension(file.name);if(ext==='xlsx')return{format:'XLSX',sheets:await xlsxSheets(await file.arrayBuffer())};if(ext==='ods')return{format:'ODS',sheets:await odsSheets(await file.arrayBuffer())};if(ext==='xls'){const json=await xlsToJson(await file.arrayBuffer());return{format:'XLS',sheets:[sheetFromTable(parseTableInput(json,{format:'json'}).data,'Sheet1')],note:'Legacy XLS viewing currently exposes the first worksheet through the on-demand SheetJS reader.'}}const text=await file.text();if(ext==='csv'||ext==='tsv'||ext==='json'){const format=ext==='csv'?'csv':ext==='tsv'?'tsv':'json',table=parseTableInput(text,{format,hasHeader:true,trimCells:false}).data;return{format:ext.toUpperCase(),sheets:[sheetFromTable(table,'Data')]}}if(ext==='xml'){return{format:'XML',sheets:[sheetFromTable(xmlTextToTable(text),'Data')]}}throw new Error('Spreadsheet Viewer supports CSV, TSV, JSON tables, XML tables, XLS, XLSX, and ODS files.')}

function parseSlides(markdown:string):SlideView[]{const chunks=markdown.split(/(?=^#\s+)/m).map(s=>s.trim()).filter(Boolean),out:SlideView[]=[];for(const chunk of chunks){const lines=chunk.split(/\r?\n/),heading=lines.find(l=>/^#\s+/.test(l))?.replace(/^#\s+/,'').trim()??`Slide ${out.length+1}`,body=lines.filter(l=>!/^#{1,2}\s+/.test(l)&&l.trim()).map(l=>l.replace(/^[-*+]\s+/,'').trim());out.push({index:out.length+1,title:heading,lines:body})}return out}
async function pptxSlides(data:ArrayBuffer):Promise<SlideView[]>{const zip=await JSZip.loadAsync(data),files=Object.keys(zip.files).filter(n=>/^ppt\/slides\/slide\d+\.xml$/i.test(n)).sort((a,b)=>Number(a.match(/slide(\d+)/i)?.[1])-Number(b.match(/slide(\d+)/i)?.[1])),slides:SlideView[]=[];for(let i=0;i<files.length;i++){const xml=await zip.file(files[i])!.async('string'),paras=[...xml.matchAll(/<a:p(?:\s[^>]*)?>([\s\S]*?)<\/a:p>/g)].map(m=>[...m[1].matchAll(/<a:t(?:\s[^>]*)?>([\s\S]*?)<\/a:t>/g)].map(x=>decodeXml(x[1])).join('').trim()).filter(Boolean);slides.push({index:i+1,title:paras[0]||`Slide ${i+1}`,lines:paras.slice(1)})}return slides}
export async function readPresentation(file:ViewerFileLike):Promise<PresentationView>{const ext=extension(file.name);if(ext==='pptx')return{format:'PPTX',slides:await pptxSlides(await file.arrayBuffer())};if(ext==='odp')return{format:'ODP',slides:parseSlides((await extractOdp(await file.arrayBuffer())).markdown)};throw new Error('Presentation Viewer supports PPTX and ODP files.')}

function normalizePath(base:string,href:string){const parts=(base?`${base}/${href}`:href).split('/'),out:string[]=[];for(const p of parts){if(!p||p==='.')continue;if(p==='..')out.pop();else out.push(p)}return out.join('/')}
function dirname(p:string){return p.includes('/')?p.slice(0,p.lastIndexOf('/')):''}
function attr(tag:string,name:string){return decodeXml(tag.match(new RegExp(`\\b${name}=["']([^"']*)["']`,'i'))?.[1]??'')}
export async function readEbook(file:ViewerFileLike):Promise<EbookView>{if(extension(file.name)!=='epub')throw new Error('EPUB Reader supports EPUB files.');const zip=await JSZip.loadAsync(await file.arrayBuffer()),container=await zip.file('META-INF/container.xml')?.async('string');if(!container)throw new Error('EPUB container metadata is missing.');const opfPath=container.match(/<rootfile[^>]*full-path=["']([^"']+)/i)?.[1];if(!opfPath)throw new Error('Could not locate the EPUB package document.');const opf=await zip.file(opfPath)?.async('string');if(!opf)throw new Error('EPUB package document is missing.');const meta=(name:string)=>stripHtml(opf.match(new RegExp(`<${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${name}>`,'i'))?.[1]??''),metadata={title:meta('dc:title'),creator:meta('dc:creator'),language:meta('dc:language'),publisher:meta('dc:publisher'),description:meta('dc:description')},manifest=new Map<string,string>();for(const m of opf.matchAll(/<item\b[^>]*>/gi)){const id=attr(m[0],'id'),href=attr(m[0],'href');if(id&&href)manifest.set(id,href)}const base=dirname(opfPath),spine=[...opf.matchAll(/<itemref\b[^>]*>/gi)].map(m=>attr(m[0],'idref')).filter(Boolean).slice(0,MAX_CHAPTERS),chapters:ChapterView[]=[];for(const id of spine){const href=manifest.get(id),entry=href?zip.file(normalizePath(base,href)):null;if(!entry)continue;const html=await entry.async('string'),body=html.match(/<body(?:\s[^>]*)?>([\s\S]*?)<\/body>/i)?.[1]??html,text=stripHtml(body),title=stripHtml(body.match(/<h[1-3][^>]*>([\s\S]*?)<\/h[1-3]>/i)?.[1]??'')||`Chapter ${chapters.length+1}`;if(text)chapters.push({index:chapters.length+1,title,text})}if(!chapters.length)throw new Error('No readable EPUB spine documents were found.');return{format:'EPUB',chapters,metadata}}

function stats(value:unknown){let count=0,maxDepth=0;const visit=(v:unknown,d:number)=>{count++;maxDepth=Math.max(maxDepth,d);if(Array.isArray(v))for(const x of v)visit(x,d+1);else if(v&&typeof v==='object')for(const x of Object.values(v as Record<string,unknown>))visit(x,d+1)};visit(value,0);return{nodeCount:count,maxDepth}}
export async function readStructuredData(file:ViewerFileLike):Promise<StructuredView>{const ext=extension(file.name),raw=await file.text();let value:unknown;if(ext==='json')value=JSON.parse(raw);else if(ext==='yaml'||ext==='yml')value=parseYamlSubset(raw);else if(ext==='toml')value=parseTomlSubset(raw);else if(ext==='xml'){if(typeof DOMParser==='undefined')value={xml:raw};else{const doc=new DOMParser().parseFromString(raw,'application/xml');if(doc.querySelector('parsererror'))throw new Error('Invalid XML document.');const node=(el:Element):unknown=>{const children=[...el.children],attrs=Object.fromEntries([...el.attributes].map(a=>[`@${a.name}`,a.value]));if(!children.length)return Object.keys(attrs).length?{...attrs,'#text':el.textContent?.trim()??''}:el.textContent?.trim()??'';const out:Record<string,unknown>={...attrs};for(const child of children){const v=node(child),old=out[child.tagName];out[child.tagName]=old===undefined?v:Array.isArray(old)?[...old,v]:[old,v]}return out};value={[doc.documentElement.tagName]:node(doc.documentElement)}}}else throw new Error('Structured Data Viewer supports JSON, XML, YAML, and TOML files.');return{format:ext.toUpperCase(),value,raw,...stats(value)}}

export async function readArchive(file:ViewerFileLike):Promise<ArchiveView>{const ext=extension(file.name);let entries:ArchiveEntryView[]=[];if(ext==='zip'){const zip=await JSZip.loadAsync(await file.arrayBuffer());entries=Object.values(zip.files).map((e:any)=>({path:e.name,size:e.dir?0:(typeof e._data?.uncompressedSize==='number'?e._data.uncompressedSize:null),isFolder:Boolean(e.dir),modified:e.date instanceof Date?e.date.toISOString():undefined}))}else if(ext==='tar'||ext==='tgz'||ext==='gz'){let bytes=new Uint8Array(await file.arrayBuffer());if(ext==='tgz'||ext==='gz')bytes=await gunzipBytes(bytes);entries=parseTar(bytes).map(e=>({path:e.path,size:e.size,isFolder:false,modified:e.mtime?.toISOString()}))}else if(ext==='rar'||ext==='7z'){entries=(await extractRar7z(await file.arrayBuffer())).map(e=>({path:e.path,size:e.size,isFolder:false}))}else throw new Error('Archive Browser supports ZIP, TAR, TGZ/TAR.GZ, RAR, and 7Z archives.');entries.sort((a,b)=>a.path.localeCompare(b.path,undefined,{numeric:true}));const known=entries.every(e=>e.size!=null),total=known?entries.reduce((sum,e)=>sum+(e.size??0),0):null;return{format:ext==='tgz'||ext==='gz'?'TGZ':ext.toUpperCase(),entries,fileCount:entries.filter(e=>!e.isFolder).length,folderCount:entries.filter(e=>e.isFolder).length,totalBytes:total,note:ext==='rar'||ext==='7z'?'RAR/7Z browsing loads the pinned local libarchive runtime and reads regular files within browser safety limits.':undefined}}

function sanitizeSvgFallback(input:string){return input.replace(/<script\b[\s\S]*?<\/script>/gi,'').replace(/<foreignObject\b[\s\S]*?<\/foreignObject>/gi,'').replace(/\son[a-z]+\s*=\s*(["']).*?\1/gi,'').replace(/(?:href|xlink:href)\s*=\s*(["'])\s*javascript:[\s\S]*?\1/gi,'')}
export function inspectSvg(input:string):SvgInspection{let sanitized=sanitizeSvgFallback(input),width='',height='',viewBox='',elementCount=0,tagCounts:Record<string,number>={},warnings:string[]=[];if(typeof DOMParser!=='undefined'){const doc=new DOMParser().parseFromString(sanitized,'image/svg+xml');if(doc.querySelector('parsererror'))throw new Error('Invalid SVG document.');const root=doc.documentElement;if(root.tagName.toLowerCase()!=='svg')throw new Error('The document root is not <svg>.');for(const bad of [...doc.querySelectorAll('script,foreignObject,iframe,object,embed')])bad.remove();for(const el of [...doc.querySelectorAll('*')]){for(const a of [...el.attributes]){if(/^on/i.test(a.name)||/^(?:href|xlink:href)$/i.test(a.name)&&/^\s*javascript:/i.test(a.value))el.removeAttribute(a.name)}}width=root.getAttribute('width')??'';height=root.getAttribute('height')??'';viewBox=root.getAttribute('viewBox')??'';const all=[root,...doc.querySelectorAll('*')];elementCount=all.length;for(const el of all){const tag=el.tagName.toLowerCase();tagCounts[tag]=(tagCounts[tag]??0)+1}sanitized=new XMLSerializer().serializeToString(root)}else{const open=input.match(/<svg\b([^>]*)>/i)?.[1]??'';width=open.match(/\bwidth=["']([^"']+)/i)?.[1]??'';height=open.match(/\bheight=["']([^"']+)/i)?.[1]??'';viewBox=open.match(/\bviewBox=["']([^"']+)/i)?.[1]??'';const tags=[...sanitized.matchAll(/<([a-z][\w:-]*)\b/gi)].map(m=>m[1].toLowerCase());elementCount=tags.length;for(const tag of tags)tagCounts[tag]=(tagCounts[tag]??0)+1}if(!viewBox)warnings.push('No viewBox is declared; responsive scaling may be less predictable.');if(!width&&!height)warnings.push('No explicit width or height is declared.');if(/<script\b|<foreignObject\b|\son[a-z]+\s*=/i.test(input))warnings.push('Potentially active SVG content was removed from the preview.');return{width,height,viewBox,elementCount,tagCounts,warnings,sanitizedSvg:sanitized}}

function ascii(bytes:Uint8Array,start:number,len:number){return decoder.decode(bytes.subarray(start,start+len))}
export function inspectFont(bytes:Uint8Array,name='font'):FontInspection{if(bytes.length<12)throw new Error('Font file is too small to contain a supported font header.');const sig=ascii(bytes,0,4),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let format='',tables:number|null=null;if(bytes[0]===0&&bytes[1]===1&&bytes[2]===0&&bytes[3]===0){format='TrueType (TTF)';tables=view.getUint16(4)}else if(sig==='OTTO'){format='OpenType CFF (OTF)';tables=view.getUint16(4)}else if(sig==='wOFF'){format='Web Open Font Format (WOFF)';tables=view.getUint16(12)}else if(sig==='wOF2'){format='Web Open Font Format 2 (WOFF2)';tables=view.getUint16(12)}else if(sig==='ttcf'){format='TrueType Collection (TTC)'}else throw new Error('Unsupported font signature. Use TTF, OTF, WOFF, or WOFF2.');return{format,signature:[...bytes.subarray(0,4)].map(b=>b.toString(16).padStart(2,'0')).join(' '),tableCount:tables,size:bytes.byteLength,extension:extension(name)}}
