/** Perceptual color extraction, WCAG contrast and harmony utilities. */
export interface ExtractedColor{hex:string;r:number;g:number;b:number;h:number;s:number;l:number;dominancePercent:number;}
export type PaletteSortOption='dominance'|'brightness'|'hue';
export type HarmonyType='complementary'|'analogous'|'triadic'|'monochromatic';
export interface ColorHarmony{name:string;type:HarmonyType;colors:string[];}
export interface LabColor{l:number;a:number;b:number;}
export interface AccessiblePaletteRoles{background:string;text:string;accent:string;muted:string;backgroundTextContrast:number;accentContrast:number;}
export function rgbToHex(r:number,g:number,b:number):string{const h=(n:number)=>Math.max(0,Math.min(255,Math.round(Number.isFinite(n)?n:0))).toString(16).padStart(2,'0');return`#${h(r)}${h(g)}${h(b)}`;}
export function hexToRgb(hex:string):{r:number;g:number;b:number}|null{const clean=hex.trim().replace(/^#/,'');if(!/^(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(clean))return null;const x=clean.length===3?clean.split('').map(c=>c+c).join(''):clean;return{r:parseInt(x.slice(0,2),16),g:parseInt(x.slice(2,4),16),b:parseInt(x.slice(4,6),16)};}
export function rgbToHsl(r:number,g:number,b:number):{h:number;s:number;l:number}{const rn=Math.max(0,Math.min(255,r))/255,gn=Math.max(0,Math.min(255,g))/255,bn=Math.max(0,Math.min(255,b))/255,max=Math.max(rn,gn,bn),min=Math.min(rn,gn,bn);let h=0,s=0;const l=(max+min)/2;if(max!==min){const d=max-min;s=l>0.5?d/(2-max-min):d/(max+min);switch(max){case rn:h=(gn-bn)/d+(gn<bn?6:0);break;case gn:h=(bn-rn)/d+2;break;default:h=(rn-gn)/d+4;}h/=6;}return{h:Math.round(h*360)%360,s:Math.round(s*100),l:Math.round(l*100)};}
export function hslToRgb(h:number,s:number,l:number):{r:number;g:number;b:number}{const hn=((h%360)+360)%360/360,sn=Math.max(0,Math.min(100,s))/100,ln=Math.max(0,Math.min(100,l))/100;if(sn===0){const v=Math.round(ln*255);return{r:v,g:v,b:v};}const hue=(p:number,q:number,t:number)=>{if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p;};const q=ln<.5?ln*(1+sn):ln+sn-ln*sn,p=2*ln-q;return{r:Math.round(hue(p,q,hn+1/3)*255),g:Math.round(hue(p,q,hn)*255),b:Math.round(hue(p,q,hn-1/3)*255)};}
export function getRelativeLuminance(r:number,g:number,b:number):number{const c=[r,g,b].map(v=>{const x=Math.max(0,Math.min(255,v))/255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4;});return .2126*c[0]+.7152*c[1]+.0722*c[2];}
export function getContrastRatio(aHex:string,bHex:string):number{const a=hexToRgb(aHex),b=hexToRgb(bHex);if(!a||!b)return 1;const l1=getRelativeLuminance(a.r,a.g,a.b),l2=getRelativeLuminance(b.r,b.g,b.b);return Number(((Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05)).toFixed(2));}
export function getReadableTextColor(bg:string):'#000000'|'#ffffff'{return getContrastRatio(bg,'#000000')>=getContrastRatio(bg,'#ffffff')?'#000000':'#ffffff';}
function linearize(v:number){const x=v/255;return x<=.04045?x/12.92:((x+.055)/1.055)**2.4;}
export function rgbToLab(r:number,g:number,b:number):LabColor{const rn=linearize(r),gn=linearize(g),bn=linearize(b),x=(rn*.4124564+gn*.3575761+bn*.1804375)/.95047,y=(rn*.2126729+gn*.7151522+bn*.072175),z=(rn*.0193339+gn*.119192+bn*.9503041)/1.08883;const f=(t:number)=>t>.008856?Math.cbrt(t):7.787*t+16/116;const fx=f(x),fy=f(y),fz=f(z);return{l:116*fy-16,a:500*(fx-fy),b:200*(fy-fz)};}
export function deltaE76(a:LabColor,b:LabColor):number{return Math.hypot(a.l-b.l,a.a-b.a,a.b-b.b);}
function toExtracted(r:number,g:number,b:number,dominancePercent:number):ExtractedColor{const hsl=rgbToHsl(r,g,b);return{hex:rgbToHex(r,g,b),r,g,b,h:hsl.h,s:hsl.s,l:hsl.l,dominancePercent:Number(dominancePercent.toFixed(1))};}
function rgbDistance(a:ExtractedColor,b:ExtractedColor):number{return deltaE76(rgbToLab(a.r,a.g,a.b),rgbToLab(b.r,b.g,b.b));}
export function mergeSimilarExtractedColors(colors:ExtractedColor[],threshold=7):ExtractedColor[]{const merged:ExtractedColor[]=[];for(const color of[...colors].sort((a,b)=>b.dominancePercent-a.dominancePercent)){const match=merged.find(existing=>rgbDistance(existing,color)<=threshold);if(!match){merged.push({...color});continue;}const total=match.dominancePercent+color.dominancePercent,w=total>0?color.dominancePercent/total:.5;match.r=Math.round(match.r*(1-w)+color.r*w);match.g=Math.round(match.g*(1-w)+color.g*w);match.b=Math.round(match.b*(1-w)+color.b*w);Object.assign(match,toExtracted(match.r,match.g,match.b,total));}return merged.sort((a,b)=>b.dominancePercent-a.dominancePercent);}
/** Deterministic CIELAB k-means over sampled opaque pixels. */
export function extractPerceptualPaletteFromRgba(data:Uint8ClampedArray,width:number,height:number,paletteSize=5):ExtractedColor[]{const count=Math.max(1,Math.min(16,Math.floor(paletteSize)));if(width<=0||height<=0||data.length<width*height*4)return[];const maxSamples=24_000,step=Math.max(1,Math.ceil(width*height/maxSamples));const samples:{r:number;g:number;b:number;lab:LabColor}[]=[];for(let p=0;p<width*height;p+=step){const i=p*4;if(data[i+3]<96)continue;const r=data[i],g=data[i+1],b=data[i+2];samples.push({r,g,b,lab:rgbToLab(r,g,b)});}if(!samples.length)return[];const histogram=new Map<number,{r:number;g:number;b:number;count:number}>();for(const p of samples){const key=((p.r>>4)<<8)|((p.g>>4)<<4)|(p.b>>4),entry=histogram.get(key);if(entry){entry.r+=p.r;entry.g+=p.g;entry.b+=p.b;entry.count++;}else histogram.set(key,{r:p.r,g:p.g,b:p.b,count:1});}const seeds=[...histogram.values()].sort((a,b)=>b.count-a.count).slice(0,count).map(e=>({r:e.r/e.count,g:e.g/e.count,b:e.b/e.count,lab:rgbToLab(e.r/e.count,e.g/e.count,e.b/e.count)}));while(seeds.length<count&&seeds.length<samples.length){let best=samples[0],bestDistance=-1;for(const s of samples){const distance=Math.min(...seeds.map(c=>deltaE76(s.lab,c.lab)));if(distance>bestDistance){bestDistance=distance;best=s;}}seeds.push({...best});}let centers=seeds;let assignments=new Uint16Array(samples.length);for(let iteration=0;iteration<8;iteration++){const sums=centers.map(()=>({r:0,g:0,b:0,count:0}));for(let i=0;i<samples.length;i++){let best=0,bestD=Infinity;for(let c=0;c<centers.length;c++){const d=deltaE76(samples[i].lab,centers[c].lab);if(d<bestD){bestD=d;best=c;}}assignments[i]=best;const sum=sums[best];sum.r+=samples[i].r;sum.g+=samples[i].g;sum.b+=samples[i].b;sum.count++;}centers=centers.map((center,i)=>sums[i].count?{r:sums[i].r/sums[i].count,g:sums[i].g/sums[i].count,b:sums[i].b/sums[i].count,lab:rgbToLab(sums[i].r/sums[i].count,sums[i].g/sums[i].count,sums[i].b/sums[i].count)}:center);}
 const counts=new Array(centers.length).fill(0);for(const a of assignments)counts[a]++;const raw=centers.map((c,i)=>toExtracted(Math.round(c.r),Math.round(c.g),Math.round(c.b),counts[i]/samples.length*100)).filter((_,i)=>counts[i]>0);const merged=mergeSimilarExtractedColors(raw,6);const total=merged.reduce((s,c)=>s+c.dominancePercent,0)||100;for(const c of merged)c.dominancePercent=Number((c.dominancePercent/total*100).toFixed(1));return merged.slice(0,count);}
export function extractColorsFromCanvas(canvas:HTMLCanvasElement,paletteSize=5):ExtractedColor[]{const ctx=canvas.getContext('2d');if(!ctx||canvas.width<=0||canvas.height<=0)return[];const maxDim=220,scale=Math.min(1,maxDim/Math.max(canvas.width,canvas.height)),w=Math.max(1,Math.round(canvas.width*scale)),h=Math.max(1,Math.round(canvas.height*scale)),sample=document.createElement('canvas');sample.width=w;sample.height=h;const sctx=sample.getContext('2d',{willReadFrequently:true});if(!sctx)return[];sctx.drawImage(canvas,0,0,w,h);return extractPerceptualPaletteFromRgba(sctx.getImageData(0,0,w,h).data,w,h,paletteSize);}
export function sortExtractedPalette(colors:ExtractedColor[],sortBy:PaletteSortOption):ExtractedColor[]{const copy=[...colors];if(sortBy==='brightness')return copy.sort((a,b)=>b.l-a.l);if(sortBy==='hue')return copy.sort((a,b)=>a.h-b.h);return copy.sort((a,b)=>b.dominancePercent-a.dominancePercent);}
export function generateHarmonies(baseHex:string):ColorHarmony[]{const rgb=hexToRgb(baseHex);if(!rgb)return[];const hsl=rgbToHsl(rgb.r,rgb.g,rgb.b),make=(h:number,s:number,l:number)=>{const c=hslToRgb(h,s,l);return rgbToHex(c.r,c.g,c.b);},base=rgbToHex(rgb.r,rgb.g,rgb.b);return[{name:'Complementary',type:'complementary',colors:[base,make(hsl.h+180,hsl.s,hsl.l)]},{name:'Analogous',type:'analogous',colors:[make(hsl.h-30,hsl.s,hsl.l),base,make(hsl.h+30,hsl.s,hsl.l)]},{name:'Triadic',type:'triadic',colors:[base,make(hsl.h+120,hsl.s,hsl.l),make(hsl.h+240,hsl.s,hsl.l)]},{name:'Monochromatic',type:'monochromatic',colors:[make(hsl.h,hsl.s,Math.max(15,hsl.l-30)),make(hsl.h,hsl.s,Math.max(25,hsl.l-15)),base,make(hsl.h,hsl.s,Math.min(85,hsl.l+15)),make(hsl.h,hsl.s,Math.min(95,hsl.l+30))]}];}
export function suggestAccessibleColorRoles(colors:ExtractedColor[]):AccessiblePaletteRoles|null{if(!colors.length)return null;const sorted=[...colors].sort((a,b)=>b.l-a.l);const background=sorted[0].hex;const textCandidates=[...colors.map(c=>c.hex),'#000000','#ffffff'];const text=textCandidates.sort((a,b)=>getContrastRatio(background,b)-getContrastRatio(background,a))[0];const accents=colors.filter(c=>c.hex!==background).sort((a,b)=>{const aOk=getContrastRatio(background,a.hex)>=3?1:0,bOk=getContrastRatio(background,b.hex)>=3?1:0;return bOk-aOk||b.s-a.s||b.dominancePercent-a.dominancePercent;});const accent=accents[0]?.hex||text;const muted=sorted[Math.min(sorted.length-1,Math.floor(sorted.length/2))].hex;return{background,text,accent,muted,backgroundTextContrast:getContrastRatio(background,text),accentContrast:getContrastRatio(background,accent)};}
export function formatAsCssVariables(colors:ExtractedColor[]):string{return`:root {\n${colors.map((c,i)=>`  --color-${i+1}: ${c.hex}; /* RGB(${c.r}, ${c.g}, ${c.b}) */`).join('\n')}\n}`;}
