/** Color Palette Extraction & Harmony Utilities */
export interface ExtractedColor{hex:string;r:number;g:number;b:number;h:number;s:number;l:number;dominancePercent:number;}
export type PaletteSortOption='dominance'|'brightness'|'hue';
export type HarmonyType='complementary'|'analogous'|'triadic'|'monochromatic';
export interface ColorHarmony{name:string;type:HarmonyType;colors:string[];}

export function rgbToHex(r:number,g:number,b:number):string{const toHex=(n:number)=>Math.max(0,Math.min(255,Math.round(Number.isFinite(n)?n:0))).toString(16).padStart(2,'0');return`#${toHex(r)}${toHex(g)}${toHex(b)}`;}
export function hexToRgb(hex:string):{r:number;g:number;b:number}|null{const clean=hex.trim().replace(/^#/,'');if(!/^(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$/.test(clean))return null;const expanded=clean.length===3?clean.split('').map(c=>c+c).join(''):clean;return{r:parseInt(expanded.slice(0,2),16),g:parseInt(expanded.slice(2,4),16),b:parseInt(expanded.slice(4,6),16)};}
export function rgbToHsl(r:number,g:number,b:number):{h:number;s:number;l:number}{const rn=Math.max(0,Math.min(255,r))/255,gn=Math.max(0,Math.min(255,g))/255,bn=Math.max(0,Math.min(255,b))/255;const max=Math.max(rn,gn,bn),min=Math.min(rn,gn,bn);let h=0,s=0;const l=(max+min)/2;if(max!==min){const d=max-min;s=l>0.5?d/(2-max-min):d/(max+min);switch(max){case rn:h=(gn-bn)/d+(gn<bn?6:0);break;case gn:h=(bn-rn)/d+2;break;default:h=(rn-gn)/d+4;}h/=6;}return{h:Math.round(h*360)%360,s:Math.round(s*100),l:Math.round(l*100)};}
export function hslToRgb(h:number,s:number,l:number):{r:number;g:number;b:number}{const hn=((h%360)+360)%360/360,sn=Math.max(0,Math.min(100,s))/100,ln=Math.max(0,Math.min(100,l))/100;if(sn===0){const v=Math.round(ln*255);return{r:v,g:v,b:v};}const hue=(p:number,q:number,t:number)=>{if(t<0)t+=1;if(t>1)t-=1;if(t<1/6)return p+(q-p)*6*t;if(t<1/2)return q;if(t<2/3)return p+(q-p)*(2/3-t)*6;return p;};const q=ln<0.5?ln*(1+sn):ln+sn-ln*sn,p=2*ln-q;return{r:Math.round(hue(p,q,hn+1/3)*255),g:Math.round(hue(p,q,hn)*255),b:Math.round(hue(p,q,hn-1/3)*255)};}
export function getRelativeLuminance(r:number,g:number,b:number):number{const [rs,gs,bs]=[r,g,b].map(v=>{const x=v/255;return x<=0.03928?x/12.92:((x+0.055)/1.055)**2.4;});return 0.2126*rs+0.7152*gs+0.0722*bs;}
export function getContrastRatio(hex1:string,hex2:string):number{const a=hexToRgb(hex1),b=hexToRgb(hex2);if(!a||!b)return 1;const l1=getRelativeLuminance(a.r,a.g,a.b),l2=getRelativeLuminance(b.r,b.g,b.b);return Number(((Math.max(l1,l2)+0.05)/(Math.min(l1,l2)+0.05)).toFixed(2));}
export function getReadableTextColor(backgroundHex:string):'#000000'|'#ffffff'{return getContrastRatio(backgroundHex,'#000000')>=getContrastRatio(backgroundHex,'#ffffff')?'#000000':'#ffffff';}

interface Pixel{r:number;g:number;b:number;}
function medianCut(pixels:Pixel[],depth:number):Pixel[][]{if(depth===0||pixels.length<=1)return[pixels];let minR=255,maxR=0,minG=255,maxG=0,minB=255,maxB=0;for(const p of pixels){minR=Math.min(minR,p.r);maxR=Math.max(maxR,p.r);minG=Math.min(minG,p.g);maxG=Math.max(maxG,p.g);minB=Math.min(minB,p.b);maxB=Math.max(maxB,p.b);}const ranges={r:maxR-minR,g:maxG-minG,b:maxB-minB};const channel=(Object.entries(ranges).sort((a,b)=>b[1]-a[1])[0][0]) as keyof Pixel;const sorted=[...pixels].sort((a,b)=>a[channel]-b[channel]);const mid=Math.floor(sorted.length/2);return[...medianCut(sorted.slice(0,mid),depth-1),...medianCut(sorted.slice(mid),depth-1)];}
function rgbDistance(a:ExtractedColor,b:ExtractedColor):number{return Math.hypot(a.r-b.r,a.g-b.g,a.b-b.b);}

/** Merges near-duplicate quantization buckets and recomputes weighted colors. */
export function mergeSimilarExtractedColors(colors:ExtractedColor[],threshold=18):ExtractedColor[]{const merged:ExtractedColor[]=[];for(const color of [...colors].sort((a,b)=>b.dominancePercent-a.dominancePercent)){const match=merged.find(existing=>rgbDistance(existing,color)<=threshold);if(!match){merged.push({...color});continue;}const total=match.dominancePercent+color.dominancePercent;const weight=total>0?color.dominancePercent/total:0.5;match.r=Math.round(match.r*(1-weight)+color.r*weight);match.g=Math.round(match.g*(1-weight)+color.g*weight);match.b=Math.round(match.b*(1-weight)+color.b*weight);match.hex=rgbToHex(match.r,match.g,match.b);const hsl=rgbToHsl(match.r,match.g,match.b);match.h=hsl.h;match.s=hsl.s;match.l=hsl.l;match.dominancePercent=Number(total.toFixed(1));}return merged.sort((a,b)=>b.dominancePercent-a.dominancePercent);}

export function extractColorsFromCanvas(canvas:HTMLCanvasElement,paletteSize=5):ExtractedColor[]{const ctx=canvas.getContext('2d');if(!ctx||canvas.width<=0||canvas.height<=0)return[];const target=Math.max(1,Math.min(16,Math.floor(paletteSize)));const maxDim=140;const scale=Math.min(1,maxDim/Math.max(canvas.width,canvas.height));const w=Math.max(1,Math.round(canvas.width*scale)),h=Math.max(1,Math.round(canvas.height*scale));const sample=document.createElement('canvas');sample.width=w;sample.height=h;const sctx=sample.getContext('2d',{willReadFrequently:true});if(!sctx)return[];sctx.drawImage(canvas,0,0,w,h);const data=sctx.getImageData(0,0,w,h).data;const pixels:Pixel[]=[];for(let i=0;i<data.length;i+=4){if(data[i+3]>=128)pixels.push({r:data[i],g:data[i+1],b:data[i+2]});}if(!pixels.length)return[];const depth=Math.ceil(Math.log2(target));const buckets=medianCut(pixels,depth);const raw=buckets.filter(bucket=>bucket.length).map(bucket=>{let r=0,g=0,b=0;for(const p of bucket){r+=p.r;g+=p.g;b+=p.b;}r=Math.round(r/bucket.length);g=Math.round(g/bucket.length);b=Math.round(b/bucket.length);const hsl=rgbToHsl(r,g,b);return{hex:rgbToHex(r,g,b),r,g,b,h:hsl.h,s:hsl.s,l:hsl.l,dominancePercent:Number((bucket.length/pixels.length*100).toFixed(1))};});return mergeSimilarExtractedColors(raw).slice(0,target);}
export function sortExtractedPalette(colors:ExtractedColor[],sortBy:PaletteSortOption):ExtractedColor[]{const copy=[...colors];if(sortBy==='brightness')return copy.sort((a,b)=>b.l-a.l);if(sortBy==='hue')return copy.sort((a,b)=>a.h-b.h);return copy.sort((a,b)=>b.dominancePercent-a.dominancePercent);}
export function generateHarmonies(baseHex:string):ColorHarmony[]{const rgb=hexToRgb(baseHex);if(!rgb)return[];const hsl=rgbToHsl(rgb.r,rgb.g,rgb.b);const make=(h:number,s:number,l:number)=>{const c=hslToRgb(h,s,l);return rgbToHex(c.r,c.g,c.b);};const canonical=rgbToHex(rgb.r,rgb.g,rgb.b);return[{name:'Complementary',type:'complementary',colors:[canonical,make(hsl.h+180,hsl.s,hsl.l)]},{name:'Analogous',type:'analogous',colors:[make(hsl.h-30,hsl.s,hsl.l),canonical,make(hsl.h+30,hsl.s,hsl.l)]},{name:'Triadic',type:'triadic',colors:[canonical,make(hsl.h+120,hsl.s,hsl.l),make(hsl.h+240,hsl.s,hsl.l)]},{name:'Monochromatic',type:'monochromatic',colors:[make(hsl.h,hsl.s,Math.max(15,hsl.l-30)),make(hsl.h,hsl.s,Math.max(25,hsl.l-15)),canonical,make(hsl.h,hsl.s,Math.min(85,hsl.l+15)),make(hsl.h,hsl.s,Math.min(95,hsl.l+30))]}];}
export function formatAsCssVariables(colors:ExtractedColor[]):string{return`:root {\n${colors.map((c,i)=>`  --color-${i+1}: ${c.hex}; /* RGB(${c.r}, ${c.g}, ${c.b}) */`).join('\n')}\n}`;}
