import{formatHumanNumber,parseHumanNumber}from'./human-number';
export function parseNumberInput(input:string):number|null{return parseHumanNumber(input,{allowPercentSuffix:true});}
export function formatPreciseNumber(value:number,maxDecimals=6):string{if(Number.isNaN(value))return'Invalid number';if(!Number.isFinite(value))return value>0?'Infinity':'-Infinity';return formatHumanNumber(value,maxDecimals);}
const finite=(value:number)=>Number.isFinite(value)?value:0;
export function calculatePercentOf(percent:number,total:number){const p=finite(percent),t=finite(total),result=p/100*t;return{result,formatted:formatPreciseNumber(result),formula:`(${formatPreciseNumber(p)} ÷ 100) × ${formatPreciseNumber(t)} = ${formatPreciseNumber(result)}`};}
export function calculateWhatPercent(part:number,total:number):{result:number|null;formatted:string;formula:string;error?:string}{const p=finite(part),t=finite(total);if(t===0)return{result:null,formatted:'Undefined',formula:'Division by zero is undefined',error:'Cannot calculate percentage of zero (division by zero)'};const result=p/t*100;return{result,formatted:`${formatPreciseNumber(result)}%`,formula:`(${formatPreciseNumber(p)} ÷ ${formatPreciseNumber(t)}) × 100 = ${formatPreciseNumber(result)}%`};}
export function calculatePercentChange(fromVal:number,toVal:number):{result:number|null;formatted:string;formula:string;isIncrease:boolean;error?:string}{const from=finite(fromVal),to=finite(toVal);if(from===0)return{result:null,formatted:'Undefined',formula:'Division by initial value of zero is undefined',isIncrease:to>=0,error:'Initial value cannot be zero for percentage change calculation'};const diff=to-from,result=diff/Math.abs(from)*100,isIncrease=diff>=0,sign=isIncrease&&result!==0?'+':'';return{result,formatted:`${sign}${formatPreciseNumber(result)}%`,formula:`((${formatPreciseNumber(to)} - ${formatPreciseNumber(from)}) ÷ |${formatPreciseNumber(from)}|) × 100 = ${sign}${formatPreciseNumber(result)}%`,isIncrease};}
export function calculatePercentDifference(valueA:number,valueB:number):{result:number|null;formatted:string;formula:string;error?:string}{const a=finite(valueA),b=finite(valueB),den=(Math.abs(a)+Math.abs(b))/2;if(den===0)return{result:null,formatted:'Undefined',formula:'Average magnitude is zero',error:'Percentage difference is undefined when both values are zero'};const result=Math.abs(a-b)/den*100;return{result,formatted:`${formatPreciseNumber(result)}%`,formula:`|${formatPreciseNumber(a)} - ${formatPreciseNumber(b)}| ÷ ((|${formatPreciseNumber(a)}| + |${formatPreciseNumber(b)}|) ÷ 2) × 100 = ${formatPreciseNumber(result)}%`};}
export function calculateReversePercent(finalVal:number,percentChange:number,type:'increase'|'decrease'):{result:number|null;formatted:string;formula:string;error?:string}{const finalValue=finite(finalVal),change=finite(percentChange),factor=type==='increase'?1+change/100:1-change/100;if(factor===0)return{result:null,formatted:'Undefined',formula:'',error:type==='decrease'?'Cannot reverse a 100% decrease':'Invalid percentage resulting in division by zero'};const original=finalValue/factor;return{result:original,formatted:formatPreciseNumber(original),formula:`${formatPreciseNumber(finalValue)} ÷ (1 ${type==='increase'?'+':'-'} ${formatPreciseNumber(change)}%) = ${formatPreciseNumber(original)}`};}
export function calculatePercentagePointChange(fromPercent:number,toPercent:number):{points:number;relativePercent:number|null;formatted:string}{const from=finite(fromPercent),to=finite(toPercent),points=to-from,relativePercent=from===0?null:(to-from)/Math.abs(from)*100;return{points,relativePercent,formatted:`${points>=0&&points!==0?'+':''}${formatPreciseNumber(points)} pp${relativePercent===null?'':` (${relativePercent>=0&&relativePercent!==0?'+':''}${formatPreciseNumber(relativePercent)}% relative)`}`};}
export function calculateCompoundPercentChanges(base:number,changes:number[]):{result:number;netPercent:number|null;multiplier:number;formula:string}{const start=finite(base);let multiplier=1;for(const change of changes)multiplier*=1+finite(change)/100;const result=start*multiplier,netPercent=start===0?null:(result-start)/Math.abs(start)*100;return{result,netPercent,multiplier,formula:`${formatPreciseNumber(start)} × ${changes.map(c=>`(1 ${c>=0?'+':'-'} ${formatPreciseNumber(Math.abs(c))}%)`).join(' × ')} = ${formatPreciseNumber(result)}`};}
export function calculateCagr(startValue:number,endValue:number,periods:number):{result:number|null;formatted:string;formula:string;error?:string}{const start=finite(startValue),end=finite(endValue),n=finite(periods);if(start<=0||end<0||n<=0)return{result:null,formatted:'Undefined',formula:'',error:'CAGR requires a positive starting value, non-negative ending value, and positive number of periods'};const result=(Math.pow(end/start,1/n)-1)*100;return{result,formatted:`${formatPreciseNumber(result)}%`,formula:`((${formatPreciseNumber(end)} ÷ ${formatPreciseNumber(start)})^(1 ÷ ${formatPreciseNumber(n)}) - 1) × 100 = ${formatPreciseNumber(result)}%`};}
