export type DigestAlgorithm='SHA-256'|'SHA-384'|'SHA-512';
const te=new TextEncoder(),td=new TextDecoder();
const cryptoApi=()=>{const c=globalThis.crypto;if(!c?.subtle)throw new Error('Web Crypto is not available in this browser.');return c};
export function bytesToHex(bytes:Uint8Array){return[...bytes].map(b=>b.toString(16).padStart(2,'0')).join('')}
export function hexToBytes(value:string){const clean=value.trim().replace(/\s+/g,'');if(!clean||clean.length%2||!/^[0-9a-f]+$/i.test(clean))throw new Error('Enter an even number of hexadecimal characters.');const out=new Uint8Array(clean.length/2);for(let i=0;i<out.length;i++)out[i]=Number.parseInt(clean.slice(i*2,i*2+2),16);return out}
function toBase64(bytes:Uint8Array){let binary='';for(let i=0;i<bytes.length;i+=0x8000)binary+=String.fromCharCode(...bytes.subarray(i,i+0x8000));return btoa(binary)}
function fromBase64(value:string){const binary=atob(value),out=new Uint8Array(binary.length);for(let i=0;i<binary.length;i++)out[i]=binary.charCodeAt(i);return out}
function randomBytes(length:number){const out=new Uint8Array(length);cryptoApi().getRandomValues(out);return out}
export async function digestBytes(data:BufferSource,algorithm:DigestAlgorithm='SHA-256'){return bytesToHex(new Uint8Array(await cryptoApi().subtle.digest(algorithm,data)))}
export async function digestText(text:string,algorithm:DigestAlgorithm='SHA-256'){return digestBytes(te.encode(text),algorithm)}
export async function hmacHex(message:string,key:string,algorithm:DigestAlgorithm='SHA-256'){if(!key)throw new Error('Enter an HMAC key.');const subtle=cryptoApi().subtle,cryptoKey=await subtle.importKey('raw',te.encode(key),{name:'HMAC',hash:algorithm},false,['sign']);return bytesToHex(new Uint8Array(await subtle.sign('HMAC',cryptoKey,te.encode(message))))}
async function deriveAesKey(passphrase:string,salt:Uint8Array,iterations:number,usages:KeyUsage[]){if(passphrase.length<1)throw new Error('Enter a password.');const subtle=cryptoApi().subtle,material=await subtle.importKey('raw',te.encode(passphrase),'PBKDF2',false,['deriveKey']);return subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',salt,iterations},material,{name:'AES-GCM',length:256},false,usages)}
const DEFAULT_ITERATIONS=210000;
export async function encryptTextEnvelope(plaintext:string,passphrase:string,iterations=DEFAULT_ITERATIONS){const salt=randomBytes(16),iv=randomBytes(12),key=await deriveAesKey(passphrase,salt,iterations,['encrypt']),cipher=new Uint8Array(await cryptoApi().subtle.encrypt({name:'AES-GCM',iv},key,te.encode(plaintext)));return`TT1:${iterations}:${toBase64(salt)}:${toBase64(iv)}:${toBase64(cipher)}`}
export async function decryptTextEnvelope(envelope:string,passphrase:string){const parts=envelope.trim().split(':');if(parts.length!==5||parts[0]!=='TT1')throw new Error('This is not a Tiny Tools TT1 encrypted-text envelope.');const iterations=Number(parts[1]);if(!Number.isInteger(iterations)||iterations<10000||iterations>2000000)throw new Error('Encrypted-text iteration count is invalid.');const salt=fromBase64(parts[2]),iv=fromBase64(parts[3]),cipher=fromBase64(parts[4]);if(salt.length!==16||iv.length!==12||cipher.length<16)throw new Error('Encrypted-text envelope is malformed.');try{const key=await deriveAesKey(passphrase,salt,iterations,['decrypt']),plain=await cryptoApi().subtle.decrypt({name:'AES-GCM',iv},key,cipher);return td.decode(plain)}catch{throw new Error('Decryption failed. Check the password and encrypted text.')}}
const FILE_MAGIC=new Uint8Array([0x54,0x54,0x46,0x31]);
export async function encryptFileBytes(data:ArrayBuffer,passphrase:string,iterations=DEFAULT_ITERATIONS){const salt=randomBytes(16),iv=randomBytes(12),key=await deriveAesKey(passphrase,salt,iterations,['encrypt']),cipher=new Uint8Array(await cryptoApi().subtle.encrypt({name:'AES-GCM',iv},key,data)),out=new Uint8Array(36+cipher.length);out.set(FILE_MAGIC,0);new DataView(out.buffer).setUint32(4,iterations,false);out.set(salt,8);out.set(iv,24);out.set(cipher,36);return out}
export async function decryptFileBytes(data:ArrayBuffer,passphrase:string){const bytes=new Uint8Array(data);if(bytes.length<52||!FILE_MAGIC.every((v,i)=>bytes[i]===v))throw new Error('This is not a Tiny Tools TTF1 encrypted file.');const iterations=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength).getUint32(4,false);if(iterations<10000||iterations>2000000)throw new Error('Encrypted-file iteration count is invalid.');const salt=bytes.slice(8,24),iv=bytes.slice(24,36),cipher=bytes.slice(36);try{const key=await deriveAesKey(passphrase,salt,iterations,['decrypt']),plain=await cryptoApi().subtle.decrypt({name:'AES-GCM',iv},key,cipher);return new Uint8Array(plain)}catch{throw new Error('Decryption failed. Check the password and encrypted file.')}}
export function detectDigestAlgorithm(expected:string):DigestAlgorithm|null{const n=expected.trim().replace(/^0x/i,'').replace(/\s+/g,'').length;return n===64?'SHA-256':n===96?'SHA-384':n===128?'SHA-512':null}
export interface PasswordStrength{score:0|1|2|3|4;label:string;entropyBits:number;warnings:string[]}
const COMMON=['password','qwerty','letmein','welcome','admin','iloveyou','monkey','dragon','123456'];
export function analyzePasswordStrength(password:string):PasswordStrength{const warnings:string[]=[];if(!password)return{score:0,label:'Empty',entropyBits:0,warnings:['Enter a password to inspect it.']};let pool=0;if(/[a-z]/.test(password))pool+=26;if(/[A-Z]/.test(password))pool+=26;if(/\d/.test(password))pool+=10;if(/[^\p{L}\p{N}]/u.test(password))pool+=33;if(/[^\x00-\x7f]/.test(password))pool+=80;pool=Math.max(pool,1);let bits=password.length*Math.log2(pool),penalty=0;const lower=password.toLowerCase();if(password.length<12){warnings.push('Length below 12 characters limits resistance to guessing.');penalty+=12}if(/(.)\1{2,}/u.test(password)){warnings.push('Repeated characters reduce effective strength.');penalty+=10}if(COMMON.some(term=>lower.includes(term))){warnings.push('Contains a common password word or sequence.');penalty+=25}const seq='abcdefghijklmnopqrstuvwxyz0123456789',rev=[...seq].reverse().join('');for(let i=0;i<=lower.length-4;i++){const s=lower.slice(i,i+4);if(seq.includes(s)||rev.includes(s)){warnings.push('Contains an obvious ordered sequence.');penalty+=10;break}}bits=Math.max(0,Math.round((bits-penalty)*10)/10);let score:0|1|2|3|4=bits<30?0:bits<45?1:bits<65?2:bits<85?3:4;if(password.length<8)score=0;else if(password.length<12&&score>2)score=2;const labels=['Very weak','Weak','Fair','Strong','Very strong'];if(!warnings.length&&score<4)warnings.push('More length is usually the simplest way to improve a password.');return{score,label:labels[score],entropyBits:bits,warnings}}
export type PiiPatternType='email'|'phone'|'ipv4'|'payment-card';
export interface PiiPatternMatch{type:PiiPatternType;value:string;start:number;end:number}
function luhn(value:string){const digits=value.replace(/\D/g,'');if(digits.length<13||digits.length>19)return false;let sum=0,alt=false;for(let i=digits.length-1;i>=0;i--){let n=Number(digits[i]);if(alt){n*=2;if(n>9)n-=9}sum+=n;alt=!alt}return sum%10===0}
function validIpv4(value:string){const parts=value.split('.');return parts.length===4&&parts.every(p=>/^\d{1,3}$/.test(p)&&Number(p)<=255)}
export function findPiiPatterns(text:string):PiiPatternMatch[]{const found:Array<PiiPatternMatch&{priority:number}>=[],add=(type:PiiPatternType,re:RegExp,valid:(v:string)=>boolean=()=>true,priority=1)=>{for(const m of text.matchAll(re)){if(m.index===undefined||!valid(m[0]))continue;found.push({type,value:m[0],start:m.index,end:m.index+m[0].length,priority})}};add('email',/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,()=>true,4);add('payment-card',/(?:\d[ -]?){12,18}\d/g,luhn,5);add('ipv4',/\b(?:\d{1,3}\.){3}\d{1,3}\b/g,validIpv4,3);add('phone',/(?<![\w.])(?:\+?\d[\d ().-]{6,}\d)(?![\w.])/g,v=>{const digits=v.replace(/\D/g,'');return digits.length>=7&&digits.length<=15&&!luhn(v)},2);found.sort((a,b)=>a.start-b.start||b.priority-a.priority||b.end-a.end);const out:PiiPatternMatch[]=[];for(const item of found){if(out.some(x=>item.start<x.end&&item.end>x.start))continue;out.push({type:item.type,value:item.value,start:item.start,end:item.end})}return out}
export function redactPiiPatterns(text:string,matches=findPiiPatterns(text)){let out=text;for(const m of [...matches].sort((a,b)=>b.start-a.start))out=out.slice(0,m.start)+`[${m.type.toUpperCase()}]`+out.slice(m.end);return out}
function uuidFromBytes(bytes:Uint8Array){const h=bytesToHex(bytes);return`${h.slice(0,8)}-${h.slice(8,12)}-${h.slice(12,16)}-${h.slice(16,20)}-${h.slice(20)}`}
export function generateUuidV4(){const b=randomBytes(16);b[6]=(b[6]&0x0f)|0x40;b[8]=(b[8]&0x3f)|0x80;return uuidFromBytes(b)}
export function generateUuidV7(timestampMs=Date.now()){let ts=BigInt(Math.max(0,Math.floor(timestampMs)))&0xffffffffffffn;const b=new Uint8Array(16);for(let i=5;i>=0;i--){b[i]=Number(ts&255n);ts>>=8n}b.set(randomBytes(10),6);b[6]=(b[6]&0x0f)|0x70;b[8]=(b[8]&0x3f)|0x80;return uuidFromBytes(b)}
const CROCKFORD='0123456789ABCDEFGHJKMNPQRSTVWXYZ';
function encodeBase32(value:bigint,length:number){let out='';for(let i=0;i<length;i++){out=CROCKFORD[Number(value&31n)]+out;value>>=5n}return out}
export function generateUlid(timestampMs=Date.now()){const ts=BigInt(Math.max(0,Math.floor(timestampMs)))&0xffffffffffffn,r=randomBytes(10);let rand=0n;for(const byte of r)rand=(rand<<8n)|BigInt(byte);return encodeBase32(ts,10)+encodeBase32(rand,16)}
function decodeBase64Url(value:string){const normalized=value.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(value.length/4)*4,'=');return td.decode(fromBase64(normalized))}
export interface JwtInspection{header:Record<string,unknown>;payload:Record<string,unknown>;signaturePresent:boolean;algorithm:string|null;issuedAt:string|null;notBefore:string|null;expiresAt:string|null}
function epochClaim(value:unknown){return typeof value==='number'&&Number.isFinite(value)?new Date(value*1000).toISOString():null}
export function decodeJwt(token:string):JwtInspection{const parts=token.trim().split('.');if(parts.length!==3)throw new Error('A JWT must contain three dot-separated parts.');let header:Record<string,unknown>,payload:Record<string,unknown>;try{header=JSON.parse(decodeBase64Url(parts[0]));payload=JSON.parse(decodeBase64Url(parts[1]))}catch{throw new Error('JWT header or payload is not valid Base64URL JSON.')}if(!header||Array.isArray(header)||!payload||Array.isArray(payload))throw new Error('JWT header and payload must be JSON objects.');return{header,payload,signaturePresent:Boolean(parts[2]),algorithm:typeof header.alg==='string'?header.alg:null,issuedAt:epochClaim(payload.iat),notBefore:epochClaim(payload.nbf),expiresAt:epochClaim(payload.exp)}}
export type EpochUnit='auto'|'seconds'|'milliseconds';
export function epochToDate(value:string|number,unit:EpochUnit='auto'){const n=typeof value==='number'?value:Number(String(value).trim());if(!Number.isFinite(n))throw new Error('Enter a valid Unix timestamp.');const chosen=unit==='auto'?(Math.abs(n)<1e11?'seconds':'milliseconds'):unit,ms=chosen==='seconds'?n*1000:n,date=new Date(ms);if(!Number.isFinite(date.getTime()))throw new Error('Timestamp is outside the supported Date range.');return{milliseconds:Math.trunc(ms),seconds:Math.trunc(ms/1000),iso:date.toISOString(),local:date.toString(),detectedUnit:chosen}}
export function dateToEpoch(value:string){const ms=Date.parse(value);if(!Number.isFinite(ms))throw new Error('Enter a date/time that the browser can parse.');return{milliseconds:ms,seconds:Math.trunc(ms/1000),iso:new Date(ms).toISOString()}}
function digitValue(char:string){const code=char.toLowerCase().charCodeAt(0);if(code>=48&&code<=57)return code-48;if(code>=97&&code<=122)return code-87;return-1}
export function convertIntegerBase(value:string,fromBase:number,toBase:number){if(!Number.isInteger(fromBase)||fromBase<2||fromBase>36||!Number.isInteger(toBase)||toBase<2||toBase>36)throw new Error('Bases must be integers from 2 through 36.');let text=value.trim(),sign=1n;if(text.startsWith('-')){sign=-1n;text=text.slice(1)}else if(text.startsWith('+'))text=text.slice(1);if(!text)throw new Error('Enter an integer.');let n=0n;for(const char of text){const digit=digitValue(char);if(digit<0||digit>=fromBase)throw new Error(`“${char}” is not valid in base ${fromBase}.`);n=n*BigInt(fromBase)+BigInt(digit)}return(sign*n).toString(toBase).toUpperCase()}
export function textToHex(text:string){return bytesToHex(te.encode(text)).toUpperCase()}
export function hexToText(hex:string){return td.decode(hexToBytes(hex))}
const ENTITY_ENCODE:Record<string,string>={'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'};
export function encodeHtmlEntities(text:string){return text.replace(/[&<>"']/g,ch=>ENTITY_ENCODE[ch])}
const ENTITY_DECODE:Record<string,string>={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:'\u00a0'};
export function decodeHtmlEntities(text:string){return text.replace(/&(#x[0-9a-f]+|#\d+|amp|lt|gt|quot|apos|nbsp);/gi,(_,body:string)=>{if(body[0]==='#'){const hex=body[1]?.toLowerCase()==='x',n=Number.parseInt(body.slice(hex?2:1),hex?16:10);return Number.isFinite(n)&&n>=0&&n<=0x10ffff?String.fromCodePoint(n):_}return ENTITY_DECODE[body.toLowerCase()]??_})}
const MONTHS:Record<string,number>={jan:1,feb:2,mar:3,apr:4,may:5,jun:6,jul:7,aug:8,sep:9,oct:10,nov:11,dec:12},DAYS:Record<string,number>={sun:0,mon:1,tue:2,wed:3,thu:4,fri:5,sat:6};
function named(raw:string,names?:Record<string,number>){return names?raw.toLowerCase().replace(/[a-z]{3}/g,m=>String(names[m]??m)):raw}
function cronField(raw:string,min:number,max:number,names?:Record<string,number>,dow=false){raw=named(raw.trim(),names);if(!raw)throw new Error('Cron field cannot be empty.');const values=new Set<number>();for(const item of raw.split(',')){const pieces=item.split('/');if(pieces.length>2)throw new Error(`Invalid cron step: ${item}`);const step=pieces[1]===undefined?1:Number(pieces[1]);if(!Number.isInteger(step)||step<1)throw new Error(`Invalid cron step: ${item}`);const base=pieces[0];let start:number,end:number;if(base==='*'){start=min;end=max}else if(base.includes('-')){const pair=base.split('-');if(pair.length!==2)throw new Error(`Invalid cron range: ${item}`);start=Number(pair[0]);end=Number(pair[1])}else{start=Number(base);end=pieces[1]===undefined?start:max}if(!Number.isInteger(start)||!Number.isInteger(end)||start<min||end>max||start>end)throw new Error(`Cron value is outside ${min}–${max}: ${item}`);for(let v=start;v<=end;v+=step)values.add(dow&&v===7?0:v)}return values}
interface ParsedCron{minute:Set<number>;hour:Set<number>;day:Set<number>;month:Set<number>;weekday:Set<number>;dayAny:boolean;weekdayAny:boolean}
export function parseCron(expression:string):ParsedCron{const parts=expression.trim().split(/\s+/);if(parts.length!==5)throw new Error('Use a standard five-field cron expression: minute hour day month weekday.');return{minute:cronField(parts[0],0,59),hour:cronField(parts[1],0,23),day:cronField(parts[2],1,31),month:cronField(parts[3],1,12,MONTHS),weekday:cronField(parts[4],0,7,DAYS,true),dayAny:parts[2]==='*',weekdayAny:parts[4]==='*'}}
export function cronMatches(date:Date,cron:ParsedCron){const dom=cron.day.has(date.getDate()),dow=cron.weekday.has(date.getDay()),dayOk=cron.dayAny&&cron.weekdayAny?true:cron.dayAny?dow:cron.weekdayAny?dom:dom||dow;return cron.minute.has(date.getMinutes())&&cron.hour.has(date.getHours())&&cron.month.has(date.getMonth()+1)&&dayOk}
export function nextCronMatches(expression:string,start:Date=new Date(),count=8,maxMinutes=527040){const cron=parseCron(expression),cursor=new Date(start);cursor.setSeconds(0,0);cursor.setMinutes(cursor.getMinutes()+1);const out:Date[]=[];for(let i=0;i<maxMinutes&&out.length<count;i++,cursor.setMinutes(cursor.getMinutes()+1))if(cronMatches(cursor,cron))out.push(new Date(cursor));return out}
