import QRCode from 'qrcode';
export type QrDataType='text'|'url'|'wifi'|'email'|'phone'|'sms'|'vcard';export type QrErrorCorrectionLevel='L'|'M'|'Q'|'H';
export interface WifiQrConfig{ssid:string;password?:string;security:'WPA'|'WEP'|'nopass';hidden:boolean;}export interface EmailQrConfig{recipient:string;subject?:string;body?:string;}export interface SmsQrConfig{phoneNumber:string;message?:string;}export interface VCardQrConfig{firstName:string;lastName:string;phone?:string;email?:string;organization?:string;website?:string;}
const escapeWifi=(s:string)=>s.replace(/([\\;,":])/g,'\\$1');
const unescapeWifi=(s:string)=>s.replace(/\\([\\;,":])/g,'$1');
const escapeVCard=(s:string)=>s.replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
const unescapeVCard=(s:string)=>s.replace(/\\n/gi,'\n').replace(/\\([\\;,])/g,'$1');
export function formatWifiPayload(c:WifiQrConfig):string{return`WIFI:T:${c.security||'WPA'};S:${escapeWifi(c.ssid||'')};P:${c.password?escapeWifi(c.password):''};H:${c.hidden?'true':'false'};;`;}
export function formatEmailPayload(c:EmailQrConfig):string{const q=new URLSearchParams();if(c.subject)q.set('subject',c.subject);if(c.body)q.set('body',c.body);return`mailto:${c.recipient}${q.toString()?`?${q.toString()}`:''}`;}
export const formatPhonePayload=(p:string)=>`tel:${p.trim()}`;
export function formatSmsPayload(c:SmsQrConfig):string{const q=new URLSearchParams();if(c.message)q.set('body',c.message);return`sms:${c.phoneNumber.trim()}${q.toString()?`?${q.toString()}`:''}`;}
export function formatVCardPayload(c:VCardQrConfig):string{const lines=['BEGIN:VCARD','VERSION:3.0',`N:${escapeVCard(c.lastName||'')};${escapeVCard(c.firstName||'')};;;`,`FN:${escapeVCard(`${c.firstName||''} ${c.lastName||''}`.trim())}`];if(c.organization)lines.push(`ORG:${escapeVCard(c.organization)}`);if(c.phone)lines.push(`TEL;TYPE=CELL:${escapeVCard(c.phone)}`);if(c.email)lines.push(`EMAIL:${escapeVCard(c.email)}`);if(c.website)lines.push(`URL:${escapeVCard(c.website)}`);lines.push('END:VCARD');return lines.join('\r\n');}
export function getLuminance(hex:string):number{const clean=hex.trim().replace('#','');if(!/^[0-9a-f]{6}$/i.test(clean))return .5;const values=[0,2,4].map(i=>parseInt(clean.slice(i,i+2),16)/255).map(v=>v<=.04045?v/12.92:((v+.055)/1.055)**2.4);return values[0]*.2126+values[1]*.7152+values[2]*.0722;}
export function checkContrast(a:string,b:string):number{const l1=getLuminance(a),l2=getLuminance(b);return(Math.max(l1,l2)+.05)/(Math.min(l1,l2)+.05);}
export interface QrPayloadAssessment{byteLength:number;capacityBytes:number;usagePercent:number;quietZoneModules:number;contrastRatio:number;isWithinCapacity:boolean;warnings:string[];}
const CAPACITY:Record<QrErrorCorrectionLevel,number>={L:2953,M:2331,Q:1663,H:1273};
export function assessQrPayload(text:string,level:QrErrorCorrectionLevel='M',dark='#000000',light='#FFFFFF',margin=4):QrPayloadAssessment{const bytes=new TextEncoder().encode(text).length,capacity=CAPACITY[level],contrast=checkContrast(dark,light),warnings:string[]=[];if(bytes>capacity)warnings.push(`Payload exceeds the conservative byte capacity for error correction ${level}.`);if(margin<4)warnings.push('QR quiet zone should be at least 4 modules.');if(contrast<4.5)warnings.push('Foreground/background contrast is low for robust scanning.');return{byteLength:bytes,capacityBytes:capacity,usagePercent:Number((bytes/capacity*100).toFixed(1)),quietZoneModules:margin,contrastRatio:Number(contrast.toFixed(2)),isWithinCapacity:bytes<=capacity,warnings};}
function normalizedOptions(options:{width?:number;margin?:number;errorCorrectionLevel?:QrErrorCorrectionLevel;color?:{dark?:string;light?:string}}){return{width:Math.max(96,Math.min(4096,Math.round(options.width||320))),margin:Math.max(0,Math.min(32,Math.round(options.margin??4))),errorCorrectionLevel:(options.errorCorrectionLevel||'M') as QrErrorCorrectionLevel,color:{dark:options.color?.dark||'#000000',light:options.color?.light||'#FFFFFF'}};}
export async function generateQrDataUrl(text:string,options:{width?:number;margin?:number;errorCorrectionLevel?:QrErrorCorrectionLevel;color?:{dark?:string;light?:string}}):Promise<string>{const o=normalizedOptions(options);const a=assessQrPayload(text,o.errorCorrectionLevel,o.color.dark,o.color.light,o.margin);if(!a.isWithinCapacity)throw new Error(a.warnings[0]);return QRCode.toDataURL(text,o);}
export async function generateQrSvgString(text:string,options:{width?:number;margin?:number;errorCorrectionLevel?:QrErrorCorrectionLevel;color?:{dark?:string;light?:string}}):Promise<string>{const o=normalizedOptions(options);const a=assessQrPayload(text,o.errorCorrectionLevel,o.color.dark,o.color.light,o.margin);if(!a.isWithinCapacity)throw new Error(a.warnings[0]);return QRCode.toString(text,{...o,type:'svg'});}
export interface ParsedQrResult{raw:string;type:'url'|'wifi'|'email'|'phone'|'sms'|'vcard'|'text';parsedData?:{url?:string;wifi?:{ssid:string;password?:string;security:string;hidden:boolean};email?:{recipient:string;subject?:string;body?:string};phone?:string;sms?:{phone:string;message?:string};vcard?:{name:string;phone?:string;email?:string;org?:string}};warnings?:string[];}
function parseEscapedFields(body:string):Record<string,string>{const fields:string[]=[];let current='';let escaped=false;for(const ch of body){if(escaped){current+=`\\${ch}`;escaped=false;continue;}if(ch==='\\'){escaped=true;continue;}if(ch===';'){fields.push(current);current='';}else current+=ch;}if(current)fields.push(current);const out:Record<string,string>={};for(const field of fields){let split=-1,esc=false;for(let i=0;i<field.length;i++){if(esc){esc=false;continue;}if(field[i]==='\\'){esc=true;continue;}if(field[i]===':'){split=i;break;}}if(split>0)out[field.slice(0,split).toUpperCase()]=unescapeWifi(field.slice(split+1));}return out;}
function parseVCard(raw:string){const unfolded=raw.replace(/\r?\n[ \t]/g,'');const lines=unfolded.split(/\r?\n/);const get=(name:string)=>lines.find(l=>l.toUpperCase().startsWith(name))?.split(':').slice(1).join(':');return{name:unescapeVCard(get('FN:')||'Contact'),phone:get('TEL')?unescapeVCard(get('TEL')!):undefined,email:get('EMAIL')?unescapeVCard(get('EMAIL')!):undefined,org:get('ORG:')?unescapeVCard(get('ORG:')!):undefined};}
export function assessScannedUrl(url:string):string[]{const warnings:string[]=[];try{const parsed=new URL(url);if(!['http:','https:'].includes(parsed.protocol))warnings.push(`Non-web URL scheme: ${parsed.protocol}`);if(parsed.username||parsed.password)warnings.push('URL contains embedded credentials.');if(/(?:xn--)/i.test(parsed.hostname))warnings.push('Internationalized hostname uses punycode; verify the destination carefully.');if(/\d+\.\d+\.\d+\.\d+/.test(parsed.hostname))warnings.push('URL points directly to an IP address.');}catch{warnings.push('Malformed URL.');}return warnings;}
export function parseScannedQr(raw:string):ParsedQrResult{
  const t=raw.trim();
  if(/^WIFI:/i.test(t)){const f=parseEscapedFields(t.slice(5));return{raw,type:'wifi',parsedData:{wifi:{ssid:f.S||'Unknown Network',password:f.P||undefined,security:f.T||'WPA',hidden:(f.H||'').toLowerCase()==='true'}}};}
  if(/^(https?:\/\/|www\.)/i.test(t)){const url=t.startsWith('www.')?`https://${t}`:t;return{raw,type:'url',parsedData:{url},warnings:assessScannedUrl(url)};}
  if(/^mailto:/i.test(t)){const q=t.indexOf('?'),recipient=decodeURIComponent(t.slice(7,q<0?undefined:q)),p=new URLSearchParams(q<0?'':t.slice(q+1));return{raw,type:'email',parsedData:{email:{recipient,subject:p.get('subject')||undefined,body:p.get('body')||undefined}}};}
  if(/^tel:/i.test(t))return{raw,type:'phone',parsedData:{phone:t.slice(4)}};
  if(/^sms:/i.test(t)){const q=t.indexOf('?'),phone=t.slice(4,q<0?undefined:q),p=new URLSearchParams(q<0?'':t.slice(q+1));return{raw,type:'sms',parsedData:{sms:{phone,message:p.get('body')||undefined}}};}
  if(/^BEGIN:VCARD/i.test(t))return{raw,type:'vcard',parsedData:{vcard:parseVCard(t)}};
  return{raw,type:'text'};
}
