/** Local notepad persistence, Unicode-aware search/statistics and portable integrity helpers. */
export interface NoteDoc{id:string;title:string;content:string;updatedAt:number;isPinned?:boolean;tags?:string[];createdAt?:number;archived?:boolean;}
export interface NotepadStore{version:number;activeNoteId:string;notes:NoteDoc[];}export interface NoteSearchResult{note:NoteDoc;matchIndex:number;snippet:string;score?:number;}export const NOTEPAD_STORAGE_KEY='tiny_tools_notepad_store_v1';
const MAX_NOTES=1000,MAX_CHARS=2_000_000;function defaultStore():NotepadStore{return{version:1,activeNoteId:'note-welcome',notes:[{id:'note-welcome',title:'Welcome Scratchpad',content:'# Quick Scratchpad\n\n- Everything here is saved automatically in your browser.\n- Create, search, pin, tag, back up, and transfer notes locally.',updatedAt:Date.now(),createdAt:Date.now(),isPinned:true,tags:['welcome']}]};}export const defaultNotepadStore=defaultStore();const cloneDefault=()=>({version:1,activeNoteId:defaultNotepadStore.activeNoteId,notes:defaultNotepadStore.notes.map(n=>({...n,tags:n.tags?[...n.tags]:undefined}))});
function unique(preferred:string,used:Set<string>,fallback:string){let id=preferred.trim()||fallback;if(!used.has(id)){used.add(id);return id;}let n=2;while(used.has(`${id}-${n}`))n++;id=`${id}-${n}`;used.add(id);return id;}
export function sanitizeNotepadStore(raw:unknown):NotepadStore{if(!raw||typeof raw!=='object')return cloneDefault();try{const c=raw as Partial<NotepadStore>;if(!Array.isArray(c.notes)||!c.notes.length)return cloneDefault();const used=new Set<string>(),notes:NoteDoc[]=[];for(const value of c.notes.slice(0,MAX_NOTES)){if(!value||typeof value!=='object')continue;const n=value as Partial<NoteDoc>,tags=Array.isArray(n.tags)?[...new Set(n.tags.filter((x):x is string=>typeof x==='string').map(x=>x.trim()).filter(Boolean).slice(0,30))]:undefined,updatedAt=Number.isFinite(n.updatedAt)?Number(n.updatedAt):Date.now();notes.push({id:unique(typeof n.id==='string'?n.id:'',used,`note-${notes.length+1}`),title:typeof n.title==='string'&&n.title.trim()?n.title.trim().slice(0,500):'Untitled Note',content:typeof n.content==='string'?n.content.slice(0,MAX_CHARS):'',updatedAt,createdAt:Number.isFinite(n.createdAt)?Number(n.createdAt):updatedAt,isPinned:Boolean(n.isPinned),archived:Boolean(n.archived),...(tags!==undefined?{tags}:{})});}if(!notes.length)return cloneDefault();const requested=typeof c.activeNoteId==='string'?c.activeNoteId:'';return{version:1,activeNoteId:notes.find(n=>n.id===requested)?.id||notes[0].id,notes};}catch{return cloneDefault();}}
export function getStoredNotes():NotepadStore{if(typeof window==='undefined'||!window.localStorage)return cloneDefault();try{const raw=window.localStorage.getItem(NOTEPAD_STORAGE_KEY);return raw?sanitizeNotepadStore(JSON.parse(raw)):cloneDefault();}catch{return cloneDefault();}}export function saveNotes(store:NotepadStore):void{if(typeof window==='undefined'||!window.localStorage)return;try{window.localStorage.setItem(NOTEPAD_STORAGE_KEY,JSON.stringify(sanitizeNotepadStore(store)));}catch{}}
function wordSegments(text:string):string[]{const Segmenter=(Intl as unknown as{Segmenter?:new(locale?:string,options?:{granularity:'word'})=>{segment:(value:string)=>Iterable<{segment:string;isWordLike?:boolean}>}}).Segmenter;if(Segmenter)try{return[...new Segmenter(undefined,{granularity:'word'}).segment(text)].filter(x=>x.isWordLike!==false&&/[\p{L}\p{N}]/u.test(x.segment)).map(x=>x.segment);}catch{}return text.match(/[\p{L}\p{N}\p{M}]+/gu)||[];}
export function calculateNoteStats(text:string){const chars=text.length,lines=text?text.split('\n').length:0,words=wordSegments(text).length;return{words,chars,lines,readingSeconds:words?Math.max(1,Math.round(words/220*60)):0};}
function sortedNotes(notes:NoteDoc[]){return[...notes].sort((a,b)=>Number(b.isPinned)-Number(a.isPinned)||Number(a.archived)-Number(b.archived)||b.updatedAt-a.updatedAt);}
export function searchNotes(notes:NoteDoc[],query:string):NoteDoc[]{const needle=query.trim().toLocaleLowerCase(),sorted=sortedNotes(notes);return needle?sorted.filter(n=>`${n.title}\n${n.tags?.join(' ')||''}\n${n.content}`.toLocaleLowerCase().includes(needle)):sorted;}
export function searchNotesDetailed(notes:NoteDoc[],query:string):NoteSearchResult[]{const needle=query.trim().toLocaleLowerCase();if(!needle)return sortedNotes(notes).map(note=>({note,matchIndex:-1,snippet:'',score:0}));return searchNotes(notes,query).map(note=>{const title=note.title.toLocaleLowerCase(),tags=(note.tags||[]).join(' ').toLocaleLowerCase(),content=note.content.toLocaleLowerCase(),index=content.indexOf(needle),score=(title.includes(needle)?30:0)+(tags.includes(needle)?20:0)+(index>=0?10:0)+(note.isPinned?5:0),start=Math.max(0,index-45),end=index<0?0:Math.min(note.content.length,index+needle.length+75);return{note,matchIndex:index,score,snippet:index<0?'':`${start>0?'…':''}${note.content.slice(start,end).replace(/\s+/g,' ')}${end<note.content.length?'…':''}`};}).sort((a,b)=>(b.score||0)-(a.score||0)||Number(b.note.isPinned)-Number(a.note.isPinned)||b.note.updatedAt-a.note.updatedAt);}
export const serializeNotepadBackup=(store:NotepadStore)=>JSON.stringify(sanitizeNotepadStore(store),null,2);export function parseNotepadBackup(raw:string):NotepadStore|null{try{const p=JSON.parse(raw);return p&&typeof p==='object'&&Array.isArray((p as NotepadStore).notes)?sanitizeNotepadStore(p):null;}catch{return null;}}export function exportAllNotesMarkdown(store:NotepadStore):string{return sortedNotes(store.notes).map(n=>`# ${n.title}\n\n${n.tags?.length?`Tags: ${n.tags.map(t=>`#${t.replace(/\s+/g,'-')}`).join(' ')}\n\n`:''}${n.content}`).join('\n\n---\n\n');}
export function replaceInNote(content:string,search:string,replacement:string,replaceAll=true){if(!search)return{content,replacements:0};if(!replaceAll){const i=content.indexOf(search);return i<0?{content,replacements:0}:{content:content.slice(0,i)+replacement+content.slice(i+search.length),replacements:1};}const parts=content.split(search);return{content:parts.join(replacement),replacements:Math.max(0,parts.length-1)};}
/** Stable non-cryptographic fingerprint for change detection and backup integrity checks. */
export function computeNoteFingerprint(note:Pick<NoteDoc,'title'|'content'|'tags'>):string{let hash=2166136261;const text=`${note.title}\u0000${note.tags?.join('\u0001')||''}\u0000${note.content}`.normalize('NFC');for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619);}return(hash>>>0).toString(16).padStart(8,'0');}
export function findDuplicateNotes(notes:NoteDoc[]):Array<{fingerprint:string;noteIds:string[]}>{const map=new Map<string,string[]>();for(const note of notes){const fp=computeNoteFingerprint(note),ids=map.get(fp)||[];ids.push(note.id);map.set(fp,ids);}return[...map].filter(([,ids])=>ids.length>1).map(([fingerprint,noteIds])=>({fingerprint,noteIds}));}
export function filterNotesByTag(notes:NoteDoc[],tag:string):NoteDoc[]{const needle=tag.trim().toLocaleLowerCase();return sortedNotes(notes.filter(n=>!needle||(n.tags||[]).some(t=>t.toLocaleLowerCase()===needle)));}
export interface PortableNotepadBackup{format:'tiny-tools-notepad';version:2;createdAt:string;store:NotepadStore;fingerprints:Record<string,string>;}
export function serializePortableNotepadBackup(store:NotepadStore,date=new Date()):string{const clean=sanitizeNotepadStore(store),fingerprints=Object.fromEntries(clean.notes.map(n=>[n.id,computeNoteFingerprint(n)]));return JSON.stringify({format:'tiny-tools-notepad',version:2,createdAt:date.toISOString(),store:clean,fingerprints} satisfies PortableNotepadBackup,null,2);}export function parsePortableNotepadBackup(raw:string):NotepadStore|null{try{const b=JSON.parse(raw) as PortableNotepadBackup;if(b?.format!=='tiny-tools-notepad'||b.version!==2||!b.store)return null;const store=sanitizeNotepadStore(b.store);for(const note of store.notes)if(b.fingerprints?.[note.id]&&b.fingerprints[note.id]!==computeNoteFingerprint(note))return null;return store;}catch{return null;}}
