/** Quick Notepad persistence, search and portable backup utilities. */
export interface NoteDoc{id:string;title:string;content:string;updatedAt:number;isPinned?:boolean;tags?:string[];}
export interface NotepadStore{version:number;activeNoteId:string;notes:NoteDoc[];}
export interface NoteSearchResult{note:NoteDoc;matchIndex:number;snippet:string;}
export const NOTEPAD_STORAGE_KEY='tiny_tools_notepad_store_v1';
function createDefault():NotepadStore{return{version:1,activeNoteId:'note-welcome',notes:[{id:'note-welcome',title:'Welcome Scratchpad',content:'# Quick Scratchpad\n\n- Everything here is saved automatically in your browser.\n- Create, search, pin, tag, back up, and transfer notes locally.',updatedAt:Date.now(),isPinned:true,tags:['welcome']}]};}
export const defaultNotepadStore=createDefault();
const cloneDefault=()=>({version:1,activeNoteId:defaultNotepadStore.activeNoteId,notes:defaultNotepadStore.notes.map(n=>({...n,tags:[...(n.tags||[])]}))});
const MAX_NOTES=1000,MAX_CHARS=2_000_000;
function unique(preferred:string,used:Set<string>,fallback:string){let id=preferred.trim()||fallback;if(!used.has(id)){used.add(id);return id;}let n=2;while(used.has(`${id}-${n}`))n++;id=`${id}-${n}`;used.add(id);return id;}
export function sanitizeNotepadStore(raw:unknown):NotepadStore{if(!raw||typeof raw!=='object')return cloneDefault();try{const c=raw as Partial<NotepadStore>;if(!Array.isArray(c.notes)||!c.notes.length)return cloneDefault();const used=new Set<string>(),notes:NoteDoc[]=[];for(const value of c.notes.slice(0,MAX_NOTES)){if(!value||typeof value!=='object')continue;const note=value as Partial<NoteDoc>;notes.push({id:unique(typeof note.id==='string'?note.id:'',used,`note-${notes.length+1}`),title:typeof note.title==='string'&&note.title.trim()?note.title.trim().slice(0,500):'Untitled Note',content:typeof note.content==='string'?note.content.slice(0,MAX_CHARS):'',updatedAt:typeof note.updatedAt==='number'&&Number.isFinite(note.updatedAt)?note.updatedAt:Date.now(),isPinned:Boolean(note.isPinned),tags:Array.isArray(note.tags)?[...new Set(note.tags.filter((t):t is string=>typeof t==='string').map(t=>t.trim()).filter(Boolean).slice(0,30))]:[]});}if(!notes.length)return cloneDefault();const requested=typeof c.activeNoteId==='string'?c.activeNoteId:'';return{version:1,activeNoteId:notes.find(n=>n.id===requested)?.id||notes[0].id,notes};}catch{return cloneDefault();}}
export function getStoredNotes():NotepadStore{if(typeof window==='undefined'||!window.localStorage)return cloneDefault();try{const raw=window.localStorage.getItem(NOTEPAD_STORAGE_KEY);return raw?sanitizeNotepadStore(JSON.parse(raw)):cloneDefault();}catch{return cloneDefault();}}
export function saveNotes(store:NotepadStore):void{if(typeof window==='undefined'||!window.localStorage)return;try{window.localStorage.setItem(NOTEPAD_STORAGE_KEY,JSON.stringify(sanitizeNotepadStore(store)));}catch{}}
export function calculateNoteStats(text:string):{words:number;chars:number;lines:number;readingSeconds:number}{const chars=text.length,lines=text?text.split('\n').length:0,words=text.trim()?text.trim().split(/\s+/).filter(Boolean).length:0;return{words,chars,lines,readingSeconds:words?Math.max(1,Math.round(words/220*60)):0};}
export function searchNotes(notes:NoteDoc[],query:string):NoteDoc[]{const needle=query.trim().toLocaleLowerCase(),sorted=[...notes].sort((a,b)=>a.isPinned!==b.isPinned?(a.isPinned?-1:1):b.updatedAt-a.updatedAt);return needle?sorted.filter(note=>`${note.title}\n${note.tags?.join(' ')||''}\n${note.content}`.toLocaleLowerCase().includes(needle)):sorted;}
export function searchNotesDetailed(notes:NoteDoc[],query:string):NoteSearchResult[]{const needle=query.trim().toLocaleLowerCase();if(!needle)return searchNotes(notes,'').map(note=>({note,matchIndex:-1,snippet:''}));return searchNotes(notes,query).map(note=>{const hay=`${note.title}\n${note.content}`,lower=hay.toLocaleLowerCase(),index=lower.indexOf(needle),start=Math.max(0,index-45),end=Math.min(hay.length,index+needle.length+75);return{note,matchIndex:index,snippet:`${start>0?'…':''}${hay.slice(start,end).replace(/\s+/g,' ')}${end<hay.length?'…':''}`};});}
export function serializeNotepadBackup(store:NotepadStore):string{return JSON.stringify(sanitizeNotepadStore(store),null,2);}
export function parseNotepadBackup(raw:string):NotepadStore|null{try{const parsed=JSON.parse(raw);if(!parsed||typeof parsed!=='object'||!Array.isArray((parsed as NotepadStore).notes))return null;return sanitizeNotepadStore(parsed);}catch{return null;}}
export function exportAllNotesMarkdown(store:NotepadStore):string{return searchNotes(store.notes,'').map(note=>`# ${note.title}\n\n${note.tags?.length?`Tags: ${note.tags.map(t=>`#${t.replace(/\s+/g,'-')}`).join(' ')}\n\n`:''}${note.content}`).join('\n\n---\n\n');}
export function replaceInNote(content:string,search:string,replacement:string,replaceAll=true):{content:string;replacements:number}{if(!search)return{content,replacements:0};let count=0;if(!replaceAll){const i=content.indexOf(search);return i<0?{content,replacements:0}:{content:content.slice(0,i)+replacement+content.slice(i+search.length),replacements:1};}const pieces=content.split(search);count=Math.max(0,pieces.length-1);return{content:pieces.join(replacement),replacements:count};}
