export interface StableDecisionCriterion{name:string;weight:number;}
export interface StableDecisionOption{name:string;scores:number[];}
export interface StableDecisionRow{sourceIndex:number;name:string;score:number;contributions:number[];}
export interface DecisionSensitivityScenario{criterionIndex:number;criterionName:string;winnerSourceIndex:number|null;winnerName:string|null;winnerScore:number|null;changedWinner:boolean;}
const finite=(v:number,fallback=0)=>Number.isFinite(v)?v:fallback;const clamp=(v:number,min:number,max:number)=>Math.min(max,Math.max(min,v));const round=(v:number,d=3)=>{const f=10**d;return Math.round((v+Number.EPSILON)*f)/f};
export function normalizedDecisionWeights(criteria:StableDecisionCriterion[]):number[]{const raw=criteria.map(c=>Math.max(0,finite(c.weight)));const total=raw.reduce((a,b)=>a+b,0);return total>0?raw.map(v=>v/total):raw.map(()=>0);}
export function rankDecisionOptionsStable(criteria:StableDecisionCriterion[],options:StableDecisionOption[]):StableDecisionRow[]{const weights=normalizedDecisionWeights(criteria);return options.map((option,sourceIndex)=>{const contributions=weights.map((weight,index)=>clamp(finite(option.scores[index]),0,10)*weight);return{sourceIndex,name:option.name.trim()||'Untitled option',score:round(contributions.reduce((a,b)=>a+b,0)),contributions:contributions.map(v=>round(v))};}).sort((a,b)=>b.score-a.score||a.sourceIndex-b.sourceIndex);}
export function decisionWinnerMargin(rows:StableDecisionRow[]):number|null{return rows.length<2?null:round(rows[0].score-rows[1].score);}
export function analyzeDecisionSensitivity(criteria:StableDecisionCriterion[],options:StableDecisionOption[]):DecisionSensitivityScenario[]{const baseline=rankDecisionOptionsStable(criteria,options)[0]?.sourceIndex??null;return criteria.map((criterion,criterionIndex)=>{const modified=criteria.map((item,index)=>({...item,weight:index===criterionIndex?0:item.weight}));const winner=rankDecisionOptionsStable(modified,options)[0];return{criterionIndex,criterionName:criterion.name.trim()||`Criterion ${criterionIndex+1}`,winnerSourceIndex:winner?.sourceIndex??null,winnerName:winner?.name??null,winnerScore:winner?.score??null,changedWinner:baseline!==null&&winner!=null&&winner.sourceIndex!==baseline};});}
export function decisionContributionShare(row:StableDecisionRow){const total=row.contributions.reduce((a,b)=>a+b,0);return row.contributions.map(value=>total>0?round(value/total*100,1):0);}
