/** Signature drawing, vector export and paper-cleaning utilities. */
export interface Point{x:number;y:number;time?:number;pressure?:number;}
export interface SignatureStroke{points:Point[];color:string;width:number;}
export interface BoundingBox{minX:number;minY:number;maxX:number;maxY:number;width:number;height:number;}
export function getCanvasContentBounds(ctx:CanvasRenderingContext2D,width:number,height:number,padding=16):BoundingBox|null{if(width<=0||height<=0)return null;const data=ctx.getImageData(0,0,width,height).data;let minX=width,minY=height,maxX=-1,maxY=-1;for(let y=0;y<height;y++)for(let x=0;x<width;x++)if(data[(y*width+x)*4+3]>10){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}if(maxX<0)return null;const pad=Math.max(0,Math.floor(padding)),left=Math.max(0,minX-pad),top=Math.max(0,minY-pad),right=Math.min(width,maxX+1+pad),bottom=Math.min(height,maxY+1+pad);return{minX:left,minY:top,maxX:right,maxY:bottom,width:right-left,height:bottom-top};}
export function cropCanvasToContent(source:HTMLCanvasElement,bounds:BoundingBox):HTMLCanvasElement{const c=document.createElement('canvas');c.width=Math.max(1,Math.round(bounds.width));c.height=Math.max(1,Math.round(bounds.height));c.getContext('2d')?.drawImage(source,bounds.minX,bounds.minY,bounds.width,bounds.height,0,0,c.width,c.height);return c;}
/** Distance-based simplification followed by moving-average smoothing. */
export function smoothSignaturePoints(points:Point[],minimumDistance=1.2):Point[]{if(points.length<=2)return points.map(p=>({...p}));const filtered:Point[]=[{...points[0]}];for(let i=1;i<points.length-1;i++){const prev=filtered.at(-1)!;if(Math.hypot(points[i].x-prev.x,points[i].y-prev.y)>=minimumDistance)filtered.push({...points[i]});}filtered.push({...points.at(-1)!});if(filtered.length<=2)return filtered;return filtered.map((p,i)=>i===0||i===filtered.length-1?p:{...p,x:(filtered[i-1].x+p.x+filtered[i+1].x)/3,y:(filtered[i-1].y+p.y+filtered[i+1].y)/3});}
function escapeXml(value:string){return value.replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&apos;'}[ch]!));}
export function signatureStrokeToSvgPath(stroke:SignatureStroke):string{const points=smoothSignaturePoints(stroke.points);if(!points.length)return'';if(points.length===1)return`M ${points[0].x.toFixed(2)} ${points[0].y.toFixed(2)} l 0.01 0`;let d=`M ${points[0].x.toFixed(2)} ${points[0].y.toFixed(2)}`;for(let i=1;i<points.length-1;i++){const midX=(points[i].x+points[i+1].x)/2,midY=(points[i].y+points[i+1].y)/2;d+=` Q ${points[i].x.toFixed(2)} ${points[i].y.toFixed(2)} ${midX.toFixed(2)} ${midY.toFixed(2)}`;}const last=points.at(-1)!;d+=` L ${last.x.toFixed(2)} ${last.y.toFixed(2)}`;return d;}
export function signatureStrokesToSvg(strokes:SignatureStroke[],padding=16):string{const all=strokes.flatMap(s=>s.points);if(!all.length)return'<svg xmlns="http://www.w3.org/2000/svg" width="1" height="1" viewBox="0 0 1 1"/>';const maxStroke=Math.max(...strokes.map(s=>s.width),1),minX=Math.min(...all.map(p=>p.x))-padding-maxStroke,minY=Math.min(...all.map(p=>p.y))-padding-maxStroke,maxX=Math.max(...all.map(p=>p.x))+padding+maxStroke,maxY=Math.max(...all.map(p=>p.y))+padding+maxStroke,width=Math.max(1,maxX-minX),height=Math.max(1,maxY-minY);const paths=strokes.map(s=>`<path d="${escapeXml(signatureStrokeToSvgPath(s))}" fill="none" stroke="${escapeXml(s.color)}" stroke-width="${Math.max(.5,s.width)}" stroke-linecap="round" stroke-linejoin="round"/>`).join('');return`<svg xmlns="http://www.w3.org/2000/svg" width="${Math.ceil(width)}" height="${Math.ceil(height)}" viewBox="${minX.toFixed(2)} ${minY.toFixed(2)} ${width.toFixed(2)} ${height.toFixed(2)}">${paths}</svg>`;}
export function calculateAdaptiveSignatureThreshold(rgba:Uint8ClampedArray):number{if(rgba.length<4)return 200;const hist=new Uint32Array(256);let total=0,sum=0;for(let i=0;i<rgba.length;i+=4){if(rgba[i+3]<16)continue;const v=Math.round(.299*rgba[i]+.587*rgba[i+1]+.114*rgba[i+2]);hist[v]++;total++;sum+=v;}if(!total)return 200;let sumB=0,wB=0,best=200,maxVariance=-1;for(let t=0;t<256;t++){wB+=hist[t];if(!wB)continue;const wF=total-wB;if(!wF)break;sumB+=t*hist[t];const mB=sumB/wB,mF=(sum-sumB)/wF,variance=wB*wF*(mB-mF)**2;if(variance>maxVariance){maxVariance=variance;best=t;}}return Math.max(80,Math.min(245,best));}
function parseInkColor(color:string){const clean=color.trim().replace(/^#/,'');let x='0f172a';if(/^[0-9a-f]{3}$/i.test(clean))x=clean.split('').map(c=>c+c).join('');else if(/^[0-9a-f]{6}$/i.test(clean))x=clean;return{r:parseInt(x.slice(0,2),16),g:parseInt(x.slice(2,4),16),b:parseInt(x.slice(4,6),16)};}
export function cleanSignatureImage(source:HTMLImageElement|HTMLCanvasElement,threshold=200,contrast=1.2,inkColor='#0f172a'):HTMLCanvasElement{const canvas=document.createElement('canvas'),w='naturalWidth'in source&&source.naturalWidth?source.naturalWidth:source.width,h='naturalHeight'in source&&source.naturalHeight?source.naturalHeight:source.height;canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)return canvas;ctx.drawImage(source,0,0,w,h);const image=ctx.getImageData(0,0,w,h),data=image.data,ink=parseInkColor(inkColor),safeThreshold=Math.max(1,Math.min(255,Number.isFinite(threshold)?threshold:calculateAdaptiveSignatureThreshold(data))),safeContrast=Math.max(.1,Math.min(4,Number.isFinite(contrast)?contrast:1.2));for(let i=0;i<data.length;i+=4){const lum=.299*data[i]+.587*data[i+1]+.114*data[i+2],adjusted=(lum-128)*safeContrast+128;if(adjusted>=safeThreshold)data[i+3]=0;else{const alpha=Math.round(255*(1-Math.max(0,adjusted)/safeThreshold));data[i]=ink.r;data[i+1]=ink.g;data[i+2]=ink.b;data[i+3]=Math.max(0,Math.min(255,alpha));}}ctx.putImageData(image,0,0);return canvas;}
