export type AudioStats={duration:number;sampleRate:number;channels:number;frames:number;peak:number;rms:number;estimatedPcmBytes:number};
export function analyzeAudioBuffer(buffer:AudioBuffer):AudioStats{let peak=0,sum=0,count=0;for(let c=0;c<buffer.numberOfChannels;c+=1){const data=buffer.getChannelData(c);for(let i=0;i<data.length;i+=1){const v=data[i];const a=Math.abs(v);if(a>peak)peak=a;sum+=v*v;count+=1}}return{duration:buffer.duration,sampleRate:buffer.sampleRate,channels:buffer.numberOfChannels,frames:buffer.length,peak,rms:count?Math.sqrt(sum/count):0,estimatedPcmBytes:buffer.length*buffer.numberOfChannels*2}}
export function dbToGain(db:number){if(!Number.isFinite(db))throw new Error('Gain must be finite.');return 10**(db/20)}
export function reverseAudioRange(context:BaseAudioContext,source:AudioBuffer,startSeconds=0,endSeconds=source.duration):AudioBuffer{const start=Math.max(0,Math.min(source.duration,startSeconds)),end=Math.max(start,Math.min(source.duration,endSeconds)),from=Math.floor(start*source.sampleRate),to=Math.min(source.length,Math.ceil(end*source.sampleRate)),output=context.createBuffer(source.numberOfChannels,source.length,source.sampleRate);for(let c=0;c<source.numberOfChannels;c+=1){const input=source.getChannelData(c),dest=output.getChannelData(c);dest.set(input);for(let i=from;i<to;i+=1)dest[i]=input[to-1-(i-from)]}return output}
export type StereoMixMode='stereo'|'mono'|'left'|'right'|'swap'|'difference';
export function remixAudio(context:BaseAudioContext,source:AudioBuffer,mode:StereoMixMode,gain=1):AudioBuffer{const frames=source.length,sr=source.sampleRate,left=source.getChannelData(0),right=source.numberOfChannels>1?source.getChannelData(1):left;if(mode==='mono'){const out=context.createBuffer(1,frames,sr),dest=out.getChannelData(0);for(let i=0;i<frames;i+=1)dest[i]=Math.max(-1,Math.min(1,(left[i]+right[i])*.5*gain));return out}const out=context.createBuffer(2,frames,sr),a=out.getChannelData(0),b=out.getChannelData(1);for(let i=0;i<frames;i+=1){let l=left[i],r=right[i];if(mode==='left')r=l;else if(mode==='right')l=r;else if(mode==='swap'){const t=l;l=r;r=t}else if(mode==='difference'){const d=(l-r)*.5;l=d;r=d}a[i]=Math.max(-1,Math.min(1,l*gain));b[i]=Math.max(-1,Math.min(1,r*gain))}return out}
export function normalizeAudio(context:BaseAudioContext,source:AudioBuffer,targetPeak=.98):AudioBuffer{let peak=0;for(let c=0;c<source.numberOfChannels;c+=1)for(const value of source.getChannelData(c))peak=Math.max(peak,Math.abs(value));const gain=peak>0?targetPeak/peak:1;const out=context.createBuffer(source.numberOfChannels,source.length,source.sampleRate);for(let c=0;c<source.numberOfChannels;c+=1){const input=source.getChannelData(c),dest=out.getChannelData(c);for(let i=0;i<input.length;i+=1)dest[i]=Math.max(-1,Math.min(1,input[i]*gain))}return out}
export function applyFade(context:BaseAudioContext,source:AudioBuffer,fadeInSeconds=0,fadeOutSeconds=0):AudioBuffer{const out=context.createBuffer(source.numberOfChannels,source.length,source.sampleRate),fadeIn=Math.max(0,Math.floor(fadeInSeconds*source.sampleRate)),fadeOut=Math.max(0,Math.floor(fadeOutSeconds*source.sampleRate));for(let c=0;c<source.numberOfChannels;c+=1){const input=source.getChannelData(c),dest=out.getChannelData(c);for(let i=0;i<input.length;i+=1){let g=1;if(fadeIn>0&&i<fadeIn)g=Math.min(g,i/fadeIn);if(fadeOut>0&&i>=input.length-fadeOut)g=Math.min(g,(input.length-1-i)/fadeOut);dest[i]=input[i]*Math.max(0,g)}}return out}
function writeString(view:DataView,offset:number,value:string){for(let i=0;i<value.length;i+=1)view.setUint8(offset+i,value.charCodeAt(i))}
export function encodeWav(buffer:AudioBuffer):Uint8Array{const channels=Math.min(2,buffer.numberOfChannels),frames=buffer.length,bytesPerSample=2,blockAlign=channels*bytesPerSample,dataBytes=frames*blockAlign,out=new ArrayBuffer(44+dataBytes),view=new DataView(out);writeString(view,0,'RIFF');view.setUint32(4,36+dataBytes,true);writeString(view,8,'WAVE');writeString(view,12,'fmt ');view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,channels,true);view.setUint32(24,buffer.sampleRate,true);view.setUint32(28,buffer.sampleRate*blockAlign,true);view.setUint16(32,blockAlign,true);view.setUint16(34,16,true);writeString(view,36,'data');view.setUint32(40,dataBytes,true);let offset=44;for(let i=0;i<frames;i+=1){for(let c=0;c<channels;c+=1){const sample=Math.max(-1,Math.min(1,buffer.getChannelData(c)[i]));view.setInt16(offset,sample<0?sample*0x8000:sample*0x7fff,true);offset+=2}}return new Uint8Array(out)}
