export interface Flashcard{front:string;back:string}
export interface ClozeResult{prompt:string;answers:string[]}
export type RecallRating='again'|'hard'|'good'|'easy';
export interface StudySubject{name:string;weight:number}
export interface StudyAllocation{name:string;minutes:number}
export interface ReadingDay{day:number;startPage:number;endPage:number;pages:number}
export type CitationStyle='apa'|'mla'|'chicago';
export type CitationType='website'|'book';
export interface CitationInput{type:CitationType;author:string;title:string;container?:string;publisher?:string;year?:string;url?:string;accessed?:string}

export function parseFlashcards(input:string):Flashcard[]{const cards:Flashcard[]=[];for(const raw of input.split(/\n/)){const line=raw.trim();if(!line)continue;let parts:string[]=[];if(line.includes('::'))parts=line.split('::');else if(line.includes('\t'))parts=line.split('\t');else if(line.includes('|'))parts=line.split('|');if(parts.length>=2){const front=parts.shift()!.trim(),back=parts.join('::').trim();if(front&&back)cards.push({front,back})}}return cards}
export function parseCloze(input:string):ClozeResult{const answers:string[]=[];const prompt=input.replace(/{{(?:c\d+::)?([^}:]+)(?:::[^}]+)?}}/g,(_,answer:string)=>{answers.push(answer.trim());return'____'});return{prompt,answers}}
function normalize(text:string){return text.normalize('NFKC').toLocaleLowerCase().replace(/\s+/g,' ').trim()}
function levenshtein(a:string,b:string){if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;const prev=Array.from({length:b.length+1},(_,i)=>i),curr=new Array<number>(b.length+1);for(let i=1;i<=a.length;i++){curr[0]=i;for(let j=1;j<=b.length;j++)curr[j]=Math.min(curr[j-1]+1,prev[j]+1,prev[j-1]+(a[i-1]===b[j-1]?0:1));for(let j=0;j<=b.length;j++)prev[j]=curr[j]}return prev[b.length]}
export function memorizationAccuracy(target:string,attempt:string){const a=normalize(target).slice(0,5000),b=normalize(attempt).slice(0,5000),max=Math.max(a.length,b.length);if(!max)return 100;return Math.max(0,Math.round((1-levenshtein(a,b)/max)*1000)/10)}
export function maskPassage(text:string,hidePercent=50){const words=text.split(/(\s+)/),wordIndexes=words.map((v,i)=>({v,i})).filter(x=>/\p{L}|\p{N}/u.test(x.v)),hide=Math.round(wordIndexes.length*Math.max(0,Math.min(100,hidePercent))/100),step=hide?wordIndexes.length/hide:Infinity;for(let k=0;k<hide;k++){const item=wordIndexes[Math.min(wordIndexes.length-1,Math.floor(k*step))];words[item.i]='_'.repeat(Math.max(3,Math.min(12,item.v.length)))}return words.join('')}
export function nextReviewInterval(currentDays:number,rating:RecallRating){const current=Math.max(1,Math.round(currentDays||1));if(rating==='again')return 1;if(rating==='hard')return Math.max(2,Math.round(current*1.4));if(rating==='good')return Math.max(3,Math.round(current*2.3));return Math.max(4,Math.round(current*3.2))}
export function parseStudySubjects(input:string):StudySubject[]{return input.split(/\n/).map(line=>line.trim()).filter(Boolean).map(line=>{const [nameRaw,weightRaw]=line.split(/::|\|/),weight=Number(weightRaw);return{name:(nameRaw||'').trim(),weight:Number.isFinite(weight)&&weight>0?weight:1}}).filter(s=>s.name)}
export function planStudySession(subjects:StudySubject[],totalMinutes:number,breakMinutes=10,focusMinutes=50):{allocations:StudyAllocation[];studyMinutes:number;breaks:number;breakMinutes:number}{totalMinutes=Math.max(10,Math.round(totalMinutes));breakMinutes=Math.max(0,Math.min(30,Math.round(breakMinutes)));focusMinutes=Math.max(10,Math.min(120,Math.round(focusMinutes)));const breaks=Math.max(0,Math.floor((totalMinutes-1)/(focusMinutes+breakMinutes))),breakTotal=breaks*breakMinutes,studyMinutes=Math.max(1,totalMinutes-breakTotal),sum=subjects.reduce((n,s)=>n+s.weight,0)||1;let assigned=0;const allocations=subjects.map((s,i)=>{const minutes=i===subjects.length-1?studyMinutes-assigned:Math.round(studyMinutes*s.weight/sum);assigned+=minutes;return{name:s.name,minutes:Math.max(0,minutes)}});return{allocations,studyMinutes,breaks,breakMinutes:breakTotal}}
export function buildReadingPlan(startPage:number,endPage:number,days:number):ReadingDay[]{startPage=Math.max(1,Math.round(startPage));endPage=Math.max(startPage,Math.round(endPage));days=Math.max(1,Math.min(365,Math.round(days)));const total=endPage-startPage+1,base=Math.floor(total/days),remainder=total%days;let cursor=startPage;return Array.from({length:days},(_,i)=>{const pages=base+(i<remainder?1:0),start=cursor,end=pages?cursor+pages-1:cursor-1;cursor=end+1;return{day:i+1,startPage:start,endPage:end,pages}})}
function p(value:string|undefined){return(value||'').trim()}
function citationAuthor(value:string|undefined){return(p(value)||'Unknown author').replace(/\.+$/,'')}
export function formatCitation(input:CitationInput,style:CitationStyle){const author=citationAuthor(input.author),title=p(input.title)||'Untitled',container=p(input.container),publisher=p(input.publisher),year=p(input.year)||'n.d.',url=p(input.url),accessed=p(input.accessed);if(style==='apa'){const source=input.type==='book'?publisher:(container||publisher);return`${author}. (${year}). ${title}.${source?` ${source}.`:''}${url?` ${url}`:''}`.replace(/\s+/g,' ').trim()}if(style==='mla'){if(input.type==='book')return`${author}. ${title}. ${publisher?publisher+', ':''}${year}.`.replace(/\s+/g,' ').trim();return`${author}. “${title}.” ${container||publisher}${year?`, ${year}`:''}${url?`, ${url}`:''}.${accessed?` Accessed ${accessed}.`:''}`.replace(/\s+/g,' ').trim()}const source=input.type==='book'?publisher:(container||publisher);return`${author}. ${year}. “${title}.”${source?` ${source}.`:''}${url?` ${url}.`:''}`.replace(/\s+/g,' ').trim()}
