/** Teleprompter timing, cue navigation and pace-analysis utilities. */
export interface TeleprompterConfig{speed:number;fontSize:number;lineHeight:number;textColor:string;backgroundColor:string;textAlign:'left'|'center'|'right';isMirrored:boolean;showFocusGuide:boolean;marginWidthPercent:number;}export interface TeleprompterCue{label:string;paragraphIndex:number;}export interface TeleprompterCueTiming extends TeleprompterCue{wordOffset:number;estimatedSeconds:number;progress:number;}export const DEFAULT_TELEPROMPTER_CONFIG:TeleprompterConfig={speed:25,fontSize:44,lineHeight:1.6,textColor:'#ffffff',backgroundColor:'#09090b',textAlign:'center',isMirrored:false,showFocusGuide:true,marginWidthPercent:85};
function words(text:string):string[]{const Segmenter=(Intl as unknown as{Segmenter?:new(locale?:string,options?:{granularity:'word'})=>{segment:(value:string)=>Iterable<{segment:string;isWordLike?:boolean}>}}).Segmenter;if(Segmenter)try{return[...new Segmenter(undefined,{granularity:'word'}).segment(text)].filter(x=>x.isWordLike!==false&&/[\p{L}\p{N}]/u.test(x.segment)).map(x=>x.segment);}catch{}return text.match(/[\p{L}\p{N}\p{M}]+/gu)||[];}
export function calculateSpeakingStats(text:string,wpm=140){const wordCount=words(text).length,safe=Math.max(1,Number.isFinite(wpm)?wpm:140),seconds=Math.round(wordCount/safe*60),h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return{wordCount,estimatedSeconds:seconds,formattedDuration:h>0?`${h}h ${m}m ${s}s`:m>0?`${m}m ${s}s`:`${s}s`};}
export function calculateScrollStep(speed:number):number{if(speed<=0)return 0;const n=Math.max(1,Math.min(100,speed));return .2+(n/100)**1.5*7.8;}export const calculateScrollSpeedPixelsPerSecond=(speed:number)=>calculateScrollStep(speed)*60;export function calculateScrollDelta(speed:number,deltaMs:number):number{return calculateScrollSpeedPixelsPerSecond(speed)*Math.max(0,Math.min(250,Number.isFinite(deltaMs)?deltaMs:0))/1000;}export function calculateScrollSpeedForWpm(wpm:number,fontSize:number,lineHeight:number,averageWordsPerLine=7.5):number{const safe=Math.max(40,Math.min(400,Number.isFinite(wpm)?wpm:140)),linePx=Math.max(12,fontSize)*Math.max(1,lineHeight);return Number((linePx*(safe/Math.max(2,averageWordsPerLine)/60)).toFixed(3));}export function calculatePrompterProgress(scrollTop:number,clientHeight:number,scrollHeight:number):number{const max=Math.max(0,scrollHeight-clientHeight);return max<=0?1:Number(Math.max(0,Math.min(1,scrollTop/max)).toFixed(4));}export function estimateRemainingSeconds(totalSeconds:number,progress:number):number{return Math.max(0,Math.round(Math.max(0,totalSeconds)*(1-Math.max(0,Math.min(1,progress)))));}
export function parseTeleprompterCues(script:string):TeleprompterCue[]{const paragraphs=script.split(/\n\s*\n/),cues:TeleprompterCue[]=[];paragraphs.forEach((p,i)=>{const m=p.trim().match(/^\[\[\s*(?:cue\s*:\s*)?(.+?)\s*\]\]$/i);if(m)cues.push({label:m[1].trim(),paragraphIndex:i});});return cues;}export function stripTeleprompterCueParagraphs(script:string):string[]{return script.split(/\n\s*\n/).filter(p=>!/^\[\[\s*(?:cue\s*:\s*)?.+?\s*\]\]$/i.test(p.trim()));}
export function calculateCueTimeline(script:string,wpm=140):TeleprompterCueTiming[]{const paragraphs=script.split(/\n\s*\n/),total=words(stripTeleprompterCueParagraphs(script).join(' ')).length||1,safeWpm=Math.max(1,wpm);let offset=0;const out:TeleprompterCueTiming[]=[];for(let i=0;i<paragraphs.length;i++){const m=paragraphs[i].trim().match(/^\[\[\s*(?:cue\s*:\s*)?(.+?)\s*\]\]$/i);if(m)out.push({label:m[1].trim(),paragraphIndex:i,wordOffset:offset,estimatedSeconds:Number((offset/safeWpm*60).toFixed(1)),progress:Number((offset/total).toFixed(4))});else offset+=words(paragraphs[i]).length;}return out;}
export function getNextTeleprompterCue(cues:TeleprompterCueTiming[],progress:number):TeleprompterCueTiming|null{return cues.find(c=>c.progress>Math.max(0,Math.min(1,progress))+.0001)||null;}
/** Compares actual elapsed time with script progress. Positive drift means the speaker is behind the planned pace. */
export function calculatePaceDrift(totalEstimatedSeconds:number,progress:number,elapsedSeconds:number):{driftSeconds:number;paceRatio:number;status:'ahead'|'on-pace'|'behind'}{const expected=Math.max(0,totalEstimatedSeconds)*Math.max(0,Math.min(1,progress)),drift=Math.round(elapsedSeconds-expected),ratio=expected>0?elapsedSeconds/expected:1,status=drift>8?'behind':drift<-8?'ahead':'on-pace';return{driftSeconds:drift,paceRatio:Number(ratio.toFixed(3)),status};}
