export interface ReadabilityResult{words:number;sentences:number;syllables:number;readingEase:number;gradeLevel:number;note:string}
export interface NgramCount{phrase:string;count:number}
export interface ExtractedPatterns{emails:string[];urls:string[];hashtags:string[];mentions:string[]}
export interface DuplicatePhrase{phrase:string;count:number}
export interface SimilarityResult{jaccard:number;cosine:number;combined:number}
export interface UnicodeItem{grapheme:string;codePoints:string[];utf16Units:number;category:string}
const WORD=/[\p{L}\p{N}]+(?:['’\-][\p{L}\p{N}]+)*/gu;
function seg(text:string,granularity:'word'|'grapheme'):{segment:string;isWordLike?:boolean}[]{const S=(Intl as unknown as{Segmenter?:new(locale?:string,options?:{granularity:'word'|'grapheme'})=>{segment(input:string):Iterable<{segment:string;isWordLike?:boolean}>}}).Segmenter;if(S)return Array.from(new S(undefined,{granularity}).segment(text));if(granularity==='grapheme')return Array.from(text).map(segment=>({segment}));return(text.match(WORD)||[]).map(segment=>({segment,isWordLike:true}));}
export function textWords(text:string){const out=seg(text,'word').filter(x=>x.isWordLike!==false&&/[\p{L}\p{N}]/u.test(x.segment)).map(x=>x.segment);return out.length?out:(text.match(WORD)||[])}
export function textGraphemes(text:string){return seg(text,'grapheme').map(x=>x.segment)}
export function textSentences(text:string){return text.trim().split(/(?<=[.!?])(?:["'”’)]*)\s+|\n+/u).map(s=>s.trim()).filter(Boolean)}
function syllables(word:string){let w=word.toLowerCase().replace(/[^a-z]/g,'');if(!w)return 0;if(w.length<=3)return 1;w=w.replace(/(?:[^laeiouy]es|ed|[^laeiouy]e)$/,'').replace(/^y/,'');return Math.max(1,w.match(/[aeiouy]{1,2}/g)?.length||1)}
export function calculateReadability(text:string):ReadabilityResult{const words=textWords(text).filter(w=>/[A-Za-z]/.test(w));if(!words.length)return{words:0,sentences:0,syllables:0,readingEase:0,gradeLevel:0,note:'Add English prose to calculate readability.'};const sentences=Math.max(1,textSentences(text).length),syllableCount=words.reduce((n,w)=>n+syllables(w),0),asl=words.length/sentences,asw=syllableCount/words.length;return{words:words.length,sentences,syllables:syllableCount,readingEase:Math.round((206.835-1.015*asl-84.6*asw)*10)/10,gradeLevel:Math.round((.39*asl+11.8*asw-15.59)*10)/10,note:'Flesch formulas are designed for English prose and are approximate.'}}
export function analyzeNgrams(text:string,n=2,limit=50):NgramCount[]{n=Math.max(1,Math.min(3,Math.round(n)));const words=textWords(text).map(w=>w.toLocaleLowerCase()),counts=new Map<string,number>();for(let i=0;i<=words.length-n;i++){const phrase=words.slice(i,i+n).join(' ');counts.set(phrase,(counts.get(phrase)||0)+1)}return[...counts].map(([phrase,count])=>({phrase,count})).sort((a,b)=>b.count-a.count||a.phrase.localeCompare(b.phrase)).slice(0,Math.max(1,limit))}
const uniq=(items:string[])=>[...new Set(items)].sort((a,b)=>a.localeCompare(b));
export function extractTextPatterns(text:string):ExtractedPatterns{const emails=uniq(text.match(/[\p{L}\p{N}.!#$%&'*+/=?^_`{|}~-]+@[\p{L}\p{N}-]+(?:\.[\p{L}\p{N}-]+)+/gu)||[]),urls=uniq((text.match(/https?:\/\/[^\s<>"']+/giu)||[]).map(x=>x.replace(/[),.;!?]+$/,''))),hashtags=uniq(text.match(/#[\p{L}\p{N}_]+/gu)||[]),raw=text.match(/@[\p{L}\p{N}_.-]+/gu)||[],emailMentions=new Set(emails.map(e=>e.slice(e.indexOf('@'))));return{emails,urls,hashtags,mentions:uniq(raw.filter(m=>!emailMentions.has(m)))}}
export function findDuplicatePhrases(text:string,size=4,minCount=2,limit=30):DuplicatePhrase[]{size=Math.max(2,Math.min(8,Math.round(size)));const words=textWords(text).map(w=>w.toLocaleLowerCase()),counts=new Map<string,number>();for(let i=0;i<=words.length-size;i++){const phrase=words.slice(i,i+size).join(' ');counts.set(phrase,(counts.get(phrase)||0)+1)}return[...counts].filter(([,count])=>count>=minCount).map(([phrase,count])=>({phrase,count})).sort((a,b)=>b.count-a.count||a.phrase.localeCompare(b.phrase)).slice(0,limit)}
function freq(text:string){const m=new Map<string,number>();for(const w of textWords(text).map(w=>w.toLocaleLowerCase()))m.set(w,(m.get(w)||0)+1);return m}
export function compareTextSimilarity(a:string,b:string):SimilarityResult{const fa=freq(a),fb=freq(b),sa=new Set(fa.keys()),sb=new Set(fb.keys()),union=new Set([...sa,...sb]),intersection=[...sa].filter(x=>sb.has(x)).length,jaccard=union.size?intersection/union.size:0;let dot=0,aa=0,bb=0;for(const k of union){const x=fa.get(k)||0,y=fb.get(k)||0;dot+=x*y;aa+=x*x;bb+=y*y}const cosine=aa&&bb?dot/Math.sqrt(aa*bb):0;return{jaccard:Math.round(jaccard*1000)/1000,cosine:Math.round(cosine*1000)/1000,combined:Math.round(((jaccard+cosine)/2)*1000)/1000}}
function category(g:string){if(g===' ')return'SPACE';if(g==='\n')return'LINE FEED';if(g==='\r')return'CARRIAGE RETURN';if(g==='\t')return'TAB';if(g==='\u00a0')return'NO-BREAK SPACE';if(g==='\u200b')return'ZERO WIDTH SPACE';if(g==='\ufeff')return'ZERO WIDTH NO-BREAK SPACE / BOM';if(/^\p{L}+$/u.test(g))return'Letter';if(/^\p{N}+$/u.test(g))return'Number';if(/^\p{P}+$/u.test(g))return'Punctuation';if(/^\p{S}+$/u.test(g))return'Symbol';if(/^\s+$/u.test(g))return'Whitespace';return'Other'}
export function inspectUnicode(text:string,limit=500):UnicodeItem[]{return textGraphemes(text).slice(0,limit).map(grapheme=>({grapheme,codePoints:Array.from(grapheme).map(ch=>`U+${ch.codePointAt(0)!.toString(16).toUpperCase().padStart(4,'0')}`),utf16Units:grapheme.length,category:category(grapheme)}))}
export function repeatText(text:string,count:number,separator='\n'){count=Math.max(1,Math.min(1000,Math.floor(count||1)));if(text.length*count>1_000_000)throw new Error('Repeated output is limited to 1,000,000 characters.');return Array.from({length:count},()=>text).join(separator)}
export function reverseText(text:string,mode:'characters'|'words'|'sentences'){if(mode==='characters')return textGraphemes(text).reverse().join('');if(mode==='words')return text.trim().split(/\s+/).reverse().join(' ');return textSentences(text).reverse().join(' ')}
function wrapLine(line:string,width:number){if(!line.trim())return'';const out:string[]=[],words=line.trim().split(/\s+/);let current='';for(const word of words){if(word.length>width){if(current){out.push(current);current=''}for(let i=0;i<word.length;i+=width)out.push(word.slice(i,i+width));continue}if(!current)current=word;else if(current.length+word.length+1<=width)current+=' '+word;else{out.push(current);current=word}}if(current)out.push(current);return out.join('\n')}
export function wrapText(text:string,width=80){width=Math.max(10,Math.min(240,Math.round(width)));return text.split(/\n/).map(line=>wrapLine(line,width)).join('\n')}
export function visualizeWhitespace(text:string){return text.replace(/\u200b/g,'⟦ZWSP⟧').replace(/\ufeff/g,'⟦BOM⟧').replace(/\u00a0/g,'⍽').replace(/\t/g,'→\t').replace(/ /g,'·').replace(/\r\n/g,'↵\n').replace(/\r/g,'↵\n').replace(/\n/g,'↵\n')}
const LOREM=['Lorem ipsum dolor sit amet, consectetur adipiscing elit.','Integer vitae justo eget magna fermentum iaculis.','Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.','Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.','Donec sollicitudin molestie malesuada.','Vivamus suscipit tortor eget felis porttitor volutpat.','Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.','Sed porttitor lectus nibh.'];
export function generateLorem(paragraphs=2,sentences=4){paragraphs=Math.max(1,Math.min(20,Math.round(paragraphs)));sentences=Math.max(1,Math.min(12,Math.round(sentences)));return Array.from({length:paragraphs},(_,p)=>Array.from({length:sentences},(_,s)=>LOREM[(p*sentences+s)%LOREM.length]).join(' ')).join('\n\n')}
export function markdownToPlainText(input:string){return input.replace(/```[^\n]*\n([\s\S]*?)```/g,'$1').replace(/`([^`]+)`/g,'$1').replace(/!\[([^\]]*)\]\([^)]*\)/g,'$1').replace(/\[([^\]]+)\]\([^)]*\)/g,'$1').replace(/^\s{0,3}#{1,6}\s+/gm,'').replace(/^\s*>\s?/gm,'').replace(/^\s*(?:[-+*]|\d+[.)])\s+/gm,'').replace(/\*\*([^*]+)\*\*/g,'$1').replace(/__([^_]+)__/g,'$1').replace(/~~([^~]+)~~/g,'$1').replace(/^\s*[-*_]{3,}\s*$/gm,'').replace(/\n{3,}/g,'\n\n').trim()}
const ENTITIES:Record<string,string>={amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '};
function entity(e:string){if(/^#x/i.test(e)){const n=parseInt(e.slice(2),16);return Number.isFinite(n)?String.fromCodePoint(n):`&${e};`}if(e.startsWith('#')){const n=parseInt(e.slice(1),10);return Number.isFinite(n)?String.fromCodePoint(n):`&${e};`}return ENTITIES[e]??`&${e};`}
export function htmlToPlainText(input:string){return input.replace(/<(script|style)[^>]*>[\s\S]*?<\/\1>/gi,'').replace(/<br\s*\/?>/gi,'\n').replace(/<\/(p|div|li|h[1-6]|blockquote|tr)>/gi,'\n').replace(/<li[^>]*>/gi,'• ').replace(/<[^>]+>/g,'').replace(/&([#\w]+);/g,(_,e)=>entity(e)).replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
