/** Unicode-aware text diff with bounded large-document alignment and patch export. */
export type DiffChangeType='unchanged'|'added'|'removed'|'modified';
export interface DiffToken{text:string;added?:boolean;removed?:boolean;}
export interface DiffLine{type:DiffChangeType;originalLineNum?:number;revisedLineNum?:number;originalText?:string;revisedText?:string;wordTokens?:DiffToken[];}
export interface DiffOptions{ignoreCase:boolean;ignoreWhitespace:boolean;ignoreBlankLines:boolean;}
export interface DiffSummary{lines:DiffLine[];addedCount:number;removedCount:number;modifiedCount:number;unchangedCount:number;similarityScore:number;}
export interface MovedLine{fromLine:number;toLine:number;text:string;}
interface RawDiffLine{type:'unchanged'|'added'|'removed';orig?:string;rev?:string;origNum?:number;revNum?:number;}
const MAX_EXACT_LINE_MATRIX_CELLS=2_000_000,MAX_EXACT_WORD_MATRIX_CELLS=120_000,LARGE_DIFF_LOOKAHEAD=96;
const defaultOptions:DiffOptions={ignoreCase:false,ignoreWhitespace:false,ignoreBlankLines:false};
function lineNormalizer(options:DiffOptions){return(line:string)=>{let v=line;if(options.ignoreWhitespace)v=v.trim().replace(/\s+/gu,' ');if(options.ignoreCase)v=v.toLocaleLowerCase();return v;};}
function exactLineDiff(a:string[],b:string[],normalize:(line:string)=>string){const n=a.length,m=b.length,dp=Array.from({length:n+1},()=>new Uint32Array(m+1));for(let i=0;i<n;i++){const left=normalize(a[i]);for(let j=0;j<m;j++)dp[i+1][j+1]=left===normalize(b[j])?dp[i][j]+1:Math.max(dp[i+1][j],dp[i][j+1]);}let i=n,j=m;const out:RawDiffLine[]=[];while(i||j){if(i&&j&&normalize(a[i-1])===normalize(b[j-1])){out.push({type:'unchanged',orig:a[i-1],rev:b[j-1],origNum:i,revNum:j});i--;j--;}else if(j&&(!i||dp[i][j-1]>=dp[i-1][j])){out.push({type:'added',rev:b[j-1],revNum:j});j--;}else{out.push({type:'removed',orig:a[i-1],origNum:i});i--;}}return{raw:out.reverse(),unchanged:dp[n][m]};}
/** Greedy anchor alignment avoids an O(n*m) allocation for multi-thousand-line documents. */
function largeLineDiff(a:string[],b:string[],normalize:(line:string)=>string){const raw:RawDiffLine[]=[];let unchanged=0,i=0,j=0;while(i<a.length||j<b.length){if(i>=a.length){raw.push({type:'added',rev:b[j],revNum:j+1});j++;continue;}if(j>=b.length){raw.push({type:'removed',orig:a[i],origNum:i+1});i++;continue;}if(normalize(a[i])===normalize(b[j])){raw.push({type:'unchanged',orig:a[i],rev:b[j],origNum:i+1,revNum:j+1});unchanged++;i++;j++;continue;}const rev=new Map<string,number>();for(let k=j;k<Math.min(b.length,j+LARGE_DIFF_LOOKAHEAD+1);k++){const key=normalize(b[k]);if(!rev.has(key))rev.set(key,k-j);}let ao=-1,bo=-1,score=Infinity;for(let k=i;k<Math.min(a.length,i+LARGE_DIFF_LOOKAHEAD+1);k++){const r=rev.get(normalize(a[k]));if(r===undefined)continue;const s=(k-i)+r;if(s<score){score=s;ao=k-i;bo=r;}}if(ao>=0){for(let k=0;k<ao;k++)raw.push({type:'removed',orig:a[i+k],origNum:i+k+1});for(let k=0;k<bo;k++)raw.push({type:'added',rev:b[j+k],revNum:j+k+1});i+=ao;j+=bo;continue;}raw.push({type:'removed',orig:a[i],origNum:i+1},{type:'added',rev:b[j],revNum:j+1});i++;j++;}return{raw,unchanged};}
function segmentText(value:string):string[]{const Segmenter=(Intl as unknown as{Segmenter?:new(locale?:string|string[],options?:{granularity:'word'})=>{segment:(input:string)=>Iterable<{segment:string}>}}).Segmenter;if(Segmenter){try{return[...new Segmenter(undefined,{granularity:'word'}).segment(value)].map(x=>x.segment);}catch{}}return value.match(/\s+|[\p{L}\p{N}\p{M}]+|[^\p{L}\p{N}\p{M}\s]+/gu)||[];}
/** Word/grapheme diff keeps CJK and punctuation useful instead of treating a whole line as one token. */
export function computeWordDiff(a:string,b:string):DiffToken[]{const wa=segmentText(a),wb=segmentText(b),n=wa.length,m=wb.length;if((n+1)*(m+1)>MAX_EXACT_WORD_MATRIX_CELLS){const out:DiffToken[]=[];if(a)out.push({text:a,removed:true});if(b)out.push({text:b,added:true});return out;}const dp=Array.from({length:n+1},()=>new Uint16Array(m+1));for(let i=0;i<n;i++)for(let j=0;j<m;j++)dp[i+1][j+1]=wa[i]===wb[j]?dp[i][j]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=n,j=m;const out:DiffToken[]=[];while(i||j){if(i&&j&&wa[i-1]===wb[j-1]){out.push({text:wa[i-1]});i--;j--;}else if(j&&(!i||dp[i][j-1]>=dp[i-1][j])){out.push({text:wb[j-1],added:true});j--;}else{out.push({text:wa[i-1],removed:true});i--;}}return out.reverse();}
function flushRun(lines:DiffLine[],run:RawDiffLine[],counts:{added:number;removed:number;modified:number}){if(!run.length)return;const removed=run.filter(x=>x.type==='removed'),added=run.filter(x=>x.type==='added'),paired=Math.min(removed.length,added.length);for(let i=0;i<paired;i++){lines.push({type:'modified',originalLineNum:removed[i].origNum,revisedLineNum:added[i].revNum,originalText:removed[i].orig,revisedText:added[i].rev,wordTokens:computeWordDiff(removed[i].orig||'',added[i].rev||'')});counts.modified++;}for(let i=paired;i<removed.length;i++){lines.push({type:'removed',originalLineNum:removed[i].origNum,originalText:removed[i].orig});counts.removed++;}for(let i=paired;i<added.length;i++){lines.push({type:'added',revisedLineNum:added[i].revNum,revisedText:added[i].rev});counts.added++;}}
export function computeTextDiff(originalText:string,revisedText:string,options:DiffOptions=defaultOptions):DiffSummary{let a=originalText.split(/\r?\n/),b=revisedText.split(/\r?\n/);if(options.ignoreBlankLines){a=a.filter(x=>x.trim());b=b.filter(x=>x.trim());}const normalize=lineNormalizer(options),alignment=(a.length+1)*(b.length+1)<=MAX_EXACT_LINE_MATRIX_CELLS?exactLineDiff(a,b,normalize):largeLineDiff(a,b,normalize),lines:DiffLine[]=[],counts={added:0,removed:0,modified:0};let unchangedCount=0,run:RawDiffLine[]=[];const flush=()=>{flushRun(lines,run,counts);run=[];};for(const item of alignment.raw){if(item.type!=='unchanged'){run.push(item);continue;}flush();lines.push({type:'unchanged',originalLineNum:item.origNum,revisedLineNum:item.revNum,originalText:item.orig,revisedText:item.rev});unchangedCount++;}flush();const denom=Math.max(1,a.length+b.length);return{lines,addedCount:counts.added,removedCount:counts.removed,modifiedCount:counts.modified,unchangedCount,similarityScore:Math.min(100,Math.round(200*alignment.unchanged/denom))};}
export function detectMovedLines(summary:DiffSummary,options:Pick<DiffOptions,'ignoreCase'|'ignoreWhitespace'>={ignoreCase:false,ignoreWhitespace:false}):MovedLine[]{const normalize=lineNormalizer({...options,ignoreBlankLines:false}),removed=new Map<string,number[]>();for(const line of summary.lines){if(line.type==='removed'&&line.originalText!==undefined){const k=normalize(line.originalText);if(k)(removed.get(k)||removed.set(k,[]).get(k)!).push(line.originalLineNum||0);}}const moves:MovedLine[]=[];for(const line of summary.lines){if(line.type!=='added'||line.revisedText===undefined)continue;const key=normalize(line.revisedText),queue=removed.get(key);if(queue?.length)moves.push({fromLine:queue.shift()!,toLine:line.revisedLineNum||0,text:line.revisedText});}return moves;}
export function formatToMarkdownDiff(summary:DiffSummary):string{const out=['```diff'];for(const line of summary.lines){if(line.type==='added')out.push(`+ ${line.revisedText||''}`);else if(line.type==='removed')out.push(`- ${line.originalText||''}`);else if(line.type==='modified')out.push(`- ${line.originalText||''}`,`+ ${line.revisedText||''}`);else out.push(`  ${line.originalText||''}`);}out.push('```');return out.join('\n');}
/** Creates a standards-shaped unified patch with bounded context hunks. */
export function generateUnifiedDiffPatch(originalText:string,revisedText:string,options:{originalName?:string;revisedName?:string;contextLines?:number;diffOptions?:DiffOptions}={}):string{const summary=computeTextDiff(originalText,revisedText,options.diffOptions||defaultOptions),context=Math.max(0,Math.min(20,Math.floor(options.contextLines??3))),expanded:DiffLine[]=[];for(const line of summary.lines){if(line.type==='modified'){expanded.push({type:'removed',originalLineNum:line.originalLineNum,originalText:line.originalText},{type:'added',revisedLineNum:line.revisedLineNum,revisedText:line.revisedText});}else expanded.push(line);}const changed=expanded.map((l,i)=>l.type==='unchanged'?-1:i).filter(i=>i>=0);const out=[`--- ${options.originalName||'a/text'}`,`+++ ${options.revisedName||'b/text'}`];if(!changed.length)return out.join('\n')+'\n';const ranges:{start:number;end:number}[]=[];for(const index of changed){const start=Math.max(0,index-context),end=Math.min(expanded.length-1,index+context),last=ranges.at(-1);if(last&&start<=last.end+1)last.end=Math.max(last.end,end);else ranges.push({start,end});}for(const range of ranges){const h=expanded.slice(range.start,range.end+1);const oldNums=h.flatMap(l=>l.originalLineNum?[l.originalLineNum]:[]),newNums=h.flatMap(l=>l.revisedLineNum?[l.revisedLineNum]:[]),oldStart=oldNums[0]??1,newStart=newNums[0]??1,oldCount=h.filter(l=>l.type!=='added').length,newCount=h.filter(l=>l.type!=='removed').length;out.push(`@@ -${oldStart},${oldCount} +${newStart},${newCount} @@`);for(const l of h)out.push(l.type==='added'?`+${l.revisedText||''}`:l.type==='removed'?`-${l.originalText||''}`:` ${l.originalText||''}`);}return out.join('\n')+'\n';}
