import{htmlToMarkdown,markdownToHtml}from'./p11-developer';
export type DocumentFormat='txt'|'md'|'html'|'rtf'|'docx'|'odt'|'epub'|'pptx'|'pdf';
export type DataFormat='csv'|'tsv'|'json'|'xml'|'xlsx'|'ods'|'yaml'|'toml'|'html';
export type SubtitleConverterFormat='srt'|'vtt'|'ass'|'ssa'|'sbv'|'ttml'|'txt';
export const DOCUMENT_INPUT_FORMATS:DocumentFormat[]=['txt','md','html','rtf','docx','odt','epub','pptx','pdf'];
export const DOCUMENT_OUTPUT_FORMATS:DocumentFormat[]=['txt','md','html','rtf','docx','odt','epub','pptx','pdf'];
export const DATA_FORMATS:DataFormat[]=['csv','tsv','json','xml','xlsx','ods','yaml','toml','html'];
export const SUBTITLE_CONVERTER_FORMATS:SubtitleConverterFormat[]=['srt','vtt','ass','ssa','sbv','ttml','txt'];
export function extensionOf(name:string){return name.toLowerCase().split('.').pop()?.replace(/[^a-z0-9]/g,'')??''}
export function detectDocumentFormat(name:string):DocumentFormat|null{const ext=extensionOf(name);const normalized=ext==='markdown'?'md':ext==='htm'?'html':ext;return DOCUMENT_INPUT_FORMATS.includes(normalized as DocumentFormat)?normalized as DocumentFormat:null}
export function detectDataFormat(name:string):DataFormat|null{const ext=extensionOf(name),normalized=ext==='yml'?'yaml':ext==='htm'?'html':ext;return DATA_FORMATS.includes(normalized as DataFormat)?normalized as DataFormat:null}
export function detectSubtitleFormat(name:string):SubtitleConverterFormat|null{const ext=extensionOf(name),normalized=ext==='webvtt'?'vtt':ext==='dfxp'?'ttml':ext;return SUBTITLE_CONVERTER_FORMATS.includes(normalized as SubtitleConverterFormat)?normalized as SubtitleConverterFormat:null}
export function escapeHtml(text:string){return text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')}
export function plainTextToHtml(text:string){return text.replace(/\r/g,'').split(/\n{2,}/).map(p=>`<p>${escapeHtml(p).replace(/\n/g,'<br>')}</p>`).join('\n')}
export function markdownToPlainText(markdown:string){return markdownToHtml(markdown).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<br\s*\/?\s*>/gi,'\n').replace(/<\/(?:p|div|h[1-6]|li|blockquote|pre)>/gi,'\n').replace(/<li[^>]*>/gi,'• ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&lt;/gi,'<').replace(/&gt;/gi,'>').replace(/&quot;/gi,'"').replace(/[ \t]+\n/g,'\n').replace(/\n{3,}/g,'\n\n').trim()}
export function htmlToPlainText(html:string){return markdownToPlainText(htmlToMarkdown(html))}
export function documentTextViews(source:string,format:'txt'|'md'|'html'){if(format==='txt')return{text:source,markdown:source,html:plainTextToHtml(source)};if(format==='md')return{text:markdownToPlainText(source),markdown:source,html:markdownToHtml(source)};const markdown=htmlToMarkdown(source);return{text:htmlToPlainText(source),markdown,html:source}}
function decodePdfLiteral(input:string){return input.replace(/\\([nrtbf()\\])/g,(_,c)=>({n:'\n',r:'\r',t:'\t',b:'\b',f:'\f','(':'(',')':')','\\':'\\'}[c]??c)).replace(/\\([0-7]{1,3})/g,(_,n)=>String.fromCharCode(parseInt(n,8)))}
function stringsFromPdfContent(content:string){const blocks=[...content.matchAll(/BT([\s\S]*?)ET/g)].map(m=>m[1]),texts:string[]=[];for(const block of blocks){for(const m of block.matchAll(/\((?:\\.|[^\\)])*\)\s*Tj/g)){const raw=m[0].replace(/\s*Tj$/,'').slice(1,-1);texts.push(decodePdfLiteral(raw))}for(const m of block.matchAll(/\[([\s\S]*?)\]\s*TJ/g)){const joined=[...m[1].matchAll(/\((?:\\.|[^\\)])*\)/g)].map(x=>decodePdfLiteral(x[0].slice(1,-1))).join('');if(joined)texts.push(joined)}}return texts.join('\n').replace(/\n{3,}/g,'\n\n').trim()}
async function inflatePdfStream(bytes:Uint8Array){if(typeof DecompressionStream==='undefined')return null;try{const ds=new DecompressionStream('deflate'),stream=new Blob([bytes]).stream().pipeThrough(ds);return new Uint8Array(await new Response(stream).arrayBuffer())}catch{return null}}
export async function extractBasicPdfText(data:ArrayBuffer|Uint8Array){const bytes=data instanceof Uint8Array?data:new Uint8Array(data),latin=new TextDecoder('latin1').decode(bytes);let text=stringsFromPdfContent(latin);const streamRe=/stream\r?\n/g;let match:RegExpExecArray|null;while((match=streamRe.exec(latin))){const start=match.index+match[0].length,end=latin.indexOf('endstream',start);if(end<0)break;const prefix=latin.slice(Math.max(0,match.index-500),match.index),raw=bytes.slice(start,end-(latin[end-1]==='\n'?1:0));let decoded=raw;if(/\/FlateDecode/.test(prefix)){const inflated=await inflatePdfStream(raw);if(inflated)decoded=inflated}const found=stringsFromPdfContent(new TextDecoder('latin1').decode(decoded));if(found)text+=(text?'\n\n':'')+found;streamRe.lastIndex=end+9}text=text.replace(/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/g,'').trim();if(!text)throw new Error('No readable text was found in this PDF. Scanned PDFs, embedded-font encodings, and complex compressed content may require the dedicated PDF OCR/export workspace.');return text}
export type AudioTarget={label:string;mime:string;extension:string;realtime:boolean;pcm?:'wav'|'aiff'};
export function audioTargets(isSupported:(mime:string)=>boolean):AudioTarget[]{const targets:AudioTarget[]=[{label:'WAV (PCM)',mime:'audio/wav',extension:'wav',realtime:false,pcm:'wav'},{label:'AIFF (PCM)',mime:'audio/aiff',extension:'aiff',realtime:false,pcm:'aiff'}],candidates:[string,string,string][]=[['MP3','audio/mpeg','mp3'],['M4A / AAC','audio/mp4;codecs=mp4a.40.2','m4a'],['Ogg / Opus','audio/ogg;codecs=opus','ogg'],['WebM / Opus','audio/webm;codecs=opus','webm'],['FLAC','audio/flac','flac'],['WMA','audio/x-ms-wma','wma']];for(const[label,mime,extension]of candidates)if(isSupported(mime))targets.push({label,mime,extension,realtime:true});return targets}
export function humanBytes(bytes:number){if(bytes<1024)return`${bytes} B`;if(bytes<1024**2)return`${(bytes/1024).toFixed(1)} KB`;return`${(bytes/1024**2).toFixed(1)} MB`}
