import { parseHumanNumber } from './human-number';
export type UnitCategory='weight'|'volume'|'count'|'length'|'area';export type NormalizationBasis='standard'|'hundred'|'base';
export interface UnitDefinition{id:string;label:string;category:UnitCategory;baseRatio:number;displayStandardUnit:string;}
export const SUPPORTED_UNITS:UnitDefinition[]=[
{id:'mcg',label:'Micrograms (µg)',category:'weight',baseRatio:.000001,displayStandardUnit:'kg'},{id:'mg',label:'Milligrams (mg)',category:'weight',baseRatio:.001,displayStandardUnit:'kg'},{id:'g',label:'Grams (g)',category:'weight',baseRatio:1,displayStandardUnit:'kg'},{id:'kg',label:'Kilograms (kg)',category:'weight',baseRatio:1000,displayStandardUnit:'kg'},{id:'oz',label:'Ounces (oz)',category:'weight',baseRatio:28.349523125,displayStandardUnit:'lb'},{id:'lb',label:'Pounds (lb)',category:'weight',baseRatio:453.59237,displayStandardUnit:'lb'},{id:'stone',label:'Stone (st)',category:'weight',baseRatio:6350.29318,displayStandardUnit:'lb'},
{id:'ml',label:'Milliliters (ml)',category:'volume',baseRatio:1,displayStandardUnit:'L'},{id:'cl',label:'Centiliters (cl)',category:'volume',baseRatio:10,displayStandardUnit:'L'},{id:'dl',label:'Deciliters (dl)',category:'volume',baseRatio:100,displayStandardUnit:'L'},{id:'l',label:'Liters (L)',category:'volume',baseRatio:1000,displayStandardUnit:'L'},{id:'floz',label:'Fluid Ounces (US fl oz)',category:'volume',baseRatio:29.5735295625,displayStandardUnit:'fl oz'},{id:'imp_floz',label:'Fluid Ounces (UK fl oz)',category:'volume',baseRatio:28.4130625,displayStandardUnit:'L'},{id:'gal',label:'Gallons (US gal)',category:'volume',baseRatio:3785.411784,displayStandardUnit:'gal'},{id:'imp_gal',label:'Gallons (UK gal)',category:'volume',baseRatio:4546.09,displayStandardUnit:'L'},{id:'pt',label:'Pints (US pt)',category:'volume',baseRatio:473.176473,displayStandardUnit:'gal'},
{id:'item',label:'Items / Units',category:'count',baseRatio:1,displayStandardUnit:'item'},{id:'pcs',label:'Pieces (pcs)',category:'count',baseRatio:1,displayStandardUnit:'item'},{id:'pack',label:'Packs',category:'count',baseRatio:1,displayStandardUnit:'item'},{id:'sheet',label:'Sheets / Rolls',category:'count',baseRatio:1,displayStandardUnit:'sheet'},
{id:'mm',label:'Millimeters (mm)',category:'length',baseRatio:.001,displayStandardUnit:'m'},{id:'cm',label:'Centimeters (cm)',category:'length',baseRatio:.01,displayStandardUnit:'m'},{id:'m',label:'Meters (m)',category:'length',baseRatio:1,displayStandardUnit:'m'},{id:'km',label:'Kilometers (km)',category:'length',baseRatio:1000,displayStandardUnit:'m'},{id:'in',label:'Inches (in)',category:'length',baseRatio:.0254,displayStandardUnit:'ft'},{id:'ft',label:'Feet (ft)',category:'length',baseRatio:.3048,displayStandardUnit:'ft'},{id:'yd',label:'Yards (yd)',category:'length',baseRatio:.9144,displayStandardUnit:'yd'},
{id:'sqcm',label:'Square Centimeters (cm²)',category:'area',baseRatio:.0001,displayStandardUnit:'m²'},{id:'sqm',label:'Square Meters (m²)',category:'area',baseRatio:1,displayStandardUnit:'m²'},{id:'sqft',label:'Square Feet (sq ft)',category:'area',baseRatio:.09290304,displayStandardUnit:'sq ft'}];
export interface ProductItem{id:string;name:string;price:number;packCount:number;unitSize:number;unitId:string;discountAmount?:number;feeAmount?:number;depositAmount?:number;taxPercent?:number;}
export interface EvaluatedProduct{id:string;name:string;totalPrice:number;totalQuantityInBase:number;pricePerBaseUnit:number;pricePerStandardUnit:number;standardUnitLabel:string;unitCategory:UnitCategory;isBestValue:boolean;isTie:boolean;savingsPercentageVsWorst:number;savingsPercentageVsNext:number;priceDifferenceVsBest:number;effectivePrice?:number;packagesForNeed?:number;purchaseCostForNeed?:number;leftoverInBase?:number;}
export interface ComparisonOptions{neededQuantityInBase?:number;wastePercent?:number;includeTax?:boolean;}
export function parseFlexibleNumber(v:string|number):number{return parseHumanNumber(v)??0;}function nearlyEqual(a:number,b:number){return Math.abs(a-b)<=Math.max(1,Math.abs(a),Math.abs(b))*1e-9;}
function basisInfo(category:UnitCategory,basis:NormalizationBasis){if(basis==='hundred'){if(category==='weight')return{multiplier:100,label:'100g'};if(category==='volume')return{multiplier:100,label:'100ml'};}if(basis==='base')return{multiplier:1,label:category==='weight'?'g':category==='volume'?'ml':category==='area'?'m²':category==='length'?'m':'item'};return category==='weight'?{multiplier:1000,label:'kg'}:category==='volume'?{multiplier:1000,label:'L'}:category==='area'?{multiplier:1,label:'m²'}:category==='length'?{multiplier:1,label:'m'}:{multiplier:1,label:'item'};}
export function calculateEffectiveProductPrice(product:ProductItem,includeTax=true):number{let price=Math.max(0,Number.isFinite(product.price)?product.price:0);price=Math.max(0,price-Math.max(0,product.discountAmount||0))+Math.max(0,product.feeAmount||0)+Math.max(0,product.depositAmount||0);if(includeTax&&product.taxPercent&&product.taxPercent>0)price*=1+product.taxPercent/100;return price;}
export function calculateRequiredPurchase(totalQuantityInBase:number,effectivePrice:number,neededQuantityInBase:number,wastePercent=0):{packages:number;cost:number;leftover:number}|null{if(totalQuantityInBase<=0||effectivePrice<0||neededQuantityInBase<=0)return null;const needed=neededQuantityInBase*(1+Math.max(0,wastePercent)/100),packages=Math.ceil(needed/totalQuantityInBase),purchased=packages*totalQuantityInBase;return{packages,cost:packages*effectivePrice,leftover:Math.max(0,purchased-neededQuantityInBase)};}
export function evaluateProducts(products:ProductItem[],basis:NormalizationBasis='standard',options:ComparisonOptions={}):{items:EvaluatedProduct[];hasMismatchedCategories:boolean;primaryCategory:UnitCategory|null;hasIncompleteData:boolean}{if(!products.length)return{items:[],hasMismatchedCategories:false,primaryCategory:null,hasIncompleteData:false};const defs=products.map(p=>SUPPORTED_UNITS.find(u=>u.id===p.unitId)),cats=defs.map(d=>d?.category||'count' as UnitCategory),primaryCategory=cats[0],hasMismatchedCategories=cats.some(c=>c!==primaryCategory);let hasIncompleteData=false;const items=products.map((p,i)=>{const d=defs[i]||{id:p.unitId,label:p.unitId,category:'count' as UnitCategory,baseRatio:1,displayStandardUnit:'item'},count=Number.isFinite(p.packCount)&&p.packCount>0?p.packCount:1,size=Number.isFinite(p.unitSize)&&p.unitSize>0?p.unitSize:0,effective=calculateEffectiveProductPrice(p,options.includeTax??true);if(size<=0||effective<=0||!defs[i])hasIncompleteData=true;const quantity=count*size*d.baseRatio,per=quantity>0?effective/quantity:0,b=basisInfo(d.category,basis),purchase=options.neededQuantityInBase?calculateRequiredPurchase(quantity,effective,options.neededQuantityInBase,options.wastePercent):null;return{id:p.id,name:p.name||'Unnamed Item',totalPrice:Number.isFinite(p.price)&&p.price>=0?p.price:0,totalQuantityInBase:quantity,pricePerBaseUnit:per,pricePerStandardUnit:per*b.multiplier,standardUnitLabel:b.label,unitCategory:d.category,isBestValue:false,isTie:false,savingsPercentageVsWorst:0,savingsPercentageVsNext:0,priceDifferenceVsBest:0,effectivePrice:effective,packagesForNeed:purchase?.packages,purchaseCostForNeed:purchase?.cost,leftoverInBase:purchase?.leftover};});if(!hasMismatchedCategories){const valid=items.filter(x=>x.pricePerBaseUnit>0).sort((a,b)=>a.pricePerBaseUnit-b.pricePerBaseUnit);if(valid.length){const best=valid[0].pricePerBaseUnit,worst=valid.at(-1)!.pricePerBaseUnit,bestItems=valid.filter(x=>nearlyEqual(x.pricePerBaseUnit,best)),next=valid.find(x=>!nearlyEqual(x.pricePerBaseUnit,best));for(const item of items){if(item.pricePerBaseUnit<=0)continue;item.isBestValue=nearlyEqual(item.pricePerBaseUnit,best);item.isTie=item.isBestValue&&bestItems.length>1;item.savingsPercentageVsWorst=worst?Number(((worst-item.pricePerBaseUnit)/worst*100).toFixed(2)):0;if(item.isBestValue&&next)item.savingsPercentageVsNext=Number(((next.pricePerBaseUnit-best)/next.pricePerBaseUnit*100).toFixed(2));item.priceDifferenceVsBest=Number(((item.pricePerBaseUnit-best)*basisInfo(item.unitCategory,basis).multiplier).toFixed(6));}}}return{items,hasMismatchedCategories,primaryCategory,hasIncompleteData};}
export function rankProductsForNeed(products:ProductItem[],neededQuantityInBase:number,basis:NormalizationBasis='standard',wastePercent=0):EvaluatedProduct[]{return evaluateProducts(products,basis,{neededQuantityInBase,wastePercent}).items.slice().sort((a,b)=>(a.purchaseCostForNeed??Infinity)-(b.purchaseCostForNeed??Infinity)||a.pricePerBaseUnit-b.pricePerBaseUnit);}
