export type WatermarkPosition='top-left'|'top-center'|'top-right'|'center-left'|'center'|'center-right'|'bottom-left'|'bottom-center'|'bottom-right'|'custom'|'tiled';
export interface WatermarkConfig{type:'text'|'logo';text:string;fontFamily:string;fontSizeRatio:number;fontWeight:'normal'|'bold'|'900';color:string;opacity:number;rotationDeg:number;position:WatermarkPosition;customXPercent:number;customYPercent:number;paddingPx:number;tileSpacingPx:number;logoDataUrl?:string;logoScaleRatio:number;strokeColor?:string;strokeWidthRatio?:number;blendMode?:GlobalCompositeOperation;staggerTiles?:boolean;}
export const DEFAULT_WATERMARK_CONFIG:WatermarkConfig={type:'text',text:'CONFIDENTIAL',fontFamily:'Inter, system-ui, sans-serif',fontSizeRatio:.05,fontWeight:'bold',color:'#ffffff',opacity:.7,rotationDeg:0,position:'bottom-right',customXPercent:50,customYPercent:50,paddingPx:24,tileSpacingPx:120,logoScaleRatio:.2,strokeColor:'#000000',strokeWidthRatio:0,blendMode:'source-over',staggerTiles:true};
export function normalizeWatermarkConfig(c:WatermarkConfig):WatermarkConfig{return{...DEFAULT_WATERMARK_CONFIG,...c,fontSizeRatio:Math.max(.005,Math.min(.5,c.fontSizeRatio||.05)),opacity:Math.max(0,Math.min(1,c.opacity)),rotationDeg:((c.rotationDeg%360)+360)%360,customXPercent:Math.max(0,Math.min(100,c.customXPercent)),customYPercent:Math.max(0,Math.min(100,c.customYPercent)),paddingPx:Math.max(0,c.paddingPx),tileSpacingPx:Math.max(20,c.tileSpacingPx),logoScaleRatio:Math.max(.01,Math.min(1,c.logoScaleRatio)),strokeWidthRatio:Math.max(0,Math.min(.2,c.strokeWidthRatio||0))};}
export interface WatermarkTemplateContext{filename?:string;date?:Date;index?:number;total?:number;}
export function resolveWatermarkTemplate(text:string,ctx:WatermarkTemplateContext={}):string{const date=ctx.date||new Date(),filename=ctx.filename||'';return text.replace(/\{filename\}/gi,filename).replace(/\{stem\}/gi,filename.replace(/\.[^.]+$/,'')).replace(/\{date\}/gi,date.toISOString().slice(0,10)).replace(/\{index\}/gi,String(ctx.index??1)).replace(/\{total\}/gi,String(ctx.total??1));}
export function calculateWatermarkCoordinates(w:number,h:number,ew:number,eh:number,pos:WatermarkPosition,pad:number,cx=50,cy=50){switch(pos){case'top-left':return{x:pad,y:pad};case'top-center':return{x:(w-ew)/2,y:pad};case'top-right':return{x:w-ew-pad,y:pad};case'center-left':return{x:pad,y:(h-eh)/2};case'center':return{x:(w-ew)/2,y:(h-eh)/2};case'center-right':return{x:w-ew-pad,y:(h-eh)/2};case'bottom-left':return{x:pad,y:h-eh-pad};case'bottom-center':return{x:(w-ew)/2,y:h-eh-pad};case'bottom-right':return{x:w-ew-pad,y:h-eh-pad};case'custom':return{x:w*cx/100-ew/2,y:h*cy/100-eh/2};default:return{x:pad,y:pad};}}
export function calculateRotatedBounds(width:number,height:number,deg:number){const r=deg*Math.PI/180,c=Math.abs(Math.cos(r)),s=Math.abs(Math.sin(r));return{width:width*c+height*s,height:width*s+height*c};}
export function clampRotatedWatermarkCenter(w:number,h:number,x:number,y:number,ew:number,eh:number,deg:number,padding=0){const b=calculateRotatedBounds(ew,eh,deg),p=Math.max(0,padding),minX=p+b.width/2,maxX=w-p-b.width/2,minY=p+b.height/2,maxY=h-p-b.height/2;return{x:minX>maxX?w/2:Math.max(minX,Math.min(maxX,x)),y:minY>maxY?h/2:Math.max(minY,Math.min(maxY,y))};}
export function calculateTileCenters(width:number,height:number,spacing:number,stagger=true):Array<{x:number;y:number}>{const s=Math.max(20,spacing),diag=Math.hypot(width,height),centers:Array<{x:number;y:number}>=[];let row=0;for(let y=-diag;y<=height+diag;y+=s,row++){const shift=stagger&&row%2?s*.55:0;for(let x=-diag+shift;x<=width+diag;x+=s*1.5)centers.push({x,y});}return centers;}
function renderText(ctx:CanvasRenderingContext2D,text:string,fontSize:number,c:WatermarkConfig){ctx.font=`${c.fontWeight} ${fontSize}px ${c.fontFamily}`;ctx.textAlign='center';ctx.textBaseline='middle';if((c.strokeWidthRatio||0)>0){ctx.strokeStyle=c.strokeColor||'#000';ctx.lineWidth=Math.max(1,fontSize*(c.strokeWidthRatio||0));ctx.strokeText(text,0,0);}ctx.fillStyle=c.color;ctx.fillText(text,0,0);}
export async function applyWatermarkToImage(image:HTMLImageElement|ImageBitmap,config:WatermarkConfig,logoImg?:HTMLImageElement|null,template:WatermarkTemplateContext={}):Promise<HTMLCanvasElement>{const c=normalizeWatermarkConfig(config),canvas=document.createElement('canvas'),width=image.width,height=image.height;canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Could not obtain canvas 2D rendering context.');ctx.drawImage(image,0,0,width,height);ctx.save();ctx.globalAlpha=c.opacity;ctx.globalCompositeOperation=c.blendMode||'source-over';const fontSize=Math.max(14,Math.round(height*c.fontSizeRatio)),text=resolveWatermarkTemplate(c.text,template),rad=c.rotationDeg*Math.PI/180;if(c.position==='tiled'){for(const center of calculateTileCenters(width,height,c.tileSpacingPx,c.staggerTiles!==false)){ctx.save();ctx.translate(center.x,center.y);ctx.rotate(rad);if(c.type==='text')renderText(ctx,text,fontSize,c);else if(logoImg){const lw=Math.max(20,width*c.logoScaleRatio),lh=lw/logoImg.width*logoImg.height;ctx.drawImage(logoImg,-lw/2,-lh/2,lw,lh);}ctx.restore();}}else if(c.type==='text'){ctx.font=`${c.fontWeight} ${fontSize}px ${c.fontFamily}`;const m=ctx.measureText(text),tw=Math.max(1,m.width),th=Math.max(fontSize,(m.actualBoundingBoxAscent||fontSize)+(m.actualBoundingBoxDescent||0)),pos=calculateWatermarkCoordinates(width,height,tw,th,c.position,c.paddingPx,c.customXPercent,c.customYPercent),center=clampRotatedWatermarkCenter(width,height,pos.x+tw/2,pos.y+th/2,tw,th,c.rotationDeg,c.paddingPx);ctx.translate(center.x,center.y);ctx.rotate(rad);renderText(ctx,text,fontSize,c);}else if(logoImg){const lw=Math.max(20,width*c.logoScaleRatio),lh=lw/logoImg.width*logoImg.height,pos=calculateWatermarkCoordinates(width,height,lw,lh,c.position,c.paddingPx,c.customXPercent,c.customYPercent),center=clampRotatedWatermarkCenter(width,height,pos.x+lw/2,pos.y+lh/2,lw,lh,c.rotationDeg,c.paddingPx);ctx.translate(center.x,center.y);ctx.rotate(rad);ctx.drawImage(logoImg,-lw/2,-lh/2,lw,lh);}ctx.restore();return canvas;}
export async function applyWatermarkBatch(items:Array<{image:HTMLImageElement|ImageBitmap;filename:string}>,config:WatermarkConfig,logo?:HTMLImageElement|null):Promise<HTMLCanvasElement[]>{const total=items.length,results:HTMLCanvasElement[]=[];for(let i=0;i<items.length;i++)results.push(await applyWatermarkToImage(items[i].image,config,logo,{filename:items[i].filename,index:i+1,total}));return results;}
