export interface WordCounterStats{words:number;charactersWithSpaces:number;charactersWithoutSpaces:number;sentences:number;paragraphs:number;lines:number;uniqueWords:number;averageWordLength:number;readingTimeSeconds:number;speakingTimeSeconds:number;longestWord:string;topWords:Array<{word:string;count:number;percentage:number}>;graphemes:number;averageSentenceLength:number;lexicalDensity:number;fleschReadingEase:number|null;}
export interface WordCounterSettings{readingWpm:number;speakingWpm:number;locale?:string;}export const defaultCounterSettings:WordCounterSettings={readingWpm:200,speakingWpm:130};
function segment(locale:string|undefined,granularity:'word'|'sentence'|'grapheme',text:string):Array<{segment:string;isWordLike?:boolean}>{try{const Segmenter=(Intl as typeof Intl&{Segmenter?:new(locale?:string|string[],options?:{granularity:string})=>{segment:(text:string)=>Iterable<{segment:string;isWordLike?:boolean}>}}).Segmenter;if(Segmenter)return Array.from(new Segmenter(locale,{granularity}).segment(text));}catch{}if(granularity==='sentence')return text.split(/(?<=[.!?。！？])\s+|\n+/u).filter(Boolean).map(segment=>({segment}));if(granularity==='grapheme')return Array.from(text).map(segment=>({segment}));return(text.match(/[\p{L}\p{N}]+(?:['’\-][\p{L}\p{N}]+)*/gu)||[]).map(segment=>({segment,isWordLike:true}));}
function wordSegments(text:string,locale?:string):string[]{return segment(locale,'word',text).filter(p=>p.isWordLike!==false&&/[\p{L}\p{N}]/u.test(p.segment)).map(p=>p.segment);}
function countSyllablesEnglish(word:string):number{const w=word.toLowerCase().replace(/[^a-z]/g,'');if(!w)return 0;if(w.length<=3)return 1;const stripped=w.replace(/(?:e|es|ed)$/,'');return Math.max(1,(stripped.match(/[aeiouy]+/g)||[]).length);}
export function countWordsAndStats(text:string,settings:WordCounterSettings=defaultCounterSettings):WordCounterStats{const charactersWithSpaces=text?.length||0,charactersWithoutSpaces=(text||'').replace(/\s/g,'').length,lines=text?text.split(/\r\n|\r|\n/).length:0;if(!text||!text.trim())return{words:0,charactersWithSpaces,charactersWithoutSpaces,sentences:0,paragraphs:0,lines,uniqueWords:0,averageWordLength:0,readingTimeSeconds:0,speakingTimeSeconds:0,longestWord:'',topWords:[],graphemes:segment(settings.locale,'grapheme',text||'').length,averageSentenceLength:0,lexicalDensity:0,fleschReadingEase:null};const rawWords=wordSegments(text,settings.locale),words=rawWords.map(w=>w.toLocaleLowerCase(settings.locale)),sentences=Math.max(1,segment(settings.locale,'sentence',text).filter(s=>s.segment.trim()).length),paragraphs=Math.max(1,text.split(/\n\s*\n/).filter(p=>p.trim()).length),freq=new Map<string,number>();let letters=0,longestWord='';for(const w of words){const len=Array.from(w).length;letters+=len;if(len>Array.from(longestWord).length)longestWord=w;freq.set(w,(freq.get(w)||0)+1);}const count=words.length,uniqueWords=freq.size,topWords=[...freq].sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,10).map(([word,n])=>({word,count:n,percentage:count?Number((n/count*100).toFixed(1)):0})),latinWords=words.filter(w=>/^[a-z]+(?:['’-][a-z]+)*$/i.test(w)),syllables=latinWords.reduce((sum,w)=>sum+countSyllablesEnglish(w),0),flesch=latinWords.length===count&&count>0?Number((206.835-1.015*(count/sentences)-84.6*(syllables/count)).toFixed(1)):null;return{words:count,charactersWithSpaces,charactersWithoutSpaces,sentences,paragraphs,lines,uniqueWords,averageWordLength:count?Number((letters/count).toFixed(1)):0,readingTimeSeconds:Math.ceil(count/Math.max(10,settings.readingWpm||200)*60),speakingTimeSeconds:Math.ceil(count/Math.max(10,settings.speakingWpm||130)*60),longestWord,topWords,graphemes:segment(settings.locale,'grapheme',text).length,averageSentenceLength:Number((count/sentences).toFixed(1)),lexicalDensity:count?Number((uniqueWords/count*100).toFixed(1)):0,fleschReadingEase:flesch};}
export function formatTimeEstimate(seconds:number):string{if(seconds<=0)return'0s';if(seconds<60)return`${seconds}s`;const h=Math.floor(seconds/3600),m=Math.floor(seconds%3600/60),s=seconds%60;return h?`${h}h ${m}m${s?` ${s}s`:''}`:s?`${m}m ${s}s`:`${m}m`;}
export function analyzeScriptMix(text:string):Record<'latin'|'cjk'|'hangul'|'arabic'|'cyrillic'|'other',number>{const counts={latin:0,cjk:0,hangul:0,arabic:0,cyrillic:0,other:0};for(const char of text){if(/\p{Script=Latin}/u.test(char))counts.latin++;else if(/\p{Script=Han}|\p{Script=Hiragana}|\p{Script=Katakana}/u.test(char))counts.cjk++;else if(/\p{Script=Hangul}/u.test(char))counts.hangul++;else if(/\p{Script=Arabic}/u.test(char))counts.arabic++;else if(/\p{Script=Cyrillic}/u.test(char))counts.cyrillic++;else if(/\p{L}/u.test(char))counts.other++;}return counts;}
export const calculateWordStats=countWordsAndStats;
