import JSZip from 'jszip';
export interface ArchiveEntry{path:string;name:string;isFolder:boolean;uncompressedSize:number;compressedSize?:number;date?:Date;comment?:string;}
export interface PendingZipFile{id:string;file:File;relativePath:string;size:number;}
export interface ArchiveSafetyOptions{maxEntries?:number;maxTotalUncompressedBytes?:number;maxSingleEntryBytes?:number;maxCompressionRatio?:number;maxPathLength?:number;verifyCrc32?:boolean;}
export const DEFAULT_ARCHIVE_SAFETY:Required<ArchiveSafetyOptions>={maxEntries:5000,maxTotalUncompressedBytes:2*1024**3,maxSingleEntryBytes:1024**3,maxCompressionRatio:250,maxPathLength:1024,verifyCrc32:false};
export function sanitizeZipPath(raw:string):string{const normalized=raw.replace(/\\/g,'/').replace(/^\/+/,'');const safe:string[]=[];for(const segment of normalized.split('/').filter(Boolean)){if(segment==='.')continue;if(segment==='..'){safe.pop();continue;}safe.push(segment.replace(/[\u0000-\u001f\u007f]/g,''));}return safe.join('/');}
export function analyzeZipPath(raw:string):{safePath:string;changed:boolean;warnings:string[]}{const safePath=sanitizeZipPath(raw),warnings:string[]=[];if(raw.includes('\\'))warnings.push('Backslashes were normalized to archive separators.');if(/(^|\/)\.\.?(\/|$)/.test(raw.replace(/\\/g,'/')))warnings.push('Traversal segments were removed.');if(/^[/\\]/.test(raw))warnings.push('Absolute archive path was made relative.');if(/[\u0000-\u001f\u007f]/.test(raw))warnings.push('Control characters were removed.');return{safePath,changed:safePath!==raw.replace(/\\/g,'/').replace(/^\/+/,'').replace(/\/$/,''),warnings};}
export interface CentralDirectoryEntry{rawPath:string;compressedSize:number;uncompressedSize:number;compressionMethod:number;encrypted:boolean;crc32:number;}
function u16(v:DataView,o:number){return v.getUint16(o,true);}function u32(v:DataView,o:number){return v.getUint32(o,true);}
async function bytesOf(input:Blob|ArrayBuffer|Uint8Array):Promise<Uint8Array>{if(input instanceof Uint8Array)return input;if(input instanceof ArrayBuffer)return new Uint8Array(input);return new Uint8Array(await input.arrayBuffer());}
export async function inspectZipCentralDirectory(input:Blob|ArrayBuffer|Uint8Array):Promise<{entries:CentralDirectoryEntry[];totalCompressedSize:number;totalUncompressedSize:number}>{const bytes=await bytesOf(input),view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let eocd=-1;for(let i=Math.max(0,bytes.length-65557);i<=bytes.length-22;i++)if(u32(view,i)===0x06054b50)eocd=i;if(eocd<0)throw new Error('ZIP end-of-central-directory record not found.');const total=u16(view,eocd+10),cdOffset=u32(view,eocd+16);if(total===0xffff||cdOffset===0xffffffff)throw new Error('ZIP64 archive requires metadata beyond the safe browser preflight supported here.');let offset=cdOffset,totalCompressed=0,totalUncompressed=0;const entries:CentralDirectoryEntry[]=[];const decoder=new TextDecoder('utf-8');for(let index=0;index<total;index++){if(offset+46>bytes.length||u32(view,offset)!==0x02014b50)throw new Error('Malformed ZIP central directory.');const flags=u16(view,offset+8),method=u16(view,offset+10),crc=u32(view,offset+16),compressed=u32(view,offset+20),uncompressed=u32(view,offset+24),nameLen=u16(view,offset+28),extraLen=u16(view,offset+30),commentLen=u16(view,offset+32);if(compressed===0xffffffff||uncompressed===0xffffffff)throw new Error('ZIP64 entry requires unsupported extended size metadata.');const start=offset+46,end=start+nameLen;if(end>bytes.length)throw new Error('Malformed ZIP filename record.');const rawPath=decoder.decode(bytes.subarray(start,end));entries.push({rawPath,compressedSize:compressed,uncompressedSize:uncompressed,compressionMethod:method,encrypted:Boolean(flags&1),crc32:crc});totalCompressed+=compressed;totalUncompressed+=uncompressed;offset=end+extraLen+commentLen;}return{entries,totalCompressedSize:totalCompressed,totalUncompressedSize:totalUncompressed};}
export async function parseZipArchive(input:Blob|ArrayBuffer|Uint8Array,options:ArchiveSafetyOptions={}):Promise<{entries:ArchiveEntry[];totalUncompressedSize:number;zipInstance:JSZip}>{const limits={...DEFAULT_ARCHIVE_SAFETY,...options},preflight=await inspectZipCentralDirectory(input);if(preflight.entries.length>limits.maxEntries)throw new Error(`Archive contains ${preflight.entries.length.toLocaleString()} entries; safety limit is ${limits.maxEntries.toLocaleString()}.`);if(preflight.totalUncompressedSize>limits.maxTotalUncompressedBytes)throw new Error('Archive expands beyond the configured safety limit.');const metadata=new Map(preflight.entries.map(e=>[e.rawPath,e]));const paths=new Set<string>();for(const entry of preflight.entries){if(entry.encrypted)throw new Error(`Encrypted ZIP entries are not supported: ${entry.rawPath}`);if(entry.uncompressedSize>limits.maxSingleEntryBytes)throw new Error(`Archive entry is too large to open safely: ${entry.rawPath}`);if(entry.compressedSize>0&&entry.uncompressedSize/entry.compressedSize>limits.maxCompressionRatio)throw new Error(`Archive entry has a suspicious compression ratio: ${entry.rawPath}`);const safe=sanitizeZipPath(entry.rawPath);if(safe.length>limits.maxPathLength)throw new Error(`Archive path is too long: ${safe.slice(0,80)}…`);const key=safe.toLocaleLowerCase();if(safe&&paths.has(key))throw new Error(`Archive contains multiple entries that resolve to the same safe path: ${safe}`);if(safe)paths.add(key);}const zip=await new JSZip().loadAsync(input,{checkCRC32:limits.verifyCrc32});const entries:ArchiveEntry[]=[];for(const[rawPath,obj]of Object.entries(zip.files)){const safe=sanitizeZipPath(rawPath),meta=metadata.get(rawPath),isFolder=obj.dir||rawPath.endsWith('/');if(!safe&&!isFolder)throw new Error('Archive contains an invalid empty file path.');const parts=safe.split('/');entries.push({path:safe,name:parts.at(-1)||safe,isFolder,uncompressedSize:meta?.uncompressedSize||0,compressedSize:meta?.compressedSize||undefined,date:obj.date,comment:obj.comment});}return{entries,totalUncompressedSize:preflight.totalUncompressedSize,zipInstance:zip};}
export async function createZipArchive(files:PendingZipFile[],compressionLevel:'STORE'|'DEFLATE'='DEFLATE',onProgress?:(percent:number)=>void):Promise<Blob>{const used=new Set<string>(),planned=files.map(item=>{const safe=sanitizeZipPath(item.relativePath||item.file.name);if(!safe)throw new Error(`Invalid archive path for ${item.file.name}.`);const key=safe.toLocaleLowerCase();if(used.has(key))throw new Error(`Two files resolve to the same archive path: ${safe}`);used.add(key);return{item,safe};}),zip=new JSZip();for(const{item,safe}of planned)zip.file(safe,await item.file.arrayBuffer());return zip.generateAsync({type:'blob',compression:compressionLevel,compressionOptions:{level:compressionLevel==='DEFLATE'?6:1},platform:'DOS'},m=>onProgress?.(Math.round(m.percent)));}
export async function extractZipEntrySafe(zip:JSZip,path:string,maxBytes=256*1024*1024):Promise<Blob>{const safe=sanitizeZipPath(path),entry=zip.file(path)||zip.file(safe);if(!entry)throw new Error('Archive entry was not found.');const blob=await entry.async('blob');if(blob.size>maxBytes)throw new Error('Extracted entry exceeds the configured safety limit.');return blob;}
export function formatArchiveSize(bytes:number):string{if(!Number.isFinite(bytes)||bytes<=0)return'0 B';const units=['B','KB','MB','GB','TB'],i=Math.min(units.length-1,Math.floor(Math.log(bytes)/Math.log(1024)));return`${parseFloat((bytes/1024**i).toFixed(2))} ${units[i]}`;}
