import{describe,expect,it}from'vitest';
import{registerAllPublicTools}from'../registry/register-all';
import{TOOLS_REGISTRY}from'../registry/tools';
import{normalizeToolShellId}from'../registry/tool-shell-mode';
import{audioTargets,DATA_FORMATS,detectDataFormat,detectDocumentFormat,detectSubtitleFormat,documentTextViews,DOCUMENT_INPUT_FORMATS,DOCUMENT_OUTPUT_FORMATS,SUBTITLE_CONVERTER_FORMATS}from'../utilities/unified-converters';
registerAllPublicTools();
const canonical=['document-converter','data-converter','image-converter','audio-converter','video-converter','subtitle-converter','archive-converter'];
const removed=['create-pdf','export-pdf','csv-to-json','json-to-csv','csv-to-xlsx','xlsx-to-csv','yaml-json-converter','toml-json-converter','markdown-html-converter','docx-to-markdown','markdown-to-docx','epub-to-text','pptx-to-markdown','heic-image-converter','avif-image-converter','svg-to-image','image-format-converter','batch-image-converter','audio-to-wav-converter','srt-to-vtt','vtt-to-srt','subtitle-to-text','transcript-to-subtitles'];
describe('converter consolidation',()=>{
 it('publishes canonical converter families instead of pairwise routes',()=>{expect(TOOLS_REGISTRY).toHaveLength(320);for(const id of canonical)expect(TOOLS_REGISTRY.some(t=>t.id===id),id).toBe(true);for(const id of removed)expect(TOOLS_REGISTRY.some(t=>t.id===id),id).toBe(false)});
 it('preserves old converter hashes through canonical aliases',()=>{expect(normalizeToolShellId('csv-to-json')).toBe('data-converter');expect(normalizeToolShellId('docx-to-markdown')).toBe('document-converter');expect(normalizeToolShellId('heic-image-converter')).toBe('image-converter');expect(normalizeToolShellId('audio-to-wav-converter')).toBe('audio-converter');expect(normalizeToolShellId('srt-to-vtt')).toBe('subtitle-converter');expect(normalizeToolShellId('create-pdf')).toBe('document-converter')});
 it('exposes broad document/data/subtitle format matrices',()=>{expect(DOCUMENT_INPUT_FORMATS).toEqual(['txt','md','html','docx','epub','pptx','pdf']);expect(DOCUMENT_OUTPUT_FORMATS).toEqual(['txt','md','html','docx','epub','pdf']);expect(DATA_FORMATS).toEqual(['csv','json','xml','xlsx','yaml','toml']);expect(SUBTITLE_CONVERTER_FORMATS).toEqual(['srt','vtt','txt'])});
 it('detects common aliases and extensions',()=>{expect(detectDocumentFormat('report.DOCX')).toBe('docx');expect(detectDocumentFormat('slides.pptx')).toBe('pptx');expect(detectDataFormat('config.yml')).toBe('yaml');expect(detectDataFormat('sheet.xlsx')).toBe('xlsx');expect(detectSubtitleFormat('captions.webvtt')).toBe('vtt')});
 it('normalizes plain text, Markdown, and HTML into reusable document views',()=>{const md=documentTextViews('# Title\n\n**Bold**','md');expect(md.html).toContain('<h1>Title</h1>');expect(md.text).toContain('Bold');const html=documentTextViews('<h1>Title</h1><p>Hello</p>','html');expect(html.markdown).toContain('# Title');expect(html.text).toContain('Hello');const text=documentTextViews('One\n\nTwo','txt');expect(text.html).toContain('<p>One</p>')});
 it('always exposes WAV while capability-gating compressed audio outputs',()=>{expect(audioTargets(()=>false)).toEqual([{label:'WAV (PCM)',mime:'audio/wav',extension:'wav',realtime:false}]);const supported=audioTargets(m=>m.startsWith('audio/webm'));expect(supported.map(x=>x.extension)).toEqual(['wav','webm'])});
 it('keeps canonical converter metadata broad enough for historical search intents',()=>{const byId=(id:string)=>TOOLS_REGISTRY.find(t=>t.id===id)!;expect(byId('document-converter').keywords.join(' ')).toMatch(/docx.*markdown.*html.*text.*epub.*pdf.*pptx/i);expect(byId('data-converter').keywords.join(' ')).toMatch(/csv.*json.*xml.*xlsx.*yaml.*toml/i);expect(byId('image-converter').keywords.join(' ')).toMatch(/jpg.*png.*webp.*avif/i);expect(byId('audio-converter').keywords.join(' ')).toMatch(/mp3.*wav.*m4a.*aac.*ogg.*opus.*flac/i);expect(byId('subtitle-converter').keywords.join(' ')).toMatch(/srt.*vtt/i)});
});
