import{describe,expect,it}from'vitest';
import{PUBLIC_P11_TASKS}from'../expansion/publicP11Tasks';
import{TOOLS_REGISTRY}from'../registry/tools';
import{registerAllPublicTools}from'../registry/register-all';
import{calculateSubnet,decodeBaseText,encodeBaseText,evaluateJsonPath,formatSql,formatToml,formatYaml,jsonToToml,jsonToYaml,parseTomlSubset,parseYamlSubset,validateJsonSchema}from'../utilities/p11-developer';
import{gcdBig,lcmBig,linearRegression,matrixDeterminant,matrixInverse,matrixMultiply,nCr,nPr,normalStats,parseMatrix,primeFactors,solveQuadratic,vectorCross,vectorDot}from'../utilities/p11-math';
import{buildRobotsTxt,buildSitemapXml,buildVCard,generateTotp,minifyCss,optimizeSvg,printSizeFromPixels,simulateColorVision}from'../utilities/p11-web';
registerAllPublicTools();
describe('P11 high-value tool expansion',()=>{
 it('retains 26 unique P11 public routes after converter consolidation',()=>{expect(PUBLIC_P11_TASKS).toHaveLength(26);expect(new Set(PUBLIC_P11_TASKS.map(t=>t.id)).size).toBe(26);for(const task of PUBLIC_P11_TASKS)expect(TOOLS_REGISTRY.some(t=>t.id===task.id)).toBe(true)});
 it('keeps YAML/TOML transformation engines reusable by the unified data converter',()=>{const y='name: Tiny\ntags:\n  - local\n  - fast';expect(parseYamlSubset(y)).toEqual({name:'Tiny',tags:['local','fast']});expect(formatYaml(y)).toContain('tags:');expect(parseYamlSubset(jsonToYaml({a:1,b:true}))).toEqual({a:1,b:true});const t='title = "Tiny"\n[owner]\nname = "Ada"';expect(parseTomlSubset(t)).toEqual({title:'Tiny',owner:{name:'Ada'}});expect(parseTomlSubset(formatToml(t))).toEqual({title:'Tiny',owner:{name:'Ada'}});expect(parseTomlSubset(jsonToToml({x:1,nested:{y:false}}))).toEqual({x:1,nested:{y:false}})});
 it('handles SQL, schema validation, JSONPath, encodings, and IPv4 CIDR',()=>{expect(formatSql('select a,b from t where a=1 and b=2')).toContain('\nFROM');expect(validateJsonSchema({name:'x'},{type:'object',required:['name'],properties:{name:{type:'string',minLength:2}}})).toHaveLength(1);expect(evaluateJsonPath({a:[1,2]},'$.a[*]')).toEqual([1,2]);for(const enc of ['base32','base58','base85']as const)expect(decodeBaseText(encodeBaseText('Tiny Tools',enc),enc)).toBe('Tiny Tools');expect(calculateSubnet('192.168.1.42/24')).toMatchObject({network:'192.168.1.0',broadcast:'192.168.1.255',usableHosts:254})});
 it('calculates matrices, combinatorics, distributions, regression, integer math, quadratics, and vectors',()=>{const a=parseMatrix('1 2\n3 4'),b=parseMatrix('5 6\n7 8');expect(matrixDeterminant(a)).toBeCloseTo(-2);expect(matrixMultiply(a,b)).toEqual([[19,22],[43,50]]);expect(matrixInverse(a)[0][0]).toBeCloseTo(-2);expect(nCr(10,3)).toBe(120n);expect(nPr(10,3)).toBe(720n);expect(normalStats(0,0,1).cdf).toBeCloseTo(.5,5);const reg=linearRegression([1,2,3],[2,4,6]);expect(reg.slope).toBeCloseTo(2);expect(reg.r2).toBeCloseTo(1);expect(gcdBig(18n,24n)).toBe(6n);expect(lcmBig(18n,24n)).toBe(72n);expect(primeFactors(84n)).toEqual([[2n,2],[3n,1],[7n,1]]);expect(solveQuadratic(1,-3,2).roots).toEqual([2,1]);expect(vectorDot([1,2,3],[4,5,6])).toBe(32);expect(vectorCross([1,0,0],[0,1,0])).toEqual([0,0,1])});
 it('builds and transforms web/design outputs locally',()=>{expect(optimizeSvg('<svg><!--x--><circle cx="1" /></svg>')).toBe('<svg><circle cx="1"/></svg>');expect(printSizeFromPixels(3000,1500,300)).toMatchObject({widthIn:10,heightIn:5});expect(simulateColorVision('#FF0000','grayscale').output).toMatch(/^#[0-9A-F]{6}$/);expect(buildRobotsTxt([{agent:'*',allow:[],disallow:['/private']}],['https://example.com/sitemap.xml'])).toContain('Disallow: /private');expect(buildSitemapXml([{loc:'https://example.com/'}])).toContain('<loc>https://example.com/</loc>');expect(buildVCard({first:'Ada',last:'Lovelace'})).toContain('FN:Ada Lovelace');expect(minifyCss('body { color: red; /* x */ margin: 0; }')).toBe('body{color:red;margin:0}')});
 it('matches the RFC 6238 SHA-1 TOTP vector',async()=>{const result=await generateTotp('GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ',{digits:8,period:30,timestamp:59000});expect(result.code).toBe('94287082')});
});