import{describe,expect,it}from'vitest';
import{PUBLIC_P12_TASKS}from'../expansion/publicP12Tasks';
import{TOOLS_REGISTRY}from'../registry/tools';
import{registerAllPublicTools}from'../registry/register-all';
import{buildQueryStringFromLines,compareSemver,dotenvObject,formatDotenv,formatXml,jsonToTypeScript,lookupMime,minifyHtml,normalizeUnicode,parseChmod,parseHttpHeaders,parseQueryString,parseUrl}from'../utilities/p12-developer';
import{buildBoxShadow,buildCssGradient,buildHtmlTable,buildMetaTags,buildSocialMeta,contrastRatio,cssClamp}from'../utilities/p12-web';
registerAllPublicTools();
describe('P12 web/developer authoring expansion',()=>{
 it('registers 18 unique routes and reaches 300 public tools',()=>{expect(PUBLIC_P12_TASKS).toHaveLength(18);expect(new Set(PUBLIC_P12_TASKS.map(t=>t.id)).size).toBe(18);expect(TOOLS_REGISTRY).toHaveLength(300);for(const task of PUBLIC_P12_TASKS)expect(TOOLS_REGISTRY.some(t=>t.id===task.id)).toBe(true)});
 it('formats XML and handles URLs and query strings',()=>{expect(formatXml('<a><b>1</b></a>')).toContain('  <b>');expect(()=>formatXml('<a></b>')).toThrow(/Mismatched/);expect(parseUrl('https://example.com/a?q=1#x')).toMatchObject({hostname:'example.com',pathname:'/a',hash:'#x'});expect(parseQueryString('?a=1&a=2').object).toEqual({a:['1','2']});expect(buildQueryStringFromLines('a=hello world\nb=2')).toBe('?a=hello+world&b=2')});
 it('compares SemVer and converts chmod modes',()=>{expect(compareSemver('1.0.0-alpha','1.0.0')).toBe(-1);expect(compareSemver('1.2.3+one','1.2.3+two')).toBe(0);expect(parseChmod('755')).toMatchObject({octal:'755',symbolic:'rwxr-xr-x'});expect(parseChmod('rw-r-----').octal).toBe('640')});
 it('generates TypeScript and parses developer text formats',()=>{const ts=jsonToTypeScript({id:1,owner:{name:'Ada'}},'Api');expect(ts).toContain('export interface Api');expect(ts).toContain('owner: ApiOwner;');expect(parseHttpHeaders('HTTP/1.1 200 OK\nContent-Type: application/json').headers['content-type']).toEqual(['application/json']);expect(lookupMime('.svg')).toMatchObject({mime:'image/svg+xml',known:true});expect(normalizeUnicode('e\u0301').NFC).toBe('é');expect(dotenvObject('A=1\nB="hello world"')).toEqual({A:'1',B:'hello world'});expect(formatDotenv(' A = 1 ')).toBe('A=1\n');expect(minifyHtml('<div>\n  <!--x--> <span>Hi</span>\n</div>')).toBe('<div><span>Hi</span></div>')});
 it('generates web metadata and CSS deterministically',()=>{expect(buildMetaTags({title:'Tiny',description:'Local'})).toContain('<meta name="description" content="Local">');expect(buildSocialMeta({title:'Tiny',url:'https://example.com'})).toContain('property="og:title"');expect(contrastRatio('#000','#fff').ratio).toBeCloseTo(21,5);expect(buildCssGradient('linear',[{color:'#000000',position:0},{color:'#FFFFFF',position:100}],90)).toContain('linear-gradient(90deg');expect(buildBoxShadow({x:0,y:2,blur:4,spread:0,color:'#000000',opacity:.25})).toContain('rgba(0, 0, 0, 0.25)');expect(cssClamp(16,32,320,1280).css).toContain('clamp(16px')});
 it('builds escaped semantic HTML tables',()=>{const table=buildHtmlTable('Name,Value\nA,<script>',{header:true,caption:'Data'});expect(table).toContain('<th scope="col">Name</th>');expect(table).toContain('&lt;script&gt;');expect(table).toContain('<caption>Data</caption>')});
});
