import{describe,expect,it}from'vitest';
import{PUBLIC_P14_TASKS}from'../expansion/publicP14Tasks';
import{TOOLS_REGISTRY}from'../registry/tools';
import{registerAllPublicTools}from'../registry/register-all';
import{canonicalizeJson,compareJson,decodeDerOid,generateSri,inspectPemEnvelope,verifyJwtSignature}from'../utilities/p14-security';
import{buildCsp,buildHreflang,buildJsonLd,buildPwaManifest,parseHar,serpPreview,slugify}from'../utilities/p14-web';
registerAllPublicTools();
function b64url(text:string){return Buffer.from(text).toString('base64url')}
async function hs256Token(secret:string){const h=b64url(JSON.stringify({alg:'HS256',typ:'JWT'})),p=b64url(JSON.stringify({sub:'123',admin:true})),data=`${h}.${p}`,key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']),sig=new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(data)));return`${data}.${Buffer.from(sig).toString('base64url')}`}
describe('P14 developer/security completion',()=>{
 it('retains 13 unique P14 routes in the expanded catalog',()=>{expect(PUBLIC_P14_TASKS).toHaveLength(13);expect(new Set(PUBLIC_P14_TASKS.map(t=>t.id)).size).toBe(13);for(const task of PUBLIC_P14_TASKS)expect(TOOLS_REGISTRY.some(t=>t.id===task.id)).toBe(true)});
 it('compares JSON structurally and creates stable sorted JSON',()=>{const d=compareJson('{"a":1,"b":{"x":2}}','{"a":1,"b":{"x":3,"y":4}}');expect(d.equal).toBe(false);expect(d.counts).toEqual({added:1,removed:0,changed:1});expect(d.changes.map(x=>x.path)).toEqual(['$.b.x','$.b.y']);expect(canonicalizeJson('{"z":1,"a":{"y":2,"b":3}}',true)).toBe('{"a":{"b":3,"y":2},"z":1}')});
 it('verifies HMAC JWT signatures and rejects the wrong secret',async()=>{const token=await hs256Token('tiny-secret');expect((await verifyJwtSignature(token,'tiny-secret')).valid).toBe(true);expect((await verifyJwtSignature(token,'wrong-secret')).valid).toBe(false)});
 it('generates SRI hashes and decodes basic PEM/DER metadata',async()=>{const sri=await generateSri(new TextEncoder().encode('hello'),'SHA-384');expect(sri).toMatch(/^sha384-[A-Za-z0-9+/]+=*$/);expect(await generateSri(new TextEncoder().encode('hello'),'SHA-384')).toBe(sri);expect(inspectPemEnvelope('-----BEGIN PUBLIC KEY-----\nAQID\n-----END PUBLIC KEY-----')).toEqual({label:'PUBLIC KEY',byteLength:3});expect(decodeDerOid(new Uint8Array([0x2a,0x86,0x48,0x86,0xf7,0x0d,0x01,0x01,0x01]))).toBe('1.2.840.113549.1.1.1')});
 it('builds CSP, manifest, JSON-LD, slugs, hreflang, and SERP guidance',()=>{expect(buildCsp({defaultSrc:"'self'",objectSrc:"'none'",upgradeInsecureRequests:true})).toBe("default-src 'self'; object-src 'none'; upgrade-insecure-requests;");expect(JSON.parse(buildPwaManifest({name:'Tiny Tools'}))).toMatchObject({name:'Tiny Tools',display:'standalone'});expect(buildJsonLd('WebSite',{name:'Tiny Tools'})).toContain('"@type": "WebSite"');expect(slugify('Tiny Tools: Déjà Vu')).toBe('tiny-tools-deja-vu');expect(buildHreflang([{lang:'en',url:'https://example.com/en'}],'https://example.com/')).toContain('hreflang="x-default"');expect(serpPreview('A'.repeat(61),'https://example.com','Description').titleGuidance).toMatch(/truncate/)});
 it('summarizes HAR network entries without external requests',()=>{const har=parseHar(JSON.stringify({log:{entries:[{request:{method:'GET',url:'https://example.com/a'},response:{status:200,headersSize:10,bodySize:20,content:{mimeType:'text/plain'}},time:12},{request:{method:'POST',url:'https://api.example.com/b'},response:{status:404,headersSize:5,bodySize:7,content:{mimeType:'application/json'}},time:30}]}}));expect(har.entryCount).toBe(2);expect(har.totalTransferBytes).toBe(42);expect(har.statusClasses).toEqual({'2xx':1,'4xx':1});expect(har.domains).toEqual(['api.example.com','example.com'])});
});
