import{describe,expect,it}from'vitest';
import{PUBLIC_P15_TASKS}from'../expansion/publicP15Tasks';
import{TOOLS_REGISTRY}from'../registry/tools';
import{registerAllPublicTools}from'../registry/register-all';
import{binomialPmf,binomialRange,chiSquareGoodness,csvNumericSeries,descriptiveStats,findPolynomialRealRoots,histogram,meanConfidenceInterval,oneSampleTTest,parseCoefficients,poissonPmf,proportionConfidenceInterval,sampleFunction,sampleSizeForProportion,scatterStats,solveLinearSystem,welchTTest}from'../utilities/p15-math-data';
registerAllPublicTools();
describe('P15 math and data visualization',()=>{
 it('retains 13 unique P15 routes in the expanded catalog',()=>{expect(PUBLIC_P15_TASKS).toHaveLength(13);expect(new Set(PUBLIC_P15_TASKS.map(t=>t.id)).size).toBe(13);for(const task of PUBLIC_P15_TASKS)expect(TOOLS_REGISTRY.some(t=>t.id===task.id)).toBe(true)});
 it('parses functions, explores polynomials, and solves linear systems',()=>{const pts=sampleFunction('sin(pi/2)+x^2',3,3.1,3);expect(pts[0].y).toBeCloseTo(10,10);const c=parseCoefficients('1 0 -4'),roots=findPolynomialRealRoots(c,-5,5);expect(roots).toHaveLength(2);expect(roots[0]).toBeCloseTo(-2,5);expect(roots[1]).toBeCloseTo(2,5);const s=solveLinearSystem([[2,1,5],[1,-1,1]]);expect(s.kind).toBe('unique');expect(s.solution?.[0]).toBeCloseTo(2,10);expect(s.solution?.[1]).toBeCloseTo(1,10)});
 it('calculates binomial and Poisson probabilities',()=>{expect(binomialPmf(10,3,.5)).toBeCloseTo(.1171875,10);expect(binomialRange(10,.5,0,10)).toBeCloseTo(1,10);expect(poissonPmf(3,2)).toBeCloseTo(.2240418077,8)});
 it('computes intervals, sample size, t tests, and chi-square inference',()=>{const ci=meanConfidenceInterval([1,2,3,4,5],.95);expect(ci.mean).toBe(3);expect(ci.lower).toBeLessThan(3);expect(ci.upper).toBeGreaterThan(3);const pc=proportionConfidenceInterval(60,100,.95);expect(pc.lower).toBeLessThan(.6);expect(pc.upper).toBeGreaterThan(.6);expect(sampleSizeForProportion(.95,.05,.5).required).toBe(385);expect(oneSampleTTest([4,5,6,7,8],5).pValue).toBeLessThan(1);expect(welchTTest([1,2,3,4],[5,6,7,8]).pValue).toBeLessThan(.05);const chi=chiSquareGoodness([10,20,30],[20,20,20]);expect(chi.statistic).toBeCloseTo(10,10);expect(chi.pValue).toBeLessThan(.01)});
 it('summarizes and bins numeric data and builds scatter/CSV series',()=>{const d=descriptiveStats([1,2,3,4,5]);expect(d).toMatchObject({n:5,mean:3,median:3,min:1,max:5});const h=histogram([1,1,2,2,3,3],3);expect(h.bins.reduce((s,b)=>s+b.count,0)).toBe(6);const scatter=scatterStats([1,2,3],[2,4,6]);expect(scatter.r).toBeCloseTo(1,10);expect(scatter.slope).toBeCloseTo(2,10);const csv=csvNumericSeries('x,y\n1,2\n2,4\n3,6','x','y');expect(csv.points).toEqual([{x:1,y:2},{x:2,y:4},{x:3,y:6}])});
 it('keeps P15 local-first and visualization-oriented',()=>{for(const t of PUBLIC_P15_TASKS){expect(t.category).toBe('math');expect(['graph','statistics','data']).toContain(t.engine);expect(t.description).toMatch(/local|locally|browser|SVG/i)}});
});
