import{describe,expect,it}from'vitest';
import{PUBLIC_P16_TASKS}from'../expansion/publicP16Tasks';
import{TOOLS_REGISTRY}from'../registry/tools';
import{registerAllPublicTools}from'../registry/register-all';
import{normalizeToolShellId}from'../registry/tool-shell-mode';
import{analyzeSubtitleReadingSpeed,cleanSubtitleCues,convertSubtitleFrameRate,formatSrt,formatVtt,mergeSubtitleCues,parseSubtitles,resyncSubtitleCues,shiftSubtitleCues,splitSubtitleCues,subtitleToPlainText,transcriptToSubtitleCues,validateSubtitleCues}from'../utilities/p16-subtitles';
registerAllPublicTools();
const SRT='1\n00:00:01,000 --> 00:00:03,000\nHello world.\n\n2\n00:00:04,000 --> 00:00:06,000\nSecond cue.\n';
describe('P16 subtitle and media completion',()=>{
 it('registers 9 unique P16 routes in the current catalog',()=>{expect(PUBLIC_P16_TASKS).toHaveLength(9);expect(new Set(PUBLIC_P16_TASKS.map(t=>t.id)).size).toBe(9);expect(TOOLS_REGISTRY.length).toBeGreaterThanOrEqual(320);expect(PUBLIC_P16_TASKS.some(t=>t.id==='subtitle-converter')).toBe(true);for(const task of PUBLIC_P16_TASKS)expect(TOOLS_REGISTRY.some(t=>t.id===task.id)).toBe(true)});
 it('maps historical SRT/VTT/text conversion routes into one subtitle converter',()=>{for(const id of['srt-to-vtt','vtt-to-srt','subtitle-to-text','transcript-to-subtitles'])expect(normalizeToolShellId(id)).toBe('subtitle-converter')});
 it('round-trips ordinary SRT and WebVTT cue timing and text',()=>{const p=parseSubtitles(SRT,'srt');expect(p.cues).toHaveLength(2);expect(p.cues[0]).toMatchObject({startMs:1000,endMs:3000,text:'Hello world.'});const vtt=formatVtt(p.cues);expect(vtt).toContain('WEBVTT');expect(vtt).toContain('00:00:01.000 --> 00:00:03.000');const back=parseSubtitles(vtt,'vtt');expect(back.cues.map(c=>c.text)).toEqual(['Hello world.','Second cue.']);expect(formatSrt(back.cues)).toContain('00:00:04,000 --> 00:00:06,000')});
 it('shifts, drift-resynchronizes, and frame-rate rescales cue timing',()=>{const cues=parseSubtitles(SRT).cues,shifted=shiftSubtitleCues(cues,-1500);expect(shifted[0].startMs).toBe(0);expect(shifted[1].startMs).toBe(2500);const resync=resyncSubtitleCues(cues,2000,8000);expect(resync.scale).toBeCloseTo(2,10);expect(resync.cues[0].startMs).toBeCloseTo(2000,10);expect(resync.cues[1].startMs).toBeCloseTo(8000,10);const fps=convertSubtitleFrameRate(cues,25,23.976);expect(fps.scale).toBeCloseTo(25/23.976,10);expect(fps.cues[0].startMs).toBeCloseTo(1000*25/23.976,8)});
 it('cleans cue text and reports overlaps, line length, and reading-speed issues',()=>{const dirty=[{index:1,startMs:0,endMs:300,text:'  <i>Hello</i>   world  '},{index:2,startMs:250,endMs:1000,text:'This line is deliberately much longer than forty two characters'}],clean=cleanSubtitleCues(dirty,{stripMarkup:true});expect(clean.cues[0].text).toBe('Hello world');const v=validateSubtitleCues(clean.cues,{maxCps:10,maxCharsPerLine:42});expect(v.issues.some(x=>x.code==='overlap')).toBe(true);expect(v.issues.some(x=>x.code==='reading-speed')).toBe(true);expect(v.issues.some(x=>x.code==='long-line')).toBe(true)});
 it('merges and splits tracks without losing subtitle content',()=>{const a=parseSubtitles(SRT).cues,b=parseSubtitles(SRT.replace('Hello world.','Hallo Welt.')).cues,bilingual=mergeSubtitleCues(a,b,'bilingual');expect(bilingual[0].text).toBe('Hello world.\nHallo Welt.');const appended=mergeSubtitleCues(a,b,'append',500);expect(appended[2].startMs).toBeGreaterThanOrEqual(a[1].endMs+500);const split=splitSubtitleCues(a,4500,true);expect(split.first).toHaveLength(2);expect(split.second).toHaveLength(1);expect(split.second[0].startMs).toBe(0)});
 it('extracts transcript text, generates timed cues, and analyzes reading speed locally',()=>{const cues=parseSubtitles(SRT).cues;expect(subtitleToPlainText(cues,'paragraph')).toBe('Hello world. Second cue.');const generated=transcriptToSubtitleCues('One line\nAnother line',{cueDurationMs:2000,gapMs:100});expect(generated).toHaveLength(2);expect(generated[1].startMs).toBe(2100);const a=analyzeSubtitleReadingSpeed(cues,20);expect(a.cueCount).toBe(2);expect(a.rows[0].words).toBe(2)});
 it('keeps every P16 route local-first and subtitle/transcript focused',()=>{for(const t of PUBLIC_P16_TASKS){expect(t.category).toBe('media');expect(['subtitle','transcript']).toContain(t.engine);expect(t.description).toMatch(/local|locally|browser/i)}});
});
