import{describe,expect,it}from'vitest';
import{PUBLIC_P17_TASKS}from'../expansion/publicP17Tasks';
import{inspectFont,inspectSvg,readArchive,readDocument,readEbook,readPresentation,readSpreadsheet,readStructuredData,type ViewerFileLike}from'../utilities/p17-viewers';
import{createDocx,createEpub}from'../utilities/p13-office';
import{createOdp}from'../utilities/mainstream-odp';
import{createTar}from'../utilities/file-format-conversion';
const file=(name:string,data:string|Uint8Array):ViewerFileLike=>{const bytes=typeof data==='string'?new TextEncoder().encode(data):data;return{name,size:bytes.length,type:'',async text(){return new TextDecoder().decode(bytes)},async arrayBuffer(){return bytes.slice().buffer}}};
describe('P17 file viewers and inspection',()=>{
 it('publishes eight distinct viewer routes with strong local metadata',()=>{expect(PUBLIC_P17_TASKS).toHaveLength(8);expect(new Set(PUBLIC_P17_TASKS.map(t=>t.id)).size).toBe(8);for(const task of PUBLIC_P17_TASKS){expect(task.description.toLowerCase()).toMatch(/local|browser/);expect(task.keywords.length).toBeGreaterThan(2)}});
 it('reads Markdown and DOCX as searchable document content',async()=>{const md=await readDocument(file('notes.md','# Heading\n\nHello viewer'));expect(md.outline[0]).toMatchObject({level:1,title:'Heading'});expect(md.text).toContain('Hello viewer');const docx=await createDocx('# Report\n\nOffice content',{title:'Viewer Test'}),view=await readDocument(file('report.docx',docx));expect(view.markdown).toContain('# Report');expect(view.metadata.title).toBe('Viewer Test')});
 it('opens CSV as a spreadsheet model',async()=>{const view=await readSpreadsheet(file('data.csv','name,score\nAda,10\nLinus,8'));expect(view.sheets).toHaveLength(1);expect(view.sheets[0].headers).toEqual(['name','score']);expect(view.sheets[0].rows[0]).toEqual(['Ada','10'])});
 it('reads generated ODP slides into presentation navigation',async()=>{const odp=await createOdp('# First\n- Alpha\n# Second\n- Beta','Deck'),view=await readPresentation(file('deck.odp',odp));expect(view.slides.length).toBeGreaterThanOrEqual(2);expect(view.slides.some(s=>s.title==='Second')).toBe(true)});
 it('reads generated EPUB content into spine chapters and metadata',async()=>{const epub=await createEpub('# Tiny Book\n\nHello reader',{title:'Tiny Book',creator:'Tiny Tools'}),view=await readEbook(file('book.epub',epub));expect(view.metadata.title).toBe('Tiny Book');expect(view.metadata.creator).toBe('Tiny Tools');expect(view.chapters[0].text).toContain('Hello reader')});
 it('parses structured JSON with node/depth statistics',async()=>{const view=await readStructuredData(file('data.json','{"a":{"b":[1,2]},"ok":true}'));expect(view.value).toEqual({a:{b:[1,2]},ok:true});expect(view.nodeCount).toBeGreaterThan(4);expect(view.maxDepth).toBeGreaterThanOrEqual(3)});
 it('browses TAR inventories without extracting to disk',async()=>{const tar=createTar([{path:'docs/readme.txt',bytes:new TextEncoder().encode('hello')},{path:'data.json',bytes:new TextEncoder().encode('{}')}]),view=await readArchive(file('bundle.tar',tar));expect(view.fileCount).toBe(2);expect(view.entries.map(e=>e.path)).toEqual(['data.json','docs/readme.txt']);expect(view.totalBytes).toBe(7)});
 it('removes active SVG content from inspection previews',()=>{const view=inspectSvg('<svg width="100" height="50"><script>alert(1)</script><rect width="10" height="10" onclick="x()"/></svg>');expect(view.width).toBe('100');expect(view.height).toBe('50');expect(view.sanitizedSvg).not.toMatch(/script|onclick/i);expect(view.warnings.some(w=>/removed/i.test(w))).toBe(true)});
 it('detects mainstream font container headers',()=>{const bytes=new Uint8Array(16);bytes.set([0,1,0,0,0,7],0);const info=inspectFont(bytes,'sample.ttf');expect(info.format).toContain('TrueType');expect(info.tableCount).toBe(7);expect(info.extension).toBe('ttf')});
});
