import{describe,expect,it}from'vitest';
import{PUBLIC_P18_TASKS}from'../expansion/publicP18Tasks';
import{PUBLIC_IMAGE_TASKS}from'../image/publicImageTasks';
import{TOOLS_REGISTRY}from'../registry/tools';
import{registerAllPublicTools}from'../registry/register-all';
import{autoLevelsRgba,edgePreservingDenoiseRgba,enhanceRgba,estimateSkewAngleRgba,inpaintMaskedRgba,removeDustScratchesRgba,restoreOldPhotoRgba,suppressRedEyeRgba,unsharpMaskRgba}from'../utilities/p18-image-restoration';
registerAllPublicTools();
const rgba=(w:number,h:number,v=100)=>{const out=new Uint8ClampedArray(w*h*4);for(let p=0;p<w*h;p++){out[p*4]=out[p*4+1]=out[p*4+2]=v;out[p*4+3]=255}return out};
describe('P18 image enhancement and restoration',()=>{
 it('publishes six distinct P18 routes in the 334-route catalog',()=>{expect(PUBLIC_P18_TASKS).toHaveLength(6);expect(new Set(PUBLIC_P18_TASKS.map(t=>t.id)).size).toBe(6);expect(TOOLS_REGISTRY).toHaveLength(334);for(const t of PUBLIC_P18_TASKS){expect(t.category).toBe('image');expect(t.description).toMatch(/local|locally|browser/i);expect(TOOLS_REGISTRY.some(x=>x.id===t.id)).toBe(true)}});
 it('upgrades the existing upscaler without publishing a duplicate route or AI claim',()=>{const up=PUBLIC_IMAGE_TASKS.find(t=>t.id==='image-upscaler');expect(up).toBeTruthy();expect(PUBLIC_IMAGE_TASKS.filter(t=>t.id==='image-upscaler')).toHaveLength(1);expect(up!.description).toMatch(/staged high-quality browser resampling/i);expect(up!.description).toMatch(/without claiming AI-generated detail/i);expect(up!.description).toMatch(/generative reconstruction/i)});
 it('denoises isolated noise while preserving alpha and dimensions',()=>{const data=rgba(5,5,100),i=(2*5+2)*4;data[i]=data[i+1]=data[i+2]=240;const out=edgePreservingDenoiseRgba(data,5,5,4);expect(out).toHaveLength(data.length);expect(out[i]).toBeLessThan(240);expect(out[i+3]).toBe(255)});
 it('auto-levels narrow tonal ranges and supports a combined enhancer',()=>{const data=rgba(4,2,60);for(let p=4;p<8;p++){data[p*4]=data[p*4+1]=data[p*4+2]=110}const leveled=autoLevelsRgba(data,4,2,0);expect(Math.min(...[...leveled].filter((_,i)=>i%4!==3))).toBe(0);expect(Math.max(...[...leveled].filter((_,i)=>i%4!==3))).toBe(255);const enhanced=enhanceRgba(data,4,2,{denoise:0,sharpen:0,autoLevels:true,localContrast:0,saturation:1});expect(enhanced).toHaveLength(data.length)});
 it('sharpens edge contrast without altering alpha',()=>{const data=rgba(5,5,80);for(let y=0;y<5;y++)for(let x=3;x<5;x++){const i=(y*5+x)*4;data[i]=data[i+1]=data[i+2]=180}const out=unsharpMaskRgba(data,5,5,1,1);expect(out[(2*5+2)*4]).toBeLessThanOrEqual(data[(2*5+2)*4]);expect(out[(2*5+3)*4]).toBeGreaterThanOrEqual(data[(2*5+3)*4]);expect(out[(2*5+3)*4+3]).toBe(255)});
 it('suppresses dust-like outliers and composes the old-photo restoration pipeline',()=>{const data=rgba(5,5,120),i=(2*5+2)*4;data[i]=data[i+1]=data[i+2]=255;const clean=removeDustScratchesRgba(data,5,5,3);expect(clean[i]).toBeLessThan(200);const restored=restoreOldPhotoRgba(data,5,5,{dustRemoval:3,denoise:1,fadeRecovery:.5,sharpen:.3,warmth:.2});expect(restored).toHaveLength(data.length);expect(restored[i+3]).toBe(255)});
 it('fills a painted object mask from surrounding pixels locally',()=>{const data=rgba(7,7,90);for(let y=2;y<=4;y++)for(let x=2;x<=4;x++){const i=(y*7+x)*4;data[i]=220;data[i+1]=30;data[i+2]=30}const mask=new Uint8Array(49);for(let y=2;y<=4;y++)for(let x=2;x<=4;x++)mask[y*7+x]=1;const out=inpaintMaskedRgba(data,7,7,mask),center=(3*7+3)*4;expect(out[center]).toBeLessThan(150);expect(out[center+1]).toBeGreaterThan(60);expect(out[center+3]).toBe(255)});
 it('reduces strongly red-dominant eye pixels inside the chosen circle only',()=>{const data=rgba(7,7,80),center=(3*7+3)*4;data[center]=240;data[center+1]=50;data[center+2]=45;const out=suppressRedEyeRgba(data,7,7,{x:3,y:3},2,1);expect(out[center]).toBeLessThan(120);expect(out[0]).toBe(80)});
 it('returns a bounded deskew estimate with meaningful edge sampling on slanted lines',()=>{const w=160,h=100,data=rgba(w,h,255),slope=Math.tan(5*Math.PI/180);for(const base of[20,40,60,80])for(let x=8;x<w-8;x++){const y=Math.round(base+slope*x);for(let t=-1;t<=1;t++){const yy=y+t;if(yy>0&&yy<h){const i=(yy*w+x)*4;data[i]=data[i+1]=data[i+2]=20}}}const estimate=estimateSkewAngleRgba(data,w,h,12,.5);expect(estimate.edgeSamples).toBeGreaterThan(40);expect(Math.abs(estimate.detectedAngleDeg)).toBeLessThanOrEqual(12);expect(Math.abs(estimate.correctionAngleDeg+estimate.detectedAngleDeg)).toBeLessThan(.01)});
});
