import{describe,expect,it}from'vitest';
import{PUBLIC_P19_TASKS}from'../expansion/publicP19Tasks';
import{TOOLS_REGISTRY}from'../registry/tools';
import{registerAllPublicTools}from'../registry/register-all';
import{analyzeLatency,capabilitySummary,classifyIpReachability,evaluateCodecSupport,gradeConnection,parseIceCandidate,summarizeIceCandidates,throughputMbps}from'../utilities/p19-network-browser';
registerAllPublicTools();
describe('P19 network and browser diagnostics',()=>{
 it('publishes nine unique diagnostic routes in the current catalog',()=>{expect(PUBLIC_P19_TASKS).toHaveLength(9);expect(new Set(PUBLIC_P19_TASKS.map(t=>t.id)).size).toBe(9);expect(TOOLS_REGISTRY.length).toBeGreaterThanOrEqual(343);for(const t of PUBLIC_P19_TASKS){expect(t.category).toBe('device');expect(TOOLS_REGISTRY.some(x=>x.id===t.id)).toBe(true)}});
 it('separates external network probes from local-only browser inspection',()=>{const external=PUBLIC_P19_TASKS.filter(t=>t.networkUse==='external'),local=PUBLIC_P19_TASKS.filter(t=>t.networkUse==='local');expect(external.map(t=>t.id)).toEqual(['internet-speed-test','connection-stability-test','ipv4-ipv6-test','webrtc-leak-test']);expect(local).toHaveLength(5);for(const t of external)expect(t.description).toMatch(/Cloudflare|STUN|external|Internet/i);for(const t of local)expect(t.description).toMatch(/local|locally|browser/i)});
 it('calculates payload throughput in decimal megabits per second',()=>{expect(throughputMbps(1_000_000,1000)).toBe(8);expect(throughputMbps(5_000_000,2000)).toBe(20);expect(throughputMbps(100,0)).toBe(0)});
 it('summarizes latency, jitter, failures, and a bounded quality grade',()=>{const s=analyzeLatency([10,12,null,14,50]);expect(s).toMatchObject({samples:5,successes:4,failures:1,failurePercent:20,minMs:10,maxMs:50});expect(s.averageMs).toBe(21.5);expect(s.jitterMs).toBeCloseTo(13.3,1);const g=gradeConnection(s);expect(g.score).toBeGreaterThanOrEqual(0);expect(g.score).toBeLessThanOrEqual(100)});
 it('classifies IPv4/IPv6 reachability without inventing an address',()=>{expect(classifyIpReachability(true,true)).toBe('Dual-stack (IPv4 + IPv6)');expect(classifyIpReachability(true,false)).toBe('IPv4 only');expect(classifyIpReachability(false,true)).toBe('IPv6 only');expect(classifyIpReachability(false,false)).toBe('No tested IP reachability')});
 it('parses WebRTC ICE candidates and distinguishes private public and mDNS addresses',()=>{const a=parseIceCandidate('candidate:1 1 udp 2122260223 192.168.1.20 54321 typ host generation 0'),b=parseIceCandidate('candidate:2 1 udp 1686052607 203.0.113.10 62000 typ srflx raddr 0.0.0.0 rport 0'),c=parseIceCandidate('candidate:3 1 udp 2122260223 abcdef.local 50000 typ host');expect(a).toMatchObject({type:'host',family:'ipv4',scope:'private'});expect(b).toMatchObject({type:'srflx',family:'ipv4',scope:'public'});expect(c).toMatchObject({family:'mdns',scope:'mdns'});const summary=summarizeIceCandidates([a,b,c]);expect(summary).toMatchObject({total:3,literalCount:2,privateCount:1,publicCount:1,mdnsCount:1})});
 it('evaluates common codec decoding and recording through injected browser probes',()=>{const rows=evaluateCodecSupport((kind,mime)=>mime.includes('audio/mpeg')?'probably':kind==='video'&&mime.includes('vp09')?'maybe':'',mime=>mime.includes('webm'));expect(rows.find(r=>r.label==='MP3')).toMatchObject({decode:'probably',record:false});expect(rows.find(r=>r.label.includes('VP9'))).toMatchObject({decode:'maybe',record:true});expect(rows.some(r=>r.decode==='no')).toBe(true)});
 it('summarizes browser capabilities by supported count and group coverage',()=>{const s=capabilitySummary([{group:'A',name:'one',supported:true},{group:'A',name:'two',supported:false},{group:'B',name:'three',supported:true}]);expect(s).toEqual({supported:2,total:3,percent:67,groups:2})});
});
