import{describe,expect,it}from'vitest';
import{PUBLIC_TEXT_STUDY_TASKS}from'../text-study/publicTextStudyTasks';
import{analyzeNgrams,calculateReadability,compareTextSimilarity,extractTextPatterns,findDuplicatePhrases,htmlToPlainText,inspectUnicode,markdownToPlainText,repeatText,reverseText,visualizeWhitespace,wrapText}from'../utilities/text-analysis-tools';
import{buildReadingPlan,formatCitation,memorizationAccuracy,nextReviewInterval,parseCloze,parseFlashcards,parseStudySubjects,planStudySession}from'../utilities/study-tools';

describe('P7 text and study expansion',()=>{
 it('publishes exactly 22 unique routes with a 14 text / 8 productivity split',()=>{expect(PUBLIC_TEXT_STUDY_TASKS).toHaveLength(22);expect(new Set(PUBLIC_TEXT_STUDY_TASKS.map(t=>t.id)).size).toBe(22);expect(PUBLIC_TEXT_STUDY_TASKS.filter(t=>t.category==='text')).toHaveLength(14);expect(PUBLIC_TEXT_STUDY_TASKS.filter(t=>t.category==='productivity')).toHaveLength(8)});
 it('computes finite English readability metrics and states the formula boundary',()=>{const r=calculateReadability('The cat sat on the mat. It likes the warm sun.');expect(r.words).toBeGreaterThan(5);expect(r.sentences).toBe(2);expect(Number.isFinite(r.readingEase)).toBe(true);expect(Number.isFinite(r.gradeLevel)).toBe(true);expect(r.note.toLowerCase()).toContain('english')});
 it('counts n-grams deterministically',()=>{const rows=analyzeNgrams('red blue red blue green',2);expect(rows[0]).toEqual({phrase:'red blue',count:2});expect(rows.some(r=>r.phrase==='blue red'&&r.count===1)).toBe(true)});
 it('extracts public text patterns without treating the email suffix as a mention',()=>{const r=extractTextPatterns('Mail me at a@example.com or visit https://example.com/test. #Study @jon');expect(r.emails).toEqual(['a@example.com']);expect(r.urls).toEqual(['https://example.com/test']);expect(r.hashtags).toEqual(['#Study']);expect(r.mentions).toEqual(['@jon'])});
 it('finds repeated multi-word phrases',()=>{const r=findDuplicatePhrases('active recall is useful and active recall is useful',3,2);expect(r.some(x=>x.phrase==='active recall is'&&x.count===2)).toBe(true)});
 it('reports identical texts as fully similar and disjoint texts as dissimilar',()=>{expect(compareTextSimilarity('alpha beta beta','alpha beta beta')).toEqual({jaccard:1,cosine:1,combined:1});expect(compareTextSimilarity('alpha beta','gamma delta').combined).toBe(0)});
 it('inspects Unicode graphemes and named invisible spacing',()=>{const rows=inspectUnicode('A\u00a0🙂\u200b');expect(rows.some(r=>r.codePoints.includes('U+00A0')&&r.category==='NO-BREAK SPACE')).toBe(true);expect(rows.some(r=>r.category==='ZERO WIDTH SPACE')).toBe(true);expect(rows.some(r=>r.grapheme==='🙂'&&r.codePoints[0]==='U+1F642')).toBe(true)});
 it('bounds repeated output and preserves graphemes when reversing characters',()=>{expect(repeatText('go',3,'|')).toBe('go|go|go');expect(()=>repeatText('x'.repeat(2000),1000,'')).toThrow(/1,000,000/);expect(reverseText('A🙂B','characters')).toBe('B🙂A')});
 it('wraps text to the requested width and makes whitespace visible',()=>{const wrapped=wrapText('one two three four five six',10);expect(Math.max(...wrapped.split('\n').map(x=>x.length))).toBeLessThanOrEqual(10);expect(visualizeWhitespace('a b\tc\n')).toContain('a·b→\tc↵\n')});
 it('converts common Markdown and HTML to readable plain text',()=>{expect(markdownToPlainText('# Title\n- **Bold** [link](https://example.com)')).toBe('Title\nBold link');expect(htmlToPlainText('<p>Hello &amp; welcome</p><script>bad()</script><p>Next</p>')).toBe('Hello & welcome\nNext')});
 it('parses flashcard and cloze source formats',()=>{expect(parseFlashcards('Q1 :: A1\nQ2\tA2')).toEqual([{front:'Q1',back:'A1'},{front:'Q2',back:'A2'}]);expect(parseCloze('Water is {{c1::wet}} and ice is {{cold}}.')).toEqual({prompt:'Water is ____ and ice is ____.',answers:['wet','cold']})});
 it('scores exact memorization at 100 and penalizes changed text',()=>{expect(memorizationAccuracy('Hello world',' hello   WORLD ')).toBe(100);expect(memorizationAccuracy('Hello world','Goodbye world')).toBeLessThan(100)});
 it('orders review intervals from again through easy',()=>{const values=(['again','hard','good','easy']as const).map(r=>nextReviewInterval(4,r));expect(values[0]).toBe(1);expect(values[1]).toBeLessThan(values[2]);expect(values[2]).toBeLessThan(values[3])});
 it('allocates weighted study time without losing minutes',()=>{const subjects=parseStudySubjects('Analysis :: 3\nFrench :: 1'),plan=planStudySession(subjects,120,10,50);expect(plan.studyMinutes+plan.breakMinutes).toBe(120);expect(plan.allocations.reduce((n,x)=>n+x.minutes,0)).toBe(plan.studyMinutes);expect(plan.allocations[0].minutes).toBeGreaterThan(plan.allocations[1].minutes)});
 it('divides an inclusive page range exactly across study days',()=>{const plan=buildReadingPlan(11,110,6);expect(plan).toHaveLength(6);expect(plan[0].startPage).toBe(11);expect(plan.at(-1)?.endPage).toBe(110);expect(plan.reduce((n,x)=>n+x.pages,0)).toBe(100);expect(Math.max(...plan.map(x=>x.pages))-Math.min(...plan.map(x=>x.pages))).toBeLessThanOrEqual(1)});
 it('formats basic APA, MLA, and Chicago citations while remaining deterministic',()=>{const input={type:'website' as const,author:'Doe, J.',title:'Example',container:'Example Site',year:'2026',url:'https://example.com'};expect(formatCitation(input,'apa')).toContain('(2026)');expect(formatCitation(input,'mla')).toContain('“Example.”');expect(formatCitation(input,'chicago')).toContain('Doe, J. 2026.')});
});
