import{describe,expect,it}from'vitest';
import{PUBLIC_EVERYDAY_TASKS}from'../everyday/publicEverydayTasks';
import{buildMonthCalendar,calculateDocumentTotals,calendarAge,countdownParts,durationBetween,escapeHtml,isoWeekInfo,parseLineItems,parseScheduleEntries,parseTimesheet,printableHtml,safeHttpUrl}from'../utilities/everyday-docs';
describe('P9 everyday documents and planning',()=>{
 it('publishes exactly 13 unique routes',()=>{expect(PUBLIC_EVERYDAY_TASKS).toHaveLength(13);const ids=PUBLIC_EVERYDAY_TASKS.map(t=>t.id);expect(new Set(ids).size).toBe(13);expect(PUBLIC_EVERYDAY_TASKS.every(t=>t.name&&t.description&&t.keywords.length)).toBe(true)});
 it('parses line items and totals discount before tax',()=>{const parsed=parseLineItems('Work | 2 | 50\nParts | 1 | 20');expect(parsed.errors).toEqual([]);expect(parsed.items).toHaveLength(2);expect(calculateDocumentTotals(parsed.items,20,10)).toEqual({subtotal:120,discount:12,taxable:108,tax:21.6,total:129.6})});
 it('reports malformed commerce lines instead of silently accepting them',()=>{const parsed=parseLineItems('Good | 1 | 5\nBad row\nNegative | 1 | -2');expect(parsed.items).toHaveLength(1);expect(parsed.errors).toHaveLength(2)});
 it('escapes generated document text and only accepts http(s) website URLs',()=>{expect(escapeHtml('<script>"x" & y</script>')).toBe('&lt;script&gt;&quot;x&quot; &amp; y&lt;/script&gt;');expect(safeHttpUrl('example.com')).toBe('https://example.com/');expect(safeHttpUrl('javascript:alert(1)')).toBe('');expect(printableHtml('A < B','<p>safe body</p>')).toContain('<title>A &lt; B</title>')});
 it('builds complete Monday-first and Sunday-first calendar grids',()=>{const monday=buildMonthCalendar(2026,9,1),sunday=buildMonthCalendar(2026,9,0);expect(monday.flat().filter(c=>c.day).map(c=>c.day)).toEqual(Array.from({length:30},(_,i)=>i+1));expect(monday[0][1].day).toBe(1);expect(sunday[0][2].day).toBe(1)});
 it('parses and orders weekly schedule rows',()=>{const out=parseScheduleEntries('Friday | 10:00 | 11:00 | B\nMonday | 09:00 | 10:00 | A');expect(out.errors).toEqual([]);expect(out.items.map(x=>x.day)).toEqual(['Monday','Friday']);expect(parseScheduleEntries('Funday | 09:00 | 10:00 | Nope').errors).toHaveLength(1)});
 it('calculates countdown and signed duration components',()=>{const c=countdownParts('2026-09-03T12:30:00Z','2026-09-01T10:00:00Z');expect(c).toMatchObject({sign:1,days:2,hours:2,minutes:30,seconds:0});const d=durationBetween('2026-09-02T00:00:00Z','2026-09-01T22:30:00Z');expect(d).toMatchObject({sign:-1,days:0,hours:1,minutes:30})});
 it('totals timesheets including overnight shifts and breaks',()=>{const out=parseTimesheet('2026-09-01 | 09:00 | 17:00 | 30\n2026-09-02 | 22:00 | 02:00 | 15');expect(out.errors).toEqual([]);expect(out.items[0].workedMinutes).toBe(450);expect(out.items[1].workedMinutes).toBe(225);expect(out.totalMinutes).toBe(675)});
 it('rejects impossible breaks and malformed dates',()=>{const out=parseTimesheet('2026-02-31 | 09:00 | 17:00 | 30\n2026-09-01 | 09:00 | 10:00 | 120');expect(out.items).toHaveLength(0);expect(out.errors).toHaveLength(2)});
 it('returns correct ISO week boundaries and day of year',()=>{expect(isoWeekInfo('2021-01-01')).toMatchObject({isoYear:2020,week:53,weekday:'Friday',isoWeekday:5,dayOfYear:1});expect(isoWeekInfo('2026-09-01')).toMatchObject({isoYear:2026,week:36,weekday:'Tuesday'})});
 it('calculates calendar age as years, months, days and total elapsed days',()=>{expect(calendarAge('2000-01-15','2026-09-01')).toEqual({years:26,months:7,days:17,totalDays:9726})});
 it('uses February 28 as the clamped non-leap anniversary for Feb 29 births',()=>{expect(calendarAge('2000-02-29','2026-02-28')).toMatchObject({years:26,months:0,days:0})});
 it('rejects age calculations before birth',()=>{expect(()=>calendarAge('2026-09-02','2026-09-01')).toThrow(/before the birth date/)});
});
