import{describe,expect,it}from'vitest';
import{bmiAssessment,estimateBmr,estimateBodyFat,estimateTdee,feetAndInchesToCm,kgToLb}from'../utilities/s-tier-fitness';
import{generateLorem,isGraphemePalindrome,repeatText,reverseText,wrapText}from'../utilities/s-tier-text';
import{decodeHtmlEntitiesBasic,encodeHtmlEntities,entityStats}from'../utilities/s-tier-html-entities';
import{acceptFragment,batchMimeLookup,exactMimeForExtension,lookupMime,preferredExtension}from'../utilities/s-tier-mime';
import{slugifyAdvanced,uniqueSlugs}from'../utilities/s-tier-slug';
import{dateFromIsoWeek,isoWeekFromDate,isoWeeksInYear,weekCalendarInfo,weekDates}from'../utilities/s-tier-week';
import{encodePcm16Wav,processReverseChannels}from'../utilities/s-tier-audio';
import{analyzeDecisionSensitivity,decisionWinnerMargin,rankDecisionOptionsStable}from'../utilities/s-tier-decision';
import{TOOLS_REGISTRY}from'../registry/tools';
import{registerAllPublicTools}from'../registry/register-all';
registerAllPublicTools();

const TARGETS=['bmr-calculator','tdee-calculator','decision-matrix','bmi-calculator','reverse-audio','html-entity-converter','body-fat-calculator','mime-type-lookup','text-wrapper','slug-generator','lorem-ipsum-generator','week-number-weekday','text-reverser','text-repeater'];

describe('S-tier uplift of the former C/D group',()=>{
 it('keeps every targeted public route registered and discoverable',()=>{for(const id of TARGETS){const tool=TOOLS_REGISTRY.find(item=>item.id===id);expect(tool,id).toBeTruthy();expect(tool?.description.length,id).toBeGreaterThan(70);expect(tool?.component,id).toBeTruthy();}});
 it('adds a contextual BMI assessment and unit conversion',()=>{const result=bmiAssessment(80,180);expect(result.bmi).toBeCloseTo(24.69,2);expect(result.category).toBe('Healthy range');expect(result.healthyWeightMinKg).toBeCloseTo(59.94,1);expect(kgToLb(80)).toBeCloseTo(176.37,1);expect(feetAndInchesToCm(5,11)).toBeCloseTo(180.34,2);});
 it('compares multiple BMR methods and derives transparent TDEE bands',()=>{const bmr=estimateBmr(80,181,30,'male',15);expect(bmr.methodsUsed).toBe(3);expect(bmr.mifflinStJeor).toBeCloseTo(1786.3,1);expect(bmr.katchMcArdle).toBeGreaterThan(1700);expect(bmr.spread).toBeGreaterThan(0);const tdee=estimateTdee(bmr.consensus,1.55);expect(tdee.maintenance).toBeGreaterThan(2600);expect(tdee.uncertaintyLow).toBeLessThan(tdee.maintenance);expect(tdee.uncertaintyHigh).toBeGreaterThan(tdee.maintenance);});
 it('uses the Navy circumference method with fat/lean mass outputs',()=>{const result=estimateBodyFat('male',180,85,38,undefined,80);expect(result.bodyFatPercent).toBeGreaterThan(5);expect(result.bodyFatPercent).toBeLessThan(30);expect((result.fatMassKg??0)+(result.leanMassKg??0)).toBeCloseTo(80,1);expect(result.waistToHeightRatio).toBeCloseTo(.472,3);});
 it('ranks duplicate-named decision rows by stable source identity',()=>{const criteria=[{name:'Impact',weight:70},{name:'Ease',weight:30}],options=[{name:'Same',scores:[10,2]},{name:'Same',scores:[4,10]},{name:'Other',scores:[6,6]}];const ranked=rankDecisionOptionsStable(criteria,options);expect(ranked).toHaveLength(3);expect(new Set(ranked.map(row=>row.sourceIndex)).size).toBe(3);const first=ranked.find(row=>row.sourceIndex===0)!,second=ranked.find(row=>row.sourceIndex===1)!;expect(first.score).not.toBe(second.score);expect(ranked[0].sourceIndex).toBe(0);expect(decisionWinnerMargin(ranked)).toBeGreaterThan(0);const sensitivity=analyzeDecisionSensitivity(criteria,options);expect(sensitivity).toHaveLength(2);expect(sensitivity.some(row=>row.changedWinner)).toBe(true);});
 it('reverses Unicode graphemes and word/line structures safely',()=>{expect(reverseText('A👨‍👩‍👧‍👦B','graphemes')).toBe('B👨‍👩‍👧‍👦A');expect(reverseText('one two  three','words')).toBe('three two  one');expect(reverseText('a b\nc d','words-per-line')).toBe('b a\nd c');expect(reverseText('a\nb\nc','lines')).toBe('c\nb\na');expect(isGraphemePalindrome('Never odd or even')).toBe(true);});
 it('repeats and wraps text with explicit safety and formatting behavior',()=>{expect(repeatText('x',{count:3,separator:'|',numberLines:true,startNumber:2})).toBe('2. x|3. x|4. x');expect(()=>repeatText('x'.repeat(1000),{count:10000,separator:''})).toThrow(/safety limit/i);expect(wrapText('alpha beta gamma delta',{width:12,mode:'soft'})).toBe('alpha beta\ngamma delta');expect(wrapText('abcdefgh',{width:4,mode:'hard'})).toBe('abcd\nefgh');});
 it('generates deterministic seeded Lorem variations',()=>{const options={unit:'paragraphs' as const,count:2,seed:'same-seed',minSentenceWords:6,maxSentenceWords:9,sentencesPerParagraph:2,startClassic:false};const a=generateLorem(options),b=generateLorem(options),c=generateLorem({...options,seed:'different'});expect(a).toBe(b);expect(c).not.toBe(a);expect(a.split('\n\n')).toHaveLength(2);});
 it('encodes named/numeric HTML entities and decodes common/numeric forms',()=>{expect(encodeHtmlEntities('<Tom & Jerry>',{encoding:'named',scope:'special'})).toBe('&lt;Tom &amp; Jerry&gt;');expect(encodeHtmlEntities('é',{encoding:'hex',scope:'non-ascii'})).toBe('&#xE9;');expect(decodeHtmlEntitiesBasic('&lt;A&#x20;B&gt; &copy;')).toBe('<A B> ©');expect(entityStats('&amp; &#38; &amp;')).toEqual({entities:3,named:2,numeric:1,unique:2});});
 it('provides broad MIME lookup, batch resolution, and web-ready fragments',()=>{expect(exactMimeForExtension('photo.webp')?.mime).toBe('image/webp');expect(preferredExtension('application/pdf')).toBe('pdf');expect(lookupMime('xlsx')[0]?.mime).toContain('spreadsheetml');expect(lookupMime('application/json')[0]?.extensions).toContain('json');expect(batchMimeLookup('a.pdf\nimage/png')).toHaveLength(2);expect(acceptFragment(exactMimeForExtension('mp3')!)).toContain('audio/mpeg');});
 it('generates bounded Unicode/ASCII slugs and unique duplicate suffixes',()=>{const base={separator:'-' as const,lowercase:true,unicode:false,removeStopWords:false,maxLength:80,trimBoundary:true};expect(slugifyAdvanced('Café & Crème — Déjà Vu',base)).toBe('cafe-creme-deja-vu');expect(slugifyAdvanced('안녕하세요 세계',{...base,unicode:true})).toBe('안녕하세요-세계');const rows=uniqueSlugs(['Same title','Same title','Same title'],base);expect(rows.map(row=>row.slug)).toEqual(['same-title','same-title-2','same-title-3']);expect(slugifyAdvanced('this is a very long title with many useful words',{...base,maxLength:20}).length).toBeLessThanOrEqual(20);});
 it('handles ISO week-year boundaries and reverse conversion',()=>{const info=weekCalendarInfo('2021-01-01','en');expect(info.isoYear).toBe(2020);expect(info.isoWeek).toBe(53);expect(info.isoWeekday).toBe(5);expect(info.weekStart).toBe('2020-12-28');expect(info.weekEnd).toBe('2021-01-03');expect(dateFromIsoWeek(2020,53,5)).toBe('2021-01-01');expect(weekDates(2020,53)).toHaveLength(7);expect(isoWeeksInYear(2020)).toBe(53);expect(isoWeekFromDate(new Date(Date.UTC(2026,8,3))).isoWeekday).toBe(4);});
 it('reverses only the selected audio samples, fades boundaries, normalizes, and exports WAV',async()=>{const source=new Float32Array([.1,.2,.3,.4,.5,.6,.7,.8]);const processed=processReverseChannels([source],4,{startSeconds:.5,endSeconds:1.5,fadeMs:0,normalizePeak:false});expect([...processed.channels[0]]).toEqual([.1,.2,.6,.5,.4,.3,.7,.8].map(x=>expect.closeTo(x,5)));expect(processed.summary.startSample).toBe(2);expect(processed.summary.endSample).toBe(6);const normalized=processReverseChannels([new Float32Array([.25,.5])],2,{startSeconds:0,endSeconds:1,fadeMs:0,normalizePeak:true});expect(normalized.summary.peakAfter).toBeCloseTo(.98,5);const blob=encodePcm16Wav([processed.channels[0]],4);expect(blob.type).toBe('audio/wav');expect(blob.size).toBe(44+8*2);});
});
