import { lazy } from 'react';
import type { ToolCategory, ToolDefinition } from '../types';

export const TOOLS_REGISTRY: ToolDefinition[] = [
  // 1. Text Cleaner
  {
    id: 'text-cleaner',
    name: 'Text Cleaner & Normalizer',
    shortName: 'Text Cleaner',
    description: 'Trim excess whitespace, normalize Unicode spaces, strip emoji/symbols/HTML, and clean line endings.',
    category: 'text',
    keywords: ['clean', 'trim', 'spaces', 'unicode', 'html', 'strip', 'emoji', 'quotes', 'normalize', 'format'],
    iconName: 'Sparkles',
    route: '/text-cleaner',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/text-cleaner/TextCleanerTool')),
  },
  // 2. Case Converter
  {
    id: 'case-converter',
    name: 'Case Converter',
    shortName: 'Case Converter',
    description: 'Convert text between camelCase, PascalCase, snake_case, kebab-case, UPPERCASE, lowercase, CONSTANT_CASE, dot.case, and Title Case.',
    category: 'text',
    keywords: ['case', 'camel', 'pascal', 'snake', 'kebab', 'upper', 'lower', 'title', 'constant', 'dot', 'slug', 'casing'],
    iconName: 'Type',
    route: '/case-converter',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/case-converter/CaseConverterTool')),
  },
  // 3. Word Counter
  {
    id: 'word-counter',
    name: 'Word & Character Counter',
    shortName: 'Word Counter',
    description: 'Count words, characters, unique words, sentences, paragraphs, reading/speaking time, and frequency rankings.',
    category: 'text',
    keywords: ['word count', 'character count', 'stats', 'reading time', 'speaking time', 'density', 'sentences', 'paragraphs', 'unique'],
    iconName: 'FileText',
    route: '/word-counter',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/word-counter/WordCounterTool')),
  },
  // 4. List Processor
  {
    id: 'list-processor',
    name: 'List Processor & Sorter',
    shortName: 'List Processor',
    description: 'Sort alphabetically/numerically, deduplicate, reverse, shuffle, prefix/suffix, number, and change delimiters.',
    category: 'text',
    keywords: ['list', 'sort', 'dedupe', 'deduplicate', 'unique', 'prefix', 'suffix', 'csv', 'lines', 'shuffle', 'reverse'],
    iconName: 'ListOrdered',
    route: '/list-processor',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/list-processor/ListProcessorTool')),
  },
  // 5. JSON Formatter
  {
    id: 'json-formatter',
    name: 'JSON Formatter & Validator',
    shortName: 'JSON Formatter',
    description: 'Prettify, minify, sort keys, and validate JSON syntax with precise line and column error reporting.',
    category: 'developer',
    keywords: ['json', 'prettify', 'format', 'minify', 'validate', 'sort keys', 'parse', 'indent'],
    iconName: 'Code2',
    route: '/json-formatter',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/json-formatter/JsonFormatterTool')),
  },
  // 6. Regex Tester
  {
    id: 'regex-tester',
    name: 'Regex Tester & Debugger',
    shortName: 'Regex Tester',
    description: 'Test regular expressions, inspect captured groups and flags, and preview real-time string replacement.',
    category: 'developer',
    keywords: ['regex', 'regular expression', 'pattern', 'match', 'replace', 'groups', 'test', 'capture'],
    iconName: 'Regex',
    route: '/regex-tester',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/regex-tester/RegexTesterTool')),
  },
  // 7. URL & Base64 Tools
  {
    id: 'encoding-tools',
    name: 'URL & Base64 Tools',
    shortName: 'URL & Base64',
    description: 'Encode/decode URLs, parse and edit query parameters, and convert UTF-8 strings to and from Base64.',
    category: 'developer',
    keywords: ['url', 'uri', 'encode', 'decode', 'query params', 'querystring', 'base64', 'utf8', 'binary'],
    iconName: 'Globe',
    route: '/encoding-tools',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/encoding-tools/EncodingTools')),
  },
  // 8. Password & Passphrase Generator
  {
    id: 'secure-generator',
    name: 'Password & Passphrase Generator',
    shortName: 'Password Generator',
    description: 'Cryptographically secure passwords, EFF multi-word passphrases, PINs, and entropy calculation.',
    category: 'developer',
    keywords: ['password', 'passphrase', 'pin', 'crypto', 'secure', 'random', 'diceware', 'generator', 'entropy'],
    iconName: 'KeyRound',
    route: '/secure-generator',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/secure-generator/SecureGeneratorTool')),
  },
  // 9. Color Converter & Contrast
  {
    id: 'color-converter',
    name: 'Color Converter & Contrast',
    shortName: 'Color Converter',
    description: 'Convert HEX, RGB, RGBA, HSL, HSLA and verify WCAG 2.1 AA/AAA accessibility contrast compliance.',
    category: 'design',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'wcag', 'contrast', 'accessibility', 'palette', 'picker'],
    iconName: 'Pipette',
    route: '/color-converter',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/color-converter/ColorConverterTool')),
  },
  // 10. Aspect Ratio Calculator
  {
    id: 'aspect-ratio-calculator',
    name: 'Aspect Ratio Calculator',
    shortName: 'Aspect Ratio',
    description: 'Calculate dimensions, simplify pixel ratios, scale viewports, and test responsive screen proportions.',
    category: 'design',
    keywords: ['aspect ratio', 'dimensions', 'resolution', '16:9', '4:3', 'width', 'height', 'scale', 'gcd', 'screen'],
    iconName: 'Ratio',
    route: '/aspect-ratio-calculator',
    featured: false,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/aspect-ratio-calculator/AspectRatioCalculatorTool')),
  },
  // 11. Percentage Calculator
  {
    id: 'percentage-calculator',
    name: 'Percentage Calculator',
    shortName: 'Percentage Calc',
    description: 'Calculate percentages of numbers, relative ratios, percentage increase/decrease, and reverse percentages.',
    category: 'math',
    keywords: ['percent', 'percentage', 'increase', 'decrease', 'discount', 'ratio', 'math', 'calculator'],
    iconName: 'Percent',
    route: '/percentage-calculator',
    featured: false,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/percentage-calculator/PercentageCalculatorTool')),
  },
  // 12. Unit Converter
  {
    id: 'unit-converter',
    name: 'Unit Converter',
    shortName: 'Unit Converter',
    description: 'Convert length, mass, temperature, area, volume, speed, and SI/IEC digital storage units with zero drift.',
    category: 'math',
    keywords: ['unit', 'converter', 'metric', 'imperial', 'length', 'weight', 'temperature', 'storage', 'celsius', 'fahrenheit', 'meters', 'feet'],
    iconName: 'Ruler',
    route: '/unit-converter',
    featured: false,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/unit-converter/UnitConverterTool')),
  },
  // 13. Unit Price Comparator
  {
    id: 'unit-price-comparator',
    name: 'Unit Price Comparator',
    shortName: 'Unit Price',
    description: 'Compare groceries, packaging sizes, and bulk items across mixed units to find the true lowest cost.',
    category: 'everyday',
    keywords: ['unit price', 'grocery', 'compare', 'shopping', 'cost per ounce', 'cost per kg', 'cheapest', 'deal', 'savings'],
    iconName: 'Scale',
    route: '/unit-price-comparator',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/unit-price-comparator/UnitPriceComparatorTool')),
  },
  // 14. Discount, VAT & Margin Calculator
  {
    id: 'discount-vat-calculator',
    name: 'Discount, VAT & Margin Calculator',
    shortName: 'Discount & VAT',
    description: 'Calculate retail discounts with stacked coupons, sales tax / VAT additions/extractions, and commercial profit margins.',
    category: 'math',
    keywords: ['discount', 'vat', 'tax', 'sales tax', 'margin', 'markup', 'cogs', 'coupon', 'sale price', 'profit'],
    iconName: 'Tag',
    route: '/discount-vat-calculator',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/discount-vat/DiscountVatTool')),
  },
  // 15. Date Calculator
  {
    id: 'date-calculator',
    name: 'Date Calculator',
    shortName: 'Date Calculator',
    description: 'Calculate calendar duration, add/subtract intervals, find exact age, and compute working business days.',
    category: 'time',
    keywords: ['date', 'calendar', 'days', 'weeks', 'duration', 'age', 'working days', 'business days', 'time'],
    iconName: 'CalendarDays',
    route: '/date-calculator',
    featured: false,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/date-calculator/DateCalculatorTool')),
  },
  // 16. Time Zone & World Clock Converter
  {
    id: 'time-zone-converter',
    name: 'Time Zone & World Clock Converter',
    shortName: 'Time Zone',
    description: 'Compare local times across worldwide time zones, visualize meeting overlaps, and convert UTC/ISO timestamps.',
    category: 'time',
    keywords: ['time zone', 'timezone', 'utc', 'gmt', 'world clock', 'meeting planner', 'dst', 'iso time'],
    iconName: 'Clock',
    route: '/time-zone-converter',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/time-zone-converter/TimeZoneConverterTool')),
  },
  // 17. Timer, Stopwatch & Pomodoro
  {
    id: 'timer-stopwatch',
    name: 'Timer, Stopwatch & Pomodoro',
    shortName: 'Timer & Stopwatch',
    description: 'Precision countdown timer with audible synth chimes, millisecond split-lap stopwatch, and Pomodoro focus intervals.',
    category: 'time',
    keywords: ['timer', 'stopwatch', 'pomodoro', 'countdown', 'lap', 'alarm', 'focus', 'interval', 'clock'],
    iconName: 'Timer',
    route: '/timer-stopwatch',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/timer-stopwatch/TimerStopwatchTool')),
  },
  // 18. QR Code Studio & Scanner
  {
    id: 'qr-studio',
    name: 'QR Code Studio & Scanner',
    shortName: 'QR Studio',
    description: 'Generate high-res customized QR codes for URLs, WiFi, vCards, and decode images locally in-browser.',
    category: 'everyday',
    keywords: ['qr', 'qr code', 'barcode', 'scan', 'wifi', 'vcard', 'generator', 'scanner', 'svg'],
    iconName: 'QrCode',
    route: '/qr-studio',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/qr-studio/QrStudioTool')),
  },
  // 19. Image Optimizer & Converter
  {
    id: 'image-optimizer',
    name: 'Image Optimizer & Converter',
    shortName: 'Image Optimizer',
    description: 'Compress, resize, and convert images between WebP, JPEG, and PNG client-side with instant before/after preview.',
    category: 'image',
    keywords: ['image', 'optimizer', 'compress', 'resize', 'webp', 'jpeg', 'png', 'photo', 'picture', 'shrink'],
    iconName: 'Image',
    route: '/image-optimizer',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/image-optimizer/ImageOptimizerTool')),
  },
  // 20. Screenshot & Image Annotator
  {
    id: 'image-annotator',
    name: 'Screenshot & Image Annotator',
    shortName: 'Image Annotator',
    description: 'Draw arrows, boxes, badges, highlights, and redact sensitive information locally on images and screenshots.',
    category: 'image',
    keywords: ['screenshot', 'annotate', 'arrow', 'redact', 'blur', 'highlight', 'crop', 'markup', 'draw', 'callout'],
    iconName: 'Pencil',
    route: '/image-annotator',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/image-annotator/ImageAnnotatorTool')),
  },
  // 21. Image Collage Maker
  {
    id: 'image-collage',
    name: 'Image Collage Maker',
    shortName: 'Image Collage',
    description: 'Combine multiple photos and screenshots into high-resolution custom collages locally in your browser.',
    category: 'image',
    keywords: ['collage', 'grid', 'combine images', 'stitch', 'side by side', 'photo grid', 'before after', 'montage'],
    iconName: 'LayoutGrid',
    route: '/image-collage',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/image-collage/ImageCollageTool')),
  },
  // 22. Image Background Remover
  {
    id: 'background-remover',
    name: 'Image Background Remover',
    shortName: 'Background Remover',
    description: 'Remove image backgrounds locally in your browser using local machine learning and instant canvas refinement.',
    category: 'image',
    keywords: ['background remover', 'transparent png', 'cutout', 'isolate subject', 'mask', 'erase background', 'product photo'],
    iconName: 'Scissors',
    route: '/background-remover',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/background-remover/BackgroundRemoverTool')),
  },
  // 23. Image to Text (OCR)
  {
    id: 'image-to-text',
    name: 'Image to Text / OCR',
    shortName: 'Image to Text (OCR)',
    description: 'Extract selectable text from images, photos, and screenshots locally using in-browser optical character recognition.',
    category: 'productivity',
    keywords: ['ocr', 'image to text', 'extract text', 'scan document', 'screenshot to text', 'tesseract', 'read image'],
    iconName: 'ScanText',
    route: '/image-to-text',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/image-to-text/ImageToTextTool')),
  },
  // 24. Screen Recorder
  {
    id: 'screen-recorder',
    name: 'Screen Recorder',
    shortName: 'Screen Recorder',
    description: 'Record your screen, browser tab, or app window with audio locally in your browser.',
    category: 'media',
    keywords: ['screen recorder', 'record screen', 'capture video', 'screen capture', 'screencast', 'record tab', 'webcam', 'video'],
    iconName: 'Video',
    route: '/screen-recorder',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/screen-recorder/ScreenRecorderTool')),
  },
  // 25. Audio Recorder & Trimmer
  {
    id: 'audio-recorder',
    name: 'Audio Recorder & Trimmer',
    shortName: 'Audio Recorder',
    description: 'Record or upload audio, trim waveforms visually, adjust gain and fade effects, and export standard WAV files locally.',
    category: 'media',
    keywords: ['audio recorder', 'voice memo', 'trim audio', 'sound recorder', 'mic', 'waveform', 'wav', 'sound cutter'],
    iconName: 'Mic',
    route: '/audio-recorder',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/audio-recorder/AudioRecorderTool')),
  },
  // 26. Text to Speech
  {
    id: 'text-to-speech',
    name: 'Text to Speech / Voice Synthesizer',
    shortName: 'Text to Speech',
    description: 'Listen to any text aloud with customizable browser voices, speech rate, pitch, and sentence highlighting.',
    category: 'productivity',
    keywords: ['text to speech', 'tts', 'voice', 'read aloud', 'speech synthesis', 'narrate', 'speak', 'audiobook'],
    iconName: 'Volume2',
    route: '/text-to-speech',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/text-to-speech/TextToSpeechTool')),
  },
  // 27. Random Picker & Team Generator
  {
    id: 'random-picker',
    name: 'Random Picker & Team Generator',
    shortName: 'Random Picker',
    description: 'Draw raffle winners, generate randomized teams, shuffle lists, and create Secret Santa buddy pairings using cryptographic randomness.',
    category: 'productivity',
    keywords: ['random picker', 'team generator', 'raffle', 'shuffle', 'secret santa', 'pairs', 'groups', 'decision maker', 'wheel'],
    iconName: 'Dice5',
    route: '/random-picker',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/random-picker/RandomPickerTool')),
  },
  // 28. Recipe Scaler & Converter
  {
    id: 'recipe-scaler',
    name: 'Recipe Scaler & Unit Converter',
    shortName: 'Recipe Scaler',
    description: 'Scale recipe ingredients precisely for any serving size with automatic metric/US unit conversions and fraction formatting.',
    category: 'productivity',
    keywords: ['recipe scaler', 'cooking converter', 'servings', 'kitchen math', 'baking converter', 'ingredients', 'grams to cups'],
    iconName: 'Utensils',
    route: '/recipe-scaler',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/recipe-scaler/RecipeScalerTool')),
  },
  // 29. Checklist & Packing List
  {
    id: 'checklist',
    name: 'Checklist & Packing List',
    shortName: 'Checklist & Packing',
    description: 'Create, customize, and track packing lists and todo checklists offline with pre-built travel and moving templates.',
    category: 'productivity',
    keywords: ['checklist', 'packing list', 'travel checklist', 'todo', 'task list', 'moving checklist', 'camping list', 'grocery'],
    iconName: 'CheckSquare',
    route: '/checklist',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/checklist/ChecklistTool')),
  },
  // 30. Quick Notepad / Scratchpad
  {
    id: 'notepad',
    name: 'Quick Notepad / Scratchpad',
    shortName: 'Quick Notepad',
    description: 'Autosaving local scratchpad for quick notes, code snippets, drafts, and seamless data transfer across Tiny Tools.',
    category: 'productivity',
    keywords: ['notepad', 'notes', 'scratchpad', 'draft', 'memo', 'pastebin', 'markdown note', 'quick text'],
    iconName: 'FileText',
    route: '/notepad',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/quick-notepad/QuickNotepadTool')),
  },
  // 31. Video Toolkit & Editor
  {
    id: 'video-toolkit',
    name: 'Video Toolkit & Editor',
    shortName: 'Video Toolkit',
    description: 'Trim, crop aspect ratios, rotate, resize, adjust playback speed, mute audio, or extract WAV tracks locally.',
    category: 'media',
    keywords: ['video', 'trim video', 'crop video', 'rotate video', 'speed', 'extract audio', 'resize video', 'mute video'],
    iconName: 'Video',
    route: '/video-toolkit',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/video-toolkit/VideoToolkitTool')),
  },
  // 32. Document & Receipt Scanner
  {
    id: 'document-scanner',
    name: 'Document & Receipt Scanner',
    shortName: 'Doc Scanner',
    description: 'Perspective warp correction, scan contrast enhancement, black & white thresholding, and camera capture.',
    category: 'productivity',
    keywords: ['scanner', 'document', 'receipt', 'perspective', 'warp', 'deskew', 'pdf', 'crop', 'enhance', 'contrast'],
    iconName: 'ScanText',
    route: '/document-scanner',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/document-scanner/DocumentScannerTool')),
  },
  // 33. Speech to Text / Voice Transcriber
  {
    id: 'speech-to-text',
    name: 'Speech to Text / Voice Transcriber',
    shortName: 'Speech to Text',
    description: 'Transcribe live microphone speech into text with timestamps and multi-language support in your browser.',
    category: 'productivity',
    keywords: ['speech to text', 'voice transcription', 'dictation', 'speech recognition', 'transcribe', 'microphone', 'subtitles'],
    iconName: 'Mic',
    route: '/speech-to-text',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/speech-to-text/SpeechToTextTool')),
  },
  // 34. ZIP File Pack & Unpack
  {
    id: 'zip-manager',
    name: 'ZIP File Pack & Unpack',
    shortName: 'ZIP Manager',
    description: 'Create compressed .ZIP archives from multiple files or inspect and extract existing ZIP files in-browser.',
    category: 'files',
    keywords: ['zip', 'archive', 'unzip', 'compress', 'extract', 'files', 'tar', 'folder', 'deflate'],
    iconName: 'FolderArchive',
    route: '/zip-manager',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/zip-manager/ZipManagerTool')),
  },
  // 35. Screenshot Stitcher
  {
    id: 'screenshot-stitcher',
    name: 'Screenshot Stitcher',
    shortName: 'Screenshot Stitcher',
    description: 'Stitch multiple sequential screenshots into one seamless long capture with automated overlap detection.',
    category: 'image',
    keywords: ['stitch', 'screenshot', 'scroll screenshot', 'long image', 'combine screenshots', 'overlap', 'vertical stitch'],
    iconName: 'Layers',
    route: '/screenshot-stitcher',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/screenshot-stitcher/ScreenshotStitcherTool')),
  },
  // 36. Photo Metadata & EXIF Cleaner
  {
    id: 'photo-metadata-cleaner',
    name: 'Photo Metadata & EXIF Cleaner',
    shortName: 'EXIF Cleaner',
    description: 'Inspect and remove sensitive GPS locations, camera serials, timestamps, and EXIF tags from photos.',
    category: 'image',
    keywords: ['exif', 'metadata', 'privacy', 'gps', 'location', 'clean photo', 'strip exif', 'camera info'],
    iconName: 'ShieldAlert',
    route: '/photo-metadata-cleaner',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/photo-metadata-cleaner/PhotoMetadataCleanerTool')),
  },
  // 37. Animated GIF Maker
  {
    id: 'gif-maker',
    name: 'Animated GIF Maker',
    shortName: 'GIF Maker',
    description: 'Convert video clips or multiple image sequences into smooth animated GIFs with custom FPS and captions.',
    category: 'media',
    keywords: ['gif', 'gif maker', 'video to gif', 'images to gif', 'animation', 'loop', 'frames', 'meme generator'],
    iconName: 'Film',
    route: '/gif-maker',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/gif-maker/GifMakerTool')),
  },
  // 38. Batch File Renamer
  {
    id: 'batch-file-renamer',
    name: 'Batch File Renamer',
    shortName: 'Batch Renamer',
    description: 'Rename multiple files at once with prefix/suffix rules, find-replace regex, sequential numbering, and ZIP export.',
    category: 'files',
    keywords: ['rename', 'batch rename', 'bulk rename', 'numbering', 'regex replace', 'file manager', 'extension change'],
    iconName: 'FileText',
    route: '/batch-file-renamer',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/batch-file-renamer/BatchFileRenamerTool')),
  },
  // 39. Text & Code Diff Checker
  {
    id: 'text-diff',
    name: 'Text & Code Diff Checker',
    shortName: 'Diff Checker',
    description: 'Compare two text files, markdown documents, or code snippets side-by-side with word-level highlight precision.',
    category: 'developer',
    keywords: ['diff', 'compare', 'difference', 'code diff', 'text diff', 'similarity', 'changes', 'patch'],
    iconName: 'GitCompare',
    route: '/text-diff',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/text-diff/TextDiffCheckerTool')),
  },
  // 40. Passport / ID Photo Maker
  {
    id: 'id-photo-maker',
    name: 'Passport & ID Photo Maker',
    shortName: 'ID Photo Maker',
    description: 'Prepare portrait photos to common standard passport/visa presets with biometric guides and printable sheets.',
    category: 'image',
    keywords: ['passport', 'id photo', 'visa photo', 'print sheet', '2x2', '35x45', 'biometric', 'portrait', 'crop photo'],
    iconName: 'Image',
    route: '/id-photo-maker',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/id-photo-maker/IdPhotoMakerTool')),
  },
  // 41. Barcode Studio & Scanner
  {
    id: 'barcode-studio',
    name: 'Barcode Studio & Scanner',
    shortName: 'Barcode Studio',
    description: 'Generate customizable 1D barcodes (Code 128, EAN, UPC, Code 39) with SVG/PNG export and scan barcode images.',
    category: 'everyday',
    keywords: ['barcode', 'code128', 'ean13', 'upc', 'code39', 'isbn', 'inventory', 'scanner', 'generator'],
    iconName: 'Barcode',
    route: '/barcode-studio',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/barcode-studio/BarcodeStudioTool')),
  },
  // 42. Watermark Maker
  {
    id: 'watermark-maker',
    name: 'Watermark & Stamp Maker',
    shortName: 'Watermark Maker',
    description: 'Stamp text or logo watermarks onto single or batch photos with position presets, opacity, and ZIP download.',
    category: 'image',
    keywords: ['watermark', 'stamp', 'batch watermark', 'protect photo', 'logo overlay', 'copyright', 'opacity'],
    iconName: 'Stamp',
    route: '/watermark-maker',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/watermark-maker/WatermarkMakerTool')),
  },
  // 43. Signature Maker & Cleaner
  {
    id: 'signature-maker',
    name: 'Signature Maker & Paper Cleaner',
    shortName: 'Signature Maker',
    description: 'Draw smooth digital signatures, type cursive scripts, or upload handwritten paper scans with background removal.',
    category: 'productivity',
    keywords: ['signature', 'sign', 'draw signature', 'clean signature', 'transparent signature', 'cursive', 'paper scan'],
    iconName: 'PenTool',
    route: '/signature-maker',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/signature-maker/SignatureMakerTool')),
  },
  // 44. Whiteboard & Sketchpad
  {
    id: 'whiteboard',
    name: 'Whiteboard & Sketchpad',
    shortName: 'Whiteboard',
    description: 'Lightweight drawing canvas with pens, highlighters, shapes, arrows, step markers, grid/dot patterns, and image export.',
    category: 'productivity',
    keywords: ['whiteboard', 'sketch', 'draw', 'diagram', 'canvas', 'marker', 'arrows', 'flowchart', 'doodle'],
    iconName: 'Presentation',
    route: '/whiteboard',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/whiteboard/WhiteboardTool')),
  },
  // 45. Teleprompter
  {
    id: 'teleprompter',
    name: 'Teleprompter & Speech Timer',
    shortName: 'Teleprompter',
    description: 'Smooth auto-scrolling teleprompter with speed controls, fullscreen mirror mode for glass rigs, and reading focus guide.',
    category: 'productivity',
    keywords: ['teleprompter', 'prompter', 'speech', 'presentation', 'autoscroll', 'mirror', 'reading guide', 'speaking timer'],
    iconName: 'Monitor',
    route: '/teleprompter',
    featured: true,
    acceptsTextTransfer: true,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/teleprompter/TeleprompterTool')),
  },
  // 46. Color Palette Extractor
  {
    id: 'palette-extractor',
    name: 'Color Palette Extractor & Harmonies',
    shortName: 'Palette Extractor',
    description: 'Extract dominant color swatches from uploaded images, check contrast, and generate color harmonies and CSS variables.',
    category: 'design',
    keywords: ['palette', 'extract colors', 'dominant color', 'color scheme', 'harmony', 'css variables', 'swatches'],
    iconName: 'Palette',
    route: '/palette-extractor',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/palette-extractor/PaletteExtractorTool')),
  },
  // 47. Calendar Event / ICS Maker
  {
    id: 'calendar-event-maker',
    name: 'Calendar Event & ICS Maker',
    shortName: 'Calendar Event',
    description: 'Generate standard RFC 5545 .ics calendar files for Google Calendar, Apple Calendar, and Outlook with alarms and repeat rules.',
    category: 'time',
    keywords: ['calendar', 'ics', 'icalendar', 'event', 'meeting', 'reminder', 'schedule', 'rrule', 'outlook', 'google calendar'],
    iconName: 'CalendarPlus',
    route: '/calendar-event-maker',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: true,
    component: lazy(() => import('../tools/calendar-event-maker/CalendarEventMakerTool')),
  },
  // 48. Metronome & Tap Tempo
  {
    id: 'metronome',
    name: 'Metronome & Tap Tempo',
    shortName: 'Metronome',
    description: 'Accurate Web Audio lookahead metronome with BPM slider, tap tempo calculator, time signatures, and subdivisions.',
    category: 'media',
    keywords: ['metronome', 'tempo', 'bpm', 'tap tempo', 'rhythm', 'beat', 'time signature', 'subdivision', 'click track'],
    iconName: 'Music',
    route: '/metronome',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/metronome/MetronomeTool')),
  },
  // 49. Duplicate File Finder
  {
    id: 'duplicate-finder',
    name: 'Duplicate File Finder',
    shortName: 'Duplicate Finder',
    description: 'Find identical duplicate files locally using fast SHA-256 Web Crypto hashing, calculate wasted space, and export reports.',
    category: 'files',
    keywords: ['duplicate', 'duplicate files', 'dedupe', 'hash', 'sha256', 'wasted space', 'file cleanup', 'audit report'],
    iconName: 'Files',
    route: '/duplicate-finder',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/duplicate-finder/DuplicateFinderTool')),
  },
  // 50. Meme & Caption Maker
  {
    id: 'meme-maker',
    name: 'Meme & Caption Maker',
    shortName: 'Meme Maker',
    description: 'Create classic Impact memes, modern header captions, or custom captioned photos client-side with instant export.',
    category: 'media',
    keywords: ['meme', 'caption', 'impact font', 'funny', 'image caption', 'doge', 'meme generator', 'watermark'],
    iconName: 'Smile',
    route: '/meme-maker',
    featured: true,
    acceptsTextTransfer: false,
    producesTextTransfer: false,
    component: lazy(() => import('../tools/meme-maker/MemeMakerTool')),
  },
];

export const CATEGORIES: { id: ToolCategory; label: string; description: string }[] = [
  { id: 'text', label: 'Text Tools', description: 'Clean, convert case, count words, and process lists' },
  { id: 'developer', label: 'Developer Utilities', description: 'Format JSON, test regex, diff text, encode URLs & Base64, and generate secure passwords' },
  { id: 'math', label: 'Math & Commercial', description: 'Percentages, unit conversion, unit pricing, discounts & margins' },
  { id: 'time', label: 'Time & Dates', description: 'Date arithmetic, worldwide time zones, and stopwatch/timers' },
  { id: 'design', label: 'Design & Visuals', description: 'Color converter, WCAG contrast, and aspect ratios' },
  { id: 'everyday', label: 'Everyday Tools', description: 'QR Code Studio and grocery unit price comparator' },
  { id: 'image', label: 'Image Tools', description: 'Client-side image optimizer, collage maker, stitcher, EXIF cleaner, and background remover' },
  { id: 'media', label: 'Media & Audio', description: 'In-browser screen recorder, GIF maker, video toolkit, and audio trimmer' },
  { id: 'productivity', label: 'Productivity & Office', description: 'OCR text extractor, speech recognition, speech synthesizer, random picker, recipe scaler, and checklists' },
  { id: 'files', label: 'Files & Archives', description: 'Client-side ZIP pack/extract and batch file renamer' },
];

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOLS_REGISTRY.find((t) => t.id === id);
}

export function searchTools(query: string, category?: ToolCategory | 'all'): ToolDefinition[] {
  const cleanQ = query.trim().toLowerCase();
  return TOOLS_REGISTRY.filter((tool) => {
    if (category && category !== 'all' && tool.category !== category) {
      return false;
    }
    if (!cleanQ) return true;

    const matchesName = tool.name.toLowerCase().includes(cleanQ);
    const matchesDesc = tool.description.toLowerCase().includes(cleanQ);
    const matchesKeywords = tool.keywords.some((k) => k.toLowerCase().includes(cleanQ));
    return matchesName || matchesDesc || matchesKeywords;
  });
}
