import React,{useMemo,useState}from'react';
import{Clipboard,Code2,RefreshCw,ShieldCheck}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{convertIntegerBase,dateToEpoch,decodeHtmlEntities,decodeJwt,encodeHtmlEntities,epochToDate,generateUlid,generateUuidV4,generateUuidV7,hexToText,nextCronMatches,textToHex,type EpochUnit}from'../../utilities/privacy-dev-tools';
import{getPublicPrivacyDevTask,PUBLIC_PRIVACY_DEV_TASKS}from'../../privacy-dev/publicPrivacyDevTasks';
function currentId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
function safe<T>(fn:()=>T){try{return{value:fn(),error:''}}catch(e){return{value:null,error:e instanceof Error?e.message:'Unable to process input.'}}}
const JWT_SAMPLE='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjMiLCJpYXQiOjE3MDAwMDAwMDB9.signature';
const DeveloperMicroTools:React.FC<{initialText?:string}>=({initialText})=>{const task=useMemo(()=>getPublicPrivacyDevTask(currentId())??PUBLIC_PRIVACY_DEV_TASKS.find(t=>t.group==='developer')!,[]),[count,setCount]=useState(5),[uuidVersion,setUuidVersion]=useState<'v4'|'v7'>('v4'),[ids,setIds]=useState<string[]>([]),[jwt,setJwt]=useState(initialText||JWT_SAMPLE),[epoch,setEpoch]=useState(String(Math.floor(Date.now()/1000))),[epochUnit,setEpochUnit]=useState<EpochUnit>('auto'),[dateText,setDateText]=useState(new Date().toISOString()),[baseValue,setBaseValue]=useState('FF'),[fromBase,setFromBase]=useState(16),[toBase,setToBase]=useState(10),[hexMode,setHexMode]=useState<'encode'|'decode'>('encode'),[hexText,setHexText]=useState(initialText||'Tiny Tools'),[entityMode,setEntityMode]=useState<'encode'|'decode'>('encode'),[entityText,setEntityText]=useState(initialText||'<strong>Tom & Jerry</strong>'),[cron,setCron]=useState('*/15 9-17 * * mon-fri'),[copied,setCopied]=useState(false);const jwtResult=useMemo(()=>safe(()=>decodeJwt(jwt)),[jwt]),epochResult=useMemo(()=>safe(()=>epochToDate(epoch,epochUnit)),[epoch,epochUnit]),dateResult=useMemo(()=>safe(()=>dateToEpoch(dateText)),[dateText]),baseResult=useMemo(()=>safe(()=>convertIntegerBase(baseValue,fromBase,toBase)),[baseValue,fromBase,toBase]),hexResult=useMemo(()=>safe(()=>hexMode==='encode'?textToHex(hexText):hexToText(hexText)),[hexMode,hexText]),entityResult=useMemo(()=>safe(()=>entityMode==='encode'?encodeHtmlEntities(entityText):decodeHtmlEntities(entityText)),[entityMode,entityText]),cronResult=useMemo(()=>safe(()=>nextCronMatches(cron,new Date(),8)),[cron]);
 const copy=async(value:string)=>{if(await copyToClipboard(value)){setCopied(true);setTimeout(()=>setCopied(false),1200)}};const generate=()=>{const n=Math.max(1,Math.min(100,Math.round(count)));setIds(Array.from({length:n},()=>task.id==='ulid-generator'?generateUlid():uuidVersion==='v7'?generateUuidV7():generateUuidV4()))};
 return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={['json-formatter','encoding-tools','secure-generator']}><div className="space-y-5"><div className="flex items-center gap-2 rounded-lg border border-indigo-200 bg-indigo-50 px-3 py-2 text-xs text-indigo-700 dark:border-indigo-900 dark:bg-indigo-950/20 dark:text-indigo-300"><Code2 className="h-4 w-4"/>Processed locally in this browser. Developer-facing limitations are shown explicitly.</div>
 {['uuid-generator','ulid-generator'].includes(task.id)&&<><div className="grid gap-3 sm:grid-cols-2"><NumberField label="How many" value={count} set={setCount} min={1} max={100}/>{task.id==='uuid-generator'&&<label className="text-xs font-semibold">Version<select value={uuidVersion} onChange={e=>setUuidVersion(e.target.value as'v4'|'v7')} className="mt-1 w-full rounded border bg-transparent px-3 py-2"><option value="v4">UUID v4 · random</option><option value="v7">UUID v7 · time ordered</option></select></label>}</div><button onClick={generate} className="inline-flex items-center gap-2 rounded-lg bg-indigo-600 px-4 py-2 text-xs font-bold text-white"><RefreshCw className="h-4 w-4"/>Generate</button>{ids.length>0&&<Output value={ids.join('\n')} copied={copied} copy={copy}/>}<p className="text-xs text-neutral-500">{task.id==='ulid-generator'?'ULIDs use the current millisecond timestamp plus 80 cryptographically random bits. Same-millisecond output is not advertised as monotonic.':'UUID v4 uses cryptographic randomness. UUID v7 embeds the current Unix-millisecond timestamp and RFC-style version/variant bits.'}</p></>}
 {task.id==='jwt-decoder'&&<><TextArea label="JWT" value={jwt} set={setJwt}/>{jwtResult.value?<div className="grid gap-3 lg:grid-cols-2"><JsonBlock title="Header" value={jwtResult.value.header}/><JsonBlock title="Payload" value={jwtResult.value.payload}/><section className="rounded-xl border p-3 text-xs lg:col-span-2"><div>Algorithm claim: <b>{jwtResult.value.algorithm||'none / unspecified'}</b></div><div>Signature segment present: <b>{jwtResult.value.signaturePresent?'yes':'no'}</b></div>{jwtResult.value.issuedAt&&<div>iat: {jwtResult.value.issuedAt}</div>}{jwtResult.value.notBefore&&<div>nbf: {jwtResult.value.notBefore}</div>}{jwtResult.value.expiresAt&&<div>exp: {jwtResult.value.expiresAt}</div>}</section></div>:<ErrorBox text={jwtResult.error}/>}<p className="text-xs font-semibold text-amber-700 dark:text-amber-300">Decoding is not verification. Tiny Tools does not validate the JWT signature, issuer, audience, key, or trustworthiness.</p></>}
 {task.id==='unix-timestamp-converter'&&<><div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Unix timestamp<input value={epoch} onChange={e=>setEpoch(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2 font-mono"/></label><label className="text-xs font-semibold">Unit<select value={epochUnit} onChange={e=>setEpochUnit(e.target.value as EpochUnit)} className="mt-1 w-full rounded border bg-transparent px-3 py-2"><option value="auto">Auto detect</option><option value="seconds">Seconds</option><option value="milliseconds">Milliseconds</option></select></label></div>{epochResult.value?<div className="grid gap-3 sm:grid-cols-2"><Stat label="ISO 8601" value={epochResult.value.iso}/><Stat label="Browser local time" value={epochResult.value.local}/><Stat label="Epoch seconds" value={String(epochResult.value.seconds)}/><Stat label="Epoch milliseconds" value={String(epochResult.value.milliseconds)}/></div>:<ErrorBox text={epochResult.error}/>}<label className="block text-xs font-semibold">Date / time → epoch<input value={dateText} onChange={e=>setDateText(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2 font-mono"/></label>{dateResult.value?<p className="text-xs">{dateResult.value.iso} · {dateResult.value.seconds}s · {dateResult.value.milliseconds}ms</p>:<ErrorBox text={dateResult.error}/>}</>}
 {task.id==='number-base-converter'&&<><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs font-semibold">Integer<input value={baseValue} onChange={e=>setBaseValue(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2 font-mono"/></label><NumberField label="From base" value={fromBase} set={setFromBase} min={2} max={36}/><NumberField label="To base" value={toBase} set={setToBase} min={2} max={36}/></div>{baseResult.value!==null?<Output value={baseResult.value} copied={copied} copy={copy}/>:<ErrorBox text={baseResult.error}/>}<p className="text-xs text-neutral-500">Uses BigInt, so integer conversion is exact rather than limited to JavaScript's safe-number range.</p></>}
 {task.id==='text-hex-converter'&&<><ModeTabs mode={hexMode} set={setHexMode} left="Text → Hex" right="Hex → Text"/><TextArea label={hexMode==='encode'?'UTF-8 text':'Hexadecimal bytes'} value={hexText} set={setHexText}/>{hexResult.value!==null?<Output value={hexResult.value} copied={copied} copy={copy}/>:<ErrorBox text={hexResult.error}/>}</>}
 {task.id==='html-entity-converter'&&<><ModeTabs mode={entityMode} set={setEntityMode} left="Encode" right="Decode"/><TextArea label={entityMode==='encode'?'HTML-sensitive text':'Entity-encoded text'} value={entityText} set={setEntityText}/>{entityResult.value!==null&&<Output value={entityResult.value} copied={copied} copy={copy}/>}<p className="text-xs text-neutral-500">Encoder escapes the five HTML-sensitive characters. Decoder supports common named entities plus decimal and hexadecimal numeric entities.</p></>}
 {task.id==='cron-expression-helper'&&<><label className="block text-xs font-semibold">Five-field cron expression<input value={cron} onChange={e=>setCron(e.target.value)} spellCheck={false} className="mt-1 w-full rounded border bg-transparent px-3 py-2 font-mono"/></label><div className="rounded-lg bg-neutral-50 p-3 font-mono text-xs dark:bg-neutral-950">minute · hour · day-of-month · month · weekday</div>{cronResult.value?<section className="rounded-xl border p-3"><div className="mb-2 flex items-center gap-2 text-xs font-bold text-emerald-700"><ShieldCheck className="h-4 w-4"/>Valid expression · next matches</div><ol className="space-y-1 text-xs">{cronResult.value.length?cronResult.value.map((d,i)=><li key={i}>{d.toString()}</li>):<li>No match found within the one-year preview window.</li>}</ol></section>:<ErrorBox text={cronResult.error}/>}<p className="text-xs text-neutral-500">Supports standard five-field wildcards, lists, ranges, steps, three-letter month/day names, and traditional cron day-of-month/day-of-week OR semantics. Preview uses the browser's local timezone and searches up to 366 days.</p></>}
 </div></ToolShell>}
function NumberField({label,value,set,min,max}:{label:string;value:number;set:React.Dispatch<React.SetStateAction<number>>;min:number;max:number}){return<label className="text-xs font-semibold">{label}<input type="number" min={min} max={max} value={value} onChange={e=>set(Number(e.target.value))} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>}
function TextArea({label,value,set}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>}){return<label className="block text-xs font-semibold">{label}<textarea rows={8} value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full resize-y rounded-xl border border-neutral-300 bg-white p-3 font-mono text-sm dark:border-neutral-700 dark:bg-neutral-950"/></label>}
function Output({value,copied,copy}:{value:string;copied:boolean;copy:(v:string)=>Promise<void>}){return<section className="rounded-xl border border-neutral-200 bg-neutral-50 p-3 dark:border-neutral-800 dark:bg-neutral-950"><div className="mb-2 flex justify-end"><button onClick={()=>void copy(value)} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Clipboard className="h-3.5 w-3.5"/>{copied?'Copied':'Copy'}</button></div><pre className="max-h-80 overflow-auto whitespace-pre-wrap break-all text-xs">{value}</pre></section>}
function JsonBlock({title,value}:{title:string;value:Record<string,unknown>}){return<section className="rounded-xl border p-3"><h3 className="text-xs font-bold">{title}</h3><pre className="mt-2 overflow-auto whitespace-pre-wrap break-words text-xs">{JSON.stringify(value,null,2)}</pre></section>}
function Stat({label,value}:{label:string;value:string}){return<div className="rounded-xl border p-3"><div className="text-[11px] uppercase tracking-wide text-neutral-500">{label}</div><div className="mt-1 break-words text-sm font-semibold">{value}</div></div>}
function ErrorBox({text}:{text:string}){return<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{text}</div>}
function ModeTabs({mode,set,left,right}:{mode:'encode'|'decode';set:React.Dispatch<React.SetStateAction<'encode'|'decode'>>;left:string;right:string}){return<div className="flex gap-2"><button onClick={()=>set('encode')} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${mode==='encode'?'bg-neutral-900 text-white dark:bg-neutral-100 dark:text-neutral-900':''}`}>{left}</button><button onClick={()=>set('decode')} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${mode==='decode'?'bg-neutral-900 text-white dark:bg-neutral-100 dark:text-neutral-900':''}`}>{right}</button></div>}
export default DeveloperMicroTools;
