import React,{useMemo,useState}from'react';
import{Clipboard,Download,Eye,EyeOff,Loader2,ShieldCheck,Upload}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{analyzePasswordStrength,decryptFileBytes,decryptTextEnvelope,detectDigestAlgorithm,digestBytes,digestText,encryptFileBytes,encryptTextEnvelope,findPiiPatterns,hmacHex,redactPiiPatterns,type DigestAlgorithm}from'../../utilities/privacy-dev-tools';
import{getPublicPrivacyDevTask,PUBLIC_PRIVACY_DEV_TASKS}from'../../privacy-dev/publicPrivacyDevTasks';
function currentId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
function saveBytes(bytes:Uint8Array,name:string){const blob=new Blob([bytes]),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
const SAMPLE='Tiny Tools keeps this text in your browser.';
const PII_SAMPLE='Contact alex@example.com or +49 151 23456789. Test card: 4111 1111 1111 1111. Server: 192.168.1.25.';
const SecurityPrivacyMicroTools:React.FC<{initialText?:string}>=({initialText})=>{const task=useMemo(()=>getPublicPrivacyDevTask(currentId())??PUBLIC_PRIVACY_DEV_TASKS[0],[]),[text,setText]=useState(initialText||SAMPLE),[algorithm,setAlgorithm]=useState<DigestAlgorithm>('SHA-256'),[result,setResult]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[file,setFile]=useState<File|null>(null),[expected,setExpected]=useState(''),[key,setKey]=useState(''),[password,setPassword]=useState(''),[showPassword,setShowPassword]=useState(false),[decryptMode,setDecryptMode]=useState(false),[pii,setPii]=useState(initialText||PII_SAMPLE),[copied,setCopied]=useState(false);const strength=useMemo(()=>analyzePasswordStrength(password),[password]),matches=useMemo(()=>findPiiPatterns(pii),[pii]),redacted=useMemo(()=>redactPiiPatterns(pii,matches),[pii,matches]);
 const copy=async(value:string)=>{if(await copyToClipboard(value)){setCopied(true);setTimeout(()=>setCopied(false),1200)}};
 const run=async()=>{setBusy(true);setError('');setResult('');try{if(task.id==='text-hash-generator')setResult(await digestText(text,algorithm));else if(task.id==='file-checksum-generator'){if(!file)throw new Error('Choose a file first.');setResult(await digestBytes(await file.arrayBuffer(),algorithm));}else if(task.id==='checksum-verifier'){if(!file)throw new Error('Choose a file first.');const detected=detectDigestAlgorithm(expected);if(!detected)throw new Error('Expected checksum must be 64, 96, or 128 hexadecimal characters.');const actual=await digestBytes(await file.arrayBuffer(),detected),clean=expected.trim().replace(/^0x/i,'').replace(/\s+/g,'').toLowerCase();setResult(actual.toLowerCase()===clean?`MATCH · ${detected} · ${actual}`:`MISMATCH · ${detected} · actual ${actual}`);}else if(task.id==='hmac-generator')setResult(await hmacHex(text,key,algorithm));else if(task.id==='text-encryptor')setResult(decryptMode?await decryptTextEnvelope(text,password):await encryptTextEnvelope(text,password));else if(task.id==='file-encryptor'){if(!file)throw new Error('Choose a file first.');if(file.size>128*1024*1024)throw new Error('This browser workflow is capped at 128 MiB per file to avoid excessive memory use.');const data=await file.arrayBuffer(),out=decryptMode?await decryptFileBytes(data,password):await encryptFileBytes(data,password),name=decryptMode?(file.name.endsWith('.ttenc')?file.name.slice(0,-6):`${file.name}.decrypted`):`${file.name}.ttenc`;saveBytes(out,name);setResult(`${decryptMode?'Decrypted':'Encrypted'} ${out.byteLength.toLocaleString()} bytes locally.`)}}catch(e){setError(e instanceof Error?e.message:'Operation failed.')}finally{setBusy(false)}};
 const fileTools=['file-checksum-generator','checksum-verifier','file-encryptor'].includes(task.id),hashTools=['text-hash-generator','file-checksum-generator','hmac-generator'].includes(task.id);
 return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={['secure-generator','image-metadata-cleaner','clean-pdf']}><div className="space-y-5"><div className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-300"><ShieldCheck className="h-4 w-4"/>Runs locally. Secrets, files, and pasted text are not uploaded by Tiny Tools.</div>
 {fileTools&&<label className="block rounded-xl border-2 border-dashed border-neutral-300 p-6 text-center text-sm dark:border-neutral-700"><Upload className="mx-auto h-6 w-6"/><span className="mt-2 block font-semibold">{file?file.name:'Choose a local file'}</span><input type="file" className="mt-3 block w-full text-xs" onChange={e=>setFile(e.target.files?.[0]||null)}/>{file&&<span className="mt-1 block text-xs text-neutral-500">{file.size.toLocaleString()} bytes</span>}</label>}
 {hashTools&&<label className="text-xs font-semibold">Digest<select value={algorithm} onChange={e=>setAlgorithm(e.target.value as DigestAlgorithm)} className="ml-2 rounded border bg-transparent px-2 py-1"><option>SHA-256</option><option>SHA-384</option><option>SHA-512</option></select></label>}
 {task.id==='text-hash-generator'&&<TextArea label="Text" value={text} set={setText}/>} 
 {task.id==='checksum-verifier'&&<label className="block text-xs font-semibold">Expected SHA checksum<input value={expected} onChange={e=>setExpected(e.target.value)} spellCheck={false} className="mt-1 w-full rounded-lg border bg-transparent p-3 font-mono text-xs" placeholder="Paste SHA-256, SHA-384, or SHA-512 hex"/></label>}
 {task.id==='hmac-generator'&&<><TextArea label="Message" value={text} set={setText}/><label className="block text-xs font-semibold">Secret HMAC key<input type="password" value={key} onChange={e=>setKey(e.target.value)} className="mt-1 w-full rounded-lg border bg-transparent p-3" autoComplete="off"/></label></>}
 {task.id==='text-encryptor'&&<><div className="flex gap-2"><ModeButton active={!decryptMode} onClick={()=>setDecryptMode(false)}>Encrypt</ModeButton><ModeButton active={decryptMode} onClick={()=>setDecryptMode(true)}>Decrypt TT1</ModeButton></div><TextArea label={decryptMode?'TT1 encrypted envelope':'Plain text'} value={text} set={setText}/><PasswordField value={password} set={setPassword} show={showPassword} setShow={setShowPassword}/><p className="text-xs text-neutral-500">PBKDF2-SHA-256 (210,000 iterations) derives an AES-256-GCM key. The password is not stored in the envelope.</p></>}
 {task.id==='file-encryptor'&&<><div className="flex gap-2"><ModeButton active={!decryptMode} onClick={()=>setDecryptMode(false)}>Encrypt</ModeButton><ModeButton active={decryptMode} onClick={()=>setDecryptMode(true)}>Decrypt TTF1</ModeButton></div><PasswordField value={password} set={setPassword} show={showPassword} setShow={setShowPassword}/><p className="text-xs text-neutral-500">Whole-file AES-256-GCM processing is capped at 128 MiB. Keep the password separately: Tiny Tools cannot recover it.</p></>}
 {task.id==='password-strength-checker'&&<><PasswordField value={password} set={setPassword} show={showPassword} setShow={setShowPassword}/><div className="grid gap-3 sm:grid-cols-3"><Stat label="Rating" value={strength.label}/><Stat label="Heuristic score" value={`${strength.score}/4`}/><Stat label="Estimated entropy" value={`${strength.entropyBits.toFixed(1)} bits`}/></div><ul className="list-disc space-y-1 pl-5 text-xs text-neutral-500">{strength.warnings.map(w=><li key={w}>{w}</li>)}</ul><p className="text-xs text-neutral-500">This is a local heuristic, not a breach-database lookup or an exact cracking-time prediction.</p></>}
 {task.id==='pii-pattern-redactor'&&<><TextArea label="Text to inspect" value={pii} set={setPii}/><div className="grid gap-3 sm:grid-cols-2"><section className="rounded-xl border p-3"><h3 className="text-xs font-bold">Detected patterns · {matches.length}</h3><div className="mt-2 max-h-52 overflow-auto space-y-1 text-xs">{matches.length?matches.map((m,i)=><div key={`${m.start}-${i}`}><span className="font-semibold">{m.type}</span> · <span className="font-mono">{m.value}</span></div>):<span className="text-neutral-400">No supported patterns found.</span>}</div></section><section className="rounded-xl border p-3"><div className="flex items-center justify-between"><h3 className="text-xs font-bold">Redacted output</h3><CopyButton copied={copied} onClick={()=>void copy(redacted)}/></div><pre className="mt-2 whitespace-pre-wrap break-words text-xs">{redacted}</pre></section></div><p className="text-xs text-neutral-500">Detects common email, phone-like, IPv4, and Luhn-valid payment-card patterns only. It does not identify names, addresses, or every form of personal data.</p></>}
 {['text-hash-generator','file-checksum-generator','checksum-verifier','hmac-generator','text-encryptor','file-encryptor'].includes(task.id)&&<div className="flex flex-wrap items-center gap-3"><button onClick={()=>void run()} disabled={busy||(fileTools&&!file)} className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-4 py-2 text-xs font-bold text-white disabled:opacity-40 dark:bg-neutral-100 dark:text-neutral-900">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:task.id==='file-encryptor'?<Download className="h-4 w-4"/>:<ShieldCheck className="h-4 w-4"/>}{busy?'Working…':task.id==='checksum-verifier'?'Verify':task.id==='file-encryptor'?(decryptMode?'Decrypt & download':'Encrypt & download'):'Run locally'}</button>{result&&task.id!=='file-encryptor'&&<CopyButton copied={copied} onClick={()=>void copy(result)}/>}</div>}
 {result&&<pre className="overflow-auto whitespace-pre-wrap break-all rounded-xl border border-neutral-200 bg-neutral-50 p-4 text-xs dark:border-neutral-800 dark:bg-neutral-950">{result}</pre>}{error&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{error}</div>}</div></ToolShell>}
function TextArea({label,value,set}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>}){return<label className="block text-xs font-semibold">{label}<textarea rows={8} value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full resize-y rounded-xl border border-neutral-300 bg-white p-3 font-mono text-sm dark:border-neutral-700 dark:bg-neutral-950"/></label>}
function PasswordField({value,set,show,setShow}:{value:string;set:React.Dispatch<React.SetStateAction<string>>;show:boolean;setShow:React.Dispatch<React.SetStateAction<boolean>>}){return<label className="block text-xs font-semibold">Password<div className="mt-1 flex gap-2"><input type={show?'text':'password'} value={value} onChange={e=>set(e.target.value)} autoComplete="off" className="min-w-0 flex-1 rounded-lg border bg-transparent p-3"/><button type="button" onClick={()=>setShow(v=>!v)} className="rounded-lg border px-3" aria-label={show?'Hide password':'Show password'}>{show?<EyeOff className="h-4 w-4"/>:<Eye className="h-4 w-4"/>}</button></div></label>}
function ModeButton({active,onClick,children}:{active:boolean;onClick:()=>void;children:React.ReactNode}){return<button onClick={onClick} className={`rounded-lg border px-3 py-2 text-xs font-semibold ${active?'bg-neutral-900 text-white dark:bg-neutral-100 dark:text-neutral-900':''}`}>{children}</button>}
function Stat({label,value}:{label:string;value:React.ReactNode}){return<div className="rounded-xl border p-3"><div className="text-[11px] uppercase tracking-wide text-neutral-500">{label}</div><div className="mt-1 text-lg font-bold">{value}</div></div>}
function CopyButton({copied,onClick}:{copied:boolean;onClick:()=>void}){return<button onClick={onClick} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Clipboard className="h-3.5 w-3.5"/>{copied?'Copied':'Copy'}</button>}
export default SecurityPrivacyMicroTools;
