import type{ToolCategory}from'../types';
export type P19DiagnosticMode='speed'|'stability'|'ip'|'webrtc'|'capabilities'|'webgl'|'webgpu'|'codecs'|'storage';
export interface PublicP19Task{id:string;name:string;shortName:string;description:string;keywords:string[];mode:P19DiagnosticMode;category:ToolCategory;networkUse:'local'|'external';featured?:boolean}
type Raw=[string,string,string,string,P19DiagnosticMode,'local'|'external',string?,boolean?];
const RAW:Raw[]=[
['internet-speed-test','Internet Speed Test','Measure download and upload throughput plus HTTPS latency and jitter against Cloudflare public speed-test endpoints. Test bytes are generated in memory; no user files are sent.','internet speed test|speed test|download speed|upload speed|bandwidth test|ping test|latency jitter|network speed|wifi speed','speed','external','Speed Test',true],
['connection-stability-test','Connection Stability Test','Sample repeated HTTPS round trips to Cloudflare and summarize latency variation, jitter, slow spikes, and request failures without claiming ICMP packet-loss measurement.','connection stability|internet stability|network stability|jitter test|latency monitor|connection drops|packet loss alternative|wifi stability','stability','external','Stability Test',true],
['ipv4-ipv6-test','IPv4 / IPv6 Connectivity Test','Probe IPv4-only and IPv6-only Cloudflare hosts from this browser to identify IPv4, IPv6, dual-stack, or unavailable Internet reachability.','ipv4 test|ipv6 test|dual stack test|ipv6 connectivity|ipv4 connectivity|internet protocol test|ip version','ip','external','IPv4 / IPv6',true],
['webrtc-leak-test','WebRTC Leak Test','Inspect browser ICE candidates locally and optionally use Cloudflare STUN to see whether WebRTC exposes literal local or public IP addresses instead of privacy-preserving mDNS names.','webrtc leak test|ip leak test|webrtc privacy|ice candidate|stun test|local ip leak|public ip leak','webrtc','external','WebRTC Leak',true],
['browser-capability-inspector','Browser Capability Inspector','Inspect modern browser APIs and security-context capabilities locally, including workers, WebAssembly, WebRTC, WebGPU, storage, compression, WebCodecs, clipboard, and file-system features.','browser capabilities|browser feature test|web api support|feature detection|browser compatibility|wasm webworker service worker|webcodecs','capabilities','local','Browser Capabilities',true],
['webgl-inspector','WebGL Inspector','Inspect the browser WebGL/WebGL2 context locally, including renderer strings when exposed, texture/renderbuffer limits, antialiasing, and supported extensions.','webgl inspector|webgl test|gpu renderer|graphics card browser|webgl2 support|gpu info|webgl extensions','webgl','local','WebGL Inspector',true],
['webgpu-inspector','WebGPU Inspector','Request a WebGPU adapter locally and inspect exposed adapter information, features, and selected GPU limits without sending graphics data anywhere.','webgpu test|webgpu inspector|webgpu support|gpu adapter|gpu limits|webgpu features|browser gpu','webgpu','local','WebGPU Inspector',true],
['codec-support-tester','Media Codec Support Tester','Ask this browser which common audio/video MIME types it declares decodable or recordable, covering MP4/H.264, HEVC, AV1, VP8/VP9, Opus, AAC, MP3, FLAC, Ogg, WebM, and WAV.','codec support test|video codec support|audio codec support|h264 hevc av1 vp9 vp8 opus aac mp3 flac webm mp4|media recorder support','codecs','local','Codec Support',true],
['storage-quota-inspector','Browser Storage & Quota Inspector','Inspect browser storage quota and usage locally plus IndexedDB, Cache Storage, persistent-storage, localStorage, and OPFS capability when exposed.','browser storage quota|storage inspector|indexeddb quota|cache storage|persistent storage|opfs|localstorage size|storage estimate','storage','local','Storage & Quota',true],
];
export const PUBLIC_P19_TASKS:PublicP19Task[]=RAW.map(([id,name,description,keys,mode,networkUse,shortName,featured])=>({id,name,shortName:shortName||name,description,keywords:keys.split('|'),mode,category:'device',networkUse,featured:Boolean(featured)}));
export function getPublicP19Task(id:string|null|undefined){return id?PUBLIC_P19_TASKS.find(t=>t.id===id):undefined}
