import type{ToolCategory}from'../types';
export type P11Engine='developer'|'math'|'web';
export interface PublicP11Task{id:string;name:string;shortName:string;description:string;keywords:string[];engine:P11Engine;category:ToolCategory;featured?:boolean}
type Raw=[string,string,string,string,P11Engine,ToolCategory,string?,boolean?];
const RAW:Raw[]=[
['yaml-formatter','YAML Formatter & Validator','Format and validate a practical YAML subset with indentation-aware local parsing.','yaml formatter|yaml validator|prettify yaml|validate yaml','developer','developer','YAML Formatter',true],
['yaml-json-converter','YAML ↔ JSON Converter','Convert common YAML mappings, sequences, scalars, and JSON documents locally in either direction.','yaml to json|json to yaml|convert yaml json','developer','developer','YAML ↔ JSON',true],
['toml-formatter','TOML Formatter & Validator','Format and validate common TOML key/value data, arrays, and table sections locally.','toml formatter|toml validator|prettify toml','developer','developer','TOML Formatter'],
['toml-json-converter','TOML ↔ JSON Converter','Convert common TOML tables and values to JSON, or JSON objects back to deterministic TOML.','toml to json|json to toml|convert toml json','developer','developer','TOML ↔ JSON'],
['sql-formatter','SQL Formatter & Minifier','Format or minify common SQL statements with quote-aware tokenization and keyword layout.','sql formatter|format sql|sql minifier|prettify query','developer','developer','SQL Formatter',true],
['json-schema-validator','JSON Schema Validator','Validate JSON against a useful local subset of JSON Schema including types, required fields, properties, arrays, enums, ranges, and patterns.','json schema validator|validate json schema|schema validation','developer','developer','JSON Schema',true],
['jsonpath-tester','JSONPath Tester','Evaluate practical JSONPath expressions with root, dot, bracket, index, and wildcard selectors.','jsonpath tester|json path|query json|json selector','developer','developer','JSONPath Tester'],
['base-encoding-converter','Base32 / Base58 / Base85 Converter','Encode or decode UTF-8 data using Base32, Bitcoin-style Base58, or Ascii85 locally.','base32|base58|base85|ascii85|encoding converter','developer','developer','Base Encoding',true],
['file-base64-converter','File ↔ Base64 Converter','Encode a local file as Base64 or decode Base64 text into a downloadable binary file.','file to base64|base64 to file|data url|binary base64','developer','files','File ↔ Base64',true],
['cidr-subnet-calculator','CIDR / Subnet Calculator','Calculate IPv4 network, broadcast, usable host range, mask, wildcard mask, and host counts from CIDR notation.','cidr calculator|subnet calculator|ipv4 network|netmask','developer','developer','Subnet Calculator',true],
['user-agent-parser','User-Agent Parser','Parse a browser user-agent string into likely browser, rendering engine, operating system, and device class.','user agent parser|ua parser|browser detector|device parser','developer','developer','User-Agent Parser'],
['utm-link-builder','UTM Link Builder','Build campaign URLs with correctly encoded UTM source, medium, campaign, term, and content parameters.','utm builder|campaign url|utm_source|marketing link','developer','developer','UTM Builder',true],
['markdown-html-converter','Markdown ↔ HTML Converter','Convert common Markdown to safe HTML or turn basic HTML structure back into readable Markdown locally.','markdown to html|html to markdown|md converter','developer','text','Markdown ↔ HTML',true],
['matrix-calculator','Matrix Calculator','Add, subtract, multiply, transpose, calculate determinants, and invert small numeric matrices locally.','matrix calculator|matrix inverse|determinant|matrix multiply','math','math','Matrix Calculator',true],
['combinations-permutations-calculator','Combinations & Permutations Calculator','Calculate exact nCr and nPr values with BigInt for non-negative integer inputs.','combinations calculator|permutations calculator|ncr|npr|binomial coefficient','math','math','nCr / nPr',true],
['normal-distribution-calculator','Normal Distribution & Z-Score Calculator','Convert values to z-scores and estimate normal CDF, upper-tail, and interval probabilities.','normal distribution calculator|z score|normal cdf|probability','math','math','Normal Distribution',true],
['linear-regression-calculator','Correlation & Linear Regression Calculator','Calculate Pearson correlation, least-squares slope/intercept, R², predictions, and residual summaries from paired data.','linear regression|correlation calculator|pearson r|r squared','math','math','Regression',true],
['gcd-lcm-prime-factorization','GCD, LCM & Prime Factorization','Calculate exact greatest common divisors, least common multiples, and prime factorizations for integers.','gcd calculator|lcm calculator|prime factors|factorization','math','math','GCD / LCM / Factors',true],
['complex-number-calculator','Complex Number Calculator','Add, subtract, multiply, divide, and inspect magnitude and argument for complex numbers.','complex number calculator|imaginary numbers|a+bi|complex arithmetic','math','math','Complex Numbers'],
['quadratic-solver','Quadratic Equation Solver','Solve ax² + bx + c = 0 with real or complex roots, discriminant, vertex, and axis of symmetry.','quadratic solver|quadratic formula|roots|discriminant|parabola','math','math','Quadratic Solver',true],
['vector-calculator','Vector Calculator','Calculate vector magnitude, dot product, cross product, angle, addition, subtraction, and scalar multiplication.','vector calculator|dot product|cross product|vector angle','math','math','Vector Calculator'],
['svg-optimizer','SVG Optimizer & Minifier','Remove common SVG metadata, comments, redundant whitespace, and safe-to-drop editor noise without rasterizing the artwork.','svg optimizer|svg minifier|compress svg|clean svg','web','design','SVG Optimizer',true],
['dpi-print-size-calculator','DPI & Print Size Calculator','Convert pixel dimensions, DPI/PPI, inches, centimeters, and megapixels for print planning.','dpi calculator|ppi calculator|print size|pixels to inches','web','design','DPI / Print Size',true],
['color-blindness-simulator','Color-Blindness Simulator','Preview approximate protanopia, deuteranopia, tritanopia, and grayscale transforms for selected colors.','color blindness simulator|protanopia|deuteranopia|tritanopia|accessible color','web','design','Color Vision Simulator'],
['robots-txt-builder','robots.txt Builder','Generate a standards-oriented robots.txt with user-agent groups, allow/disallow rules, crawl delay notes, and sitemap references.','robots.txt generator|robots builder|seo crawler rules','web','developer','robots.txt Builder',true],
['sitemap-xml-builder','Sitemap XML Builder','Generate a basic XML sitemap from URLs with optional last-modified dates, change frequencies, and priorities.','sitemap generator|sitemap xml|seo sitemap|urlset','web','developer','Sitemap Builder',true],
['vcard-generator','vCard / VCF Contact Generator','Generate a downloadable vCard 3.0 contact from name, organization, phone, email, website, and address fields.','vcard generator|vcf generator|contact card|address book','web','everyday','vCard Generator',true],
['totp-generator','TOTP / 2FA Code Generator','Generate RFC-style time-based one-time passwords locally from a Base32 secret with selectable digits and period.','totp generator|2fa code|otp|authenticator|base32 secret','web','developer','TOTP Generator',true],
['css-minifier','CSS Minifier','Remove comments and redundant whitespace from CSS while preserving quoted strings and practical syntax.','css minifier|minify css|compress css|css formatter','web','developer','CSS Minifier'],
];
export const PUBLIC_P11_TASKS:PublicP11Task[]=RAW.map(([id,name,description,keys,engine,category,shortName,featured])=>({id,name,shortName:shortName||name,description,keywords:keys.split('|'),engine,category,featured}));
export function getPublicP11Task(id:string|null|undefined){return id?PUBLIC_P11_TASKS.find(t=>t.id===id):undefined}
