import React,{useMemo,useState}from'react';
import{Clipboard,FileSearch,ShieldCheck,Upload}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{canonicalizeJson,compareJson,generateSri,inspectCertificatePem,inspectCsrPem,verifyJwtSignature,type SriAlgorithm}from'../../utilities/p14-security';
import{buildCsp,buildHreflang,buildJsonLd,buildPwaManifest,parseHar,serpPreview,slugify}from'../../utilities/p14-web';
import{getPublicP14Task,PUBLIC_P14_TASKS}from'../../expansion/publicP14Tasks';
function currentId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
const SAMPLE_JSON='{"name":"Tiny Tools","active":true,"nested":{"b":2,"a":1}}';
const SAMPLE_RIGHT='{"name":"Tiny Tools","active":false,"nested":{"a":1,"c":3}}';
const SAMPLE_HAR='{"log":{"version":"1.2","entries":[{"request":{"method":"GET","url":"https://example.com/app.js"},"response":{"status":200,"headersSize":120,"bodySize":800,"content":{"mimeType":"text/javascript"}},"time":42}]}}';
const DeveloperSecurityCompletionTools:React.FC<{initialText?:string}>=({initialText})=>{const task=useMemo(()=>getPublicP14Task(currentId())??PUBLIC_P14_TASKS[0],[]),[input,setInput]=useState(initialText??defaultInput(task.id)),[secondary,setSecondary]=useState(defaultSecondary(task.id)),[third,setThird]=useState(defaultThird(task.id)),[output,setOutput]=useState(''),[error,setError]=useState(''),[compact,setCompact]=useState(false),[asciiOnly,setAsciiOnly]=useState(true),[alg,setAlg]=useState<SriAlgorithm>('SHA-384'),[file,setFile]=useState<File|null>(null),[copied,setCopied]=useState(false),[busy,setBusy]=useState(false);
 const copy=async()=>{if(output&&await copyToClipboard(output)){setCopied(true);setTimeout(()=>setCopied(false),1000)}};
 const run=async()=>{setBusy(true);setError('');try{let value:unknown;switch(task.id){case'json-structural-diff':value=compareJson(input,secondary);break;case'json-canonicalizer':value=canonicalizeJson(input,compact);break;case'jwt-signature-verifier':value=await verifyJwtSignature(input,secondary);break;case'x509-certificate-inspector':value=await inspectCertificatePem(input);break;case'csr-decoder':value=inspectCsrPem(input);break;case'sri-hash-generator':value=await generateSri(file?await file.arrayBuffer():new TextEncoder().encode(input),alg);break;case'csp-builder':{const o:any={};for(const raw of input.split(/\r?\n/)){const line=raw.trim();if(!line)continue;const [name,...rest]=line.split(/\s+/),v=rest.join(' ');const map:Record<string,string>={'default-src':'defaultSrc','script-src':'scriptSrc','style-src':'styleSrc','img-src':'imgSrc','font-src':'fontSrc','connect-src':'connectSrc','frame-src':'frameSrc','object-src':'objectSrc','base-uri':'baseUri','form-action':'formAction','frame-ancestors':'frameAncestors'};if(name==='upgrade-insecure-requests')o.upgradeInsecureRequests=true;else if(map[name])o[map[name]]=v}value=buildCsp(o);break}case'pwa-manifest-generator':value=buildPwaManifest(JSON.parse(input));break;case'json-ld-generator':value=buildJsonLd(secondary||'Thing',JSON.parse(input));break;case'serp-snippet-preview':value=serpPreview(input,secondary,third);break;case'slug-generator':value=slugify(input,secondary||'-',asciiOnly);break;case'hreflang-generator':value=buildHreflang(input.split(/\r?\n/).map(line=>{const i=line.indexOf('=');return{lang:i>=0?line.slice(0,i).trim():'',url:i>=0?line.slice(i+1).trim():''}}),secondary);break;case'har-viewer':value=parseHar(file?await file.text():input);break;default:value=''}setOutput(typeof value==='string'?value:JSON.stringify(value,null,2))}catch(e){setOutput('');setError(e instanceof globalThis.Error?e.message:String(e))}finally{setBusy(false)}};
 return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={related(task.id)}><div className="space-y-5"><div className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-800 dark:border-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-300"><ShieldCheck className="h-4 w-4"/>All supplied JSON, secrets, keys, certificates, policies, manifests, and HAR data stay in this browser.</div><Inputs id={task.id} input={input} setInput={setInput} secondary={secondary} setSecondary={setSecondary} third={third} setThird={setThird} compact={compact} setCompact={setCompact} asciiOnly={asciiOnly} setAsciiOnly={setAsciiOnly} alg={alg} setAlg={setAlg} file={file} setFile={setFile}/><div className="flex flex-wrap gap-2"><button type="button" disabled={busy} onClick={()=>void run()} className="rounded-lg bg-neutral-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50 dark:bg-neutral-100 dark:text-neutral-900">{busy?'Working…':action(task.id)}</button>{output&&<button type="button" onClick={()=>void copy()} className="inline-flex items-center gap-2 rounded-lg border px-4 py-2 text-sm font-semibold"><Clipboard className="h-4 w-4"/>{copied?'Copied':'Copy output'}</button>}</div>{error&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{error}</div>}{output&&<pre className="max-h-[32rem] overflow-auto whitespace-pre-wrap break-words rounded-xl border bg-neutral-50 p-4 text-xs dark:bg-neutral-950">{output}</pre>}<Limit id={task.id}/></div></ToolShell>};
function Inputs(p:{id:string;input:string;setInput:(v:string)=>void;secondary:string;setSecondary:(v:string)=>void;third:string;setThird:(v:string)=>void;compact:boolean;setCompact:(v:boolean)=>void;asciiOnly:boolean;setAsciiOnly:(v:boolean)=>void;alg:SriAlgorithm;setAlg:(v:SriAlgorithm)=>void;file:File|null;setFile:(v:File|null)=>void}){const a=<Area label={inputLabel(p.id)} value={p.input} set={p.setInput}/>;if(p.id==='json-structural-diff')return<div className="grid gap-4 lg:grid-cols-2">{a}<Area label="Right JSON" value={p.secondary} set={p.setSecondary}/></div>;if(p.id==='json-canonicalizer')return<>{a}<Check label="Compact output" checked={p.compact} set={p.setCompact}/></>;if(p.id==='jwt-signature-verifier')return<>{a}<Area label="HMAC secret or RSA PUBLIC KEY / CERTIFICATE PEM" value={p.secondary} set={p.setSecondary}/></>;if(p.id==='sri-hash-generator')return<><label className="block text-xs font-semibold">Algorithm<select value={p.alg} onChange={e=>p.setAlg(e.target.value as SriAlgorithm)} className="ml-2 rounded border bg-transparent px-3 py-2"><option>SHA-256</option><option>SHA-384</option><option>SHA-512</option></select></label>{a}<FilePick file={p.file} set={p.setFile} accept="*/*"/></>;if(p.id==='json-ld-generator')return<><Input label="Schema @type" value={p.secondary} set={p.setSecondary}/>{a}</>;if(p.id==='serp-snippet-preview')return<><Input label="Page title" value={p.input} set={p.setInput}/><Input label="Display URL" value={p.secondary} set={p.setSecondary}/><Area label="Meta description" value={p.third} set={p.setThird}/></>;if(p.id==='slug-generator')return<><Area label="Text" value={p.input} set={p.setInput}/><Input label="Separator" value={p.secondary} set={p.setSecondary}/><Check label="Strip remaining non-ASCII characters" checked={p.asciiOnly} set={p.setAsciiOnly}/></>;if(p.id==='hreflang-generator')return<>{a}<Input label="x-default URL (optional)" value={p.secondary} set={p.setSecondary}/></>;if(p.id==='har-viewer')return<>{a}<FilePick file={p.file} set={p.setFile} accept=".har,application/json"/></>;return a}
function Area({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return<label className="block text-xs font-semibold">{label}<textarea rows={10} value={value} onChange={e=>set(e.target.value)} spellCheck={false} className="mt-1 w-full resize-y rounded-xl border bg-transparent p-3 font-mono text-sm"/></label>}
function Input({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return<label className="block text-xs font-semibold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>}
function Check({label,checked,set}:{label:string;checked:boolean;set:(v:boolean)=>void}){return<label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" checked={checked} onChange={e=>set(e.target.checked)}/>{label}</label>}
function FilePick({file,set,accept}:{file:File|null;set:(v:File|null)=>void;accept:string}){return<label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl border border-dashed p-4 text-xs font-semibold"><Upload className="h-4 w-4"/>{file?file.name:'Use a local file instead'}<input type="file" accept={accept} className="sr-only" onChange={e=>set(e.target.files?.[0]??null)}/></label>}
function inputLabel(id:string){const x:Record<string,string>={'json-structural-diff':'Left JSON','json-canonicalizer':'JSON','jwt-signature-verifier':'JWT','x509-certificate-inspector':'CERTIFICATE PEM','csr-decoder':'CERTIFICATE REQUEST PEM','sri-hash-generator':'Text input (ignored when a file is selected)','csp-builder':'One CSP directive per line','pwa-manifest-generator':'Manifest configuration JSON','json-ld-generator':'Schema properties JSON','hreflang-generator':'One locale=URL pair per line','har-viewer':'HAR JSON (ignored when a file is selected)'};return x[id]??'Input'}
function action(id:string){return['x509-certificate-inspector','csr-decoder','har-viewer'].includes(id)?'Inspect':id==='jwt-signature-verifier'?'Verify':id==='json-structural-diff'?'Compare':'Generate'}
function related(id:string){if(id.startsWith('json-'))return['json-formatter','json-schema-validator','text-diff'];if(id.includes('jwt'))return['jwt-decoder','text-hash-generator','hmac-generator'];if(id.includes('certificate')||id.includes('csr'))return['text-hash-generator','file-checksum-generator','encoding-tools'];if(id==='sri-hash-generator')return['file-checksum-generator','text-hash-generator','html-entity-converter'];if(id==='har-viewer')return['json-formatter','url-parser','http-header-parser'];return['meta-tags-generator','robots-txt-builder','sitemap-xml-builder']}
function defaultInput(id:string){const x:Record<string,string>={'json-structural-diff':SAMPLE_JSON,'json-canonicalizer':'{"z":1,"a":{"y":2,"b":3}}','jwt-signature-verifier':'','x509-certificate-inspector':'','csr-decoder':'','sri-hash-generator':'console.log("Tiny Tools");','csp-builder':"default-src 'self'\nscript-src 'self' https://cdn.example.com\nimg-src 'self' data:\nobject-src 'none'\nbase-uri 'self'\nupgrade-insecure-requests",'pwa-manifest-generator':'{"name":"Tiny Tools","shortName":"Tools","description":"Privacy-first browser utilities","startUrl":"./","scope":"./","display":"standalone","themeColor":"#171717","backgroundColor":"#ffffff","icons":[{"src":"./favicon.svg","sizes":"any","type":"image/svg+xml"}]}','json-ld-generator':'{"name":"Tiny Tools","url":"https://example.com/tools","description":"Privacy-first browser utilities"}','serp-snippet-preview':'Tiny Tools — Privacy-First Browser Utilities','slug-generator':'Tiny Tools: Developer & Security Completion','hreflang-generator':'en=https://example.com/en/tools\nde=https://example.com/de/tools','har-viewer':SAMPLE_HAR};return x[id]??''}
function defaultSecondary(id:string){if(id==='json-structural-diff')return SAMPLE_RIGHT;if(id==='json-ld-generator')return'WebSite';if(id==='serp-snippet-preview')return'https://example.com/tools';if(id==='slug-generator')return'-';if(id==='hreflang-generator')return'https://example.com/tools';return''}
function defaultThird(id:string){return id==='serp-snippet-preview'?'Fast, private browser utilities for files, developer workflows, media, documents, calculations, and everyday tasks.':''}
function Limit({id}:{id:string}){const x:Record<string,string>={'json-structural-diff':'Array order is significant. The tool reports structural paths rather than a line-oriented text diff.','json-canonicalizer':'Object keys are recursively sorted; array order is preserved. This is deterministic stable JSON output, not a claim of RFC 8785 number/string canonicalization.','jwt-signature-verifier':'Supports HS256/384/512 and RS256/384/512. Verification proves only that the supplied key matches the token signature; it does not establish issuer trust, key provenance, claim validity, revocation, or authorization.','x509-certificate-inspector':'Parses common DER-encoded X.509 certificate fields. It does not build or validate a certificate chain, check revocation, or establish trust.','csr-decoder':'Decodes common PKCS#10 request fields but does not issue certificates or validate CA policy.','sri-hash-generator':'SRI protects fetched subresources only when the browser receives the exact hashed bytes and the integrity attribute is used correctly.','csp-builder':'Generates policy syntax from common directives; a secure policy still requires application-specific testing and deployment headers.','pwa-manifest-generator':'Generates manifest JSON only. Installability also depends on HTTPS, service-worker/browser requirements, icons, and platform behavior.','json-ld-generator':'Generates JSON-LD markup but does not guarantee search-engine eligibility or rich-result display.','serp-snippet-preview':'Search engines may rewrite titles and descriptions. Length guidance is approximate, not a pixel-perfect Google renderer.','slug-generator':'Slug output is a formatting helper; redirects and canonical URL strategy remain application concerns.','hreflang-generator':'Generated tags assume each supplied URL is correct, crawlable, and reciprocally configured where required.','har-viewer':'HAR files can contain sensitive URLs, headers, cookies, and request data. This viewer stays local and summarizes up to the first 500 entries.'};return x[id]?<p className="text-xs text-neutral-500">{x[id]}</p>:null}
export default DeveloperSecurityCompletionTools;
