import React,{useMemo,useState}from'react';
import{Calculator,Clipboard}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{getPublicP15Task,PUBLIC_P15_TASKS}from'../../expansion/publicP15Tasks';
import{binomialPmf,binomialRange,chiSquareGoodness,chiSquareIndependence,csvNumericSeries,descriptiveStats,findPolynomialRealRoots,histogram,meanConfidenceInterval,oneSampleTTest,parseCoefficients,parseCsv,parseNumberList,parseNumericMatrix,poissonPmf,poissonRange,proportionConfidenceInterval,sampleFunction,samplePolynomial,sampleSizeForMean,sampleSizeForProportion,scatterStats,solveLinearSystem,welchTTest,type PlotPoint}from'../../utilities/p15-math-data';
function currentId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
function safe<T>(fn:()=>T){try{return{value:fn(),error:''}}catch(e){return{value:null,error:e instanceof Error?e.message:'Unable to calculate.'}}}
function fmt(value:unknown){return typeof value==='string'?value:JSON.stringify(value,(_,v)=>typeof v==='number'&&Number.isFinite(v)?Number(v.toPrecision(10)):v,2)}
const MathDataVisualizationTools:React.FC=()=>{const task=useMemo(()=>getPublicP15Task(currentId())??PUBLIC_P15_TASKS[0],[]);let body:React.ReactNode;switch(task.id){case'function-graph-plotter':body=<FunctionPlotter/>;break;case'polynomial-graph-explorer':body=<PolynomialExplorer/>;break;case'linear-system-solver':body=<LinearSystem/>;break;case'binomial-distribution-calculator':body=<Binomial/>;break;case'poisson-distribution-calculator':body=<Poisson/>;break;case'confidence-interval-calculator':body=<ConfidenceInterval/>;break;case'sample-size-calculator':body=<SampleSize/>;break;case't-test-calculator':body=<TTest/>;break;case'chi-square-test-calculator':body=<ChiSquare/>;break;case'descriptive-statistics-box-plot':body=<Descriptive/>;break;case'histogram-generator':body=<Histogram/>;break;case'scatter-plot-generator':body=<Scatter/>;break;case'csv-data-plotter':body=<CsvPlot/>;break;default:body=null}return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={['statistics-calculator','linear-regression-calculator','normal-distribution-calculator']}><div className="space-y-5"><div className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-300"><Calculator className="h-4 w-4 shrink-0"/>All calculations and SVG charts in P15 run locally in your browser. Statistical results are descriptive/inferential calculations, not scientific or professional conclusions.</div>{body}<p className="text-xs text-neutral-500">JavaScript floating-point arithmetic and standard numerical approximations are used. Check assumptions and use specialist statistical software for high-stakes or publication-grade analysis.</p></div></ToolShell>};
function FunctionPlotter(){const[e,setE]=useState('sin(x)'),[xmin,setXmin]=useState(-10),[xmax,setXmax]=useState(10),[ymin,setYmin]=useState(-5),[ymax,setYmax]=useState(5);const r=useMemo(()=>safe(()=>sampleFunction(e,xmin,xmax,501)),[e,xmin,xmax]);return<><Input label="f(x)" value={e} set={setE}/><div className="grid gap-3 sm:grid-cols-4"><Num label="x min" value={xmin} set={setXmin}/><Num label="x max" value={xmax} set={setXmax}/><Num label="y min" value={ymin} set={setYmin}/><Num label="y max" value={ymax} set={setYmax}/></div>{r.error?<ErrorBox text={r.error}/>:ymin>=ymax?<ErrorBox text="y minimum must be smaller than y maximum."/>:<LinePlot points={r.value!} xMin={xmin} xMax={xmax} yMin={ymin} yMax={ymax}/>}<Hint>Supported syntax: x, pi, e, + − × ÷ ^, parentheses, and sin/cos/tan/asin/acos/atan/sqrt/abs/exp/ln/log/floor/ceil/round. Multiplication must be explicit.</Hint></>}
function PolynomialExplorer(){const[c,setC]=useState('1 0 -4'),[xmin,setXmin]=useState(-5),[xmax,setXmax]=useState(5);const r=useMemo(()=>safe(()=>{const coeffs=parseCoefficients(c),points=samplePolynomial(coeffs,xmin,xmax,501),roots=findPolynomialRealRoots(coeffs,xmin,xmax);return{degree:coeffs.length-1,coefficients:coeffs,roots,points}}),[c,xmin,xmax]);if(r.error)return<><Input label="Coefficients, highest degree first" value={c} set={setC}/><RangeInputs xmin={xmin} xmax={xmax} setXmin={setXmin} setXmax={setXmax}/><ErrorBox text={r.error}/></>;const y=extentY(r.value!.points);return<><Input label="Coefficients, highest degree first" value={c} set={setC}/><RangeInputs xmin={xmin} xmax={xmax} setXmin={setXmin} setXmax={setXmax}/><LinePlot points={r.value!.points} xMin={xmin} xMax={xmax} yMin={y[0]} yMax={y[1]}/><Output value={{degree:r.value!.degree,realRootsInRange:r.value!.roots}}/><Hint>Root detection scans and bisects the selected range. Even-multiplicity roots that never cross zero can be missed unless sampled near zero.</Hint></>}
function LinearSystem(){const[input,setInput]=useState('2 1 5\n1 -1 1');const r=useMemo(()=>safe(()=>solveLinearSystem(parseNumericMatrix(input))),[input]);return<><Area label="Augmented matrix [A | b]" value={input} set={setInput}/>{r.error?<ErrorBox text={r.error}/>:<Output value={r.value}/>}<Hint>Each row is one equation. The final column is the constant term. Gauss-Jordan elimination returns RREF and classifies the system.</Hint></>}
function Binomial(){const[n,setN]=useState(10),[k,setK]=useState(3),[p,setP]=useState(.5),[lo,setLo]=useState(0),[hi,setHi]=useState(3);const r=useMemo(()=>safe(()=>({pmf:binomialPmf(n,k,p),intervalProbability:binomialRange(n,p,lo,hi)})),[n,k,p,lo,hi]);return<><div className="grid gap-3 sm:grid-cols-5"><Num label="n" value={n} set={setN} step={1}/><Num label="k" value={k} set={setK} step={1}/><Num label="p" value={p} set={setP}/><Num label="range low" value={lo} set={setLo} step={1}/><Num label="range high" value={hi} set={setHi} step={1}/></div><CalcResult result={r}/></>}
function Poisson(){const[lambda,setLambda]=useState(3),[k,setK]=useState(2),[lo,setLo]=useState(0),[hi,setHi]=useState(4);const r=useMemo(()=>safe(()=>({pmf:poissonPmf(lambda,k),intervalProbability:poissonRange(lambda,lo,hi)})),[lambda,k,lo,hi]);return<><div className="grid gap-3 sm:grid-cols-4"><Num label="λ" value={lambda} set={setLambda}/><Num label="k" value={k} set={setK} step={1}/><Num label="range low" value={lo} set={setLo} step={1}/><Num label="range high" value={hi} set={setHi} step={1}/></div><CalcResult result={r}/></>}
function ConfidenceInterval(){const[mode,setMode]=useState('mean'),[values,setValues]=useState('12, 14, 15, 13, 16, 14, 15'),[confidence,setConfidence]=useState(.95),[successes,setSuccesses]=useState(60),[total,setTotal]=useState(100);const r=useMemo(()=>safe(()=>mode==='mean'?meanConfidenceInterval(parseNumberList(values),confidence):proportionConfidenceInterval(successes,total,confidence)),[mode,values,confidence,successes,total]);return<><Select label="Interval type" value={mode} set={setMode} options={[['mean','Mean — t interval'],['proportion','Proportion — Wilson interval']]}/><Num label="Confidence (0–1)" value={confidence} set={setConfidence}/>{mode==='mean'?<Area label="Sample values" value={values} set={setValues}/>:<div className="grid gap-3 sm:grid-cols-2"><Num label="Successes" value={successes} set={setSuccesses} step={1}/><Num label="Total" value={total} set={setTotal} step={1}/></div>}<CalcResult result={r}/></>}
function SampleSize(){const[mode,setMode]=useState('proportion'),[confidence,setConfidence]=useState(.95),[margin,setMargin]=useState(.05),[p,setP]=useState(.5),[sd,setSd]=useState(10),[population,setPopulation]=useState(0);const r=useMemo(()=>safe(()=>mode==='proportion'?sampleSizeForProportion(confidence,margin,p,population>0?population:undefined):sampleSizeForMean(confidence,margin,sd)),[mode,confidence,margin,p,sd,population]);return<><Select label="Estimate for" value={mode} set={setMode} options={[['proportion','Proportion'],['mean','Mean']]}/><div className="grid gap-3 sm:grid-cols-3"><Num label="Confidence (0–1)" value={confidence} set={setConfidence}/><Num label="Margin of error" value={margin} set={setMargin}/>{mode==='proportion'?<Num label="Expected proportion p" value={p} set={setP}/>:<Num label="Estimated standard deviation" value={sd} set={setSd}/>}</div>{mode==='proportion'&&<Num label="Finite population (0 = ignore)" value={population} set={setPopulation} step={1}/>}<CalcResult result={r}/><Hint>This is precision-based sample-size estimation, not a statistical-power calculation for a specific hypothesis test.</Hint></>}
function TTest(){const[mode,setMode]=useState('one'),[a,setA]=useState('4,5,6,7,8'),[b,setB]=useState('3,4,4,5,6'),[mu,setMu]=useState(5),r=useMemo(()=>safe(()=>mode==='one'?oneSampleTTest(parseNumberList(a),mu):welchTTest(parseNumberList(a),parseNumberList(b))),[mode,a,b,mu]);return<><Select label="Test" value={mode} set={setMode} options={[['one','One-sample t-test'],['welch','Welch two-sample t-test']]}/><Area label={mode==='one'?'Sample values':'Group A'} value={a} set={setA}/>{mode==='one'?<Num label="Null mean μ₀" value={mu} set={setMu}/>:<Area label="Group B" value={b} set={setB}/>}<CalcResult result={r}/><Hint>Reported p-values are two-sided. The calculation does not test normality, independence, sampling design, or practical significance.</Hint></>}
function ChiSquare(){const[mode,setMode]=useState('goodness'),[obs,setObs]=useState('10, 20, 30'),[exp,setExp]=useState('20, 20, 20'),[matrix,setMatrix]=useState('20 10\n10 20');const r=useMemo(()=>safe(()=>mode==='goodness'?chiSquareGoodness(parseNumberList(obs),parseNumberList(exp)):chiSquareIndependence(parseNumericMatrix(matrix))),[mode,obs,exp,matrix]);return<><Select label="Test" value={mode} set={setMode} options={[['goodness','Goodness of fit'],['independence','Independence']]}/>{mode==='goodness'?<div className="grid gap-4 lg:grid-cols-2"><Area label="Observed frequencies" value={obs} set={setObs}/><Area label="Expected frequencies" value={exp} set={setExp}/></div>:<Area label="Contingency table" value={matrix} set={setMatrix}/>}<CalcResult result={r}/><Hint>Expected cell counts should generally be sufficiently large for the chi-square approximation to be appropriate.</Hint></>}
function Descriptive(){const[input,setInput]=useState('2, 3, 4, 5, 5, 6, 7, 9, 12');const r=useMemo(()=>safe(()=>{const values=parseNumberList(input);return{stats:descriptiveStats(values),values}}),[input]);return<><Area label="Numeric values" value={input} set={setInput}/>{r.error?<ErrorBox text={r.error}/>:<><BoxPlot stats={r.value!.stats}/><Output value={r.value!.stats}/></>}</>}
function Histogram(){const[input,setInput]=useState('1,2,2,3,3,3,4,4,5,6,7,8,8,9'),[bins,setBins]=useState(6);const r=useMemo(()=>safe(()=>histogram(parseNumberList(input),bins)),[input,bins]);return<><Area label="Numeric values" value={input} set={setInput}/><Num label="Bins" value={bins} set={setBins} step={1}/>{r.error?<ErrorBox text={r.error}/>:<><HistogramPlot bins={r.value!.bins}/><Output value={r.value}/></>}</>}
function Scatter(){const[xs,setXs]=useState('1,2,3,4,5,6'),[ys,setYs]=useState('2,4,5,7,8,11');const r=useMemo(()=>safe(()=>scatterStats(parseNumberList(xs),parseNumberList(ys))),[xs,ys]);return<><div className="grid gap-4 lg:grid-cols-2"><Area label="X values" value={xs} set={setXs}/><Area label="Y values" value={ys} set={setYs}/></div>{r.error?<ErrorBox text={r.error}/>:<><ScatterPlot points={r.value!.points} regression={{slope:r.value!.slope,intercept:r.value!.intercept}}/><Output value={{n:r.value!.n,r:r.value!.r,r2:r.value!.r2,slope:r.value!.slope,intercept:r.value!.intercept}}/></>}</>}
function CsvPlot(){const[csv,setCsv]=useState('month,revenue\n1,12\n2,18\n3,15\n4,24\n5,30'),[xcol,setXcol]=useState('month'),[ycol,setYcol]=useState('revenue'),[mode,setMode]=useState('line');const headers=useMemo(()=>safe(()=>parseCsv(csv)[0]?.map(x=>x.trim())??[]),[csv]),r=useMemo(()=>safe(()=>csvNumericSeries(csv,xcol,ycol)),[csv,xcol,ycol]);return<><Area label="CSV data" value={csv} set={setCsv}/><div className="grid gap-3 sm:grid-cols-3"><Select label="X column" value={xcol} set={setXcol} options={(headers.value??[]).map(h=>[h,h])}/><Select label="Y column" value={ycol} set={setYcol} options={(headers.value??[]).map(h=>[h,h])}/><Select label="Chart" value={mode} set={setMode} options={[['line','Line'],['scatter','Scatter']]}/></div>{headers.error?<ErrorBox text={headers.error}/>:r.error?<ErrorBox text={r.error}/>:mode==='line'?<AutoLinePlot points={r.value!.points}/>:<ScatterPlot points={r.value!.points.map(p=>({x:p.x,y:p.y!}))}/>}<Hint>CSV parsing supports quoted fields and escaped double quotes. Rows where either selected value is non-numeric are skipped.</Hint></>}
function CalcResult<T>({result}:{result:{value:T|null;error:string}}){return result.error?<ErrorBox text={result.error}/>:result.value!=null?<Output value={result.value}/>:null}
function Output({value}:{value:unknown}){const text=fmt(value),[copied,setCopied]=useState(false);const copy=async()=>{if(await copyToClipboard(text)){setCopied(true);setTimeout(()=>setCopied(false),900)}};return<section className="rounded-xl border bg-neutral-50 p-3 dark:bg-neutral-950"><div className="mb-2 flex justify-end"><button onClick={()=>void copy()} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Clipboard className="h-3.5 w-3.5"/>{copied?'Copied':'Copy'}</button></div><pre className="overflow-auto whitespace-pre-wrap text-xs">{text}</pre></section>}
function ErrorBox({text}:{text:string}){return<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{text}</div>}
function Hint({children}:{children:React.ReactNode}){return<p className="text-xs text-neutral-500">{children}</p>}
function Area({label,value,set}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>}){return<label className="block text-xs font-semibold">{label}<textarea rows={5} value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded-xl border bg-transparent p-3 font-mono"/></label>}
function Input({label,value,set}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>}){return<label className="block text-xs font-semibold">{label}<input value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2 font-mono"/></label>}
function Num({label,value,set,step='any'}:{label:string;value:number;set:React.Dispatch<React.SetStateAction<number>>;step?:number|'any'}){return<label className="block text-xs font-semibold">{label}<input type="number" step={step} value={value} onChange={e=>set(Number(e.target.value))} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>}
function Select({label,value,set,options}:{label:string;value:string;set:React.Dispatch<React.SetStateAction<string>>;options:string[][]}){return<label className="block text-xs font-semibold">{label}<select value={value} onChange={e=>set(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2">{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function RangeInputs({xmin,xmax,setXmin,setXmax}:{xmin:number;xmax:number;setXmin:React.Dispatch<React.SetStateAction<number>>;setXmax:React.Dispatch<React.SetStateAction<number>>}){return<div className="grid gap-3 sm:grid-cols-2"><Num label="x min" value={xmin} set={setXmin}/><Num label="x max" value={xmax} set={setXmax}/></div>}
const W=720,H=360,P=42;
function scale(v:number,a:number,b:number,c:number,d:number){return c+(v-a)*(d-c)/(b-a)}
function extentY(points:PlotPoint[]):[number,number]{const ys=points.flatMap(p=>p.y==null?[]:[p.y]);if(!ys.length)return[-1,1];let lo=Math.min(...ys),hi=Math.max(...ys);if(lo===hi){lo-=1;hi+=1}else{const pad=(hi-lo)*.08;lo-=pad;hi+=pad}return[lo,hi]}
function extentXY(points:{x:number;y:number}[]){let xmin=Math.min(...points.map(p=>p.x)),xmax=Math.max(...points.map(p=>p.x)),ymin=Math.min(...points.map(p=>p.y)),ymax=Math.max(...points.map(p=>p.y));if(xmin===xmax){xmin-=1;xmax+=1}if(ymin===ymax){ymin-=1;ymax+=1}const xp=(xmax-xmin)*.06,yp=(ymax-ymin)*.08;return[xmin-xp,xmax+xp,ymin-yp,ymax+yp]as const}
function Grid({xMin,xMax,yMin,yMax}:{xMin:number;xMax:number;yMin:number;yMax:number}){const x0=xMin<=0&&xMax>=0?scale(0,xMin,xMax,P,W-P):null,y0=yMin<=0&&yMax>=0?scale(0,yMin,yMax,H-P,P):null;return<>{[.25,.5,.75].map(t=><React.Fragment key={t}><line x1={P+(W-2*P)*t} y1={P} x2={P+(W-2*P)*t} y2={H-P} stroke="currentColor" opacity=".08"/><line x1={P} y1={P+(H-2*P)*t} x2={W-P} y2={P+(H-2*P)*t} stroke="currentColor" opacity=".08"/></React.Fragment>)}<rect x={P} y={P} width={W-2*P} height={H-2*P} fill="none" stroke="currentColor" opacity=".18"/>{x0!=null&&<line x1={x0} y1={P} x2={x0} y2={H-P} stroke="currentColor" opacity=".35"/>}{y0!=null&&<line x1={P} y1={y0} x2={W-P} y2={y0} stroke="currentColor" opacity=".35"/>}<text x={P} y={H-12} fontSize="12" fill="currentColor" opacity=".65">{Number(xMin.toPrecision(5))}</text><text x={W-P} y={H-12} textAnchor="end" fontSize="12" fill="currentColor" opacity=".65">{Number(xMax.toPrecision(5))}</text><text x={8} y={P+4} fontSize="12" fill="currentColor" opacity=".65">{Number(yMax.toPrecision(5))}</text><text x={8} y={H-P} fontSize="12" fill="currentColor" opacity=".65">{Number(yMin.toPrecision(5))}</text></>}
function LinePlot({points,xMin,xMax,yMin,yMax}:{points:PlotPoint[];xMin:number;xMax:number;yMin:number;yMax:number}){let started=false,d='';for(const p of points){if(p.y==null){started=false;continue}const x=scale(p.x,xMin,xMax,P,W-P),y=scale(p.y,yMin,yMax,H-P,P);if(!Number.isFinite(x)||!Number.isFinite(y)){started=false;continue}d+=`${started?'L':'M'}${x.toFixed(2)},${y.toFixed(2)} `;started=true}return<Chart><Grid xMin={xMin} xMax={xMax} yMin={yMin} yMax={yMax}/><path d={d} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke"/></Chart>}
function AutoLinePlot({points}:{points:PlotPoint[]}){const finite=points.flatMap(p=>p.y==null?[]:[{x:p.x,y:p.y}]);if(!finite.length)return<ErrorBox text="No numeric points to plot."/>;const[xmin,xmax,ymin,ymax]=extentXY(finite);return<LinePlot points={points} xMin={xmin} xMax={xmax} yMin={ymin} yMax={ymax}/>}
function HistogramPlot({bins}:{bins:{lower:number;upper:number;count:number}[]}){const max=Math.max(1,...bins.map(b=>b.count)),bw=(W-2*P)/bins.length;return<Chart><rect x={P} y={P} width={W-2*P} height={H-2*P} fill="none" stroke="currentColor" opacity=".18"/>{bins.map((b,i)=>{const h=(H-2*P)*b.count/max;return<rect key={i} x={P+i*bw+1} y={H-P-h} width={Math.max(1,bw-2)} height={h} fill="currentColor" opacity=".65"/>})}<text x={P} y={H-12} fontSize="12" fill="currentColor" opacity=".65">{Number(bins[0]?.lower.toPrecision(5))}</text><text x={W-P} y={H-12} textAnchor="end" fontSize="12" fill="currentColor" opacity=".65">{Number(bins.at(-1)?.upper.toPrecision(5))}</text><text x={10} y={P+4} fontSize="12" fill="currentColor" opacity=".65">{max}</text></Chart>}
function ScatterPlot({points,regression}:{points:{x:number;y:number}[];regression?:{slope:number;intercept:number}}){const[xmin,xmax,ymin,ymax]=extentXY(points),line=regression?[{x:xmin,y:regression.intercept+regression.slope*xmin},{x:xmax,y:regression.intercept+regression.slope*xmax}]:[];return<Chart><Grid xMin={xmin} xMax={xmax} yMin={ymin} yMax={ymax}/>{line.length>0&&<line x1={scale(line[0].x,xmin,xmax,P,W-P)} y1={scale(line[0].y,ymin,ymax,H-P,P)} x2={scale(line[1].x,xmin,xmax,P,W-P)} y2={scale(line[1].y,ymin,ymax,H-P,P)} stroke="currentColor" opacity=".45" strokeWidth="2"/>}{points.map((p,i)=><circle key={i} cx={scale(p.x,xmin,xmax,P,W-P)} cy={scale(p.y,ymin,ymax,H-P,P)} r="4" fill="currentColor" opacity=".78"/>)}</Chart>}
function BoxPlot({stats}:{stats:{min:number;q1:number;median:number;q3:number;max:number}}){let min=stats.min,max=stats.max;if(min===max){min-=1;max+=1}const x=(v:number)=>scale(v,min,max,P,W-P),cy=H/2;return<Chart><line x1={x(stats.min)} y1={cy} x2={x(stats.max)} y2={cy} stroke="currentColor" strokeWidth="2"/><line x1={x(stats.min)} y1={cy-35} x2={x(stats.min)} y2={cy+35} stroke="currentColor"/><line x1={x(stats.max)} y1={cy-35} x2={x(stats.max)} y2={cy+35} stroke="currentColor"/><rect x={x(stats.q1)} y={cy-60} width={Math.max(1,x(stats.q3)-x(stats.q1))} height="120" fill="currentColor" opacity=".12" stroke="currentColor"/><line x1={x(stats.median)} y1={cy-60} x2={x(stats.median)} y2={cy+60} stroke="currentColor" strokeWidth="3"/><text x={P} y={H-18} fontSize="12" fill="currentColor" opacity=".65">min {Number(stats.min.toPrecision(5))}</text><text x={W-P} y={H-18} textAnchor="end" fontSize="12" fill="currentColor" opacity=".65">max {Number(stats.max.toPrecision(5))}</text></Chart>}
function Chart({children}:{children:React.ReactNode}){return<div className="overflow-hidden rounded-xl border bg-neutral-50 p-2 dark:bg-neutral-950"><svg viewBox={`0 0 ${W} ${H}`} className="block h-auto w-full" role="img" aria-label="Data visualization">{children}</svg></div>}
export default MathDataVisualizationTools;
