export interface PublicDeviceTask{id:string;name:string;shortName:string;description:string;keywords:string[];featured:boolean}
type Raw=[string,string,string,string,string?,boolean?];
const RAW:Raw[]=[
['microphone-test','Microphone Test','Test microphone permission, live input level, peak level, and audio activity locally in your browser.','microphone test|mic test|test microphone|audio input|mic level|microphone volume','',true],
['webcam-test','Webcam Test','Preview your camera locally and inspect the resolution, frame rate, facing mode, and active video track settings.','webcam test|camera test|test webcam|test camera|video camera|camera resolution','',true],
['speaker-test','Speaker & Headphone Test','Play local test tones through both channels or isolate left and right audio for speaker and headphone checks.','speaker test|headphone test|left right audio test|stereo test|sound test|audio output test','Speaker Test',true],
['keyboard-test','Keyboard Tester','See keydown and keyup events, physical key codes, repeat state, key location, and currently held keys.','keyboard test|key tester|test keys|broken key|keydown|keycode|keyboard checker','Keyboard Test',true],
['mouse-test','Mouse Tester','Check pointer movement, mouse buttons, wheel direction, double-clicks, coordinates, and browser pointer events.','mouse test|mouse button test|scroll wheel test|double click test|pointer test|mouse checker','Mouse Test',true],
['dead-pixel-test','Dead Pixel Test','Fill the display with solid diagnostic colors to inspect for dead, stuck, bright, or discolored pixels.','dead pixel test|stuck pixel test|screen pixel test|monitor pixel test|dead pixels|screen color test','',true],
['display-test','Display Test Patterns','Inspect gradients, grayscale steps, color bars, contrast, checkerboards, and other fullscreen display patterns.','display test|monitor test|screen test|gradient test|grayscale test|contrast test|color bars','Display Test'],
['refresh-rate-test','Refresh Rate Test','Estimate the browser-visible display refresh rate from animation-frame timing and report frame-time stability.','refresh rate test|hz test|monitor hz|screen refresh rate|fps display test|144hz test|240hz test','Refresh Rate',true],
['device-info','Screen & Device Info','Inspect browser-exposed display dimensions, pixel ratio, color depth, orientation, CPU concurrency, and memory hints.','device info|screen info|display resolution|pixel ratio|color depth|hardware concurrency|device memory','Device Info'],
['touchscreen-test','Touchscreen Tester','Visualize simultaneous touch or pointer contacts and verify multi-touch movement, pressure, and contact tracking.','touchscreen test|touch test|multi touch test|touch points|screen touch checker|pointer pressure','Touch Test'],
['gamepad-test','Gamepad & Stick Drift Test','Inspect connected gamepad buttons and axes in real time and measure observed resting analog-stick drift.','gamepad test|controller test|stick drift test|joystick test|controller buttons|gamepad axes','Gamepad Test',true],
['polling-rate-test','Pointer Event Rate Test','Measure browser-delivered pointer-event frequency and timing while moving the mouse; this is not a raw USB polling-rate claim.','mouse polling rate test|polling rate|pointer event rate|mouse hz test|event frequency|mouse response rate','Polling Test'],
['keyboard-ghosting-test','Keyboard Ghosting & NKRO Test','Track simultaneous key combinations and the maximum keys your browser receives while you test rollover and ghosting behavior.','keyboard ghosting test|nkro test|n key rollover|key rollover test|simultaneous keys|keyboard matrix test','Ghosting Test'],
['battery-status','Battery Status','Show charging state, reported level, and time estimates when the browser exposes the Battery Status API.','battery status|battery level|charging status|battery api|battery percentage|charging time'],
['tone-generator','Tone Generator','Generate local sine, square, sawtooth, or triangle tones with adjustable frequency and output level.','tone generator|frequency generator|sine wave generator|audio tone|hz generator|test tone'],
['instrument-tuner','Instrument Tuner','Use your microphone locally to estimate pitch, musical note, tuning cents, and signal confidence.','instrument tuner|guitar tuner|chromatic tuner|pitch detector|tune instrument|frequency tuner','Tuner',true],
];
export const PUBLIC_DEVICE_TASKS:PublicDeviceTask[]=RAW.map(([id,name,description,keys,shortName,featured])=>({id,name,shortName:shortName||name,description,keywords:keys.split('|'),featured:Boolean(featured)}));
export function getPublicDeviceTask(id:string|null|undefined){return id?PUBLIC_DEVICE_TASKS.find(task=>task.id===id):undefined}
export function readTinyToolsDeviceTaskId(hash:string):string|null{const clean=hash.replace(/^#\/?/,'').split('?')[0];if(!clean)return null;if(clean.startsWith('tool/'))return clean.slice('tool/'.length).split('/')[0]||null;return clean.split('/')[0]||null}
