import React,{useMemo,useState}from'react';
import{CalendarDays,Check,Copy}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{dateFromIsoWeek,isoWeeksInYear,weekCalendarInfo,weekDates}from'../../utilities/s-tier-week';
const inputClass='mt-1 w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 dark:border-neutral-700 dark:bg-neutral-950';
function today(){const d=new Date(),local=new Date(d.getTime()-d.getTimezoneOffset()*60000);return local.toISOString().slice(0,10)}
function safe<T>(fn:()=>T){try{return{value:fn(),error:''}}catch(error){return{value:null,error:error instanceof Error?error.message:String(error)}}}
export default function WeekCalendarIntelligence(){
 const[date,setDate]=useState(today()),[isoYear,setIsoYear]=useState(new Date().getFullYear()),[isoWeek,setIsoWeek]=useState(1),[isoWeekday,setIsoWeekday]=useState(1),[copied,setCopied]=useState(false);
 const info=useMemo(()=>safe(()=>weekCalendarInfo(date)),[date]);const reverse=useMemo(()=>safe(()=>dateFromIsoWeek(isoYear,isoWeek,isoWeekday)),[isoYear,isoWeek,isoWeekday]);const days=info.value?weekDates(info.value.isoYear,info.value.isoWeek):[];
 const copy=async()=>{if(!info.value)return;const text=`${info.value.dateKey}: ${info.value.weekdayName}, ISO ${info.value.isoWeekCode}, day ${info.value.dayOfYear}/${info.value.daysInYear}, Q${info.value.quarter}, week ${info.value.weekStart}–${info.value.weekEnd}`;if(await copyToClipboard(text)){setCopied(true);setTimeout(()=>setCopied(false),1200)}};
 return<ToolShell toolId="week-number-weekday" title="Week Number & Weekday" description="Inspect ISO week/year/weekday, week boundaries, day-of-year progress, quarter and leap-year context, or convert an ISO week date back to a calendar date." category="time" relatedToolIds={['date-calculator','time-duration-calculator','countdown-to-date']}><div className="space-y-5">
  <div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs leading-5 text-blue-900 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-200">ISO weeks start Monday. Week 1 is the week containing January 4, so dates near New Year can belong to the previous or next ISO week-year.</div>
  <div className="grid gap-3 sm:grid-cols-[1fr_auto] sm:items-end"><label className="text-xs font-semibold">Calendar date<input aria-label="Calendar date" type="date" value={date} onChange={e=>setDate(e.target.value)} className={inputClass}/></label><button type="button" disabled={!info.value} onClick={()=>void copy()} className="inline-flex items-center justify-center gap-2 rounded-lg border border-neutral-300 px-3 py-2 text-sm font-semibold disabled:opacity-40 dark:border-neutral-700">{copied?<Check className="h-4 w-4"/>:<Copy className="h-4 w-4"/>}{copied?'Copied':'Copy summary'}</button></div>
  {info.error&&<ErrorBox text={info.error}/>} {info.value&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="ISO week" value={`W${String(info.value.isoWeek).padStart(2,'0')} / ${info.value.isoYear}`} icon={<CalendarDays className="h-4 w-4"/>}/><Metric label="Weekday" value={`${info.value.weekdayName} · ${info.value.isoWeekday}/7`}/><Metric label="Day of year" value={`${info.value.dayOfYear} / ${info.value.daysInYear}`}/><Metric label="Quarter" value={`Q${info.value.quarter}`} /></div><div className="grid gap-3 sm:grid-cols-3"><Metric label="ISO code" value={info.value.isoWeekCode}/><Metric label="Week range" value={`${info.value.weekStart} → ${info.value.weekEnd}`}/><Metric label="Year progress" value={`${info.value.daysRemaining} days remaining`} /></div><section className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><h2 className="text-sm font-bold">This ISO week</h2><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-7">{days.map((key,index)=>{const current=key===date;const d=new Date(`${key}T00:00:00Z`);return<div key={key} className={`rounded-lg border p-3 text-center ${current?'border-blue-400 bg-blue-50 dark:bg-blue-950/20':'border-neutral-200 dark:border-neutral-800'}`}><div className="text-[10px] uppercase text-neutral-500">{new Intl.DateTimeFormat(undefined,{weekday:'short',timeZone:'UTC'}).format(d)}</div><div className="mt-1 text-lg font-bold">{d.getUTCDate()}</div><div className="text-[10px] text-neutral-500">{key}</div><div className="mt-1 text-[10px]">ISO day {index+1}</div></div>})}</div><p className="mt-3 text-xs text-neutral-500">Calendar year {new Date(`${date}T00:00:00Z`).getUTCFullYear()} has {info.value.daysInYear} days and ISO year {info.value.isoYear} has {isoWeeksInYear(info.value.isoYear)} weeks. {info.value.leapYear?'It is a leap year.':'It is not a leap year.'}</p></section></>}
  <section className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><h2 className="text-sm font-bold">ISO week date → calendar date</h2><div className="mt-3 grid gap-3 sm:grid-cols-3"><label className="text-xs font-semibold">ISO year<input aria-label="ISO year" type="number" min="1" max="9999" value={isoYear} onChange={e=>setIsoYear(Number(e.target.value))} className={inputClass}/></label><label className="text-xs font-semibold">ISO week<input aria-label="ISO week" type="number" min="1" max="53" value={isoWeek} onChange={e=>setIsoWeek(Number(e.target.value))} className={inputClass}/></label><label className="text-xs font-semibold">ISO weekday<select aria-label="ISO weekday" value={isoWeekday} onChange={e=>setIsoWeekday(Number(e.target.value))} className={inputClass}>{['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'].map((name,index)=><option key={name} value={index+1}>{index+1} · {name}</option>)}</select></label></div>{reverse.error?<div className="mt-3"><ErrorBox text={reverse.error}/></div>:<div className="mt-3 rounded-lg bg-neutral-50 p-3 text-sm dark:bg-neutral-950"><span className="text-neutral-500">Calendar date:</span> <strong className="ml-2 font-mono">{reverse.value}</strong></div>}</section>
 </div></ToolShell>
}
function Metric({label,value,icon}:{label:string;value:string;icon?:React.ReactNode}){return<div className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><div className="flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wide text-neutral-500">{icon}{label}</div><div className="mt-1 break-words text-lg font-bold">{value}</div></div>}
function ErrorBox({text}:{text:string}){return<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{text}</div>}
