import React,{useEffect,useRef,useState}from'react';
import{Copy,Download,Eraser,Paintbrush,RotateCcw,Scissors,Upload}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyImageToClipboard}from'../../utilities/clipboard';
import{applyCircularMaskBrush,refineAlphaMaskRgba,removeBackgroundLocal,type BackgroundStyle,type MaskBrushMode}from'../../utilities/background-remover';

const loadImage=(src:string)=>new Promise<HTMLImageElement>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(new Error('Image decode failed'));img.src=src;});
export const BackgroundRemoverTool:React.FC=()=>{
 const[file,setFile]=useState<Blob|null>(null);const[sourceUrl,setSourceUrl]=useState<string|null>(null);const[ready,setReady]=useState(false);const[processing,setProcessing]=useState(false);const[status,setStatus]=useState('');const[smoothing,setSmoothing]=useState(2);const[feather,setFeather]=useState(3);const[brushMode,setBrushMode]=useState<MaskBrushMode>('erase');const[brushSize,setBrushSize]=useState(28);const[drawing,setDrawing]=useState(false);const[undo,setUndo]=useState<ImageData[]>([]);const[background,setBackground]=useState<BackgroundStyle>('transparent');const[customColor,setCustomColor]=useState('#3b82f6');
 const canvasRef=useRef<HTMLCanvasElement>(null),baseRef=useRef<ImageData|null>(null),originalRef=useRef<Uint8ClampedArray|null>(null),sourceUrlRef=useRef<string|null>(null);
 useEffect(()=>()=>{if(sourceUrlRef.current)URL.revokeObjectURL(sourceUrlRef.current);},[]);
 const selectFile=(blob:Blob)=>{if(!blob.type.startsWith('image/'))return;if(sourceUrlRef.current)URL.revokeObjectURL(sourceUrlRef.current);const url=URL.createObjectURL(blob);sourceUrlRef.current=url;setSourceUrl(url);setFile(blob);setReady(false);baseRef.current=null;originalRef.current=null;setUndo([]);};
 const applyRefinement=(s=smoothing,f=feather)=>{const canvas=canvasRef.current,base=baseRef.current;if(!canvas||!base)return;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)return;const refined=refineAlphaMaskRgba(base.data,canvas.width,canvas.height,s,f);ctx.putImageData(new ImageData(refined,canvas.width,canvas.height),0,0);};
 useEffect(()=>{if(ready)applyRefinement();},[smoothing,feather,ready]);
 const process=async()=>{if(!file||!sourceUrl)return;setProcessing(true);setStatus('Starting local segmentation…');try{const result=await removeBackgroundLocal(file,(stage,p)=>setStatus(`${stage} ${p}%`)),url=URL.createObjectURL(result);try{const[seg,original]=await Promise.all([loadImage(url),loadImage(sourceUrl)]),canvas=canvasRef.current;if(!canvas)return;canvas.width=seg.naturalWidth;canvas.height=seg.naturalHeight;const ctx=canvas.getContext('2d',{willReadFrequently:true});if(!ctx)return;ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(seg,0,0);baseRef.current=ctx.getImageData(0,0,canvas.width,canvas.height);const o=document.createElement('canvas');o.width=canvas.width;o.height=canvas.height;const ox=o.getContext('2d',{willReadFrequently:true});if(ox){ox.drawImage(original,0,0,canvas.width,canvas.height);originalRef.current=ox.getImageData(0,0,canvas.width,canvas.height).data;}setReady(true);setStatus('Ready for edge refinement');}finally{URL.revokeObjectURL(url);}}catch(error){setStatus(error instanceof Error?error.message:'Background removal failed');}finally{setProcessing(false);}};
 const snapshot=()=>{const c=canvasRef.current,ctx=c?.getContext('2d',{willReadFrequently:true});if(c&&ctx)setUndo(u=>[...u.slice(-9),ctx.getImageData(0,0,c.width,c.height)]);};
 const brushAt=(clientX:number,clientY:number)=>{const c=canvasRef.current,original=originalRef.current;if(!c||!original)return;const ctx=c.getContext('2d',{willReadFrequently:true});if(!ctx)return;const r=c.getBoundingClientRect(),x=(clientX-r.left)*c.width/r.width,y=(clientY-r.top)*c.height/r.height,current=ctx.getImageData(0,0,c.width,c.height),next=applyCircularMaskBrush(current.data,original,c.width,c.height,[{x,y}],brushSize,brushMode);ctx.putImageData(new ImageData(next,c.width,c.height),0,0);};
 const undoRefine=()=>setUndo(u=>{const last=u.at(-1),c=canvasRef.current;if(last&&c)c.getContext('2d')?.putImageData(last,0,0);return u.slice(0,-1);});
 const outputCanvas=()=>{const source=canvasRef.current;if(!source)return null;if(background==='transparent')return source;const c=document.createElement('canvas');c.width=source.width;c.height=source.height;const ctx=c.getContext('2d');if(!ctx)return source;ctx.fillStyle=background==='white'?'#fff':background==='black'?'#000':customColor;ctx.fillRect(0,0,c.width,c.height);ctx.drawImage(source,0,0);return c;};
 const download=()=>{const c=outputCanvas();if(!c)return;c.toBlob(blob=>{if(!blob)return;const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`background-removed-${Date.now()}.png`;a.click();URL.revokeObjectURL(url);},'image/png');};
 const copy=()=>{const c=outputCanvas();c?.toBlob(blob=>{if(blob)void copyImageToClipboard(blob);},'image/png');};
 return <ToolShell toolId="background-remover" title="Image Background Remover" description="Local neural background removal with nondestructive smoothing, feathering, and deterministic restore/erase refinement." category="image" relatedToolIds={['image-annotator','image-collage','image-optimizer']}>
  <div className="space-y-5"><div className="flex flex-wrap gap-2"><label className="px-3 py-2 rounded-lg bg-blue-600 text-white text-xs font-semibold cursor-pointer inline-flex items-center gap-1"><Upload className="w-4 h-4"/>Select image<input hidden type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&selectFile(e.target.files[0])}/></label>{file&&<button type="button" disabled={processing} onClick={process} className="px-3 py-2 rounded-lg bg-emerald-600 text-white text-xs font-semibold inline-flex items-center gap-1"><Scissors className="w-4 h-4"/>{processing?'Processing…':'Remove background'}</button>}<span className="text-xs self-center text-neutral-500">{status}</span></div>
   {sourceUrl&&<div className="grid lg:grid-cols-2 gap-4"><div className="border rounded-xl bg-neutral-950 p-3 flex items-center justify-center min-h-72"><img src={sourceUrl} alt="Original" className="max-h-[440px] max-w-full object-contain"/></div><div className="border rounded-xl bg-[linear-gradient(45deg,#ddd_25%,transparent_25%),linear-gradient(-45deg,#ddd_25%,transparent_25%),linear-gradient(45deg,transparent_75%,#ddd_75%),linear-gradient(-45deg,transparent_75%,#ddd_75%)] bg-[length:20px_20px] p-3 flex items-center justify-center min-h-72"><canvas ref={canvasRef} onPointerDown={e=>{if(!ready)return;snapshot();setDrawing(true);(e.currentTarget).setPointerCapture(e.pointerId);brushAt(e.clientX,e.clientY);}} onPointerMove={e=>drawing&&brushAt(e.clientX,e.clientY)} onPointerUp={()=>setDrawing(false)} className="max-w-full max-h-[440px] touch-none"/></div></div>}
   {ready&&<div className="grid md:grid-cols-4 gap-4 p-4 border rounded-xl bg-neutral-50 dark:bg-neutral-950"><label className="text-xs">Smoothing <strong>{smoothing}</strong><input className="w-full" type="range" min={0} max={9} value={smoothing} onChange={e=>setSmoothing(Number(e.target.value))}/></label><label className="text-xs">Feather <strong>{feather}px</strong><input className="w-full" type="range" min={0} max={10} value={feather} onChange={e=>setFeather(Number(e.target.value))}/></label><div className="text-xs space-y-2"><div className="flex gap-1"><button type="button" onClick={()=>setBrushMode('erase')} className={`px-2 py-1 border rounded ${brushMode==='erase'?'bg-neutral-900 text-white':''}`}><Eraser className="w-3 h-3 inline"/> Erase</button><button type="button" onClick={()=>setBrushMode('restore')} className={`px-2 py-1 border rounded ${brushMode==='restore'?'bg-neutral-900 text-white':''}`}><Paintbrush className="w-3 h-3 inline"/> Restore</button></div><label>Brush {brushSize}px<input className="w-full" type="range" min={5} max={100} value={brushSize} onChange={e=>setBrushSize(Number(e.target.value))}/></label></div><div className="space-y-2"><button type="button" disabled={!undo.length} onClick={undoRefine} className="w-full px-2 py-1.5 border rounded text-xs disabled:opacity-40 inline-flex justify-center items-center gap-1"><RotateCcw className="w-3 h-3"/>Undo refine</button><select value={background} onChange={e=>setBackground(e.target.value as BackgroundStyle)} className="w-full p-1.5 text-xs border rounded bg-white dark:bg-neutral-900"><option value="transparent">Transparent</option><option value="white">White</option><option value="black">Black</option><option value="custom-color">Custom color</option></select>{background==='custom-color'&&<input type="color" value={customColor} onChange={e=>setCustomColor(e.target.value)}/>}</div></div>}
   {ready&&<div className="flex gap-2"><button type="button" onClick={copy} className="px-3 py-2 text-xs border rounded-lg inline-flex items-center gap-1"><Copy className="w-3.5 h-3.5"/>Copy PNG</button><button type="button" onClick={download} className="px-3 py-2 text-xs rounded-lg bg-emerald-600 text-white inline-flex items-center gap-1"><Download className="w-3.5 h-3.5"/>Download PNG</button></div>}
  </div>
 </ToolShell>;
};
export default BackgroundRemoverTool;
