import React,{useMemo,useState}from'react';
import{BookOpen,Clipboard,FileText,Sparkles}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{analyzeNgrams,calculateReadability,compareTextSimilarity,extractTextPatterns,findDuplicatePhrases,generateLorem,htmlToPlainText,inspectUnicode,markdownToPlainText,repeatText,reverseText,visualizeWhitespace,wrapText}from'../../utilities/text-analysis-tools';
import{getPublicTextStudyTask,PUBLIC_TEXT_STUDY_TASKS}from'../../text-study/publicTextStudyTasks';

function currentId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0]}
function inlineMarkdown(text:string,key:string){const parts=text.split(/(\*\*[^*]+\*\*|`[^`]+`|\*[^*]+\*|_[^_]+_|\[[^\]]+\]\([^)]+\))/g);return parts.map((part,i)=>{if(/^\*\*[^*]+\*\*$/.test(part))return<strong key={`${key}-${i}`}>{part.slice(2,-2)}</strong>;if(/^`[^`]+`$/.test(part))return<code key={`${key}-${i}`} className="rounded bg-neutral-100 px-1 dark:bg-neutral-800">{part.slice(1,-1)}</code>;if(/^\*[^*]+\*$/.test(part)||/^_[^_]+_$/.test(part))return<em key={`${key}-${i}`}>{part.slice(1,-1)}</em>;const link=part.match(/^\[([^\]]+)\]\(([^)]+)\)$/);if(link){let href='';try{const u=new URL(link[2],window.location.href);if(['http:','https:','mailto:'].includes(u.protocol))href=u.href}catch{}return href?<a key={`${key}-${i}`} className="text-blue-600 underline" href={href} target="_blank" rel="noreferrer">{link[1]}</a>:<span key={`${key}-${i}`}>{link[1]}</span>}return<React.Fragment key={`${key}-${i}`}>{part}</React.Fragment>})}
function MarkdownPreview({text}:{text:string}){const lines=text.split(/\n/),nodes:React.ReactNode[]=[];let code:string[]|null=null;for(let i=0;i<lines.length;i++){const line=lines[i];if(/^```/.test(line)){if(code){nodes.push(<pre key={`code-${i}`} className="overflow-auto rounded-lg bg-neutral-950 p-3 text-xs text-neutral-100"><code>{code.join('\n')}</code></pre>);code=null}else code=[];continue}if(code){code.push(line);continue}const h=line.match(/^(#{1,6})\s+(.*)$/);if(h){const level=h[1].length,cls=level<=2?'text-xl font-bold':'text-base font-semibold';nodes.push(<div key={i} role="heading" aria-level={level} className={cls}>{inlineMarkdown(h[2],`h${i}`)}</div>);continue}if(/^>\s?/.test(line)){nodes.push(<blockquote key={i} className="border-l-4 border-neutral-300 pl-3 italic text-neutral-600 dark:border-neutral-700 dark:text-neutral-300">{inlineMarkdown(line.replace(/^>\s?/,''),`q${i}`)}</blockquote>);continue}const ul=line.match(/^\s*[-+*]\s+(.*)$/);if(ul){nodes.push(<div key={i} className="flex gap-2"><span aria-hidden="true">•</span><span>{inlineMarkdown(ul[1],`u${i}`)}</span></div>);continue}const ol=line.match(/^\s*(\d+)[.)]\s+(.*)$/);if(ol){nodes.push(<div key={i} className="flex gap-2"><span>{ol[1]}.</span><span>{inlineMarkdown(ol[2],`o${i}`)}</span></div>);continue}if(!line.trim()){nodes.push(<div key={i} className="h-2"/>);continue}nodes.push(<p key={i} className="leading-7">{inlineMarkdown(line,`p${i}`)}</p>)}if(code)nodes.push(<pre key="code-end" className="overflow-auto rounded-lg bg-neutral-950 p-3 text-xs text-neutral-100"><code>{code.join('\n')}</code></pre>);return<div className="space-y-2">{nodes}</div>}
const sample=`# Study Notes\n\nPaste text here.\n\n- Markdown **preview** is safe.\n- Analysis stays local.`;
const TextMicroTools:React.FC<{initialText?:string}>=({initialText})=>{const task=useMemo(()=>getPublicTextStudyTask(currentId())??PUBLIC_TEXT_STUDY_TASKS[0],[]),[text,setText]=useState(initialText||sample),[second,setSecond]=useState('Paste the comparison text here.'),[count,setCount]=useState(3),[separator,setSeparator]=useState('\n'),[reverseMode,setReverseMode]=useState<'characters'|'words'|'sentences'>('characters'),[width,setWidth]=useState(72),[ngram,setNgram]=useState(2),[phraseSize,setPhraseSize]=useState(4),[paragraphs,setParagraphs]=useState(2),[sentences,setSentences]=useState(4),[copied,setCopied]=useState(false);
 const readability=useMemo(()=>calculateReadability(text),[text]),ngrams=useMemo(()=>analyzeNgrams(text,ngram),[text,ngram]),patterns=useMemo(()=>extractTextPatterns(text),[text]),duplicates=useMemo(()=>findDuplicatePhrases(text,phraseSize),[text,phraseSize]),similarity=useMemo(()=>compareTextSimilarity(text,second),[text,second]),unicode=useMemo(()=>inspectUnicode(text),[text]);
 const output=useMemo(()=>{try{if(task.id==='text-repeater')return repeatText(text,count,separator.replace(/\\n/g,'\n').replace(/\\t/g,'\t'));if(task.id==='text-reverser')return reverseText(text,reverseMode);if(task.id==='text-wrapper')return wrapText(text,width);if(task.id==='whitespace-visualizer')return visualizeWhitespace(text);if(task.id==='lorem-ipsum-generator')return generateLorem(paragraphs,sentences);if(task.id==='markdown-to-plain-text')return markdownToPlainText(text);if(task.id==='html-to-plain-text')return htmlToPlainText(text);return''}catch(e){return e instanceof Error?e.message:'Unable to transform text.'}},[task.id,text,count,separator,reverseMode,width,paragraphs,sentences]);
 const copy=async(value:string)=>{if(await copyToClipboard(value)){setCopied(true);setTimeout(()=>setCopied(false),1200)}};
 const isSimilarity=task.id==='text-similarity-checker',isLorem=task.id==='lorem-ipsum-generator';
 return<ToolShell toolId={task.id} title={task.name} description={task.description} category={task.category} relatedToolIds={['text-cleaner','word-counter','text-diff']}><div className="space-y-5">
  <div className="flex items-center gap-2 rounded-lg border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs text-emerald-700 dark:border-emerald-900 dark:bg-emerald-950/20 dark:text-emerald-300"><Sparkles className="h-4 w-4"/>Runs entirely in this tab. No text is uploaded.</div>
  {!isLorem&&<div className={`grid gap-4 ${isSimilarity?'lg:grid-cols-2':''}`}><label className="text-xs font-semibold">{isSimilarity?'Text A':'Input'}<textarea value={text} onChange={e=>setText(e.target.value)} rows={isSimilarity?12:10} className="mt-1 w-full resize-y rounded-xl border border-neutral-300 bg-white p-3 font-mono text-sm outline-none focus:border-blue-500 dark:border-neutral-700 dark:bg-neutral-950"/></label>{isSimilarity&&<label className="text-xs font-semibold">Text B<textarea value={second} onChange={e=>setSecond(e.target.value)} rows={12} className="mt-1 w-full resize-y rounded-xl border border-neutral-300 bg-white p-3 font-mono text-sm outline-none focus:border-blue-500 dark:border-neutral-700 dark:bg-neutral-950"/></label>}</div>}
  {task.id==='readability-checker'&&<div className="grid gap-3 sm:grid-cols-4"><Stat label="Words" value={readability.words}/><Stat label="Sentences" value={readability.sentences}/><Stat label="Reading ease" value={readability.readingEase}/><Stat label="Grade level" value={readability.gradeLevel}/><p className="text-xs text-neutral-500 sm:col-span-4">{readability.note}</p></div>}
  {task.id==='ngram-analyzer'&&<><label className="text-xs font-semibold">N-gram size<select value={ngram} onChange={e=>setNgram(Number(e.target.value))} className="ml-2 rounded border bg-transparent px-2 py-1"><option value={1}>1 word</option><option value={2}>2 words</option><option value={3}>3 words</option></select></label><SimpleTable rows={ngrams.map(x=>[x.phrase,String(x.count)])} headers={['Phrase','Count']}/></>}
  {task.id==='text-pattern-extractor'&&<div className="grid gap-3 md:grid-cols-2">{Object.entries(patterns).map(([label,items])=><section key={label} className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800"><h3 className="text-xs font-bold capitalize">{label} · {items.length}</h3><div className="mt-2 max-h-40 overflow-auto font-mono text-xs">{items.length?items.map(x=><div key={x}>{x}</div>):<span className="text-neutral-400">None found</span>}</div></section>)}</div>}
  {task.id==='duplicate-phrase-finder'&&<><label className="text-xs font-semibold">Phrase length {phraseSize} words<input className="ml-3 align-middle" type="range" min="2" max="8" value={phraseSize} onChange={e=>setPhraseSize(Number(e.target.value))}/></label><SimpleTable rows={duplicates.map(x=>[x.phrase,String(x.count)])} headers={['Repeated phrase','Count']} empty="No repeated phrases at this length."/></>}
  {isSimilarity&&<div className="grid gap-3 sm:grid-cols-3"><Stat label="Token-set similarity" value={`${Math.round(similarity.jaccard*100)}%`}/><Stat label="Frequency similarity" value={`${Math.round(similarity.cosine*100)}%`}/><Stat label="Combined" value={`${Math.round(similarity.combined*100)}%`}/></div>}
  {task.id==='unicode-inspector'&&<SimpleTable rows={unicode.map(x=>[x.grapheme===' '?'␠':x.grapheme,x.codePoints.join(' '),String(x.utf16Units),x.category])} headers={['Grapheme','Code points','UTF-16','Category']} empty="Type text to inspect Unicode."/>}
  {task.id==='text-repeater'&&<div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Repeat count<input type="number" min="1" max="1000" value={count} onChange={e=>setCount(Number(e.target.value))} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label><label className="text-xs font-semibold">Separator (`\\n` supported)<input value={separator} onChange={e=>setSeparator(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2 font-mono"/></label></div>}
  {task.id==='text-reverser'&&<label className="text-xs font-semibold">Reverse<select value={reverseMode} onChange={e=>setReverseMode(e.target.value as 'characters'|'words'|'sentences')} className="ml-2 rounded border bg-transparent px-2 py-1"><option value="characters">Characters</option><option value="words">Words</option><option value="sentences">Sentences</option></select></label>}
  {task.id==='text-wrapper'&&<label className="text-xs font-semibold">Line width {width}<input className="ml-3 align-middle" type="range" min="20" max="120" value={width} onChange={e=>setWidth(Number(e.target.value))}/></label>}
  {isLorem&&<div className="grid gap-3 sm:grid-cols-2"><label className="text-xs font-semibold">Paragraphs<input type="number" min="1" max="20" value={paragraphs} onChange={e=>setParagraphs(Number(e.target.value))} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label><label className="text-xs font-semibold">Sentences per paragraph<input type="number" min="1" max="12" value={sentences} onChange={e=>setSentences(Number(e.target.value))} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label></div>}
  {task.id==='markdown-preview'&&<section className="rounded-xl border border-neutral-200 bg-white p-5 dark:border-neutral-800 dark:bg-neutral-950"><div className="mb-3 flex items-center gap-2 text-xs font-bold"><BookOpen className="h-4 w-4"/>Safe preview</div><MarkdownPreview text={text}/></section>}
  {output&&<section><div className="mb-2 flex items-center justify-between"><h3 className="flex items-center gap-2 text-xs font-bold"><FileText className="h-4 w-4"/>Output</h3><button onClick={()=>void copy(output)} className="inline-flex items-center gap-1 rounded border px-2 py-1 text-xs"><Clipboard className="h-3.5 w-3.5"/>{copied?'Copied':'Copy'}</button></div><pre className="max-h-[28rem] overflow-auto whitespace-pre-wrap break-words rounded-xl border border-neutral-200 bg-neutral-50 p-4 text-sm dark:border-neutral-800 dark:bg-neutral-950">{output}</pre></section>}
 </div></ToolShell>}
function Stat({label,value}:{label:string;value:React.ReactNode}){return<div className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800"><div className="text-[11px] uppercase tracking-wide text-neutral-500">{label}</div><div className="mt-1 text-xl font-bold">{value}</div></div>}
function SimpleTable({rows,headers,empty='No results.'}:{rows:string[][];headers:string[];empty?:string}){return<div className="overflow-auto rounded-xl border border-neutral-200 dark:border-neutral-800">{rows.length?<table className="w-full min-w-[34rem] text-left text-xs"><thead className="bg-neutral-50 dark:bg-neutral-900"><tr>{headers.map(h=><th key={h} className="px-3 py-2 font-bold">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-t border-neutral-100 dark:border-neutral-900">{row.map((cell,j)=><td key={j} className="px-3 py-2 font-mono">{cell}</td>)}</tr>)}</tbody></table>:<div className="p-4 text-xs text-neutral-500">{empty}</div>}</div>}
export default TextMicroTools;
