export interface PublicCalculatorTask {
  id: string;
  name: string;
  shortName: string;
  description: string;
  keywords: string[];
  group: 'math-school' | 'money' | 'household' | 'fitness';
  featured: boolean;
}

export const PUBLIC_CALCULATOR_TASKS: PublicCalculatorTask[] = [
  { id: 'basic-calculator', name: 'Basic Calculator', shortName: 'Calculator', description: 'Do everyday arithmetic with a safe expression parser for addition, subtraction, multiplication, division, powers, and parentheses.', keywords: ['calculator', 'basic calculator', 'arithmetic', 'add', 'subtract', 'multiply', 'divide'], group: 'math-school', featured: true },
  { id: 'scientific-calculator', name: 'Scientific Calculator', shortName: 'Scientific Calculator', description: 'Evaluate scientific expressions with powers, roots, logarithms, trigonometry, constants, and parentheses without using eval.', keywords: ['scientific calculator', 'sin', 'cos', 'tan', 'sqrt', 'log', 'ln', 'pi', 'math'], group: 'math-school', featured: true },
  { id: 'fraction-calculator', name: 'Fraction Calculator', shortName: 'Fractions', description: 'Add, subtract, multiply, or divide two fractions and reduce the result automatically.', keywords: ['fraction calculator', 'fractions', 'add fractions', 'subtract fractions', 'reduce fraction'], group: 'math-school', featured: true },
  { id: 'average-calculator', name: 'Average Calculator', shortName: 'Average', description: 'Calculate the arithmetic mean of a list of numbers.', keywords: ['average calculator', 'mean', 'average numbers'], group: 'math-school', featured: true },
  { id: 'ratio-calculator', name: 'Ratio & Proportion Calculator', shortName: 'Ratio', description: 'Simplify ratios and solve direct proportions.', keywords: ['ratio calculator', 'proportion calculator', 'simplify ratio', 'rule of three'], group: 'math-school', featured: true },
  { id: 'grade-calculator', name: 'Grade Calculator', shortName: 'Grade', description: 'Convert earned and possible points into a percentage grade.', keywords: ['grade calculator', 'score percentage', 'school grade', 'points grade'], group: 'math-school', featured: true },
  { id: 'final-grade-calculator', name: 'Final Grade Calculator', shortName: 'Final Grade', description: 'Calculate the score needed on a final exam to reach a target course grade.', keywords: ['final grade calculator', 'exam grade needed', 'target grade', 'final exam'], group: 'math-school', featured: true },
  { id: 'gpa-calculator', name: 'GPA Calculator', shortName: 'GPA', description: 'Calculate a credit-weighted GPA from grade-point and credit lists.', keywords: ['gpa calculator', 'grade point average', 'college gpa', 'credits'], group: 'math-school', featured: false },
  { id: 'weighted-average-calculator', name: 'Weighted Average Calculator', shortName: 'Weighted Average', description: 'Calculate an average when values contribute with different weights.', keywords: ['weighted average', 'weighted mean', 'weights calculator'], group: 'math-school', featured: false },
  { id: 'statistics-calculator', name: 'Statistics Calculator', shortName: 'Statistics', description: 'Calculate count, sum, mean, median, minimum, maximum, range, population variance, and standard deviation.', keywords: ['statistics calculator', 'mean median', 'standard deviation', 'variance', 'dataset'], group: 'math-school', featured: true },
  { id: 'triangle-calculator', name: 'Triangle Calculator', shortName: 'Triangle', description: 'Calculate perimeter, area, and angles from three valid side lengths.', keywords: ['triangle calculator', 'heron formula', 'triangle area', 'triangle angles'], group: 'math-school', featured: false },
  { id: 'circle-calculator', name: 'Circle Calculator', shortName: 'Circle', description: 'Calculate diameter, circumference, and area from a radius.', keywords: ['circle calculator', 'circumference', 'circle area', 'diameter', 'radius'], group: 'math-school', featured: false },
  { id: 'probability-calculator', name: 'Probability Calculator', shortName: 'Probability', description: 'Combine two independent event probabilities for AND, OR, or at-least-one outcomes.', keywords: ['probability calculator', 'and probability', 'or probability', 'independent events'], group: 'math-school', featured: false },

  { id: 'tip-calculator', name: 'Tip Calculator', shortName: 'Tip', description: 'Calculate a tip, total bill, and optional per-person split.', keywords: ['tip calculator', 'restaurant tip', 'gratuity', 'split bill'], group: 'money', featured: true },
  { id: 'bill-splitter', name: 'Bill Splitter', shortName: 'Bill Splitter', description: 'Split a bill between people with an optional tip.', keywords: ['bill splitter', 'split check', 'split restaurant bill', 'per person'], group: 'money', featured: true },
  { id: 'currency-converter', name: 'Currency Converter', shortName: 'Currency', description: 'Convert between major currencies using a current public reference-rate API and show the rate source timestamp.', keywords: ['currency converter', 'exchange rate', 'eur usd', 'money converter', 'fx'], group: 'money', featured: true },
  { id: 'loan-calculator', name: 'Loan Calculator', shortName: 'Loan', description: 'Calculate monthly payment, total repayment, and total interest for a fixed-rate amortizing loan.', keywords: ['loan calculator', 'monthly payment', 'interest', 'personal loan'], group: 'money', featured: true },
  { id: 'mortgage-calculator', name: 'Mortgage Calculator', shortName: 'Mortgage', description: 'Estimate monthly mortgage costs including principal, interest, property tax, insurance, and HOA.', keywords: ['mortgage calculator', 'home loan', 'monthly mortgage', 'house payment'], group: 'money', featured: true },
  { id: 'amortization-calculator', name: 'Amortization Calculator', shortName: 'Amortization', description: 'Inspect fixed-loan payment, first-month principal and interest, and total interest over the term.', keywords: ['amortization calculator', 'loan schedule', 'principal interest', 'loan payoff'], group: 'money', featured: false },
  { id: 'compound-interest-calculator', name: 'Compound Interest Calculator', shortName: 'Compound Interest', description: 'Project savings growth from a starting balance, annual return, time, and monthly contributions.', keywords: ['compound interest calculator', 'investment growth', 'savings growth', 'monthly contribution'], group: 'money', featured: true },
  { id: 'savings-goal-calculator', name: 'Savings Goal Calculator', shortName: 'Savings Goal', description: 'Estimate the monthly contribution needed to reach a savings goal by a target date.', keywords: ['savings goal calculator', 'monthly savings needed', 'saving target'], group: 'money', featured: true },
  { id: 'simple-interest-calculator', name: 'Simple Interest Calculator', shortName: 'Simple Interest', description: 'Calculate simple interest and final balance from principal, annual rate, and time.', keywords: ['simple interest calculator', 'interest formula', 'principal rate time'], group: 'money', featured: false },
  { id: 'roi-calculator', name: 'ROI Calculator', shortName: 'ROI', description: 'Calculate absolute profit and return on investment percentage.', keywords: ['roi calculator', 'return on investment', 'profit percentage', 'investment return'], group: 'money', featured: false },
  { id: 'retirement-calculator', name: 'Retirement Savings Calculator', shortName: 'Retirement', description: 'Project a retirement balance from current savings, monthly contributions, annual return, and years.', keywords: ['retirement calculator', 'retirement savings', 'future value', 'pension savings'], group: 'money', featured: false },
  { id: 'credit-card-payoff-calculator', name: 'Credit Card Payoff Calculator', shortName: 'Card Payoff', description: 'Estimate payoff time and interest for a credit-card balance with a fixed monthly payment.', keywords: ['credit card payoff', 'debt payoff calculator', 'credit card interest', 'months to pay'], group: 'money', featured: true },
  { id: 'salary-hourly-calculator', name: 'Salary ↔ Hourly Calculator', shortName: 'Salary ↔ Hourly', description: 'Convert an annual salary into hourly, monthly, weekly, and daily equivalents.', keywords: ['salary to hourly', 'hourly to salary', 'wage calculator', 'monthly salary'], group: 'money', featured: true },
  { id: 'car-loan-calculator', name: 'Car Loan Calculator', shortName: 'Car Loan', description: 'Estimate financed amount, monthly payment, and interest from vehicle price, down payment, trade-in, tax, rate, and term.', keywords: ['car loan calculator', 'auto loan', 'car payment', 'vehicle finance'], group: 'money', featured: true },
  { id: 'rent-vs-buy-calculator', name: 'Rent vs Buy Calculator', shortName: 'Rent vs Buy', description: 'Compare approximate multi-year housing costs using rent growth, mortgage, appreciation, taxes, maintenance, and selling costs.', keywords: ['rent vs buy calculator', 'rent or buy', 'home buying comparison', 'housing cost'], group: 'money', featured: false },
  { id: 'inflation-calculator', name: 'Inflation Impact Calculator', shortName: 'Inflation', description: 'Estimate how inflation changes future prices and the purchasing power of today’s money.', keywords: ['inflation calculator', 'purchasing power', 'future price', 'inflation impact'], group: 'money', featured: true },
  { id: 'debt-to-income-calculator', name: 'Debt-to-Income Calculator', shortName: 'Debt-to-Income', description: 'Calculate monthly debt payments as a percentage of gross monthly income.', keywords: ['debt to income calculator', 'dti ratio', 'monthly debt income'], group: 'money', featured: false },

  { id: 'fuel-trip-cost-calculator', name: 'Fuel & Trip Cost Calculator', shortName: 'Trip Cost', description: 'Estimate fuel used and trip cost from distance, consumption, and fuel price.', keywords: ['fuel cost calculator', 'trip cost', 'gas cost', 'petrol cost', 'l per 100km'], group: 'household', featured: true },
  { id: 'fuel-economy-calculator', name: 'Fuel Economy Calculator', shortName: 'Fuel Economy', description: 'Calculate L/100 km, km/L, and US MPG from distance traveled and fuel used.', keywords: ['fuel economy calculator', 'mpg calculator', 'l/100km', 'km per liter'], group: 'household', featured: true },
  { id: 'electricity-cost-calculator', name: 'Electricity Cost Calculator', shortName: 'Electricity Cost', description: 'Estimate electricity consumption and cost from wattage, daily use, electricity price, and number of days.', keywords: ['electricity cost calculator', 'power cost', 'kwh calculator', 'energy bill'], group: 'household', featured: true },
  { id: 'appliance-cost-calculator', name: 'Appliance Running Cost Calculator', shortName: 'Appliance Cost', description: 'Estimate annual appliance electricity cost including active and standby power.', keywords: ['appliance cost calculator', 'running cost', 'standby power', 'annual electricity'], group: 'household', featured: true },
  { id: 'room-area-calculator', name: 'Room Area Calculator', shortName: 'Room Area', description: 'Calculate floor area and perimeter from room length and width.', keywords: ['room area calculator', 'floor area', 'square meters', 'room size'], group: 'household', featured: true },
  { id: 'paint-calculator', name: 'Paint Calculator', shortName: 'Paint', description: 'Estimate paintable wall area and liters needed after doors/windows, coats, coverage, and waste.', keywords: ['paint calculator', 'liters of paint', 'wall area', 'paint coverage'], group: 'household', featured: true },
  { id: 'flooring-calculator', name: 'Flooring Calculator', shortName: 'Flooring', description: 'Estimate flooring area including waste and the number of boxes required.', keywords: ['flooring calculator', 'floor boxes', 'laminate calculator', 'waste allowance'], group: 'household', featured: true },
  { id: 'tile-calculator', name: 'Tile Calculator', shortName: 'Tile', description: 'Estimate the number of tiles needed for an area including a waste allowance.', keywords: ['tile calculator', 'tiles needed', 'wall tiles', 'floor tiles'], group: 'household', featured: true },
  { id: 'box-volume-calculator', name: 'Box Volume Calculator', shortName: 'Box Volume', description: 'Calculate rectangular box volume in cubic meters and liters from centimeter dimensions.', keywords: ['box volume calculator', 'volume calculator', 'liters', 'cubic meters'], group: 'household', featured: false },
  { id: 'concrete-calculator', name: 'Concrete Calculator', shortName: 'Concrete', description: 'Estimate concrete volume for a rectangular slab including waste allowance.', keywords: ['concrete calculator', 'concrete volume', 'slab concrete', 'cubic meters'], group: 'household', featured: true },

  { id: 'bmi-calculator', name: 'BMI Calculator', shortName: 'BMI', description: 'Calculate body mass index from weight and height as a general screening estimate.', keywords: ['bmi calculator', 'body mass index', 'weight height'], group: 'fitness', featured: true },
  { id: 'bmr-calculator', name: 'BMR Calculator', shortName: 'BMR', description: 'Estimate basal metabolic rate using the Mifflin–St Jeor equation.', keywords: ['bmr calculator', 'basal metabolic rate', 'mifflin st jeor', 'calories at rest'], group: 'fitness', featured: true },
  { id: 'tdee-calculator', name: 'TDEE / Calorie Needs Calculator', shortName: 'TDEE', description: 'Estimate daily energy expenditure from BMR inputs and an activity multiplier.', keywords: ['tdee calculator', 'calorie needs', 'daily calories', 'energy expenditure'], group: 'fitness', featured: true },
  { id: 'running-pace-calculator', name: 'Running Pace Calculator', shortName: 'Running Pace', description: 'Calculate pace, speed, and equivalent finish times from distance and elapsed time.', keywords: ['running pace calculator', 'min per km', 'running speed', 'race pace'], group: 'fitness', featured: true },
  { id: 'body-fat-calculator', name: 'Body Fat Estimate Calculator', shortName: 'Body Fat', description: 'Estimate body-fat percentage using the U.S. Navy circumference method.', keywords: ['body fat calculator', 'navy method', 'waist neck height', 'body fat estimate'], group: 'fitness', featured: false },
  { id: 'one-rep-max-calculator', name: 'One-Rep Max Calculator', shortName: '1RM', description: 'Estimate one-repetition maximum from a submaximal weight and repetition count using common strength formulas.', keywords: ['one rep max calculator', '1rm calculator', 'epley', 'brzycki', 'strength'], group: 'fitness', featured: true },
];

export function getPublicCalculatorTask(id: string | null | undefined): PublicCalculatorTask | undefined {
  return id ? PUBLIC_CALCULATOR_TASKS.find((task) => task.id === id) : undefined;
}
