import React from'react';
import{Download}from'lucide-react';
import type{ProMetric}from'../../strict-b-to-s/calculatorSpecs';
export const panel='rounded-2xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-950';
export const field='mt-1 w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm text-neutral-900 outline-none focus:ring-2 focus:ring-blue-500/30 dark:border-neutral-700 dark:bg-neutral-950 dark:text-neutral-100';
export function Metrics({items}:{items:ProMetric[]}){return <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{items.map((m,i)=><div key={`${m.label}-${i}`} className="rounded-xl border border-neutral-200 bg-neutral-50 p-3 dark:border-neutral-800 dark:bg-neutral-900/40"><div className="text-[10px] font-black uppercase tracking-wide text-neutral-500">{m.label}</div><div className="mt-1 break-words text-sm font-bold tabular-nums text-neutral-900 dark:text-neutral-100">{m.value}</div>{m.note&&<p className="mt-1 text-[11px] leading-4 text-neutral-500">{m.note}</p>}</div>)}</div>}
export function Num({label,value,set,min,max,step=1,unit}:{label:string;value:number;set:(v:number)=>void;min?:number;max?:number;step?:number;unit?:string}){return <label className="block text-xs font-semibold text-neutral-700 dark:text-neutral-300"><span>{label}{unit?` (${unit})`:''}</span><input aria-label={label} className={field} type="number" value={Number.isFinite(value)?value:''} min={min} max={max} step={step} onChange={e=>set(Number(e.target.value))}/></label>}
export function Text({label,value,set,rows=8,placeholder}:{label:string;value:string;set:(v:string)=>void;rows?:number;placeholder?:string}){return <label className="block text-xs font-semibold text-neutral-700 dark:text-neutral-300"><span>{label}</span><textarea aria-label={label} className={`${field} font-mono`} rows={rows} value={value} placeholder={placeholder} onChange={e=>set(e.target.value)}/></label>}
export function downloadReport(filename:string,toolId:string,items:ProMetric[],inputs:unknown){const body=JSON.stringify({toolId,generatedAt:new Date().toISOString(),inputs,metrics:items},null,2),blob=new Blob([body],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
export function ExportButton({toolId,items,inputs}:{toolId:string;items:ProMetric[];inputs:unknown}){return <button type="button" onClick={()=>downloadReport(`${toolId}-specialist-report.json`,toolId,items,inputs)} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-neutral-300 px-3 py-2 text-xs font-bold hover:bg-neutral-50 dark:border-neutral-700 dark:hover:bg-neutral-900"><Download className="h-4 w-4"/>Export specialist report</button>}
export function Heading({label,focus}:{label:string;focus:string}){return <div><div className="text-[10px] font-black uppercase tracking-[.18em] text-emerald-600">R16 specialist core</div><h2 className="mt-1 text-lg font-black text-neutral-900 dark:text-neutral-100">{focus}</h2><p className="mt-1 text-xs leading-5 text-neutral-500">{label}. This panel adds task-specific analysis to the underlying tool rather than another generic state/workspace layer.</p></div>}
