import React,{useMemo,useState}from'react';
import type{ProMetric}from'../../strict-b-to-s/calculatorSpecs';
import{ExportButton,Heading,Metrics,Text,panel}from'./common';

type Parsed={major:number;minor:number;patch:number;pre:string[];build:string;normalized:string};
function parseSemver(raw:string):Parsed|null{const match=raw.trim().match(/^v?(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?(?:\+([0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*))?$/);if(!match)return null;const major=Number(match[1]),minor=Number(match[2]),patch=Number(match[3]);if(![major,minor,patch].every(Number.isSafeInteger))return null;return{major,minor,patch,pre:match[4]?.split('.')??[],build:match[5]??'',normalized:`${major}.${minor}.${patch}${match[4]?`-${match[4]}`:''}${match[5]?`+${match[5]}`:''}`}}
function compareIdentifiers(a:string,b:string){const an=/^\d+$/.test(a),bn=/^\d+$/.test(b);if(an&&bn){const ai=BigInt(a),bi=BigInt(b);return ai<bi?-1:ai>bi?1:0}if(an!==bn)return an?-1:1;return a<b?-1:a>b?1:0}
function compare(a:Parsed,b:Parsed){for(const key of ['major','minor','patch'] as const){if(a[key]!==b[key])return a[key]<b[key]?-1:1}if(!a.pre.length&&!b.pre.length)return 0;if(!a.pre.length)return 1;if(!b.pre.length)return-1;const n=Math.max(a.pre.length,b.pre.length);for(let i=0;i<n;i++){if(a.pre[i]===undefined)return-1;if(b.pre[i]===undefined)return 1;const c=compareIdentifiers(a.pre[i],b.pre[i]);if(c)return c}return 0}
function metrics(aRaw:string,bRaw:string):ProMetric[]{const a=parseSemver(aRaw),b=parseSemver(bRaw);if(!a||!b)return[{label:'Version A',value:a?'Valid':'Invalid'},{label:'Version B',value:b?'Valid':'Invalid'},{label:'Comparison',value:'Unavailable until both versions are valid SemVer'},{label:'Required shape',value:'MAJOR.MINOR.PATCH[-PRERELEASE][+BUILD]'},{label:'Leading-zero rule',value:'Numeric core identifiers cannot contain leading zeroes'},{label:'Trust boundary',value:'Build metadata does not affect precedence'}];const c=compare(a,b);return[{label:'Version A normalized',value:a.normalized},{label:'Version B normalized',value:b.normalized},{label:'Precedence',value:c===0?'A = B':c<0?'A < B':'A > B'},{label:'A prerelease',value:a.pre.length?a.pre.join('.'):'stable release'},{label:'B prerelease',value:b.pre.length?b.pre.join('.'):'stable release'},{label:'Build metadata',value:`A: ${a.build||'none'} · B: ${b.build||'none'}`} ]}
export function SemverLab({toolId,label,focus}:{toolId:string;label:string;focus:string}){const[a,setA]=useState('2.3.1-beta.1'),[b,setB]=useState('2.3.1');const items=useMemo(()=>metrics(a,b),[a,b]);return<section data-r16-s-tier={toolId} className={`${panel} space-y-4`}><Heading label={label} focus={focus}/><div className="grid gap-3 md:grid-cols-2"><Text label="Version A" value={a} set={setA} rows={3}/><Text label="Version B" value={b} set={setB} rows={3}/></div><Metrics items={items}/><p className="text-xs leading-5 text-neutral-500">Comparison follows SemVer precedence: core numbers compare numerically, prerelease identifiers compare in order, numeric prerelease identifiers sort below non-numeric identifiers, and build metadata is ignored for precedence.</p><ExportButton toolId={toolId} items={items} inputs={{a,b}}/></section>}
