import React,{useEffect,useMemo,useRef,useState}from'react';
import{Download,Loader2,Music,ShieldCheck,Upload}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{getPublicMediaTask,PUBLIC_MEDIA_TASKS}from'../../media/publicMediaTasks';
import{analyzeAudioBuffer,audioBufferToWavBlob,decodeAudioBlob,findActiveAudioRange,trimAudioBuffer}from'../../utilities/audio-recorder';
import{dbToGain,downmixChannels,joinedAudioDuration,playbackRateForSemitones,reverseSamples,sanitizeMediaBaseName,softNoiseGateSample}from'../../utilities/media-micro-tools';

function taskId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0];}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function createLike(ctx:BaseAudioContext,source:AudioBuffer,channels=source.numberOfChannels,length=source.length){return ctx.createBuffer(Math.max(1,channels),Math.max(1,length),source.sampleRate);}
function copyBuffer(ctx:BaseAudioContext,source:AudioBuffer){const out=createLike(ctx,source);for(let c=0;c<source.numberOfChannels;c++)out.copyToChannel(source.getChannelData(c),c);return out;}
function joinBuffers(ctx:BaseAudioContext,buffers:AudioBuffer[]){if(!buffers.length)throw new Error('Choose audio files first.');const rate=buffers[0].sampleRate,channels=Math.max(...buffers.map(b=>b.numberOfChannels)),length=buffers.reduce((n,b)=>n+b.length,0),out=ctx.createBuffer(channels,length,rate);let offset=0;for(const b of buffers){for(let c=0;c<channels;c++){const src=b.getChannelData(Math.min(c,b.numberOfChannels-1));out.getChannelData(c).set(src,offset);}offset+=b.length;}return out;}
async function renderRate(source:AudioBuffer,rate:number,filters?:{low:number;mid:number;high:number;highpass?:number;lowpass?:number}){const Offline=(window.OfflineAudioContext||(window as unknown as{webkitOfflineAudioContext?:typeof OfflineAudioContext}).webkitOfflineAudioContext);if(!Offline)throw new Error('Offline Web Audio rendering is not supported by this browser.');const playback=Math.max(.25,Math.min(4,rate)),length=Math.max(1,Math.ceil(source.length/playback)),offline=new Offline(source.numberOfChannels,length,source.sampleRate),node=offline.createBufferSource();node.buffer=source;node.playbackRate.value=playback;let tail:AudioNode=node;if(filters){if(filters.highpass){const f=offline.createBiquadFilter();f.type='highpass';f.frequency.value=filters.highpass;tail.connect(f);tail=f;}const low=offline.createBiquadFilter();low.type='lowshelf';low.frequency.value=180;low.gain.value=filters.low;tail.connect(low);tail=low;const mid=offline.createBiquadFilter();mid.type='peaking';mid.frequency.value=1200;mid.Q.value=.8;mid.gain.value=filters.mid;tail.connect(mid);tail=mid;const high=offline.createBiquadFilter();high.type='highshelf';high.frequency.value=6500;high.gain.value=filters.high;tail.connect(high);tail=high;if(filters.lowpass){const f=offline.createBiquadFilter();f.type='lowpass';f.frequency.value=filters.lowpass;tail.connect(f);tail=f;}}tail.connect(offline.destination);node.start();return offline.startRendering();}

const AudioMicroTools:React.FC=()=>{const task=useMemo(()=>getPublicMediaTask(taskId())??PUBLIC_MEDIA_TASKS.find(t=>t.engine==='audio')!,[]);const[file,setFile]=useState<File|null>(null),[files,setFiles]=useState<File[]>([]),[buffers,setBuffers]=useState<AudioBuffer[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState('');const[gainDb,setGainDb]=useState(3),[speed,setSpeed]=useState(1.25),[semitones,setSemitones]=useState(3),[normalizeDb,setNormalizeDb]=useState(-1),[thresholdDb,setThresholdDb]=useState(-45),[low,setLow]=useState(0),[mid,setMid]=useState(0),[high,setHigh]=useState(0),[channelMode,setChannelMode]=useState<'mono'|'stereo'>('mono'),[ringStart,setRingStart]=useState(0),[ringDuration,setRingDuration]=useState(30),[fade,setFade]=useState(.15);const ctxRef=useRef<AudioContext|null>(null),sourceUrl=useRef<string|null>(null);const getCtx=()=>{if(!ctxRef.current)ctxRef.current=new AudioContext();return ctxRef.current;};useEffect(()=>()=>{ctxRef.current?.close().catch(()=>{});if(sourceUrl.current)URL.revokeObjectURL(sourceUrl.current);},[]);
  const pick=async(list:FileList|null)=>{if(!list?.length)return;setBusy(true);setError('');try{const ctx=getCtx(),selected=[...list],decoded:AudioBuffer[]=[];for(const f of selected){setStatus(`Decoding ${decoded.length+1}/${selected.length}…`);decoded.push(await decodeAudioBlob(f,ctx));}setFiles(selected);setFile(selected[0]);setBuffers(decoded);if(sourceUrl.current)URL.revokeObjectURL(sourceUrl.current);sourceUrl.current=URL.createObjectURL(selected[0]);setStatus(`${selected.length} file${selected.length===1?'':'s'} ready.`);}catch(e){setError(e instanceof Error?e.message:'Audio decode failed.');setBuffers([]);}finally{setBusy(false);}};
  const primary=buffers[0]??null,analysis=primary?analyzeAudioBuffer(primary):null,multi=task.id==='audio-joiner';
  const process=async()=>{if(!primary)throw new Error('Choose an audio file first.');setBusy(true);setError('');setStatus('Processing locally…');try{const ctx=getCtx();let out:AudioBuffer;
    if(task.id==='audio-joiner'){out=joinBuffers(ctx,buffers);setStatus(`Joined ${buffers.length} files · ${joinedAudioDuration(buffers.map(b=>b.duration)).toFixed(1)}s.`);}
    else if(task.id==='audio-volume-changer')out=trimAudioBuffer(primary,ctx,{startSeconds:0,endSeconds:primary.duration},{fadeInSeconds:0,fadeOutSeconds:0,gain:dbToGain(gainDb)});
    else if(task.id==='audio-speed-changer')out=await renderRate(primary,speed);
    else if(task.id==='audio-pitch-speed-shifter')out=await renderRate(primary,playbackRateForSemitones(semitones));
    else if(task.id==='audio-normalizer')out=trimAudioBuffer(primary,ctx,{startSeconds:0,endSeconds:primary.duration},{fadeInSeconds:0,fadeOutSeconds:0,gain:1,normalizePeakDb:normalizeDb,removeDcOffset:true});
    else if(task.id==='silence-trimmer'){const range=findActiveAudioRange(primary,thresholdDb,.08);out=trimAudioBuffer(primary,ctx,range,{fadeInSeconds:.01,fadeOutSeconds:.01,gain:1});setStatus(`Kept ${range.startSeconds.toFixed(2)}s–${range.endSeconds.toFixed(2)}s.`);}
    else if(task.id==='audio-equalizer')out=await renderRate(primary,1,{low,mid,high});
    else if(task.id==='reverse-audio'){out=createLike(ctx,primary);for(let c=0;c<primary.numberOfChannels;c++)out.copyToChannel(reverseSamples(primary.getChannelData(c)),c);}
    else if(task.id==='audio-noise-cleanup'){const gated=copyBuffer(ctx,primary);for(let c=0;c<gated.numberOfChannels;c++){const data=gated.getChannelData(c);for(let i=0;i<data.length;i++)data[i]=softNoiseGateSample(data[i],thresholdDb);}out=await renderRate(gated,1,{low:0,mid:0,high:0,highpass:80,lowpass:14000});}
    else if(task.id==='stereo-mono-converter'){if(channelMode==='mono'){const mono=downmixChannels(Array.from({length:primary.numberOfChannels},(_,i)=>primary.getChannelData(i))),m=ctx.createBuffer(1,mono.length,primary.sampleRate);m.copyToChannel(mono,0);out=m;}else{const mono=primary.numberOfChannels===1?primary.getChannelData(0):downmixChannels(Array.from({length:primary.numberOfChannels},(_,i)=>primary.getChannelData(i))),s=ctx.createBuffer(2,mono.length,primary.sampleRate);s.copyToChannel(mono,0);s.copyToChannel(mono,1);out=s;}}
    else if(task.id==='ringtone-maker'){const start=Math.max(0,Math.min(primary.duration,ringStart)),end=Math.min(primary.duration,start+Math.max(1,Math.min(60,ringDuration)));out=trimAudioBuffer(primary,ctx,{startSeconds:start,endSeconds:end},{fadeInSeconds:fade,fadeOutSeconds:fade,gain:1});}
    else out=copyBuffer(ctx,primary);
    const blob=audioBufferToWavBlob(out),name=`${sanitizeMediaBaseName(file?.name||'audio')}-${task.id}.wav`;download(blob,name);if(!status.startsWith('Kept')&&!status.startsWith('Joined'))setStatus(`Done · ${out.duration.toFixed(2)}s WAV.`);
  }catch(e){setError(e instanceof Error?e.message:'Audio processing failed.');setStatus('');}finally{setBusy(false);}};
  return <ToolShell toolId={task.id} title={task.name} description={task.description} category="media" relatedToolIds={['audio-recorder','video-toolkit','speech-to-text']}><div className="space-y-5">
    <div className="rounded-xl border-2 border-dashed border-neutral-300 p-7 text-center dark:border-neutral-700"><Music className="mx-auto h-8 w-8 text-violet-600"/><p className="mt-2 text-sm font-semibold">Choose {multi?'two or more audio files':'an audio file'}</p><label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-lg bg-violet-600 px-4 py-2 text-xs font-semibold text-white"><Upload className="h-4 w-4"/>Choose audio<input className="hidden" type="file" accept="audio/*,.mp3,.m4a,.aac,.ogg,.wav,.webm" multiple={multi} onChange={e=>{void pick(e.target.files);e.target.value='';}}/></label><div className="mt-3 inline-flex items-center gap-1 text-[11px] text-emerald-700 dark:text-emerald-400"><ShieldCheck className="h-3.5 w-3.5"/>Decoded and processed locally.</div></div>
    {primary&&<><div className="grid gap-2 rounded-lg border border-neutral-200 bg-neutral-50 p-3 text-xs dark:border-neutral-800 dark:bg-neutral-950 sm:grid-cols-4"><span>{file?.name}</span><span>{primary.duration.toFixed(2)}s</span><span>{primary.sampleRate.toLocaleString()} Hz</span><span>{primary.numberOfChannels} channel{primary.numberOfChannels===1?'':'s'}</span></div>{sourceUrl.current&&<audio controls src={sourceUrl.current} className="w-full"/>}{analysis&&<div className="grid grid-cols-2 gap-2 text-xs sm:grid-cols-4"><span>Peak {Number.isFinite(analysis.peakDb)?analysis.peakDb.toFixed(1):'-∞'} dB</span><span>RMS {Number.isFinite(analysis.rmsDb)?analysis.rmsDb.toFixed(1):'-∞'} dB</span><span>Clipping {analysis.clippingPercent.toFixed(3)}%</span><span>DC {analysis.dcOffset.toFixed(5)}</span></div>}</>}
    <section className="grid gap-3 rounded-xl border border-neutral-200 p-4 dark:border-neutral-800 sm:grid-cols-2">
      {task.id==='audio-volume-changer'&&<label className="text-xs font-semibold">Gain {gainDb} dB<input className="mt-2 w-full" type="range" min="-24" max="12" step=".5" value={gainDb} onChange={e=>setGainDb(Number(e.target.value))}/></label>}
      {task.id==='audio-speed-changer'&&<label className="text-xs font-semibold">Speed {speed.toFixed(2)}×<input className="mt-2 w-full" type="range" min=".5" max="2" step=".05" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></label>}
      {task.id==='audio-pitch-speed-shifter'&&<label className="text-xs font-semibold">Transpose {semitones>0?'+':''}{semitones} semitones<input className="mt-2 w-full" type="range" min="-12" max="12" step="1" value={semitones} onChange={e=>setSemitones(Number(e.target.value))}/></label>}
      {task.id==='audio-normalizer'&&<label className="text-xs font-semibold">Target peak {normalizeDb} dBFS<input className="mt-2 w-full" type="range" min="-12" max="0" step=".5" value={normalizeDb} onChange={e=>setNormalizeDb(Number(e.target.value))}/></label>}
      {['silence-trimmer','audio-noise-cleanup'].includes(task.id)&&<label className="text-xs font-semibold">Threshold {thresholdDb} dB<input className="mt-2 w-full" type="range" min="-70" max="-20" step="1" value={thresholdDb} onChange={e=>setThresholdDb(Number(e.target.value))}/></label>}
      {task.id==='audio-equalizer'&&<>{[['Bass',low,setLow],['Mid',mid,setMid],['Treble',high,setHigh]].map(([label,value,setter])=><label key={String(label)} className="text-xs font-semibold">{label} {Number(value)>0?'+':''}{value} dB<input className="mt-2 w-full" type="range" min="-12" max="12" step="1" value={Number(value)} onChange={e=>(setter as React.Dispatch<React.SetStateAction<number>>)(Number(e.target.value))}/></label>)}</>}
      {task.id==='stereo-mono-converter'&&<label className="text-xs font-semibold">Output channels<select className="mt-1 w-full rounded border bg-transparent px-3 py-2" value={channelMode} onChange={e=>setChannelMode(e.target.value as'mono'|'stereo')}><option value="mono">Mono</option><option value="stereo">Stereo</option></select></label>}
      {task.id==='ringtone-maker'&&<><label className="text-xs font-semibold">Start seconds<input className="mt-1 w-full rounded border bg-transparent px-3 py-2" type="number" min="0" step=".1" value={ringStart} onChange={e=>setRingStart(Number(e.target.value))}/></label><label className="text-xs font-semibold">Length seconds<input className="mt-1 w-full rounded border bg-transparent px-3 py-2" type="number" min="1" max="60" value={ringDuration} onChange={e=>setRingDuration(Number(e.target.value))}/></label><label className="text-xs font-semibold">Fade {fade.toFixed(2)}s<input className="mt-2 w-full" type="range" min="0" max="2" step=".05" value={fade} onChange={e=>setFade(Number(e.target.value))}/></label></>}
      {task.id==='audio-noise-cleanup'&&<p className="text-xs text-neutral-500 sm:col-span-2">Uses an 80 Hz high-pass, 14 kHz low-pass and soft gate. It will not separate voices from music or remove complex background sounds like an AI model.</p>}
      {task.id==='audio-speed-changer'&&<p className="text-xs text-neutral-500 sm:col-span-2">Browser-native offline playback-rate rendering changes pitch with speed. This route does not claim studio-grade pitch-preserving time stretch.</p>}
    </section>
    {error&&<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{error}</div>}
    <div className="flex flex-wrap items-center gap-3"><button disabled={!primary||busy||(multi&&buffers.length<2)} onClick={()=>void process()} className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-4 py-2 text-xs font-bold text-white disabled:opacity-40 dark:bg-neutral-100 dark:text-neutral-900">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Download className="h-4 w-4"/>}Process & download WAV</button>{status&&<span className="text-xs text-neutral-500">{status}</span>}</div>
  </div></ToolShell>;
};
export default AudioMicroTools;
