import React from'react';
import{Download}from'lucide-react';
import type{Metric}from'../../strict-a-to-s/analysis';
export const panel='rounded-2xl border border-neutral-200 bg-white p-4 dark:border-neutral-800 dark:bg-neutral-950';
export const field='mt-1 w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm text-neutral-900 outline-none focus:ring-2 focus:ring-blue-500/30 dark:border-neutral-700 dark:bg-neutral-950 dark:text-neutral-100';
export function Num({label,value,set}:{label:string;value:number;set:(v:number)=>void}){return <label className="block text-xs font-semibold text-neutral-700 dark:text-neutral-300"><span>{label}</span><input className={field} type="number" aria-label={label} value={Number.isFinite(value)?value:''} onChange={e=>set(Number(e.target.value))}/></label>}
export function Text({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return <label className="block text-xs font-semibold text-neutral-700 dark:text-neutral-300"><span>{label}</span><textarea className={`${field} font-mono`} rows={5} aria-label={label} value={value} onChange={e=>set(e.target.value)}/></label>}
export function Metrics({items}:{items:Metric[]}){return <div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{items.map((item,index)=><div key={`${item.label}-${index}`} className="rounded-xl border border-neutral-200 bg-neutral-50 p-3 dark:border-neutral-800 dark:bg-neutral-900/40"><div className="text-[10px] font-black uppercase tracking-wide text-neutral-500">{item.label}</div><div className="mt-1 break-words text-sm font-bold tabular-nums text-neutral-900 dark:text-neutral-100">{item.value}</div>{item.note&&<p className="mt-1 text-[11px] leading-4 text-neutral-500">{item.note}</p>}</div>)}</div>}
export function exportMetrics(toolId:string,inputs:unknown,metrics:Metric[]){const blob=new Blob([JSON.stringify({toolId,generatedAt:new Date().toISOString(),inputs,metrics},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${toolId}-r17-verification.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),0)}
export function ExportButton({toolId,inputs,metrics}:{toolId:string;inputs:unknown;metrics:Metric[]}){return <button type="button" onClick={()=>exportMetrics(toolId,inputs,metrics)} className="inline-flex min-h-10 items-center gap-2 rounded-lg border border-neutral-300 px-3 py-2 text-xs font-bold hover:bg-neutral-50 dark:border-neutral-700 dark:hover:bg-neutral-900"><Download className="h-4 w-4"/>Export verification JSON</button>}
