import React,{useEffect,useMemo,useState}from'react';
import{Download,RotateCcw,Upload}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{encodePcm16Wav,formatAudioTime,processReverseChannels,type AudioProcessSummary}from'../../utilities/s-tier-audio';

interface LoadedAudio{name:string;channels:Float32Array[];sampleRate:number;duration:number;originalUrl:string;}
const inputClass='mt-1 w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 dark:border-neutral-700 dark:bg-neutral-950';
export default function ReverseAudioStudio(){
 const[audio,setAudio]=useState<LoadedAudio|null>(null),[start,setStart]=useState(0),[end,setEnd]=useState(0),[fade,setFade]=useState(5),[normalize,setNormalize]=useState(false),[resultUrl,setResultUrl]=useState(''),[summary,setSummary]=useState<AudioProcessSummary|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>()=>{if(audio?.originalUrl)URL.revokeObjectURL(audio.originalUrl);if(resultUrl)URL.revokeObjectURL(resultUrl)},[audio?.originalUrl,resultUrl]);
 const selection=audio?Math.max(0,end-start):0;
 const load=async(file:File|null)=>{if(!file)return;setBusy(true);setError('');setSummary(null);if(resultUrl){URL.revokeObjectURL(resultUrl);setResultUrl('')}try{const Context=window.AudioContext||(window as typeof window&{webkitAudioContext?:typeof AudioContext}).webkitAudioContext;if(!Context)throw new Error('Web Audio decoding is unavailable in this browser.');const ctx=new Context();const buffer=await ctx.decodeAudioData((await file.arrayBuffer()).slice(0));const channels=Array.from({length:buffer.numberOfChannels},(_,i)=>new Float32Array(buffer.getChannelData(i)));await ctx.close();if(audio?.originalUrl)URL.revokeObjectURL(audio.originalUrl);const originalUrl=URL.createObjectURL(file);const loaded={name:file.name,channels,sampleRate:buffer.sampleRate,duration:buffer.duration,originalUrl};setAudio(loaded);setStart(0);setEnd(buffer.duration);}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}};
 const process=()=>{if(!audio)return;setError('');try{const processed=processReverseChannels(audio.channels,audio.sampleRate,{startSeconds:start,endSeconds:end,fadeMs:fade,normalizePeak:normalize});const blob=encodePcm16Wav(processed.channels,audio.sampleRate);if(resultUrl)URL.revokeObjectURL(resultUrl);setResultUrl(URL.createObjectURL(blob));setSummary(processed.summary);}catch(e){setError(e instanceof Error?e.message:String(e))}};
 const download=()=>{if(!resultUrl||!audio)return;const a=document.createElement('a');a.href=resultUrl;a.download=`${audio.name.replace(/\.[^/.]+$/,'') || 'audio'}-reversed.wav`;a.click()};
 return<ToolShell toolId="reverse-audio" title="Reverse Audio" description="Reverse an entire audio file or a precise time selection locally, with boundary fades, optional peak normalization, before/after previews, and PCM WAV export." category="media" relatedToolIds={['audio-normalizer','audio-volume-changer','audio-speed-changer']}><div className="space-y-5">
  <div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs leading-5 text-blue-900 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-200">Audio is decoded and processed locally with Web Audio. Selection reversal preserves the rest of the file. Short boundary fades can reduce clicks where the reversed region meets unchanged audio.</div>
  <label className="flex cursor-pointer flex-col items-center justify-center gap-2 rounded-xl border-2 border-dashed border-neutral-300 p-7 text-center dark:border-neutral-700"><Upload className="h-6 w-6 text-neutral-500"/><span className="font-semibold">Choose an audio file</span><span className="text-xs text-neutral-500">Any format your browser can decode</span><input aria-label="Choose audio file to reverse" type="file" accept="audio/*" className="sr-only" onChange={e=>void load(e.target.files?.[0]??null)}/></label>
  {busy&&<div role="status" className="text-sm text-neutral-500">Decoding audio…</div>}{error&&<ErrorBox text={error}/>} {audio&&<><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Duration" value={formatAudioTime(audio.duration)}/><Metric label="Sample rate" value={`${audio.sampleRate.toLocaleString()} Hz`}/><Metric label="Channels" value={String(audio.channels.length)}/><Metric label="Selection" value={formatAudioTime(selection)}/></div><section className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><h2 className="text-sm font-bold">1. Original</h2><audio aria-label="Original audio preview" controls src={audio.originalUrl} className="mt-3 w-full"/></section><section className="space-y-4 rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><h2 className="text-sm font-bold">2. Reverse settings</h2><div className="grid gap-3 sm:grid-cols-2"><Num label="Selection start (seconds)" value={start} set={v=>setStart(Math.min(Math.max(0,v),end))} min={0} max={audio.duration}/><Num label="Selection end (seconds)" value={end} set={v=>setEnd(Math.max(start,Math.min(audio.duration,v)))} min={0} max={audio.duration}/></div><div className="grid gap-3 sm:grid-cols-2"><Num label="Boundary fade (ms)" value={fade} set={setFade} min={0} max={200}/><label className="flex items-end gap-2 pb-2 text-xs"><input type="checkbox" checked={normalize} onChange={e=>setNormalize(e.target.checked)}/> Peak-normalize result to 98%</label></div><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>{setStart(0);setEnd(audio.duration)}} className="rounded-lg border border-neutral-300 px-3 py-2 text-sm font-semibold dark:border-neutral-700">Whole file</button><button type="button" onClick={process} className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-4 py-2 text-sm font-semibold text-white dark:bg-neutral-100 dark:text-neutral-900"><RotateCcw className="h-4 w-4"/>Reverse selection</button></div></section>{resultUrl&&<section className="rounded-xl border border-emerald-200 bg-emerald-50/50 p-4 dark:border-emerald-900 dark:bg-emerald-950/10"><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="text-sm font-bold">3. Reversed result</h2><button type="button" onClick={download} className="inline-flex items-center gap-2 rounded-lg border border-emerald-400 px-3 py-2 text-sm font-semibold"><Download className="h-4 w-4"/>Download WAV</button></div><audio aria-label="Reversed audio preview" controls src={resultUrl} className="mt-3 w-full"/>{summary&&<div className="mt-3 grid gap-2 sm:grid-cols-3"><Metric label="Samples reversed" value={summary.reversedSamples.toLocaleString()}/><Metric label="Peak after" value={summary.peakAfter.toFixed(3)}/><Metric label="Gain applied" value={`${summary.gainApplied.toFixed(3)}×`}/></div>}</section>}</>}
 </div></ToolShell>
}
function Num({label,value,set,min,max}:{label:string;value:number;set:(v:number)=>void;min:number;max:number}){return<label className="text-xs font-semibold">{label}<input aria-label={label} type="number" min={min} max={max} step="0.01" value={Number(value.toFixed(3))} onChange={e=>set(Number(e.target.value))} className={inputClass}/></label>}
function Metric({label,value}:{label:string;value:string}){return<div className="rounded-xl border border-neutral-200 p-3 dark:border-neutral-800"><div className="text-[10px] font-semibold uppercase tracking-wide text-neutral-500">{label}</div><div className="mt-1 text-lg font-bold">{value}</div></div>}
function ErrorBox({text}:{text:string}){return<div role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{text}</div>}
