import React,{useMemo,useState}from'react';
import{Clock,Copy,Plus,RotateCcw,Search,Trash2}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{findBestMeetingSlots,formatZoneTime,generateComparisonSummary,getSupportedTimeZones,getZonedNowFields,resolveDateInZone,type ConvertedTimeRow}from'../../utilities/time-zone-converter';

export const TimeZoneConverterTool:React.FC=()=>{
 const localZone=useMemo(()=>{try{return Intl.DateTimeFormat().resolvedOptions().timeZone||'UTC';}catch{return'UTC';}},[]);
 const allZones=useMemo(()=>getSupportedTimeZones(),[]);
 const nowFields=useMemo(()=>getZonedNowFields(localZone),[localZone]);
 const[sourceZone,setSourceZone]=useState(localZone);const[selectedDate,setSelectedDate]=useState(nowFields.date);const[hour,setHour]=useState(nowFields.hour);const[minute,setMinute]=useState(nowFields.minute);const[active,setActive]=useState<string[]>(()=>[...new Set([localZone,'UTC','America/New_York','Europe/London','Europe/Berlin','Asia/Seoul','Asia/Tokyo'])]);const[query,setQuery]=useState('');const[is24,setIs24]=useState(true);const[duration,setDuration]=useState(60);const[horizon,setHorizon]=useState(24);const[copied,setCopied]=useState(false);
 const resolution=useMemo(()=>{const[y,m,d]=selectedDate.split('-').map(Number);try{return resolveDateInZone(y,m,d,hour,minute,sourceZone);}catch{return null;}},[selectedDate,hour,minute,sourceZone]);
 const instant=resolution?.date??new Date();
 const rows:ConvertedTimeRow[]=useMemo(()=>active.map(zone=>formatZoneTime(instant,zone,instant,is24,sourceZone)),[active,instant,is24,sourceZone]);
 const meetings=useMemo(()=>findBestMeetingSlots(instant,active,{durationMinutes:duration,horizonHours:horizon,limit:5,is24Hour:is24}),[instant,active,duration,horizon,is24]);
 const matches=useMemo(()=>{const q=query.trim().toLocaleLowerCase();if(!q)return[];return allZones.filter(z=>!active.includes(z.id)&&`${z.city} ${z.country||''} ${z.id}`.toLocaleLowerCase().includes(q)).slice(0,12);},[query,allZones,active]);
 const setNow=()=>{const f=getZonedNowFields(sourceZone);setSelectedDate(f.date);setHour(f.hour);setMinute(f.minute);};
 const copyAll=async()=>{if(await copyToClipboard(generateComparisonSummary(rows))){setCopied(true);window.setTimeout(()=>setCopied(false),1500);}};
 return <ToolShell toolId="time-zone-converter" title="Time Zone & World Clock Converter" description="Convert any IANA time zone, handle DST folds/gaps explicitly, and rank practical meeting windows." category="time" relatedToolIds={['date-calculator','calendar-event-maker','timer-stopwatch']} outputToTransfer={generateComparisonSummary(rows)}>
  <div className="space-y-5">
   <div className="rounded-xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-950 p-4 space-y-3">
    <div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2 text-sm font-semibold"><Clock className="w-4 h-4 text-blue-600"/>Source wall-clock time</div><div className="flex gap-2"><button type="button" onClick={setNow} className="px-3 py-1.5 text-xs border rounded-lg bg-white dark:bg-neutral-900 inline-flex items-center gap-1"><RotateCcw className="w-3 h-3"/>Now in source zone</button><button type="button" onClick={()=>setIs24(v=>!v)} className="px-3 py-1.5 text-xs border rounded-lg bg-white dark:bg-neutral-900">{is24?'24-hour':'12-hour'}</button></div></div>
    <div className="grid sm:grid-cols-4 gap-2"><select value={sourceZone} onChange={e=>setSourceZone(e.target.value)} className="px-2 py-2 text-xs border rounded-lg bg-white dark:bg-neutral-900"><option value={sourceZone}>{sourceZone}</option>{allZones.filter(z=>z.id!==sourceZone).map(z=><option key={z.id} value={z.id}>{z.city} — {z.id}</option>)}</select><input type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)} className="px-2 py-2 text-xs border rounded-lg bg-white dark:bg-neutral-900"/><input aria-label="Source hour" type="number" min={0} max={23} value={hour} onChange={e=>setHour(Math.max(0,Math.min(23,Number(e.target.value))))} className="px-2 py-2 text-xs border rounded-lg bg-white dark:bg-neutral-900"/><input aria-label="Source minute" type="number" min={0} max={59} value={minute} onChange={e=>setMinute(Math.max(0,Math.min(59,Number(e.target.value))))} className="px-2 py-2 text-xs border rounded-lg bg-white dark:bg-neutral-900"/></div>
    {resolution&&resolution.status!=='exact'&&<div className="text-xs rounded-lg border border-amber-300 dark:border-amber-800 bg-amber-50 dark:bg-amber-950/40 p-2"><strong>DST {resolution.status==='ambiguous'?'fold':'gap'}:</strong> {resolution.status==='ambiguous'?`this wall time occurs twice; the earlier instant is selected (${resolution.candidates.length} valid instants).`:`this wall time does not exist; shifted forward ${resolution.shiftedByMinutes} minutes.`}</div>}
   </div>
   <div className="relative"><Search className="absolute left-3 top-2.5 w-4 h-4 text-neutral-400"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the full browser-supported IANA time-zone catalog…" className="w-full pl-9 pr-3 py-2 text-xs border rounded-lg bg-white dark:bg-neutral-900"/>{matches.length>0&&<div className="absolute z-20 top-full mt-1 w-full max-h-64 overflow-auto border rounded-lg bg-white dark:bg-neutral-900 shadow-xl">{matches.map(z=><button key={z.id} type="button" onClick={()=>{setActive(a=>[...a,z.id]);setQuery('');}} className="w-full px-3 py-2 text-left text-xs hover:bg-neutral-100 dark:hover:bg-neutral-800 flex justify-between"><span>{z.city}{z.country?` · ${z.country}`:''}</span><span className="font-mono text-neutral-400">{z.id}</span></button>)}</div>}</div>
   <div className="space-y-2">{rows.map(row=><div key={row.zoneId} className="grid sm:grid-cols-[1fr_auto_auto] gap-3 items-center border rounded-lg p-3 bg-white dark:bg-neutral-900"><div className="min-w-0"><div className="font-semibold text-sm truncate">{row.city}</div><div className="font-mono text-[11px] text-neutral-500 truncate">{row.zoneId} · {row.utcOffset}</div></div><div className="text-right"><div className="text-lg font-mono font-bold">{row.formattedTime}</div><div className="text-[11px] text-neutral-500">{row.formattedDate} · {row.dayDifference} · {row.isBusinessHours?'business hours':'off hours'}</div></div><button aria-label={`Remove ${row.city}`} type="button" disabled={active.length<=1} onClick={()=>setActive(a=>a.filter(x=>x!==row.zoneId))} className="p-2 text-neutral-400 hover:text-red-500 disabled:opacity-30"><Trash2 className="w-4 h-4"/></button></div>)}</div>
   <div className="rounded-xl border border-neutral-200 dark:border-neutral-800 p-4 space-y-3"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-sm font-semibold">Meeting Planner</h3><p className="text-xs text-neutral-500">Ranks upcoming slots by overlap with 09:00–18:00 local business hours across every selected zone.</p></div><div className="flex gap-2"><label className="text-xs">Duration <select value={duration} onChange={e=>setDuration(Number(e.target.value))} className="ml-1 border rounded bg-white dark:bg-neutral-900 p-1"><option value={30}>30m</option><option value={60}>60m</option><option value={90}>90m</option></select></label><label className="text-xs">Search <select value={horizon} onChange={e=>setHorizon(Number(e.target.value))} className="ml-1 border rounded bg-white dark:bg-neutral-900 p-1"><option value={12}>12h</option><option value={24}>24h</option><option value={48}>48h</option></select></label></div></div><div className="grid md:grid-cols-5 gap-2">{meetings.map((slot,index)=><div key={slot.instant.toISOString()} className={`p-3 rounded-lg border ${slot.allBusinessHours?'border-emerald-300 bg-emerald-50 dark:bg-emerald-950/30':'border-neutral-200 dark:border-neutral-800'}`}><div className="text-[10px] uppercase font-bold text-neutral-500">#{index+1}{slot.allBusinessHours?' · all in hours':''}</div><div className="font-mono text-xs mt-1">{slot.rows[0]?.formattedDate}</div><div className="font-mono font-bold">{slot.rows[0]?.formattedTime}</div><div className="text-[10px] text-neutral-500 mt-1">score {slot.score.toFixed(1)}</div></div>)}</div></div>
   <button type="button" onClick={copyAll} className="px-3 py-2 rounded-lg bg-neutral-900 dark:bg-neutral-100 text-white dark:text-neutral-900 text-xs font-semibold inline-flex items-center gap-1"><Copy className="w-3.5 h-3.5"/>{copied?'Copied':'Copy all times'}</button>
  </div>
 </ToolShell>;
};
export default TimeZoneConverterTool;
