import React,{useEffect,useMemo,useRef,useState}from'react';
import JSZip from'jszip';
import{Camera,Download,Film,Loader2,ShieldCheck,Square,Upload}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{getPublicMediaTask,PUBLIC_MEDIA_TASKS}from'../../media/publicMediaTasks';
import{audioBufferToWavBlob}from'../../utilities/audio-recorder';
import{encodeGif}from'../../utilities/gif-maker';
import{estimateLoopedDuration,mediaExtensionFromMime,parseSubtitleCues,planVideoFrameTimes,sanitizeMediaBaseName,subtitleAtTime,supportedVideoRecorderMimes}from'../../utilities/media-micro-tools';
import{calculateRecommendedVideoBitrate}from'../../utilities/video-toolkit';

type LoadedVideo={file:File;video:HTMLVideoElement;url:string;duration:number;width:number;height:number};
type CaptureVideo=HTMLVideoElement&{captureStream?:()=>MediaStream;mozCaptureStream?:()=>MediaStream};
function currentTaskId(){const clean=window.location.hash.replace(/^#\/?/,'').split('?')[0];return clean.startsWith('tool/')?clean.slice(5).split('/')[0]:clean.split('/')[0];}
function download(blob:Blob,name:string){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1200);}
function seek(video:HTMLVideoElement,time:number){return new Promise<void>((resolve,reject)=>{const target=Math.max(0,Math.min(Number.isFinite(video.duration)?video.duration:time,time));if(Math.abs(video.currentTime-target)<.015){resolve();return;}const timer=window.setTimeout(()=>{cleanup();reject(new Error('Timed out while seeking the video.'));},6000),cleanup=()=>{clearTimeout(timer);video.removeEventListener('seeked',ok);video.removeEventListener('error',bad);},ok=()=>{cleanup();resolve();},bad=()=>{cleanup();reject(new Error('The video could not seek to that frame.'));};video.addEventListener('seeked',ok,{once:true});video.addEventListener('error',bad,{once:true});video.currentTime=target;});}
function loadVideo(file:File):Promise<LoadedVideo>{return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),video=document.createElement('video');video.preload='auto';video.playsInline=true;video.src=url;video.onloadedmetadata=()=>resolve({file,video,url,duration:Number.isFinite(video.duration)?video.duration:0,width:video.videoWidth||1280,height:video.videoHeight||720});video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error(`This browser could not decode ${file.name}.`));};});}
function loadImage(file:File):Promise<HTMLImageElement>{return new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{URL.revokeObjectURL(url);resolve(img);};img.onerror=()=>{URL.revokeObjectURL(url);reject(new Error('The overlay image could not be decoded.'));};img.src=url;});}
function canvasBlob(canvas:HTMLCanvasElement,type='image/png',quality=.92){return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Image export failed.')),type,quality));}
function drawContain(ctx:CanvasRenderingContext2D,video:HTMLVideoElement,w:number,h:number,aspect:string){ctx.fillStyle='#000';ctx.fillRect(0,0,w,h);let sx=0,sy=0,sw=video.videoWidth,sh=video.videoHeight;if(aspect!=='original'){const[a,b]=aspect.split(':').map(Number),target=a/b,current=sw/sh;if(current>target){const next=sh*target;sx=(sw-next)/2;sw=next;}else{const next=sw/target;sy=(sh-next)/2;sh=next;}}ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.drawImage(video,sx,sy,sw,sh,0,0,w,h);}
function wrapText(ctx:CanvasRenderingContext2D,text:string,maxWidth:number){const words=text.split(/\s+/),lines:string[]=[];let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);return lines.slice(0,4);}

const VideoMicroTools:React.FC=()=>{const task=useMemo(()=>getPublicMediaTask(currentTaskId())??PUBLIC_MEDIA_TASKS.find(t=>t.engine==='video')!,[]);const[files,setFiles]=useState<File[]>([]),[loaded,setLoaded]=useState<LoadedVideo[]>([]),[audioFile,setAudioFile]=useState<File|null>(null),[logoFile,setLogoFile]=useState<File|null>(null),[overlayText,setOverlayText]=useState('Sample caption'),[subtitleText,setSubtitleText]=useState(''),[loops,setLoops]=useState(2),[speed,setSpeed]=useState(1),[quality,setQuality]=useState<'compact'|'balanced'|'high'>('balanced'),[resolution,setResolution]=useState<'original'|'1080'|'720'|'480'>('original'),[aspect,setAspect]=useState('original'),[volume,setVolume]=useState(1),[mime,setMime]=useState(''),[frameCount,setFrameCount]=useState(12),[thumbTime,setThumbTime]=useState(0),[gifFps,setGifFps]=useState(8),[gifSeconds,setGifSeconds]=useState(5),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[error,setError]=useState(''),[status,setStatus]=useState('');const[webcamStream,setWebcamStream]=useState<MediaStream|null>(null),[recording,setRecording]=useState(false),[recorded,setRecorded]=useState<{blob:Blob;url:string}|null>(null);const webcamRef=useRef<HTMLVideoElement>(null),recorderRef=useRef<MediaRecorder|null>(null),chunksRef=useRef<Blob[]>([]),cancelRef=useRef(false);
  const mimes=useMemo(()=>supportedVideoRecorderMimes(),[]);useEffect(()=>{if(!mime&&mimes[0])setMime(mimes[0]);},[mime,mimes]);useEffect(()=>()=>{for(const item of loaded)URL.revokeObjectURL(item.url);webcamStream?.getTracks().forEach(t=>t.stop());if(recorded)URL.revokeObjectURL(recorded.url);},[loaded,webcamStream,recorded]);
  const chooseVideos=async(list:FileList|null)=>{if(!list?.length)return;setBusy(true);setError('');try{for(const item of loaded)URL.revokeObjectURL(item.url);const selected=[...list],items:LoadedVideo[]=[];for(const file of selected){setStatus(`Loading ${items.length+1}/${selected.length}…`);items.push(await loadVideo(file));}setFiles(selected);setLoaded(items);setThumbTime(Math.min(1,items[0]?.duration||0));setStatus(`${items.length} video${items.length===1?'':'s'} ready.`);}catch(e){setError(e instanceof Error?e.message:'Video load failed.');}finally{setBusy(false);}};
  const primary=loaded[0],multi=task.id==='merge-videos';
  const dimensions=()=>{if(!primary)return{width:1280,height:720};const ratio=aspect==='original'?primary.width/primary.height:Number(aspect.split(':')[0])/Number(aspect.split(':')[1]),long=resolution==='1080'?1080:resolution==='720'?720:resolution==='480'?480:0;if(!long)return{width:Math.max(2,Math.round(primary.width/2)*2),height:Math.max(2,Math.round(primary.height/2)*2)};if(ratio>=1)return{width:Math.max(2,Math.round(long*ratio/2)*2),height:long};return{width:long,height:Math.max(2,Math.round(long/ratio/2)*2)};};
  const renderVideo=async()=>{if(!primary)throw new Error('Choose a video first.');if(typeof MediaRecorder==='undefined'||typeof HTMLCanvasElement.prototype.captureStream!=='function')throw new Error('This browser cannot perform local transformed-video encoding.');if(!mime)throw new Error('No supported browser video encoder was found.');cancelRef.current=false;const sequence=task.id==='merge-videos'?loaded:[primary],loopCount=task.id==='loop-video'?Math.max(1,Math.min(10,loops)):1,{width,height}=dimensions(),fps=quality==='compact'?24:quality==='high'?60:30,bitrate=calculateRecommendedVideoBitrate(width,height,fps,quality),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const ctx=canvas.getContext('2d',{alpha:false});if(!ctx)throw new Error('Canvas rendering is unavailable.');const stream=canvas.captureStream(fps),audioCtx=new AudioContext(),destination=audioCtx.createMediaStreamDestination(),nodes:AudioNode[]=[];let extraAudio:HTMLAudioElement|null=null,extraUrl:string|null=null;
    const muted=task.id==='mute-video';for(const item of sequence){try{const source=audioCtx.createMediaElementSource(item.video),gain=audioCtx.createGain();gain.gain.value=muted?0:Math.max(0,Math.min(2,volume));source.connect(gain).connect(destination);nodes.push(source,gain);}catch{}}
    if(task.id==='add-audio-to-video'&&audioFile){extraUrl=URL.createObjectURL(audioFile);extraAudio=new Audio(extraUrl);extraAudio.loop=true;extraAudio.preload='auto';try{const source=audioCtx.createMediaElementSource(extraAudio),gain=audioCtx.createGain();gain.gain.value=.8;source.connect(gain).connect(destination);nodes.push(source,gain);}catch{}}
    const outputTracks=[...stream.getVideoTracks(),...destination.stream.getAudioTracks()],output=new MediaStream(outputTracks),recorder=new MediaRecorder(output,{mimeType:mime,videoBitsPerSecond:bitrate}),chunks:Blob[]=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};const stopped=new Promise<Blob>((resolve,reject)=>{recorder.onerror=()=>reject(new Error('Browser video encoder failed.'));recorder.onstop=()=>resolve(new Blob(chunks,{type:mime}));});recorder.start(250);await audioCtx.resume();if(extraAudio)await extraAudio.play().catch(()=>{});let logo:HTMLImageElement|null=null;if(task.id==='add-logo-to-video'&&logoFile)logo=await loadImage(logoFile);const cues=task.id==='subtitle-burner'?parseSubtitleCues(subtitleText):[],total=sequence.reduce((sum,v)=>sum+v.duration,0)*loopCount/Math.max(.1,speed);let elapsedBase=0;
    const drawOverlay=(video:HTMLVideoElement)=>{drawContain(ctx,video,width,height,aspect);if(task.id==='add-logo-to-video'&&logo){const max=Math.min(width,height)*.2,scale=Math.min(max/logo.width,max/logo.height,1),dw=logo.width*scale,dh=logo.height*scale;ctx.drawImage(logo,width-dw-24,height-dh-24,dw,dh);}let text='';if(task.id==='add-text-to-video')text=overlayText;if(task.id==='subtitle-burner')text=subtitleAtTime(cues,video.currentTime);if(text){ctx.font=`600 ${Math.max(22,Math.round(width/32))}px system-ui,sans-serif`;ctx.textAlign='center';ctx.textBaseline='bottom';const lines=wrapText(ctx,text,width*.84),lineH=Math.round(width/26),boxH=lines.length*lineH+24;ctx.fillStyle='rgba(0,0,0,.62)';ctx.fillRect(width*.06,height-boxH-28,width*.88,boxH);ctx.fillStyle='#fff';lines.forEach((line,i)=>ctx.fillText(line,width/2,height-40-(lines.length-1-i)*lineH,width*.82));}};
    try{for(let repeat=0;repeat<loopCount;repeat++)for(const item of sequence){if(cancelRef.current)break;const video=item.video;video.playbackRate=Math.max(.5,Math.min(2,speed));await seek(video,0);drawOverlay(video);await video.play();await new Promise<void>((resolve,reject)=>{const tick=()=>{if(cancelRef.current){video.pause();resolve();return;}try{drawOverlay(video);const local=Math.min(item.duration,video.currentTime)/Math.max(.1,speed);setProgress(Math.min(99,Math.round((elapsedBase+local)/Math.max(.01,total)*100)));if(video.ended||video.currentTime>=item.duration-.02){video.pause();resolve();return;}requestAnimationFrame(tick);}catch(e){reject(e);}};requestAnimationFrame(tick);});elapsedBase+=item.duration/Math.max(.1,speed);}if(recorder.state!=='inactive')recorder.stop();const blob=await stopped;if(!blob.size)throw new Error('The browser produced an empty video.');download(blob,`${sanitizeMediaBaseName(files[0]?.name||'video')}-${task.id}.${mediaExtensionFromMime(mime)}`);setProgress(100);setStatus(`Done · real-time ${fps} fps browser export.`);}finally{sequence.forEach(v=>v.video.pause());extraAudio?.pause();if(extraUrl)URL.revokeObjectURL(extraUrl);stream.getTracks().forEach(t=>t.stop());output.getTracks().forEach(t=>t.stop());await audioCtx.close().catch(()=>{});}
  };
  const extractAudio=async()=>{if(!files[0])throw new Error('Choose a video first.');const ctx=new AudioContext();try{const buffer=await ctx.decodeAudioData((await files[0].arrayBuffer()).slice(0));download(audioBufferToWavBlob(buffer),`${sanitizeMediaBaseName(files[0].name)}-audio.wav`);setStatus(`Extracted ${buffer.duration.toFixed(2)}s WAV.`);}finally{await ctx.close().catch(()=>{});}};
  const frameAt=async(time:number)=>{if(!primary)throw new Error('Choose a video first.');await seek(primary.video,time);const c=document.createElement('canvas');c.width=primary.width;c.height=primary.height;const ctx=c.getContext('2d');if(!ctx)throw new Error('Canvas unavailable.');ctx.drawImage(primary.video,0,0,c.width,c.height);return c;};
  const extractFrames=async()=>{if(!primary)throw new Error('Choose a video first.');const zip=new JSZip(),times=planVideoFrameTimes(primary.duration,frameCount);for(let i=0;i<times.length;i++){setProgress(Math.round(i/times.length*100));const c=await frameAt(times[i]),blob=await canvasBlob(c);zip.file(`frame-${String(i+1).padStart(3,'0')}-${times[i].toFixed(2)}s.png`,await blob.arrayBuffer());}download(await zip.generateAsync({type:'blob',compression:'DEFLATE'}),`${sanitizeMediaBaseName(primary.file.name)}-frames.zip`);setProgress(100);setStatus(`${times.length} frames exported.`);};
  const thumbnail=async()=>{const c=await frameAt(thumbTime),blob=await canvasBlob(c);download(blob,`${sanitizeMediaBaseName(primary!.file.name)}-${thumbTime.toFixed(2)}s.png`);setStatus('Thumbnail exported.');};
  const makeGif=async()=>{if(!primary)throw new Error('Choose a video first.');const duration=Math.min(primary.duration,Math.max(.5,Math.min(8,gifSeconds))),count=Math.max(2,Math.min(80,Math.round(duration*gifFps))),times=planVideoFrameTimes(primary.duration,count,0,duration),scale=Math.min(1,480/primary.width),w=Math.max(2,Math.round(primary.width*scale)),h=Math.max(2,Math.round(primary.height*scale)),frames=[] as {canvas:HTMLCanvasElement;delayMs:number}[];for(let i=0;i<times.length;i++){setProgress(Math.round(i/times.length*65));await seek(primary.video,times[i]);const c=document.createElement('canvas');c.width=w;c.height=h;c.getContext('2d')?.drawImage(primary.video,0,0,w,h);frames.push({canvas:c,delayMs:1000/gifFps});}const blob=encodeGif(frames,w,h,0,p=>setProgress(65+Math.round(p*.35)));download(blob,`${sanitizeMediaBaseName(primary.file.name)}.gif`);setProgress(100);setStatus(`${duration.toFixed(1)}s GIF · ${w}×${h}.`);};
  const run=async()=>{setBusy(true);setError('');setProgress(0);setStatus('Processing locally…');try{if(task.id==='video-to-audio')await extractAudio();else if(task.id==='video-to-frames')await extractFrames();else if(task.id==='video-thumbnail-extractor')await thumbnail();else if(task.id==='video-to-gif')await makeGif();else await renderVideo();}catch(e){setError(e instanceof Error?e.message:'Video processing failed.');setStatus('');}finally{setBusy(false);}};
  const startWebcam=async()=>{setError('');try{const stream=await navigator.mediaDevices.getUserMedia({video:true,audio:true});setWebcamStream(stream);requestAnimationFrame(()=>{if(webcamRef.current){webcamRef.current.srcObject=stream;void webcamRef.current.play();}});}catch{setError('Camera or microphone permission was denied or unavailable.');}};
  const startRecording=()=>{if(!webcamStream||!mimes[0])return;chunksRef.current=[];const recorder=new MediaRecorder(webcamStream,{mimeType:mimes[0]});recorderRef.current=recorder;recorder.ondataavailable=e=>{if(e.data.size)chunksRef.current.push(e.data);};recorder.onstop=()=>{const blob=new Blob(chunksRef.current,{type:mimes[0]});if(recorded)URL.revokeObjectURL(recorded.url);setRecorded({blob,url:URL.createObjectURL(blob)});};recorder.start(500);setRecording(true);};const stopRecording=()=>{if(recorderRef.current?.state!=='inactive')recorderRef.current?.stop();setRecording(false);};
  if(task.id==='webcam-video-recorder')return <ToolShell toolId={task.id} title={task.name} description={task.description} category="media" relatedToolIds={['screen-recorder','audio-recorder','webcam-test']}><div className="space-y-4">{error&&<div role="alert" className="rounded border border-red-200 bg-red-50 p-3 text-xs text-red-700">{error}</div>}<div className="overflow-hidden rounded-xl border bg-black"><video ref={webcamRef} muted playsInline className="mx-auto max-h-[520px] w-full"/></div><div className="flex flex-wrap gap-2">{!webcamStream&&<button onClick={()=>void startWebcam()} className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white"><Camera className="h-4 w-4"/>Enable camera</button>}{webcamStream&&!recording&&<button onClick={startRecording} className="rounded-lg bg-red-600 px-4 py-2 text-xs font-bold text-white">Start recording</button>}{recording&&<button onClick={stopRecording} className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-4 py-2 text-xs font-bold text-white"><Square className="h-4 w-4"/>Stop</button>}{recorded&&<button onClick={()=>download(recorded.blob,`webcam-recording.${mediaExtensionFromMime(recorded.blob.type)}`)} className="inline-flex items-center gap-2 rounded-lg border px-4 py-2 text-xs font-bold"><Download className="h-4 w-4"/>Download</button>}</div>{recorded&&<video controls src={recorded.url} className="w-full rounded-lg bg-black"/>}<p className="text-xs text-neutral-500">The output container is selected from MediaRecorder formats supported by this browser. Recording remains local.</p></div></ToolShell>;
  return <ToolShell toolId={task.id} title={task.name} description={task.description} category="media" relatedToolIds={['video-toolkit','audio-recorder','gif-maker']}><div className="space-y-5">
    <div className="rounded-xl border-2 border-dashed border-neutral-300 p-7 text-center dark:border-neutral-700"><Film className="mx-auto h-8 w-8 text-blue-600"/><p className="mt-2 text-sm font-semibold">Choose {multi?'video clips':'a video'}</p><label className="mt-3 inline-flex cursor-pointer items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-xs font-semibold text-white"><Upload className="h-4 w-4"/>Choose video<input className="hidden" type="file" accept="video/*" multiple={multi} onChange={e=>{void chooseVideos(e.target.files);e.target.value='';}}/></label><div className="mt-3 inline-flex items-center gap-1 text-[11px] text-emerald-700 dark:text-emerald-400"><ShieldCheck className="h-3.5 w-3.5"/>Local decode and processing.</div></div>
    {primary&&<><video controls src={primary.url} className="max-h-[480px] w-full rounded-xl bg-black"/><div className="grid gap-2 rounded-lg border p-3 text-xs sm:grid-cols-4"><span>{primary.width}×{primary.height}</span><span>{primary.duration.toFixed(2)}s</span><span>{files.length} clip{files.length===1?'':'s'}</span><span>{task.id==='loop-video'?`~${estimateLoopedDuration(primary.duration,loops,speed).toFixed(1)}s output`:files[0]?.type||'video'}</span></div></>}
    <section className="grid gap-3 rounded-xl border border-neutral-200 p-4 text-xs dark:border-neutral-800 sm:grid-cols-2">
      {['video-compressor','video-converter','merge-videos','add-audio-to-video','add-text-to-video','loop-video','add-logo-to-video','subtitle-burner','video-speed-changer','crop-resize-video','mute-video','video-volume-changer'].includes(task.id)&&<><label className="font-semibold">Output encoder<select value={mime} onChange={e=>setMime(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2">{mimes.map(m=><option key={m} value={m}>{m}</option>)}</select></label><label className="font-semibold">Quality<select value={quality} onChange={e=>setQuality(e.target.value as typeof quality)} className="mt-1 w-full rounded border bg-transparent px-3 py-2"><option value="compact">Compact</option><option value="balanced">Balanced</option><option value="high">High</option></select></label></>}
      {['video-compressor','crop-resize-video'].includes(task.id)&&<label className="font-semibold">Output size<select value={resolution} onChange={e=>setResolution(e.target.value as typeof resolution)} className="mt-1 w-full rounded border bg-transparent px-3 py-2"><option value="original">Original</option><option value="1080">1080-class</option><option value="720">720-class</option><option value="480">480-class</option></select></label>}
      {task.id==='crop-resize-video'&&<label className="font-semibold">Aspect<select value={aspect} onChange={e=>setAspect(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2"><option value="original">Original</option><option value="16:9">16:9</option><option value="9:16">9:16</option><option value="1:1">1:1</option><option value="4:5">4:5</option></select></label>}
      {['video-speed-changer','loop-video'].includes(task.id)&&<label className="font-semibold">Speed {speed.toFixed(2)}×<input className="mt-2 w-full" type="range" min=".5" max="2" step=".05" value={speed} onChange={e=>setSpeed(Number(e.target.value))}/></label>}
      {task.id==='loop-video'&&<label className="font-semibold">Repeats<input type="number" min="2" max="10" value={loops} onChange={e=>setLoops(Number(e.target.value))} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>}
      {task.id==='video-volume-changer'&&<label className="font-semibold">Source volume {Math.round(volume*100)}%<input className="mt-2 w-full" type="range" min="0" max="2" step=".05" value={volume} onChange={e=>setVolume(Number(e.target.value))}/></label>}
      {task.id==='add-text-to-video'&&<label className="font-semibold sm:col-span-2">Text<input value={overlayText} onChange={e=>setOverlayText(e.target.value)} className="mt-1 w-full rounded border bg-transparent px-3 py-2"/></label>}
      {task.id==='add-audio-to-video'&&<label className="font-semibold sm:col-span-2">Additional audio<input type="file" accept="audio/*" onChange={e=>setAudioFile(e.target.files?.[0]||null)} className="mt-1 block w-full"/><span className="mt-1 block text-neutral-500">The added track loops if shorter than the video and is mixed with source audio.</span></label>}
      {task.id==='add-logo-to-video'&&<label className="font-semibold sm:col-span-2">Logo / image<input type="file" accept="image/*" onChange={e=>setLogoFile(e.target.files?.[0]||null)} className="mt-1 block w-full"/></label>}
      {task.id==='subtitle-burner'&&<label className="font-semibold sm:col-span-2">SRT or WebVTT<textarea value={subtitleText} onChange={e=>setSubtitleText(e.target.value)} rows={7} placeholder="1\n00:00:01,000 --> 00:00:03,000\nSubtitle text" className="mt-1 w-full rounded border bg-transparent px-3 py-2 font-mono text-[11px]"/><input type="file" accept=".srt,.vtt,text/plain" onChange={e=>{const f=e.target.files?.[0];if(f)void f.text().then(setSubtitleText);}} className="mt-2 block w-full"/></label>}
      {task.id==='video-to-frames'&&<label className="font-semibold">Frames {frameCount}<input className="mt-2 w-full" type="range" min="2" max="60" value={frameCount} onChange={e=>setFrameCount(Number(e.target.value))}/></label>}
      {task.id==='video-thumbnail-extractor'&&<label className="font-semibold">Timestamp {thumbTime.toFixed(2)}s<input className="mt-2 w-full" type="range" min="0" max={primary?.duration||0} step=".05" value={thumbTime} onChange={e=>setThumbTime(Number(e.target.value))}/></label>}
      {task.id==='video-to-gif'&&<><label className="font-semibold">GIF seconds {gifSeconds.toFixed(1)}<input className="mt-2 w-full" type="range" min=".5" max={Math.min(8,primary?.duration||8)} step=".5" value={gifSeconds} onChange={e=>setGifSeconds(Number(e.target.value))}/></label><label className="font-semibold">GIF fps {gifFps}<input className="mt-2 w-full" type="range" min="4" max="15" value={gifFps} onChange={e=>setGifFps(Number(e.target.value))}/></label></>}
      {['merge-videos','video-compressor','video-converter','add-audio-to-video','add-text-to-video','loop-video','add-logo-to-video','subtitle-burner','video-speed-changer','crop-resize-video','mute-video','video-volume-changer'].includes(task.id)&&<p className="text-neutral-500 sm:col-span-2">Transformed video is encoded in real time. Keep this tab visible. Codec/container support is determined by MediaRecorder in this browser.</p>}
    </section>
    {error&&<div role="alert" className="rounded border border-red-200 bg-red-50 p-3 text-xs text-red-700 dark:border-red-900 dark:bg-red-950/20 dark:text-red-300">{error}</div>}{busy&&<div className="h-2 overflow-hidden rounded bg-neutral-200 dark:bg-neutral-800"><div className="h-full bg-blue-600" style={{width:`${progress}%`}}/></div>}
    <div className="flex flex-wrap items-center gap-3"><button disabled={!primary||busy||(multi&&loaded.length<2)||(task.id==='add-audio-to-video'&&!audioFile)||(task.id==='add-logo-to-video'&&!logoFile)||(task.id==='subtitle-burner'&&!subtitleText.trim())} onClick={()=>void run()} className="inline-flex items-center gap-2 rounded-lg bg-neutral-900 px-4 py-2 text-xs font-bold text-white disabled:opacity-40 dark:bg-neutral-100 dark:text-neutral-900">{busy?<Loader2 className="h-4 w-4 animate-spin"/>:<Download className="h-4 w-4"/>}Process & download</button>{busy&&<button onClick={()=>{cancelRef.current=true;setStatus('Cancelling…');}} className="rounded-lg border px-3 py-2 text-xs">Cancel</button>}{status&&<span className="text-xs text-neutral-500">{status}</span>}</div>
  </div></ToolShell>;
};
export default VideoMicroTools;
