import React,{useEffect,useRef,useState}from'react';
import{ArrowDown,ArrowUp,Copy,Download,Layers,Trash2,Upload}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyImageToClipboard}from'../../utilities/clipboard';
import{estimateStitchOverlapDetailed,renderStitchedCanvas,type StitchDirection,type StitchItem}from'../../utilities/screenshot-stitcher';
let idCounter=0;
export const ScreenshotStitcherTool:React.FC=()=>{
 const[items,setItems]=useState<StitchItem[]>([]);const[direction,setDirection]=useState<StitchDirection>('vertical');const[trim,setTrim]=useState(0);const[crossAxis,setCrossAxis]=useState<'preserve'|'fit-largest'>('preserve');const canvasRef=useRef<HTMLCanvasElement>(null),itemsRef=useRef<StitchItem[]>([]);
 useEffect(()=>{itemsRef.current=items;},[items]);useEffect(()=>()=>itemsRef.current.forEach(i=>i.img.src.startsWith('blob:')&&URL.revokeObjectURL(i.img.src)),[]);
 const enrich=(list:StitchItem[],dir=direction)=>list.map((item,index)=>{if(index===0)return{...item,overlapPx:0,overlapConfidence:1};const estimate=estimateStitchOverlapDetailed(list[index-1].img,item.img,dir);return{...item,overlapPx:estimate.overlapPx,overlapConfidence:estimate.confidence};});
 const add=async(files:FileList|File[])=>{const loaded=await Promise.all(Array.from(files).filter(f=>f.type.startsWith('image/')).map(file=>new Promise<StitchItem>((resolve,reject)=>{const u=URL.createObjectURL(file),img=new Image();img.onload=()=>resolve({id:`stitch-${Date.now()}-${++idCounter}`,file,img,width:img.naturalWidth,height:img.naturalHeight,overlapPx:0});img.onerror=()=>{URL.revokeObjectURL(u);reject(new Error('Image decode failed'));};img.src=u;})));setItems(prev=>enrich([...prev,...loaded]));};
 const recompute=(dir=direction)=>setItems(prev=>enrich(prev,dir));
 const move=(i:number,d:number)=>setItems(prev=>{const n=i+d;if(n<0||n>=prev.length)return prev;const copy=[...prev];[copy[i],copy[n]]=[copy[n],copy[i]];return enrich(copy);});
 const remove=(i:number)=>setItems(prev=>{const removed=prev[i];if(removed?.img.src.startsWith('blob:'))URL.revokeObjectURL(removed.img.src);return enrich(prev.filter((_,x)=>x!==i));});
 useEffect(()=>{if(!items.length||!canvasRef.current)return;const rendered=renderStitchedCanvas(items,direction,trim,'#fff',crossAxis);canvasRef.current.width=rendered.width;canvasRef.current.height=rendered.height;canvasRef.current.getContext('2d')?.drawImage(rendered,0,0);},[items,direction,trim,crossAxis]);
 const copy=()=>canvasRef.current?.toBlob(blob=>blob&&void copyImageToClipboard(blob),'image/png');const download=()=>canvasRef.current?.toBlob(blob=>{if(!blob)return;const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`stitched-${Date.now()}.png`;a.click();URL.revokeObjectURL(u);},'image/png');
 return <ToolShell toolId="screenshot-stitcher" title="Screenshot Stitcher" description="Join sequential screenshots with gradient-aware overlap detection, confidence scoring, manual correction, and cross-axis fitting." category="image" relatedToolIds={['image-annotator','image-optimizer','image-collage']}>
  <div className="space-y-5"><div className="flex flex-wrap gap-2"><label className="px-3 py-2 text-xs bg-blue-600 text-white rounded-lg cursor-pointer inline-flex gap-1"><Upload className="w-4 h-4"/>Add screenshots<input hidden multiple type="file" accept="image/*" onChange={e=>e.target.files&&void add(e.target.files)}/></label><button type="button" onClick={()=>{const next=direction==='vertical'?'horizontal':'vertical';setDirection(next);queueMicrotask(()=>recompute(next));}} className="px-3 py-2 text-xs border rounded-lg">Direction: {direction}</button><button type="button" onClick={()=>recompute()} className="px-3 py-2 text-xs border rounded-lg">Auto-match all</button></div>
   {!items.length?<div className="p-12 border-2 border-dashed rounded-xl text-center"><Layers className="mx-auto w-8 h-8 text-blue-500"/><p className="text-sm font-semibold mt-2">Add sequential screenshots</p></div>:<div className="grid lg:grid-cols-[360px_1fr] gap-5"><div className="space-y-3"><div className="max-h-[430px] overflow-auto space-y-2">{items.map((item,i)=><div key={item.id} className="border rounded-lg p-2"><div className="flex gap-2 items-center"><img src={item.img.src} alt={item.file.name} className="w-12 h-14 object-cover rounded"/><div className="min-w-0 flex-1"><div className="text-xs font-semibold truncate">#{i+1} {item.file.name}</div><div className="text-[10px] text-neutral-500">{item.width}×{item.height}</div>{i>0&&<div className="text-[10px] mt-1">confidence <strong className={(item.overlapConfidence||0)>=.55?'text-emerald-600':(item.overlapConfidence||0)>=.25?'text-amber-600':'text-red-600'}>{Math.round((item.overlapConfidence||0)*100)}%</strong> · overlap {item.overlapPx}px</div>}</div><button disabled={!i} onClick={()=>move(i,-1)}><ArrowUp className="w-3 h-3"/></button><button disabled={i===items.length-1} onClick={()=>move(i,1)}><ArrowDown className="w-3 h-3"/></button><button onClick={()=>remove(i)}><Trash2 className="w-3 h-3 text-red-500"/></button></div>{i>0&&<input aria-label={`Overlap ${i}`} className="w-full mt-2" type="range" min={0} max={Math.min(600,(direction==='vertical'?item.height:item.width)-1)} value={item.overlapPx} onChange={e=>setItems(prev=>prev.map((x,index)=>index===i?{...x,overlapPx:Number(e.target.value),overlapConfidence:0}:x))}/>}</div>)}</div><div className="p-3 border rounded-lg space-y-2"><label className="text-xs">Trim cross-axis {trim}px<input className="w-full" type="range" min={0} max={100} value={trim} onChange={e=>setTrim(Number(e.target.value))}/></label><label className="text-xs">Fit cross-axis <select value={crossAxis} onChange={e=>setCrossAxis(e.target.value as 'preserve'|'fit-largest')} className="block w-full mt-1 p-1.5 border rounded bg-white dark:bg-neutral-900"><option value="preserve">Preserve source pixels</option><option value="fit-largest">Fit to largest cross-axis</option></select></label><p className="text-[10px] text-neutral-500">Low confidence is deliberately surfaced instead of silently trusting a weak seam match.</p></div></div><div><div className="border rounded-xl bg-neutral-100 dark:bg-neutral-950 p-2 overflow-auto max-h-[650px]"><canvas ref={canvasRef} className="max-w-full h-auto mx-auto"/></div><div className="flex gap-2 mt-3"><button onClick={copy} className="px-3 py-2 text-xs border rounded inline-flex gap-1"><Copy className="w-3 h-3"/>Copy</button><button onClick={download} className="px-3 py-2 text-xs bg-emerald-600 text-white rounded inline-flex gap-1"><Download className="w-3 h-3"/>Download</button></div></div></div>}
  </div>
 </ToolShell>;
};
export default ScreenshotStitcherTool;
