export const STRICT_S_TIER_TARGETS = [
  'refresh-rate-test',
  'touchscreen-test',
  'polling-rate-test',
  'keyboard-ghosting-test',
  'battery-status',
  'basic-calculator',
  'average-calculator',
  'tip-calculator',
  'bill-splitter',
  'simple-interest-calculator',
  'room-area-calculator',
  'paint-calculator',
  'flooring-calculator',
  'tile-calculator',
  'box-volume-calculator',
  'tar-pack',
  'tar-extract',
  'gzip-compress',
  'gzip-decompress',
  'reverse-audio',
  'stereo-mono-converter',
  'loop-video',
  'mute-video',
  'video-volume-changer',
  'text-repeater',
  'text-reverser',
  'lorem-ipsum-generator',
  'reading-plan-divider',
  'pwa-manifest-generator',
  'number-words-converter',
  'habit-consistency-tracker',
  'currency-converter',
] as const;

export type StrictSTierTarget = typeof STRICT_S_TIER_TARGETS[number];
export const STRICT_S_TIER_TARGET_SET = new Set<string>(STRICT_S_TIER_TARGETS);
