import React,{useEffect,useRef,useState}from'react';
import{Copy,Download,LayoutGrid,RotateCw,Trash2,Upload}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyImageToClipboard}from'../../utilities/clipboard';
import{calculateCellRects,calculateGridDimensions,renderCollageToCanvas,type AspectRatioPreset,type CollageConfig,type CollageItem,type CollageLayoutType}from'../../utilities/image-collage';
export const ImageCollageTool:React.FC=()=>{
 const[items,setItems]=useState<CollageItem[]>([]);const[selected,setSelected]=useState(0);const[config,setConfig]=useState<CollageConfig>({layout:'auto',customRows:2,customCols:2,aspectPreset:'auto',targetWidth:1600,targetHeight:1000,gap:12,padding:16,borderRadius:8,backgroundColor:'#0f172a',format:'image/png',quality:.92});const canvasRef=useRef<HTMLCanvasElement>(null),itemsRef=useRef<CollageItem[]>([]);
 useEffect(()=>{itemsRef.current=items;},[items]);useEffect(()=>()=>itemsRef.current.forEach(i=>i.dataUrl.startsWith('blob:')&&URL.revokeObjectURL(i.dataUrl)),[]);
 const add=(files:FileList|File[])=>Array.from(files).filter(f=>f.type.startsWith('image/')).slice(0,20-items.length).forEach(file=>{const url=URL.createObjectURL(file),img=new Image();img.onload=()=>setItems(prev=>[...prev,{id:`item-${Date.now()}-${Math.random()}`,blob:file,dataUrl:url,imgElement:img,filename:file.name,naturalWidth:img.naturalWidth,naturalHeight:img.naturalHeight,fitMode:'cover',offsetX:.5,offsetY:.5,zoom:1,rotation:0,caption:''}]);img.onerror=()=>URL.revokeObjectURL(url);img.src=url;});
 useEffect(()=>{if(canvasRef.current&&items.length)renderCollageToCanvas(canvasRef.current,items,config);},[items,config]);
 const update=(patch:Partial<CollageItem>)=>setItems(prev=>prev.map((item,i)=>i===selected?{...item,...patch}:item));
 const remove=(index:number)=>setItems(prev=>{const item=prev[index];if(item?.dataUrl.startsWith('blob:'))URL.revokeObjectURL(item.dataUrl);return prev.filter((_,i)=>i!==index);});
 const copy=()=>canvasRef.current?.toBlob(blob=>blob&&void copyImageToClipboard(blob),'image/png');const download=()=>canvasRef.current?.toBlob(blob=>{if(!blob)return;const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`collage-${Date.now()}.png`;a.click();URL.revokeObjectURL(u);},config.format,config.quality);
 const grid=calculateGridDimensions(config.layout,items.length,config.customRows,config.customCols),previewRects=calculateCellRects(grid,items.length,1200,800,config.gap,config.padding);
 return <ToolShell toolId="image-collage" title="Image Collage Maker" description="High-resolution local collage editor with centered partial rows, rotation, captions, crop focus and export controls." category="image" relatedToolIds={['image-optimizer','image-annotator','background-remover']}>
  <div className="space-y-5"><div className="flex flex-wrap gap-2 items-center"><label className="px-3 py-2 text-xs bg-blue-600 text-white rounded-lg cursor-pointer inline-flex gap-1"><Upload className="w-4 h-4"/>Add images<input hidden multiple type="file" accept="image/*" onChange={e=>e.target.files&&add(e.target.files)}/></label><select value={config.layout} onChange={e=>setConfig(c=>({...c,layout:e.target.value as CollageLayoutType}))} className="p-2 text-xs border rounded bg-white dark:bg-neutral-900"><option value="auto">Auto grid</option><option value="2-horizontal">Side by side</option><option value="2-vertical">Stacked</option><option value="before-after">Before / After</option><option value="2x2">2×2</option><option value="3x3">3×3</option><option value="h-strip">Horizontal strip</option><option value="v-strip">Vertical strip</option><option value="custom">Custom</option></select><select value={config.aspectPreset} onChange={e=>setConfig(c=>({...c,aspectPreset:e.target.value as AspectRatioPreset}))} className="p-2 text-xs border rounded bg-white dark:bg-neutral-900"><option value="auto">Auto aspect</option><option value="1:1">1:1</option><option value="4:3">4:3</option><option value="16:9">16:9</option><option value="9:16">9:16</option></select><label className="text-xs">Gap <input type="range" min={0} max={60} value={config.gap} onChange={e=>setConfig(c=>({...c,gap:Number(e.target.value)}))}/></label></div>
   {!items.length?<div className="p-12 text-center border-2 border-dashed rounded-xl"><LayoutGrid className="w-8 h-8 mx-auto text-blue-500"/><p className="text-sm font-semibold mt-2">Drop or add up to 20 images</p><p className="text-xs text-neutral-500">Layouts are rendered locally at export resolution.</p></div>:<div className="grid lg:grid-cols-[320px_1fr] gap-5"><div className="space-y-3"><div className="grid grid-cols-3 gap-2 max-h-72 overflow-auto">{items.map((item,i)=><button key={item.id} onClick={()=>setSelected(i)} className={`relative rounded border overflow-hidden ${selected===i?'ring-2 ring-blue-500':''}`}><img src={item.dataUrl} alt={item.filename} className="w-full h-20 object-cover"/><span className="absolute bottom-0 inset-x-0 bg-black/60 text-white text-[9px] truncate p-1">{item.filename}</span></button>)}</div>{items[selected]&&<div className="p-3 border rounded-xl space-y-2"><div className="flex justify-between text-xs font-semibold"><span>Edit image {selected+1}</span><button onClick={()=>remove(selected)}><Trash2 className="w-4 h-4 text-red-500"/></button></div><button type="button" onClick={()=>update({rotation:((((items[selected].rotation||0)+90)%360) as 0|90|180|270)})} className="w-full border rounded p-1.5 text-xs"><RotateCw className="inline w-3 h-3"/> rotation {items[selected].rotation||0}°</button><label className="text-xs">Zoom {items[selected].zoom.toFixed(1)}×<input className="w-full" type="range" min={1} max={4} step={.1} value={items[selected].zoom} onChange={e=>update({zoom:Number(e.target.value)})}/></label><label className="text-xs">Horizontal focus<input className="w-full" type="range" min={0} max={1} step={.01} value={items[selected].offsetX} onChange={e=>update({offsetX:Number(e.target.value)})}/></label><label className="text-xs">Vertical focus<input className="w-full" type="range" min={0} max={1} step={.01} value={items[selected].offsetY} onChange={e=>update({offsetY:Number(e.target.value)})}/></label><label className="text-xs">caption<input value={items[selected].caption||''} onChange={e=>update({caption:e.target.value})} className="block w-full mt-1 p-2 border rounded bg-white dark:bg-neutral-900"/></label></div>}<div className="p-2 rounded bg-neutral-50 dark:bg-neutral-950 text-[11px] text-neutral-500"><strong>Centered last row:</strong> partial auto-grid rows are centered instead of pinned to the left. Current preview plan: {previewRects.length} cells.</div></div><div className="min-w-0"><div className="p-3 bg-neutral-100 dark:bg-neutral-950 border rounded-xl overflow-auto"><canvas ref={canvasRef} className="max-w-full h-auto mx-auto"/></div><div className="flex gap-2 mt-3"><button onClick={copy} className="px-3 py-2 text-xs border rounded-lg inline-flex gap-1"><Copy className="w-3 h-3"/>Copy</button><button onClick={download} className="px-3 py-2 text-xs bg-emerald-600 text-white rounded-lg inline-flex gap-1"><Download className="w-3 h-3"/>Download</button></div></div></div>}
  </div>
 </ToolShell>;
};
export default ImageCollageTool;
