import React,{useMemo,useState}from'react';
import{Check,Copy}from'lucide-react';
import{ToolShell}from'../../components/tool-shell/ToolShell';
import{copyToClipboard}from'../../utilities/clipboard';
import{decodeHtmlEntitiesBasic,encodeHtmlEntities,entityReference,entityStats,type HtmlEntityEncoding,type HtmlEntityScope}from'../../utilities/s-tier-html-entities';

const inputClass='mt-1 w-full rounded-lg border border-neutral-300 bg-white px-3 py-2 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-500/20 dark:border-neutral-700 dark:bg-neutral-950';
function browserDecode(value:string){if(typeof document==='undefined')return decodeHtmlEntitiesBasic(value);const textarea=document.createElement('textarea');textarea.innerHTML=value;return textarea.value;}
export default function HtmlEntityStudio({initialText=''}:{initialText?:string}){
 const[direction,setDirection]=useState<'encode'|'decode'>('encode'),[input,setInput]=useState(initialText||'<p title="Tom & Jerry">Café — 50% © 2026</p>'),[encoding,setEncoding]=useState<HtmlEntityEncoding>('named'),[scope,setScope]=useState<HtmlEntityScope>('special'),[preserve,setPreserve]=useState(true),[copied,setCopied]=useState(false);
 const output=useMemo(()=>direction==='encode'?encodeHtmlEntities(input,{encoding,scope,preserveExisting:preserve}):browserDecode(input),[direction,input,encoding,scope,preserve]);const stats=entityStats(output);const reference=entityReference();
 const copy=async()=>{if(await copyToClipboard(output)){setCopied(true);setTimeout(()=>setCopied(false),1200)}};
 return<ToolShell toolId="html-entity-converter" title="HTML Entity Converter" description="Encode or decode HTML entities with named, decimal, or hexadecimal output, selectable encoding scope, preservation controls, live statistics, and a character reference." category="developer" relatedToolIds={['html-minifier','unicode-inspector','text-hex-converter']} outputToTransfer={output}><div className="space-y-5">
  <div className="rounded-xl border border-blue-200 bg-blue-50 p-3 text-xs leading-5 text-blue-900 dark:border-blue-900 dark:bg-blue-950/20 dark:text-blue-200">Decode uses the browser’s HTML parser, so standard HTML named entities are recognized beyond the built-in quick-reference table. Encoding operates locally and never executes the input as markup.</div>
  <div className="flex flex-wrap items-end gap-3"><div className="inline-flex rounded-lg border border-neutral-300 p-1 dark:border-neutral-700">{(['encode','decode']as const).map(v=><button key={v} type="button" aria-pressed={direction===v} onClick={()=>setDirection(v)} className={`rounded-md px-3 py-1.5 text-sm font-semibold ${direction===v?'bg-neutral-900 text-white dark:bg-neutral-100 dark:text-neutral-900':''}`}>{v==='encode'?'Encode':'Decode'}</button>)}</div>{direction==='encode'&&<><Select label="Encoding" value={encoding} set={v=>setEncoding(v as HtmlEntityEncoding)} options={[['named','Named when available'],['decimal','Decimal numeric'],['hex','Hex numeric']]}/><Select label="Encode scope" value={scope} set={v=>setScope(v as HtmlEntityScope)} options={[['special','HTML specials only'],['non-ascii','Specials + non-ASCII'],['all','All non-whitespace characters']]}/><label className="mb-2 flex items-center gap-2 text-xs"><input type="checkbox" checked={preserve} onChange={e=>setPreserve(e.target.checked)}/> Preserve existing entities</label></>}</div>
  <div className="grid gap-4 lg:grid-cols-2"><Area label="Input" value={input} set={setInput}/><section><div className="mb-1 flex items-center justify-between"><span className="text-xs font-semibold">Output</span><button type="button" onClick={()=>void copy()} disabled={!output} className="inline-flex items-center gap-1 rounded-lg border border-neutral-300 px-2.5 py-1.5 text-xs font-semibold disabled:opacity-40 dark:border-neutral-700">{copied?<Check className="h-3.5 w-3.5"/>:<Copy className="h-3.5 w-3.5"/>}{copied?'Copied':'Copy'}</button></div><textarea aria-label="HTML entity output" readOnly rows={12} value={output} className="w-full resize-y rounded-lg border border-neutral-300 bg-neutral-50 p-3 font-mono text-sm dark:border-neutral-700 dark:bg-neutral-950"/></section></div>
  <div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Entities" value={stats.entities}/><Metric label="Named" value={stats.named}/><Metric label="Numeric" value={stats.numeric}/><Metric label="Unique" value={stats.unique}/></div>
  <details className="rounded-xl border border-neutral-200 p-4 dark:border-neutral-800"><summary className="cursor-pointer text-sm font-bold">Common entity reference</summary><div className="mt-3 overflow-auto"><table className="w-full min-w-[34rem] text-xs"><thead><tr className="text-left text-neutral-500"><th className="p-2">Character</th><th className="p-2">Named</th><th className="p-2">Decimal</th><th className="p-2">Hex</th></tr></thead><tbody>{reference.map(row=><tr key={row.name} className="border-t border-neutral-200 dark:border-neutral-800"><td className="p-2 text-lg">{row.char==='\u00a0'?'NBSP':row.char}</td><td className="p-2 font-mono">{row.name}</td><td className="p-2 font-mono">{row.decimal}</td><td className="p-2 font-mono">{row.hex}</td></tr>)}</tbody></table></div></details>
 </div></ToolShell>
}
function Area({label,value,set}:{label:string;value:string;set:(v:string)=>void}){return<label className="block text-xs font-semibold">{label}<textarea aria-label={label} rows={12} value={value} onChange={e=>set(e.target.value)} className={`${inputClass} resize-y font-mono`}/></label>}
function Select({label,value,set,options}:{label:string;value:string;set:(v:string)=>void;options:string[][]}){return<label className="min-w-44 text-xs font-semibold">{label}<select aria-label={label} value={value} onChange={e=>set(e.target.value)} className={inputClass}>{options.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}
function Metric({label,value}:{label:string;value:number}){return<div className="rounded-lg border border-neutral-200 p-3 dark:border-neutral-800"><div className="text-[10px] font-semibold uppercase tracking-wide text-neutral-500">{label}</div><div className="mt-1 text-lg font-bold">{value.toLocaleString()}</div></div>}
