import type{ProMetric}from'./calculatorSpecs';
const r=(n:number,d=2)=>Number(n.toFixed(d));
const metric=(label:string,value:string|number,note?:string):ProMetric=>({label,value:String(value),note});
const words=(s:string)=>s.trim()?s.trim().split(/\s+/u):[];
const lines=(s:string)=>s.replace(/\r/g,'').split('\n');
const graphemes=(s:string)=>typeof Intl!=='undefined'&&'Segmenter'in Intl?[...new Intl.Segmenter(undefined,{granularity:'grapheme'}).segment(s)].map(x=>x.segment):Array.from(s);
const utf8=(s:string)=>new TextEncoder().encode(s).length;
const unique=<T,>(v:T[])=>new Set(v).size;
const entropy=(s:string)=>{if(!s)return 0;const counts=new Map<string,number>();for(const ch of graphemes(s))counts.set(ch,(counts.get(ch)||0)+1);const n=[...counts.values()].reduce((a,b)=>a+b,0);return[...counts.values()].reduce((sum,c)=>{const p=c/n;return sum-p*Math.log2(p)},0)*n};
const parseNums=(s:string)=>s.split(/[\s,;]+/).map(Number).filter(Number.isFinite);
const mean=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0;
const std=(v:number[])=>{const m=mean(v);return Math.sqrt(mean(v.map(x=>(x-m)**2)))};
const pct=(n:number)=>`${r(n,2)}%`;
const safeJson=(s:string)=>{try{return JSON.parse(s)}catch{return null}};
const hex=(n:number)=>Math.max(0,Math.floor(n)).toString(16).toUpperCase();

export function analyzeTextStudy(id:string,text:string,aux=3):ProMetric[]{const ws=words(text),ls=lines(text),gs=graphemes(text),lower=ws.map(w=>w.toLocaleLowerCase()),freq=new Map<string,number>();for(const w of lower)freq.set(w,(freq.get(w)||0)+1);const top=[...freq.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5);const n=Math.max(1,Math.round(aux));switch(id){
case'ngram-analyzer':{const grams:string[]=[];for(let i=0;i<=lower.length-n;i++)grams.push(lower.slice(i,i+n).join(' '));const f=new Map<string,number>();grams.forEach(g=>f.set(g,(f.get(g)||0)+1));const best=[...f.entries()].sort((a,b)=>b[1]-a[1]).slice(0,5);return[metric(`${n}-grams`,grams.length),metric('Unique n-grams',f.size),metric('Repeated n-grams',[...f.values()].filter(x=>x>1).length),metric('Top n-gram',best[0]?`${best[0][0]} ×${best[0][1]}`:'—'),metric('Lexical diversity',pct(ws.length?unique(lower)/ws.length*100:0)),metric('UTF-8 bytes',utf8(text))]}
case'text-pattern-extractor':{const emails=text.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g)||[],urls=text.match(/https?:\/\/[^\s<>()]+/g)||[],nums=text.match(/[+-]?(?:\d+\.?\d*|\.\d+)/g)||[],dates=text.match(/\b\d{4}-\d{2}-\d{2}\b/g)||[];return[metric('Email-like tokens',emails.length),metric('URLs',urls.length),metric('Numbers',nums.length),metric('ISO dates',dates.length),metric('Unique extracted tokens',unique([...emails,...urls,...nums,...dates])),metric('Lines with a match',ls.filter(line=>/[\d@]|https?:\/\//.test(line)).length)]}
case'duplicate-phrase-finder':{const size=Math.max(2,n),m=new Map<string,number>();for(let i=0;i<=lower.length-size;i++){const p=lower.slice(i,i+size).join(' ');m.set(p,(m.get(p)||0)+1)}const dup=[...m.entries()].filter(([,c])=>c>1).sort((a,b)=>b[1]-a[1]);return[metric('Phrase size',`${size} words`),metric('Duplicate phrases',dup.length),metric('Most repeated',dup[0]?`${dup[0][0]} ×${dup[0][1]}`:'—'),metric('Repeated phrase occurrences',dup.reduce((a,[,c])=>a+c,0)),metric('Coverage estimate',pct(ws.length?dup.reduce((a,[p,c])=>a+p.split(' ').length*c,0)/ws.length*100:0)),metric('Unique words',unique(lower))]}
case'text-similarity-checker':{const halves=text.split(/\n---+\n/);const a=new Set(words(halves[0]||'').map(x=>x.toLowerCase())),b=new Set(words(halves[1]||'').map(x=>x.toLowerCase()));const inter=[...a].filter(x=>b.has(x)).length,union=new Set([...a,...b]).size;return[metric('Segment A unique words',a.size),metric('Segment B unique words',b.size),metric('Shared unique words',inter),metric('Jaccard similarity',pct(union?inter/union*100:0)),metric('Cosine-like overlap',pct(a.size&&b.size?inter/Math.sqrt(a.size*b.size)*100:0)),metric('Delimiter detected',halves.length>1?'Yes':'No — separate texts with a line containing ---')]}
case'text-wrapper':{const width=Math.max(10,n*10),wrapped: string[]=[];for(const line of ls){let current='';for(const word of words(line)){if((current+' '+word).trim().length>width&&current){wrapped.push(current);current=word}else current=(current+' '+word).trim()}wrapped.push(current)}return[metric('Wrap width',`${width} chars`),metric('Source lines',ls.length),metric('Wrapped lines',wrapped.length),metric('Longest wrapped line',Math.max(0,...wrapped.map(x=>x.length))),metric('Hard-overflow words',ws.filter(w=>w.length>width).length),metric('Preview',wrapped.slice(0,3).join(' / '))]}
case'whitespace-visualizer':{const spaces=(text.match(/ /g)||[]).length,tabs=(text.match(/\t/g)||[]).length,nbsp=(text.match(/\u00a0/g)||[]).length,zw=(text.match(/[\u200b-\u200d\ufeff]/g)||[]).length,trailing=ls.filter(x=>/[ \t]+$/.test(x)).length;return[metric('Spaces',spaces),metric('Tabs',tabs),metric('NBSP',nbsp),metric('Zero-width / BOM',zw),metric('Lines with trailing whitespace',trailing),metric('Mixed line endings',/\r\n/.test(text)&&/(^|[^\r])\n/.test(text)?'Yes':'No')]}
case'markdown-to-plain-text':{const headings=(text.match(/^#{1,6}\s+/gm)||[]).length,links=(text.match(/\[[^\]]+\]\([^)]+\)/g)||[]).length,code=(text.match(/```[\s\S]*?```|`[^`]+`/g)||[]).length,plain=text.replace(/```[\s\S]*?```/g,'').replace(/`([^`]+)`/g,'$1').replace(/!?(\[([^\]]*)\])\([^)]+\)/g,'$2').replace(/^#{1,6}\s+/gm,'').replace(/[*_~>-]/g,'');return[metric('Headings removed',headings),metric('Links/images normalized',links),metric('Code spans/blocks',code),metric('Plain words',words(plain).length),metric('Plain UTF-8 bytes',utf8(plain)),metric('Size reduction',pct(text.length?(1-plain.length/text.length)*100:0))]}
case'cloze-deletion-trainer':{const clozes=[...text.matchAll(/\{\{c\d+::(.*?)(?:::(.*?))?\}\}/g)];return[metric('Cloze deletions',clozes.length),metric('Distinct cloze indices',unique([...text.matchAll(/\{\{c(\d+)::/g)].map(m=>m[1]))),metric('Hints present',clozes.filter(m=>m[2]).length),metric('Average answer length',r(mean(clozes.map(m=>graphemes(m[1]).length)),1)),metric('Longest answer',Math.max(0,...clozes.map(m=>graphemes(m[1]).length))),metric('Cards implied',unique([...text.matchAll(/\{\{c(\d+)::/g)].map(m=>m[1]))||0)]}
case'memorization-trainer':{const chunks=ls.filter(x=>x.trim()),lens=chunks.map(x=>words(x).length);return[metric('Memorization chunks',chunks.length),metric('Words',ws.length),metric('Average words/chunk',r(mean(lens),1)),metric('Longest chunk',Math.max(0,...lens)),metric('Estimated 120 wpm recitation',`${r(ws.length/120,2)} min`),metric('Recommended first-pass chunks',Math.max(1,Math.ceil(ws.length/35)))]}
case'self-test-maker':{const questions=ls.filter(x=>/\?$/.test(x.trim())||/^q[:.)\s]/i.test(x.trim())),answers=ls.filter(x=>/^a[:.)\s]/i.test(x.trim()));return[metric('Question-like lines',questions.length),metric('Answer-like lines',answers.length),metric('Q/A balance',questions.length?`${r(answers/questions.length,2)} answers/question`:'—'),metric('Unpaired question estimate',Math.max(0,questions.length-answers.length)),metric('Average question words',r(mean(questions.map(x=>words(x).length)),1)),metric('Total study words',ws.length)]}
case'study-session-planner':{const topics=ls.filter(x=>x.trim()),minutes=Math.max(5,n*15),per=topics.length?minutes/topics.length:0;return[metric('Topics',topics.length),metric('Session budget',`${minutes} min`),metric('Minutes/topic',r(per,1)),metric('Recall block',`${r(minutes*.45,0)} min`),metric('Practice block',`${r(minutes*.4,0)} min`),metric('Review block',`${r(minutes*.15,0)} min`)]}
default:return[metric('Words',ws.length),metric('Characters',gs.length),metric('Unique words',unique(lower)),metric('Lines',ls.length),metric('Entropy',r(entropy(text),2)),metric('UTF-8 bytes',utf8(text))]}}

export function analyzeVisual(id:string,w:number,h:number,param=20):ProMetric[]{w=Math.max(1,w);h=Math.max(1,h);param=Math.max(0,param);const pixels=w*h,ratio=w/h,scaled=Math.max(.01,param/100),sw=Math.max(1,Math.round(w*scaled)),sh=Math.max(1,Math.round(h*scaled));switch(id){
case'aspect-ratio-calculator':return[metric('Aspect ratio',r(ratio,6)),metric('Pixel count',pixels.toLocaleString()),metric(`${param}% width`,sw),metric(`${param}% height`,sh),metric('Landscape/portrait',w===h?'Square':w>h?'Landscape':'Portrait'),metric('16:9 crop height',Math.round(w*9/16))];
case'image-collage':return[metric('Canvas pixels',pixels.toLocaleString()),metric('2×2 cell',`${Math.floor(w/2)}×${Math.floor(h/2)}`),metric('3×3 cell',`${Math.floor(w/3)}×${Math.floor(h/3)}`),metric('4 px gaps consumed','12 px across 4 columns'),metric('Print @300dpi',`${r(w/300,2)}×${r(h/300,2)} in`),metric('Approx RGBA memory',`${r(pixels*4/1048576,2)} MiB`)];
case'image-grid-splitter':{const n=Math.max(1,Math.round(param/10));return[metric('Grid',`${n}×${n}`),metric('Tile size',`${Math.floor(w/n)}×${Math.floor(h/n)}`),metric('Tiles',n*n),metric('Remainder X',w%n),metric('Remainder Y',h%n),metric('Tile pixels',Math.floor(w/n)*Math.floor(h/n))]}
case'profile-picture-maker':case'headshot-cropper':{const side=Math.min(w,h),removed=1-side*side/pixels;return[metric('Square crop',`${side}×${side}`),metric('Pixels retained',`${r((1-removed)*100,1)}%`),metric('Pixels removed',`${r(removed*100,1)}%`),metric('512px scale',`${r(512/side,3)}×`),metric('1024px scale',`${r(1024/side,3)}×`),metric('Safe face-zone diameter',`${Math.round(side*.72)} px`)]}
case'favicon-maker':return[metric('Source aspect',r(ratio,4)),metric('16×16 scale',`${r(16/w,5)}×`),metric('32×32 scale',`${r(32/w,5)}×`),metric('180×180 scale',`${r(180/w,5)}×`),metric('512×512 scale',`${r(512/w,5)}×`),metric('Square padding needed',`${Math.abs(w-h)} px`)]
case'dpi-print-size-calculator':{const dpi=Math.max(36,param*10);return[metric('DPI',dpi),metric('Print width',`${r(w/dpi,2)} in`),metric('Print height',`${r(h/dpi,2)} in`),metric('Print width',`${r(w/dpi*2.54,2)} cm`),metric('Megapixels',r(pixels/1e6,2)),metric('300dpi suitability',w>=1800&&h>=1200?'Strong for common small prints':'Check target print size') ]}
case'css-gradient-generator':return[metric('Angle',`${param%361}°`),metric('Stop midpoint',`${r(param%101,0)}%`),metric('Canvas ratio',r(ratio,4)),metric('Suggested CSS',`linear-gradient(${param%361}deg, var(--a), var(--b))`),metric('Preview pixels',pixels.toLocaleString()),metric('Fallback','solid var(--a)')];
case'box-shadow-generator':return[metric('Blur radius',`${param}px`),metric('Spread suggestion',`${r(param*.25,1)}px`),metric('Y offset',`${r(param*.35,1)}px`),metric('Soft shadow',`0 ${r(param*.35,1)}px ${param}px rgba(0,0,0,.18)`),metric('Element ratio',r(ratio,3)),metric('Shadow budget',`${r(param/Math.min(w,h)*100,2)}% of short side`)];
case'color-blindness-simulator':return[metric('Preview size',`${w}×${h}`),metric('Pixels inspected',pixels.toLocaleString()),metric('Severity scenario',`${Math.min(100,param)}%`),metric('Independent cue reminder','Do not encode state by color alone'),metric('Contrast check','Run text/background pairs through WCAG contrast'),metric('Export recommendation','Keep original + simulated comparison')];
case'color-palette-generator':return[metric('Requested swatches',Math.max(2,Math.round(param/5))),metric('Reference canvas',`${w}×${h}`),metric('Harmony rotation',`${param%360}°`),metric('Complement angle',`${(param+180)%360}°`),metric('Triad angles',`${param%360}° / ${(param+120)%360}° / ${(param+240)%360}°`),metric('Accessibility reminder','Validate every text/background pair')];
default:return[metric('Source dimensions',`${w}×${h}`),metric('Pixels',pixels.toLocaleString()),metric('Megapixels',r(pixels/1e6,2)),metric('Aspect ratio',r(ratio,5)),metric(`${param}% scale`,`${sw}×${sh}`),metric('RGBA working memory',`${r(pixels*4/1048576,2)} MiB`)]}}

export function analyzeMedia(id:string,duration:number,start:number,end:number,param=1):ProMetric[]{duration=Math.max(.001,duration);start=Math.max(0,Math.min(duration,start));end=Math.max(start,Math.min(duration,end));const segment=end-start,speed=Math.max(.05,param),fps=30,frames=Math.round(segment*fps);switch(id){
case'text-to-speech':return[metric('Text-rate scenario',`${r(param*160,0)} words/min`),metric('1,000-word duration',`${r(1000/(param*160),2)} min`),metric('5,000-word duration',`${r(5000/(param*160),2)} min`),metric('Playback speed',`${r(param,2)}×`),metric('Pause budget suggestion','Add punctuation pauses for long-form listening'),metric('Accessibility note','Voice availability and quality depend on the browser/OS')];
case'audio-speed-changer':case'video-speed-changer':return[metric('Selected segment',`${r(segment,3)} s`),metric('Speed factor',`${r(speed,2)}×`),metric('Result duration',`${r(segment/speed,3)} s`),metric('Duration change',pct((segment/speed/segment-1)*100)),metric('30fps source frames',frames),metric('Audio pitch policy','Choose time-stretch vs resample explicitly')];
case'audio-volume-changer':case'video-volume-changer':{const gainDb=param*6-6,gain=10**(gainDb/20);return[metric('Gain',`${r(gainDb,2)} dB`),metric('Linear multiplier',r(gain,4)),metric('Selected duration',`${r(segment,2)} s`),metric('Peak clipping risk',gain>1?'Higher — normalize/limit after gain':'Not increased by gain'),metric('Silence unaffected','Yes'),metric('Export check','Compare peak and loudness before/after')]}
case'silence-trimmer':{const threshold=-Math.abs(param*30);return[metric('Threshold scenario',`${r(threshold,1)} dBFS`),metric('Input duration',`${r(duration,2)} s`),metric('Candidate scan window',`${r(segment,2)} s`),metric('Suggested hold',`${r(Math.max(.05,.2/Math.max(.1,param)),2)} s`),metric('Boundary fade','5–20 ms to prevent clicks'),metric('Preserve ambience','Avoid aggressive trim on noisy recordings') ]}
case'audio-equalizer':return[metric('Gain scenario',`${r((param-1)*12,1)} dB`),metric('Low band','80–200 Hz'),metric('Presence band','2–5 kHz'),metric('Air band','8–14 kHz'),metric('Headroom reserve',`${r(Math.max(0,(param-1)*-6+3),1)} dB`),metric('A/B recommendation','Level-match before judging EQ')];
case'audio-noise-cleanup':return[metric('Reduction strength',pct(Math.min(100,param*50))),metric('Noise-profile window',`${r(Math.min(2,segment*.1),2)} s`),metric('Selected duration',`${r(segment,2)} s`),metric('Artifact guard','Prefer several light passes to one extreme pass'),metric('Speech check','Verify consonants and room tone after reduction'),metric('Export check','Listen at normal and boosted volume')];
case'ringtone-maker':return[metric('Clip duration',`${r(segment,2)} s`),metric('30-second limit',segment<=30?'Within common limit':'Longer than common ringtone target'),metric('Fade-in',`${r(Math.min(.25,segment*.03),2)} s`),metric('Fade-out',`${r(Math.min(.5,segment*.05),2)} s`),metric('Loop seam','Compare first/last 100 ms'),metric('Suggested loudness','Keep headroom; avoid hard clipping')];
case'video-to-frames':return[metric('Selected duration',`${r(segment,2)} s`),metric('Frame rate scenario',`${r(param*10,1)} fps`),metric('Frames to export',Math.ceil(segment*param*10)),metric('30fps source frames',frames),metric('Interval',`${r(1/(param*10),4)} s`),metric('Storage warning','PNG sequences grow quickly; estimate before batch export')];
case'video-to-gif':return[metric('GIF segment',`${r(segment,2)} s`),metric('GIF fps',`${r(Math.max(1,param*8),1)}`),metric('Estimated frames',Math.ceil(segment*Math.max(1,param*8))),metric('Palette budget','256 colors maximum per GIF frame'),metric('Loop duration',`${r(segment,2)} s`),metric('Optimization','Crop + reduce fps before reducing dimensions')];
case'crop-resize-video':return[metric('Segment duration',`${r(segment,2)} s`),metric('Frame count @30fps',frames),metric('Scale factor',`${r(speed,2)}×`),metric('Output timeline',`${r(segment,2)} s`),metric('Even-dimension reminder','H.264/WebM encoders often prefer even width/height'),metric('Safe workflow','Crop before resize to avoid extra resampling')];
default:return[metric('Input duration',`${r(duration,3)} s`),metric('Selected range',`${r(start,3)}–${r(end,3)} s`),metric('Segment duration',`${r(segment,3)} s`),metric('Frames @30fps',frames),metric('Processing factor',r(param,3)),metric('Timeline coverage',pct(segment/duration*100))]}}

function isValidUuid(s:string){return/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(s.trim())}
function base64UrlDecode(input:string){try{const s=input.replace(/-/g,'+').replace(/_/g,'/');return decodeURIComponent(Array.from(atob(s),c=>'%'+c.charCodeAt(0).toString(16).padStart(2,'0')).join(''))}catch{return''}}
export function analyzeSecurityDev(id:string,text:string,aux=''):ProMetric[]{const trimmed=text.trim(),ws=words(text);switch(id){
case'checksum-verifier':{const a=trimmed.toLowerCase().replace(/\s/g,''),b=aux.trim().toLowerCase().replace(/\s/g,'');return[metric('Normalized A length',a.length),metric('Normalized B length',b.length),metric('Hex-like A',/^[0-9a-f]+$/.test(a)?'Yes':'No'),metric('Hex-like B',/^[0-9a-f]+$/.test(b)?'Yes':'No'),metric('Exact normalized match',a&&b&&a===b?'Yes':'No'),metric('Likely algorithm by length',a.length===64?'SHA-256':a.length===40?'SHA-1':a.length===32?'MD5/other 128-bit':'Unknown') ]}
case'hmac-generator':return[metric('Message bytes',utf8(text)),metric('Key bytes',utf8(aux)),metric('Message entropy',r(entropy(text),1)),metric('Key entropy (empirical)',r(entropy(aux),1)),metric('Recommended digest','SHA-256 or stronger'),metric('Verification rule','Compare MACs in constant time in security-sensitive code')];
case'text-encryptor':case'file-encryptor':return[metric('Plaintext/sample bytes',utf8(text)),metric('Passphrase characters',graphemes(aux).length),metric('Passphrase entropy estimate',r(entropy(aux),1)),metric('Authenticated-encryption reminder','Use AEAD such as AES-GCM; do not encrypt without authentication'),metric('Salt rule','Unique random salt for password-based KDF'),metric('Nonce rule','Never reuse a nonce with the same key')];
case'password-strength-checker':{const chars=graphemes(trimmed),classes=[/[a-z]/.test(trimmed),/[A-Z]/.test(trimmed),/\d/.test(trimmed),/[^\p{L}\p{N}]/u.test(trimmed)].filter(Boolean).length;return[metric('Graphemes',chars.length),metric('Character classes',classes),metric('Unique graphemes',unique(chars)),metric('Empirical entropy',`${r(entropy(trimmed),1)} bits`),metric('Repeated-run risk',/(.)\1{2,}/u.test(trimmed)?'Detected':'No obvious triple repeat'),metric('Recommendation','Prefer long randomly generated passwords/passphrases over composition tricks') ]}
case'pii-pattern-redactor':{const emails=trimmed.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g)||[],phones=trimmed.match(/\+?\d[\d ()-]{7,}\d/g)||[],ips=trimmed.match(/\b(?:\d{1,3}\.){3}\d{1,3}\b/g)||[];return[metric('Emails',emails.length),metric('Phone-like values',phones.length),metric('IPv4-like values',ips.length),metric('Unique sensitive candidates',unique([...emails,...phones,...ips])),metric('False-positive warning','Pattern matching cannot determine whether a value is truly personal data'),metric('Redaction policy','Prefer reversible review before destructive export') ]}
case'uuid-generator':{const valid=isValidUuid(trimmed),version=valid?trimmed[14]:'—',variant=valid?trimmed[19]:'—';return[metric('Valid canonical UUID',valid?'Yes':'No'),metric('Version nibble',version),metric('Variant nibble',variant),metric('Lowercase canonical',valid?trimmed.toLowerCase():'—'),metric('128-bit hex digits',valid?32:0),metric('Uniqueness note','Random UUID collision probability is tiny but not zero') ]}
case'ulid-generator':{const valid=/^[0-9A-HJKMNP-TV-Z]{26}$/i.test(trimmed);let time='—';if(valid){const alphabet='0123456789ABCDEFGHJKMNPQRSTVWXYZ';let n=0;for(const ch of trimmed.slice(0,10).toUpperCase())n=n*32+alphabet.indexOf(ch);time=new Date(n).toISOString()}return[metric('Valid ULID shape',valid?'Yes':'No'),metric('Timestamp',time),metric('Sortable prefix',valid?trimmed.slice(0,10):'—'),metric('Random suffix chars',valid?16:0),metric('Case-insensitive input',valid?'Supported shape':'—'),metric('Ordering note','ULIDs sort by millisecond timestamp, not by generation order within the same millisecond') ]}
case'jwt-decoder':{const parts=trimmed.split('.'),payload=parts.length>=2?safeJson(base64UrlDecode(parts[1])):null;const exp=payload?.exp?new Date(payload.exp*1000):null;return[metric('Segments',parts.length),metric('Payload JSON',payload?'Valid':'Invalid/unavailable'),metric('Issuer',payload?.iss||'—'),metric('Subject',payload?.sub||'—'),metric('Expiration',exp?exp.toISOString():'—'),metric('Expired?',exp?exp.getTime()<Date.now()?'Yes':'No':'Unknown','Decoding does not verify the signature.') ]}
case'unix-timestamp-converter':{const n=Number(trimmed);const ms=Math.abs(n)<1e12?n*1000:n;const d=Number.isFinite(ms)?new Date(ms):null;return[metric('Interpreted unit',Math.abs(n)<1e12?'seconds':'milliseconds'),metric('UTC ISO',d&&!Number.isNaN(d.getTime())?d.toISOString():'Invalid'),metric('Local',d&&!Number.isNaN(d.getTime())?d.toLocaleString():'Invalid'),metric('Seconds',Number.isFinite(ms)?Math.trunc(ms/1000):'—'),metric('Milliseconds',Number.isFinite(ms)?Math.trunc(ms):'—'),metric('Offset from now',Number.isFinite(ms)?`${r((ms-Date.now())/86400000,2)} days`:'—') ]}
case'number-base-converter':{const n=Number.parseInt(trimmed||'0',Number(aux)||10);return[metric('Parsed decimal',Number.isFinite(n)?n:'Invalid'),metric('Binary',Number.isFinite(n)?Math.trunc(n).toString(2):'—'),metric('Octal',Number.isFinite(n)?Math.trunc(n).toString(8):'—'),metric('Hex',Number.isFinite(n)?Math.trunc(n).toString(16).toUpperCase():'—'),metric('Bit length',Number.isFinite(n)?Math.max(1,Math.abs(Math.trunc(n)).toString(2).length):0),metric('Signed note','Negative values use a sign here, not two’s-complement encoding') ]}
case'text-hex-converter':{const bytes=new TextEncoder().encode(text);return[metric('UTF-8 bytes',bytes.length),metric('Unicode code points',Array.from(text).length),metric('Graphemes',graphemes(text).length),metric('Hex preview',[...bytes.slice(0,16)].map(x=>x.toString(16).padStart(2,'0')).join(' ')),metric('ASCII-only?',bytes.every(x=>x<128)?'Yes':'No'),metric('Round-trip rule','Decode bytes as UTF-8, not one byte per JavaScript character') ]}
case'html-entity-converter':{const named=(text.match(/&[a-zA-Z][a-zA-Z0-9]+;/g)||[]).length,numeric=(text.match(/&#(?:x[0-9a-fA-F]+|\d+);/g)||[]).length,raw=(text.match(/[<>&"']/g)||[]).length;return[metric('Named entities',named),metric('Numeric entities',numeric),metric('Raw HTML-sensitive chars',raw.length),metric('Ampersands',raw.filter(x=>x==='&').length),metric('UTF-8 bytes',utf8(text)),metric('Double-encode warning',/&amp;(?:amp|lt|gt|quot|#)/i.test(text)?'Possible':'No obvious signal') ]}
case'cron-expression-helper':{const fields=trimmed.split(/\s+/);return[metric('Fields',fields.length),metric('Common 5-field shape',fields.length===5?'Yes':'No'),metric('Minute field',fields[0]||'—'),metric('Hour field',fields[1]||'—'),metric('Day/month fields',fields.slice(2,4).join(' ')||'—'),metric('Dialect warning','Cron semantics differ across Unix, Quartz, cloud schedulers and libraries') ]}
case'toml-formatter':{const tables=(text.match(/^\s*\[\[?.+?\]\]?\s*$/gm)||[]).length,keys=(text.match(/^\s*[A-Za-z0-9_."'-]+\s*=/gm)||[]).length;return[metric('Table headers',tables),metric('Assignments',keys),metric('Comment lines',lsCount(text,'#')),metric('Multiline strings',(text.match(/'''|"""/g)||[]).length),metric('Duplicate-key caution','Semantic duplicate detection requires a TOML parser'),metric('UTF-8 bytes',utf8(text)) ]}
case'jsonpath-tester':{const json=safeJson(text),path=aux.trim();return[metric('JSON input',json?'Valid':'Invalid'),metric('Path',path||'—'),metric('Root marker',path.startsWith('$')?'Present':'Missing'),metric('Wildcards',(path.match(/\*/g)||[]).length),metric('Recursive descent',(path.match(/\.\./g)||[]).length),metric('Portability note','JSONPath dialects differ; test the target runtime') ]}
case'base-encoding-converter':case'file-base64-converter':return[metric('Input characters',graphemes(text).length),metric('UTF-8 bytes',utf8(text)),metric('Base64 encoded length',Math.ceil(utf8(text)/3)*4),metric('Base64 overhead',pct(utf8(text)?(Math.ceil(utf8(text)/3)*4/utf8(text)-1)*100:0)),metric('Hex encoded length',utf8(text)*2),metric('Transport note','Base encodings are reversible representations, not encryption')];
case'cidr-subnet-calculator':{const m=trimmed.match(/^(\d{1,3}(?:\.\d{1,3}){3})\/(\d{1,2})$/),prefix=m?Number(m[2]):NaN,hosts=Number.isFinite(prefix)&&prefix<=32?2**(32-prefix):0;return[metric('IPv4 CIDR shape',m&&prefix<=32?'Valid':'Invalid'),metric('Prefix',Number.isFinite(prefix)?prefix:'—'),metric('Addresses',hosts||'—'),metric('Traditional usable hosts',hosts>=2?Math.max(0,hosts-2):hosts),metric('Netmask hex',Number.isFinite(prefix)?`0x${hex(prefix===0?0:(0xffffffff<<(32-prefix))>>>0).padStart(8,'0')}`:'—'),metric('IPv6 note','IPv6 subnet sizing uses 128-bit prefixes and different host conventions') ]}
case'user-agent-parser':return[metric('UA characters',trimmed.length),metric('Mozilla token',/Mozilla\//i.test(trimmed)?'Yes':'No'),metric('Chromium family',/(Chrome|Chromium|Edg)\//i.test(trimmed)?'Likely':'No'),metric('Firefox family',/Firefox\//i.test(trimmed)?'Likely':'No'),metric('Mobile token',/Mobile|Android|iPhone|iPad/i.test(trimmed)?'Present':'Absent'),metric('Reliability warning','User-Agent strings can be frozen, reduced or spoofed')];
case'utm-link-builder':{let u:URL|null=null;try{u=new URL(trimmed)}catch{}const params=u?[...u.searchParams.keys()]:[];return[metric('Valid absolute URL',u?'Yes':'No'),metric('Existing query keys',params.length),metric('utm_source',u?.searchParams.get('utm_source')||'—'),metric('utm_medium',u?.searchParams.get('utm_medium')||'—'),metric('utm_campaign',u?.searchParams.get('utm_campaign')||'—'),metric('Fragment preserved',u?.hash?'Yes':'No') ]}
case'robots-txt-builder':return[metric('User-agent directives',(text.match(/^\s*User-agent\s*:/gim)||[]).length),metric('Allow rules',(text.match(/^\s*Allow\s*:/gim)||[]).length),metric('Disallow rules',(text.match(/^\s*Disallow\s*:/gim)||[]).length),metric('Sitemap directives',(text.match(/^\s*Sitemap\s*:/gim)||[]).length),metric('Unknown lines',lines(text).filter(x=>x.trim()&&!/^\s*(#|User-agent:|Allow:|Disallow:|Sitemap:|Crawl-delay:)/i.test(x)).length),metric('Scope note','robots.txt is crawl guidance, not access control')];
case'sitemap-xml-builder':return[metric('<url> entries',(text.match(/<url(?:\s|>)/g)||[]).length),metric('<loc> entries',(text.match(/<loc>/g)||[]).length),metric('<lastmod> entries',(text.match(/<lastmod>/g)||[]).length),metric('XML declaration',/^\s*<\?xml/i.test(text)?'Present':'Absent'),metric('Likely sitemap root',/<urlset[\s>]/.test(text)?'Yes':'No'),metric('Validation note','Production sitemaps should use absolute canonical URLs')];
case'vcard-generator':return[metric('BEGIN:VCARD',(text.match(/BEGIN:VCARD/gi)||[]).length),metric('FN fields',(text.match(/^FN:/gim)||[]).length),metric('TEL fields',(text.match(/^TEL[;:]/gim)||[]).length),metric('EMAIL fields',(text.match(/^EMAIL[;:]/gim)||[]).length),metric('VERSION',text.match(/^VERSION:(.+)$/im)?.[1]||'—'),metric('Line-folding reminder','Long vCard lines may require RFC-style folding')];
case'totp-generator':return[metric('Secret characters',trimmed.replace(/\s/g,'').length),metric('Base32 shape',/^[A-Z2-7]+=*$/i.test(trimmed.replace(/\s/g,''))?'Likely':'Invalid/other'),metric('30-second counter',Math.floor(Date.now()/30000)),metric('Seconds remaining',30-Math.floor(Date.now()/1000)%30),metric('Clock dependency','TOTP verification requires synchronized clocks'),metric('Secret handling','Do not log or persist TOTP secrets unnecessarily')];
case'css-minifier':case'html-minifier':{const stripped=text.replace(/\/\*[\s\S]*?\*\//g,'').replace(/>\s+</g,'><').replace(/\s+/g,' ').trim();return[metric('Source bytes',utf8(text)),metric('Compact estimate bytes',utf8(stripped)),metric('Estimated reduction',pct(utf8(text)?(1-utf8(stripped)/utf8(text))*100:0)),metric('Comment markers',(text.match(/\/\*/g)||[]).length),metric('Lines',lines(text).length),metric('Safety note','Syntax-aware minification is safer than regex-only transformations') ]}
case'query-string-tool':{const q=trimmed.replace(/^\?/,'');const p=new URLSearchParams(q);return[metric('Parameters',[...p].length),metric('Unique keys',unique([...p.keys()])),metric('Repeated keys',[...new Set([...p.keys()])].filter(k=>p.getAll(k).length>1).length),metric('Empty values',[...p].filter(([,v])=>!v).length),metric('Canonical encoding',p.toString()),metric('Order note','Some servers treat parameter order/repetition as meaningful') ]}
case'semver-comparator':{const parse=(s:string)=>s.trim().replace(/^v/,'').split('-')[0].split('.').map(Number);const a=parse(trimmed),b=parse(aux);const cmp=[0,1,2].map(i=>(a[i]||0)-(b[i]||0)).find(x=>x!==0)||0;return[metric('A normalized',a.slice(0,3).join('.')),metric('B normalized',b.slice(0,3).join('.')),metric('Core comparison',cmp===0?'Equal':cmp<0?'A < B':'A > B'),metric('A prerelease',trimmed.includes('-')?'Yes':'No'),metric('B prerelease',aux.includes('-')?'Yes':'No'),metric('SemVer caveat','Full SemVer precedence must compare prerelease identifiers, not just core numbers') ]}
case'chmod-calculator':{const n=/^[0-7]{3,4}$/.test(trimmed)?trimmed.slice(-3):'';const sym=n?[...n].map(d=>{const x=Number(d);return`${x&4?'r':'-'}${x&2?'w':'-'}${x&1?'x':'-'}`}).join(''): '—';return[metric('Octal mode',n||'Invalid'),metric('Symbolic mode',sym),metric('Owner',n?n[0]:'—'),metric('Group',n?n[1]:'—'),metric('Other',n?n[2]:'—'),metric('Security reminder','Avoid world-writable permissions unless explicitly required') ]}
case'http-header-parser':{const rows=lines(text).filter(x=>x.includes(':')),names=rows.map(x=>x.split(':',1)[0].trim().toLowerCase());return[metric('Header lines',rows.length),metric('Unique header names',unique(names)),metric('Duplicate names',names.length-unique(names)),metric('Content-Type',rows.find(x=>/^content-type:/i.test(x))?.split(':').slice(1).join(':').trim()||'—'),metric('Cache-Control',rows.find(x=>/^cache-control:/i.test(x))?.split(':').slice(1).join(':').trim()||'—'),metric('Header-name casing','HTTP field names are case-insensitive') ]}
case'mime-type-lookup':{const ext=trimmed.toLowerCase().replace(/^\./,'');const common:Record<string,string>={json:'application/json',html:'text/html',css:'text/css',js:'text/javascript',png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',svg:'image/svg+xml',pdf:'application/pdf',zip:'application/zip',mp3:'audio/mpeg',mp4:'video/mp4',webm:'video/webm'};return[metric('Extension',ext||'—'),metric('Known common MIME',common[ext]||'Unknown in compact reference'),metric('Category',(common[ext]||'').split('/')[0]||'—'),metric('Compressibility',/^(text\/|application\/(json|javascript|xml))/.test(common[ext]||'')?'Usually':'Depends'),metric('Sniffing warning','Do not trust filename extensions for security decisions'),metric('HTTP rule','Set explicit Content-Type and consider nosniff') ]}
case'dotenv-formatter':{const entries=lines(text).filter(x=>/^\s*(?:export\s+)?[A-Za-z_][A-Za-z0-9_]*\s*=/.test(x)),keys=entries.map(x=>x.replace(/^\s*export\s+/,'').split('=')[0].trim());return[metric('Assignments',entries.length),metric('Unique keys',unique(keys)),metric('Duplicate keys',keys.length-unique(keys)),metric('Comments',lines(text).filter(x=>/^\s*#/.test(x)).length),metric('Likely secret keys',keys.filter(k=>/(secret|token|password|key)/i.test(k)).length),metric('Export warning','Do not include production secrets in screenshots or shared files') ]}
case'meta-tags-generator':case'open-graph-generator':{const title=text.match(/<title>([\s\S]*?)<\/title>/i)?.[1]||'',desc=text.match(/<meta[^>]+name=["']description["'][^>]+content=["']([^"']*)/i)?.[1]||'';return[metric('Title length',graphemes(title).length),metric('Description length',graphemes(desc).length),metric('Canonical tag',/<link[^>]+rel=["']canonical/i.test(text)?'Present':'Missing'),metric('Open Graph title',/property=["']og:title/i.test(text)?'Present':'Missing'),metric('Open Graph image',/property=["']og:image/i.test(text)?'Present':'Missing'),metric('Robots meta',/name=["']robots/i.test(text)?'Present':'Missing') ]}
case'css-clamp-calculator':{const nums=parseNums(`${text} ${aux}`);const min=nums[0]??16,preferred=nums[1]??2,max=nums[2]??32;return[metric('Minimum',`${min}px`),metric('Preferred',`${preferred}vw`),metric('Maximum',`${max}px`),metric('CSS',`clamp(${min}px, ${preferred}vw, ${max}px)`),metric('Order valid',min<=max?'Yes':'No'),metric('Accessibility reminder','Do not prevent text zoom; verify at 200% zoom') ]}
case'html-table-generator':{const rowsCount=(text.match(/<tr[\s>]/gi)||[]).length,cells=(text.match(/<(td|th)[\s>]/gi)||[]).length;return[metric('Rows',rowsCount),metric('Cells',cells),metric('Header cells',(text.match(/<th[\s>]/gi)||[]).length),metric('Caption',/<caption[\s>]/i.test(text)?'Present':'Missing'),metric('Average cells/row',r(rowsCount?cells/rowsCount:0,2)),metric('Accessibility rule','Use <th scope> and a caption/accessible name for data tables') ]}
case'csr-decoder':return[metric('PEM header',/BEGIN CERTIFICATE REQUEST/.test(text)?'Present':'Missing'),metric('Base64 body chars',text.replace(/-----[^-]+-----|\s/g,'').length),metric('Likely PKCS#10 PEM',/BEGIN (?:NEW )?CERTIFICATE REQUEST/.test(text)?'Yes':'No'),metric('Private key included?',/PRIVATE KEY/.test(text)?'Danger — remove it':'No'),metric('Verification note','A CSR parser should verify structure and signature before trusting fields'),metric('Privacy note','CSRs are often public; private keys never are')];
case'json-ld-generator':{const j=safeJson(text);return[metric('Valid JSON',j?'Yes':'No'),metric('@context',j?.['@context']||'—'),metric('@type',j?.['@type']||'—'),metric('Top-level properties',j&&typeof j==='object'?Object.keys(j).length:0),metric('JSON-LD context present',j?.['@context']?'Yes':'No'),metric('Search feature note','Eligibility depends on schema type and search-engine requirements') ]}
case'serp-snippet-preview':return[metric('Title characters',graphemes(text).length),metric('Description characters',graphemes(aux).length),metric('Title heuristic',graphemes(text).length>=30&&graphemes(text).length<=65?'Common range':'Review length'),metric('Description heuristic',graphemes(aux).length>=70&&graphemes(aux).length<=170?'Common range':'Review length'),metric('Pixel-width caveat','Search engines truncate by rendered width and context, not a fixed character count'),metric('Content rule','Write for relevance; snippet display is not guaranteed')];
case'hreflang-generator':{const entries=lines(text).filter(x=>x.trim()),codes=entries.map(x=>x.split(/[\s,]+/)[0]);return[metric('Locale entries',entries.length),metric('Unique locale codes',unique(codes)),metric('x-default',codes.includes('x-default')?'Present':'Missing'),metric('Duplicate locales',codes.length-unique(codes)),metric('BCP 47-like shapes',codes.filter(x=>/^[a-z]{2,3}(?:-[A-Z]{2})?$|^x-default$/.test(x)).length),metric('Reciprocity reminder','Each localized page should reference itself and its alternates consistently') ]}
default:return[metric('Characters',graphemes(text).length),metric('Words',ws.length),metric('UTF-8 bytes',utf8(text)),metric('Lines',lines(text).length),metric('Aux input bytes',utf8(aux)),metric('Entropy',r(entropy(text),1))]}}
function lsCount(text:string,prefix:string){return lines(text).filter(x=>x.trim().startsWith(prefix)).length}

export function analyzeMathData(id:string,a:number,b:number,c:number,n:number):ProMetric[]{a=Number(a);b=Number(b);c=Number(c);n=Math.max(1,Math.round(n));switch(id){
case'combinations-permutations-calculator':{const N=Math.max(0,Math.round(a)),K=Math.max(0,Math.min(N,Math.round(b))),comb=choose(N,K),perm=comb*factorial(K);return[metric('n',N),metric('k',K),metric('n choose k',comb),metric('nPk',perm),metric('Complement combination',choose(N,N-K)),metric('Probability denominator if equiprobable',comb)]}
case'normal-distribution-calculator':{const z=(a-b)/Math.max(Math.abs(c),1e-12),cdf=normalCdf(z);return[metric('z-score',r(z,5)),metric('P(X ≤ x)',r(cdf,7)),metric('P(X > x)',r(1-cdf,7)),metric('Two-sided tail',r(2*Math.min(cdf,1-cdf),7)),metric('Within ±1σ',r(normalCdf(1)-normalCdf(-1),6)),metric('Parameters',`x=${a}, μ=${b}, σ=${c}`)]}
case'gcd-lcm-prime-factorization':{const A=Math.trunc(a),B=Math.trunc(b),g=gcd2(A,B),l=A&&B?Math.abs(A*B)/g:0;return[metric('GCD',g),metric('LCM',l),metric('A factors',factorize(A).join(' × ')||'—'),metric('B factors',factorize(B).join(' × ')||'—'),metric('Coprime?',g===1?'Yes':'No'),metric('Identity check',Math.abs(A*B)===g*l?'gcd·lcm = |ab|':'Degenerate zero case') ]}
case'complex-number-calculator':{const re=a,im=b,mag=Math.hypot(re,im),arg=Math.atan2(im,re);return[metric('z',`${re}${im<0?'':'+'}${im}i`),metric('|z|',r(mag,6)),metric('arg(z)',`${r(arg,6)} rad`),metric('Conjugate',`${re}${-im<0?'':'+'}${-im}i`),metric('z²',`${r(re*re-im*im,4)}${2*re*im<0?'':'+'}${r(2*re*im,4)}i`),metric('Polar',`${r(mag,4)}·e^(i${r(arg,4)})`)]}
case'quadratic-solver':{if(a===0)return[metric('Equation','Linear'),metric('Root',b?String(r(-c/b,8)):'Undefined'),metric('Discriminant','—'),metric('Vertex','—'),metric('Axis','—'),metric('Factorability','—')];const d=b*b-4*a*c,x=-b/(2*a),y=a*x*x+b*x+c;return[metric('Discriminant',r(d,8)),metric('Root type',d>0?'Two real':d===0?'Repeated real':'Complex conjugate'),metric('Root 1',d>=0?r((-b+Math.sqrt(d))/(2*a),8):`${r(-b/(2*a),6)} + ${r(Math.sqrt(-d)/(2*a),6)}i`),metric('Root 2',d>=0?r((-b-Math.sqrt(d))/(2*a),8):`${r(-b/(2*a),6)} - ${r(Math.sqrt(-d)/(2*a),6)}i`),metric('Vertex',`(${r(x,6)}, ${r(y,6)})`),metric('Axis of symmetry',`x = ${r(x,6)}`)]}
case'vector-calculator':{const mag=Math.hypot(a,b,c),unit=mag?[a/mag,b/mag,c/mag]:[0,0,0];return[metric('Magnitude',r(mag,8)),metric('Unit vector',unit.map(x=>r(x,6)).join(', ')),metric('Dot with (1,1,1)',r(a+b+c,6)),metric('Distance from origin',r(mag,8)),metric('Largest component',Math.max(Math.abs(a),Math.abs(b),Math.abs(c))),metric('Dimension','3D') ]}
case'polynomial-graph-explorer':{const x=n/10,y=a*x*x+b*x+c,vertex=a?[-b/(2*a),c-b*b/(4*a)]:[0,c];return[metric('Sample x',x),metric('f(x)',r(y,8)),metric('Quadratic vertex',a?`(${r(vertex[0],4)}, ${r(vertex[1],4)})`:'Not quadratic'),metric('Opening',a>0?'Up':a<0?'Down':'Linear/constant'),metric('y-intercept',c),metric('Derivative at sample',r(2*a*x+b,8))]}
case'binomial-distribution-calculator':{const N=n,p=Math.min(1,Math.max(0,a)),k=Math.max(0,Math.min(N,Math.round(b))),pmf=choose(N,k)*p**k*(1-p)**(N-k);let cdf=0;for(let i=0;i<=k;i++)cdf+=choose(N,i)*p**i*(1-p)**(N-i);return[metric('P(X = k)',r(pmf,8)),metric('P(X ≤ k)',r(cdf,8)),metric('Mean',r(N*p,5)),metric('Variance',r(N*p*(1-p),5)),metric('Std dev',r(Math.sqrt(N*p*(1-p)),5)),metric('Parameters',`n=${N}, p=${p}, k=${k}`)]}
case'poisson-distribution-calculator':{const lambda=Math.max(0,a),k=Math.max(0,Math.round(b)),pmf=Math.exp(-lambda)*lambda**k/factorial(k);let cdf=0;for(let i=0;i<=k;i++)cdf+=Math.exp(-lambda)*lambda**i/factorial(i);return[metric('P(X = k)',r(pmf,8)),metric('P(X ≤ k)',r(cdf,8)),metric('Mean',lambda),metric('Variance',lambda),metric('Std dev',r(Math.sqrt(lambda),6)),metric('Parameters',`λ=${lambda}, k=${k}`)]}
case'confidence-interval-calculator':{const m=a,s=Math.abs(b),N=n,se=s/Math.sqrt(N),z=Math.abs(c)||1.96;return[metric('Standard error',r(se,6)),metric('Margin',r(z*se,6)),metric('Lower',r(m-z*se,6)),metric('Upper',r(m+z*se,6)),metric('Width',r(2*z*se,6)),metric('Inputs',`mean=${m}, sd=${s}, n=${N}, z=${z}`)]}
case'sample-size-calculator':{const p=Math.min(.999999,Math.max(.000001,a)),margin=Math.abs(b)||.05,z=Math.abs(c)||1.96,raw=z*z*p*(1-p)/(margin*margin);return[metric('Raw sample size',r(raw,2)),metric('Rounded up',Math.ceil(raw)),metric('Assumed proportion',p),metric('Margin',margin),metric('z critical',z),metric('Conservative p=.5',Math.ceil(z*z*.25/(margin*margin)))]}
case't-test-calculator':{const diff=a-b,se=Math.abs(c)||1,t=diff/(se/Math.sqrt(n));return[metric('Difference',r(diff,6)),metric('Standard error of mean',r(se/Math.sqrt(n),6)),metric('t statistic',r(t,6)),metric('Degrees of freedom',n-1),metric('Direction',t>0?'A > B':t<0?'A < B':'Equal means'),metric('Inference note','Exact p-value requires a Student-t CDF; do not substitute a normal CDF for small samples') ]}
case'chi-square-test-calculator':{const observed=[a,b],expected=[c,n],chi=observed.reduce((s,o,i)=>s+(o-expected[i])**2/Math.max(expected[i],1e-12),0);return[metric('χ² contribution total',r(chi,8)),metric('Cell 1 contribution',r((a-c)**2/Math.max(c,1e-12),8)),metric('Cell 2 contribution',r((b-n)**2/Math.max(n,1e-12),8)),metric('Observed total',a+b),metric('Expected total',c+n),metric('Validity note','Expected counts and degrees of freedom determine whether the χ² approximation is appropriate') ]}
case'histogram-generator':case'scatter-plot-generator':case'csv-data-plotter':{const vals=[a,b,c,n].filter(Number.isFinite);return[metric('Sample count',vals.length),metric('Mean',r(mean(vals),6)),metric('Min',Math.min(...vals)),metric('Max',Math.max(...vals)),metric('Range',r(Math.max(...vals)-Math.min(...vals),6)),metric('Std dev',r(std(vals),6))]}
default:return[metric('a',a),metric('b',b),metric('c',c),metric('n',n),metric('Mean',r(mean([a,b,c,n]),4)),metric('Std dev',r(std([a,b,c,n]),4))]}}
function factorial(n:number){n=Math.max(0,Math.floor(n));let out=1;for(let i=2;i<=n;i++)out*=i;return out}
function gcd2(a:number,b:number){a=Math.abs(Math.trunc(a));b=Math.abs(Math.trunc(b));while(b)[a,b]=[b,a%b];return a}
function factorize(n:number){n=Math.abs(Math.trunc(n));const out:number[]=[];for(let p=2;p*p<=n;p++)while(n%p===0){out.push(p);n/=p}if(n>1)out.push(n);return out}

export function analyzeDocumentTime(id:string,text:string,a:number,b:number):ProMetric[]{const ws=words(text),ls=lines(text).filter(x=>x.trim()),today=new Date();switch(id){
case'checklist':{const items=ls.filter(x=>/^\s*[-*]?\s*\[[ xX]\]/.test(x)),done=items.filter(x=>/\[[xX]\]/.test(x)).length;return[metric('Checklist items',items.length),metric('Completed',done),metric('Remaining',items.length-done),metric('Completion',pct(items.length?done/items.length*100:0)),metric('Longest item words',Math.max(0,...items.map(x=>words(x).length))),metric('Empty/ambiguous lines',ls.length-items.length)]}
case'teleprompter':{const wpm=Math.max(60,a||150),mins=ws.length/wpm;return[metric('Words',ws.length),metric('Reading speed',`${wpm} wpm`),metric('Estimated runtime',`${r(mins,2)} min`),metric('Words per 30 sec',Math.round(wpm/2)),metric('Paragraphs',text.split(/\n\s*\n/).filter(x=>x.trim()).length),metric('Cue density',pct(ws.length?ls.filter(x=>/^\s*\[.*\]\s*$/.test(x)).length/ws.length*100:0))]}
case'invoice-generator':case'quote-estimate-generator':case'receipt-generator':{const subtotal=Math.max(0,a),tax=Math.max(0,b),total=subtotal*(1+tax/100);return[metric('Subtotal',moneyEUR(subtotal)),metric('Tax rate',pct(tax)),metric('Tax',moneyEUR(total-subtotal)),metric('Grand total',moneyEUR(total)),metric('Line-item text lines',ls.length),metric('Recordkeeping note',id==='quote-estimate-generator'?'Quotes should state validity and assumptions':'Keep immutable copies of issued documents') ]}
case'email-signature-generator':return[metric('Characters',graphemes(text).length),metric('Lines',ls.length),metric('Links',(text.match(/https?:\/\//g)||[]).length),metric('Email addresses',(text.match(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g)||[]).length),metric('Phone-like values',(text.match(/\+?\d[\d ()-]{7,}\d/g)||[]).length),metric('Deliverability note','Avoid oversized images, tracking dependencies and excessive HTML')];
case'printable-label-maker':{const width=Math.max(1,a),height=Math.max(1,b),area=width*height;return[metric('Label size',`${r(width,2)}×${r(height,2)} mm`),metric('Area',`${r(area,2)} mm²`),metric('300dpi pixels',`${Math.round(width/25.4*300)}×${Math.round(height/25.4*300)}`),metric('600dpi pixels',`${Math.round(width/25.4*600)}×${Math.round(height/25.4*600)}`),metric('Text lines',ls.length),metric('Print reminder','Test one physical sheet before a large batch') ]}
case'printable-calendar-generator':case'weekly-schedule-builder':{const blocks=ls.length,hours=Math.max(1,a),total=blocks*hours;return[metric('Entries',blocks),metric('Hours/entry scenario',hours),metric('Scheduled hours',total),metric('Average words/entry',r(mean(ls.map(x=>words(x).length)),1)),metric('Today',today.toISOString().slice(0,10)),metric('Conflict rule','Leave explicit transition/buffer time between fixed commitments') ]}
case'resume-builder':{const bullets=ls.filter(x=>/^\s*[-•*]/.test(x)),numbers=(text.match(/\b\d+(?:[.,]\d+)?%?\b/g)||[]).length;return[metric('Words',ws.length),metric('Achievement bullets',bullets.length),metric('Bullets with numbers',bullets.filter(x=>/\d/.test(x)).length),metric('Quantified values',numbers),metric('Average bullet words',r(mean(bullets.map(x=>words(x).length)),1)),metric('Scanning note','Lead bullets with outcome + action; verify every claim') ]}
case'countdown-to-date':case'birthday-age-calculator':{const target=new Date(text.trim()||today.toISOString().slice(0,10));const ms=target.getTime()-today.getTime(),days=Math.trunc(ms/86400000);return[metric('Target',Number.isNaN(target.getTime())?'Invalid':target.toISOString().slice(0,10)),metric('Calendar-day delta',Number.isNaN(days)?'—':days),metric('Weeks',Number.isNaN(days)?'—':r(days/7,2)),metric('Approx months',Number.isNaN(days)?'—':r(days/30.436875,2)),metric('Direction',days>0?'Future':days<0?'Past':'Today'),metric('Timezone note','Calendar dates and instants are different concepts') ]}
case'week-number-weekday':{const d=new Date(text.trim()||today.toISOString().slice(0,10));return[metric('Date',Number.isNaN(d.getTime())?'Invalid':d.toISOString().slice(0,10)),metric('Weekday',Number.isNaN(d.getTime())?'—':d.toLocaleDateString(undefined,{weekday:'long'})),metric('Day of year',Number.isNaN(d.getTime())?'—':dayOfYear(d)),metric('Quarter',Number.isNaN(d.getTime())?'—':`Q${Math.floor(d.getUTCMonth()/3)+1}`),metric('Leap year',Number.isNaN(d.getTime())?'—':isLeap(d.getUTCFullYear())?'Yes':'No'),metric('ISO caution','ISO week-year can differ from calendar year near New Year') ]}
case'time-duration-calculator':{const start=Math.max(0,a),end=Math.max(0,b),diff=end-start;return[metric('Start',`${r(start,3)} h`),metric('End',`${r(end,3)} h`),metric('Signed duration',`${r(diff,3)} h`),metric('Minutes',r(diff*60,2)),metric('Seconds',r(diff*3600,0)),metric('Overnight alternative',`${r(diff<0?diff+24:diff,3)} h`)]}
default:return[metric('Words',ws.length),metric('Lines',ls.length),metric('Numeric A',a),metric('Numeric B',b),metric('UTF-8 bytes',utf8(text)),metric('Today',today.toISOString().slice(0,10))]}}
function moneyEUR(n:number){return new Intl.NumberFormat(undefined,{style:'currency',currency:'EUR'}).format(n)}
function dayOfYear(d:Date){const start=Date.UTC(d.getUTCFullYear(),0,0);return Math.floor((Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-start)/86400000)}
function isLeap(y:number){return y%4===0&&(y%100!==0||y%400===0)}

export function analyzeSubtitle(id:string,text:string,fps=25):ProMetric[]{const timeRx=/(\d{1,2}):(\d{2}):(\d{2})[,.](\d{3})/g;const times=[...text.matchAll(timeRx)].map(m=>(Number(m[1])*3600+Number(m[2])*60+Number(m[3]))*1000+Number(m[4]));const cues=Math.floor(times.length/2),durations:Array<number>=[];for(let i=0;i+1<times.length;i+=2)durations.push((times[i+1]-times[i])/1000);const textOnly=text.replace(/\d{1,2}:\d{2}:\d{2}[,.]\d{3}\s*--?>\s*\d{1,2}:\d{2}:\d{2}[,.]\d{3}/g,'').replace(/^\d+$/gm,'').trim(),w=words(textOnly).length,total=durations.reduce((a,b)=>a+Math.max(0,b),0);switch(id){
case'subtitle-time-shifter':return[metric('Cues detected',cues),metric('First timestamp',times[0]!==undefined?`${r(times[0]/1000,3)} s`:'—'),metric('Shift scenario',`${r(1000/fps,3)} ms (1 frame)`),metric('Negative-time risk',times[0]!==undefined&&times[0]<1000/fps?'Yes for −1 frame':'No'),metric('Last timestamp',times.length?`${r(times.at(-1)!/1000,3)} s`:'—'),metric('Frame rate',fps)];
case'subtitle-frame-rate-converter':return[metric('Cues detected',cues),metric('Source fps',fps),metric('24→25 timing factor',r(24/25,6)),metric('25→23.976 factor',r(25/23.976,6)),metric('Last timestamp',times.length?`${r(times.at(-1)!/1000,3)} s`:'—'),metric('Rule','Frame-rate conversion scales timestamps; a constant offset is a different operation')];
case'subtitle-reading-speed-analyzer':return[metric('Cues detected',cues),metric('Subtitle words',w),metric('Total on-screen seconds',r(total,2)),metric('Average words/second',r(total?w/total:0,3)),metric('Mean cue duration',r(mean(durations),3)),metric('Short cues <1s',durations.filter(x=>x>0&&x<1).length)];
case'subtitle-cleaner-validator':return[metric('Cues detected',cues),metric('Negative durations',durations.filter(x=>x<0).length),metric('Zero durations',durations.filter(x=>x===0).length),metric('Overlaps',countOverlaps(times)),metric('Very long cues >10s',durations.filter(x=>x>10).length),metric('Empty-looking cue blocks',(text.match(/-->[^\n]*\n\s*(?:\n|$)/g)||[]).length)];
case'subtitle-merger':case'subtitle-splitter':return[metric('Cues detected',cues),metric('Timeline start',times.length?`${r(times[0]/1000,2)} s`:'—'),metric('Timeline end',times.length?`${r(times.at(-1)!/1000,2)} s`:'—'),metric('Midpoint split',times.length?`${r((times[0]+times.at(-1)!)/2000,2)} s`:'—'),metric('Words',w),metric('Average words/cue',r(cues?w/cues:0,2))];
default:return[metric('Cues detected',cues),metric('Timestamps',times.length),metric('Words',w),metric('Mean cue duration',r(mean(durations),3)),metric('Overlaps',countOverlaps(times)),metric('FPS reference',fps)]}}
function countOverlaps(times:number[]){let n=0;for(let i=1;i+1<times.length;i+=2)if(times[i]>times[i+1])n++;return n}

export function analyzeRestoration(id:string,w:number,h:number,strength:number):ProMetric[]{const px=Math.max(1,w*h),s=Math.max(0,Math.min(100,strength));switch(id){
case'object-remover':return[metric('Image pixels',px.toLocaleString()),metric('Mask strength',pct(s)),metric('Recommended feather',`${r(Math.max(1,Math.min(w,h)*.005),1)} px`),metric('Context margin',`${r(Math.max(8,Math.min(w,h)*.03),1)} px`),metric('Patch QA','Inspect repeated textures and straight edges at 100% zoom'),metric('Non-destructive rule','Keep original and mask separately')];
case'old-photo-restorer':return[metric('Image pixels',px.toLocaleString()),metric('Restoration strength',pct(s)),metric('Pass 1','Dust/scratch cleanup'),metric('Pass 2','Contrast and tone recovery'),metric('Pass 3','Selective sharpness — avoid inventing facial detail'),metric('Archival rule','Keep an untouched master and document edits')];
case'perspective-corrector':return[metric('Source ratio',r(w/h,5)),metric('Pixels',px.toLocaleString()),metric('Correction strength',pct(s)),metric('Corner QA','Verify formerly parallel architectural/text edges'),metric('Resampling note','Perspective warps require resampling; avoid repeated transforms'),metric('Crop reserve',`${r(Math.max(w,h)*.03,1)} px suggested` )];
case'auto-deskew-image':return[metric('Source dimensions',`${w}×${h}`),metric('Search range',`±${r(Math.max(1,s/10),1)}°`),metric('Fine step',`${r(Math.max(.05,s/100),2)}°`),metric('Pixel count',px.toLocaleString()),metric('QA target','Text baselines and vertical margins should agree after correction'),metric('Crop warning','Rotation can clip corners without canvas expansion')];
case'red-eye-remover':return[metric('Image pixels',px.toLocaleString()),metric('Correction strength',pct(s)),metric('Detection prior','Constrain correction to eye-sized, red-dominant regions'),metric('Skin-tone guard','Do not desaturate surrounding skin/lips'),metric('Catchlight guard','Preserve natural eye highlights'),metric('QA','Compare both eyes at 100–200% zoom')];
default:return[metric('Dimensions',`${w}×${h}`),metric('Pixels',px.toLocaleString()),metric('Strength',pct(s)),metric('QA','Compare before/after at 100% zoom'),metric('Master','Keep original'),metric('Export','Use lossless intermediate when possible')]}}

export function analyzePlanning(id:string,text:string,a:number,b:number):ProMetric[]{if(id==='eisenhower-matrix'){const tasks=lines(text).filter(x=>x.trim()),urgent=Math.max(0,Math.min(tasks.length,Math.round(a))),important=Math.max(0,Math.min(tasks.length,Math.round(b)));return[metric('Tasks',tasks.length),metric('Urgent scenario',urgent),metric('Important scenario',important),metric('Do-now capacity',Math.min(urgent,important)),metric('Delegation candidates',Math.max(0,urgent-important)),metric('Planning rule','Protect scheduled important/not-urgent work from being displaced by low-value urgency')]}const swatches=Math.max(2,Math.round(a)),angle=((b%360)+360)%360;return[metric('Palette size',swatches),metric('Base hue',`${angle}°`),metric('Complement',`${(angle+180)%360}°`),metric('Triad',`${angle}° / ${(angle+120)%360}° / ${(angle+240)%360}°`),metric('Text notes words',words(text).length),metric('Accessibility rule','Test intended foreground/background pairs, not colors in isolation')]}
