import{STRICT_B_TO_S_TARGETS}from'./manifest';
export type StrictBFamily='calculator'|'visual'|'media'|'device-network'|'file-data'|'text-study'|'security-dev'|'document-time'|'math-data'|'subtitle'|'restoration'|'planning';
const family=(value:string)=>new Set(value.trim().split(/\s+/).filter(Boolean));
const SETS:Record<StrictBFamily,Set<string>>={
visual:family(`aspect-ratio-calculator image-annotator image-collage signature-maker whiteboard meme-maker rotate-flip-image profile-picture-maker blur-pixelate-image social-media-image-resizer favicon-maker image-grid-splitter image-border-frame photo-filters image-compare background-changer transparent-image-maker contact-sheet-maker headshot-cropper svg-optimizer dpi-print-size-calculator color-blindness-simulator css-gradient-generator box-shadow-generator color-palette-generator`),
media:family(`text-to-speech audio-volume-changer audio-speed-changer silence-trimmer audio-equalizer audio-noise-cleanup ringtone-maker audio-pitch-speed-shifter merge-videos video-to-audio add-audio-to-video add-text-to-video video-to-frames video-thumbnail-extractor webcam-video-recorder add-logo-to-video subtitle-burner video-to-gif video-speed-changer crop-resize-video`),
'device-network':family(`speaker-test mouse-test dead-pixel-test display-test device-info gamepad-test tone-generator instrument-tuner internet-speed-test connection-stability-test ipv4-ipv6-test webrtc-leak-test browser-capability-inspector webgl-inspector webgpu-inspector codec-support-tester storage-quota-inspector`),
calculator:family(`unit-price-comparator discount-vat-calculator recipe-scaler fraction-calculator ratio-calculator grade-calculator final-grade-calculator gpa-calculator weighted-average-calculator triangle-calculator circle-calculator probability-calculator savings-goal-calculator roi-calculator retirement-calculator salary-hourly-calculator car-loan-calculator rent-vs-buy-calculator inflation-calculator debt-to-income-calculator fuel-trip-cost-calculator fuel-economy-calculator electricity-cost-calculator appliance-cost-calculator concrete-calculator bmi-calculator bmr-calculator tdee-calculator running-pace-calculator body-fat-calculator one-rep-max-calculator`),
'file-data':family(`pdf-metadata csv-splitter csv-merger file-type-inspector presentation-viewer ebook-reader structured-data-viewer font-viewer docx-metadata-inspector epub-metadata-editor`),
' text-study'.trim() as 'text-study':family(`ngram-analyzer text-pattern-extractor duplicate-phrase-finder text-similarity-checker text-wrapper whitespace-visualizer markdown-to-plain-text cloze-deletion-trainer memorization-trainer self-test-maker study-session-planner`),
'security-dev':family(`checksum-verifier hmac-generator text-encryptor file-encryptor password-strength-checker pii-pattern-redactor uuid-generator ulid-generator jwt-decoder unix-timestamp-converter number-base-converter text-hex-converter html-entity-converter cron-expression-helper toml-formatter jsonpath-tester base-encoding-converter file-base64-converter cidr-subnet-calculator user-agent-parser utm-link-builder robots-txt-builder sitemap-xml-builder vcard-generator totp-generator css-minifier query-string-tool semver-comparator chmod-calculator http-header-parser mime-type-lookup dotenv-formatter html-minifier meta-tags-generator open-graph-generator css-clamp-calculator html-table-generator csr-decoder json-ld-generator serp-snippet-preview hreflang-generator`),
'document-time':family(`checklist teleprompter invoice-generator quote-estimate-generator receipt-generator email-signature-generator printable-label-maker printable-calendar-generator weekly-schedule-builder resume-builder countdown-to-date week-number-weekday time-duration-calculator birthday-age-calculator`),
'math-data':family(`combinations-permutations-calculator normal-distribution-calculator gcd-lcm-prime-factorization complex-number-calculator quadratic-solver vector-calculator polynomial-graph-explorer binomial-distribution-calculator poisson-distribution-calculator confidence-interval-calculator sample-size-calculator t-test-calculator chi-square-test-calculator histogram-generator scatter-plot-generator csv-data-plotter`),
subtitle:family(`subtitle-time-shifter subtitle-resynchronizer subtitle-frame-rate-converter subtitle-cleaner-validator subtitle-merger subtitle-splitter subtitle-reading-speed-analyzer`),
restoration:family(`object-remover old-photo-restorer perspective-corrector auto-deskew-image red-eye-remover`),
planning:family(`color-palette-generator eisenhower-matrix`),
};
const FAMILY_LABEL:Record<StrictBFamily,string>={calculator:'precision scenario lab',visual:'production geometry & quality lab',media:'timeline, bitrate & render lab','device-network':'measurement evidence lab','file-data':'structure & integrity lab','text-study':'corpus & learning analysis lab','security-dev':'protocol & validation lab','document-time':'professional planning & document QA lab','math-data':'statistical verification lab',subtitle:'subtitle timing & QC lab',restoration:'restoration quality-control lab',planning:'decision & design system lab'};
export type StrictBProfile={id:string;family:StrictBFamily;label:string;focus:string};
function humanize(id:string){return id.split('-').map(x=>x==='csv'?'CSV':x==='pdf'?'PDF':x==='jwt'?'JWT':x==='css'?'CSS':x==='html'?'HTML':x==='svg'?'SVG':x==='pwa'?'PWA':x.charAt(0).toUpperCase()+x.slice(1)).join(' ')}
export function getStrictBProfile(id:string):StrictBProfile|undefined{if(!STRICT_B_TO_S_TARGETS.includes(id as never))return undefined;const found=(Object.entries(SETS)as[StrictBFamily,Set<string>][]).find(([,set])=>set.has(id));if(!found)throw new Error(`Missing strict B family for ${id}`);const familyId=found[0];return{id,family:familyId,label:FAMILY_LABEL[familyId],focus:`${humanize(id)} specialist workflow`}}
export const STRICT_B_PROFILES=STRICT_B_TO_S_TARGETS.map(id=>getStrictBProfile(id)!);
