export type PublicMediaEngine='audio'|'video';
export interface PublicMediaTask{id:string;name:string;shortName:string;description:string;keywords:string[];engine:PublicMediaEngine;featured?:boolean;}

export const PUBLIC_MEDIA_TASKS:PublicMediaTask[]=[
  {id:'audio-joiner',name:'Audio Joiner',shortName:'Audio Joiner',description:'Join multiple browser-decodable audio files in sequence and export one WAV locally.',keywords:['join audio','merge audio','combine mp3','audio merger'],engine:'audio',featured:true},
  {id:'audio-to-wav-converter',name:'Audio to WAV Converter',shortName:'Audio to WAV',description:'Convert browser-decodable audio such as MP3, AAC, OGG, WebM, or WAV into standard PCM WAV.',keywords:['audio converter','mp3 to wav','ogg to wav','aac to wav','webm to wav'],engine:'audio',featured:true},
  {id:'audio-volume-changer',name:'Audio Volume Changer',shortName:'Volume Changer',description:'Raise or lower audio gain locally with clipping protection and WAV export.',keywords:['change audio volume','make audio louder','make audio quieter','gain'],engine:'audio'},
  {id:'audio-speed-changer',name:'Audio Speed Changer',shortName:'Audio Speed',description:'Change audio playback speed and export the result locally. This browser-native method changes pitch together with speed.',keywords:['speed up audio','slow down audio','audio playback speed'],engine:'audio'},
  {id:'audio-normalizer',name:'Audio Normalizer',shortName:'Normalize Audio',description:'Normalize peak level to a chosen dB target, optionally remove DC offset, and export WAV.',keywords:['normalize audio','audio peak normalize','loudness gain','dc offset'],engine:'audio',featured:true},
  {id:'silence-trimmer',name:'Silence Trimmer',shortName:'Trim Silence',description:'Detect leading and trailing silence using short-window RMS and export the active audio range.',keywords:['trim silence','remove silence audio','auto trim audio'],engine:'audio',featured:true},
  {id:'audio-equalizer',name:'Audio Equalizer',shortName:'Audio EQ',description:'Apply local low, mid, and high EQ using Web Audio filters and export the processed WAV.',keywords:['audio equalizer','bass treble','audio eq','mid frequencies'],engine:'audio'},
  {id:'reverse-audio',name:'Reverse Audio',shortName:'Reverse Audio',description:'Reverse decoded audio samples locally and export a standard WAV file.',keywords:['reverse audio','play audio backwards','backwards sound'],engine:'audio'},
  {id:'audio-noise-cleanup',name:'Basic Audio Noise Cleanup',shortName:'Noise Cleanup',description:'Apply a speech-friendly high-pass, low-pass, and gentle noise gate locally. This is basic cleanup, not AI source separation.',keywords:['noise reduction','remove hum','audio cleanup','noise gate','speech cleanup'],engine:'audio'},
  {id:'stereo-mono-converter',name:'Stereo ↔ Mono Converter',shortName:'Stereo / Mono',description:'Downmix stereo or multichannel audio to mono, or duplicate mono into stereo, then export WAV.',keywords:['stereo to mono','mono to stereo','audio channels'],engine:'audio'},
  {id:'ringtone-maker',name:'Ringtone Maker',shortName:'Ringtone Maker',description:'Choose a short section, add optional fades, and export a ringtone-ready WAV without uploading audio.',keywords:['ringtone maker','trim ringtone','30 second audio','phone ringtone'],engine:'audio'},
  {id:'audio-pitch-speed-shifter',name:'Audio Pitch & Speed Shifter',shortName:'Pitch / Speed',description:'Transpose audio by semitones using browser-native playback-rate shifting. Pitch and duration change together.',keywords:['pitch changer','transpose audio','semitones','chipmunk voice','lower pitch'],engine:'audio'},

  {id:'merge-videos',name:'Merge Videos',shortName:'Merge Videos',description:'Join multiple browser-decodable videos in sequence with local real-time rendering. Browser codec support determines the output container.',keywords:['merge videos','join videos','combine clips','video merger'],engine:'video',featured:true},
  {id:'video-compressor',name:'Video Compressor',shortName:'Compress Video',description:'Reduce video dimensions and bitrate with a local real-time browser encoder and explicit size estimates.',keywords:['compress video','reduce video size','smaller mp4','video mb'],engine:'video',featured:true},
  {id:'video-converter',name:'Video Converter',shortName:'Video Converter',description:'Convert a browser-decodable video to a MediaRecorder format supported by the current browser, typically WebM or MP4.',keywords:['convert video','mp4 to webm','webm to mp4','video format'],engine:'video',featured:true},
  {id:'video-to-audio',name:'Video to Audio / WAV',shortName:'Video to Audio',description:'Extract the decodable audio track from a video and export lossless PCM WAV locally.',keywords:['video to audio','video to wav','extract audio','mp4 audio'],engine:'video',featured:true},
  {id:'add-audio-to-video',name:'Add Audio to Video',shortName:'Add Audio',description:'Mix an additional browser-decodable audio file with a video during local real-time rendering.',keywords:['add music to video','add audio to video','mix audio video','background music'],engine:'video'},
  {id:'add-text-to-video',name:'Add Text to Video',shortName:'Video Text',description:'Burn a static text caption into a video with local canvas rendering and browser-native encoding.',keywords:['add text to video','caption video','text overlay'],engine:'video'},
  {id:'loop-video',name:'Loop Video',shortName:'Loop Video',description:'Repeat a source clip a chosen number of times and export one locally rendered video.',keywords:['loop video','repeat video','video repeater'],engine:'video'},
  {id:'video-to-frames',name:'Video to Frames',shortName:'Video Frames',description:'Extract evenly spaced still frames from a video and download them together as PNG files in a ZIP.',keywords:['video to frames','extract video frames','video screenshots','frames zip'],engine:'video'},
  {id:'video-thumbnail-extractor',name:'Video Thumbnail Extractor',shortName:'Video Thumbnail',description:'Seek to an exact timestamp and export that video frame as a PNG thumbnail.',keywords:['video thumbnail','extract frame','video screenshot','thumbnail maker'],engine:'video',featured:true},
  {id:'webcam-video-recorder',name:'Webcam Video Recorder',shortName:'Webcam Recorder',description:'Record camera and microphone directly with MediaRecorder and download the browser-supported local recording.',keywords:['webcam recorder','camera recorder','record webcam','video camera test'],engine:'video',featured:true},
  {id:'add-logo-to-video',name:'Add Image / Logo to Video',shortName:'Video Logo',description:'Overlay a local image or logo on a video and export through the browser real-time encoder.',keywords:['add logo to video','watermark video','image overlay video'],engine:'video'},
  {id:'subtitle-burner',name:'Subtitle Burner',shortName:'Burn Subtitles',description:'Parse SRT or WebVTT cues and burn active subtitles into video frames during local rendering.',keywords:['burn subtitles','srt to video','vtt subtitles','hard subtitles'],engine:'video'},
  {id:'video-to-gif',name:'Video to GIF',shortName:'Video to GIF',description:'Sample a short video segment into frames and encode an animated GIF locally with the existing GIF engine.',keywords:['video to gif','mp4 to gif','webm to gif','animated gif'],engine:'video'},
  {id:'video-speed-changer',name:'Video Speed Changer',shortName:'Video Speed',description:'Speed up or slow down video with real-time browser rendering. Captured audio follows browser playback-rate behavior.',keywords:['speed up video','slow motion video','video playback speed'],engine:'video'},
  {id:'crop-resize-video',name:'Crop & Resize Video',shortName:'Crop Video',description:'Crop to common aspect ratios and resize video locally before browser-native export.',keywords:['crop video','resize video','video aspect ratio','vertical video'],engine:'video'},
  {id:'mute-video',name:'Mute Video',shortName:'Mute Video',description:'Remove the source audio track while locally re-encoding the video.',keywords:['mute video','remove audio from video','silent video'],engine:'video'},
  {id:'video-volume-changer',name:'Video Volume Changer',shortName:'Video Volume',description:'Adjust captured source-audio volume while locally rendering a transformed video, when the browser exposes the source audio track.',keywords:['video volume','make video louder','lower video audio'],engine:'video'},
];

export function getPublicMediaTask(id:string|null|undefined){return PUBLIC_MEDIA_TASKS.find(task=>task.id===id);}
